--
-- DBF_TIME_TO_CHAR  (Function) 
--
CREATE OR REPLACE FUNCTION MASTER.DBF_TIME_TO_CHAR(pDate DATE) RETURN VARCHAR2 AS
BEGIN
     IF pDate IS NULL THEN
	   RETURN '''''';
	 ELSE
	   RETURN ''''||TO_CHAR(pDate,'hh24:mi:ss')||'''';
	 END IF;
END;

/

