--
-- GET_NEWKVIT  (Function) 
--
CREATE OR REPLACE FUNCTION MASTER.GET_NEWKVIT 
(OLDDATE# DATE, CIST# VARCHAR2)
RETURN NUMBER AS
NEWKVIT NUMBER;
BEGIN
	 NEWKVIT:=0;
	 
	 SELECT NUM_KVIT INTO NEWKVIT
	 FROM
	  		(SELECT NUM_KVIT
	   		FROM KVIT
	   		WHERE NUM_CIST=CIST# 
	   		AND DATE_KVIT>OLDDATE#
	   		ORDER BY DATE_KVIT)
	 WHERE ROWNUM=1;
	 
	 RETURN NEWKVIT;
END GET_NEWKVIT;

/

