--
-- GET_TARIF_CIST  (Function) 
--
CREATE OR REPLACE FUNCTION MASTER.GET_TARIF_CIST (MNUM_KVIT NUMBER,MVES NUMBER,FIELD_NAME VARCHAR2) RETURN NUMBER IS
SUM_CHISLO NUMBER;
SUM_VES NUMBER;
OTVET NUMBER;
BEGIN
  OTVET:=0;
   SELECT SUM(VES) INTO SUM_VES FROM KVIT WHERE NUM_KVIT=MNUM_KVIT;
   IF FIELD_NAME='TARIF' THEN
      SELECT TARIF INTO SUM_CHISLO FROM KVIT WHERE NUM_KVIT=MNUM_KVIT AND TARIF<>0;    
      OTVET:=ROUND(MVES*(SUM_CHISLO/SUM_VES),2);
   END IF;
   IF FIELD_NAME='DOPTARIF' THEN
      SELECT kvit.TARIF19-kvit.TARIF INTO SUM_CHISLO FROM KVIT WHERE NUM_KVIT=MNUM_KVIT AND TARIF19<>0;    
      OTVET:=ROUND(MVES*(SUM_CHISLO/SUM_VES),2);
   END IF;
   IF FIELD_NAME='TARIF_NDS' THEN
      SELECT TARIF_NDS INTO SUM_CHISLO FROM KVIT WHERE NUM_KVIT=MNUM_KVIT AND TARIF_NDS<>0;    
      OTVET:=ROUND(MVES*(SUM_CHISLO/SUM_VES),2);
   END IF;
   IF FIELD_NAME='TARIF_GUARD' THEN
      SELECT TARIF_GUARD INTO SUM_CHISLO FROM KVIT WHERE NUM_KVIT=MNUM_KVIT AND TARIF_GUARD<>0;    
      OTVET:=ROUND(MVES*(SUM_CHISLO/SUM_VES),2);
   END IF;
   IF FIELD_NAME='TARIF_GUARD_NDS' THEN
      SELECT TARIF_GUARD_NDS INTO SUM_CHISLO FROM KVIT WHERE NUM_KVIT=MNUM_KVIT AND TARIF_GUARD_NDS<>0;    
      OTVET:=ROUND(MVES*(SUM_CHISLO/SUM_VES),2);
   END IF;
   RETURN OTVET;
END GET_TARIF_CIST;

/

