--
-- GET_ISAGENT  (Function) 
--
CREATE OR REPLACE FUNCTION MASTER.GET_IsAgent(ALUK_DOG_ID NUMBER, ALUK_DOG_NUMBER VARCHAR2, ADOG_ID NUMBER, ADOG_NUMBER VARCHAR2)
  RETURN NUMBER IS
  vLUK_DOG_NUMBER VARCHAR2(250);
  vLUK_DOG_ID NUMBER;
  vDOG_NUMBER VARCHAR2(250);
  res NUMBER;
BEGIN
  vLUK_DOG_NUMBER:=RTrim(LTrim(NVL(ALUK_DOG_NUMBER,'')));
  vLUK_DOG_ID:=NVL(ALUK_DOG_ID,0);
  vDOG_NUMBER:=RTrim(LTrim(NVL(ADOG_NUMBER,'')));
  res:=1;

  IF vLUK_DOG_ID<>0 AND vLUK_DOG_NUMBER || ' '<> ' ' THEN
    BEGIN
      SELECT IS_AGENT INTO res FROM KLS_DOG WHERE KLS_DOG.DOG_NUMBER=vLUK_DOG_NUMBER;
	EXCEPTION
	  WHEN OTHERS THEN
	    res:=1;
	END;	    
  ELSE
    BEGIN
      SELECT IS_AGENT INTO res FROM KLS_DOG WHERE KLS_DOG.DOG_NUMBER=vDOG_NUMBER;
	EXCEPTION
	  WHEN OTHERS THEN
	    res:=1;
	END;	    
  END IF;
  
  RETURN res;	  		
End;

/

