--
-- AZC_TEST  (Package) 
--
CREATE OR REPLACE PACKAGE MASTER.Azc_Test AS

 FUNCTION GET_AZC_OST_VES_TEST(pORG_STRU_ID NUMBER, pPROD_ID_NPR VARCHAR2, pSOBSTV_ID NUMBER, pDATE_OPER DATE DEFAULT SYSDATE, FIRST_DAY NUMBER DEFAULT 1) RETURN NUMBER;
 FUNCTION GET_AZC_OST_VOL_TEST(pORG_STRU_ID NUMBER, pPROD_ID_NPR VARCHAR2, pSOBSTV_ID NUMBER, pDATE_OPER DATE DEFAULT SYSDATE, FIRST_DAY NUMBER DEFAULT 1) RETURN NUMBER;
  -- Остаток объема по АЗС, продукту, собственнику на определенную дату

END;

/

