--
-- FOR_PASP  (Package) 
--
CREATE OR REPLACE PACKAGE MASTER.For_pasp AS

/* ПАСПОРТА */


-- Добавить/изменить паспорт
FUNCTION AddPasp (pCOMMIT NUMBER, pID VARCHAR2, pMESTO_ID NUMBER ,pPASP_NUM VARCHAR2, pREZ_NUM VARCHAR2,
                  pPASP_DATE DATE,pINSPEKTOR VARCHAR2, pDATE_OFORML DATE, pPROD_ID_NPR VARCHAR2, pDATE_VIR DATE,
				  pPERER_ID NUMBER) RETURN VARCHAR2;

 /* УДАЛИТЬ ПАСПОРТ С ПОКАЗАТЕЛЯМИ */
PROCEDURE DelTitle(pCOMMIT NUMBER, pID VARCHAR2);

-- Добавить/обновить основные показатели паспорта
PROCEDURE AddMainPaspValue (pCOMMIT NUMBER,pPASP_ID VARCHAR2, pPL15 NUMBER, pPL20 NUMBER, pP_SER NUMBER,
                            pT_VSP NUMBER, pP_VOD NUMBER, pP_DIRT NUMBER, pMG_SOL NUMBER, pP_SOL NUMBER);

-- Добавить/обновить значение показателя паспорта
PROCEDURE SET_PASP_VALUE (pPASP_ID VARCHAR2, pKODIF_ID NUMBER, pKODIF_TAG VARCHAR2, pQUAL VARCHAR2);

-- Получить значение показателя паспорта
FUNCTION GET_PASP_VALUE_AS_NUM (pPASP_ID VARCHAR2, pKODIF_ID NUMBER, pKODIF_TAG VARCHAR2) RETURN NUMBER;
FUNCTION GET_PASP_VALUE_AS_CHAR (pPASP_ID VARCHAR2, pKODIF_ID NUMBER, pKODIF_TAG VARCHAR2) RETURN VARCHAR2;

-- Поиск паспорта
FUNCTION GET_PASP_ID RETURN NUMBER;

-- Получить ID показателя паспорта по ТЕГУ
FUNCTION GET_KODIF_ID_BY_TAG (pPROD_ID_NPR VARCHAR2, pTAG VARCHAR2) RETURN NUMBER;

--Получить показатель по тегу(ТАУБИН)
FUNCTION GET_PASP_VALUE_BY_TAG (pPASP_ID VARCHAR2, pKODIF_TAG VARCHAR2) RETURN VARCHAR2;

--Получить показатель по коду R3(ТАУБИН)
FUNCTION GET_PASP_VALUE_BY_R3 (pPASP_ID VARCHAR2, pID_R3 VARCHAR2) RETURN VARCHAR2;

END;

/

