/* This object may not be sorted properly in the script due to cirular references. */
--
-- FOR_R3  (Package) 
--
CREATE OR REPLACE PACKAGE MASTER.For_R3 AS

  PROCEDURE RaiseError (pText VARCHAR2);
  PROCEDURE RENEW_VSTEL (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_VSBED (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_VSART (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_WERKS_LGORT (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_BLOCKS (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_AUART (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_R3_GD (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_PREDPR (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_MATERIALS (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_MATERIALS_GRP (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_CC (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  FUNCTION R2M_PREDPR (R3_KOD VARCHAR2) RETURN NUMBER;
  FUNCTION R2M_DOG (R3_KOD VARCHAR2) RETURN NUMBER;
  PROCEDURE RENEW_SC (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_KONV (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_OA (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_ROUTENODES (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_ROUTES (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_ROUTE_FULL (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_LPRIO (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_VBAK (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');
  PROCEDURE RENEW_OD (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');

  /*Добавление записи в таблицу R3_VBAK при экспорте из текстового файла*/
  procedure AddVbakRow(pCOMMIT NUMBER, pVBAP_VSTEL VARCHAR2,  pVBKD_BSTKD VARCHAR2,pVBKD_BSTDK varchar2,
   pVBAK_VBELN VARCHAR2, pVBAP_POSNR varchar2,pVBAK_VDATU varchar2,pVBAK_VSBED VARCHAR2,pUNKNOWN1 VARCHAR2,
   pVBAP_MATNR VARCHAR2,pOT_LIFNR VARCHAR2,pUNKNOWN2 VARCHAR2,pUNKNOWN3 VARCHAR2,
   pVBAK_VKORG VARCHAR2, pVBAK_VTWEG VARCHAR2, 
    pVBAP_OICONTNR VARCHAR2, pVBAK_ZZ021 VARCHAR2, pVEDA_VBEGDAT varchar2,  
    	pVBAK_AUART VARCHAR2, pTVAKT_BEZEI VARCHAR2,  
	pVBKD_VSART VARCHAR2, pVBKD_TRATY VARCHAR2, pVBAP_LPRIO VARCHAR2, pVBAP_ROUTE VARCHAR2,
	 pVBAP_WERKS VARCHAR2, pLGORT VARCHAR2,  pVBAP_KWMENG varchar2, 
	pVBAP_VRKME VARCHAR2,  pSH_KUNNR VARCHAR2, pINCO1 VARCHAR2, pINCO2 VARCHAR2,
	pZLSCH VARCHAR2, pSTCEG_L VARCHAR2, pZTERM VARCHAR2, pV_TJ30_TXT04 VARCHAR2, pVBPA_KUNNR VARCHAR2, 
	pVBPA_LIFNR_SP VARCHAR2, pVBAK_STCEG_L VARCHAR2, pSPART VARCHAR2);
  
  procedure DelVbakRow(pCOMMIT NUMBER, pVBELN VARCHAR2); 
	 

  /*Добавление записи в таблицу R3_KVIT2SAP при экспорте из текстового файла*/
  procedure AddRCRow(pCOMMIT NUMBER, pID_MS VARCHAR2, pVSTEL VARCHAR2, pID_SAP VARCHAR2, pID_SAP_PSN VARCHAR2); 

  /*Удаление записи из таблицы R3_KVIT2SAP */
  procedure DelRCRow(pCOMMIT NUMBER, pID_SAP VARCHAR2); 
	
  -- Вернуть номер файла для выгрузки поставок
  FUNCTION GET_SEQ_OF RETURN NUMBER;
	
END;

/

