--
-- FOR_CRYSTAL_TEL  (Package) 
--
CREATE OR REPLACE PACKAGE MASTER.For_Crystal_Tel AS

TYPE CURSTYPE IS REF CURSOR;

PROCEDURE CR_INSIDENUM(TIP_DATE VARCHAR2, DATE_BEG VARCHAR2, DATE_END VARCHAR2,
  INSIDE_NUM VARCHAR2, CRS IN OUT CURSTYPE);


END;

/

