--
-- FOR_SESSION  (Package) 
--
CREATE OR REPLACE PACKAGE MASTER.For_Session AS

-- Открыть сессию журнала событий 
FUNCTION StartSession(pDESCRIPT VARCHAR2, pAPPL_NAME VARCHAR2, pMODULE_NAME VARCHAR2) RETURN NUMBER;

-- Закрыть сессию журнала событий
PROCEDURE FinishSession(pSessionId NUMBER, pMODULE_NAME VARCHAR2);

-- Записать событие
FUNCTION WriteToLog(pSessionId NUMBER, pSTATUS NUMBER, pDESCRIPT VARCHAR2, pSITE_RN NUMBER, pMODULE_NAME VARCHAR2, pLOG_TIME DATE DEFAULT SYSDATE) RETURN NUMBER;

END;

/

