--
-- FOR_DIAGRAM  (Package) 
--
CREATE OR REPLACE PACKAGE MASTER.For_Diagram AS

  -- Очистка таблицы DIAGRAM для текущего пользователя
  PROCEDURE EMPTY_DIAGRAM;
  
  -- Отгрузка с УНП по месяцам
  PROCEDURE UNP_MON (DATE_BEG VARCHAR2, DATE_END VARCHAR2);

  -- Движение товара по месяцам за последние 4 года (по данным КО)
  PROCEDURE OPER_MON_KONS (DATE_BEG VARCHAR2, DATE_END VARCHAR2, FILIAL VARCHAR2, ORG_KIND_GRP VARCHAR2, AZC VARCHAR2, PROD_GR VARCHAR2, PROD VARCHAR2, TIP_OP VARCHAR2, IS_SUM NUMBER);

  -- Реализовано с НБ/АЗС по месяцам в тн за последние 4 года (по данным КО)
  PROCEDURE REALIZ_MON_TON (DATE_BEG VARCHAR2, DATE_END VARCHAR2, FILIAL VARCHAR2, ORG_KIND_GRP VARCHAR2, AZC VARCHAR2, PROD_GR VARCHAR2, PROD VARCHAR2);
					    
  -- Реализовано с НБ/АЗС по месяцам в тыс.руб. за последние 4 года (по данным КО)
  PROCEDURE REALIZ_MON_SUM (DATE_BEG VARCHAR2, DATE_END VARCHAR2, FILIAL VARCHAR2, ORG_KIND_GRP VARCHAR2, AZC VARCHAR2, PROD_GR VARCHAR2, PROD VARCHAR2);

 -- Реализовано с НБ/АЗС фасовки по месяцам в тыс.руб. за последние 4 года (по данным КО)
  PROCEDURE REALIZ_MON_SUM_FAS (DATE_BEG VARCHAR2, DATE_END VARCHAR2, FILIAL VARCHAR2, ORG_KIND_GRP VARCHAR2, AZC VARCHAR2);

 -- Сведения о резервуарном парке УНП
  PROCEDURE UNP_REZ (Date# VARCHAR2, NPR_GROUP# VARCHAR2, PROD# VARCHAR2);
  
  -- Планирование объемов реализации АЗС (по данным КО)
  PROCEDURE PLAN_REALIZ_AZS (DATE_BEG VARCHAR2, DATE_END VARCHAR2, FILIAL VARCHAR2, ORG_KIND_GRP VARCHAR2, AZC VARCHAR2, PROD_GR VARCHAR2, PROD VARCHAR2);

  -- Планирование объемов реализации фасованной продукции АЗС (по данным КО)
  PROCEDURE PLAN_REALIZ_AZS_FAS (DATE_BEG VARCHAR2, DATE_END VARCHAR2, FILIAL VARCHAR2, ORG_KIND_GRP VARCHAR2, AZC VARCHAR2, PROD_GR VARCHAR2, PROD VARCHAR2);
  
END;

/

