--
-- FOR_SAIO  (Package) 
--
CREATE OR REPLACE PACKAGE MASTER.For_SAIO AS

TYPE CURSTYPE IS REF CURSOR;

PROCEDURE LORP_LOAD_BILL(ADATE_BEG VARCHAR2, ADATE_END VARCHAR2);
PROCEDURE LORP_DEL_BILL(ADATE_BEG VARCHAR2, ADATE_END VARCHAR2);
PROCEDURE ADD_VOZN(ADATE_BEG DATE, ADATE_END DATE, ADBCODE NUMBER);

END;

/

