--
-- FOR_VISIR  (Package) 
--
CREATE OR REPLACE PACKAGE MASTER.FOR_VISIR AS

TYPE CURSTYPE IS REF CURSOR;

PROCEDURE GLOBAL_TO_LOCAL(AUSER_ID NUMBER,FROM_DATE DATE,TO_DATE DATE);
PROCEDURE LOCAL_TO_GLOBAL(AUSER_ID NUMBER,FROM_DATE DATE,TO_DATE DATE);
PROCEDURE LOCAL_TO_GLOBAL_ROW(AACTION VARCHAR2,AUSER_ID NUMBER, ADATE_REE DATE, ADOP_REE NUMBER, ANOM_ZD VARCHAR2, APRICHIN VARCHAR2);

END;

/

