--
-- FOR_DISP_AZS  (Package) 
--
CREATE OR REPLACE PACKAGE MASTER.For_Disp_Azs AS

-- Подготовка данных для отчета "Контроль АЗС" по неавтоматизированным АЗС
PROCEDURE manual_azs(pDATE_BEG VARCHAR2, pDATE_END VARCHAR2, pPARUS_DEPARTMENT VARCHAR2);

-- Остаток на утро
FUNCTION GET_OST_BEGIN_MAS1(pORG_STRU_ID NUMBER, pPROD_ID_NPR VARCHAR2, pDATE_OPER DATE DEFAULT SYSDATE) RETURN NUMBER;
FUNCTION GET_OST_BEGIN_VOL1(pORG_STRU_ID NUMBER, pPROD_ID_NPR VARCHAR2, pDATE_OPER DATE DEFAULT SYSDATE) RETURN NUMBER;
        
END;

/

