--
-- FOR_REPORTS  (Package) 
--
CREATE OR REPLACE PACKAGE MASTER.FOR_REPORTS AS
  
-- Определить номер отчета
FUNCTION GetNumRep (pREP_ID NUMBER, pBEGIN_DATE DATE, pEND_DATE DATE, pIS_CRT NUMBER DEFAULT 0) RETURN NUMBER;

-- Сохранить номер отчета
PROCEDURE SetNumRep (pREP_ID NUMBER, pBEGIN_DATE DATE, pEND_DATE DATE, pIS_CRT NUMBER DEFAULT 0, pNum_Rep NUMBER DEFAULT 0);

-- Заполнить Отчет о реализации
PROCEDURE FILL_REALIZ (pBEGIN_DATE VARCHAR2, pEND_DATE VARCHAR2, pIS_CRT NUMBER);
 
END;

/

