--
-- FOR_PARUS_SNAPSHOTS  (Package) 
--
CREATE OR REPLACE PACKAGE MASTER.FOR_PARUS_SNAPSHOTS AS

TYPE CURSTYPE IS REF CURSOR;

  PROCEDURE RENEW_SNAPSHOTS(DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='');

END;
/

