--
-- FOR_REESTR  (Package) 
--
CREATE OR REPLACE PACKAGE MASTER.For_Reestr AS

PROCEDURE Fill_Reestr_Param(DATE_PLAN# VARCHAR2,DATE_REE# VARCHAR2);

/* ДОБАВИТЬ/ИЗМЕНИТЬ РЕЕСТР */
FUNCTION AddReestr(pID NUMBER, pNUM_REE NUMBER, pDATE_REE DATE,
   pDATE_TO DATE, pDATE_PLAN DATE, pUSE_GRAFIK NUMBER,
   pGRAFIK_DATE_FROM DATE, pGRAFIK_DATE_TO DATE, pSTATUS NUMBER,
   pDOP_REE NUMBER) RETURN NUMBER;

/* График в виде строки */
FUNCTION GrafikToStr(pNOM_ZD VARCHAR2, pGRAFIK_TO DATE) RETURN VARCHAR2;

/* LOAD_ABBR из ГУ-12 */
FUNCTION GetLoadAbbr(pNOM_ZD VARCHAR2) RETURN VARCHAR2;

END;

/

