--
-- FOR_SCRIPTS  (Package) 
--
CREATE OR REPLACE PACKAGE MASTER.FOR_SCRIPTS AS

   SG$ERROR CONSTANT NUMBER := -20900;
   SG$ERROR_TXT CONSTANT VARCHAR2(40) := 'Ошибка';
   SG$ROW_EXIST CONSTANT NUMBER := -20901;
   SG$ROW_EXIST_TXT CONSTANT VARCHAR2(40) := 'Данная запись уже есть в таблице';
   SG$PK_CHANGE CONSTANT NUMBER := -20902;
   SG$PK_CHANGE_TXT CONSTANT VARCHAR2(40) := 'Нельзя менять PRIMARY KEY';
   SG$FK_CHANGE CONSTANT NUMBER := -20903;
   SG$FK_CHANGE_TXT CONSTANT VARCHAR2(40) := 'Нельзя менять FOREIGN KEY';
   SG$NO_ROW CONSTANT NUMBER := -20904;
   SG$NO_ROW_TXT CONSTANT VARCHAR2(40) := 'Запись не существует';
   SG$MANY_ROWS CONSTANT NUMBER := -20905;
   SG$MANY_ROWS_TXT CONSTANT VARCHAR2(40) := 'Записей больше 1-ой';
   SG$NO_CORRECT CONSTANT NUMBER := -20906;
   SG$NO_CORRECT_TXT CONSTANT VARCHAR2(40) := 'Данные не корректны';
   SG$CHANGE_ARCHIVE CONSTANT NUMBER := -20907;
   SG$CHANGE_ARCHIVE_I CONSTANT VARCHAR2(50) := 'Нельзя добавлять документ в архивный период!';
   SG$CHANGE_ARCHIVE_U CONSTANT VARCHAR2(50) := 'Нельзя обновлять документ в архивном периоде!';
   SG$CHANGE_ARCHIVE_D CONSTANT VARCHAR2(50) := 'Нельзя удалять документ из архивного периода!';

END;
/

