--
-- EXP_FULL_DATABASE  (Role) 
--
CREATE ROLE EXP_FULL_DATABASE NOT IDENTIFIED;

GRANT BACKUP ANY TABLE TO EXP_FULL_DATABASE;
GRANT EXECUTE ANY TYPE TO EXP_FULL_DATABASE;
GRANT SELECT ANY TABLE TO EXP_FULL_DATABASE;
GRANT SELECT ANY SEQUENCE TO EXP_FULL_DATABASE;
GRANT EXECUTE ANY PROCEDURE TO EXP_FULL_DATABASE;
BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'EXP_FULL_DATABASE', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
--
-- SELECT_CATALOG_ROLE  (Role) 
--
GRANT SELECT_CATALOG_ROLE TO EXP_FULL_DATABASE;
--
-- EXECUTE_CATALOG_ROLE  (Role) 
--
GRANT EXECUTE_CATALOG_ROLE TO EXP_FULL_DATABASE;


