--
-- IMP_FULL_DATABASE  (Role) 
--
CREATE ROLE IMP_FULL_DATABASE NOT IDENTIFIED;

GRANT AUDIT ANY TO IMP_FULL_DATABASE;
GRANT DROP USER TO IMP_FULL_DATABASE;
GRANT ANALYZE ANY TO IMP_FULL_DATABASE;
GRANT BECOME USER TO IMP_FULL_DATABASE;
GRANT CREATE ROLE TO IMP_FULL_DATABASE;
GRANT CREATE USER TO IMP_FULL_DATABASE;
GRANT DROP PROFILE TO IMP_FULL_DATABASE;
GRANT DROP ANY ROLE TO IMP_FULL_DATABASE;
GRANT DROP ANY TYPE TO IMP_FULL_DATABASE;
GRANT DROP ANY VIEW TO IMP_FULL_DATABASE;
GRANT ALTER ANY TYPE TO IMP_FULL_DATABASE;
GRANT CREATE PROFILE TO IMP_FULL_DATABASE;
GRANT DROP ANY INDEX TO IMP_FULL_DATABASE;
GRANT DROP ANY TABLE TO IMP_FULL_DATABASE;
GRANT ALTER ANY TABLE TO IMP_FULL_DATABASE;
GRANT CREATE ANY TYPE TO IMP_FULL_DATABASE;
GRANT CREATE ANY VIEW TO IMP_FULL_DATABASE;
GRANT DROP TABLESPACE TO IMP_FULL_DATABASE;
GRANT CREATE ANY INDEX TO IMP_FULL_DATABASE;
GRANT CREATE ANY TABLE TO IMP_FULL_DATABASE;
GRANT DROP ANY CLUSTER TO IMP_FULL_DATABASE;
GRANT DROP ANY CONTEXT TO IMP_FULL_DATABASE;
GRANT DROP ANY LIBRARY TO IMP_FULL_DATABASE;
GRANT DROP ANY OUTLINE TO IMP_FULL_DATABASE;
GRANT DROP ANY SYNONYM TO IMP_FULL_DATABASE;
GRANT DROP ANY TRIGGER TO IMP_FULL_DATABASE;
GRANT EXECUTE ANY TYPE TO IMP_FULL_DATABASE;
GRANT INSERT ANY TABLE TO IMP_FULL_DATABASE;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'IMP_FULL_DATABASE',
  ADMIN_OPTION => FALSE);
END;
/
GRANT SELECT ANY TABLE TO IMP_FULL_DATABASE;
GRANT UPDATE ANY TABLE TO IMP_FULL_DATABASE;
GRANT ALTER ANY TRIGGER TO IMP_FULL_DATABASE;
GRANT COMMENT ANY TABLE TO IMP_FULL_DATABASE;
GRANT CREATE TABLESPACE TO IMP_FULL_DATABASE;
GRANT DROP ANY OPERATOR TO IMP_FULL_DATABASE;
GRANT DROP ANY SEQUENCE TO IMP_FULL_DATABASE;
GRANT DROP ANY SNAPSHOT TO IMP_FULL_DATABASE;
GRANT CREATE ANY CLUSTER TO IMP_FULL_DATABASE;
GRANT CREATE ANY CONTEXT TO IMP_FULL_DATABASE;
GRANT CREATE ANY LIBRARY TO IMP_FULL_DATABASE;
GRANT CREATE ANY SYNONYM TO IMP_FULL_DATABASE;
GRANT CREATE ANY TRIGGER TO IMP_FULL_DATABASE;
GRANT DROP ANY DIMENSION TO IMP_FULL_DATABASE;
GRANT DROP ANY DIRECTORY TO IMP_FULL_DATABASE;
GRANT DROP ANY INDEXTYPE TO IMP_FULL_DATABASE;
GRANT DROP ANY PROCEDURE TO IMP_FULL_DATABASE;
GRANT ALTER ANY PROCEDURE TO IMP_FULL_DATABASE;
GRANT CREATE ANY OPERATOR TO IMP_FULL_DATABASE;
GRANT CREATE ANY SEQUENCE TO IMP_FULL_DATABASE;
GRANT CREATE ANY SNAPSHOT TO IMP_FULL_DATABASE;
GRANT DROP PUBLIC SYNONYM TO IMP_FULL_DATABASE;
GRANT CREATE ANY DIMENSION TO IMP_FULL_DATABASE;
GRANT CREATE ANY DIRECTORY TO IMP_FULL_DATABASE;
GRANT CREATE ANY INDEXTYPE TO IMP_FULL_DATABASE;
GRANT CREATE ANY PROCEDURE TO IMP_FULL_DATABASE;
GRANT CREATE DATABASE LINK TO IMP_FULL_DATABASE;
GRANT GLOBAL QUERY REWRITE TO IMP_FULL_DATABASE;
GRANT CREATE PUBLIC SYNONYM TO IMP_FULL_DATABASE;
GRANT DROP ROLLBACK SEGMENT TO IMP_FULL_DATABASE;
GRANT EXECUTE ANY PROCEDURE TO IMP_FULL_DATABASE;
GRANT CREATE ROLLBACK SEGMENT TO IMP_FULL_DATABASE;
GRANT DROP PUBLIC DATABASE LINK TO IMP_FULL_DATABASE;
GRANT ADMINISTER DATABASE TRIGGER TO IMP_FULL_DATABASE;
BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'IMP_FULL_DATABASE', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
GRANT CREATE PUBLIC DATABASE LINK TO IMP_FULL_DATABASE;
--
-- SELECT_CATALOG_ROLE  (Role) 
--
GRANT SELECT_CATALOG_ROLE TO IMP_FULL_DATABASE;
--
-- EXECUTE_CATALOG_ROLE  (Role) 
--
GRANT EXECUTE_CATALOG_ROLE TO IMP_FULL_DATABASE;


