--
-- V_ARH_INORDERS  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_INORDERS
(RN, COMPANY, CRN, CONTRAGENT, FACEACC, 
 GRAPHPOINT, PARTY, PARTY_CODE, STORE, STOPERTYPE, 
 INDOCTYPE, INDOCPREF, INDOCNUMB, INDOCDATE, WORK_DATE, 
 DOCSTATUS, CONFDOCTYPE, CONFDOCNUMB, CONFDOCDATE, DIRECTDOCTYPE, 
 DIRECTDOCNUMB, DIRECTDOCDATE, INVDOCTYPE, INVDOCNUMB, INVDOCDATE, 
 SIGNTAX, CURRENCY, CURCOURS, CURBASECOURS, FA_BASECOURS, 
 FA_COURS, ACC_COURS, ACC_BASECOURS, AGENT, PLANSUM, 
 PLANSUMTAX, FACTSUM, FACTSUMTAX, PLANPAYSUMM, FACTPAYSUMM, 
 COMMENTS, ALTSIGN1, ALTSIGN2, ALTSIGN3, ALTSIGN4, 
 ALTSIGN5, ALTSIGN6, ALTSIGN7, ALTSIGN8, ALTSIGN9, 
 ALTSIGN10, AGNFIFO, JUR_PERS, SALESREPORTDATE)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CRN","CONTRAGENT","FACEACC","GRAPHPOINT","PARTY","PARTY_CODE","STORE","STOPERTYPE","INDOCTYPE","INDOCPREF","INDOCNUMB","INDOCDATE","WORK_DATE","DOCSTATUS","CONFDOCTYPE","CONFDOCNUMB","CONFDOCDATE","DIRECTDOCTYPE","DIRECTDOCNUMB","DIRECTDOCDATE","INVDOCTYPE","INVDOCNUMB","INVDOCDATE","SIGNTAX","CURRENCY","CURCOURS","CURBASECOURS","FA_BASECOURS","FA_COURS","ACC_COURS","ACC_BASECOURS","AGENT","PLANSUM","PLANSUMTAX","FACTSUM","FACTSUMTAX","PLANPAYSUMM","FACTPAYSUMM","COMMENTS","ALTSIGN1","ALTSIGN2","ALTSIGN3","ALTSIGN4","ALTSIGN5","ALTSIGN6","ALTSIGN7","ALTSIGN8","ALTSIGN9","ALTSIGN10","AGNFIFO","JUR_PERS","SALESREPORTDATE"
FROM PARUS.INORDERS
-- Фильтр по складам (ТОЛЬКО транзитные)
WHERE STORE IN (SELECT STORE_RN FROM SNP_REPL.V_STORE_LIST)
/*rn in (
select distinct p.rn from snp_repl.v_arh_salesreportmain a, docoutpt do, doclinks dl, docinpt di, inorders p
where a.rn in (249719456,299843726,310686528,320941719,322502586,323360126)
  and a.rn=do.document
  and do.rn=dl.out_doc
  and dl.in_doc=di.rn
  and di.document=p.rn
UNION ALL
select distinct p.rn from snp_repl.v_arh_dicaccfi a, docoutpt do, doclinks dl, docinpt di, inorders p
where a.rn in (249603705,299774809,310664317,320627380,320980040,323358794)
  and a.rn=do.document
  and do.rn=dl.out_doc
  and dl.in_doc=di.rn
  and di.document=p.rn
)
*/
;


