--
-- V_ARH_INORDERSPECS  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_INORDERSPECS
(RN, COMPANY, CRN, PRN, NOMMODIF, 
 NOMNMODIFPACK, ARTICLE, GOODSSUPPLY, TAXGR, PLANQUANT, 
 FACTQUANT, PLANQUANTALT, FACTQUANTALT, PRICE, PRICEMEAS, 
 FORMULA, ACC_PRICE, ACC_PRICEMEAS, EXPIRY_DATE, CERTIFICATE, 
 NOTE, PLANSUM, PLANSUMTAX, FACTSUM, FACTSUMTAX, 
 SERNUMB, BARCODE, COUNTRY, GTD, PRODUCER, 
 PRICE_CALC_RULE, CELL, STORAGE_TIME, UMEAS_STORAGE)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CRN","PRN","NOMMODIF","NOMNMODIFPACK","ARTICLE","GOODSSUPPLY","TAXGR","PLANQUANT","FACTQUANT","PLANQUANTALT","FACTQUANTALT","PRICE","PRICEMEAS","FORMULA","ACC_PRICE","ACC_PRICEMEAS","EXPIRY_DATE","CERTIFICATE","NOTE","PLANSUM","PLANSUMTAX","FACTSUM","FACTSUMTAX","SERNUMB","BARCODE","COUNTRY","GTD","PRODUCER","PRICE_CALC_RULE","CELL","STORAGE_TIME","UMEAS_STORAGE"
FROM PARUS.INORDERSPECS
WHERE PRN IN (SELECT RN FROM SNP_REPL.V_ARH_INORDERS);


