--
-- V_ARH_LIABILITYNOTES  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_LIABILITYNOTES
(RN, COMPANY, CRN, LOAD_PREFIX, LOAD_NUMB, 
 FACEACC, GRAPHPOINT, LOAD_DATE, AGENT, VDOC_TYPE, 
 VDOC_DATE, VDOC_NUMB, CURRENCY, LOAD_SUM_NOTAX, LOAD_SUM, 
 BASE_SUM_NOTAX, BASE_SUM, LOAD_SUM_ACC, SERV_SUM, SERV_BASE_SUM, 
 SERV_SUM_ACC, STOREOPER, PAY_TYPE, FDOC_TYPE, FDOC_NUMB, 
 FDOC_DATE, STATE_SIGN, DOC_STATE, PLAN_LOAD, COMMENTS, 
 ALTSIGN1, ALTSIGN2, ALTSIGN3, ALTSIGN4, ALTSIGN5, 
 ALTSIGN6, ALTSIGN7, ALTSIGN8, ALTSIGN9, ALTSIGN10)
AS 
SELECT /*+ RULE */ A.*
/* 1 - через группу Лицевых счетов */
FROM PARUS.LIABILITYNOTES A, PARUS.FACEACC B, PARUS.FCACGR C
-- Фильтр по группе лицевых счетов
WHERE A.FACEACC=B.RN
  AND B.FCACGR=C.RN
  AND C.CODE IN (SELECT FCACGR_TAG FROM SNP_REPL.V_FCACGR_LIST)
/* 2 - через связи */
--SELECT /* ORDERED */ B.*
--FROM V_ARH_INORDERS A, DOCINPT I, DOCLINKS L, DOCOUTPT O, PARUS.LIABILITYNOTES B
--WHERE A.RN=I.DOCUMENT
--  AND I.UNITCODE='IncomingOrders'
--  AND I.RN=L.IN_DOC
--  AND L.OUT_DOC=O.RN
--  AND O.UNITCODE = 'LiabilitiesNotes'
--  AND O.DOCUMENT=B.RN
;


