--
-- V_ARH_CONSUMERORDS  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_CONSUMERORDS
(RN, PRN, COMPANY, CRN, NOMEN, 
 NOM_PACK, NOM_MODIF, NOMMOD_PACK, PRODUCT, TAX_GROUP, 
 MAIN_QUANT, ALT_QUANT, EXP_PRICE, PR_MEAS, STORE, 
 SUMWTAX, SUMWOTAX, POSREDUCT, NOTE, NAME, 
 BEGIN_DATE, END_DATE)
AS 
SELECT /*+ RULE */ "RN","PRN","COMPANY","CRN","NOMEN","NOM_PACK","NOM_MODIF","NOMMOD_PACK","PRODUCT","TAX_GROUP","MAIN_QUANT","ALT_QUANT","EXP_PRICE","PR_MEAS","STORE","SUMWTAX","SUMWOTAX","POSREDUCT","NOTE","NAME","BEGIN_DATE","END_DATE" FROM PARUS.CONSUMERORDS
WHERE PRN IN (SELECT RN FROM V_ARH_CONSUMERORD);


