--
-- V_ARH_BANKDOCS_SUMM  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_BANKDOCS_SUMM
(RN, PRN, UNITCODE, REF_RN, PAY_SUM)
AS 
SELECT /*+ RULE */ A.*
FROM PARUS.BANKDOCS_SUMM A
-- Фильтр по каталогу
WHERE A.PRN IN (SELECT RN FROM V_ARH_BANKDOCS);


