--
-- V_ARH_STRPLRESJRNL  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_STRPLRESJRNL
(RN, COMPANY, RACK, CELL, GOODSSUPPLY, 
 RES_TYPE, ARTICLE, DOCTYPE, DOCDATE, DOCNUMB, 
 DOCPREF, RESERVING_DATE, FREE_DATE, QUANT, QUANTALT, 
 QUANTPACK)
AS 
SELECT /*+ RULE */ "RN","COMPANY","RACK","CELL","GOODSSUPPLY","RES_TYPE","ARTICLE","DOCTYPE","DOCDATE","DOCNUMB","DOCPREF","RESERVING_DATE","FREE_DATE","QUANT","QUANTALT","QUANTPACK" FROM PARUS.STRPLRESJRNL
WHERE GOODSSUPPLY IN (SELECT RN FROM SNP_REPL.V_ARH_GOODSSUPPLY);


