--
-- V_ARH_CASHDOCSACC  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_CASHDOCSACC
(PRN, CASH_OPER)
AS 
SELECT /*+ RULE */ A.*
FROM PARUS.CASHDOCSACC A
-- Фильтр по каталогу
WHERE A.PRN IN (SELECT RN FROM V_ARH_CASHDOCS);


