--
-- V_ARH_DOCUMENTS  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_DOCUMENTS
(RN)
AS 
SELECT RN FROM V_ARH_AGREEMENT
UNION ALL
SELECT RN FROM V_ARH_AGREEMENTS
UNION ALL
SELECT RN FROM V_ARH_BANKDOCS
UNION ALL
SELECT RN FROM V_ARH_BILLASSACT
UNION ALL
SELECT RN FROM V_ARH_BILLASSACTDOC
UNION ALL
SELECT RN FROM V_ARH_BILLCARD
UNION ALL
SELECT RN FROM V_ARH_BILLRECPACT
UNION ALL
SELECT RN FROM V_ARH_BILLRECPACTDOC
UNION ALL
SELECT RN FROM V_ARH_BILLMOVEMENT
UNION ALL
SELECT RN FROM V_ARH_CASHDOCS
UNION ALL
SELECT RN FROM V_ARH_CONSUMERORD
UNION ALL
SELECT RN FROM V_ARH_CONSUMERORDS
UNION ALL
SELECT RN FROM V_ARH_CONSUMERORDP
UNION ALL
SELECT RN FROM V_ARH_CONSUMERORDPS
UNION ALL
SELECT RN FROM V_ARH_DICACCFI
UNION ALL
SELECT RN FROM V_ARH_DICLACFI
UNION ALL
SELECT RN FROM V_ARH_DICACCFO
UNION ALL
SELECT RN FROM V_ARH_DICLACFO
UNION ALL
SELECT RN FROM V_ARH_INCOMDOC
UNION ALL
SELECT RN FROM V_ARH_INCOMEFROMDEPS
UNION ALL
SELECT RN FROM V_ARH_INCOMEFROMDEPSSPEC
UNION ALL
SELECT RN FROM V_ARH_INORDERS
UNION ALL
SELECT RN FROM V_ARH_INORDERSPECS
UNION ALL
SELECT RN FROM V_ARH_LIABILITYNOTES
UNION ALL
SELECT RN FROM V_ARH_PAYACC
UNION ALL
SELECT RN FROM V_ARH_PAYACCSPECS
UNION ALL
SELECT RN FROM V_ARH_PAYNOTES
UNION ALL
SELECT RN FROM V_ARH_RESJOURNAL
UNION ALL
SELECT RN FROM V_ARH_RLINVSHEET
UNION ALL
SELECT RN FROM V_ARH_RLINVSHEETSPEC
UNION ALL
SELECT RN FROM V_ARH_RLPRICES
UNION ALL
SELECT RN FROM V_ARH_RLPRICESPECS
UNION ALL
SELECT RN FROM V_ARH_SALESREPORTDETAIL
UNION ALL
SELECT RN FROM V_ARH_SALESREPORTMAIN
UNION ALL
SELECT RN FROM V_ARH_SHEEPDIRSCUST
UNION ALL
SELECT RN FROM V_ARH_SHEEPDIRSCUSTSPECS
UNION ALL
SELECT RN FROM V_ARH_SHEEPDIRSDEPT
UNION ALL
SELECT RN FROM V_ARH_SHEEPDIRSDEPTSPECS
UNION ALL
SELECT RN FROM V_ARH_STOREOPERJOURN
UNION ALL
SELECT RN FROM V_ARH_STRPLRESJRNL
UNION ALL
SELECT RN FROM V_ARH_STRPLOPRJRNL
UNION ALL
SELECT RN FROM V_ARH_TRANSINVCUST
UNION ALL
SELECT RN FROM V_ARH_TRANSINVCUSTSPECS
UNION ALL
SELECT RN FROM V_ARH_RINVTOSUP
UNION ALL
SELECT RN FROM V_ARH_RINVTOSUPSPECS
UNION ALL
SELECT RN FROM V_ARH_TRANSINVDEPT
UNION ALL
SELECT RN FROM V_ARH_TRANSINVDEPTSPECS
UNION ALL
SELECT RN FROM V_ARH_WROFFACTS
UNION ALL
SELECT RN FROM V_ARH_WROFFACTSPECS;


