--
-- V_ARH_BANKDOCSACC  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_BANKDOCSACC
(PRN, BANK_OPER)
AS 
SELECT /*+ RULE */ A.*
FROM PARUS.BANKDOCSACC A
-- Фильтр по каталогу
WHERE A.PRN IN (SELECT RN FROM V_ARH_BANKDOCS);


