--
-- V_ARH_CONSUMERORDP  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_CONSUMERORDP
(RN, PRN, COMPANY, CRN, PERF_NUMB, 
 PERF_DATE, PSUMWTAX, PSUMWOTAX, SUPP_PLAN_SUM, SUPP_FACT_SUM, 
 PAY_PLAN_SUM, PAY_FACT_SUM, ACC_QUANT, ACC_SUM)
AS 
SELECT /*+ RULE */ "RN","PRN","COMPANY","CRN","PERF_NUMB","PERF_DATE","PSUMWTAX","PSUMWOTAX","SUPP_PLAN_SUM","SUPP_FACT_SUM","PAY_PLAN_SUM","PAY_FACT_SUM","ACC_QUANT","ACC_SUM" FROM PARUS.CONSUMERORDP
WHERE PRN IN (SELECT RN FROM V_ARH_CONSUMERORD);


