--
-- V_ARH_BILLASSACTASS  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_BILLASSACTASS
(RN, PRN, COMPANY, CRN, DESTIGNATION, 
 DEST_SIGN, FINOPER, PAY_TYPE, BILL_TYPE_SIGN, BILL_TYPE, 
 CALC_TYPE_SIGN, CALC_TYPE, DEST_VALUE, DEST_VALUE_BASE)
AS 
SELECT /*+ RULE */ "RN","PRN","COMPANY","CRN","DESTIGNATION","DEST_SIGN","FINOPER","PAY_TYPE","BILL_TYPE_SIGN","BILL_TYPE","CALC_TYPE_SIGN","CALC_TYPE","DEST_VALUE","DEST_VALUE_BASE"
FROM PARUS.BILLASSACTASS
WHERE PRN IN (SELECT RN FROM PARUS.BILLASSACT);


