--
-- V_ARH_INCOMEFROMDEPSSPEC  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_INCOMEFROMDEPSSPEC
(RN, PRN, COMPANY, CRN, NOMMODIF, 
 PACK, ARTICLE, SUPPLY, QUANT_PLAN, QUANT_FACT, 
 QUANT_PLAN_ALT, QUANT_FACT_ALT, SROK, SERTIFICATE, PRICE, 
 PRICEMEAS, SUMM_PLAN, SUMM_FACT, NOTE, SERNUMB, 
 BARCODE, COUNTRY, GTD, PRODUCER, CELL)
AS 
SELECT /*+ RULE */ "RN","PRN","COMPANY","CRN","NOMMODIF","PACK","ARTICLE","SUPPLY","QUANT_PLAN","QUANT_FACT","QUANT_PLAN_ALT","QUANT_FACT_ALT","SROK","SERTIFICATE","PRICE","PRICEMEAS","SUMM_PLAN","SUMM_FACT","NOTE","SERNUMB","BARCODE","COUNTRY","GTD","PRODUCER","CELL" FROM PARUS.INCOMEFROMDEPSSPEC
WHERE PRN IN (SELECT RN FROM V_ARH_INCOMEFROMDEPS);


