--
-- V_ARH_CONSUMERORDPS  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_CONSUMERORDPS
(RN, PRN, COMPANY, CRN, PERF, 
 PERFS_STATE, CS_DATE, PERF_DATE, ACTPF_DATE, CUST_DATE, 
 EXEC_DATE, ACTM_QUANT, ACTA_QUANT, EXECM_QUANT, EXECA_QUANT, 
 CUSTM_QUANT, CUSTA_QUANT, ACTSWTAX, ACTSWOTAX, EXECSWTAX, 
 EXECSWOTAX, CUSTSWTAX, CUSTSWOTAX, ACCM_QUANT, ACCA_QUANT, 
 ACC_SUM, P_PLANM_QUANT, P_PLANA_QUANT, P_FACTM_QUANT, P_FACTA_QUANT, 
 P_PLAN_SUM, P_FACT_SUM, RESERVM_QUANT, RESERVA_QUANT)
AS 
SELECT /*+ RULE */ "RN","PRN","COMPANY","CRN","PERF","PERFS_STATE","CS_DATE","PERF_DATE","ACTPF_DATE","CUST_DATE","EXEC_DATE","ACTM_QUANT","ACTA_QUANT","EXECM_QUANT","EXECA_QUANT","CUSTM_QUANT","CUSTA_QUANT","ACTSWTAX","ACTSWOTAX","EXECSWTAX","EXECSWOTAX","CUSTSWTAX","CUSTSWOTAX","ACCM_QUANT","ACCA_QUANT","ACC_SUM","P_PLANM_QUANT","P_PLANA_QUANT","P_FACTM_QUANT","P_FACTA_QUANT","P_PLAN_SUM","P_FACT_SUM","RESERVM_QUANT","RESERVA_QUANT" FROM PARUS.CONSUMERORDPS
WHERE PRN IN (SELECT RN FROM V_ARH_CONSUMERORDS);


