--
-- V_ARH_SALESREPORTMAIN  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_SALESREPORTMAIN
(RN, CRN, COMPANY, RPT_PREFIX, RPT_NUMBER, 
 RPT_DATE, B_DATE, E_DATE, RPT_UNIT, AGENT, 
 APPCODE, WORK_STATE, WORK_DATE, JUR_PERS, WORK_STATE_TAX, 
 WORK_DATE_TAX)
AS 
SELECT /*+ RULE */ "RN","CRN","COMPANY","RPT_PREFIX","RPT_NUMBER","RPT_DATE","B_DATE","E_DATE","RPT_UNIT","AGENT","APPCODE","WORK_STATE","WORK_DATE","JUR_PERS","WORK_STATE_TAX","WORK_DATE_TAX" FROM PARUS.SALESREPORTMAIN
-- Фильтр по складам (БЕЗ транзитных)
WHERE RPT_UNIT IN (SELECT STORE_RN FROM SNP_REPL.V_STORE_LIST)
/* rn in (249719456,299843726,310686528,320941719,322502586,323360126)*/
;


