--
-- V_ARH_GOODSPARTIES  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_GOODSPARTIES
(RN, COMPANY, INDOC, NOMMODIF, NOMNMODIFPACK, 
 EXPIRY_DATE, CERTIFICATE, SIGNBREAK, SERNUMB, BARCODE, 
 COUNTRY, GTD, PRODUCER, STORAGE_TIME, UMEAS_STORAGE)
AS 
SELECT /*+ RULE */ "RN","COMPANY","INDOC","NOMMODIF","NOMNMODIFPACK","EXPIRY_DATE","CERTIFICATE","SIGNBREAK","SERNUMB","BARCODE","COUNTRY","GTD","PRODUCER","STORAGE_TIME","UMEAS_STORAGE" FROM PARUS.GOODSPARTIES
--WHERE RN IN (SELECT PRN FROM SNP_REPL.V_ARH_GOODSSUPPLY)
;


