--
-- V_ARH_PAYACC  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_PAYACC
(RN, COMPANY, CRN, SELF_AGNACC, AGNACC, 
 FACEACC, GRAPHPOINT, CURRENCY, SHEEPVIEW, PAYTYPE, 
 TARIF, FIFO, STORE, DOCTYPE, STATUS, 
 PREF, NUMB, ACCDATE, SALEDATE, RESERVDATE, 
 WORK_DATE, CURCOURS, CURBASE, FA_BASECOURS, FA_COURS, 
 DISCOUNT, SUMM, SUMMWITHNDS, PLANPAYSUMM, FACTPAYSUMM, 
 PLANSHEEPSUMM, FACTSHEEPSUMM, VDOC_TYPE, VDOC_NUMB, VDOC_DATE, 
 COMMENTS, ALTSIGN1, ALTSIGN2, ALTSIGN3, ALTSIGN4, 
 ALTSIGN5, ALTSIGN6, ALTSIGN7, ALTSIGN8, ALTSIGN9, 
 ALTSIGN10, ACC_AGENT, SUBDIV, JUR_PERS, AGENT)
AS 
SELECT /*+ RULE */ A.*
FROM PARUS.PAYACC A, PARUS.FACEACC B, PARUS.FCACGR C
-- Фильтр по группе лицевых счетов
WHERE A.FACEACC=B.RN
  AND B.FCACGR=C.RN
  AND C.CODE IN (SELECT FCACGR_TAG FROM SNP_REPL.V_FCACGR_LIST);


