--
-- V_ARH_AGREEMENT  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_AGREEMENT
(RN, COMPANY, CRN, AGR_D_TYPE, AGR_PREF, 
 AGR_NUMB, AGR_DATE, AGR_CONTENTS, CURRENCY, CURSUM, 
 EQUALSUM, VDOC_TYPE, VDOC_NUMB, VDOC_DATE, PLAN_SUM, 
 FACT_SUM, STATE, JUR_PERS, EXT_NUMBER, EXT_DATE)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CRN","AGR_D_TYPE","AGR_PREF","AGR_NUMB","AGR_DATE","AGR_CONTENTS","CURRENCY","CURSUM","EQUALSUM","VDOC_TYPE","VDOC_NUMB","VDOC_DATE","PLAN_SUM","FACT_SUM","STATE","JUR_PERS","EXT_NUMBER","EXT_DATE"
FROM PARUS.AGREEMENT
WHERE COMPANY=2 AND AGR_DATE>=TO_DATE('01.09.2004','dd.mm.yyyy');


