--
-- V_ARH_WROFFACTSPECS  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_WROFFACTSPECS
(RN, COMPANY, CRN, PRN, NOMMODIF, 
 NOMMODIFPACK, ARTICLE, GOODSSUPPLY, QUANT, QUANTALT, 
 PRICE, PRICEMEAS, SUMM, NOTE)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CRN","PRN","NOMMODIF","NOMMODIFPACK","ARTICLE","GOODSSUPPLY","QUANT","QUANTALT","PRICE","PRICEMEAS","SUMM","NOTE" FROM PARUS.WROFFACTSPECS
WHERE PRN IN (SELECT RN FROM V_ARH_WROFFACTS);


