--
-- V_ARH_STRPLOPRJRNL  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_STRPLOPRJRNL
(RN, COMPANY, CELL, GOODSSUPPLY, ARTICLE, 
 QUANT, QUANTALT, QUANTPACK, OPER_TYPE, OPER_DATE, 
 DOCTYPE, DOCDATE, DOCNUMB, DOCPREF)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CELL","GOODSSUPPLY","ARTICLE","QUANT","QUANTALT","QUANTPACK","OPER_TYPE","OPER_DATE","DOCTYPE","DOCDATE","DOCNUMB","DOCPREF" FROM PARUS.STRPLOPRJRNL
WHERE GOODSSUPPLY IN (SELECT RN FROM SNP_REPL.V_ARH_GOODSSUPPLY);


