--
-- V_ARH_DICLACFO_PSV  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_DICLACFO_PSV
(RN, COMPANY, PRN, PAY_DATE, FOOD_CODE, 
 FOOD_NAME, AMOUNT, MES_UNITS, TAX_GROUP, ONE_PRICE, 
 SUM_PRICE, ONE_EXCISE, EXCISE, ONE_EXCISE_SUM, ONE_GSM_TAX, 
 ONE_GSM_TAX_SUM, GSM_TAX, ONE_WOUT_SUM, SUM_WOUT, RATE_NDS, 
 ONE_SUM_NDS, SUM_NDS, ONE_SUM_TOTAL, SUM_TOTAL, FOODMODIF_CODE, 
 FOODPACK_CODE, TARIFF_NAME, RATE_NDS_OUT, NDS_PR, TYPE, 
 ACC_RN, ACC_PR, AUTO_CALC_SIGN, COUNTRY, GTD, 
 ONE_NSP, NSP, ONE_NSP_SUM, STORN_PAY_RN, INCLUDE_DATE)
AS 
SELECT /*+ RULE */ "RN","COMPANY","PRN","PAY_DATE","FOOD_CODE","FOOD_NAME","AMOUNT","MES_UNITS","TAX_GROUP","ONE_PRICE","SUM_PRICE","ONE_EXCISE","EXCISE","ONE_EXCISE_SUM","ONE_GSM_TAX","ONE_GSM_TAX_SUM","GSM_TAX","ONE_WOUT_SUM","SUM_WOUT","RATE_NDS","ONE_SUM_NDS","SUM_NDS","ONE_SUM_TOTAL","SUM_TOTAL","FOODMODIF_CODE","FOODPACK_CODE","TARIFF_NAME","RATE_NDS_OUT","NDS_PR","TYPE","ACC_RN","ACC_PR","AUTO_CALC_SIGN","COUNTRY","GTD","ONE_NSP","NSP","ONE_NSP_SUM","STORN_PAY_RN","INCLUDE_DATE" FROM PARUS.DICLACFO
WHERE PRN IN (SELECT RN FROM V_ARH_DICACCFO);


