--
-- V_ARH_AGREEMENTS  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_AGREEMENTS
(RN, PRN, COMPANY, CRN, DIAG_NUMB, 
 PLAN_DATE, FACT_DATE, SET_EO, DIAG_PLAN_SUM, DIAG_FACT_SUM, 
 NOTE, AGENT_FROM, FACEACC_FROM, BALUNIT_FROM, NAME_FROM, 
 AGENT_TO, FACEACC_TO, BALUNIT_TO, NAME_TO)
AS 
SELECT /*+ RULE */ "RN","PRN","COMPANY","CRN","DIAG_NUMB","PLAN_DATE","FACT_DATE","SET_EO","DIAG_PLAN_SUM","DIAG_FACT_SUM","NOTE","AGENT_FROM","FACEACC_FROM","BALUNIT_FROM","NAME_FROM","AGENT_TO","FACEACC_TO","BALUNIT_TO","NAME_TO" FROM PARUS.AGREEMENTS
WHERE PRN IN (SELECT RN FROM V_ARH_AGREEMENT);


