--
-- V_ARH_SHEEPDIRSDEPTSPECS  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_SHEEPDIRSDEPTSPECS
(RN, COMPANY, CRN, PRN, GOODSPARTY, 
 NOMNMODIFPACK, NOMMODIF, ARTICLE, PRICE, QUANT, 
 QUANTALT, PRICEMEAS, SUMMWITHNDS, BEGINDATE, ENDDATE, 
 NOTE)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CRN","PRN","GOODSPARTY","NOMNMODIFPACK","NOMMODIF","ARTICLE","PRICE","QUANT","QUANTALT","PRICEMEAS","SUMMWITHNDS","BEGINDATE","ENDDATE","NOTE"
FROM PARUS.SHEEPDIRSDEPTSPECS
WHERE PRN IN (SELECT RN FROM V_ARH_SHEEPDIRSDEPT);


