--
-- V_ARH_BILLASSACTDOC  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_BILLASSACTDOC
(RN, PRN, COMPANY, CRN, FACEACC, 
 AGENT, VDOC_TYPE, VDOC_NUMB, VDOC_DATE, VDOC_VALUE, 
 VDOC_VALUE_BASE, BALUNIT)
AS 
SELECT /*+ RULE */ "RN","PRN","COMPANY","CRN","FACEACC","AGENT","VDOC_TYPE","VDOC_NUMB","VDOC_DATE","VDOC_VALUE","VDOC_VALUE_BASE","BALUNIT" FROM PARUS.BILLASSACTDOC
WHERE PRN IN (SELECT RN FROM PARUS.BILLASSACT);


