--
-- V_ARH_DOCOUTPT  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_DOCOUTPT
(RN, COMPANY, AUTHID, UNITCODE, DOCUMENT, 
 PRN_DOCUMENT, STATUS, IN_DATE, IN_UNITCODE, BREAKUP_KIND)
AS 
SELECT /*+ RULE */ A.*
FROM PARUS.DOCOUTPT A
WHERE A.DOCUMENT IN
(
SELECT RN FROM V_ARH_DOCUMENTS
);


