--
-- V_ARH_PAYACCIN  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_PAYACCIN
(RN, COMPANY, CRN, DOC_TYPE, DOC_PREF, 
 DOC_NUMB, DOC_DATE, EXT_NUMB, REG_DATE, DOC_STATE, 
 STATE_DATE, PAY_DATE, PAYER, PAYERACC, SUPPLIER, 
 SUPPLACC, FACEACC, GRAPHPOINT, CURRENCY, CURCOURS, 
 CURBASE, AGNFI, AGNFO, STORE, VDOC_TYPE, 
 VDOC_NUM, VDOC_DATE, PRICEWITHTAX, SUMM, SUMMWITHNDS, 
 FA_BASECOURS, FA_COURS, PLANPAYSUMM, FACTPAYSUMM, ININVSUMM, 
 INORDSUMM, COMMENTS, JUR_PERS, PAYTYPE)
AS 
SELECT /*+ RULE */ A.*
FROM PARUS.PAYACCIN A, PARUS.FACEACC B, PARUS.FCACGR C
-- Фильтр по группе лицевых счетов
WHERE A.FACEACC=B.RN
  AND B.FCACGR=C.RN
  AND C.CODE IN (SELECT FCACGR_TAG FROM SNP_REPL.V_FCACGR_LIST);


