--
-- V_ARH_RLPRICES  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_RLPRICES
(RN, COMPANY, CRN, TARIF, NOMEN, 
 NOMEN_GROUP, TAXGROUP, PRICEDATE, ENDDATE, DEPONPAYTP, 
 DEPONSHEEP, DEPONSTORE)
AS 
SELECT /*+ RULE */ A.*
FROM PARUS.RLPRICES A
-- Фильтр по каталогу
WHERE A.CRN IN (SELECT CRN FROM SNP_REPL.V_CATALOG_LIST WHERE DOC_TYPE='RealizationPrices');


