--
-- V_ARH_PAYNOTES  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_PAYNOTES
(RN, COMPANY, CRN, PAY_PREFIX, PAY_NUMBER, 
 PAYER, PAY_DATE, FACEACC, FINOPER, VDOC_TYPE, 
 VDOC_NUMB, VDOC_DATE, FDOC_TYPE, FDOC_NUMB, FDOC_DATE, 
 CURRENCY, PAY_SUM, PAY_SUM_ACC, CURR_RATE, CURR_RATE_BASE, 
 FINSPEC, INTRDEBT, EDITABLE, PAYER_ACC, PAY_TYPE, 
 SERV_PAY, SIGNPLAN, PAY_PLAN, SIGNACNT, SIGNSPENT, 
 SIGNACTIVE, COMMENTS, ALTSIGN1, ALTSIGN2, ALTSIGN3, 
 ALTSIGN4, ALTSIGN5, ALTSIGN6, ALTSIGN7, ALTSIGN8, 
 ALTSIGN9, ALTSIGN10, TAXGROUP, SIGNOPACC, TDOC_TYPE, 
 TDOC_NUMB, TDOC_DATE, TAX_SUM, TAX_PERCENT, PAY_SUM_TRD, 
 CURR_RATE_ACC, CURR_RATE_PAY_ACC, CURR_RATE_TRD, CURR_RATE_BASE_TRD, GRAPHPOINT, 
 PAYTOOL, JUR_PERS, ESCORT_DOCTYPE, ESCORT_DOCNUMB, ESCORT_DOCDATE)
AS 
SELECT /*+ RULE */ A.*
FROM PARUS.PAYNOTES A, PARUS.FACEACC B, PARUS.FCACGR C
WHERE A.FACEACC=B.RN
  AND B.FCACGR=C.RN
  -- Фильтр по группе лицевых счетов
  AND C.CODE IN (SELECT FCACGR_TAG FROM SNP_REPL.V_FCACGR_LIST);


