--
-- V_ARH_PAYACCSPECS  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_PAYACCSPECS
(RN, COMPANY, CRN, PRN, TAXGR, 
 GOODSPARTY, STORE, NOMNMODIFPACK, NOMMODIF, ARTICLE, 
 PRICE, DISCOUNT, QUANT, EQUAL, QUANTALT, 
 PRICEMEAS, SUMM, SUMMWITHNDS, BEGINDATE, ENDDATE, 
 NOTE)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CRN","PRN","TAXGR","GOODSPARTY","STORE","NOMNMODIFPACK","NOMMODIF","ARTICLE","PRICE","DISCOUNT","QUANT","EQUAL","QUANTALT","PRICEMEAS","SUMM","SUMMWITHNDS","BEGINDATE","ENDDATE","NOTE"
FROM PARUS.PAYACCSPECS
WHERE PRN IN (SELECT RN FROM SNP_REPL.V_ARH_PAYACC);


