--
-- V_ARH_INCOMEFROMDEPS  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_INCOMEFROMDEPS
(RN, COMPANY, CRN, DOC_TYPE, DOC_PREF, 
 DOC_NUMB, DOC_DATE, WORK_DATE, DOC_STATE, VALID_DOCTYPE, 
 VALID_DOCNUMB, VALID_DOCDATE, OUT_DEPARTMENT, OUT_FACEACC, OUT_GRAPHPOINT, 
 OUT_STORE, STORE, AGENT, CURRENCY, STORE_OPER, 
 PARTY_RN, PARTY, NOTE, SUMM_PLAN, SUMM_FACT, 
 CURCOURS, CURBASECOURS, CURCOURS_DOC, CURBASECOURS_DOC, JUR_PERS)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CRN","DOC_TYPE","DOC_PREF","DOC_NUMB","DOC_DATE","WORK_DATE","DOC_STATE","VALID_DOCTYPE","VALID_DOCNUMB","VALID_DOCDATE","OUT_DEPARTMENT","OUT_FACEACC","OUT_GRAPHPOINT","OUT_STORE","STORE","AGENT","CURRENCY","STORE_OPER","PARTY_RN","PARTY","NOTE","SUMM_PLAN","SUMM_FACT","CURCOURS","CURBASECOURS","CURCOURS_DOC","CURBASECOURS_DOC","JUR_PERS" FROM PARUS.INCOMEFROMDEPS
-- Фильтр по складам-получателям (БЕЗ транзитных)
WHERE STORE IN (SELECT STORE_RN FROM SNP_REPL.V_STORE_LIST)
-- Фильтр по складам-отправителям (ВКЛЮЧАЯ транзитные)
   OR OUT_STORE IN (SELECT STORE_RN FROM SNP_REPL.V_STORE_LIST);


