--
-- V_ARH_BILLASSACT  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_BILLASSACT
(RN, COMPANY, CRN, ACT_TYPE, ACT_PREF, 
 ACT_NUMB, REG_DATE, AGENT_FROM, AGENT_ACT_NUMB, ACT_DATE, 
 VDOC_TYPE, VDOC_NUMB, VDOC_DATE, CURRENCY, NOM_SUM, 
 PRICE_SUM, DISC_SUM, NOM_SUM_BASE, PRICE_SUM_BASE, DISC_SUM_BASE, 
 DOC_SUM, DOC_SUM_BASE, DEST_SUM, DEST_SUM_BASE, ACC_STATE, 
 NOTE, SIGN_PRESENT, JUR_PERS, FACEACC)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CRN","ACT_TYPE","ACT_PREF","ACT_NUMB","REG_DATE","AGENT_FROM","AGENT_ACT_NUMB","ACT_DATE","VDOC_TYPE","VDOC_NUMB","VDOC_DATE","CURRENCY","NOM_SUM","PRICE_SUM","DISC_SUM","NOM_SUM_BASE","PRICE_SUM_BASE","DISC_SUM_BASE","DOC_SUM","DOC_SUM_BASE","DEST_SUM","DEST_SUM_BASE","ACC_STATE","NOTE","SIGN_PRESENT","JUR_PERS","FACEACC"
FROM PARUS.BILLASSACT
WHERE COMPANY=2 AND REG_DATE>=TO_DATE('01.09.2004','dd.mm.yyyy');


