--
-- V_ARH_SHEEPDIRSCUST  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_SHEEPDIRSCUST
(RN, COMPANY, CRN, DOCTYPE, PREF, 
 NUMB, DOCDATE, STATUS, WORK_DATE, SALEDATE, 
 STORE, DIRECTOR, FACEACC, GRAPHPOINT, AGENT, 
 STOPER, SHEEPVIEW, PAYTYPE, TARIF, CURRENCY, 
 CURCOURS, CURBASE, FA_COURS, FA_BASECOURS, DISCOUNT, 
 SUMM, SUMMWITHNDS, SERV_SUMM, SERV_SUMM_NDS, SHEEPSUMM, 
 COMMENTS, RESERVDATE, ACC_AGENT, SUBDIV, JUR_PERS)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CRN","DOCTYPE","PREF","NUMB","DOCDATE","STATUS","WORK_DATE","SALEDATE","STORE","DIRECTOR","FACEACC","GRAPHPOINT","AGENT","STOPER","SHEEPVIEW","PAYTYPE","TARIF","CURRENCY","CURCOURS","CURBASE","FA_COURS","FA_BASECOURS","DISCOUNT","SUMM","SUMMWITHNDS","SERV_SUMM","SERV_SUMM_NDS","SHEEPSUMM","COMMENTS","RESERVDATE","ACC_AGENT","SUBDIV","JUR_PERS" FROM PARUS.SHEEPDIRSCUST
-- Фильтр по складам-получателям (БЕЗ транзитных)
WHERE STORE IN (SELECT STORE_RN FROM SNP_REPL.V_STORE_LIST);


