--
-- V_ARH_CONSUMERORD  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_CONSUMERORD
(RN, COMPANY, CRN, ORD_DOCTYPE, ORD_PREF, 
 ORD_NUMB, AGENT, FACEACC, ORD_DATE, ORD_STATE, 
 STATE_DATE, DISP_TYPE, PAY_TYPE, TARIF, CURRENCY, 
 STORE, ACC_AGENT, SUBDIV, PAY_DATE, RELEASE_DATE, 
 PRICE_DATE, ORD_PERIOD, PERIOD_CORR, PERIOD_QUANT, PERIOD_TYPE, 
 PERIOD_LEN, ATSAMETIME, PRICE_TYPE, REDUCTION, NOTE, 
 AGNFI, PSUMWTAX, PSUMWOTAX, CONTRACT, JUR_PERS, 
 BLOCKED, GRAPHPOINT, RESERVDATE, ROUTE, CONSOLIDATED)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CRN","ORD_DOCTYPE","ORD_PREF","ORD_NUMB","AGENT","FACEACC","ORD_DATE","ORD_STATE","STATE_DATE","DISP_TYPE","PAY_TYPE","TARIF","CURRENCY","STORE","ACC_AGENT","SUBDIV","PAY_DATE","RELEASE_DATE","PRICE_DATE","ORD_PERIOD","PERIOD_CORR","PERIOD_QUANT","PERIOD_TYPE","PERIOD_LEN","ATSAMETIME","PRICE_TYPE","REDUCTION","NOTE","AGNFI","PSUMWTAX","PSUMWOTAX","CONTRACT","JUR_PERS","BLOCKED","GRAPHPOINT","RESERVDATE","ROUTE","CONSOLIDATED" FROM PARUS.CONSUMERORD
-- Фильтр по складам-получателям (БЕЗ транзитных)
WHERE STORE IN (SELECT STORE_RN FROM SNP_REPL.V_STORE_LIST);


