--
-- V_ARH_RLINVSHEETSPEC  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_RLINVSHEETSPEC
(RN, PRN, COMPANY, CRN, NOMEN, 
 NOMMODIF, NOMMODIFPACK, ARTICLE, GOODSSUPPLY, ACCQUANT, 
 ACCQUANTALT, FACTQUANT, FACTQUANTALT, PRICE, PRICEMEAS, 
 ACCSUM, FACTSUM, NOTE, MISCALC, MISCALCALT)
AS 
SELECT /*+ RULE */ "RN","PRN","COMPANY","CRN","NOMEN","NOMMODIF","NOMMODIFPACK","ARTICLE","GOODSSUPPLY","ACCQUANT","ACCQUANTALT","FACTQUANT","FACTQUANTALT","PRICE","PRICEMEAS","ACCSUM","FACTSUM","NOTE","MISCALC","MISCALCALT"
FROM PARUS.RLINVSHEETSPEC
WHERE PRN IN (SELECT RN FROM SNP_REPL.V_ARH_RLINVSHEET);


