--
-- V_ARH_REGPRICE  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_REGPRICE
(RN, PRN, COMPANY, ADATE, PRICE, 
 MEASTYPE, FORMULA, PRICE_CALC_RULE, TAXGR)
AS 
SELECT /*+ RULE */ "RN","PRN","COMPANY","ADATE","PRICE","MEASTYPE","FORMULA","PRICE_CALC_RULE","TAXGR"
FROM PARUS.REGPRICE
WHERE PRN IN (SELECT RN FROM SNP_REPL.V_ARH_GOODSSUPPLY);


