--
-- V_ARH_STPLGOODSSUPPLY  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_STPLGOODSSUPPLY
(RN, COMPANY, CELL, GOODSSUPPLY, ARTICLE, 
 QUANT, QUANTALT, QUANTPACK)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CELL","GOODSSUPPLY","ARTICLE","QUANT","QUANTALT","QUANTPACK"
FROM PARUS.STPLGOODSSUPPLY
WHERE GOODSSUPPLY IN (SELECT RN FROM SNP_REPL.V_ARH_GOODSSUPPLY);


