--
-- V_ARH_DOCINPT  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_DOCINPT
(RN, COMPANY, AUTHID, UNITCODE, DOCUMENT, 
 PRN_DOCUMENT, STATUS, IN_DATE, OUT_UNITCODE, BREAKUP_KIND)
AS 
SELECT /*+ RULE */ A.*
FROM PARUS.DOCINPT A
WHERE A.DOCUMENT IN (SELECT RN FROM SNP_REPL.V_ARH_DOCUMENTS);


