--
-- V_ARH_DICACCFI  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_DICACCFI
(RN, COMPANY, PREF_NUMB, REG_NUMB, DIR_RULE, 
 INCOME_DATE, ACC_NUMB, ACC_DATE, PR_CODE, PR_BANK_CODE, 
 PR_SENDER_CODE, CS_CODE, CS_BANK_CODE, CS_RECEIVER_CODE, BASE_TYPE, 
 BASE_NUMB, BASE_DATE, CONF_TYPE, CONF_NUMB, CONF_DATE, 
 COMMEN, ONCOME_DATE, PAY_DATE, INCLUDE_DATE, STORN_DATE, 
 CRN, WORK_DATE, WORK_STATE, EXPORT_SIGN, EXPORT_DATE, 
 JUR_PERS, WORK_STATE_TAX, INC_LIST_DATE)
AS 
SELECT /*+ RULE */ A.*
FROM PARUS.DICACCFI A
-- Фильтр по каталогу
WHERE A.CRN IN (SELECT CRN FROM SNP_REPL.V_CATALOG_LIST WHERE DOC_TYPE='AccountFactInput')
/* rn in (249603705,299774809,310664317,320627380,320980040,323358794)*/
;


