--
-- V_ARH_PAYACCINSPEC  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_PAYACCINSPEC
(RN, PRN, COMPANY, CRN, NOMEN, 
 NOMMODIF, NOMPACK, NOMMODIFPACK, SERNUMB, COUNTRY, 
 GTD, TAXGR, QUANT, QUANTALT, BEGINDATE, 
 ENDDATE, PRICE, PRICEMEAS, SUMMWITHNDS, SUMM, 
 PLANQUANT, FACTQUANT, PLANSUMM, FACTSUMM, STORE, 
 COMMENTS)
AS 
SELECT /*+ RULE */ "RN","PRN","COMPANY","CRN","NOMEN","NOMMODIF","NOMPACK","NOMMODIFPACK","SERNUMB","COUNTRY","GTD","TAXGR","QUANT","QUANTALT","BEGINDATE","ENDDATE","PRICE","PRICEMEAS","SUMMWITHNDS","SUMM","PLANQUANT","FACTQUANT","PLANSUMM","FACTSUMM","STORE","COMMENTS"
FROM PARUS.PAYACCINSPEC
WHERE PRN IN (SELECT RN FROM SNP_REPL.V_ARH_PAYACCIN);


