--
-- V_ARH_BILLCARD  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_BILLCARD
(RN, COMPANY, CRN, BILL_NOM, BILL_SER, 
 BILL_DATE, BILL_MAKER, BILL_HOLDER, BILL_TYPE, BILL_PLACE, 
 CURRENCY, BILL_VALUE, BILL_VALUE_BASE, NOM_TYPE, BILL_PAY_DATE, 
 GUARANTOR, PLAN_RECEIVER, NOTE, PROCENT, REG_DATE, 
 BILL_STATE, DESTINATION, PACKAGE_SIGN, AMOUNT, BILL_PAY_DATE_TO, 
 JUR_PERS)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CRN","BILL_NOM","BILL_SER","BILL_DATE","BILL_MAKER","BILL_HOLDER","BILL_TYPE","BILL_PLACE","CURRENCY","BILL_VALUE","BILL_VALUE_BASE","NOM_TYPE","BILL_PAY_DATE","GUARANTOR","PLAN_RECEIVER","NOTE","PROCENT","REG_DATE","BILL_STATE","DESTINATION","PACKAGE_SIGN","AMOUNT","BILL_PAY_DATE_TO","JUR_PERS" FROM PARUS.BILLCARD
WHERE COMPANY=2 AND REG_DATE>=TO_DATE('01.09.2004','dd.mm.yyyy');


