--
-- V_ARH_DOCOUTPT_PSV  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_DOCOUTPT_PSV
(RN, COMPANY, AUTHID, UNITCODE, DOCUMENT, 
 PRN_DOCUMENT, STATUS, IN_DATE, IN_UNITCODE, BREAKUP_KIND)
AS 
SELECT /* ORDERED */ A.*
FROM PARUS.DOCOUTPT A, SNP_REPL.V_ARH_DOCUMENTS_PSV B
WHERE A.DOCUMENT=B.RN;


