--
-- V_ARH_RLINVSHEET  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_RLINVSHEET
(RN, COMPANY, CRN, DOCTYPE, PREF, 
 NUMB, DOCDATE, STATUS, VDOCTYPE, VDOCNUMB, 
 VDOCDATE, STORE, MOL, CURRENCY, DIRECTOR, 
 ACCSUM, FACTSUM, MORESUM, MISSSUM, NOTE, 
 CELL)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CRN","DOCTYPE","PREF","NUMB","DOCDATE","STATUS","VDOCTYPE","VDOCNUMB","VDOCDATE","STORE","MOL","CURRENCY","DIRECTOR","ACCSUM","FACTSUM","MORESUM","MISSSUM","NOTE","CELL" FROM PARUS.RLINVSHEET
-- Фильтр по складам (БЕЗ транзитных)
WHERE STORE IN (SELECT STORE_RN FROM SNP_REPL.V_STORE_LIST)
--WHERE DOCDATE>=TO_DATE('01.10.2004','dd.mm.yyyy')
;


