--
-- V_ARH_DOCINPT_PSV  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_DOCINPT_PSV
(RN, COMPANY, AUTHID, UNITCODE, DOCUMENT, 
 PRN_DOCUMENT, STATUS, IN_DATE, OUT_UNITCODE, BREAKUP_KIND)
AS 
SELECT /*+ INDEX(A DOCINPT_COMPANY_DOCUMENT_RN_I) */ A.* 
FROM SNP_REPL.V_ARH_DOCUMENTS B, PARUS.DOCINPT A 
WHERE A.COMPANY=2 
  AND A.RN>=497796466 
  AND A.DOCUMENT=B.RN 
ORDER BY A.RN;


