--
-- V_ARH_INCOMDOC  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_INCOMDOC
(RN, COMPANY, CODE, AGENT, SUBDIV, 
 ENTRY_DATE, OUT_PARTY, STOR_SIGN, JUR_PERS, COMMIS_SIGN)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CODE","AGENT","SUBDIV","ENTRY_DATE","OUT_PARTY","STOR_SIGN","JUR_PERS","COMMIS_SIGN" FROM PARUS.INCOMDOC
WHERE ENTRY_DATE>=TO_DATE('01.09.2005','dd.mm.yyyy')
--WHERE RN IN (SELECT INDOC FROM SNP_REPL.V_ARH_GOODSPARTIES)
;


