--
-- V_ARH_TRANSINVCUST  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_TRANSINVCUST
(RN, COMPANY, CRN, DOCTYPE, PREF, 
 NUMB, DOCDATE, STATUS, WORK_DATE, SALEDATE, 
 ACCDOC, ACCNUMB, ACCDATE, DIRDOC, DIRNUMB, 
 DIRDATE, STOPER, FACEACC, GRAPHPOINT, AGENT, 
 TARIF, STORE, MOL, SHEEPVIEW, PAYTYPE, 
 DISCOUNT, CURRENCY, CURCOURS, CURBASE, FA_BASECOURS, 
 FA_COURS, SUMM, SUMMWITHNDS, SERV_SUMM, SERV_SUMM_NDS, 
 PLANPAYSUMM, FACTPAYSUMM, RECIPDOC, RECIPNUMB, RECIPDATE, 
 FERRYMAN, AGNFIFO, GETCONFIRM, WAYBLADENUMB, DRIVER, 
 CAR, ROUTE, TRAILER1, TRAILER2, BARCODE, 
 COMMENTS, FORWARDER, RESERVDATE, SALESREPORTDATE, ACC_AGENT, 
 SUBDIV, JUR_PERS, SERVACT_SIGN)
AS 
SELECT DISTINCT "RN","COMPANY","CRN","DOCTYPE","PREF","NUMB","DOCDATE","STATUS","WORK_DATE","SALEDATE","ACCDOC","ACCNUMB","ACCDATE","DIRDOC","DIRNUMB","DIRDATE","STOPER","FACEACC","GRAPHPOINT","AGENT","TARIF","STORE","MOL","SHEEPVIEW","PAYTYPE","DISCOUNT","CURRENCY","CURCOURS","CURBASE","FA_BASECOURS","FA_COURS","SUMM","SUMMWITHNDS","SERV_SUMM","SERV_SUMM_NDS","PLANPAYSUMM","FACTPAYSUMM","RECIPDOC","RECIPNUMB","RECIPDATE","FERRYMAN","AGNFIFO","GETCONFIRM","WAYBLADENUMB","DRIVER","CAR","ROUTE","TRAILER1","TRAILER2","BARCODE","COMMENTS","FORWARDER","RESERVDATE","SALESREPORTDATE","ACC_AGENT","SUBDIV","JUR_PERS","SERVACT_SIGN" FROM
(
SELECT /*+ RULE */ "RN","COMPANY","CRN","DOCTYPE","PREF","NUMB","DOCDATE","STATUS","WORK_DATE","SALEDATE","ACCDOC","ACCNUMB","ACCDATE","DIRDOC","DIRNUMB","DIRDATE","STOPER","FACEACC","GRAPHPOINT","AGENT","TARIF","STORE","MOL","SHEEPVIEW","PAYTYPE","DISCOUNT","CURRENCY","CURCOURS","CURBASE","FA_BASECOURS","FA_COURS","SUMM","SUMMWITHNDS","SERV_SUMM","SERV_SUMM_NDS","PLANPAYSUMM","FACTPAYSUMM","RECIPDOC","RECIPNUMB","RECIPDATE","FERRYMAN","AGNFIFO","GETCONFIRM","WAYBLADENUMB","DRIVER","CAR","ROUTE","TRAILER1","TRAILER2","BARCODE","COMMENTS","FORWARDER","RESERVDATE","SALESREPORTDATE","ACC_AGENT","SUBDIV","JUR_PERS","SERVACT_SIGN" FROM PARUS.TRANSINVCUST
WHERE
  -- Фильтр по складам
  STORE IN (SELECT STORE_RN FROM SNP_REPL.V_STORE_LIST)
UNION ALL
SELECT /*+ RULE */ "RN","COMPANY","CRN","DOCTYPE","PREF","NUMB","DOCDATE","STATUS","WORK_DATE","SALEDATE","ACCDOC","ACCNUMB","ACCDATE","DIRDOC","DIRNUMB","DIRDATE","STOPER","FACEACC","GRAPHPOINT","AGENT","TARIF","STORE","MOL","SHEEPVIEW","PAYTYPE","DISCOUNT","CURRENCY","CURCOURS","CURBASE","FA_BASECOURS","FA_COURS","SUMM","SUMMWITHNDS","SERV_SUMM","SERV_SUMM_NDS","PLANPAYSUMM","FACTPAYSUMM","RECIPDOC","RECIPNUMB","RECIPDATE","FERRYMAN","AGNFIFO","GETCONFIRM","WAYBLADENUMB","DRIVER","CAR","ROUTE","TRAILER1","TRAILER2","BARCODE","COMMENTS","FORWARDER","RESERVDATE","SALESREPORTDATE","ACC_AGENT","SUBDIV","JUR_PERS","SERVACT_SIGN" FROM PARUS.TRANSINVCUST
WHERE
  -- Фильтр по группе лицевых счетов
  STORE IS NULL AND FACEACC IN (SELECT B.RN FROM PARUS.FACEACC B, PARUS.FCACGR C WHERE B.FCACGR=C.RN  AND C.CODE IN (SELECT FCACGR_TAG FROM SNP_REPL.V_FCACGR_LIST))
/*SELECT -- RULE
"RN","COMPANY","CRN","DOCTYPE","PREF","NUMB","DOCDATE","STATUS","WORK_DATE","SALEDATE","ACCDOC","ACCNUMB","ACCDATE","DIRDOC","DIRNUMB","DIRDATE","STOPER","FACEACC","GRAPHPOINT","AGENT","TARIF","STORE","MOL","SHEEPVIEW","PAYTYPE","DISCOUNT","CURRENCY","CURCOURS","CURBASE","FA_BASECOURS","FA_COURS","SUMM","SUMMWITHNDS","SERV_SUMM","SERV_SUMM_NDS","PLANPAYSUMM","FACTPAYSUMM","RECIPDOC","RECIPNUMB","RECIPDATE","FERRYMAN","AGNFIFO","GETCONFIRM","WAYBLADENUMB","DRIVER","CAR","ROUTE","TRAILER1","TRAILER2","BARCODE","COMMENTS","FORWARDER","RESERVDATE","SALESREPORTDATE","ACC_AGENT","SUBDIV","JUR_PERS","SERVACT_SIGN" FROM PARUS.TRANSINVCUST
-- Фильтр по складам (БЕЗ транзитных)
WHERE STORE IN (SELECT STORE_RN FROM SNP_REPL.V_STORE_LIST)*/
);


