--
-- V_ARH_RESJOURNAL  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_RESJOURNAL
(RN, COMPANY, AUTHID, SUPPLY, RES_START_DATE, 
 RES_END_DATE, QUANT, QUANT_ALT, DOCTYPE, DOCDATE, 
 DOCPREF, DOCNUMB, NOTES)
AS 
SELECT /*+ RULE */ "RN","COMPANY","AUTHID","SUPPLY","RES_START_DATE","RES_END_DATE","QUANT","QUANT_ALT","DOCTYPE","DOCDATE","DOCPREF","DOCNUMB","NOTES" FROM PARUS.RESJOURNAL
WHERE SUPPLY IN (SELECT RN FROM SNP_REPL.V_ARH_GOODSSUPPLY);


