--
-- V_ARH_GOODSSUPPLYGRP  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_GOODSSUPPLYGRP
(RN, COMPANY, GROUP_LEVEL, NOMMODIF, NOMNMODIFPACK, 
 STORE, RESTPLAN, RESTPLANALT, RESTFACT, RESTFACTALT, 
 RESERV, RESERVALT)
AS 
SELECT /*+ RULE */ "RN","COMPANY","GROUP_LEVEL","NOMMODIF","NOMNMODIFPACK","STORE","RESTPLAN","RESTPLANALT","RESTFACT","RESTFACTALT","RESERV","RESERVALT" FROM PARUS.GOODSSUPPLYGRP
-- ‘ильтр по складам (¬ Ћё„јя транзитные)
WHERE STORE IN (SELECT STORE_RN FROM SNP_REPL.V_STORE_LIST);


