--
-- V_ARH_SHEEPDIRSDEPT  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_SHEEPDIRSDEPT
(RN, COMPANY, CRN, DOCTYPE, PREF, 
 NUMB, DOCDATE, STATUS, WORK_DATE, STORE, 
 DIRECTOR, FACEACC, GRAPHPOINT, STOPER, SHEEPVIEW, 
 SUBDIV, IN_STORE, CURRENCY, CURCOURS, CURBASE, 
 FA_CURCOURS, FA_CURBASE, SUMMWITHNDS, SERV_SUMM_NDS, SHEEPSUMM, 
 VALID_DOCTYPE, VALID_DOCNUMB, VALID_DOCDATE, COMMENTS, RESERVDATE, 
 JUR_PERS)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CRN","DOCTYPE","PREF","NUMB","DOCDATE","STATUS","WORK_DATE","STORE","DIRECTOR","FACEACC","GRAPHPOINT","STOPER","SHEEPVIEW","SUBDIV","IN_STORE","CURRENCY","CURCOURS","CURBASE","FA_CURCOURS","FA_CURBASE","SUMMWITHNDS","SERV_SUMM_NDS","SHEEPSUMM","VALID_DOCTYPE","VALID_DOCNUMB","VALID_DOCDATE","COMMENTS","RESERVDATE","JUR_PERS"
FROM PARUS.SHEEPDIRSDEPT
-- Фильтр по складам-получателям
WHERE STORE IN (SELECT STORE_RN FROM SNP_REPL.V_STORE_LIST);


