--
-- V_ARH_WROFFACTS  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_ARH_WROFFACTS
(RN, COMPANY, CRN, DOCTYPE, DOCNUMB, 
 DOCPREF, DOCDATE, STATUS, WORK_DATE, STORE, 
 AGENT, STOPER, CURRENCY, CURCOURSUM, CURBASESUM, 
 SUMM, BASESUMM, VALID_DOCTYPE, VALID_NUMB, VALID_DOCDATE, 
 COMMENTS, ALTSIGN1, ALTSIGN2, ALTSIGN3, ALTSIGN4, 
 ALTSIGN5, ALTSIGN6, ALTSIGN7, ALTSIGN8, ALTSIGN9, 
 ALTSIGN10, JUR_PERS)
AS 
SELECT /*+ RULE */ "RN","COMPANY","CRN","DOCTYPE","DOCNUMB","DOCPREF","DOCDATE","STATUS","WORK_DATE","STORE","AGENT","STOPER","CURRENCY","CURCOURSUM","CURBASESUM","SUMM","BASESUMM","VALID_DOCTYPE","VALID_NUMB","VALID_DOCDATE","COMMENTS","ALTSIGN1","ALTSIGN2","ALTSIGN3","ALTSIGN4","ALTSIGN5","ALTSIGN6","ALTSIGN7","ALTSIGN8","ALTSIGN9","ALTSIGN10","JUR_PERS"
FROM  PARUS.WROFFACTS
-- Фильтр по складам-получателям (БЕЗ транзитных)
WHERE STORE IN (SELECT STORE_RN FROM SNP_REPL.V_STORE_LIST);


