--
-- V_CATALOG_LIST  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_CATALOG_LIST
(DOC_TYPE, CRN, NAME)
AS 
SELECT /*+ RULE */ DISTINCT B.DOC_TYPE,A.RN,A.NAME FROM CATALOG_LIST B, PARUS.ACATALOG A
WHERE B.DOC_TYPE=A.DOCNAME
START WITH A.RN=B.CRN
CONNECT BY PRIOR A.RN=A.CRN;


