--
-- V_FCACGR_LIST  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_FCACGR_LIST
(FCACGR_TAG)
AS 
SELECT /*+ RULE */ FCACGR_TAG FROM FCACGR_LIST
UNION
SELECT CODE FROM FCACGR WHERE CRN IN (SELECT CRN FROM V_CATALOG_LIST WHERE DOC_TYPE='FaceAccGroups');


