--
-- V_REPL_DOCLINKS_DEL  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_REPL_DOCLINKS_DEL
(REPL_RN, REPL_USERNAME, REPL_TABLENAME, REPL_TABLERN, REPL_MODIFDATE, 
 REPL_OPERATION, REPL_AUTHID)
AS 
select /*+ RULE */
-- Удаления связей
u.RN+8000000000000 as REPL_RN,
'PARUS' as USERNAME,
u.TABLENAME,
u.TABLERN,
u.MODIFDATE,
u.OPERATION,
u.AUTHID
from parus.updatelist u
where u.TABLENAME='DOCLINKS'
and u.operation='D';


