--
-- V_REPL_PSV  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_REPL_PSV
(REPL_RN, REPL_USERNAME, REPL_TABLENAME, REPL_TABLERN, REPL_MODIFDATE, 
 REPL_OPERATION, REPL_AUTHID)
AS 
select /*+ INDEX(updatelist I_UPDATELIST_TABLE_RN) */
RN as REPL_RN,
'PARUS' as USERNAME,
TABLENAME,
TABLERN,
MODIFDATE,
OPERATION,
AUTHID from parus.updatelist;


