--
-- V_STORE_LIST  (View) 
--
CREATE OR REPLACE FORCE VIEW SNP_REPL.V_STORE_LIST
(STORE_RN, STORE_TAG, IS_TRANSIT, CRN)
AS 
SELECT /*+ RULE */ A.RN AS STORE_RN, B.STORE_TAG, B.IS_TRANSIT, A.CRN
FROM AZSAZSLISTMT A, SNP_REPL.STORE_LIST B
WHERE A.AZS_NUMBER=B.STORE_TAG
UNION
SELECT /*+ RULE */ A.RN as STORE_RN, A.AZS_NUMBER as STORE_TAG, B.IS_TRANSIT, A.CRN
FROM AZSAZSLISTMT A, SNP_REPL.CATALOG_LIST B
WHERE B.DOC_TYPE = 'AZSListView'
AND B.CRN=A.CRN;


