--
-- PARUS_AGNLIST  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.PARUS_AGNLIST
(RN, AGNABBR, AGNNAME, AGNIDNUMB, ECONCODE, 
 NATECONSECT, ORGCODE, CITYNAME, STREETNAME, ADDR_HOUSE, 
 ADDR_POST, PHONE, PHONE2, FAX, TELEX, 
 MAIL, PROPFORM)
AS 
SELECT "RN","AGNABBR","AGNNAME","AGNIDNUMB","ECONCODE","NATECONSECT","ORGCODE","CITYNAME","STREETNAME","ADDR_HOUSE","ADDR_POST","PHONE","PHONE2","FAX","TELEX","MAIL","PROPFORM" FROM VANEEV.V_AGNLIST_FOR_MASTER@oracle.world;


