--
-- PLAN_PROIZVODSTVO_SUT_VIEW  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.PLAN_PROIZVODSTVO_SUT_VIEW
(DATE_PLAN, OKP, KCCC, NAME_OIL_PRODUCT, PLAN_PROIZVODSTVO_SUT)
AS 
select "DATE_PLAN","OKP","KCCC","NAME_OIL_PRODUCT","PLAN_PROIZVODSTVO_SUT" from ART.plan_proizvodstvo_sut_view@ORA.LUNP.RU@ART;


