--
-- PLAN_RESU_OLD  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.PLAN_RESU_OLD
(DATE_PLAN, PROD_ID_NPR, PLAN_UTMSK, HRAN_UTMSK, OSTAT_UTMSK)
AS 
SELECT PLAN_REFINERY.DATE_PLAN,PLAN_REFINERY.PROD_ID_NPR,
SUM(PLAN_REFINERY.PLAN_UTMSK) AS PLAN_UTMSK, SUM(PLAN_REFINERY.HRAN_UTMSK) AS HRAN_UTMSK,
SUM(PLAN_REFINERY.OSTAT_UTMSK) AS OSTAT_UTMSK
FROM PLAN_REFINERY
GROUP BY PLAN_REFINERY.DATE_PLAN,PLAN_REFINERY.PROD_ID_NPR;


