--
-- V_1_FIPP_1010  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_1_FIPP_1010
(DOG_NUMBER, DOG_ID, DATE_BUXG, DATE_TO_PLAT, VES, 
 SUMMA_DOK, SUMMA_OPL)
AS 
SELECT 
  KLS_DOG.dog_number,
  BILLS.DOG_ID,
  BILLS.DATE_KVIT,
  BILLS.DATE_KVIT+BILLS.KOL_DN AS date_to_plat,
  SUM(kv.ves) AS ves,
  SUM(BILLS.summa_dok) AS summa_dok,
  0 AS summa_opl
  FROM BILLS,KLS_DOG,
    (SELECT KVIT.bill_id,SUM(ves) AS ves 
	 FROM KVIT,KLS_DOG,MONTH
	 WHERE 
	   KVIT.NOM_ZD=MONTH.nom_zd AND 
	   MONTH.dog_id=KLS_DOG.ID AND 
	   KLS_DOG.LUKDOG_ID=793 
	  GROUP BY bill_id
	) kv 
  WHERE BILLS.dog_id=KLS_DOG.ID  AND KLS_DOG.LUKDOG_ID=793 AND BILLS.nom_dok=kv.bill_id
  GROUP BY
    KLS_DOG.dog_number,
    BILLS.DOG_ID,
    BILLS.DATE_KVIT,
    BILLS.DATE_KVIT+BILLS.KOL_DN
UNION ALL
SELECT
  KLS_DOG.dog_number,
  OPL.DOG_ID,
  OPL.DATA_POR,
  OPL.DATA_POR,
  0 AS ves,
  0 AS summa_dok,
  SUM(OPL.SUMMA) AS summa_opl
  FROM OPL,KLS_DOG
  WHERE OPL.dog_id=KLS_DOG.ID AND KLS_DOG.LUKDOG_ID=793
  GROUP BY
    KLS_DOG.dog_number,
    OPL.DOG_ID,
    OPL.DATA_POR,
    OPL.DATA_POR;


