--
-- V_AGENT_REPORT_TARIF_2006  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_AGENT_REPORT_TARIF_2006
(NOM_DOK, TARIF_BN, TARIF_NDS, TARIF, TARIF_GUARD_BN, 
 TARIF_GUARD_NDS, TARIF_GUARD)
AS 
SELECT /*+ RULE */
  BILLS.NOM_DOK,
  SUM(NVL(KVIT.TARIF,0)) as TARIF_BN,
  SUM(NVL(KVIT.TARIF_NDS,0)) AS TARIF_NDS,
  SUM(NVL(KVIT.TARIF,0)+NVL(KVIT.TARIF_NDS,0)) AS TARIF,
  SUM(NVL(KVIT.TARIF_GUARD,0)) AS TARIF_GUARD_BN,
  SUM(NVL(KVIT.TARIF_GUARD_NDS,0)) AS TARIF_GUARD_NDS,
  SUM(NVL(KVIT.TARIF_GUARD,0)+NVL(KVIT.TARIF_GUARD_NDS,0)) AS TARIF_GUARD
FROM 
  BILLS, KVIT, 
  (SELECT distinct nom_perech,dat_perech 
     FROM (select * from V_MASTER_REPORTS where UPPER(REPORT_FILE)='OTCH_AGENT_2006.XLS') r,REESTR_RAIL_RGD_SF 
    WHERE DATE_SCH BETWEEN r.BEGIN_DATE AND r.END_DATE -- По дате счета РЖД
      AND r21=95) rail_sf  
WHERE BILLS.NOM_DOK = KVIT.BILL_ID
  AND KVIT.PERECH_TEXPD_DATE=rail_sf.dat_perech
  AND KVIT.PERECH_TEXPD_NUM=rail_sf.nom_perech
GROUP BY
  NOM_DOK;


