--
-- V_AZC_REALIZ_LIKARD  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_AZC_REALIZ_LIKARD
(ID_SOBSTV, ID_PROD, ID_ORG, SUMMA_VOL, SUMMA_VES)
AS 
select A.SOBSTV_ID as ID_SOBSTV, A.PROD_ID_NPR AS ID_PROD, A.ORG_STRU_ID as ID_ORG, SUM(A.VOLUME)  as SUMMA_VOL, SUM(A.VES) as SUMMA_VES   from azc_realiz_likard A
  GROUP BY A.SOBSTV_ID, A.PROD_ID_NPR, A.ORG_STRU_ID;


