--
-- V_AZS_REPORTS_TMP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_AZS_REPORTS_TMP
(TYPE_OPER_ID, DISCOUNT, ORG_STRU_ID, PROD_ID_NPR, OPER_DAY, 
 PRICE, VOLUME, MASSA, SUMMA)
AS 
SELECT "TYPE_OPER_ID","DISCOUNT","ORG_STRU_ID","PROD_ID_NPR","OPER_DAY","PRICE","VOLUME","MASSA","SUMMA" FROM AZS_REPORTS_TMP
WHERE TERMINAL_NAME = For_Init.GetCurrTerm
  AND OSUSER_NAME = For_Init.GetCurrUser;


