--
-- V_AZC_ORG  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_AZC_ORG
(ID_ORG, NAME_ORG, ID_PARENT_ORG, ID_ORG_TYPE, IS_ROOT)
AS 
SELECT ORG_RELATIONS.ORG_STRU_1_ID, ORG_STRUCTURE.NAME, DECODE(ORG_RELATIONS.ORG_STRU_2_ID,ORG_RELATIONS.ORG_STRU_1_ID, 0,ORG_RELATIONS.ORG_STRU_2_ID),
ORG_STRUCTURE.ORG_TYPE_ID,ORG_RELATIONS.is_root
FROM ORG_RELATIONS, ORG_STRUCTURE
WHERE ORG_STRUCTURE.ID = ORG_RELATIONS.ORG_STRU_1_ID
ORDER BY ORG_STRUCTURE.NAME;


