--
-- V_AZS_REPORTS_LAST  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_AZS_REPORTS_LAST
(ORG_STRU_ID, LAST_DAY)
AS 
SELECT ORG_STRU_ID,MAX(OPER_DAY) as LAST_DAY
FROM AZS_REPORTS_TMP
WHERE TERMINAL_NAME = For_Init.GetCurrTerm
  AND OSUSER_NAME = For_Init.GetCurrUser
GROUP BY ORG_STRU_ID;


