--
-- V_AZC_WEEK_PARUS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_AZC_WEEK_PARUS
(IS_OPT, AZC_GROUP_ORDER, AZC_GROUP_NAME, GROUP_ORDER, GROUP_NAME, 
 GROUP_FULL_NAME, KOD_OKDP, REALIZ, OSTATOK)
AS 
SELECT
  IS_OPT,
  AZC_GROUP_ORDER,
  AZC_GROUP_NAME,
  GROUP_ORDER,
  GROUP_NAME,
  GROUP_FULL_NAME,
  MAX(KOD_OKDP) AS KOD_OKDP,
  SUM(REALIZ) AS REALIZ,
  SUM(OSTATOK) AS OSTATOK
FROM
(
-- Розница из MASTER
SELECT
  0 AS IS_OPT,
  C.ID AS AZC_GROUP_ORDER,
  C.NAME AS AZC_GROUP_NAME,
  GROUP_ORDER,
  GROUP_NAME,
  GROUP_FULL_NAME,
  B.KOD_OKDP,
  FACT_REAL_VES AS REALIZ,
  END_OST AS OSTATOK
FROM V_FIL_SUT_REAL A,KLS_PROD B, AZC_PROD_GROUP C
WHERE A.PROD_ID_NPR=B.ID_NPR
AND B.AZC_PR_GRP_ID=C.ID
AND A.ORG_KIND_ID IN (5,12)
AND FILIAL_ID<>40
AND FILIAL_ID<>50
UNION ALL
-- Опт из MASTER
SELECT
  1 AS IS_OPT,
  C.ID AS AZC_GROUP_ORDER,
  C.NAME AS AZC_GROUP_NAME,
  GROUP_ORDER,
  GROUP_NAME,
  GROUP_FULL_NAME,
  B.KOD_OKDP,
  FACT_REAL_VES AS REALIZ,
  END_OST AS OSTATOK
FROM V_FIL_SUT_REAL A,KLS_PROD B, AZC_PROD_GROUP C
WHERE A.PROD_ID_NPR=B.ID_NPR
AND B.AZC_PR_GRP_ID=C.ID
AND A.ORG_KIND_ID=1
AND FILIAL_ID<>40
AND FILIAL_ID<>50
UNION ALL
-- Транзит из MASTER
SELECT
  2 AS IS_OPT,
  C.ID AS AZC_GROUP_ORDER,
  C.NAME AS AZC_GROUP_NAME,
  GROUP_ORDER,
  GROUP_NAME,
  GROUP_FULL_NAME,
  B.KOD_OKDP,
  FACT_REAL_VES AS REALIZ,
  END_OST AS OSTATOK
FROM V_FIL_SUT_TRANZIT A,KLS_PROD B, AZC_PROD_GROUP C
WHERE A.PROD_ID_NPR=B.ID_NPR
AND B.AZC_PR_GRP_ID=C.ID
AND A.ORG_KIND_ID=1
AND FILIAL_ID<>40
AND FILIAL_ID<>50
UNION ALL
-- Розница из Паруса
SELECT
  0 AS IS_OPT,
  E.ID AS AZC_GROUP_ORDER,
  E.NAME AS AZC_GROUP_NAME,
  C.GROUP_ORDER,
  C.GROUP_ABBR AS GROUP_NAME,
  C.GROUP_NAME AS GROUP_FULL_NAME,
  D.KOD_OKDP,
  usinsk.REALIZ,
  usinsk.OSTATOK
FROM
(
SELECT
  DECODE(A.NNOMEN,128857374, '10305', 72906864, '10421' , 95873245,'10315', 126748032,'10460', 72931860, '10421',173288904,'10351',A.NNOMEN) AS PROD_ID_NPR,
  A.REALIZ_ALL AS REALIZ,
  A.OSTATOK
FROM V_AZC_FROM_PARUS A
WHERE IS_AZC=1
) usinsk,
KLS_PROD_GROUPS_DESC B,
KLS_PROD_GROUPS C,
KLS_PROD D,
AZC_PROD_GROUP E
WHERE usinsk.PROD_ID_NPR=B.PROD_ID_NPR
AND B.PROD_GROUPS_ID=C.ID
AND C.PROD_TYPE_GRP_ID=5
AND usinsk.PROD_ID_NPR=D.ID_NPR
AND D.AZC_PR_GRP_ID=E.ID
--AND 1=0
UNION ALL
-- Опт из Паруса
SELECT
  1 AS IS_OPT,
  E.ID AS AZC_GROUP_ORDER,
  E.NAME AS AZC_GROUP_NAME,
  C.GROUP_ORDER,
  C.GROUP_ABBR AS GROUP_NAME,
  C.GROUP_NAME AS GROUP_FULL_NAME,
  D.KOD_OKDP,
  usinsk.REALIZ,
  usinsk.OSTATOK
FROM
(
SELECT
  DECODE(A.NNOMEN,128857374, '10305', 72906864, '10421' , 95873245,'10315', 126748032,'10460', 72931860, '10421',173288904,'10351',A.NNOMEN) AS PROD_ID_NPR,
  A.REALIZ_ALL AS REALIZ,
  A.OSTATOK
FROM v_azc_from_parus A
WHERE IS_AZC=0
) usinsk,
KLS_PROD_GROUPS_DESC B,
KLS_PROD_GROUPS C,
KLS_PROD D,
AZC_PROD_GROUP E
WHERE usinsk.PROD_ID_NPR=B.PROD_ID_NPR
AND B.PROD_GROUPS_ID=C.ID
AND C.PROD_TYPE_GRP_ID=5
AND usinsk.PROD_ID_NPR=D.ID_NPR
AND D.AZC_PR_GRP_ID=E.ID
--AND 1=0
)
GROUP BY
  IS_OPT,
  AZC_GROUP_ORDER,
  AZC_GROUP_NAME,
  GROUP_ORDER,
  GROUP_NAME,
  GROUP_FULL_NAME
ORDER BY
  IS_OPT,
  AZC_GROUP_ORDER,
  GROUP_ORDER;


