--
-- V_AZC_PROD_GROUP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_AZC_PROD_GROUP
(ID, NAME_NPR, AZC_PR_GRP_ID)
AS 
SELECT TO_NUMBER(a.ID_NPR) AS ID, A.NAME_NPR,A.AZC_PR_GRP_ID  FROM KLS_PROD A
WHERE A.AZC_PR_GRP_ID IS NOT NULL
UNION
SELECT B.ID, B.NAME, 0 AS azc_pr_grp_id FROM AZC_PROD_GROUP B;


