--
-- V_AZC_FROM_PARUS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_AZC_FROM_PARUS
(ID, OSUSER_NAME, TERMINAL_NAME, NNOMEN, SNOMEN, 
 NSTORE, SSTORE, REALIZ_ALL, REALIZ_AVG, IS_AZC, 
 OSTATOK)
AS 
SELECT "ID","OSUSER_NAME","TERMINAL_NAME","NNOMEN","SNOMEN","NSTORE","SSTORE","REALIZ_ALL","REALIZ_AVG","IS_AZC","OSTATOK" FROM AZC_FROM_PARUS
WHERE TERMINAL_NAME=For_Init.GetCurrTerm
  AND OSUSER_NAME=For_Init.GetCurrUser;


