--
-- V_BILLS_FOR_REAL_OPL  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_BILLS_FOR_REAL_OPL
(NOM_DOK, NOM_SF, DATE_VYP_SF, DATE_BUXG, DATE_KVIT, 
 KOL_DN, DOG_ID, USL_NUMBER, NOM_ZD, SUMMA_DOK, 
 OWNER_ID, PROD_ID_NPR)
AS 
SELECT  NOM_DOK,NOM_SF,DATE_VYP_SF,DATE_BUXG,DATE_KVIT,KOL_DN,DOG_ID,USL_NUMBER,NOM_ZD,SUMMA_DOK,OWNER_ID,PROD_ID_NPR FROM BILLS
UNION ALL
SELECT NOM_DOK,NOM_SF,DATA_DOK,DATA_BUXG,DATA_KVIT,KOL_DN,DOG_ID,K_USL,NOM_ZD,SUMMA_DOK,KOD_SOB,KOD_NFP FROM master.to_ss;


