--
-- V_BILLS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_BILLS
(IS_AGENT, NOM_DOK, NOM_SF, NPO_SF, DATE_VYP_SF, 
 DATE_KVIT, DATE_BUXG, DATE_MOS, SUMMA_DOK, NDS_DOK, 
 GSM_DOK, AKCIZ_DOK, PRIM, FIO_ISPOL, KOL_DN, 
 OLD_NOM_DOK, NOM_ZD, OWNER_ID, DOG_ID, USL_NUMBER, 
 PROD_ID_NPR, ORIG_DOG_ID, ORIG_USL_NUMBER, SNP_DOG_ID, SNP_USL_NUMBER, 
 ORIG_NOM_SF, ORIG_SUMMA_DOK, ORIG_NDS_DOK, ORIG_GSM_DOK, ORIG_AKCIZ_DOK, 
 OLD_NOM_SF, NUM_5_DAY, NAZN_OTG_ID, KORR_5_DAY, PROTO_NUM, 
 PROTO_DATE, NO_AKCIZ, KORR_PROD)
AS 
SELECT "IS_AGENT","NOM_DOK","NOM_SF","NPO_SF","DATE_VYP_SF","DATE_KVIT","DATE_BUXG","DATE_MOS","SUMMA_DOK","NDS_DOK","GSM_DOK","AKCIZ_DOK","PRIM","FIO_ISPOL","KOL_DN","OLD_NOM_DOK","NOM_ZD","OWNER_ID","DOG_ID","USL_NUMBER","PROD_ID_NPR","ORIG_DOG_ID","ORIG_USL_NUMBER","SNP_DOG_ID","SNP_USL_NUMBER","ORIG_NOM_SF","ORIG_SUMMA_DOK","ORIG_NDS_DOK","ORIG_GSM_DOK","ORIG_AKCIZ_DOK","OLD_NOM_SF","NUM_5_DAY","NAZN_OTG_ID","KORR_5_DAY","PROTO_NUM","PROTO_DATE","NO_AKCIZ","KORR_PROD" FROM V_BILLS_FIN_SNP
UNION ALL
SELECT "IS_AGENT","NOM_DOK","NOM_SF","NPO_SF","DATE_VYP_SF","DATE_KVIT","DATE_BUXG","DATE_MOS","SUMMA_DOK","NDS_DOK","GSM_DOK","AKCIZ_DOK","PRIM","FIO_ISPOL","KOL_DN","OLD_NOM_DOK","NOM_ZD","OWNER_ID","DOG_ID","USL_NUMBER","PROD_ID_NPR","ORIG_DOG_ID","ORIG_USL_NUMBER","SNP_DOG_ID","SNP_USL_NUMBER","ORIG_NOM_SF","ORIG_SUMMA_DOK","ORIG_NDS_DOK","ORIG_GSM_DOK","ORIG_AKCIZ_DOK","OLD_NOM_SF","NUM_5_DAY","NAZN_OTG_ID","KORR_5_DAY","PROTO_NUM","PROTO_DATE","NO_AKCIZ","KORR_PROD" FROM V_BILLS_FIN_UNP
UNION ALL
SELECT "IS_AGENT","NOM_DOK","NOM_SF","NPO_SF","DATE_VYP_SF","DATE_KVIT","DATE_BUXG","DATE_MOS","SUMMA_DOK","NDS_DOK","GSM_DOK","AKCIZ_DOK","PRIM","FIO_ISPOL","KOL_DN","OLD_NOM_DOK","NOM_ZD","OWNER_ID","DOG_ID","USL_NUMBER","PROD_ID_NPR","ORIG_DOG_ID","ORIG_USL_NUMBER","SNP_DOG_ID","SNP_USL_NUMBER","ORIG_NOM_SF","ORIG_SUMMA_DOK","ORIG_NDS_DOK","ORIG_GSM_DOK","ORIG_AKCIZ_DOK","OLD_NOM_SF","NUM_5_DAY","NAZN_OTG_ID","KORR_5_DAY","PROTO_NUM","PROTO_DATE","NO_AKCIZ","KORR_PROD" FROM V_BILLS_R3;


