--
-- V_BILLS_FIN_SNP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_BILLS_FIN_SNP
(IS_AGENT, NOM_DOK, NOM_SF, NPO_SF, DATE_VYP_SF, 
 DATE_KVIT, DATE_BUXG, DATE_MOS, SUMMA_DOK, NDS_DOK, 
 GSM_DOK, AKCIZ_DOK, PRIM, FIO_ISPOL, KOL_DN, 
 OLD_NOM_DOK, NOM_ZD, OWNER_ID, DOG_ID, USL_NUMBER, 
 PROD_ID_NPR, ORIG_DOG_ID, ORIG_USL_NUMBER, SNP_DOG_ID, SNP_USL_NUMBER, 
 ORIG_NOM_SF, ORIG_SUMMA_DOK, ORIG_NDS_DOK, ORIG_GSM_DOK, ORIG_AKCIZ_DOK, 
 OLD_NOM_SF, NUM_5_DAY, NAZN_OTG_ID, KORR_5_DAY, PROTO_NUM, 
 PROTO_DATE, NO_AKCIZ, KORR_PROD)
AS 
SELECT /*+ ALL_ROWS INDEX(BILLS BILLS_DATE_MOS_I) */
-- Счета-фактуры из комплекса ФИНАНСЫ
  BILLS.IS_AGENT,
  BILLS.NOM_DOK,
  BILLS.NOM_SF,
  BILLS.NPO_SF,
  BILLS.DATE_VYP_SF,
  BILLS.DATE_KVIT,
  BILLS.DATE_BUXG,
  BILLS.DATE_MOS,
  BILLS.LUK_SUMMA_DOK,
  BILLS.LUK_NDS_DOK,
  BILLS.GSM_DOK,
  BILLS.AKCIZ_DOK,
  BILLS.PRIM,
  BILLS.FIO_ISPOL,
  BILLS.KOL_DN,
  BILLS.OLD_NOM_DOK,
  BILLS.NOM_ZD,
  BILLS.OWNER_ID,
  BILLS.LUK_DOG_ID,
  BILLS.LUK_USL_NUMBER,
  BILLS.PROD_ID_NPR,
  BILLS.DOG_ID,
  BILLS.USL_NUMBER,
  BILLS.SNP_DOG_ID,
  BILLS.SNP_USL_NUMBER,
  BILLS.NOM_SF,
  BILLS.SUMMA_DOK,
  BILLS.NDS_DOK,
  BILLS.GSM_DOK,
  BILLS.AKCIZ_DOK,
  BILLS.OLD_NOM_SF,
  BILLS.NUM_5_DAY,
  BILLS.NAZN_OTG_ID,
  BILLS.KORR_5_DAY,
  BILLS.PROTO_NUM,
  BILLS.PROTO_DATE,
  BILLS.NO_AKCIZ,
  BILLS.KORR_PROD
FROM BILLS,BILLS_PRIMARY
WHERE BILLS_PRIMARY.PRIMARY_APPL='FIN_SNP'
  AND BILLS.DATE_MOS BETWEEN BILLS_PRIMARY.BEGIN_DATE AND BILLS_PRIMARY.END_DATE
  AND BILLS.IS_AGENT<3
  AND BILLS.NAZN_OTG_ID<>10;


