--
-- V_CB_KLSACC  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_CB_KLSACC
(BV_BIK, BV_ACC, ID, CITY, BALUNIT, 
 JUR_PERS, BANKDOKPREF, TYPE_OPER_IN, TYPE_OPER_OUT, BANK_DOCTYPE, 
 RN, ON_LINE, SBANK_DOCTYPE, STYPE_OPER_IN, STYPE_OPER_OUT, 
 SJURPERS, SBALUNIT, SCURRENCY, SMTP_HOST, EMAIL_NAME, 
 CATALOG)
AS 
SELECT kls_acc."BV_BIK",kls_acc."BV_ACC",kls_acc."ID",kls_acc."CITY",kls_acc."BANKDOKPREF",kls_acc."RN",kls_acc."ON_LINE",kls_acc."SBANK_DOCTYPE",kls_acc."STYPE_OPER_IN",kls_acc."STYPE_OPER_OUT",kls_acc."SJURPERS",kls_acc."SBALUNIT",kls_acc."SCURRENCY",kls_acc."SMTP_HOST",kls_acc."EMAIL_NAME",kls_acc."CATALOG",kls_acc."REMARK",kls_acc."IS_OK"
FROM   pvz.kls_acc@oracle.world;


