--
-- V_CHECK_PRICES  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_CHECK_PRICES
(ERROR_ID, ID, CAT_CEN_ID, PROD_ID, PROD_NAME, 
 BEGIN_DATE, END_DATE)
AS 
SELECT 
  1,
  V_NPR_PRICES.ID, 
  CAT_CEN_ID, 
  PROD_ID_NPR,
  KLS_PROD.NAME_NPR, 
  BEGIN_DATE , 
  END_DATE   
FROM V_NPR_PRICES,KLS_PROD
WHERE BEGIN_DATE>END_DATE
  AND PROD_ID_NPR = KLS_PROD.ID_NPR
UNION ALL
--- Пересечение периодов действия
SELECT 
  2,
  V_NPR_PRICES.ID, 
  CAT_CEN_ID, 
  PROD_ID_NPR, 
  KLS_PROD.NAME_NPR, 
  BEGIN_DATE , 
  END_DATE   
FROM V_NPR_PRICES,KLS_PROD
WHERE V_NPR_PRICES.ID in (select a.id from v_npr_prices a,v_npr_prices b where a.id<>b.id and 
             a.begin_date<=b.END_DATE and a.END_DATE>=b.begin_date and a.CAT_CEN_ID=b.CAT_CEN_ID and a.PROD_ID_NPR=b.PROD_ID_NPR)
  AND PROD_ID_NPR = KLS_PROD.ID_NPR
ORDER BY CAT_CEN_ID,NAME_NPR,BEGIN_DATE,END_DATE;


