--
-- V_DESIGNER_FOREIGN_KEYS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_DESIGNER_FOREIGN_KEYS
(TAB_NAME, PK_NAME, COL_NAME, POSITION)
AS 
SELECT DISTINCT UC.TABLE_NAME AS tab_name, UC.CONSTRAINT_NAME AS index_name,C.COLUMN_NAME AS col_name,C.POSITION
FROM SYS.USER_CONSTRAINTS UC, SYS.USER_CONS_COLUMNS C
WHERE UC.CONSTRAINT_TYPE='R'
AND UC.CONSTRAINT_NAME=C.CONSTRAINT_NAME
ORDER BY UC.TABLE_NAME, UC.CONSTRAINT_NAME,C.POSITION;


