--
-- V_DESIGNER_SEQUENCES  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_DESIGNER_SEQUENCES
(TAB_NAME, PK_NAME, COL_NAME, SEQ_NAME)
AS 
SELECT DISTINCT T.NAME AS tab_name, O.NAME AS index_name,C.NAME AS col_name, SQ.NAME AS seq_name
FROM designer6.SDD_TAB T, designer6.SDD_OCO O, designer6.SDD_OKY Y, designer6.SDD_COL C, designer6.SDD_OSQ SQ
WHERE O.PARENT_IVID=T.IVID AND O.TABLE_REF=T.IRID
AND Y.PARENT_IVID=O.PARENT_IVID AND Y.CONSTRAINT_REF=O.IRID
AND C.PARENT_IVID=Y.PARENT_IVID AND C.IRID=Y.COLUMN_REF
AND C.SEQUENCE_REF=SQ.IRID
AND T.ELEMENT_TYPE_NAME='TAB'
AND O.COMPLETE_FLAG='Y'
AND O.CONSTRAINT_TYPE='PRIMARY'
AND Y.CONSTRAINT_TYPE='PRIMARY'
ORDER BY T.NAME,O.NAME,C.NAME;


