--
-- V_DESIGNER_COLUMNS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_DESIGNER_COLUMNS
(TAB_NAME, SEQ_NUM, COL_NAME, DATATYPE, MAXIMUM_LENGTH, 
 DECIMAL_PLACES, NULL_INDICATOR, PROMPT)
AS 
SELECT DISTINCT C.TABLE_NAME, C.COLUMN_ID, C.COLUMN_NAME,
C.data_type,DECODE(C.data_type,'VARCHAR2',C.data_length,C.data_precision),NVL(C.data_scale,0),
C.NULLABLE,''
FROM sys.USER_TAB_COLUMNS C
ORDER BY C.TABLE_NAME, C.COLUMN_ID;


