--
-- V_DESIGNER_PRIMARY_KEYS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_DESIGNER_PRIMARY_KEYS
(TAB_NAME, PK_NAME, COL_NAME, POSITION, COL_TYPE)
AS 
SELECT DISTINCT UC.TABLE_NAME AS tab_name, UC.CONSTRAINT_NAME AS index_name,C.COLUMN_NAME AS col_name,C.POSITION, CC.DATA_TYPE
FROM SYS.USER_CONSTRAINTS UC, SYS.USER_CONS_COLUMNS C, sys.USER_TAB_COLUMNS CC
WHERE UC.CONSTRAINT_TYPE='P'
AND UC.CONSTRAINT_NAME=C.CONSTRAINT_NAME
AND C.TABLE_NAME=CC.TABLE_NAME
AND C.COLUMN_NAME=CC.COLUMN_NAME
ORDER BY UC.TABLE_NAME, UC.CONSTRAINT_NAME,C.POSITION;


