--
-- V_DICLACFO_POS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_DICLACFO_POS
(NOM_DOK, BILL_POS_PARUS_ID, VES, PROD, RN, 
 PRN, FOOD_RN, FOOD_PRN, FOOD_CODE, FOOD_TYPE, 
 FOOD_NAME, AMOUNT, MES_UNIT, MES_UNIT_NAME, CENA_BN, 
 SUM_BN, AKCIZ, GSM, SUM_WOUT, RATE_NDS, 
 SUM_NDS, CENA, SUM_TOTAL, ACC_DATE, ACC_PREF_SF, 
 ACC_NOM_SF, ACC_PRIM, CONF_DATE)
AS 
SELECT
  NOM_DOK,
  BILL_POS_PARUS_ID,
  SUM(VES) AS VES,
  MAX(PROD),
  MAX(RN),
  PRN,
  MAX(FOOD_RN),
  MAX(FOOD_PRN),
  MAX(FOOD_CODE),
  MAX(FOOD_TYPE),
  MAX(FOOD_NAME),
  SUM(AMOUNT),
  MAX(MES_UNIT),
  MAX(MES_UNIT_NAME),
  MAX(CENA_BN),
  SUM(SUM_BN),
  SUM(AKCIZ),
  SUM(GSM),
  SUM(SUM_WOUT),
  MAX(RATE_NDS),
  SUM(SUM_NDS),
  MAX(CENA),
  SUM(SUM_TOTAL),
  MAX(ACC_DATE),
  MAX(ACC_PREF_SF),
  MAX(ACC_NOM_SF),
  MAX(ACC_PRIM),
  MAX(CONF_DATE) FROM
(
    SELECT PRN AS NOM_DOK,
	       DECODE(B.PROD,NULL,0,'10010',10,'10013',13,'10011',11,'10012',12,'10092',DECODE(A.AMOUNT,1,12,11),'10020',20,1) AS BILL_POS_PARUS_ID,
	       DECODE(B.PROD,NULL,0,DECODE(A.MES_UNIT,17,A.AMOUNT/1000,15,0,A.AMOUNT)) AS VES,
		   DECODE(B.PROD,NULL,'     ','10092',DECODE(A.AMOUNT,1,'10012','10011'),B.PROD) AS PROD,
		   RN, PRN, FOOD_RN, FOOD_PRN, FOOD_CODE, FOOD_TYPE, FOOD_NAME, AMOUNT, MES_UNIT, MES_UNIT_NAME,
		   DECODE(A.MES_UNIT,17,CENA_BN*1000,15,0,CENA_BN) AS CENA_BN, SUM_BN, AKCIZ, GSM, SUM_WOUT, RATE_NDS, SUM_NDS,
		   DECODE(A.MES_UNIT,17,CENA*1000,15,0,CENA) AS CENA, SUM_TOTAL, ACC_DATE, ACC_PREF_SF,ACC_NOM_SF, ACC_PRIM, CONF_DATE
  	   FROM load_buffer.v_diclacfo A, KLS_PROD_NOMENKLATOR B
	  WHERE A.FOOD_RN = B.PARUS_RN(+)
	    AND A.FOOD_PRN = B.PARUS_PRN(+)
--		AND A.FOOD_CODE = B.MODIF(+)
)
GROUP BY NOM_DOK, BILL_POS_PARUS_ID,PRN
ORDER BY NOM_DOK, BILL_POS_PARUS_ID,PRN;


