--
-- V_DISP_AZS_MANUAL  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_DISP_AZS_MANUAL
(ID, BEG_DATE, END_DATE, ORG_STRU_ID, PROD_ID_NPR, 
 IN_O_VOL, IN_O_MAS, OUT_O_VOL, OUT_O_MAS, END_VOLUME, 
 END_MASSA, OUT_O_1_VOL, OUT_O_1_MAS, OUT_O_2_VOL, OUT_O_2_MAS, 
 OUT_O_3_VOL, OUT_O_3_MAS, OUT_O_4_VOL, OUT_O_4_MAS, OUT_O_5_VOL, 
 OUT_O_5_MAS, OUT_O_6_VOL, OUT_O_6_MAS, OUT_O_7_VOL, OUT_O_7_MAS, 
 LAST_DAY)
AS 
select "ID",BEG_DATE,END_DATE,"ORG_STRU_ID","PROD_ID_NPR","IN_O_VOL","IN_O_MAS","OUT_O_VOL","OUT_O_MAS","END_VOLUME","END_MASSA","OUT_O_1_VOL","OUT_O_1_MAS","OUT_O_2_VOL","OUT_O_2_MAS","OUT_O_3_VOL","OUT_O_3_MAS","OUT_O_4_VOL","OUT_O_4_MAS","OUT_O_5_VOL","OUT_O_5_MAS","OUT_O_6_VOL","OUT_O_6_MAS","OUT_O_7_VOL","OUT_O_7_MAS","LAST_DAY" from DISP_AZS_MANUAL
where TERMINAL = For_Init.GetCurrTerm
  AND OSUSER = For_Init.GetCurrUser;


