--
-- V_EMPTY_VOL  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_EMPTY_VOL
(PROD_ID_NPR, DATE_EMPTY_VOL, TIME_EMPTY_VOL, MAX_VOL, DEAD_VOL, 
 VOL, EMPTY_VOL)
AS 
SELECT PROD_ID_NPR,MAX(DATE_EMPTY_VOL), MAX(TIME_EMPTY_VOL), SUM(MAX_VOL),SUM(DEAD_VOL),SUM(VOL),SUM(EMPTY_VOL)
FROM PLAN_FACT
WHERE TIP_ROW='—¬.≈Ã Œ—“‹'
  AND TERMINAL_NAME = (SELECT UPPER(terminal) FROM sys.V_$SESSION WHERE audsid=USERENV('sessionid'))
  AND OSUSER_NAME = (SELECT UPPER(osuser) FROM sys.V_$SESSION WHERE audsid=USERENV('sessionid'))
GROUP BY PROD_ID_NPR;


