--
-- V_FIL_MES_REAL_GRP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_FIL_MES_REAL_GRP
(FILIAL_ORDER, FILIAL_NAME, ORG_KIND_ORDER, ORG_KIND_NAME, GROUP_ORDER, 
 GROUP_FULL_NAME, FACT_REAL_VES, PLAN_REAL_VES, NORMA_REAL_VES)
AS 
SELECT 
       FILIAL_ORDER 
       ,MAX(FILIAL_NAME) AS FILIAL_NAME 
	   ,ORG_KIND_ORDER 
	   ,MAX(ORG_KIND_NAME) AS ORG_KIND_NAME 
	   ,GROUP_ORDER 
  	   ,MAX(GROUP_FULL_NAME) AS GROUP_FULL_NAME 
	   ,SUM(FACT_REAL_VES) AS FACT_REAL_VES 
  	   ,SUM(PLAN_REAL_VES) AS PLAN_REAL_VES 
       ,SUM(NORMA_REAL_VES) AS NORMA_REAL_VES 
FROM 
(SELECT 
  (CASE 
     WHEN FILIAL_ORDER=3 OR FILIAL_ORDER=13 THEN 2 
	 ELSE 1 
  END) AS FILIAL_ORDER, 
  (CASE 
     WHEN FILIAL_ORDER=3 OR FILIAL_ORDER=13 THEN 'АРХАНГЕЛЬСК' 
	 ELSE 'КОМИ' 
  END) AS FILIAL_NAME, 
  (CASE 
  		WHEN ORG_KIND_ORDER=11 THEN 1 
  		WHEN ORG_KIND_ORDER=12 THEN 5 
  		WHEN ORG_KIND_ORDER=13 THEN 1 
		ELSE ORG_KIND_ORDER 
	END) AS ORG_KIND_ORDER, 
  (CASE 
  		WHEN ORG_KIND_ORDER=11 THEN 'Нефтебаза' 
  		WHEN ORG_KIND_ORDER=13 THEN 'Нефтебаза' 
  		WHEN ORG_KIND_ORDER=12 THEN 'АЗС' 
  		WHEN ORG_KIND_ORDER=0 THEN 'Транзит' 
		ELSE ORG_KIND_NAME 
   END) AS ORG_KIND_NAME, 
  (CASE 
  	   WHEN GROUP_ORDER=140 THEN 130 
	   ELSE GROUP_ORDER 
  	END) AS GROUP_ORDER, 
  (CASE 
  	   WHEN GROUP_ORDER IN (130,140) THEN 'Нефтебитумы' 
	   ELSE GROUP_FULL_NAME 
  	END) AS GROUP_FULL_NAME, 
  FACT_REAL_VES, 
  PLAN_REAL_VES, 
  NORMA_REAL_VES 
FROM V_FIL_SUT_REAL) A 
GROUP BY 
        FILIAL_ORDER 
		,ORG_KIND_ORDER 
		,GROUP_ORDER 
/*ORDER BY 
        FILIAL_ORDER 
		,ORG_KIND_ORDER 
		,GROUP_ORDER*/
UNION ALL
SELECT 
       FILIAL_ORDER 
       ,MAX(FILIAL_NAME) AS FILIAL_NAME 
	   ,ORG_KIND_ORDER 
	   ,MAX(ORG_KIND_NAME) AS ORG_KIND_NAME 
	   ,GROUP_ORDER 
  	   ,MAX(GROUP_FULL_NAME) AS GROUP_FULL_NAME 
	   ,SUM(FACT_REAL_VES) AS FACT_REAL_VES 
  	   ,SUM(PLAN_REAL_VES) AS PLAN_REAL_VES 
       ,SUM(NORMA_REAL_VES) AS NORMA_REAL_VES 
FROM 
(SELECT 
  (CASE 
     WHEN FILIAL_ORDER=3  OR FILIAL_ORDER=13 THEN 2 
	 ELSE 1 
  END) AS FILIAL_ORDER, 
  (CASE 
     WHEN FILIAL_ORDER=3 OR FILIAL_ORDER=13 THEN 'АРХАНГЕЛЬСК' 
	 ELSE 'КОМИ' 
  END) AS FILIAL_NAME, 
  (CASE 
  		WHEN ORG_KIND_ORDER=11 THEN 1 
  		WHEN ORG_KIND_ORDER=12 THEN 5 
  		WHEN ORG_KIND_ORDER=13 THEN 3 
		ELSE ORG_KIND_ORDER 
	END) AS ORG_KIND_ORDER, 
  (CASE 
  		WHEN ORG_KIND_ORDER=11 THEN 'Нефтебаза' 
  		WHEN ORG_KIND_ORDER=12 THEN 'АЗС' 
  		WHEN ORG_KIND_ORDER=13 THEN 'в т.ч. "Северный завоз"' 
  		WHEN ORG_KIND_ORDER=0 THEN 'Транзит' 
		ELSE ORG_KIND_NAME 
   END) AS ORG_KIND_NAME, 
  (CASE 
  	   WHEN GROUP_ORDER=140 THEN 130 
	   ELSE GROUP_ORDER 
  	END) AS GROUP_ORDER, 
  (CASE 
  	   WHEN GROUP_ORDER IN (130,140) THEN 'Нефтебитумы' 
	   ELSE GROUP_FULL_NAME 
  	END) AS GROUP_FULL_NAME, 
  FACT_REAL_VES, 
  PLAN_REAL_VES, 
  NORMA_REAL_VES 
FROM V_FIL_SUT_REAL
WHERE ORG_KIND_ORDER=13) B 
GROUP BY 
        FILIAL_ORDER 
		,ORG_KIND_ORDER 
		,GROUP_ORDER 
/*ORDER BY 
        FILIAL_ORDER 
		,ORG_KIND_ORDER 
		,GROUP_ORDER*/
;


