--
-- V_FIL_SUT_REAL  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_FIL_SUT_REAL
(DATE_BEGIN, DATE_END, DATE_PLAN, FILIAL_ORDER, FILIAL_ID, 
 FILIAL_NAME, ORG_KIND_ORDER, ORG_KIND_ID, ORG_KIND_NAME, ORG_STRU_ORDER, 
 ORG_STRU_ID, ORG_STRU_NAME, PROD_ID_NPR, GROUP_ORDER, GROUP_NAME, 
 GROUP_FULL_NAME, FACT_REAL_VES, AVG_SUT_REAL_VES, FACT_REAL_SUMMA, AVG_SUT_REAL_SUMMA, 
 END_OST, PLAN_REAL_VES, NORMA_REAL_VES)
AS 
SELECT
DATE_BEGIN, DATE_END, DATE_PLAN, FILIAL_ORDER,FILIAL_ID, FILIAL_NAME,
 ORG_KIND_ORDER, ORG_KIND_ID, ORG_KIND_NAME,
 ORG_STRU_ORDER, ORG_STRU_ID, ORG_STRU_NAME,
 PROD_ID_NPR, GROUP_ORDER, GROUP_NAME, GROUP_FULL_NAME,
 FACT_REAL_VES, AVG_SUT_REAL_VES, FACT_REAL_SUMMA, AVG_SUT_REAL_SUMMA, END_OST,PLAN_REAL_VES, NORMA_REAL_VES
 FROM PLAN_FACT_REALIZ
WHERE (TIP_ROW='—”“Œ◊Õ¿ﬂ –≈¿À»«¿÷»ﬂ' OR TIP_ROW='—”“Œ◊Õ¿ﬂ –≈¿À»«¿÷»ﬂ (“–¿Õ«»“)')
  AND TERMINAL_NAME = For_Init.GetCurrTerm
  AND OSUSER_NAME = For_Init.GetCurrUser
  AND GROUP_ORDER IS NOT NULL;


