--
-- V_FINREPORT_9_FIPP_OPL  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_FINREPORT_9_FIPP_OPL
(PAYFORM_ID, GROUPDOG_ID, GOSPROG_ID, PREDPR_NAME, DOG_ID, 
 DATA_POST, SUMMA)
AS 
SELECT
       10,
	   NVL(KLS_dog.GROUPDOG_ID,6),
	   NVL(opl.program,0),
	   KLS_PREDPR.PREDPR_NAME,
       OPL.dog_id,
	   opl.data_post, opl.summa
  FROM MASTER.opl,
       kls_dog,
	   KLS_PREDPR
 WHERE ((opl.DOG_ID = KLS_dog.ID) AND (KLS_dog.PREDPR_ID=KLS_PREDPR.ID));


