--
-- V_FIN_REESTR_DEBKRED  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_FIN_REESTR_DEBKRED
(ID, PREDPR_NAME, DOG_NUMBER, DOG_DATE, SUMMA_DOK, 
 PROSR, SUMMA_PAYED, SUMMA_KRED, SUMMA_TO_PAY_THIS_MONTH, SUMMA_PAYED_THIS_MONTH, 
 DATE_PROSR, DATE_REPORT)
AS 
SELECT
  kls_predpr.unp_id as id,
  kls_predpr.PREDPR_NAME,
  kls_dog.DOG_NUMBER,
  kls_dog.DOG_DATE,
  DECODE(V_FIN_REESTR_DEB.SUMMA_DOK,NULL,0,V_FIN_REESTR_DEB.SUMMA_DOK) AS SUMMA_DOK,
  DECODE(V_FIN_REESTR_DEB.PROSR,NULL,0,V_FIN_REESTR_DEB.PROSR) AS PROSR,
  DECODE(V_FIN_REESTR_DEB.SUMMA_PAYED,NULL,0,V_FIN_REESTR_DEB.SUMMA_PAYED) AS SUMMA_PAYED,
  DECODE(V_FIN_REESTR_KRED.SUMMA_KRED,NULL,0,V_FIN_REESTR_KRED.SUMMA_KRED) AS SUMMA_KRED,
  DECODE(V_FIN_REESTR_DEB.SUM_TO_PAY_THIS_MONTH,NULL,0,V_FIN_REESTR_DEB.SUM_TO_PAY_THIS_MONTH) AS SUMMA_TO_PAY_THIS_MONTH,
  DECODE(V_FIN_REESTR_KRED.SUM_PAYED_THIS_MONTH,NULL,0,V_FIN_REESTR_KRED.SUM_PAYED_THIS_MONTH) AS SUMMA_PAYED_THIS_MONTH,
  DECODE(V_FIN_REESTR_DEB.DATE_PROSR,NULL,TO_DATE('01.01.2050','dd.mm.yyyy'),V_FIN_REESTR_DEB.DATE_PROSR) AS DATE_PROSR,
  NVL(For_Temp.GET_AS_DATE('DATE_END','MASTER','REESTR_DEBKRED.XLS'),TRUNC(SYSDATE)) AS date_report
  FROM kls_predpr,kls_dog,V_FIN_REESTR_DEB,V_FIN_REESTR_KRED
  WHERE
    kls_predpr.ID=kls_dog.PREDPR_ID and
	kls_dog.id=V_FIN_REESTR_DEB.DOG_ID(+) and
	kls_dog.ID=V_FIN_REESTR_KRED.DOG_ID(+) and
	kls_dog.AGENT_ID in (8,4175) and
	(V_FIN_REESTR_DEB.SUMMA_DOK is not null or V_FIN_REESTR_KRED.SUMMA_KRED is not null)
ORDER BY
  kls_predpr.UNP_ID,
  kls_dog.DOG_NUMBER;


