--
-- V_GD_AGENT_2006_GU12_KORR  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GD_AGENT_2006_GU12_KORR
(GU12_A_ID, ZAYV_NUM, ZAYV_DATE, RAZN_NUM, RAZN_DATE, 
 FROM_DATE, TO_DATE, BEGIN_DATE, END_DATE, STAN_ID, 
 STAN_NAME, PROD_ID, PROD_NAME, IS_KORR, KOL, 
 VES)
AS 
SELECT
  /* Корректировки заявок в отчетном месяце */
  GU12_A_ID,
  ZAYV_NUM,
  ZAYV_DATE,
  RAZN_NUM,
  RAZN_DATE,
  FROM_DATE,
  TO_DATE,
  BEGIN_DATE,
  END_DATE,
  STAN_ID,
  STAN_NAME,
  PROD_ID,
  PROD_NAME,
  IS_KORR,
  SUM(DECODE(IS_KORR,2,-1,1)*KOL) as KOL,
  SUM(DECODE(IS_KORR,2,-1,1)*VES) as VES
FROM V_GD_AGENT_2006_GU12
WHERE IS_KORR IN (1,2)
  AND from_date BETWEEN BEGIN_DATE AND END_DATE
GROUP BY
  GU12_A_ID,
  ZAYV_NUM,
  ZAYV_DATE,
  RAZN_NUM,
  RAZN_DATE,
  FROM_DATE,
  TO_DATE,
  BEGIN_DATE,
  END_DATE,
  STAN_ID,
  STAN_NAME,
  PROD_ID,
  PROD_NAME,
  IS_KORR
HAVING IS_KORR=2 OR SUM(DECODE(IS_KORR,2,-1,1)*KOL)<>0;


