--
-- V_GD_AGENT_2006_GU12_ZAYV_KR_2  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GD_AGENT_2006_GU12_ZAYV_KR_2
(GU12_A_ID, STAN_ID, BEGIN_DATE, END_DATE, FROM_DATE, 
 TO_DATE, ZAYV_DATE, ZAYV_NUM, STAN_NAME, PROD_NAME, 
 KOL, VES, FACT_KOL, FACT_VES, KORR_DATE, 
 KORR_NUM, KORR_KOL, KORR_VES, IS_KORR)
AS 
SELECT
  /* Заявки отчетного месяца с корректировками и отгрузкой */
  a.GU12_A_ID,
  a.STAN_ID,
  a.BEGIN_DATE,
  a.END_DATE,
  a.FROM_DATE,
  a.TO_DATE,
  a.ZAYV_DATE,
  a.ZAYV_NUM,
  a.STAN_NAME,
  a.PROD_NAME,
  a.ORIG_KOL as KOL,
  a.ORIG_VES as VES,
  NVL(b.FACT_KOL,0) as FACT_KOL,
  NVL(b.FACT_VES,0) as FACT_VES,
  c.KORR_DATE,
  c.KORR_NUM,
  c.KORR_KOL,
  c.KORR_VES,
  c.IS_KORR
FROM V_GD_AGENT_2006_GU12_ZAYV_2 a,
(
SELECT GU12_A_ID,STAN_ID,SUM(CLIENT_KOL) as FACT_KOL, SUM(CLIENT_VES) as FACT_VES FROM V_GD_AGENT_2006_GU12_LIST GROUP BY GU12_A_ID,STAN_ID
) b,
(
SELECT GU12_A_ID,STAN_ID,RAZN_DATE as KORR_DATE, RAZN_NUM as KORR_NUM, SUM(KOL) as KORR_KOL, SUM(VES) as KORR_VES,IS_KORR
  FROM V_GD_AGENT_2006_GU12_KORR GROUP BY GU12_A_ID,STAN_ID,RAZN_DATE,RAZN_NUM,IS_KORR
) c
WHERE a.GU12_A_ID=b.GU12_A_ID(+)
  AND a.STAN_ID=b.STAN_ID(+)
  AND a.GU12_A_ID=c.GU12_A_ID(+)
  AND a.STAN_ID=c.STAN_ID(+);


