--
-- V_GD_AGENT_2006_GU12_ZAYV_2  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GD_AGENT_2006_GU12_ZAYV_2
(GU12_A_ID, ZAYV_NUM, ZAYV_DATE, ZAKR_DATE, FROM_DATE, 
 TO_DATE, BEGIN_DATE, END_DATE, FOX_KOD, STAN_ID, 
 STAN_NAME, PROD_ID, PROD_NAME, IS_KORR, ORIG_KOL, 
 ORIG_VES, KOL, VES)
AS 
SELECT 
  /* «а€вки отчетного мес€ца, закрытые в отчетном мес€це */ 
  "GU12_A_ID","ZAYV_NUM","ZAYV_DATE","ZAKR_DATE","FROM_DATE","TO_DATE","BEGIN_DATE","END_DATE","FOX_KOD","STAN_ID","STAN_NAME","PROD_ID","PROD_NAME","IS_KORR","ORIG_KOL","ORIG_VES","KOL","VES" 
FROM V_GD_AGENT_2006_GU12_GRP 
WHERE zakr_date BETWEEN BEGIN_DATE AND END_DATE
  AND from_date>=BEGIN_DATE;


