--
-- V_GU12_CARD_DATE  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_CARD_DATE
(DATE_O, SOBVAG, KOL_PLAN, VES_PLAN, KOL_FAKT, 
 VES_FAKT)
AS 
SELECT
DATE_O
,SOBVAG
,SUM(A.KOL_PLAN) AS KOL_PLAN
,SUM(A.VES_PLAN) AS VES_PLAN
,SUM(A.KOL_FAKT) AS KOL_FAKT
,SUM(A.VES_FAKT) AS VES_FAKT
FROM V_GU12_CARD_N A
GROUP BY DATE_O,SOBVAG
ORDER BY DATE_O,SOBVAG;


