--
-- V_GU12_REP_SPISOK_ZAYAV  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_REP_SPISOK_ZAYAV
(PROD, NOM_Z, STAN, KOL_PLAN, VES_PLAN, 
 KOL_FAKT, VES_FAKT, REG_DATE, FROM_DATE, TO_DATE, 
 SOGL_DATE)
AS 
SELECT PROD
	   ,NOM_Z
	   ,STAN
	   ,SUM(KOL_PLAN) AS KOL_PLAN
	   ,SUM(VES_PLAN) AS VES_PLAN
	   ,SUM(KOL_FAKT) AS KOL_FAKT
	   ,SUM(VES_FAKT) AS VES_FAKT
	   ,MAX(REG_DATE) AS REG_DATE
	   ,MAX(FROM_DATE) AS FROM_DATE
	   ,MAX(TO_DATE) AS TO_DATE
	   ,MAX(SOGL_DATE) AS SOGL_DATE
FROM (
--KVIT
SELECT /*+ ORDERED USE_NL(K,M,A) */
  PGD.NAME AS PROD
  ,A.NOM_Z
  ,S.STAN_NAME AS STAN
  ,0 AS KOL_PLAN
  ,0 AS VES_PLAN
  ,1 AS KOL_FAKT
  ,K.VES_BRUTTO AS VES_FAKT
  ,TO_DATE('01.01.2000','DD.MM.YYYY') AS REG_DATE
  ,TO_DATE('01.01.2000','DD.MM.YYYY') AS FROM_DATE
  ,TO_DATE('01.01.2000','DD.MM.YYYY') AS TO_DATE
  ,TO_DATE('01.01.2000','DD.MM.YYYY') AS SOGL_DATE
FROM
  KVIT K
  ,MONTH M
  ,KLS_VID_OTGR VO
  ,KLS_PROD P
  ,KLS_PROD_GU12 PGD
  ,GU12_A A
  ,V_GU12_STAN_NAZN S
  ,KLS_DOG D
  ,V_GU12_PLAT PL
WHERE
  K.NOM_ZD=M.NOM_ZD(+)
  AND M.LOAD_ABBR=VO.LOAD_ABBR(+)
  AND K.PROD_ID_NPR=P.ID_NPR(+)
  AND P.PROD_GU12_ID=PGD.ID(+)
  AND M.GU12_A_ID=A.ID(+)
  AND M.STAN_ID=S.ID(+)
--  AND K.DATE_OFORML>=TO_DATE(SUBSTR(FOR_TEMP.GET_AS_CHAR('DBEG_MONTH'),1,10)||' 17:00:00','DD.MM.YYYY HH24:MI:SS')
--  AND K.DATE_OFORML<TO_DATE(SUBSTR(FOR_TEMP.GET_AS_CHAR('DEND_MONTH'),1,10)||' 17:00:00','DD.MM.YYYY HH24:MI:SS')
  AND K.DATE_KVIT>=FOR_TEMP.GET_AS_DATE('DBEG_SPIS','MASTER','GU12')
  AND K.DATE_KVIT<=FOR_TEMP.GET_AS_DATE('DEND_SPIS','MASTER','GU12')
  AND VO.LOAD_TYPE_ID=1
  AND M.DOG_ID=D.ID
  AND D.PREDPR_ID=PL.PLAT_ID
  AND NOT A.SOGL_DATE IS NULL
  AND D.PREDPR_ID=FOR_TEMP.GET_AS_NUM('PLATID_SPIS','MASTER','GU12')
UNION ALL
-- GU12
SELECT
  P.NAME AS PROD
  ,A.NOM_Z
  ,S.STAN_NAME AS STAN
  ,BR.KOL_VAG AS KOL_PLAN
  ,BR.VES AS VES_PLAN
  ,0 AS KOL_FAKT
  ,0 AS VES_FAKT
  ,A.REG_DATE
  ,A.FROM_DATE
  ,A.TO_DATE
  ,A.SOGL_DATE
FROM
  GU12_BR BR
  ,GU12_B B
  ,GU12_A A
  ,KLS_PROD_GU12 P
  ,V_GU12_PLAT PL
  ,V_GU12_STAN_NAZN S
WHERE
  BR.ID_B=B.ID
  AND B.ID_A=A.ID
  AND A.PROD_ID=P.ID
  AND PL.PLAT_ID=B.PLAT_ID
  AND S.ID=B.STAN_ID
  AND BR.DATE_R BETWEEN FOR_TEMP.GET_AS_DATE('DBEG_SPIS','MASTER','GU12') AND FOR_TEMP.GET_AS_DATE('DEND_SPIS','MASTER','GU12')
  AND BR.KOL_VAG<>0
  AND B.ISCOR<>2
  AND NOT A.SOGL_DATE IS NULL
  AND B.PLAT_ID=FOR_TEMP.GET_AS_NUM('PLATID_SPIS','MASTER','GU12'))
GROUP BY PROD
	     ,NOM_Z
	     ,STAN
ORDER BY PROD
	     ,NOM_Z
	     ,STAN;


