--
-- V_GU12_STAN_NAZN  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_STAN_NAZN
(ID, STAN_KOD, STAN_NAME, STATES_ID, STATES_NAME, 
 STATES_KOD)
AS 
SELECT 
A.ID
,A.STAN_KOD
,A.STAN_NAME||', '||B.SHORT_NAME AS STAN_NAME
,C.ID AS STATES_ID
,C.SHORT_NAME AS STATES_NAME
,C.GD_KOD AS STATES_KOD
FROM 
KLS_STAN A
,KLS_GDOR B
,KLS_STATES C
WHERE A.GDOR_ID=B.ID(+)
AND A.STATES_ID=C.ID(+)
AND A.ID<>0;


