--
-- V_GU12_REP_OTGR  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_REP_OTGR
(NOM_Z, PROD, STAN, PRINVAG, KOL_P, 
 VES_P, KOL_S, VES_S)
AS 
SELECT
NOM_Z
,PROD
,STAN
,PRINVAG
,SUM(KOL_P) AS KOL_P
,SUM(VES_P) AS VES_P
,SUM(KOL_S) AS KOL_S
,SUM(VES_S) AS VES_S
FROM
(SELECT /*+ ORDERED USE_NL(K,M,A) */
  A.NOM_Z
  ,PGD.NAME AS PROD
  ,S.STAN_NAME AS STAN
  ,(CASE
  		WHEN OW.VAGOWN_TYP_ID=0 THEN 'Ï'
		ELSE 'Ñ'
    END) AS PRINVAG  
  ,(CASE
  		WHEN OW.VAGOWN_TYP_ID=0 THEN 1
		ELSE 0
    END) AS KOL_P  
  ,(CASE
  		WHEN OW.VAGOWN_TYP_ID=0 THEN K.VES_BRUTTO
		ELSE 0
    END) AS VES_P  
  ,(CASE
  		WHEN OW.VAGOWN_TYP_ID=0 THEN 0
		ELSE 1
    END) AS KOL_S  
  ,(CASE
  		WHEN OW.VAGOWN_TYP_ID=0 THEN 0
		ELSE K.VES_BRUTTO
    END) AS VES_S  
FROM
  KVIT K
  ,MONTH M
  ,KLS_VID_OTGR VO
  ,KLS_PROD P
  ,KLS_PROD_GU12 PGD
  ,GU12_A A
  ,V_GU12_STAN_NAZN S
  ,KLS_VAGOWNER OW
WHERE
  K.NOM_ZD=M.NOM_ZD(+)
  AND M.LOAD_ABBR=VO.LOAD_ABBR(+)
  AND K.PROD_ID_NPR=P.ID_NPR(+)
  AND P.PROD_GU12_ID=PGD.ID(+)
  AND M.GU12_A_ID=A.ID(+)
  AND M.STAN_ID=S.ID(+)
  AND K.DATE_OFORML>=TO_DATE(SUBSTR(FOR_TEMP.GET_AS_CHAR('DBEG_OTGR','MASTER','GU12'),1,10)||' 17:00:00','DD.MM.YYYY HH24:MI:SS')
  AND K.DATE_OFORML<TO_DATE(SUBSTR(FOR_TEMP.GET_AS_CHAR('DEND_OTGR','MASTER','GU12'),1,10)||' 17:00:00','DD.MM.YYYY HH24:MI:SS')
  AND VO.LOAD_TYPE_ID=1
  AND K.VAGOWNER_ID=OW.ID)
GROUP BY NOM_Z,PROD,STAN,PRINVAG
ORDER BY NOM_Z,PROD,STAN,PRINVAG;


