--
-- V_GU12_PLAT  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_PLAT
(PLAT_ID, PLAT_NAME, FULLPLAT)
AS 
SELECT /* RULE */ DISTINCT 
  KLS_PREDPR.ID AS PLAT_ID
  ,KLS_PREDPR.SHORT_NAME AS PLAT_NAME
  ,KLS_PREDPR.PREDPR_NAME AS FULLPLAT
FROM KLS_PREDPR,KLS_DOG
WHERE KLS_PREDPR.ID=KLS_DOG.PREDPR_ID
  AND DOG_YEAR>=2003
ORDER BY PLAT_NAME;


