--
-- V_GU12_CARD  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_CARD
(DATE_O, STAN_ID, KOL_CORR, VES_CORR, KOL_PLAN, 
 VES_PLAN, KOL_FAKT, VES_FAKT, ISCOR)
AS 
SELECT
BR.DATE_R AS DATE_O
,B.STAN_ID
,(CASE WHEN B.ISCOR=1 THEN BR.KOL_VAG ELSE 0 END) AS KOL_CORR
,(CASE WHEN B.ISCOR=1 THEN BR.VES ELSE 0 END) AS VES_CORR
,BR.KOL_VAG AS KOL_PLAN
,BR.VES AS VES_PLAN
,0 AS KOL_FAKT
,0 AS VES_FAKT
,B.ISCOR AS ISCOR
FROM
GU12_A A
,GU12_B B
,GU12_BR BR
WHERE
A.ID=FOR_TEMP.GET_AS_NUM('ID_ZAYAV','MASTER','GU12')
AND A.ID=B.ID_A
AND B.ID=BR.ID_B
UNION ALL
SELECT
--TRUNC(K.DATE_OFORML) AS DATE_O
(CASE
	WHEN K.DATE_OFORML>=TO_DATE(TO_CHAR(TRUNC(K.DATE_OFORML),'DD.MM.YYYY')||' 17:00:00','DD.MM.YYYY HH24:MI:SS') THEN TRUNC(K.DATE_OFORML)+1
	ELSE TRUNC(K.DATE_OFORML)
END) AS DATE_O
,M.STAN_ID
,0 AS KOL_CORR
,0 AS VES_CORR
,0 AS KOL_PLAN
,0 AS VES_PLAN
,1 AS KOL_FAKT
,K.VES AS VES_FAKT
,0 AS ISCOR
FROM
KVIT K
,MONTH M
WHERE
K.NOM_ZD=M.NOM_ZD
AND M.GU12_A_ID=FOR_TEMP.GET_AS_NUM('ID_ZAYAV','MASTER','GU12');


