--
-- V_GU12_REP_PLANFAKT_EXP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_REP_PLANFAKT_EXP
(PROD, NOM_Z, STAN, EXPED, VLADPUT, 
 PRINVAG, DATE_O, KOL_PLAN, VES_PLAN, KOL_FAKT, 
 VES_FAKT)
AS 
SELECT PROD
	   ,NOM_Z
	   ,STAN
	   ,EXPED
	   ,VLADPUT
	   ,PRINVAG
	   ,DATE_O
	   ,SUM(KOL_PLAN) AS KOL_PLAN
	   ,SUM(VES_PLAN) AS VES_PLAN
	   ,SUM(KOL_FAKT) AS KOL_FAKT
	   ,SUM(VES_FAKT) AS VES_FAKT
FROM (
--KVIT
SELECT /*+ ORDERED USE_NL(K,M,A) */
  PGD.NAME AS PROD
  ,A.NOM_Z
  ,S.STAN_NAME AS STAN
  ,E.PREDPR_NAME AS EXPED
  ,(CASE WHEN A.VLADPUT_ID=2641 THEN 'ÑÍÏ'
  		 WHEN A.VLADPUT_ID=2120 THEN 'ÑÌÍ'
		 ELSE 'ÑÊÑ'
    END) AS VLADPUT
	,(CASE
		  WHEN VW.VAGOWN_TYP_ID=0 THEN 'Ï'
		  WHEN VW.VAGOWN_TYP_ID=1 THEN 'Ñ'
		  ELSE 'À'
	  END) AS PRINVAG
  ,(CASE
	WHEN K.DATE_OFORML>=TO_DATE(TO_CHAR(TRUNC(K.DATE_OFORML),'DD.MM.YYYY')||' 17:00:00','DD.MM.YYYY HH24:MI:SS') THEN TRUNC(K.DATE_OFORML)+1
	ELSE TRUNC(K.DATE_OFORML)
    END) AS DATE_O
  ,0 AS KOL_PLAN
  ,0 AS VES_PLAN
  ,1 AS KOL_FAKT
  ,K.VES_BRUTTO AS VES_FAKT
FROM
  KVIT K
  ,MONTH M
  ,KLS_VID_OTGR VO
  ,KLS_PROD P
  ,KLS_PROD_GU12 PGD
  ,GU12_A A
  ,V_GU12_STAN_NAZN S
  ,V_GU12_EXPED E
  ,KLS_VAGOWNER VW
WHERE
  K.NOM_ZD=M.NOM_ZD(+)
  AND M.LOAD_ABBR=VO.LOAD_ABBR(+)
  AND K.PROD_ID_NPR=P.ID_NPR(+)
  AND P.PROD_GU12_ID=PGD.ID(+)
  AND M.GU12_A_ID=A.ID(+)
  AND M.STAN_ID=S.ID(+)
  AND K.DATE_OFORML>=TO_DATE(SUBSTR(FOR_TEMP.GET_AS_CHAR('DBEG_MONTH','MASTER','GU12'),1,10)||' 17:00:00','DD.MM.YYYY HH24:MI:SS')-1
  AND K.DATE_OFORML<TO_DATE(SUBSTR(FOR_TEMP.GET_AS_CHAR('DEND_MONTH','MASTER','GU12'),1,10)||' 17:00:00','DD.MM.YYYY HH24:MI:SS')
  AND VO.LOAD_TYPE_ID=1
  AND M.IS_EXP=1
  AND A.EXPED_ID=E.ID(+)
  AND K.VAGOWNER_ID=VW.ID
UNION ALL
-- GU12
SELECT
  P.NAME AS PROD
  ,A.NOM_Z
  ,S.STAN_NAME AS STAN
  ,E.PREDPR_NAME AS EXPED
  ,(CASE WHEN A.VLADPUT_ID=2641 THEN 'ÑÍÏ'
  		 WHEN A.VLADPUT_ID=2120 THEN 'ÑÌÍ'
		 ELSE 'ÑÊÑ'
    END) AS VLADPUT
  ,TRIM(PV.ABBR) AS PRINVAG
  ,BR.DATE_R AS DATE_O
  ,BR.KOL_VAG AS KOL_PLAN
  ,BR.VES AS VES_PLAN
  ,0 AS KOL_FAKT
  ,0 AS VES_FAKT
FROM
  GU12_BR BR
  ,GU12_B B
  ,GU12_A A
  ,KLS_PROD_GU12 P
  ,V_GU12_STAN_NAZN S
  ,V_GU12_EXPED E
  ,KLS_GD_PRINVAG PV
WHERE
  BR.ID_B=B.ID
  AND B.ID_A=A.ID
  AND A.PROD_ID=P.ID
  AND S.ID=B.STAN_ID
  AND BR.DATE_R BETWEEN FOR_TEMP.GET_AS_DATE('DBEG_MONTH','MASTER','GU12') AND FOR_TEMP.GET_AS_DATE('DEND_MONTH','MASTER','GU12')
  AND BR.KOL_VAG<>0
  AND B.ISCOR<>2
  AND NOT A.SOGL_DATE IS NULL
  AND NOT A.EXPED_ID IS NULL
  AND A.EXPED_ID=E.ID(+)
  AND B.PRINVAG_ID=PV.ID
)
GROUP BY PROD
	     ,NOM_Z
	     ,STAN
	     ,EXPED
		 ,VLADPUT
		 ,PRINVAG
		 ,DATE_O
ORDER BY PROD
	     ,NOM_Z
	     ,STAN
	     ,EXPED
		 ,VLADPUT
		 ,PRINVAG
		 ,DATE_O;


