--
-- V_GU12_OTPRAV  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_OTPRAV
(GROTP_ID, SHORT_NAME, GROTP_OKPO, PREDPR_NAME, OTPR_ADR, 
 GROTP_RS, BANK_NAME)
AS 
SELECT DISTINCT 
	   KLS_TEX_PD.GROTP_ID
	   ,KLS_PREDPR.SHORT_NAME
	   ,Trim(KLS_PREDPR.OKPO) AS GROTP_OKPO
	   ,KLS_PREDPR.PREDPR_NAME
	   ,KLS_PREDPR.POSTINDEX_P||' '||KLS_PREDPR.CITY_P||' '||KLS_PREDPR.ADDRESS_P AS OTPR_ADR
	   ,KLS_PREDPR.RS AS GROTP_RS
	   ,KLS_BANKS.BANK_NAME
FROM KLS_TEX_PD
	 LEFT JOIN KLS_PREDPR ON KLS_TEX_PD.GROTP_ID=KLS_PREDPR.ID
	 LEFT JOIN KLS_BANKS ON KLS_PREDPR.BANKS_ID=KLS_BANKS.ID 
WHERE GROTP_ID<>0 AND KLS_TEX_PD.ID<>0;


