--
-- V_GU12_PLATTAR  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_PLATTAR
(PLATTAR_ID, DOGOVOR, SHORT_NAME, PREDPR_NAME, OKPO, 
 GD_KOD, PLATTAR_ADR, RS, BANK_NAME)
AS 
SELECT PL.*
,KLS_PREDPR.SHORT_NAME
,KLS_PREDPR.PREDPR_NAME
,KLS_PREDPR.OKPO
,KLS_PREDPR.GD_KOD
,KLS_PREDPR.POSTINDEX_P||' '||KLS_PREDPR.CITY_P||' '||KLS_PREDPR.ADDRESS_P AS PLATTAR_ADR 
,KLS_PREDPR.RS
,KLS_BANKS.BANK_NAME 
FROM
(SELECT PLATTARIF_ID AS PLATTAR_ID, MAX(ID) AS DOGOVOR
 FROM KLS_TEX_PD
 WHERE PLATTARIF_ID<>0
 GROUP BY PLATTARIF_ID) PL
LEFT JOIN KLS_PREDPR ON PL.PLATTAR_ID=KLS_PREDPR.ID
LEFT JOIN KLS_BANKS ON KLS_PREDPR.BANKS_ID=KLS_BANKS.ID;


