--
-- V_GU12_REP_ZAYAV  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_REP_ZAYAV
(ID, NOM_Z, FROM_DATE, TO_DATE, PROD_ID, 
 PROD, REG_DATE, SOGL_DATE, GROTP_ID, OTPRAV, 
 GROTP_OKPO, OTPR_ADR, GROTP_RS, OTPR_BANK, PLATTAR_ID, 
 PLATTAR, PLATTAR_KOD, PLATTAR_OKPO, PLATTAR_ADR, PLT_RS, 
 PLT_BANK, EXPED_ID, EXPED, EXPED_OKPO, EXPED_ADR, 
 RODVAG_ID, RODVAG, STAT_NAGR, DOGOVOR, STANOTPR_ID, 
 STANOTPR, STANKODOTPR, PODACH_ID, PODACH, VIDSOOB_ID, 
 VIDSOOB, GR_GRUZ_ID, GR_GRUZ, GR_GRUZ_ABBR, PRIZNOTPR_ID, 
 PRIZNOTPR, VLADPUT_ID, VLADPUT, VLADPUT_OKPO, ID_NOSOGL, 
 SOGL)
AS 
SELECT
Z.ID,
Z.NOM_Z,
Z.FROM_DATE,
Z.TO_DATE,
Z.PROD_ID,
KP.NAME AS PROD,
Z.REG_DATE,
Z.SOGL_DATE,
Z.GROTP_ID,
O.PREDPR_NAME AS OTPRAV,
O.GROTP_OKPO,
O.OTPR_ADR,
O.GROTP_RS,
O.BANK_NAME AS OTPR_BANK,
Z.PLATTAR_ID,
PLT.PREDPR_NAME AS PLATTAR,
PLT.GD_KOD AS PLATTAR_KOD,
PLT.OKPO AS PLATTAR_OKPO,
PLT.PLATTAR_ADR,
PLT.RS AS PLT_RS,
PLT.BANK_NAME AS PLT_BANK,
Z.EXPED_ID,
E.PREDPR_NAME AS EXPED,
E.OKPO AS EXPED_OKPO,
E.EXPED_ADR,
Z.RODVAG_ID,
RV.NAME AS RODVAG,
KP.STAT_NAGR AS STAT_NAGR,
Z.DOGOVOR,
Z.STANOTPR_ID,
SO.STAN_NAME AS STANOTPR,
SO.STAN_KOD AS STANKODOTPR,
Z.PODACH_ID,
POD.NAME AS PODACH,
Z.VIDSOOB_ID AS VIDSOOB_ID,
SOOB.NAME AS VIDSOOB,
Z.GR_GRUZ_ID,
GRGR.NAME AS GR_GRUZ,
GRGR.ABBR AS GR_GRUZ_ABBR,
Z.PRIZNOTPR_ID,
PROT.TAG AS PRIZNOTPR,
Z.VLADPUT_ID,
VP.VLADPUT,
VP.VLADPUT_OKPO,
Z.ID_NOSOGL,
Z.SOGL
FROM
GU12_A Z,
V_GU12_OTPRAV O,
V_GU12_PLATTAR PLT,
V_GU12_EXPED E,
KLS_PROD_GU12 KP,
KLS_GD_VAGTYPE RV,
V_GU12_STAN_OTPR SO,
KLS_GD_PODACH POD,
KLS_GD_SOOB SOOB,
KLS_GD_GROUP GRGR,
KLS_GD_OTPR PROT,
V_GU12_VLADPUT VP
WHERE
Z.ID=FOR_TEMP.GET_AS_NUM('ID_ZAYAV','MASTER','GU12')
AND Z.GROTP_ID=O.GROTP_ID(+)
AND Z.PLATTAR_ID=PLT.PLATTAR_ID(+)
AND Z.EXPED_ID=E.ID(+)
AND Z.PROD_ID=KP.ID(+)
AND Z.RODVAG_ID=RV.ID(+)
AND Z.STANOTPR_ID=SO.STAN_ID(+)
AND Z.PODACH_ID=POD.ID(+)
AND Z.VIDSOOB_ID=SOOB.ID(+)
AND Z.GR_GRUZ_ID=GRGR.ID(+)
AND Z.PRIZNOTPR_ID=PROT.ID(+)
AND Z.VLADPUT_ID=VP.VLADPUT_ID(+)
ORDER BY ID;


