--
-- V_GU12_CARD_DATE_STAN_N  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_CARD_DATE_STAN_N
(DATE_O, STAN_ID, KOL_PLAN, VES_PLAN, KOL_FAKT, 
 VES_FAKT, KOL_PLAN_P, KOL_PLAN_S, VES_PLAN_P, VES_PLAN_S, 
 KOL_FAKT_P, KOL_FAKT_S, VES_FAKT_P, VES_FAKT_S)
AS 
SELECT
DATE_O
,STAN_ID
,SUM(A.KOL_PLAN) AS KOL_PLAN
,SUM(A.VES_PLAN) AS VES_PLAN
,SUM(A.KOL_FAKT) AS KOL_FAKT
,SUM(A.VES_FAKT) AS VES_FAKT
,SUM(CASE WHEN A.SOBVAG='Ï' THEN A.KOL_PLAN ELSE 0 END) AS KOL_PLAN_P
,SUM(CASE WHEN A.SOBVAG='Ï' THEN 0 ELSE A.KOL_PLAN END) AS KOL_PLAN_S
,SUM(CASE WHEN A.SOBVAG='Ï' THEN A.VES_PLAN ELSE 0 END) AS VES_PLAN_P
,SUM(CASE WHEN A.SOBVAG='Ï' THEN 0 ELSE A.VES_PLAN END) AS VES_PLAN_S
,SUM(CASE WHEN A.SOBVAG='Ï' THEN A.KOL_FAKT ELSE 0 END) AS KOL_FAKT_P
,SUM(CASE WHEN A.SOBVAG='Ï' THEN 0 ELSE A.KOL_FAKT END) AS KOL_FAKT_S
,SUM(CASE WHEN A.SOBVAG='Ï' THEN A.VES_FAKT ELSE 0 END) AS VES_FAKT_P
,SUM(CASE WHEN A.SOBVAG='Ï' THEN 0 ELSE A.VES_FAKT END) AS VES_FAKT_S
FROM V_GU12_CARD_N A
GROUP BY DATE_O,STAN_ID
ORDER BY DATE_O,STAN_ID;


