--
-- V_GU12_VLADPUT  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_VLADPUT
(VLADPUT_ID, VLADPUT, VLADPUT_OKPO)
AS 
SELECT P.ID AS VLADPUT_ID,P.PREDPR_NAME||', '||P.CITY_P||', '||P.ADDRESS_P AS VLADPUT,P.OKPO AS VLADPUT_OKPO
FROM KLS_PREDPR P,PREDPR_ROLE R
WHERE P.ID=R.PREDPR_ID AND R.KLS_ROLE_ID=5
UNION
SELECT 1111 AS VLADPUT_ID,'ннн "яебепйнлокейрярпни", ц.сурю, ск.гюбндяйюъ, 16'  AS VLADPUT,'12891286' AS VLADPUT_OKPO
FROM DUAL;


