--
-- V_GU12_STAN_OTPR  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_STAN_OTPR
(STAN_ID, STAN_KOD, STAN_NAME, OTDELENIE)
AS 
SELECT KLS_STAN.ID AS STAN_ID,KLS_STAN.STAN_KOD,KLS_STAN.STAN_NAME||','||KLS_GDOR.GDOR_NAME||' æ.ä.' AS STAN_NAME,'7' AS OTDELENIE
FROM KLS_STAN
LEFT JOIN KLS_GDOR ON KLS_STAN.GDOR_ID=KLS_GDOR.ID
WHERE KLS_STAN.ID IN(2250,3110);


