--
-- V_GU12_STAN_PER  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_STAN_PER
(ID, STAN_NAME, STANPER_KOD)
AS 
SELECT S.ID,S.STAN_NAME||', '||D.SHORT_NAME AS STAN_NAME,S.STAN_KOD AS STANPER_KOD
FROM KLS_STAN S,KLS_GDOR D,STAN_ROLE R
WHERE S.GDOR_ID=D.ID AND S.ID=R.STAN_ID AND R.KLS_ROLE_ID=1 
ORDER BY STAN_NAME;


