--
-- V_GU12_GRAF_1  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_GRAF_1
(DATE_R, PRINVAG, KOL, VES)
AS 
SELECT
BR.DATE_R,
PV.ABBR AS PRINVAG,
SUM(BR.KOL_VAG) AS KOL,
SUM(BR.VES) AS VES
FROM GU12_BR BR,GU12_B B,GU12_A A,KLS_GD_PRINVAG PV
WHERE A.ID=B.ID_A
AND B.ID=BR.ID_B
AND A.ID=FOR_TEMP.GET_AS_NUM('ID_ZAYAV','MASTER','GU12')
AND b.PRINVAG_ID=PV.ID
GROUP BY DATE_R,ABBR
ORDER BY DATE_R,ABBR;


