--
-- V_GU12_REP_PLAN_SNP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_REP_PLAN_SNP
(PROD, NOM_Z, PLAT_NAME, STAN_NAME, DATE_R, 
 KOL, VES)
AS 
SELECT 
NVL(NP.NAME_NPR,'   ') AS PROD
,A.NOM_Z
,PL.PLAT_NAME
,S.STAN_NAME
,BR.DATE_R
,SUM(BR.KOL_VAG) AS KOL
,SUM(BR.VES) AS VES
FROM 
GU12_BR BR
,GU12_B B
,GU12_A A
,KLS_PROD NP
,V_GU12_PLAT PL
,V_GU12_STAN_NAZN S
WHERE BR.ID_B=B.ID
AND B.ID_A=A.ID
AND BR.ID_NPR=NP.ID_NPR(+)
AND PL.PLAT_ID=B.PLAT_ID
AND S.ID=B.STAN_ID
AND BR.DATE_R BETWEEN FOR_TEMP.GET_AS_DATE('DBEG_PLAN','MASTER','GU12') AND FOR_TEMP.GET_AS_DATE('DEND_PLAN','MASTER','GU12')
AND BR.KOL_VAG<>0
AND B.ISCOR<>2
AND (CASE
         WHEN FOR_TEMP.GET_AS_NUM('USER_UNP','MASTER','GU12')=1 THEN 2641
		 ELSE PL.PLAT_ID
	 END)=2641
GROUP BY PLAT_NAME,NOM_Z,NAME_NPR,STAN_NAME,DATE_R
ORDER BY PLAT_NAME,NOM_Z,NAME_NPR,STAN_NAME,DATE_R;


