--
-- V_GU12_GRAF_PER  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_GRAF_PER
(PROD, M_OTGR, EXPED, PRINVAG, DATE_R, 
 KOL, VES)
AS 
SELECT PROD,M_OTGR,EXPED,PRINVAG,DATE_R,SUM(KOL) AS KOL,SUM(VES) AS VES
FROM (
      SELECT
      KP.NAME AS PROD
      ,(CASE
            WHEN A.VLADPUT_ID=1111 THEN 'мог'
            WHEN A.VLADPUT_ID=2952 THEN 'мог'
            WHEN A.VLADPUT_ID=2120 THEN 'ялм'
	        ELSE 'ялм'
        END) AS M_OTGR
      ,E.PREDPR_NAME AS EXPED
      ,PV.ABBR AS PRINVAG
      ,BR.DATE_R
      ,BR.KOL_VAG AS KOL
      ,BR.VES AS VES
      FROM GU12_BR BR
      ,GU12_B B
      ,GU12_A A
      ,KLS_GD_PRINVAG PV
      ,KLS_PROD_GU12 KP
      ,V_GU12_EXPED E
      WHERE A.ID=B.ID_A
      AND B.ID=BR.ID_B
      AND BR.DATE_R BETWEEN FOR_TEMP.GET_AS_DATE('DBEG_GRAF','MASTER','GU12') AND FOR_TEMP.GET_AS_DATE('DEND_GRAF','MASTER','GU12')
      AND B.PRINVAG_ID=PV.ID
      AND A.PROD_ID=KP.ID(+)
      AND A.EXPED_ID=E.ID(+)
	  AND A.SOGL_DATE IS NOT NULL
	  AND B.ISCOR<>2)
GROUP BY PROD,M_OTGR,EXPED,PRINVAG,DATE_R
ORDER BY PROD,M_OTGR,EXPED,PRINVAG,DATE_R;


