--
-- V_GU12_REP_PLAN  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_REP_PLAN
(PROD, PLAT_NAME, STAN_NAME, DATE_R, KOL, 
 VES)
AS 
SELECT P.NAME AS PROD,PL.PLAT_NAME,S.STAN_NAME,BR.DATE_R,SUM(BR.KOL_VAG) AS KOL,SUM(BR.VES) AS VES
FROM GU12_BR BR,GU12_B B,GU12_A A,KLS_PROD_GU12 P,V_GU12_PLAT PL,V_GU12_STAN_NAZN S
WHERE BR.ID_B=B.ID
AND B.ID_A=A.ID
AND A.PROD_ID=P.ID
AND PL.PLAT_ID=B.PLAT_ID
AND S.ID=B.STAN_ID
AND BR.DATE_R BETWEEN FOR_TEMP.GET_AS_DATE('DBEG_PLAN','MASTER','GU12') AND FOR_TEMP.GET_AS_DATE('DEND_PLAN','MASTER','GU12')
AND BR.KOL_VAG<>0
AND A.SOGL_DATE IS NOT NULL
AND B.ISCOR<>2
GROUP BY PLAT_NAME,NAME,STAN_NAME,DATE_R
ORDER BY PLAT_NAME,NAME,STAN_NAME,DATE_R;


