--
-- V_GU12_REP_SVERKA_DATE  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_REP_SVERKA_DATE
(NOM_Z, KOL_A, KOL_BR, RAZN)
AS 
SELECT "NOM_Z","KOL_A","KOL_BR","RAZN" FROM
(
SELECT NOM_Z,SUM(KOL) AS KOL_A,SUM(KOL1) AS KOL_BR,SUM(KOL)-SUM(KOL1) AS RAZN FROM
(
     SELECT A.NOM_Z,BR.KOL_VAG AS KOL,0 AS KOL1 
     FROM GU12_A A,GU12_B B,GU12_BR BR 
     WHERE FROM_DATE BETWEEN FOR_TEMP.GET_AS_DATE('DBEG_SVER','MASTER','GU12') AND FOR_TEMP.GET_AS_DATE('DEND_SVER','MASTER','GU12') 
     AND A.ID=B.ID_A(+)
     AND B.ID=BR.ID_B(+)
UNION ALL
     SELECT A.NOM_Z,0 AS KOL,BR.KOL_VAG AS KOL1 
     FROM GU12_A A,GU12_B B,GU12_BR BR 
     WHERE 
     A.ID=B.ID_A(+)
     AND B.ID=BR.ID_B(+)
     AND BR.DATE_R BETWEEN FOR_TEMP.GET_AS_DATE('DBEG_SVER','MASTER','GU12') AND FOR_TEMP.GET_AS_DATE('DEND_SVER','MASTER','GU12') 
) GROUP BY NOM_Z ORDER BY NOM_Z
) WHERE RAZN <>0;


