--
-- V_GU12_CARD_STAN_CORR_N  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_GU12_CARD_STAN_CORR_N
(STAN_ID, STANNAZN, KOL_CORR_P, KOL_CORR_S, VES_CORR, 
 VES_CORR_P, VES_CORR_S, KOL_PLAN, KOL_PLAN_P, KOL_PLAN_S, 
 VES_PLAN, VES_PLAN_P, VES_PLAN_S, KOL_FAKT, KOL_FAKT_P, 
 KOL_FAKT_S, VES_FAKT, VES_FAKT_P, VES_FAKT_S)
AS 
SELECT
STAN_ID
,MAX(S.STAN_NAME) AS STANNAZN
,SUM(CASE WHEN A.SOBVAG='Ï' THEN A.KOL_CORR ELSE 0 END) AS KOL_CORR_P
,SUM(CASE WHEN A.SOBVAG='Ï' THEN 0 ELSE A.KOL_CORR END) AS KOL_CORR_S
,SUM(A.VES_CORR) AS VES_CORR
,SUM(CASE WHEN A.SOBVAG='Ï' THEN A.VES_CORR ELSE 0 END) AS VES_CORR_P
,SUM(CASE WHEN A.SOBVAG='Ï' THEN 0 ELSE A.VES_CORR END) AS VES_CORR_S
,SUM(A.KOL_PLAN) AS KOL_PLAN
,SUM(CASE WHEN A.SOBVAG='Ï' THEN A.KOL_PLAN ELSE 0 END) AS KOL_PLAN_P
,SUM(CASE WHEN A.SOBVAG='Ï' THEN 0 ELSE A.KOL_PLAN END) AS KOL_PLAN_S
,SUM(A.VES_PLAN) AS VES_PLAN
,SUM(CASE WHEN A.SOBVAG='Ï' THEN A.VES_PLAN ELSE 0 END) AS VES_PLAN_P
,SUM(CASE WHEN A.SOBVAG='Ï' THEN 0 ELSE A.VES_PLAN END) AS VES_PLAN_S
,SUM(A.KOL_FAKT) AS KOL_FAKT
,SUM(CASE WHEN A.SOBVAG='Ï' THEN A.KOL_FAKT ELSE 0 END) AS KOL_FAKT_P
,SUM(CASE WHEN A.SOBVAG='Ï' THEN 0 ELSE A.KOL_FAKT END) AS KOL_FAKT_S
,ROUND(SUM(A.VES_FAKT),0) AS VES_FAKT
,ROUND(SUM(CASE WHEN A.SOBVAG='Ï' THEN A.VES_FAKT ELSE 0 END),0) AS VES_FAKT_P
,ROUND(SUM(CASE WHEN A.SOBVAG='Ï' THEN 0 ELSE A.VES_FAKT END),0) AS VES_FAKT_S
FROM V_GU12_CARD_N A, V_GU12_STAN_NAZN S
WHERE A.STAN_ID=S.ID 
GROUP BY STAN_ID
ORDER BY STANNAZN;


