--
-- V_ISU_DOCS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_ISU_DOCS
(ID, DOC_NUM, DOC_DATE, CONTR_NAME, PACKAGE_ID, 
 FILE_NAME, FILE_POS_NUM, SOURCE_NAME, USER_NAME, UPLOAD_DATE, 
 CONTRACTOR_ID, SOURCE_ID, USER_ID, FILE_ID)
AS 
SELECT 
         ISU_TAX_DOCS.ID,
         ISU_TAX_DOCS.DOC_NUM,
         ISU_TAX_DOCS.DOC_DATE,
         ISU_TAX_CONTR.CONTR_NAME,
         ISU_TAX_DOCS.PACKAGE_ID,
         ISU_TAX_FILES.FILE_NAME,
         ISU_TAX_DOCS.FILE_POS_NUM,
         ISU_TAX_SOURCE.NAME AS SOURCE_NAME,
         ISU_TAX_USER.USER_NAME,
         ISU_TAX_FILES.UPLOAD_DATE,
         ISU_TAX_DOCS.CONTRACTOR_ID,
         ISU_TAX_FILES.SOURCE_ID,
         ISU_TAX_FILES.USER_ID,
         ISU_TAX_DOCS.FILE_ID
          FROM ISU_TAX_DOCS 
                LEFT JOIN ISU_TAX_CONTR ON ISU_TAX_CONTR.ID=ISU_TAX_DOCS.CONTRACTOR_ID 
                LEFT JOIN ISU_TAX_FILES ON ISU_TAX_FILES.ID=ISU_TAX_DOCS.FILE_ID 
                LEFT JOIN ISU_TAX_SOURCE ON ISU_TAX_FILES.SOURCE_ID=ISU_TAX_SOURCE.ID
                LEFT JOIN ISU_TAX_USER ON ISU_TAX_USER.ID=ISU_TAX_FILES.USER_ID;


