--
-- V_KLS_PROD_NOMENKLATOR_GRP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_KLS_PROD_NOMENKLATOR_GRP
(PROD, PARUS_PRN)
AS 
select PROD,MAX(PARUS_PRN) as PARUS_PRN from KLS_PROD_NOMENKLATOR where is_actual=1 GROUP BY PROD;


