--
-- V_KLS_PLANSTRU_SNP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_KLS_PLANSTRU_SNP
(ID, BEGIN_DATE, END_DATE, NAME, LEVEL_POS, 
 INPUT_DATE, KOD_SGR, KOD_SPG, KOD_RZD, KOD_PRZ, 
 KOD_GRP, KOD_PGR, PARENT_ID, NAZN_OTG_ID, VIEW_LEVEL, 
 REGION_ID, ORG_KIND_ID, TIP_REAL_ID, FOR_ID, FOR_NAME, 
 FOR_MOS_ID, SPF_GROUP_ORDER, SPF_GROUP_NAME, SPF_ORDER, SPF_NAME, 
 LUKOIL_ID, IS_TO_HRAN)
AS 
SELECT
  ID,
  BEGIN_DATE,
  END_DATE,
  NAME,
  LEVEL_POS,
  INPUT_DATE,
  KOD_SGR,
  KOD_SPG,
  KOD_RZD,
  KOD_PRZ,
  KOD_GRP,
  KOD_PGR,
  PARENT_ID,
  NAZN_OTG_ID,
  VIEW_LEVEL,
  REGION_ID,
  ORG_KIND_ID,
  TIP_REAL_ID,
  FOR_ID,
  FOR_NAME,
  FOR_MOS_ID,
  SPF_GROUP_ORDER, SPF_GROUP_NAME, SPF_ORDER, SPF_NAME, LUKOIL_ID,IS_TO_HRAN
FROM V_KLS_PLANSTRU
WHERE IS_SNP=1
ORDER BY KOD_SGR, KOD_SPG, KOD_RZD, KOD_PRZ, KOD_GRP, KOD_PGR;


