--
-- V_KVIT_FOR_PARUS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_KVIT_FOR_PARUS
(BASE_NUMB, NPODOG_ID, KOL_DN, CAT_CEN_ID, MODIF, 
 MOD_MODIF, PROD_ID_NPR, PROC_INSURE, USL_SUM, FLG_OPERDATA, 
 VAGOWNER_ID, FLG_VAG_KLIENT, TARIF_MPS, TARIF_OWN, TARIF_GUARD, 
 DATE_OTGR, VES, TARIF1TONN, TARIF, VOZNAGR, 
 ID)
AS 
SELECT
  DP.BASE_NUMB, -- Договор из Паруса
  MONTH.NPODOG_ID, -- Договор из Финансов
  KLS_USL_OPL.KOL_DN, -- Отсрочка по договору
  USL_DOG.CAT_CEN_ID, -- Категория цены из финансов
  PP.MODIF, PP.MOD_MODIF, -- Продукт из Паруса
  KVIT.PROD_ID_NPR, -- Продукт из Финансов
  USL_DOG.PROC_INSURE, -- % страховки
  USL_DOG.USL_SUM, -- вознаграждение
  KVIT.FLG_OPERDATA, -- Признак оперативки
  KVIT.VAGOWNER_ID, -- собственник вагона
  KVIT.FLG_VAG_KLIENT, -- признак вагона клиента
  KVIT.tarif AS TARIF_MPS, -- Тариф за вагоны МПС
  KVIT.TARIF19 AS TARIF_OWN, -- Тариф за собственные вагоны
  KVIT.TARIF_GUARD, -- Плата за охрану
  KVIT.DATE_OTGR, -- Дата отгрузки
  KVIT.VES_BRUTTO AS VES, --Вес в тоннах
  MONTH.TARIF1TONN, -- Тариф за 1 тонну
  ROUND(DECODE(KVIT.FLG_OPERDATA,1,NVL(MONTH.TARIF1TONN,0)*KVIT.VES_BRUTTO,KVIT.TARIF),2)+KVIT.TARIF_GUARD AS Tarif, -- Ж/д тариф
  ROUND(DECODE(KVIT.VAGOWNER_ID,3,USL_DOG.USL_SUM*KVIT.VES_BRUTTO,
           DECODE(KVIT.FLG_VAG_KLIENT,1,USL_DOG.USL_SUM*KVIT.VES_BRUTTO,DECODE(KVIT.TARIF,0,USL_DOG.USL_SUM*KVIT.VES_BRUTTO,KVIT.TARIF19-KVIT.TARIF))),2) AS VOZNAGR, -- Вознаграждение
  KVIT.ID
FROM KVIT,MONTH,USL_DOG,KLS_DOG NPO_DOG,KLS_USL_OPL,
     (SELECT MAX(BASE_NUMB) AS BASE_NUMB, DOG_ID FROM KLS_DOG_PARUS WHERE IS_ACTUAL=1 GROUP BY DOG_ID) DP,
	 (SELECT A.MODIF, A.MOD_MODIF, A.PROD AS PROD_ID_NPR
	   FROM KLS_PROD_NOMENKLATOR A,
	        (SELECT MAX(PARUS_RN) AS PARUS_RN,PROD FROM KLS_PROD_NOMENKLATOR WHERE IS_ACTUAL=1 GROUP BY PROD) B
	  WHERE A.PARUS_RN=B.PARUS_RN
	 ) PP
WHERE KVIT.nom_zd=MONTH.nom_zd
  AND KVIT.DATE_OTGR>TO_DATE('31.12.2002','dd.mm.yyyy')
  AND KVIT.PROD_ID_NPR=PP.PROD_ID_NPR (+)
  AND KVIT.BILL_ID=0
  AND MONTH.NAZN_OTG_ID<>5
  AND MONTH.DATE_PLAN>TO_DATE('31.12.2002','dd.mm.yyyy')
  AND MONTH.DOG_ID=USL_DOG.DOG_ID
  AND MONTH.USL_NUMBER=USL_DOG.USL_NUMBER
  AND MONTH.NPODOG_ID=DP.DOG_ID
  AND MONTH.NPODOG_ID=NPO_DOG.ID
  AND NPO_DOG.USL_OPL_ID=KLS_USL_OPL.ID
  AND KVIT.VES_BRUTTO<>0;


