--
-- V_KVIT_FOR_PARUS_2  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_KVIT_FOR_PARUS_2
(NOMEN_CODE, MODIF_CODE, PROD_ID_NPR, DATE_KVIT, NUM_KVIT, 
 VES)
AS 
SELECT /*+ RULE */
  PP.MODIF as NOMEN_CODE, -- Продукт из Паруса
  PP.MOD_MODIF as MODIF_CODE, -- Продукт из Паруса
  KVIT.PROD_ID_NPR,
  KVIT.DATE_KVIT, -- Дата отгрузки
  KVIT.NUM_KVIT,
  KVIT.VES_BRUTTO*1000 as VES
FROM KVIT,MONTH,
	 (SELECT A.MODIF, A.MOD_MODIF, A.PROD AS PROD_ID_NPR
	   FROM KLS_PROD_NOMENKLATOR A,
	        (SELECT MAX(PARUS_RN) AS PARUS_RN,PROD FROM KLS_PROD_NOMENKLATOR WHERE IS_ACTUAL=1 GROUP BY PROD) B
	  WHERE A.PARUS_RN=B.PARUS_RN
	 ) PP
WHERE KVIT.nom_zd=MONTH.nom_zd
  AND KVIT.PROD_ID_NPR=PP.PROD_ID_NPR (+)
  AND KVIT.DATE_KVIT>=TO_DATE('01.01.2004','dd.mm.yyyy')
  AND KVIT.VES_BRUTTO>40;


