--
-- V_LIST_DOVER_IN_NARIAD  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_LIST_DOVER_IN_NARIAD
(ID, DATE_DOVER, DATE_END, NUM_DOVER, FIO_DOVER, 
 DOLJ_DOVER, PREDPR_ID, SHORT_NAME, PREDPR_NAME)
AS 
SELECT DISTINCT KLS_DOVER.ID, KLS_DOVER.DATE_DOVER, KLS_DOVER.DATE_END,  
KLS_DOVER.NUM_DOVER, KLS_DOVER.FIO_DOVER, KLS_DOVER.DOLJ_DOVER, KLS_DOVER.PREDPR_ID, KLS_PREDPR.SHORT_NAME, KLS_PREDPR.PREDPR_NAME FROM KLS_NARIAD,KLS_PREDPR,KLS_DOVER     
WHERE KLS_DOVER.PREDPR_ID = KLS_PREDPR.ID AND    
      KLS_NARIAD.DOVER_ID = KLS_DOVER.ID    
ORDER BY KLS_DOVER.ID DESC;


