--
-- V_LIST_PLATEL  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_LIST_PLATEL
(ID, SHORT_NAME, PREDPR_NAME)
AS 
SELECT DISTINCT KLS_PREDPR.ID, KLS_PREDPR.SHORT_NAME, KLS_PREDPR.PREDPR_NAME 
FROM KLS_PREDPR,KLS_DOG  
WHERE (KLS_PREDPR.ID = KLS_DOG.PREDPR_ID AND KLS_DOG.DOG_YEAR>1999)  
ORDER BY KLS_PREDPR.SHORT_NAME;


