--
-- V_LIST_PLATEL_IN_DOVER  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_LIST_PLATEL_IN_DOVER
(ID, SHORT_NAME)
AS 
SELECT DISTINCT KLS_PREDPR.ID, KLS_PREDPR.SHORT_NAME FROM KLS_PREDPR,KLS_DOVER  
WHERE KLS_PREDPR.ID = KLS_DOVER.PREDPR_ID  
ORDER BY KLS_PREDPR.SHORT_NAME;


