--
-- V_LOAD_GU12_A  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_LOAD_GU12_A
(NOM_Z, FROM_DATE, TO_DATE, SOGL_DATE, REG_DATE, 
 DOGOVOR, STANOTPR_ID, GROTP_ID, EXPED_ID, GR_GRUZ_ID, 
 VIDSOOB_ID, PODACH_ID, SOGL, PLATTAR_ID, PROD_ID, 
 PRIZNOTPR_ID, VLADPUT_ID, RODVAG_ID, FOX_KOD, ISCOR)
AS 
SELECT
  A.NOM_Z,
  A.BDATE as FROM_DATE,
  A.EDATE as TO_DATE,
  A.SDATE as SOGL_DATE,
  A.ZDATE as REG_DATE,
  A.DOGOVOR,
  STAN_OTP.ID as STANOTPR_ID,
  GROTP.GROTP_ID as GROTP_ID,
  EXPED.ID as EXPED_ID,
  TO_NUMBER(GRUZ) as GR_GRUZ_ID,
  TO_NUMBER(VID_SOOB) as VIDSOOB_ID,
  TO_NUMBER(PODACHA) as PODACH_ID,
  DECODE(A.SDATE,NULL,0,1) as SOGL,
  PLATTAR.PLATTAR_ID,
  TO_NUMBER(PROD) as PROD_ID,
  KLS_GD_OTPR.ID as priznotpr_id,
  TO_NUMBER(vlad_put) as VLADPUT_ID,
  TO_NUMBER(rod_vag) as RODVAG_ID,
  RELA as FOX_KOD,
  MAX(A.ISCOR) as ISCOR
FROM LOAD_BUFFER.GU12A_B A, KLS_STAN STAN_OTP, V_GU12_OTPRAV GROTP,
     V_GU12_EXPED exped, V_GU12_PLATTAR plattar,
	 KLS_GD_OTPR
WHERE A.STANOTPR=STAN_OTP.STAN_KOD(+)
  AND A.GROTPR=GROTP.GROTP_OKPO(+)
  AND A.EXPED=EXPED.FOX_KOD (+)
  AND A.GRPLAT=plattar.DOGOVOR (+)
  AND A.prizn_otpr=KLS_GD_OTPR.TAG (+)
GROUP BY
  A.NOM_Z,
  A.BDATE,
  A.EDATE,
  A.SDATE,
  A.ZDATE,
  A.DOGOVOR,
  STAN_OTP.ID,
  GROTP.GROTP_ID,
  EXPED.ID,
  TO_NUMBER(GRUZ),
  TO_NUMBER(VID_SOOB),
  TO_NUMBER(PODACHA),
  DECODE(A.SDATE,NULL,0,1),
  PLATTAR.PLATTAR_ID,
  TO_NUMBER(PROD),
  KLS_GD_OTPR.ID,
  TO_NUMBER(vlad_put),
  TO_NUMBER(rod_vag),
  RELA;


