--
-- V_LOAD_GU12_B  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_LOAD_GU12_B
(PDATE, SOBSTVAG_ID, STAN_ID, STAN_POG, STAN_PER_ID, 
 PREDPR, GRUZPOL_ID, KOL_VAG, VES, VIDOTPR_ID, 
 MRK, PLAT_ID, FOX_KOD, FOX_KOD_A, ISCOR, 
 DATE_LETTER, NOM_LETTER, PRINVAG_ID)
AS 
SELECT
  A.PDATE,
  TO_NUMBER(sobst_vag) as SOBSTVAG_ID,
  STAN.ID as STAN_ID,
  A.STAN_POG,
  STAN_PER.ID as STAN_PER_ID,
  A.predpr,
  gruz_pol.ID as gruzpol_id,
  kol_vag,
  ves,
  KLS_GD_VID_OTPR.ID as vidotpr_id,
  mrk,
  TO_NUMBER(prplat) as PLAT_ID,
  TIME_AP as FOX_KOD,
  RELA as FOX_KOD_A,
  ISCOR,
  DATE_LET as DATE_LETTER,
  NOM_LET as NOM_LETTER,
  KLS_GD_PRINVAG.ID as PRINVAG_ID
FROM LOAD_BUFFER.GU12A_B A, KLS_STAN STAN, KLS_STAN STAN_PER,
    (select KOD,MAX(ID_PREDPR) AS ID_PREDPR FROM load_buffer.PREDPR_GU12 GROUP BY KOD) b,
     V_GU12_GRUZ_POL gruz_pol,KLS_GD_VID_OTPR, KLS_GD_PRINVAG
WHERE A.STAN=STAN.STAN_KOD(+)
  AND A.STAN_POG=STAN_PER.STAN_KOD(+)
  AND A.predpr=B.KOD(+)
  and b.ID_PREDPR=gruz_pol.ID(+)
  AND A.vid_otpr=KLS_GD_VID_OTPR.TAG(+)
  AND A.PRIN_VAG=KLS_GD_PRINVAG.ABBR(+);


