--
-- V_LUKREP_KVIT  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_LUKREP_KVIT
(BILL_ID, PROD_ID_NPR, VAGOWN_TYP_ID, TARIF_MPS, TARIF_KVIT, 
 CNT, ID, SVED_NUM, NUM_KVIT, NUM_DOVER, 
 NUM_CIST, VES, NUM_AKT)
AS 
SELECT /*+ INDEX(KLS_VAGOWNER VAGOWNER_PK)*/ a.BILL_ID,a.PROD_ID_NPR,MIN(KLS_VAGOWNER.VAGOWN_TYP_ID) as VAGOWN_TYP_ID,
          SUM(a.TARIF_ALT) as TARIF_MPS, SUM(a.TARIF) as TARIF_KVIT,COUNT(*) AS CNT,MAX(a.ID) AS ID,
          MAX(a.SVED_NUM) AS SVED_NUM, MAX(a.NUM_KVIT) AS NUM_KVIT, MAX(a.NUM_DOVER) AS NUM_DOVER,
		  MAX(a.NUM_CIST) AS NUM_CIST,SUM(a.VES_BRUTTO) AS VES,MAX(a.NUM_AKT) AS NUM_AKT
     FROM (
	   SELECT /*+ ALL_ROWS INDEX(KVIT KVIT_DATE_KVIT_BILLS_I) */ * FROM KVIT
  	    WHERE DATE_KVIT>=TO_DATE('01.01.2004','dd.mm.yyyy')
       UNION ALL
       SELECT /*+ ALL_ROWS INDEX(DOP_KVIT DOP_KVIT_DATE_KVIT_BILLS_I) */ * FROM DOP_KVIT
  	    WHERE DATE_KVIT>=TO_DATE('01.01.2004','dd.mm.yyyy')
	 ) a ,KLS_VAGOWNER
	WHERE a.VAGOWNER_ID=KLS_VAGOWNER.ID(+)
	GROUP BY a.BILL_ID,a.PROD_ID_NPR;


