--
-- V_LUKREP_GRPOL  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_LUKREP_GRPOL
(SCHETF, DATA_VYP_SF, GRPOL, GRPOL_ADDR)
AS 
SELECT SCHETF,DATA_VYP_SF,GRPOL,GRPOL_ADDR 
FROM SVETA.SF_SFAK_PROD 
WHERE DATA_VYP_SF>=TO_DATE('01.01.2004','DD.MM.YYYY')
ORDER BY SCHETF;


