--
-- V_LUKREP_SF  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_LUKREP_SF
(NUM_5_DAY, IS_KORR, IS_AGENT, IS_SILOV, SOBSTV, 
 PLAT_ID, PLAT_INN, PLAT_NAME, PLAT_ADDR, DOG_ID, 
 DOG_NUMBER, DOG_DATE, DATE_KVIT, DATE_MOS, DATE_CHN_SOB, 
 NOM_DOK, NOM_SF, ORIG_NOM_SF, OLD_NOM_SF, NPO_SF, 
 DATE_VYP_SF, GR_NPR_ID, GR_NPR_NAME, PROD_ID_NPR, PROD_NAME, 
 PROD_EDIZ, KVIT_ID, VES, VES_KVIT, CNT_KVIT, 
 SVED_NUM, NUM_KVIT, NUM_CIST, STANOTP_ID, STAN_NAME, 
 HRAN_ID, HRAN_NAME, POLUCH_ID, POLUCH_NAME, POLUCH_ADDR, 
 IS_SF, CENA_BN, CENA, SUMMA_PROD_BN, SUMMA_PROD_NDS, 
 SUMMA_PROD, SUMMA_AGEN, SUMMA_AGEN_NDS, SUMMA_TARIF, SUMMA_TARIF_NDS, 
 SUMMA_STRAH, SUMMA_DOK, SUMMA_DOK_NDS, PRICE_PROTOKOL, KOL_DN, 
 NUM_STRAH)
AS 
SELECT "NUM_5_DAY","IS_KORR","IS_AGENT","IS_SILOV","SOBSTV","PLAT_ID","PLAT_INN","PLAT_NAME","PLAT_ADDR","DOG_ID","DOG_NUMBER","DOG_DATE","DATE_KVIT",
"DATE_MOS","DATE_CHN_SOB","NOM_DOK","NOM_SF","ORIG_NOM_SF", "OLD_NOM_SF","NPO_SF","DATE_VYP_SF","GR_NPR_ID",
"GR_NPR_NAME","PROD_ID_NPR","PROD_NAME","PROD_EDIZ","KVIT_ID","VES","VES_KVIT","CNT_KVIT","SVED_NUM","NUM_KVIT",
"NUM_CIST","STANOTP_ID","STAN_NAME","HRAN_ID","HRAN_NAME","POLUCH_ID","POLUCH_NAME","POLUCH_ADDR","IS_SF",
"CENA_BN","CENA","SUMMA_PROD_BN","SUMMA_PROD_NDS","SUMMA_PROD","SUMMA_AGEN","SUMMA_AGEN_NDS",
"SUMMA_TARIF",
"SUMMA_TARIF_NDS","SUMMA_STRAH","SUMMA_DOK","SUMMA_DOK_NDS","PRICE_PROTOKOL","KOL_DN","NUM_STRAH" FROM V_LUKREP_SF_NEW;


