--
-- V_LUKREP_SF_AKCIZ  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_LUKREP_SF_AKCIZ
(NUM_5_DAY, IS_KORR, IS_AGENT, SOBSTV, PLAT_ID, 
 PLAT_INN, PLAT_NAME, PLAT_ADDR, DOG_ID, DOG_NUMBER, 
 DOG_DATE, NOM_DOK, NOM_SF, ORIG_NOM_SF, OLD_NOM_SF, 
 NPO_SF, NOM_SCH, DATE_VYP_SF, NOM_AKT, DATE_AKT, 
 PROD_ID_NPR, PROD_NAME, VES, PROD_EDIZ, NUM_KVIT, 
 NUM_DOVER, NUM_KVIT_STR, DATE_KVIT, DATE_MOS, NUM_PASP, 
 NUM_STRAH, CENA_BN, CENA, SUMMA_PROD_BN, SUMMA_PROD_NDS, 
 SUMMA_PROD, SUMMA_AGEN, SUMMA_AGEN_NDS, SUMMA_TARIF, SUMMA_TARIF_NDS, 
 SUMMA_STRAH, SUMMA_DOK, SUMMA_DOK_NDS, PRICE_PROTOKOL, HRAN_ID, 
 HRAN_NAME, KOL_DN, RAST, LUK_PLAT_ID, LUK_PLAT_NAME, 
 LUK_DOG_ID, LUK_DOG_NUMBER, LUK_DOG_DATE, TYPE_DOCUMENT, PROD_GROUP_ORDER, 
 EX_SVID, EX_SVID_PREF, EX_SVID_NUMB, VIR_EXIST, VIR_DATE, 
 VIR_PERIOD, VIR_SUM_PROD_BN, VIR_VES)
AS 
SELECT
  A.NUM_5_DAY,
  A.IS_KORR,
  A.IS_AGENT,
  A.SOBSTV,
  A.PLAT_ID,
  A.PLAT_INN,
  A.PLAT_NAME,
  A.PLAT_ADDR,
  A.DOG_ID,
  A.DOG_NUMBER,
  A.DOG_DATE,
  A.NOM_DOK,
  A.NOM_SF,
  A.ORIG_NOM_SF,
  A.OLD_NOM_SF,
  A.NPO_SF,
  A.NOM_SCH,
  A.DATE_VYP_SF,
  A.NOM_AKT,
  A.DATE_AKT,
  A.PROD_ID_NPR,
  A.PROD_NAME,
  A.VES,
  A.PROD_EDIZ,
  A.NUM_KVIT,
  A.NUM_DOVER,
  A.NUM_KVIT_STR,
  A.DATE_KVIT,
  A.DATE_MOS,
  A.NUM_PASP,
  A.NUM_STRAH,
  A.CENA_BN,
  A.CENA,
  A.SUMMA_PROD_BN,
  A.SUMMA_PROD_NDS,
  A.SUMMA_PROD,
  A.SUMMA_AGEN,
  A.SUMMA_AGEN_NDS,
  A.SUMMA_TARIF,
  A.SUMMA_TARIF_NDS,
  A.SUMMA_STRAH,
  A.SUMMA_DOK,
  A.SUMMA_DOK_NDS,
  A.PRICE_PROTOKOL,
  A.HRAN_ID,
  A.HRAN_NAME,
  A.KOL_DN,
  A.RAST,
  A.LUK_PLAT_ID,
  A.LUK_PLAT_NAME,
  A.LUK_DOG_ID,
  A.LUK_DOG_NUMBER,
  A.LUK_DOG_DATE,
  A.TYPE_DOCUMENT,
  prod_akciz.GROUP_ORDER AS PROD_GROUP_ORDER,
  NVL(svid_akciz.EX_SVID,0) AS EX_SVID,
  NVL(svid_akciz.EX_SVID_PREF,'') AS EX_SVID_PREF,
  NVL(svid_akciz.EX_SVID_NUMB,'') AS EX_SVID_NUMB,
  DECODE(bills_vir.DATE_VIR,NULL,0,1) AS VIR_EXIST,
  DECODE(bills_vir.DATE_VIR,NULL,A.DATE_KVIT,bills_vir.DATE_VIR)AS VIR_DATE,
  RusMonth(DECODE(bills_vir.DATE_VIR,NULL,A.DATE_KVIT,bills_vir.DATE_VIR)) AS VIR_PERIOD,
  DECODE(bills_vir.DATE_VIR,NULL,A.SUMMA_PROD_BN,bills_vir.SUM_PROD) AS VIR_SUM_PROD_BN,
  NVL(bills_vir.VES,0) AS VIR_VES
FROM V_LUKREP_SF_REES_NEW A,
(
SELECT A.PROD_ID_NPR,B.GROUP_ORDER
  FROM KLS_PROD_GROUPS_DESC A, KLS_PROD_GROUPS B
 WHERE A.PROD_GROUPS_ID=B.ID
   AND B.PROD_TYPE_GRP_ID=6
) prod_akciz, -- Подакцизные продукты
(
SELECT PLAT_ID,EX_SVID,EX_SVID_PREF,EX_SVID_NUMB
  FROM KLS_PREDPR_AKCIZ
 WHERE EX_SVID=1
) svid_akciz, -- Акцизные свидетельства
(
SELECT
  KVIT.BILL_ID,
  A.DATE_VIR,
  SUM(A.VES) AS VES,
  SUM(A.SUM_PROD) AS SUM_PROD
  FROM KVIT_DATE_VIR A,KVIT
 WHERE A.KVIT_ID=KVIT.ID
   AND KVIT.DATE_KVIT >= TO_DATE('01.01.2003','dd.mm.yyyy')
GROUP BY KVIT.BILL_ID,A.DATE_VIR
) bills_vir -- Деление СФ по дате выработки
WHERE A.DATE_VYP_SF >= TO_DATE('01.01.2003','dd.mm.yyyy')
  AND A.PROD_ID_NPR = prod_akciz.PROD_ID_NPR
  AND A.PLAT_ID=svid_akciz.PLAT_ID(+)
  AND A.NOM_DOK=bills_vir.BILL_ID(+)
  AND A.IS_AGENT=1;


