--
-- V_LUKREP_KVIT_REES  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_LUKREP_KVIT_REES
(IS_AGENT, SOBSTV, PLAT_ID, PLAT_INN, PLAT_NAME, 
 PLAT_ADDR, DOG_ID, DOG_NUMBER, DOG_DATE, NOM_DOK, 
 NOM_SF, ORIG_NOM_SF, NPO_SF, DATE_VYP_SF, PROD_ID_NPR, 
 PROD_NAME, VES, PROD_EDIZ, NUM_KVIT, DATE_KVIT, 
 DATE_MOS, SUMMA_TARIF, SUMMA_TARIF_NDS)
AS 
SELECT
  v_bills.IS_AGENT,
  DECODE(KLS_DOG.DOG_NUMBER,'01Ì1254',2,1) AS SOBSTV,
  DECODE(KLS_DOG.DOG_NUMBER,'0210218',SNP_DOG.PREDPR_ID,KLS_DOG.PREDPR_ID) AS PLAT_ID,
  DECODE(KLS_DOG.DOG_NUMBER,'0210218',SNP_PLAT.INN,PLAT.INN) AS PLAT_INN,
  DECODE(KLS_DOG.DOG_NUMBER,'0210218',SNP_PLAT.PREDPR_NAME,PLAT.PREDPR_NAME) AS PLAT_NAME,
  DECODE(KLS_DOG.DOG_NUMBER,'0210218',SNP_PLAT.CITY_J || ',' || SNP_PLAT.ADDRESS_J,PLAT.CITY_J || ',' || PLAT.ADDRESS_J) AS PLAT_ADDR,
  DECODE(KLS_DOG.DOG_NUMBER,'0210218',v_bills.SNP_DOG_ID,v_bills.DOG_ID),
  DECODE(KLS_DOG.DOG_NUMBER,'0210218',SNP_DOG.DOG_NUMBER,KLS_DOG.DOG_NUMBER),
  DECODE(KLS_DOG.DOG_NUMBER,'0210218',SNP_DOG.DOG_DATE,KLS_DOG.DOG_DATE),
  v_bills.NOM_DOK,
  v_bills.NOM_SF,
  v_bills.ORIG_NOM_SF,
  v_bills.NPO_SF,
  v_bills.DATE_VYP_SF AS DATE_VYP_SF,
  v_bills.PROD_ID_NPR,
  KLS_PROD.NAME_NPR AS PROD_NAME,
  KV.VES,
  KLS_PROD.ED_IZ AS PROD_EDIZ,
  KV.NUM_KVIT,
  v_bills.DATE_KVIT,
  v_bills.DATE_MOS,
  KV.TARIF+ROUND(KV.TARIF * FOR_BILLS.GetNDSValue(v_bills.DATE_KVIT)/100,2),
  ROUND(KV.TARIF * FOR_BILLS.GetNDSValue(v_bills.DATE_KVIT)/100,2)
FROM v_bills, KLS_PREDPR PLAT, KLS_DOG, KLS_PROD, KLS_DOG SNP_DOG, KLS_PREDPR SNP_PLAT,
  (SELECT KVIT.BILL_ID,
          KVIT.NUM_KVIT,
		  KVIT.DATE_KVIT,
          SUM(KVIT.VES_BRUTTO) AS VES,
		  SUM(KVIT.TARIF+KVIT.TARIF_GUARD) AS TARIF
 	 FROM KVIT
	WHERE KVIT.DATE_KVIT>=TO_DATE('01.04.2002','dd.mm.yyyy')
	GROUP BY KVIT.BILL_ID,KVIT.NUM_KVIT,KVIT.DATE_KVIT) KV
WHERE v_bills.NOM_DOK = KV.BILL_ID
  AND v_bills.DOG_ID = KLS_DOG.ID
  AND KLS_DOG.PREDPR_ID = PLAT.ID
  AND v_bills.SNP_DOG_ID = SNP_DOG.ID
  AND SNP_DOG.PREDPR_ID = SNP_PLAT.ID
  AND v_bills.PROD_ID_NPR = KLS_PROD.ID_NPR
  AND v_bills.DATE_KVIT>=TO_DATE('01.04.2002','dd.mm.yyyy');


