--
-- V_MONTH_GD  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_MONTH_GD
(NOM_ZD, STANOTP_ID, GDOROTP_ID, STANOTP_NAME, NPR_SOBSTV_ID, 
 NPR_SOBSTV_NAME, STAN_ID, GDOR_ID, STAN_NAME, VETKA_ID, 
 VETKA_NAME, POLUCH_ID, POLUCH_NAME, POLUCH_ADDR, TEX_PD_ID, 
 NAZN_OTG_ID, IS_EXPORT, LOAD_ABBR, LOAD_NAME, DOG_ID, 
 USL_NUMBER, GOSPROG_ID, GROUP_NPR, ID_NPR, ABBR_NPR, 
 NAME_NPR, GDKOD_NPR, GDNAME_NPR, TONN_DECLARED, TONN_LOADED, 
 CIST_DECLARED, CIST_LOADED, FLG_ALLOW_8_AXES, FLG_UPPER_SLIV, FLG_DOP_CIST, 
 FLG_FORMA_2, FLG_OBOGR, DATE_PLAN, PRIM, GR4, 
 K_TAR, INPUT_DATE, UPDATE_DATE, TARIF1TONN, POTREB_ID, 
 POTREB_NAME, POTREB_ADDR, PLANSTRU_ID, NPODOG_ID, GROTP_ID, 
 GROTP_NAME)
AS 
SELECT
  MONTH.NOM_ZD,
  MONTH.STANOTP_ID,
  STANOTP.GDOR_ID AS GDOROTP_ID,
  DECODE(MONTH.STANOTP_ID,1,' ',RTrim(STANOTP.STAN_NAME) || ' ' || DECODE(STANOTP.GDOR_ID,0,' ','('||RTrim(gdorotp.SHORT_NAME)||' ∆/ƒ) ') || ' ' || RTrim(STANOTP.STAN_KOD)) AS STANOTP_NAME,
  MONTH.NPR_SOBSTV_ID,
  DECODE(MONTH.NPR_SOBSTV_ID,0,' ',SOBSTV.SHORT_NAME) AS NPR_SOBSTV_NAME,
  MONTH.STAN_ID,
  STAN.GDOR_ID,
  DECODE(MONTH.STAN_ID,1,' ',RTrim(STAN.STAN_NAME) || ' ' || DECODE(STAN.GDOR_ID,0,' ','('||RTrim(gdor.SHORT_NAME)||' ∆/ƒ) ') || ' ' || RTrim(STAN.STAN_KOD)) AS STAN_NAME,
  MONTH.VETKA_ID,
  KLS_VETKA.VETKA_NAME,
  MONTH.POLUCH_ID,
  RTrim(POLUCH.PREDPR_NAME) || DECODE(poluch.GD_KOD,NULL,' ','  Ó‰:' || RTrim(poluch.GD_KOD)) || DECODE(poluch.OKPO,NULL,' ',' Œ œŒ:' || RTrim(poluch.OKPO)) AS POLUCH_NAME,
  Get_ADDR('',POLUCH.POSTINDEX_P,poluch.CITY_P,poluch.ADDRESS_P) AS POLUCH_ADDR,
  MONTH.TEX_PD_ID,
  MONTH.NAZN_OTG_ID,
  DECODE(MONTH.NAZN_OTG_ID,5,'› —œŒ–“',6,'› —œŒ–“','œŒ –Œ——»»') AS IS_EXPORT,
  MONTH.LOAD_ABBR,
  KLS_VID_OTGR.LOAD_NAME,
  MONTH.DOG_ID,
  MONTH.USL_NUMBER,
  MONTH.GOSPROG_ID,
  KLS_PROD.ID_GROUP_NPR,
  MONTH.PROD_ID_NPR,
  kls_prod.ABBR_NPR,
  KLS_PROD.NAME_NPR,
  KLS_PROD.GD_KOD_NPR,
  KLS_PROD.GD_NAME_NPR,
  MONTH.TONN_DECLARED,
  MONTH.TONN_LOADED,
  MONTH.CIST_DECLARED,
  MONTH.CIST_LOADED,
  MONTH.FLG_ALLOW_8_AXES,
  MONTH.FLG_UPPER_SLIV,
  MONTH.FLG_DOP_CIST,
  MONTH.FLG_FORMA_2,
  MONTH.FLG_OBOGR,
  MONTH.DATE_PLAN,
  MONTH.PRIM,
  MONTH.GR4,
  MONTH.K_TAR,
  MONTH.INPUT_DATE,
  MONTH.UPDATE_DATE,
  MONTH.TARIF1TONN,
  MONTH.POTREB_ID,
  RTrim(POTREB.PREDPR_NAME) || DECODE(potreb.GD_KOD,NULL,' ','  Ó‰:' || RTrim(potreb.GD_KOD)) || DECODE(potreb.OKPO,NULL,' ',' Œ œŒ:' || RTrim(potreb.OKPO)) AS POTREB_NAME,
  Get_ADDR('',POTREB.POSTINDEX_P,potreb.CITY_P,potreb.ADDRESS_P) AS POTREB_ADDR,
  MONTH.PLANSTRU_ID,
  MONTH.NPODOG_ID,
  MONTH.GROTP_ID,
  RTrim(DECODE(KLS_TEX_PD.TEX_PD_NAME,NULL,DECODE(GROTP.PREDPR_NAME,'Õ/ƒ',' ',GROTP.PREDPR_NAME),RTrim(KLS_TEX_PD.TEX_PD_NAME) || '  Ó‰:' || TO_CHAR(KLS_TEX_PD.ID))) || DECODE(grotp.GD_KOD,NULL,' ','/' || RTrim(grotp.GD_KOD)) || DECODE(grotp.OKPO,NULL,' ',' Œ œŒ:' || RTrim(grotp.OKPO)) AS GROTP_NAME
FROM
  MONTH,KLS_PROD,KLS_PREDPR sobstv,KLS_TEX_PD,KLS_PREDPR grotp, KLS_STAN STANOTP, KLS_STAN STAN,
  KLS_GDOR GDOROTP, KLS_GDOR GDOR, KLS_PREDPR POLUCH, KLS_VID_OTGR, KLS_PREDPR potreb, KLS_VETKA
WHERE
  MONTH.PROD_ID_NPR=KLS_PROD.ID_NPR AND
  MONTH.NPR_SOBSTV_ID=sobstv.id AND
  MONTH.TEX_PD_ID=KLS_TEX_PD.id(+) AND MONTH.GROTP_ID=KLS_TEX_PD.GROTP_ID(+) AND
  MONTH.GROTP_ID=grotp.ID(+) AND
  MONTH.STANOTP_ID=STANOTP.ID AND
  MONTH.STAN_ID=STAN.ID AND
  STANOTP.GDOR_ID=GDOROTP.ID(+) AND
  STAN.GDOR_ID=GDOR.ID(+) AND
  MONTH.POLUCH_ID=poluch.ID(+) AND
  MONTH.POTREB_ID=potreb.ID(+) AND
  MONTH.VETKA_ID=KLS_VETKA.ID(+) AND
  MONTH.LOAD_ABBR=KLS_VID_OTGR.LOAD_ABBR(+);


