--
-- V_MONTH_REE  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_MONTH_REE
(DATE_REE, DOP_REE, NOM_ZD, PRICHIN)
AS 
SELECT
  MONTH_REE.DATE_REE,
  MONTH_REE.DOP_REE,
  MONTH_REE.NOM_ZD,
  NVL(MONTH_VISIR.PRICHIN,' ')
FROM MONTH_REE,MONTH_VISIR
WHERE MONTH_REE.DATE_REE=MONTH_VISIR.DATE_REE(+)
  AND MONTH_REE.DOP_REE=MONTH_VISIR.DOP_REE(+)
  AND MONTH_REE.NOM_ZD=MONTH_VISIR.NOM_ZD(+);


