--
-- V_MONTH_SNP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_MONTH_SNP
(NOM_ZD, STANOTP_ID, NPR_SOBSTV_ID, STAN_ID, VETKA_ID, 
 POLUCH_ID, TEX_PD_ID, NAZN_OTG_ID, LOAD_ABBR, DOG_ID, 
 USL_NUMBER, GOSPROG_ID, PROD_ID_NPR, TONN_DECLARED, TONN_LOADED, 
 CIST_DECLARED, CIST_LOADED, FLG_ALLOW_8_AXES, FLG_UPPER_SLIV, FLG_DOP_CIST, 
 FLG_FORMA_2, FLG_OBOGR, DATE_PLAN, PRIM, CENA, 
 CENA_OTP, SUM_ZD, GR4, K_TAR, INPUT_DATE, 
 UPDATE_DATE, TARIF1TONN, POTREB_ID, PLANSTRU_ID, NPODOG_ID, 
 GROTP_ID)
AS 
SELECT 
  "NOM_ZD",
  "STANOTP_ID",
  "NPR_SOBSTV_ID",
  "STAN_ID",
  "VETKA_ID",
  "POLUCH_ID",
  "TEX_PD_ID",
  "NAZN_OTG_ID",
  "LOAD_ABBR",
  DECODE(NVL("DOG_ID",0),0,"DOG_ID","NPODOG_ID"),
  DECODE(NVL("DOG_ID",0),0,"USL_NUMBER",1),
  "GOSPROG_ID",
  "PROD_ID_NPR",
  "TONN_DECLARED",
  "TONN_LOADED",
  "CIST_DECLARED",
  "CIST_LOADED",
  "FLG_ALLOW_8_AXES",
  "FLG_UPPER_SLIV",
  "FLG_DOP_CIST",
  "FLG_FORMA_2",
  "FLG_OBOGR",
  "DATE_PLAN",
  "PRIM",
  "CENA",
  "CENA_OTP",
  "SUM_ZD",
  "GR4",
  "K_TAR",
  "INPUT_DATE",
  "UPDATE_DATE",
  "TARIF1TONN",
  "POTREB_ID",
  "PLANSTRU_ID",
  "NPODOG_ID",
  "GROTP_ID" 
  FROM month;


