--
-- V_NARIAD_READY  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_NARIAD_READY
(KOD_PLAT, NAME_PLAT, KOD_PROD, NAME_PROD, NOM_ZD, 
 NARIAD, DOVEREN, MM, YY, DATE_END, 
 VES)
AS 
SELECT KLS_DOVER.PREDPR_ID AS KOD_PLAT,
       KLS_PREDPR.SHORT_NAME AS NAME_PLAT,    
       KLS_PROD.ID_KIND_NPR AS KOD_PROD,   
       KINDPROD.NAME_NPR AS NAME_PROD,   
	   KLS_NAR_LINE.NOM_ZD,   
	   TRIM_NUMNAR(KLS_NARIAD.NUM_NAR) AS NARIAD,   
	   TRIM_NUMNAR(KLS_DOVER.NUM_DOVER) AS DOVEREN,   
	   TO_CHAR(KLS_NARIAD.DATE_NAR,'MM') AS MM,   
	   TO_CHAR(KLS_NARIAD.DATE_NAR,'YYYY') AS YY,   
	   KLS_NARIAD.DATE_END,  
	   KLS_NAR_LINE.VES  
FROM KLS_NAR_LINE, KLS_NARIAD, KLS_DOVER, MONTH, KLS_PROD, KLS_PROD KINDPROD, KLS_PREDPR 
WHERE KLS_NAR_LINE.NARIAD_ID = KLS_NARIAD.ID   
  AND KLS_NARIAD.DOVER_ID = KLS_DOVER.ID  
  AND KLS_NAR_LINE.NOM_ZD = MONTH.NOM_ZD  
  AND MONTH.PROD_ID_NPR = KLS_PROD.ID_NPR
  AND KINDPROD.ID_NPR = KLS_PROD.ID_KIND_NPR
  AND KLS_DOVER.PREDPR_ID = KLS_PREDPR.ID;


