--
-- V_NARIAD_KTU  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_NARIAD_KTU
(YY, MM, KOD_PLAT, NAME_PLAT, KOD_PROD, 
 NAME_PROD, NOM_ZD, NARIAD, DOVEREN, DATE_END, 
 VES)
AS 
SELECT YY,
       MM, 
       KOD_PLAT,
	   NAME_PLAT,   
       KOD_PROD,   
       NAME_PROD,   
	   NOM_ZD,   
	   NARIAD,   
	   DOVEREN,   
	   DATE_END,
	   SUM(VES) AS VES
FROM V_NARIAD_READY  
GROUP BY YY,MM,NAME_PLAT, KOD_PLAT, NAME_PROD, KOD_PROD, NOM_ZD, NARIAD, DOVEREN, DATE_END;


