--
-- V_NARIAD_REESTR  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_NARIAD_REESTR
(KOD_PLAT, PROD_ID_NPR, NOM_ZD, NARIAD_ID, NARIAD, 
 DOVEREN, MM, YY, DATE_OTGR, VES)
AS 
SELECT
	   KLS_DOG.PREDPR_ID AS KOD_PLAT,  
       KVIT.PROD_ID_NPR, 
       KVIT.NOM_ZD,
	   SVED.NARIAD_ID, 
	   TRIM_NUMNAR(KLS_NARIAD.NUM_NAR) AS NARIAD, 
	   TRIM_NUMNAR(KLS_DOVER.NUM_DOVER) AS DOVEREN,
	   TO_CHAR(KVIT.DATE_KVIT,'MM') AS MM,   
	   TO_CHAR(KVIT.DATE_KVIT,'YYYY') AS YY,   
	   KVIT.DATE_OTGR, 
   	   KVIT.VES 
FROM KVIT, SVED, MONTH, KLS_DOG, KLS_NARIAD, KLS_DOVER 
WHERE KVIT.SVED_ID = SVED.ID 
  AND KVIT.NOM_ZD = MONTH.NOM_ZD
  AND MONTH.DOG_ID = KLS_DOG.ID 
  AND SVED.NARIAD_ID = KLS_NARIAD.ID (+)
  AND KLS_NARIAD.DOVER_ID = KLS_DOVER.ID (+) 
  AND (MONTH.LOAD_ABBR='—¿Ã' OR MONTH.LOAD_ABBR=' Õ“');


