--
-- V_NARIAD_PRINT  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_NARIAD_PRINT
(ID, NUM_NAR, DATE_NAR, DATE_BEG, DATE_END, 
 NOM_ZD, KOL, VES, STAN_NAME, PROD_NAME, 
 POLUCH_NAME, NORMOTGR)
AS 
SELECT /*+ RULE */
  a.ID,a.NUM_NAR,a.DATE_NAR,a.DATE_BEG,a.DATE_END,
  b.NOM_ZD,b.KOL,b.VES,
  KLS_STAN.STAN_NAME, KLS_PROD.ABBR_NPR as PROD_NAME, KLS_PREDPR.SHORT_NAME as POLUCH_NAME, NVL(KLS_PROD.NORMOTGR,0) as NORMOTGR
FROM KLS_NARIAD a, KLS_NAR_LINE b, MONTH, KLS_STAN, KLS_PROD, KLS_PREDPR
WHERE a.MESTO_ID=NVL(FOR_TEMP.GET_AS_NUM('MESTO_ID','MASTER','MO_RASPOR.XLS'),0)
  AND a.LOAD_TYPE_ID=NVL(FOR_TEMP.GET_AS_NUM('LOAD_TYPE_ID','MASTER','MO_RASPOR.XLS'),0)
  AND a.ID=NVL(FOR_TEMP.GET_AS_NUM('NARIAD_ID','MASTER','MO_RASPOR.XLS'),0)
  AND a.ID=b.NARIAD_ID
  AND MONTH.NOM_ZD=b.NOM_ZD
  AND MONTH.STAN_ID=KLS_STAN.ID
  AND MONTH.PROD_ID_NPR=KLS_PROD.ID_NPR
  AND MONTH.POLUCH_ID=KLS_PREDPR.ID
ORDER BY b.NOM_ZD;


