--
-- V_NPR_PRICES_SNP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_NPR_PRICES_SNP
(ID, CAT_CEN_ID, PROD_ID_NPR, CENA, NDS20, 
 NGSM25, AKCIZ, CENA_OTP, BEGIN_DATE, END_DATE, 
 INPUT_DATE, OWNERSHIP_ID, SUPPLIER_ID, PROTOKOL_DATE, PROTOKOL_NUM, 
 IS_ORIGINAL, PROTOKOL_BEGIN_DATE, CENA_NPO, NDS20_NPO, CENA_OTP_NPO)
AS 
SELECT 
  ID, 
  CAT_CEN_ID, 
  PROD_ID_NPR, 
  0 AS CENA      , 
  0 AS NDS20     , 
  0 AS NGSM25    , 
  0 AS AKCIZ     , 
  0 AS CENA_OTP  , 
  BEGIN_DATE , 
  TRUNC(DECODE(END_DATE,NULL,TO_DATE('31.12.2200','dd.mm.yyyy'),END_DATE),'DD') AS NEW_END_DATE  , 
  INPUT_DATE , 
  OWNERSHIP_ID  , 
  SUPPLIER_ID   , 
  PROTOKOL_DATE , 
  PROTOKOL_NUM  , 
  IS_ORIGINAL   , 
  PROTOKOL_BEGIN_DATE,  
  CENA_NPO,
  NDS20_NPO,
  CENA_OTP_NPO  
FROM NPR_PRICES
WHERE CAT_CEN_ID>=900 AND IS_ORIGINAL=1
ORDER BY CAT_CEN_ID,PROD_ID_NPR,BEGIN_DATE,NEW_END_DATE;


