--
-- V_OPL_SNP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_OPL_SNP
(NOM_DOK, PLAT_ID, LUKPLAT_ID, NPOPLAT_ID, PLAT_RS, 
 PLAT_MFO, PLAT_NAME, SUMMA, NUM_PORUCH, DATE_PORUCH, 
 PLAT_PORUCH_ID, PLAT_PORUCH_NAME, NAZN_PLAT, DATE_OPL, TIP_VEK_ID, 
 DAVAL_ID, N_SCHET, NUM_BANK_VIPISK, DOG_NUMBER, KOL_VEK, 
 BANK_ID, BANK_NAME, NAME_VEK, USERNAME, T_TIME, 
 T_DATE, K_SCHET, OLD_NOM_DOK, DISKONT, DATE_VIP_VEK, 
 PR_DOG, DATECANCEL, EMITENT, INV, FLAG_AVIZO, 
 DEN_SOP, FLAG_VZ, GOSPROG_ID, DOG_ID, LUKDOG_ID, 
 NPODOG_ID, IS_SNP)
AS 
SELECT /*+ RULE*/
  NOM_DOK     ,
  KLS_DOG.PREDPR_ID AS PLAT_ID    ,
  DECODE(NVL(KLS_DOG.LUKDOG_ID,0),0,KLS_DOG.PREDPR_ID,LUK_DOG.PREDPR_ID) AS LUKPLAT_ID,
  KLS_DOG.PREDPR_ID AS NPOPLAT_ID,
  RS_PLD      ,
  MFO_PLD     ,
  PLAT_DOG    ,
  SUMMA       ,
  NOM_POR     ,
  DATA_POR    ,
  KOD_PLP     ,
  PLAT_POR    ,
  NAZN_PLAT   ,
  DATA_POST   ,
  TIP         ,
  DAV_ORG     ,
  N_SCHET     ,
  BANK_NOM    ,
  KLS_DOG.DOG_NUMBER,
  KOL         ,
  BANK        ,
  N_BANK      ,
  NAM_VEK     ,
  PATH        ,
  T_TIME      ,
  T_DATE      ,
  K_SCHET     ,
  STN_DOK     ,
  DISKONT     ,
  DATA_VIP    ,
  PR_DOG      ,
  DATECANCEL  ,
  EMITENT     ,
  INV         ,
  AVIZO       ,
  DEN_SOP     ,
  VZ          ,
  PROGRAM     ,
  DOG_ID ,
  DECODE(NVL(KLS_DOG.LUKDOG_ID,0),0,DOG_ID,KLS_DOG.LUKDOG_ID) AS LUKDOG_ID,
  DOG_ID,
  IS_SNP
FROM OPL,KLS_DOG,KLS_DOG LUK_DOG
WHERE OPL.DOG_ID = KLS_DOG.ID
  AND KLS_DOG.LUKDOG_ID = LUK_DOG.ID (+);


