--
-- V_OPER_KVIT  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_OPER_KVIT
(DATE_OFORML, SHORT_NAME, EMAIL, NAME_STAN, NAME_POLUCH, 
 ABBR_NPR, SVED_NUM, NUM_CIST, NOM_ZD, VES_BRUTTO, 
 KOL, VES_CIST, PASP)
AS 
SELECT /*RULE*/ 
  KVIT.DATE_OFORML, 
  PLAT.SHORT_NAME, 
  PLAT.EMAIL,
  KLS_STAN.STAN_NAME || ' ' || kls_gdor.SHORT_NAME AS name_stan,
  poluch.PREDPR_NAME as name_poluch,
  kls_prod.ABBR_NPR,
  kvit.SVED_NUM,
  kvit.NUM_CIST,
  month.nom_zd,
  kvit.VES_BRUTTO,
  1 as kol,
  kvit.VES_CIST,
  0 as pasp
FROM KVIT , KLS_PREDPR POLUCH, MONTH , KLS_DOG , KLS_PREDPR PLAT, KLS_STAN ,
 KLS_GDOR, kls_prod
WHERE (POLUCH.ID = MONTH.POLUCH_ID) AND
 (MONTH.NOM_ZD = KVIT.NOM_ZD) AND
 (KLS_DOG.ID = MONTH.DOG_ID) AND
 (PLAT.ID = KLS_DOG.PREDPR_ID) AND
 (KLS_STAN.ID = MONTH.STAN_ID) AND
 (KLS_GDOR.ID = KLS_STAN.GDOR_ID) AND
 (kls_prod.ID_NPR=kvit.PROD_ID_NPR);


