--
-- V_ORG_STRUCTURE  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_ORG_STRUCTURE
(ID, ADRESS, NOTE, NAME, ORG_KIND_ID, 
 PREDPR_ID, ORG_TYPE_ID, IS_AUTO_LINK, FILIAL, WORKSHOP, 
 INN, IS_AUTO_KONS, PLAN_REAL, CITY_PREFIX_FILE, CITY_IN_XLS, 
 FULL_NAME, PARUS_CRN_AUTO, PARUS_CRN_KNT, PARUS_DEPARTMENT, PARUS_PLAN_AZC_DEP, 
 PARUS_PLAN_AUTO_DEP, PARUS_PLAN_MB_DEP, PARUS_PLAN_TRAN_DEP, PARUS_PLAN_AZC_DEP_2, PARUS_PLAN_AUTO_DEP_2, 
 PARUS_PLAN_TRAN_DEP_2, ABBR, RAST, TRANS_ORG, NO_WORK, 
 IS_AUTO, IS_AUTO_FOR_DISP_AZS, LOAD_NALIV_FROM_XLS, LOAD_NALIV_FROM_PARUS, LOAD_FAS_FROM_XLS, 
 LOAD_FAS_FROM_PARUS, KSSS_ID, FILIAL_ID, UCHASTOK_ID, FILIAL_NAME, 
 FILIAL_ABBR, AZS_NUMB, PARUS_RN, UCHASTOK_NAME, UCHASTOK_ABBR)
AS 
SELECT B."ID",
			 B."ADRESS",
			 B."NOTE",
			 B."NAME",
			 B."ORG_KIND_ID",
			 B."PREDPR_ID",
			 B."ORG_TYPE_ID",
			 B."IS_AUTO_LINK",
			 B."FILIAL",
			 B."WORKSHOP",
			 B."INN",
			 B."IS_AUTO_KONS",
			 B."PLAN_REAL",
			 B."CITY_PREFIX_FILE",
			 B."CITY_IN_XLS",
			 B."FULL_NAME",
			 B."PARUS_CRN_AUTO",
			 B."PARUS_CRN_KNT",
			 B."PARUS_DEPARTMENT",
			 B."PARUS_PLAN_AZC_DEP",
			 B."PARUS_PLAN_AUTO_DEP",
			 B."PARUS_PLAN_MB_DEP",
			 B."PARUS_PLAN_TRAN_DEP",
			 B."PARUS_PLAN_AZC_DEP_2",
			 B."PARUS_PLAN_AUTO_DEP_2",
			 B."PARUS_PLAN_TRAN_DEP_2",
			 B."ABBR",
			 B."RAST",
			 B."TRANS_ORG",
			 B."NO_WORK",
			 B."IS_AUTO",
			 B."IS_AUTO_FOR_DISP_AZS",
			 B."LOAD_NALIV_FROM_XLS",
			 B."LOAD_NALIV_FROM_PARUS",
			 B."LOAD_FAS_FROM_XLS",
			 B."LOAD_FAS_FROM_PARUS",
			 B."KSSS_ID",
			 B."FILIAL_ID",
			 B."UCHASTOK_ID",
			 C.NAME as FILIAL_NAME,
			 C.ABBR as FILIAL_ABBR,
			 (CASE
				 WHEN b.ID = 9067 THEN
					'999'
				 ELSE
					SUBSTR(B.NAME, 1, 3)
			 END) as AZS_NUMB,
			 (SELECT MAX(STORE_RN)
					FROM PARUS_STORE_ORG_STRU_LINK P
				 WHERE P.ORG_STRU_ID = B.ID
					 AND P.IS_MAIN = 1) as PARUS_RN,
			 D.NAME as UCHASTOK_NAME,
			 D.ABBR as UCHASTOK_ABBR
	FROM (SELECT A.*,
							 DECODE(A.FILIAL, NULL, NVL(rela.FILIAL_ID, 0), A.ID) AS FILIAL_ID, -- Филиал
							 DECODE(A.FILIAL, NULL, NVL(rela2.UCHASTOK_ID, 0), A.ID) AS UCHASTOK_ID -- Участок
					FROM ORG_STRUCTURE A,
							 (SELECT O_R.ORG_STRU_1_ID AS ORG_STRU_ID,
											 O_R.ORG_STRU_2_ID AS FILIAL_ID
									FROM ORG_RELATIONS O_R
								 WHERE O_R.KIND_RELA_ID = 1) rela,
							 (SELECT O_R.ORG_STRU_1_ID AS ORG_STRU_ID,
											 O_R.ORG_STRU_2_ID AS UCHASTOK_ID
									FROM ORG_LINKS O_R
								 WHERE O_R.KIND_RELA_ID = 1) rela2
				 WHERE A.ID = rela.ORG_STRU_ID(+)
					 AND A.ID = rela2.ORG_STRU_ID(+)) B,
			 ORG_STRUCTURE C,
			 ORG_STRUCTURE D
 WHERE B.FILIAL_ID = C.ID(+)
	 AND B.UCHASTOK_ID = D.ID(+);


