--
-- V_PARUS_TRANSINVCUST  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PARUS_TRANSINVCUST
(NSTORE, SSTORE, SSTORE_NAME, SSTORE_PBE, SDEPARTMENT_PBE, 
 SSTORE_CATALOG_CODE, SSTORE_CATALOG_NAME, NPRN, NCRN, SCATALOG_CODE, 
 SCATALOG_NAME, SDOCTYPE, PREF_NUMB, DDOCDATE, SACCNUMB, 
 SSTOPER, SFACEACC, SAGENT, SAGENT_NAME, STARIF, 
 SMOL, SSHEEPVIEW, SPAYTYPE, SSUBDIV, NRN, 
 NNOMEN, SNOMEN, SNOMENNAME, NNOMMODIF, SNOMMODIF, 
 SNOMMODIFNAME, NQUANTALT, NSUMMWITHNDS, NNOMEN_TYPE)
AS 
SELECT T.nSTORE, T.sSTORE, D.SNAME AS sSTORE_NAME, D.sPBE AS sSTORE_PBE, D.SDEPARTMENT AS sDEPARTMENT_PBE,
       E.CODE as sSTORE_CATALOG_CODE, E.NAME as sSTORE_CATALOG_NAME,
       Ts.nPRN, T.nCRN, F.CODE as sCATALOG_CODE, F.NAME as sCATALOG_NAME,
	   T.sDOCTYPE, T.SPREF_LTRIM||'-'||T.sNUMB_LTRIM AS PREF_NUMB, T.dDOCDATE, T.sACCNUMB, T.sSTOPER, T.SFACEACC, T.sAGENT, T.sAGENT_NAME, T.sTARIF, T.sMOL, T.sSHEEPVIEW, T.sPAYTYPE, T.sSUBDIV,
  	   Ts.nRN, Ts.nNOMEN, Ts.sNOMEN, Ts.sNOMENNAME, Ts.NNOMMODIF, Ts.sNOMMODIF , Ts.sNOMMODIFNAME, Ts.nQUANTALT, Ts.NSUMMWITHNDS, TS.NNOMEN_TYPE
FROM Parus.V_transinvcust@Oracle.World T,
         Parus.V_transinvcustspecs@Oracle.World Ts,
		 Parus.V_dicstore@Oracle.World D,Parus.acatalog@Oracle.World E,Parus.acatalog@Oracle.World F
       WHERE T.Nrn = Ts.Nprn
	     AND T.nstore=D.nrn
		 AND T.nCRN=F.RN
		 AND D.nCRN=E.RN
		 AND Ts.NNOMEN_TYPE=1 -- только товар
 		 AND T.dDOCDATE>=TO_DATE('01.01.2003','dd.mm.yyyy');


