--
-- V_PARUS_DICSTORE  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PARUS_DICSTORE
(NRN, NCRN, SNUMB, SNAME, SPBE, 
 SDEPARTMENT, SDEP_READY, NSTORE_TYPE, SKEEPER, NLOCK_SIGN, 
 IS_TRANSIT)
AS 
SELECT "NRN","NCRN","SNUMB","SNAME","SPBE","SDEPARTMENT","SDEP_READY","NSTORE_TYPE","SKEEPER","NLOCK_SIGN","IS_TRANSIT" FROM vaneev.v_dicstore_psv@oracle.world;


