--
-- V_PARUS_CONSORD_FACT  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PARUS_CONSORD_FACT
(ORD_RN, ORD_NUMB, AGENT_RN, AGENT_TAG, AGENT_NAME, 
 T_RN, DOCDATE, STORE, DOG_NUMB, NOMEN_RN, 
 NOMEN_TAG, NOMEN_NAME, VOLUME, MASSA, SUMMA)
AS 
SELECT "ORD_RN","ORD_NUMB","AGENT_RN","AGENT_TAG","AGENT_NAME","T_RN","DOCDATE","STORE","DOG_NUMB","NOMEN_RN","NOMEN_TAG","NOMEN_NAME","VOLUME","MASSA","SUMMA" FROM VANEEV.V_CONSORD_FACT_TO_MASTER_PSV@ORACLE.WORLD p;


