--
-- V_PARUS_CONSORDS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PARUS_CONSORDS
(LOAD_ABBR, NRN, NPRN, SINPUT_NUMBER, DINPUT_DATE, 
 NFACEACC, SFACEACC, NAGENT, SAGENT, SAGENTNAME, 
 SDOG_NUMB, DDOG_DATE, SPAY_TYPE, NFILIAL, SFILIAL, 
 NNOMEN, SNOMEN, SNOMENNAME, NNOMMODIF, SNOMMODIF, 
 SMODIFNAME, VES, PRICE, OTGR_VES, DPLAN_DATE, 
 NBLOCKED, NORD_STATE, VES_TONN, PRICE_TONN, OTGR_TONN, 
 FILIAL_ID, USL_OPL_ID)
AS 
SELECT /*+ ALL_ROWS*/
   '—¿Ã' AS LOAD_ABBR,
   p."NRN",p."NPRN",p."SINPUT_NUMBER",p."DINPUT_DATE",p."NFACEACC",p."SFACEACC",p."NAGENT",p."SAGENT",p."SAGENTNAME",p."SDOG_NUMB",p."DDOG_DATE",p."SPAY_TYPE",p."NFILIAL",p."SFILIAL",p."NNOMEN",p."SNOMEN",p."SNOMENNAME",p."NNOMMODIF",p."SNOMMODIF",p."SMODIFNAME",p."VES",p."PRICE",p."OTGR_VES",p."DPLAN_DATE",p."NBLOCKED",p."NORD_STATE",
   p.VES/1000 AS VES_TONN,
   p.PRICE*1000 AS PRICE_TONN,
   p.OTGR_VES/1000 as OTGR_TONN,
   ORG_STRUCTURE.ID AS FILIAL_ID,
   Get_Usl_Opl_From_Pay_Type(p.sPAY_TYPE) AS USL_OPL_ID
 FROM VANEEV.V_CONSORDS_TO_MASTER_PSV@ORACLE.WORLD p, ORG_STRUCTURE
 WHERE p.nFILIAL=ORG_STRUCTURE.PARUS_CRN_AUTO
   AND p.VES<>0
UNION ALL
SELECT
   ' Õ“' AS LOAD_ABBR,
   p."NRN",p."NPRN",p."SINPUT_NUMBER",p."DINPUT_DATE",p."NFACEACC",p."SFACEACC",p."NAGENT",p."SAGENT",p."SAGENTNAME",p."SDOG_NUMB",p."DDOG_DATE",p."SPAY_TYPE",p."NFILIAL",p."SFILIAL",p."NNOMEN",p."SNOMEN",p."SNOMENNAME",p."NNOMMODIF",p."SNOMMODIF",p."SMODIFNAME",p."VES",p."PRICE",p."OTGR_VES",p."DPLAN_DATE",p."NBLOCKED",p."NORD_STATE",
   p.VES/1000 AS VES_TONN,
   p.PRICE*1000 AS PRICE_TONN,
   p.OTGR_VES/1000 as OTGR_TONN,
   ORG_STRUCTURE.ID AS FILIAL_ID,
   Get_Usl_Opl_From_Pay_Type(p.sPAY_TYPE) AS USL_OPL_ID
 FROM VANEEV.V_CONSORDS_TO_MASTER_PSV@ORACLE.WORLD p, ORG_STRUCTURE
 WHERE p.nFILIAL=ORG_STRUCTURE.PARUS_CRN_KNT
   AND p.VES<>0;


