--
-- V_PARUS_FACEACC  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PARUS_FACEACC
(NRN, NCRN, NCOMPANY, NPRN, NAGENT, 
 NAGENT_CTLG, SAGENT, SNUMBER, NACC_TYPE, NACC_KIND, 
 NACC_CLASS, NVALID_DOCTYPE, SVALID_DOCTYPE, SVALID_DOCNUMB, DVALID_DOCDATE, 
 DPLAN_CLOSE_DATE, DFACT_CLOSE_DATE, NEXEC, NEXEC_CTLG, SEXECUTIVE, 
 SEXECUTIVE_NAME, SCURRENCY, NCURRENCY_RN, NCREDIT_SUM, NBEGIN_SUM, 
 NCURRENT_SUM, NFCACGR, SFCACGR, SSPEC_MARK1, SSPEC_MARK2, 
 SSPEC_MARK3, SSPEC_MARK4, SSPEC_MARK5, SNOTE, NOPER_FLAG, 
 DPLAN_OPEN_DATE, DFACT_OPEN_DATE, NPLAN_SUM, NSERV_SUM, NSERV_PERCENT, 
 NAGNACC, SAGNACC, NAGNFI, SAGNFI, NAGNFO, 
 SAGNFO, NAGN_TRANS, SAGN_TRANS, NSIGN_CONTRACT, NORDER_SIGN, 
 NSUBDIV, NSDIVCRN, SSUBDIV, NTARIF, STARIF, 
 NDISCOUNT, NPAY_TYPE, SPAY_TYPE, NSHIP_TYPE, SSHIP_TYPE, 
 NPRICE_TYPE, NDOC_SERV, NPLAN_SERV, NFACT_SERV, NDOC_SHIP, 
 NPLAN_SHIP, NFACT_SHIP, NDOC_INCOME, NPLAN_INCOME, NFACT_INCOME, 
 NDOC_POSTED, NPLAN_POSTED, NFACT_POSTED, NDOC_PAYED, NPLAN_PAYED, 
 NFACT_PAYED, NFINERULE, SFINERULE, NFACTREST, NPLANREST, 
 DPRICE_DATE, AGNABBR, AGNTYPE, AGNNAME, AGNIDNUMB, 
 NATECONSECT_RN, NATECONSECT, ORGCODE, AGNFAMILYNAME, AGNFIRSTNAME, 
 AGNLASTNAME, AGNFAMILYNAME_TO, AGNFIRSTNAME_TO, AGNLASTNAME_TO, AGNFAMILYNAME_FR, 
 AGNFIRSTNAME_FR, AGNLASTNAME_FR, EMP, EMPPOST, AGNBURN, 
 GEOGRAFY_RN, GEOGRAFY_CODE, ADDR_COUNTRY, ADDR_REG, ADDR_DISTRICT, 
 ADDR_CITY, NADDR_MUNIC_DIST, SADDR_MUNIC_DIST, NADDR_ADMIN_DIST, SADDR_ADMIN_DIST, 
 ADDR_STREET, ADDR_HOUSE, ADDR_BLOCK, ADDR_FLAT, ADDR_POST, 
 PHONE, PHONE2, FAX, TELEX, MAIL, 
 PASSPORT_SER, PASSPORT_NUMB, PASSPORT_WHEN, PASSPORT_WHO, AGN_COMMENT, 
 DDISCDATE, NSEX, SPENSION_NBR, NPASSPORT_TYPE, SPASSPORT_TYPE)
AS 
SELECT "NRN","NCRN","NCOMPANY","NPRN","NAGENT","NAGENT_CTLG","SAGENT","SNUMBER","NACC_TYPE","NACC_KIND","NACC_CLASS","NVALID_DOCTYPE","SVALID_DOCTYPE","SVALID_DOCNUMB","DVALID_DOCDATE","DPLAN_CLOSE_DATE","DFACT_CLOSE_DATE","NEXEC","NEXEC_CTLG","SEXECUTIVE","SEXECUTIVE_NAME","SCURRENCY","NCURRENCY_RN","NCREDIT_SUM","NBEGIN_SUM","NCURRENT_SUM","NFCACGR","SFCACGR","SSPEC_MARK1","SSPEC_MARK2","SSPEC_MARK3","SSPEC_MARK4","SSPEC_MARK5","SNOTE","NOPER_FLAG","DPLAN_OPEN_DATE","DFACT_OPEN_DATE","NPLAN_SUM","NSERV_SUM","NSERV_PERCENT","NAGNACC","SAGNACC","NAGNFI","SAGNFI","NAGNFO","SAGNFO","NAGN_TRANS","SAGN_TRANS","NSIGN_CONTRACT","NORDER_SIGN","NSUBDIV","NSDIVCRN","SSUBDIV","NTARIF","STARIF","NDISCOUNT","NPAY_TYPE","SPAY_TYPE","NSHIP_TYPE","SSHIP_TYPE","NPRICE_TYPE","NDOC_SERV","NPLAN_SERV","NFACT_SERV","NDOC_SHIP","NPLAN_SHIP","NFACT_SHIP","NDOC_INCOME","NPLAN_INCOME","NFACT_INCOME","NDOC_POSTED","NPLAN_POSTED","NFACT_POSTED","NDOC_PAYED","NPLAN_PAYED","NFACT_PAYED","NFINERULE","SFINERULE","NFACTREST","NPLANREST","DPRICE_DATE","AGNABBR","AGNTYPE","AGNNAME","AGNIDNUMB","NATECONSECT_RN","NATECONSECT","ORGCODE","AGNFAMILYNAME","AGNFIRSTNAME","AGNLASTNAME","AGNFAMILYNAME_TO","AGNFIRSTNAME_TO","AGNLASTNAME_TO","AGNFAMILYNAME_FR","AGNFIRSTNAME_FR","AGNLASTNAME_FR","EMP","EMPPOST","AGNBURN","GEOGRAFY_RN","GEOGRAFY_CODE","ADDR_COUNTRY","ADDR_REG","ADDR_DISTRICT","ADDR_CITY","NADDR_MUNIC_DIST","SADDR_MUNIC_DIST","NADDR_ADMIN_DIST","SADDR_ADMIN_DIST","ADDR_STREET","ADDR_HOUSE","ADDR_BLOCK","ADDR_FLAT","ADDR_POST","PHONE","PHONE2","FAX","TELEX","MAIL","PASSPORT_SER","PASSPORT_NUMB","PASSPORT_WHEN","PASSPORT_WHO","AGN_COMMENT","DDISCDATE","NSEX","SPENSION_NBR","NPASSPORT_TYPE","SPASSPORT_TYPE" FROM Parus.V_FACEACC@Oracle.world;


