--
-- V_PAYMENTS_CORR_BILLS_PAIRS_P  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PAYMENTS_CORR_BILLS_PAIRS_P
(NOM_DOK, NOM_SF, DATE_VYP_SF, DATE_KVIT, DATE_BUXG, 
 SUMMA_DOK, NDS_DOK, GSM_DOK, AKCIZ_DOK, PRIM, 
 FIO_ISPOL, KOL_DN, OLD_NOM_DOK, NOM_ZD, OWNER_ID, 
 DOG_ID, USL_NUMBER, PROD_ID_NPR, PROD_SUM, PROD_NDS, 
 PROD_GSM, PROD_AKCIZ, DATE_MOS, NPO_SF, OLD_NOM_SF, 
 IS_AGENT, NUM_5_DAY, LUK_DOG_ID, LUK_USL_NUMBER, LUK_SUMMA_DOK, 
 LUK_NDS_DOK, SNP_DOG_ID, SNP_USL_NUMBER, LUK_KOL_DN, SNP_KOL_DN, 
 NAZN_OTG_ID, KORR_5_DAY, PROTO_NUM, PROTO_DATE, NO_AKCIZ, 
 KORR_PROD)
AS 
select /*+ RULE */
  "NOM_DOK","NOM_SF","DATE_VYP_SF","DATE_KVIT","DATE_BUXG","SUMMA_DOK","NDS_DOK","GSM_DOK","AKCIZ_DOK","PRIM","FIO_ISPOL","KOL_DN","OLD_NOM_DOK","NOM_ZD","OWNER_ID","DOG_ID","USL_NUMBER","PROD_ID_NPR","PROD_SUM","PROD_NDS","PROD_GSM","PROD_AKCIZ","DATE_MOS","NPO_SF","OLD_NOM_SF","IS_AGENT","NUM_5_DAY","LUK_DOG_ID","LUK_USL_NUMBER","LUK_SUMMA_DOK","LUK_NDS_DOK","SNP_DOG_ID","SNP_USL_NUMBER","LUK_KOL_DN","SNP_KOL_DN","NAZN_OTG_ID","KORR_5_DAY","PROTO_NUM","PROTO_DATE","NO_AKCIZ","KORR_PROD"
  from bills where
  ((old_nom_dok<>0 and summa_dok<0) or
   nom_dok in (select /*+ RULE */ old_nom_dok from bills where old_nom_dok<>0)) and
   not exists (select nom_dok from payments_on_bills where bills.nom_dok=payments_on_bills.nom_dok);


