--
-- V_PARUS_GRAPHPOINT  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PARUS_GRAPHPOINT
(NCONTRACT, SCONTRACT, EXT_NUMBER, NCONTRACT_STATUS, NSTAGE, 
 SSTAGE, NSTAGE_STATUS, NRN, NFACEACC, SFACEACC, 
 NAGENT, SAGENT, SAGENTNAME, SDOG_NUMB, DDOG_DATE, 
 SPAY_TYPE, SGRAPHPOINT, NDEPARTMENT, SDEPARTMENT_CODE, SDEPARTMENT, 
 NSUPPLIER, SSUPPLIER_CODE, SSUPPLIER, NNOMEN, SNOMEN, 
 SNOMENNAME, NNOMMODIF, SNOMMODIF, SMODIFNAME, VES, 
 PRICE, OTGR_VES, BEGIN_DATE, END_DATE, LOAD_ABBR, 
 VES_TONN, PRICE_TONN, FILIAL_ID, SUPPLIER_ID, TIP_REAL_ID, 
 VID_REAL_ID, ORG_KIND_ID)
AS 
SELECT /*+ ALL_ROWS*/
	  p."NCONTRACT",p."SCONTRACT",p."EXT_NUMBER",p."NCONTRACT_STATUS",p."NSTAGE",p."SSTAGE",p."NSTAGE_STATUS",p."NRN",p."NFACEACC",p."SFACEACC",p."NAGENT",p."SAGENT",p."SAGENTNAME",p."SDOG_NUMB",p."DDOG_DATE",p."SPAY_TYPE",p."SGRAPHPOINT",p."NDEPARTMENT",p."SDEPARTMENT_CODE",p."SDEPARTMENT",p."NSUPPLIER",p."SSUPPLIER_CODE",p."SSUPPLIER",p."NNOMEN",p."SNOMEN",p."SNOMENNAME",p."NNOMMODIF",p."SNOMMODIF",p."SMODIFNAME",p."VES",p."PRICE",p."OTGR_VES",p."BEGIN_DATE",p."END_DATE",
	  '—¿Ã' AS LOAD_ABBR,
	  p.VES/1000 AS VES_TONN,
	  p.PRICE*1000 AS PRICE_TONN,
	  ORG_STRUCTURE.ID AS FILIAL_ID,
	  DECODE(p.SSUPPLIER_CODE,'¬ŒÀ√¿',3353,'Õ»∆Õ≈¬ŒÀ∆— ',3352,'œ≈–Ã',3354,8) as SUPPLIER_ID,
	  1 as TIP_REAL_ID,
	  1 as VID_REAL_ID,
	  1 as ORG_KIND_ID
	FROM VANEEV.V_FCACOPERPLANS_IN_PSV@ORACLE.WORLD p, ORG_STRUCTURE
	WHERE (p.SDEPARTMENT_CODE=ORG_STRUCTURE.PARUS_PLAN_AUTO_DEP OR p.SDEPARTMENT_CODE=ORG_STRUCTURE.PARUS_PLAN_AUTO_DEP_2)
	  AND p.VES<>0
	UNION ALL
    SELECT
	  p."NCONTRACT",p."SCONTRACT",p."EXT_NUMBER",p."NCONTRACT_STATUS",p."NSTAGE",p."SSTAGE",p."NSTAGE_STATUS",p."NRN",p."NFACEACC",p."SFACEACC",p."NAGENT",p."SAGENT",p."SAGENTNAME",p."SDOG_NUMB",p."DDOG_DATE",p."SPAY_TYPE",p."SGRAPHPOINT",p."NDEPARTMENT",p."SDEPARTMENT_CODE",p."SDEPARTMENT",p."NSUPPLIER",p."SSUPPLIER_CODE",p."SSUPPLIER",p."NNOMEN",p."SNOMEN",p."SNOMENNAME",p."NNOMMODIF",p."SNOMMODIF",p."SMODIFNAME",p."VES",p."PRICE",p."OTGR_VES",p."BEGIN_DATE",p."END_DATE",
	  ' Õ“' AS LOAD_ABBR,
	  p.VES/1000 AS VES_TONN,
	  p.PRICE*1000 AS PRICE_TONN,
	  ORG_STRUCTURE.ID AS FILIAL_ID,
	  DECODE(p.SSUPPLIER_CODE,'¬ŒÀ√¿',3353,'Õ»∆Õ≈¬ŒÀ∆— ',3352,'œ≈–Ã',3354,8) as SUPPLIER_ID,
	  1 as TIP_REAL_ID,
	  1 as VID_REAL_ID,
	  1 as ORG_KIND_ID
	FROM VANEEV.V_FCACOPERPLANS_IN_PSV@ORACLE.WORLD p, ORG_STRUCTURE
	WHERE p.SDEPARTMENT_CODE=ORG_STRUCTURE.PARUS_PLAN_MB_DEP
	  AND p.VES<>0
	UNION ALL
    SELECT
	  p."NCONTRACT",p."SCONTRACT",p."EXT_NUMBER",p."NCONTRACT_STATUS",p."NSTAGE",p."SSTAGE",p."NSTAGE_STATUS",p."NRN",p."NFACEACC",p."SFACEACC",p."NAGENT",p."SAGENT",p."SAGENTNAME",p."SDOG_NUMB",p."DDOG_DATE",p."SPAY_TYPE",p."SGRAPHPOINT",p."NDEPARTMENT",p."SDEPARTMENT_CODE",p."SDEPARTMENT",p."NSUPPLIER",p."SSUPPLIER_CODE",p."SSUPPLIER",p."NNOMEN",p."SNOMEN",p."SNOMENNAME",p."NNOMMODIF",p."SNOMMODIF",p."SMODIFNAME",p."VES",p."PRICE",p."OTGR_VES",p."BEGIN_DATE",p."END_DATE",
	  '—¿Ã' AS LOAD_ABBR,
	  p.VES/1000 AS VES_TONN,
	  p.PRICE*1000 AS PRICE_TONN,
	  ORG_STRUCTURE.ID AS FILIAL_ID,
	  DECODE(p.SSUPPLIER_CODE,'¬ŒÀ√¿',3353,'Õ»∆Õ≈¬ŒÀ∆— ',3352,'œ≈–Ã',3354,8) as SUPPLIER_ID,
	  1 as TIP_REAL_ID,
	  1 as VID_REAL_ID,
	  5 as ORG_KIND_ID
	FROM VANEEV.V_FCACOPERPLANS_IN_PSV@ORACLE.WORLD p, ORG_STRUCTURE
	WHERE (p.SDEPARTMENT_CODE=ORG_STRUCTURE.PARUS_PLAN_AZC_DEP OR p.SDEPARTMENT_CODE=ORG_STRUCTURE.PARUS_PLAN_AZC_DEP_2)
	  AND p.VES<>0;


