--
-- V_PARUS_DICNOMNS_PSV  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PARUS_DICNOMNS_PSV
(RN, CRN, NOMEN_CODE, NOMEN_NAME, GROUP_CODE, 
 GROUP_TYPE)
AS 
SELECT "RN","CRN","NOMEN_CODE","NOMEN_NAME","GROUP_CODE","GROUP_TYPE" FROM vaneev.v_dicnomns_psv@oracle.world;


