--
-- V_PF_RUB  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PF_RUB
(LEVEL_POS, NP_NAME, PLANSTRU_ID, PLAN_VES, PLAN_SUM, 
 PLANOBR_VES, FACT_VES, FACT_SUM)
AS 
select T1.LEVEL_POS,
       SUBSTR('                          ',1,T1.LEVEL_POS*3) || T1.NAME as NAME,
       A."PLANSTRU_ID",A."PLAN_VES",A."PLAN_SUM",A."PLANOBR_VES",A."FACT_VES",A."FACT_SUM"
from V_MASTER_REPORTS R, KLS_PLANSTRU T1, V_PF_RUB_DATA A 
where (nls_upper(R.REPORT_FILE) = 'PF_RUB.XLS') and
      (T1.BEGIN_DATE <= R.END_DATE) and
      (T1.END_DATE >= R.BEGIN_DATE) and
      (T1.ID = A.PLANSTRU_ID(+))
order by KOD_SGR, KOD_SPG, KOD_RZD, KOD_PRZ, KOD_GRP, KOD_PGR;


