--
-- V_PLAN_POST_6  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_POST_6
(PLAN_ID, PLAN_PER_ID, PROD_ID_NPR, PLANSTRU_ID, LEVEL_POS, 
 NAME, KOD_SGR, KOD_SPG, KOD_RZD, KOD_PRZ, 
 KOD_GRP, KOD_PGR, PARENT_ID, DOG_ID, PAYFORM_ID, 
 PLAN_VES, PLAN_SUM)
AS 
SELECT
 PLAN_POST.PLAN_ID,
 PLAN_POST.PLAN_PER_ID,
 PLAN_POST.PROD_ID_NPR,
 PLAN_POST.PLANSTRU_ID,
 KLS_PLANSTRU.LEVEL_POS,
 KLS_PLANSTRU.NAME,
 KLS_PLANSTRU.KOD_SGR,
 KLS_PLANSTRU.KOD_SPG,
 KLS_PLANSTRU.KOD_RZD,
 KLS_PLANSTRU.KOD_PRZ,
 KLS_PLANSTRU.KOD_GRP,
 KLS_PLANSTRU.KOD_PGR,
 KLS_PLANSTRU.PARENT_ID,
 PLAN_POST.DOG_ID,
 PLAN_POST.PAYFORM_ID,
 SUM(PLAN_POST.PLAN_VES) AS plan_ves,
 SUM(PLAN_POST.PLAN_SUM) AS plan_sum
FROM KLS_PLANSTRU, PLAN_POST
WHERE
(KLS_PLANSTRU.ID = PLAN_POST.PLANSTRU_ID) AND
(KLS_PLANSTRU.LEVEL_POS>=6)
GROUP BY
 PLAN_POST.PLAN_ID,
 PLAN_POST.PLAN_PER_ID,
 PLAN_POST.PROD_ID_NPR,
 PLAN_POST.PLANSTRU_ID,
 KLS_PLANSTRU.LEVEL_POS,
 KLS_PLANSTRU.NAME,
 KLS_PLANSTRU.KOD_SGR,
 KLS_PLANSTRU.KOD_SPG,
 KLS_PLANSTRU.KOD_RZD,
 KLS_PLANSTRU.KOD_PRZ,
 KLS_PLANSTRU.KOD_GRP,
 KLS_PLANSTRU.KOD_PGR,
 KLS_PLANSTRU.PARENT_ID,
 PLAN_POST.DOG_ID,
 PLAN_POST.PAYFORM_ID;


