--
-- V_PLAN_FACT_REALIZ  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_FACT_REALIZ
(DATE_BEGIN, DATE_END, DATE_PLAN, FILIAL_ID, FILIAL_NAME, 
 REGION_ORDER, REGION_NAME, NAPR_ORDER, NAPR_NAME, PROD_ID_NPR, 
 GROUP_ORDER, GROUP_NAME, BEGIN_OST, PLAN_POST_VES, NORMA_POST_VES, 
 FACT_POST_VES, RESURS, PLAN_REAL_VES, NORMA_REAL_VES, FACT_REAL_VES, 
 END_OST, TERMINAL_NAME, OSUSER_NAME)
AS 
SELECT "DATE_BEGIN","DATE_END","DATE_PLAN","FILIAL_ID","FILIAL_NAME","REGION_ORDER","REGION_NAME","NAPR_ORDER",
"NAPR_NAME","PROD_ID_NPR","GROUP_ORDER","GROUP_NAME","BEGIN_OST","PLAN_POST_VES","NORMA_POST_VES","FACT_POST_VES","RESURS",
"PLAN_REAL_VES","NORMA_REAL_VES","FACT_REAL_VES","END_OST",TERMINAL_NAME,OSUSER_NAME FROM PLAN_FACT_REALIZ
WHERE TIP_ROW='œÀ¿Õ-‘¿ “ œŒ—“¿¬ » » –≈¿À»«¿÷»»'
  AND TERMINAL_NAME = For_Init.GetCurrTerm
  AND OSUSER_NAME = For_Init.GetCurrUser;


