--
-- V_PLAN_POST_5  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_POST_5
(PLAN_ID, PLAN_PER_ID, PROD_ID_NPR, PLANSTRU_ID, LEVEL_POS, 
 NAME, KOD_SGR, KOD_SPG, KOD_RZD, KOD_PRZ, 
 KOD_GRP, KOD_PGR, PARENT_ID, DOG_ID, PAYFORM_ID, 
 PLAN_VES, PLAN_SUM)
AS 
SELECT
   PLAN_ID,
   PLAN_PER_ID,
   PROD_ID_NPR,
   KLS_PLANSTRU.ID AS PLANSTRU_ID,
   KLS_PLANSTRU.level_pos,
   KLS_PLANSTRU.NAME,
   KOD_SGR1,
   KOD_SPG1,
   KOD_RZD1,
   KOD_PRZ1,
   KOD_GRP1,
   KOD_PGR1,
   KLS_PLANSTRU.PARENT_ID,
   DOG_ID,
   PAYFORM_ID,
   plan_ves,
   plan_sum
FROM KLS_PLANSTRU,(
 SELECT
 PLAN_POST.PLAN_ID,
 PLAN_POST.PLAN_PER_ID,
 PLAN_POST.PROD_ID_NPR,
 PLAN_POST.PLANSTRU_ID,
 KLS_PLANSTRU.KOD_SGR AS kod_sgr1,
 KLS_PLANSTRU.KOD_SPG AS kod_spg1,
 KLS_PLANSTRU.KOD_RZD AS kod_rzd1,
 KLS_PLANSTRU.KOD_PRZ AS kod_prz1,
 KLS_PLANSTRU.KOD_GRP AS KOD_GRP1,
 0 AS KOD_PGR1,
 PLAN_POST.DOG_ID,
 PLAN_POST.PAYFORM_ID,
 SUM(PLAN_POST.PLAN_VES) AS plan_ves,
 SUM(PLAN_POST.PLAN_SUM) AS plan_sum
FROM KLS_PLANSTRU, PLAN_POST
WHERE
(KLS_PLANSTRU.ID = PLAN_POST.PLANSTRU_ID) AND
(KLS_PLANSTRU.LEVEL_POS>=5)
GROUP BY
 PLAN_POST.PLAN_ID,
 PLAN_POST.PLAN_PER_ID,
 PLAN_POST.PROD_ID_NPR,
 PLAN_POST.PLANSTRU_ID,
 KLS_PLANSTRU.KOD_SGR,
 KLS_PLANSTRU.KOD_SPG,
 KLS_PLANSTRU.KOD_RZD,
 KLS_PLANSTRU.KOD_PRZ,
 KLS_PLANSTRU.KOD_GRP,
 0,
 PLAN_POST.DOG_ID,
 PLAN_POST.PAYFORM_ID)
WHERE kod_sgr=kod_sgr1 AND kod_spg=kod_spg1 AND kod_rzd=kod_rzd1 AND
      kod_prz=kod_prz1 AND kod_grp=kod_grp1 AND kod_pgr=kod_pgr1;


