--
-- V_PLAN_FOR_AZS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_FOR_AZS
(IS_SIGN1, IS_SIGN2, DATE_PLAN, AZS_ID, AZS_NUMB, 
 AZS_NAME, FILIAL_ID, FILIAL_NAME, PROD_ID_NPR, ABBR_NPR, 
 NAME_NPR, VES, SUMM)
AS 
SELECT
  MIN(A.IS_SIGN1) as IS_SIGN1,
  MIN(A.IS_SIGN2) as IS_SIGN2,
  A.DATE_PLAN,
  A.SKLAD_ID as AZS_ID, C.AZS_NUMB, C.NAME as AZS_NAME, C.FILIAL_ID, C.FILIAL_NAME,
  A.PROD_ID_NPR, E.GROUP_ABBR as ABBR_NPR, B.NAME_NPR,
  SUM(A.VES) as VES, sum(a.summa) as summ
  FROM PLAN_REALIZ A, KLS_PROD B, v_ORG_STRUCTURE C, KLS_PROD_GROUPS_DESC D, KLS_PROD_GROUPS E,
  (SELECT * FROM V_MASTER_REPORTS WHERE NLS_UPPER(REPORT_FILE)='PLAN_AZS.XLS') r
WHERE A.DATE_PLAN=TRUNC(r.end_date,'MONTH')
  AND C.FILIAL_ID=DECODE(NVL(r.FILIAL_ID,0),0,C.FILIAL_ID,r.FILIAL_ID)
  AND A.SKLAD_ID=C.ID
  AND A.ORG_KIND_ID IN (5,12)
  AND A.PROD_ID_NPR=B.ID_NPR
  AND A.PROD_ID_NPR=D.PROD_ID_NPR AND D.PROD_TYPE_GRP_ID=5 AND D.PROD_GROUPS_ID=E.ID
  AND A.IS_SIGN1=1 AND A.IS_SIGN2=1
GROUP BY
  A.DATE_PLAN,
  A.SKLAD_ID, C.AZS_NUMB, C.NAME, C.FILIAL_ID, C.FILIAL_NAME,
  A.PROD_ID_NPR, E.GROUP_ABBR, B.NAME_NPR
ORDER BY DATE_PLAN, FILIAL_ID, LPAD(TRIM(AZS_NUMB),5,' '), AZS_ID, ABBR_NPR;


