--
-- V_PLAN_FACT_PARUS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_FACT_PARUS
(NB_NAME, NOMMODIF_NAME, DICNOMNS_RN, NOMMODIF_RN, CONTRACTS_RN, 
 CONTRACTS_NUMB, AGENT_RN, AGENT_NAME, GROUP_ORDER, PLAN_MON_V, 
 PLAN_NAR_V, ZAYV_RN, ZAYV_PREF, TIP_OTGR_RN, TIP_OTGR_NAME, 
 PAYTYPE_RN, PAYTYPE_NAME, POLUCH_RN, POLUCH_NAME, ZAYV, 
 FACT_V)
AS 
SELECT
  NB_NAME,
  NOMMODIF_NAME,
  DICNOMNS_RN,
  NOMMODIF_RN,
  CONTRACTS_RN,
  CONTRACTS_NUMB,
  AGENT_RN,
  AGENT_NAME,
  GROUP_ORDER,
  SUM(PLAN_MON_V) AS PLAN_MON_V,
  SUM(PLAN_NAR_V) AS PLAN_NAR_V,
  ZAYV_RN,
  MAX(ZAYV_PREF),
  MAX(TIP_OTGR_RN),
  MAX(TIP_OTGR_NAME),
  MAX(PAYTYPE_RN),
  MAX(PAYTYPE_NAME),
  MAX(POLUCH_RN),
  MAX(POLUCH_NAME),
  SUM(ZAYV),
  SUM(FACT_V)
FROM PLAN_FACT
WHERE TIP_ROW='œ¿–”—'
  AND TERMINAL_NAME = For_Init.GetCurrTerm
  AND OSUSER_NAME = For_Init.GetCurrUser
GROUP BY
  NB_NAME,
  NOMMODIF_NAME,
  DICNOMNS_RN,
  NOMMODIF_RN,
  CONTRACTS_RN,
  CONTRACTS_NUMB,
  AGENT_RN,
  AGENT_NAME,
  GROUP_ORDER,
  ZAYV_RN;


