--
-- V_PLAN_FACT_3  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_FACT_3
(TIP_ROW, GROUP_ORDER, GROUP_NAME, PROD_ORDER, PROD_ID_NPR, 
 PLANSTRU_ORDER, PLANSTRU_ID, LEVEL_POS, PLANSTRU_NAME, KOD_SGR, 
 KOD_SPG, KOD_RZD, KOD_PRZ, KOD_GRP, KOD_PGR, 
 KORR_MON, KORR_NAR, DATE_PLAN, PLAN_MON, PLAN_NAR, 
 OBR_MON, OBR_NAR, DATE_ZAYV, ZAYV, DATE_FACT, 
 TIME_FACT, FACT_SUT, FACT, PLAN_NAR_RASP, OBR_NAR_RASP, 
 KORR_NAR_RASP, FACT_DECADA_1, FACT_DECADA_2, FACT_DECADA_3, PLAN_DECADA_1, 
 PLAN_DECADA_2, PLAN_DECADA_3)
AS 
SELECT
   TIP_ROW,
   GROUP_ORDER,
   GROUP_NAME,
   PROD_ORDER,
   PROD_ID_NPR,
   LTRIM(TO_CHAR(KLS_PLANSTRU.KOD_SGR*1000000000000000+KLS_PLANSTRU.KOD_SPG*1000000000000+KLS_PLANSTRU.KOD_RZD*1000000000+KLS_PLANSTRU.KOD_PRZ*1000000+KLS_PLANSTRU.KOD_GRP*1000+KLS_PLANSTRU.KOD_PGR,'000000000000000000')) AS PLANSTRU_ORDER,
   KLS_PLANSTRU.ID AS PLANSTRU_ID,
   KLS_PLANSTRU.level_pos,
   KLS_PLANSTRU.NAME,
   KOD_SGR1,
   KOD_SPG1,
   KOD_RZD1,
   KOD_PRZ1,
   KOD_GRP1,
   KOD_PGR1,
   DATE_PLAN,
   PLAN_MON,
   PLAN_NAR,
   OBR_MON,
   OBR_NAR,
   KORR_MON,
   KORR_NAR,
   DATE_ZAYV,
   ZAYV,
   DATE_FACT,
   TIME_FACT,
   FACT_SUT,
   FACT,
   PLAN_NAR_RASP,
   OBR_NAR_RASP,
   KORR_NAR_RASP,
   FACT_DECADA_1,FACT_DECADA_2,FACT_DECADA_3, PLAN_DECADA_1, PLAN_DECADA_2, PLAN_DECADA_3
 FROM KLS_PLANSTRU,(
 SELECT
   V_PLAN_FACT.TIP_ROW,
   V_PLAN_FACT.GROUP_ORDER,
   V_PLAN_FACT.GROUP_NAME,
   V_PLAN_FACT.PROD_ORDER,
   V_PLAN_FACT.PROD_ID_NPR,
   V_PLAN_FACT.PLANSTRU_ORDER,
   V_PLAN_FACT.PLANSTRU_ID,
   0 AS level_pos,
   '' AS NAME,
   KLS_PLANSTRU.KOD_SGR AS kod_sgr1,
   KLS_PLANSTRU.KOD_SPG AS kod_spg1,
   KLS_PLANSTRU.KOD_RZD AS kod_rzd1,
   0 AS kod_prz1,
   0 AS KOD_GRP1,
   0 AS KOD_PGR1,
   MAX(V_PLAN_FACT.DATE_PLAN) AS DATE_PLAN,
   SUM(V_PLAN_FACT.PLAN_MON) AS PLAN_MON,
   SUM(V_PLAN_FACT.PLAN_NAR) AS PLAN_NAR,
   SUM(V_PLAN_FACT.OBR_MON) AS OBR_MON,
   SUM(V_PLAN_FACT.OBR_NAR) AS OBR_NAR,
   SUM(V_PLAN_FACT.KORR_MON) AS KORR_MON,
   SUM(V_PLAN_FACT.KORR_NAR) AS KORR_NAR,
   MAX(V_PLAN_FACT.DATE_ZAYV) AS DATE_ZAYV,
   SUM(V_PLAN_FACT.ZAYV) AS ZAYV,
   MAX(V_PLAN_FACT.DATE_FACT) AS DATE_FACT,
   MAX(V_PLAN_FACT.TIME_FACT) AS TIME_FACT,
   SUM(V_PLAN_FACT.FACT_SUT) AS FACT_SUT,
   SUM(V_PLAN_FACT.FACT) AS FACT,
   SUM(V_PLAN_FACT.PLAN_NAR_RASP) AS PLAN_NAR_RASP,
   SUM(V_PLAN_FACT.OBR_NAR_RASP) AS OBR_NAR_RASP,
   SUM(V_PLAN_FACT.KORR_NAR_RASP) AS KORR_NAR_RASP,
   SUM(V_PLAN_FACT.FACT_DECADA_1) AS FACT_DECADA_1,
   SUM(V_PLAN_FACT.FACT_DECADA_2) AS FACT_DECADA_2,
   SUM(V_PLAN_FACT.FACT_DECADA_3) AS FACT_DECADA_3,
   SUM(V_PLAN_FACT.PLAN_DECADA_1) AS PLAN_DECADA_1,
   SUM(V_PLAN_FACT.PLAN_DECADA_2) AS PLAN_DECADA_2,
   SUM(V_PLAN_FACT.PLAN_DECADA_3) AS PLAN_DECADA_3
FROM KLS_PLANSTRU, V_PLAN_FACT
WHERE V_PLAN_FACT.PLANSTRU_ID=KLS_PLANSTRU.ID
  AND KLS_PLANSTRU.LEVEL_POS>=3
GROUP BY
   V_PLAN_FACT.TIP_ROW,
   V_PLAN_FACT.GROUP_ORDER,
   V_PLAN_FACT.GROUP_NAME,
   V_PLAN_FACT.PROD_ORDER,
   V_PLAN_FACT.PROD_ID_NPR,
   V_PLAN_FACT.PLANSTRU_ORDER,
   V_PLAN_FACT.PLANSTRU_ID,
   KLS_PLANSTRU.KOD_SGR,
   KLS_PLANSTRU.KOD_SPG,
   KLS_PLANSTRU.KOD_RZD)
WHERE kod_sgr=kod_sgr1 AND kod_spg=kod_spg1 AND kod_rzd=kod_rzd1 AND
      kod_prz=kod_prz1 AND kod_grp=kod_grp1 AND kod_pgr=kod_pgr1;


