--
-- V_PLAN_FACT_6  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_FACT_6
(TIP_ROW, GROUP_ORDER, GROUP_NAME, PROD_ORDER, PROD_ID_NPR, 
 PLANSTRU_ORDER, PLANSTRU_ID, LEVEL_POS, PLANSTRU_NAME, KOD_SGR, 
 KOD_SPG, KOD_RZD, KOD_PRZ, KOD_GRP, KOD_PGR, 
 DATE_PLAN, PLAN_MON, PLAN_NAR, OBR_MON, OBR_NAR, 
 KORR_MON, KORR_NAR, DATE_ZAYV, ZAYV, DATE_FACT, 
 TIME_FACT, FACT_SUT, FACT, PLAN_NAR_RASP, OBR_NAR_RASP, 
 KORR_MON_RASP, FACT_DECADA_1, FACT_DECADA_2, FACT_DECADA_3, PLAN_DECADA_1, 
 PLAN_DECADA_2, PLAN_DECADA_3)
AS 
SELECT
   TIP_ROW,
   GROUP_ORDER,
   GROUP_NAME,
   PROD_ORDER,
   PROD_ID_NPR,
   LTRIM(TO_CHAR(TO_NUMBER(PLANSTRU_ORDER),'000000000000000000')) AS PLANSTRU_ORDER,
   PLANSTRU_ID,
   KLS_PLANSTRU.LEVEL_POS,
   KLS_PLANSTRU.NAME,
   KLS_PLANSTRU.KOD_SGR,
   KLS_PLANSTRU.KOD_SPG,
   KLS_PLANSTRU.KOD_RZD,
   KLS_PLANSTRU.KOD_PRZ,
   KLS_PLANSTRU.KOD_GRP,
   KLS_PLANSTRU.KOD_PGR,
   MAX(V_PLAN_FACT.DATE_PLAN) AS DATE_PLAN,
   SUM(V_PLAN_FACT.PLAN_MON) AS PLAN_MON,
   SUM(V_PLAN_FACT.PLAN_NAR) AS PLAN_NAR,
   SUM(V_PLAN_FACT.OBR_MON) AS OBR_MON,
   SUM(V_PLAN_FACT.OBR_NAR) AS OBR_NAR,
   SUM(V_PLAN_FACT.KORR_MON) AS KORR_MON,
   SUM(V_PLAN_FACT.KORR_NAR) AS KORR_NAR,
   MAX(V_PLAN_FACT.DATE_ZAYV) AS DATE_ZAYV,
   SUM(V_PLAN_FACT.ZAYV) AS ZAYV,
   MAX(V_PLAN_FACT.DATE_FACT) AS DATE_FACT,
   MAX(V_PLAN_FACT.TIME_FACT) AS TIME_FACT,
   SUM(V_PLAN_FACT.FACT_SUT) AS FACT_SUT,
   SUM(V_PLAN_FACT.FACT) AS FACT,
   SUM(V_PLAN_FACT.PLAN_NAR_RASP) AS PLAN_NAR_RASP,
   SUM(V_PLAN_FACT.OBR_NAR_RASP) AS OBR_NAR_RASP,
   SUM(V_PLAN_FACT.KORR_NAR_RASP) AS KORR_NAR_RASP,
   SUM(V_PLAN_FACT.FACT_DECADA_1) AS FACT_DECADA_1,
   SUM(V_PLAN_FACT.FACT_DECADA_2) AS FACT_DECADA_2,
   SUM(V_PLAN_FACT.FACT_DECADA_3) AS FACT_DECADA_3,
   SUM(V_PLAN_FACT.PLAN_DECADA_1) AS PLAN_DECADA_1,
   SUM(V_PLAN_FACT.PLAN_DECADA_2) AS PLAN_DECADA_2,
   SUM(V_PLAN_FACT.PLAN_DECADA_3) AS PLAN_DECADA_3
FROM KLS_PLANSTRU, V_PLAN_FACT
WHERE V_PLAN_FACT.PLANSTRU_ID=KLS_PLANSTRU.ID
  AND KLS_PLANSTRU.LEVEL_POS>=6
GROUP BY
   V_PLAN_FACT.TIP_ROW,
   V_PLAN_FACT.GROUP_ORDER,
   V_PLAN_FACT.GROUP_NAME,
   V_PLAN_FACT.PROD_ORDER,
   V_PLAN_FACT.PROD_ID_NPR,
   V_PLAN_FACT.PLANSTRU_ORDER,
   V_PLAN_FACT.PLANSTRU_ID,
   KLS_PLANSTRU.LEVEL_POS,
   KLS_PLANSTRU.NAME,
   KLS_PLANSTRU.KOD_SGR,
   KLS_PLANSTRU.KOD_SPG,
   KLS_PLANSTRU.KOD_RZD,
   KLS_PLANSTRU.KOD_PRZ,
   KLS_PLANSTRU.KOD_GRP,
   KLS_PLANSTRU.KOD_PGR;


