--
-- V_PLAN_POST_REALIZ_ROWS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_POST_REALIZ_ROWS
(DATE_PLAN, SUPPLIER_ID, PROD_ID_NPR, SHORT_NAME, NAME_NPR)
AS 
SELECT /*+ RULE*/ c.DATE_PLAN,c.SUPPLIER_ID, c.PROD_ID_NPR,pr.SHORT_NAME,prod.NAME_NPR
FROM (SELECT DISTINCT "SUPPLIER_ID","PROD_ID_NPR","DATE_PLAN" FROM (
SELECT supplier_id,prod_id_npr,date_plan FROM PLAN_POST_SVOD
UNION 
SELECT supplier_id,prod_id_npr,date_plan FROM PLAN_REALIZ)) c,KLS_PREDPR pr,KLS_PROD prod
WHERE c.SUPPLIER_ID=pr.ID
AND c.PROD_ID_NPR=prod.ID_NPR;


