--
-- V_PLAN_FACT_UNI  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_FACT_UNI
(TIP_ROW, GROUP_ORDER, GROUP_NAME, PROD_ORDER, PROD_ID_NPR, 
 PLANSTRU_ORDER, PLANSTRU_ID, LEVEL_POS, PLANSTRU_NAME, KOD_SGR, 
 KOD_SPG, KOD_RZD, KOD_PRZ, KOD_GRP, KOD_PGR, 
 DATE_PLAN, PLAN_MON, PLAN_NAR, OBR_MON, OBR_NAR, 
 KORR_MON, KORR_NAR, DATE_ZAYV, ZAYV, DATE_FACT, 
 TIME_FACT, FACT_SUT, FACT, PLAN_NAR_RASP, OBR_NAR_RASP, 
 KORR_NAR_RASP, FACT_DECADA_1, FACT_DECADA_2, FACT_DECADA_3, PLAN_DECADA_1, 
 PLAN_DECADA_2, PLAN_DECADA_3)
AS 
SELECT "TIP_ROW","GROUP_ORDER","GROUP_NAME","PROD_ORDER","PROD_ID_NPR","PLANSTRU_ORDER","PLANSTRU_ID","LEVEL_POS",
"PLANSTRU_NAME","KOD_SGR","KOD_SPG","KOD_RZD","KOD_PRZ","KOD_GRP","KOD_PGR","DATE_PLAN","PLAN_MON","PLAN_NAR",
"OBR_MON","OBR_NAR","KORR_MON","KORR_NAR","DATE_ZAYV","ZAYV","DATE_FACT","TIME_FACT","FACT_SUT","FACT", "PLAN_NAR_RASP",
"OBR_NAR_RASP","KORR_NAR_RASP",
   FACT_DECADA_1,FACT_DECADA_2,FACT_DECADA_3, PLAN_DECADA_1, PLAN_DECADA_2, PLAN_DECADA_3 FROM (
SELECT * FROM V_PLAN_FACT_1
UNION ALL
SELECT * FROM V_PLAN_FACT_2
UNION ALL
SELECT * FROM V_PLAN_FACT_3
UNION ALL
SELECT * FROM V_PLAN_FACT_4
UNION ALL
SELECT * FROM V_PLAN_FACT_5
UNION ALL
SELECT * FROM V_PLAN_FACT_6
)
ORDER BY GROUP_ORDER, PROD_ORDER, PLANSTRU_ORDER;


