--
-- V_PLAN_FACT_DEC_READY  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_FACT_DEC_READY
(GROUP_ORDER, GROUP_VISIBLE, PROD_ORDER, NAZN_OTG_ID, PROD_NAME, 
 DATE_PLAN, DATE_FACT, TIME_FACT, PLAN_ALL, PLAN_FIRST, 
 NUM_DECADA, DAYS_DECADA, PLAN_DECADA, FACT_SUT, PLAN_NAR, 
 PLAN_NAR_RASP, FACT_DECADA_1, FACT_DECADA_2, FACT_DECADA_3, FACT_NAR)
AS 
SELECT "GROUP_ORDER","GROUP_VISIBLE","PROD_ORDER","NAZN_OTG_ID","PROD_NAME","DATE_PLAN","DATE_FACT","TIME_FACT","PLAN_ALL","PLAN_FIRST","NUM_DECADA","DAYS_DECADA","PLAN_DECADA","FACT_SUT","PLAN_NAR","PLAN_NAR_RASP","FACT_DECADA_1","FACT_DECADA_2","FACT_DECADA_3","FACT_NAR" FROM
(
-- ВСЕГО
SELECT
  0 as GROUP_ORDER,
  1 as GROUP_VISIBLE,
  0 as PROD_ORDER,
  1 as NAZN_OTG_ID,
  'ВСЕГО' as PROD_NAME,
  MAX(DATE_PLAN) as DATE_PLAN,
  MAX(DATE_FACT) as DATE_FACT,
  MAX(TIME_FACT) as TIME_FACT,
  SUM(PLAN_MON+OBR_MON) as PLAN_ALL,
  SUM(PLAN_MON) as PLAN_FIRST,
  MAX(NUM_DECADA) as NUM_DECADA,
  MAX(CASE
        WHEN NUM_DECADA=1 THEN 10
        WHEN NUM_DECADA=2 THEN 10
		ELSE TO_NUMBER(TO_CHAR(LAST_DAY(DATE_PLAN)-20,'DD'))
	  END) as DAYS_DECADA,
  SUM(CASE
     WHEN NUM_DECADA=1 THEN PLAN_DECADA_1
     WHEN NUM_DECADA=2 THEN PLAN_DECADA_2
     ELSE PLAN_DECADA_3
   END) as PLAN_DECADA,
  SUM(FACT_SUT) as FACT_SUT,
  SUM(PLAN_NAR+OBR_NAR) as PLAN_NAR,
  SUM(PLAN_NAR_RASP+OBR_NAR_RASP) as PLAN_NAR_RASP,
  SUM(FACT_DECADA_1) as FACT_DECADA_1,
  SUM(FACT_DECADA_2) as FACT_DECADA_2,
  SUM(FACT_DECADA_3) as FACT_DECADA_3,
  SUM(FACT) as FACT_NAR
FROM V_PLAN_FACT_DEC
UNION ALL
-- Группы
SELECT
  GROUP_ORDER,
  GROUP_VISIBLE,
  0 as PROD_ORDER,
  1 as NAZN_OTG_ID,
  GROUP_NAME as PROD_NAME,
  MAX(DATE_PLAN) as DATE_PLAN,
  MAX(DATE_FACT) as DATE_FACT,
  MAX(TIME_FACT) as TIME_FACT,
  SUM(PLAN_MON+OBR_MON) as PLAN_ALL,
  SUM(PLAN_MON) as PLAN_FIRST,
  MAX(NUM_DECADA) as NUM_DECADA,
  MAX(CASE
        WHEN NUM_DECADA=1 THEN 10
        WHEN NUM_DECADA=2 THEN 10
		ELSE TO_NUMBER(TO_CHAR(LAST_DAY(DATE_PLAN)-20,'DD'))
	  END) as DAYS_DECADA,
  SUM(CASE
     WHEN NUM_DECADA=1 THEN PLAN_DECADA_1
     WHEN NUM_DECADA=2 THEN PLAN_DECADA_2
     ELSE PLAN_DECADA_3
   END) as PLAN_DECADA,
  SUM(FACT_SUT) as FACT_SUT,
  SUM(PLAN_NAR+OBR_NAR) as PLAN_NAR,
  SUM(PLAN_NAR_RASP+OBR_NAR_RASP) as PLAN_NAR_RASP,
  SUM(FACT_DECADA_1) as FACT_DECADA_1,
  SUM(FACT_DECADA_2) as FACT_DECADA_2,
  SUM(FACT_DECADA_3) as FACT_DECADA_3,
  SUM(FACT) as FACT_NAR
FROM V_PLAN_FACT_DEC
GROUP BY
  GROUP_ORDER,
  GROUP_VISIBLE,
  GROUP_NAME
UNION ALL
-- Продукты
SELECT
  GROUP_ORDER,
  1 as GROUP_VISIBLE,
  PROD_ORDER,
  1 as NAZN_OTG_ID,
  NAME_NPR as PROD_NAME,
  MAX(DATE_PLAN) as DATE_PLAN,
  MAX(DATE_FACT) as DATE_FACT,
  MAX(TIME_FACT) as TIME_FACT,
  SUM(PLAN_MON+OBR_MON) as PLAN_ALL,
  SUM(PLAN_MON) as PLAN_FIRST,
  MAX(NUM_DECADA) as NUM_DECADA,
  MAX(CASE
        WHEN NUM_DECADA=1 THEN 10
        WHEN NUM_DECADA=2 THEN 10
		ELSE TO_NUMBER(TO_CHAR(LAST_DAY(DATE_PLAN)-20,'DD'))
	  END) as DAYS_DECADA,
  SUM(CASE
     WHEN NUM_DECADA=1 THEN PLAN_DECADA_1
     WHEN NUM_DECADA=2 THEN PLAN_DECADA_2
     ELSE PLAN_DECADA_3
   END) as PLAN_DECADA,
  SUM(FACT_SUT) as FACT_SUT,
  SUM(PLAN_NAR+OBR_NAR) as PLAN_NAR,
  SUM(PLAN_NAR_RASP+OBR_NAR_RASP) as PLAN_NAR_RASP,
  SUM(FACT_DECADA_1) as FACT_DECADA_1,
  SUM(FACT_DECADA_2) as FACT_DECADA_2,
  SUM(FACT_DECADA_3) as FACT_DECADA_3,
  SUM(FACT) as FACT_NAR
FROM V_PLAN_FACT_DEC
GROUP BY
  GROUP_ORDER,
  PROD_ORDER,
  NAME_NPR
UNION ALL
-- в т.ч.с хранения
SELECT
  GROUP_ORDER,
  1 as GROUP_VISIBLE,
  PROD_ORDER,
  NAZN_OTG_ID,
  'в т.ч. с хранения' as PROD_NAME,
  MAX(DATE_PLAN) as DATE_PLAN,
  MAX(DATE_FACT) as DATE_FACT,
  MAX(TIME_FACT) as TIME_FACT,
  SUM(PLAN_MON+OBR_MON) as PLAN_ALL,
  SUM(PLAN_MON) as PLAN_FIRST,
  MAX(NUM_DECADA) as NUM_DECADA,
  MAX(CASE
        WHEN NUM_DECADA=1 THEN 10
        WHEN NUM_DECADA=2 THEN 10
		ELSE TO_NUMBER(TO_CHAR(LAST_DAY(DATE_PLAN)-20,'DD'))
	  END) as DAYS_DECADA,
  SUM(CASE
     WHEN NUM_DECADA=1 THEN PLAN_DECADA_1
     WHEN NUM_DECADA=2 THEN PLAN_DECADA_2
     ELSE PLAN_DECADA_3
   END) as PLAN_DECADA,
  SUM(FACT_SUT) as FACT_SUT,
  SUM(PLAN_NAR+OBR_NAR) as PLAN_NAR,
  SUM(PLAN_NAR_RASP+OBR_NAR_RASP) as PLAN_NAR_RASP,
  SUM(FACT_DECADA_1) as FACT_DECADA_1,
  SUM(FACT_DECADA_2) as FACT_DECADA_2,
  SUM(FACT_DECADA_3) as FACT_DECADA_3,
  SUM(FACT) as FACT_NAR
FROM V_PLAN_FACT_DEC
WHERE NAZN_OTG_ID=9
GROUP BY
  GROUP_ORDER,
  PROD_ORDER,
  NAZN_OTG_ID,
  NAME_NPR
)
WHERE PLAN_ALL<>0 OR PLAN_FIRST<>0 OR PLAN_DECADA<>0 OR FACT_NAR<>0
ORDER BY GROUP_ORDER,PROD_ORDER,NAZN_OTG_ID,PROD_NAME;


