--
-- V_PLAN_FACT  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_FACT
(ID, TIP_ROW, GROUP_ORDER, GROUP_NAME, PROD_ORDER, 
 PROD_ID_NPR, PLANSTRU_ORDER, PLANSTRU_ID, DATE_PLAN, PLAN_MON, 
 PLAN_NAR, OBR_MON, OBR_NAR, KORR_MON, KORR_NAR, 
 DATE_ZAYV, ZAYV, DATE_FACT, TIME_FACT, FACT, 
 PLAN_NAR_RASP, OBR_NAR_RASP, KORR_NAR_RASP, FACT_SUT, PLAN_NAR_RASP_7, 
 OBR_NAR_RASP_7, FACT_NAR_7, FACT_DECADA_1, FACT_DECADA_2, FACT_DECADA_3, 
 PLAN_DECADA_1, PLAN_DECADA_2, PLAN_DECADA_3, NUM_DECADA)
AS 
SELECT "ID","TIP_ROW","GROUP_ORDER","GROUP_NAME","PROD_ORDER","PROD_ID_NPR","PLANSTRU_ORDER","PLANSTRU_ID", 
"DATE_PLAN","PLAN_MON_V","PLAN_NAR_V","OBR_MON_V","OBR_NAR_V","KORR_MON_V","KORR_NAR_V","DATE_ZAYV","ZAYV","DATE_FACT","TIME_FACT","FACT_V", 
"PLAN_NAR_RASP","OBR_NAR_RASP","KORR_NAR_RASP","FACT_SUT_V", PLAN_NAR_RASP_7, OBR_NAR_RASP_7, FACT_NAR_7,FACT_DECADA_1,FACT_DECADA_2,FACT_DECADA_3 
, PLAN_DECADA_1, PLAN_DECADA_2, PLAN_DECADA_3,NUM_DECADA FROM PLAN_FACT 
WHERE TIP_ROW IN ('онярюбйю','оняр_юбрн') 
  AND TERMINAL_NAME = For_Init.GetCurrTerm 
  AND OSUSER_NAME = For_Init.GetCurrUser;


