--
-- V_PLAN_POST_UNI  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_POST_UNI
(PLAN_ID, PLAN_PER_ID, PROD_ID_NPR, PLANSTRU_ID, LEVEL_POS, 
 NAME, KOD_SGR, KOD_SPG, KOD_RZD, KOD_PRZ, 
 KOD_GRP, KOD_PGR, PARENT_ID, DOG_ID, PAYFORM_ID, 
 PLAN_VES, PLAN_SUM)
AS 
SELECT "PLAN_ID","PLAN_PER_ID","PROD_ID_NPR","PLANSTRU_ID","LEVEL_POS","NAME","KOD_SGR","KOD_SPG","KOD_RZD","KOD_PRZ","KOD_GRP","KOD_PGR","PARENT_ID","DOG_ID","PAYFORM_ID","PLAN_VES","PLAN_SUM" FROM (
SELECT * FROM v_plan_post_1
UNION ALL
SELECT * FROM v_plan_post_2
UNION ALL
SELECT * FROM v_plan_post_3
UNION ALL
SELECT * FROM v_plan_post_4
UNION ALL
SELECT * FROM v_plan_post_5
UNION ALL
SELECT * FROM v_plan_post_6
)
ORDER BY PLAN_ID,PLAN_PER_ID,PROD_ID_NPR,LEVEL_POS,KOD_SGR,KOD_SPG,KOD_RZD,KOD_PRZ,KOD_GRP,KOD_PGR,DOG_ID,PAYFORM_ID;


