--
-- V_PLAN_FACT_REALIZ_GRP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_FACT_REALIZ_GRP
(DATE_BEGIN, DATE_END, DATE_PLAN, FILIAL_ID, FILIAL_NAME, 
 REGION_ORDER, REGION_NAME, NAPR_ORDER, NAPR_NAME, GROUP_ORDER, 
 GROUP_NAME, BEGIN_OST, PLAN_POST_VES, NORMA_POST_VES, FACT_POST_VES, 
 RESURS, PLAN_REAL_VES, NORMA_REAL_VES, FACT_REAL_VES, END_OST)
AS 
SELECT
  DATE_BEGIN,
  DATE_END,
  DATE_PLAN,
  FILIAL_ID,
  FILIAL_NAME,
  REGION_ORDER,
  REGION_NAME,
  NAPR_ORDER,
  NAPR_NAME,
  GROUP_ORDER,
  GROUP_NAME,
  SUM(DECODE(SIGN(BEGIN_OST),-1,0,BEGIN_OST)) AS BEGIN_OST,
  SUM(PLAN_POST_VES) AS PLAN_POST_VES,
  SUM(NORMA_POST_VES) AS NORMA_POST_VES,
  SUM(FACT_POST_VES) AS FACT_POST_VES,
  SUM(RESURS) AS RESURS,
  SUM(PLAN_REAL_VES) AS PLAN_REAL_VES,
  SUM(NORMA_REAL_VES) AS NORMA_REAL_VES,
  SUM(FACT_REAL_VES) AS FACT_REAL_VES,
  SUM(DECODE(SIGN(END_OST),-1,0,END_OST)) AS END_OST
FROM V_PLAN_FACT_REALIZ
WHERE GROUP_ORDER IS NOT NULL
GROUP BY
  DATE_BEGIN,
  DATE_END,
  DATE_PLAN,
  FILIAL_ID,
  FILIAL_NAME,
  REGION_ORDER,
  REGION_NAME,
  NAPR_ORDER,
  NAPR_NAME,
  GROUP_ORDER,
  GROUP_NAME
ORDER BY
  REGION_ORDER, NAPR_ORDER, GROUP_ORDER;


