--
-- V_PLAN_FACT_GD_GRP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_FACT_GD_GRP
(TIP_ROW, GROUP_ORDER, GROUP_NAME, PROD_ORDER, PROD_ID_NPR, 
 PLANSTRU_ORDER, PLANSTRU_ID, PLANSTRU_NAME, DATE_PLAN, PLAN_MON_C, 
 PLAN_MON_V, PLAN_MON_SOBS_C, PLAN_MON_SOBS_V, PLAN_NAR_C, PLAN_NAR_V, 
 PLAN_NAR_SOBS_C, PLAN_NAR_SOBS_V, DATE_FACT, TIME_FACT, FACT_C, 
 FACT_V, FACT_SOBS_C, FACT_SOBS_V)
AS 
SELECT
  TIP_ROW,
  GROUP_ORDER,
  GROUP_NAME,
  PROD_ORDER,
  PROD_ID_NPR,
  PLANSTRU_ORDER,
  PLANSTRU_ID,
  KLS_NAPR_MOS.NAME AS PLANSTRU_NAME,
  MAX(DATE_PLAN) AS DATE_PLAN,
  SUM(PLAN_MON_C) AS PLAN_MON_C,
  SUM(PLAN_MON_V) AS PLAN_MON_V,
  SUM(PLAN_MON_SOBS_C) AS PLAN_MON_SOBS_C,
  SUM(PLAN_MON_SOBS_V) AS PLAN_MON_SOBS_V,
  SUM(PLAN_NAR_C) AS PLAN_NAR_C,
  SUM(PLAN_NAR_V) AS PLAN_NAR_V,
  SUM(PLAN_NAR_SOBS_C) AS PLAN_NAR_SOBS_C,
  SUM(PLAN_NAR_SOBS_V) AS PLAN_NAR_SOBS_V,
  MAX(DATE_FACT) AS DATE_FACT,
  MAX(TIME_FACT) AS TIME_FACT,
  SUM(FACT_C) AS FACT_C,
  SUM(FACT_V) AS FACT_V,
  SUM(FACT_SOBS_C) AS FACT_SOBS_C,
  SUM(FACT_SOBS_V) AS FACT_SOBS_V
FROM V_PLAN_FACT_GD,KLS_NAPR_MOS
WHERE V_PLAN_FACT_GD.PLANSTRU_ID=KLS_NAPR_MOS.ID
GROUP BY
  TIP_ROW,
  GROUP_ORDER,
  GROUP_NAME,
  PROD_ORDER,
  PROD_ID_NPR,
  PLANSTRU_ORDER,
  PLANSTRU_ID,
  KLS_NAPR_MOS.NAME
ORDER BY
  GROUP_ORDER,
  PROD_ORDER,
  PLANSTRU_ORDER;


