--
-- V_PLAN_FACT_GRP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_FACT_GRP
(TIP_ROW, GROUP_ORDER, GROUP_NAME, PROD_ORDER, PROD_ID_NPR, 
 PLANSTRU_ORDER, PLANSTRU_ID, LEVEL_POS, PLANSTRU_NAME, KOD_SGR, 
 KOD_SPG, KOD_RZD, KOD_PRZ, KOD_GRP, KOD_PGR, 
 DATE_PLAN, PLAN_MON, PLAN_NAR, OBR_MON, OBR_NAR, 
 KORR_MON, KORR_NAR, DATE_ZAYV, ZAYV, DATE_FACT, 
 TIME_FACT, FACT_SUT, FACT, PLAN_NAR_RASP, OBR_NAR_RASP, 
 KORR_NAR_RASP, FACT_DECADA_1, FACT_DECADA_2, FACT_DECADA_3, PLAN_DECADA_1, 
 PLAN_DECADA_2, PLAN_DECADA_3)
AS 
SELECT
  TIP_ROW,
  GROUP_ORDER,
  GROUP_NAME,
  PROD_ORDER,
  PROD_ID_NPR,
  PLANSTRU_ORDER,
  PLANSTRU_ID,
  LEVEL_POS,
  PLANSTRU_NAME,
  KOD_SGR,
  KOD_SPG,
  KOD_RZD,
  KOD_PRZ,
  KOD_GRP,
  KOD_PGR,
  MAX(DATE_PLAN) AS DATE_PLAN,
  NVL(SUM(PLAN_MON),0) AS PLAN_MON,
  NVL(SUM(PLAN_NAR),0) AS PLAN_NAR,
  NVL(SUM(OBR_MON),0) AS OBR_MON,
  NVL(SUM(OBR_NAR),0) AS OBR_NAR,
  NVL(SUM(KORR_MON),0) AS KORR_MON,
  NVL(SUM(KORR_NAR),0) AS KORR_NAR,
  MAX(DATE_ZAYV) AS DATE_ZAYV,
  NVL(SUM(ZAYV),0) AS ZAYV,
  MAX(DATE_FACT) AS DATE_FACT,
  MAX(TIME_FACT) AS TIME_FACT,
  NVL(SUM(FACT_SUT),0) AS FACT_SUT,
  NVL(SUM(FACT),0) AS FACT,
  NVL(SUM(PLAN_NAR_RASP),0) AS PLAN_NAR_RASP,
  NVL(SUM(OBR_NAR_RASP),0) AS OBR_NAR_RASP,
  NVL(SUM(KORR_NAR_RASP),0) AS KORR_NAR_RASP,
  NVL(SUM(FACT_DECADA_1),0) AS FACT_DECADA_1,
  NVL(SUM(FACT_DECADA_2),0) AS FACT_DECADA_2,
  NVL(SUM(FACT_DECADA_3),0) AS FACT_DECADA_3,
  NVL(SUM(PLAN_DECADA_1),0) AS PLAN_DECADA_1,
  NVL(SUM(PLAN_DECADA_2),0) AS PLAN_DECADA_2,
  NVL(SUM(PLAN_DECADA_3),0) AS PLAN_DECADA_3
FROM V_PLAN_FACT_UNI
GROUP BY
  TIP_ROW,
  GROUP_ORDER,
  GROUP_NAME,
  PROD_ORDER,
  PROD_ID_NPR,
  PLANSTRU_ORDER,
  PLANSTRU_ID,
  LEVEL_POS,
  PLANSTRU_NAME,
  KOD_SGR,
  KOD_SPG,
  KOD_RZD,
  KOD_PRZ,
  KOD_GRP,
  KOD_PGR
ORDER BY
  GROUP_ORDER,
  PROD_ORDER,
  PLANSTRU_ORDER;


