--
-- V_PLAN_POST_VIEW_1  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_POST_VIEW_1
(ID, PLAN_ID, PLAN_PER_ID, PROD_ID_NPR, NAME_NPR, 
 PLANSTRU_ID, PLANSTRU_ORDER, LEVEL_POS, PLANSTRU_NAME, DOG_ID, 
 DOG_NUMBER, PLAT_ID, PLAT_NAME, REFINERY_ID, REFINERY_NAME, 
 ORGSTRU_ID, ORGSTRU_NAME, PAYFORM_ID, PAYFORM_NAME, CAT_CEN_ID, 
 DATE_CENA, PLAN_CENA, PLAN_VES, PLAN_SUM)
AS 
SELECT
  A.ID,
  A.PLAN_ID,
  A.PLAN_PER_ID,
  A.PROD_ID_NPR,
  KLS_PROD.NAME_NPR,
  A.PLANSTRU_ID,
  TO_CHAR(KLS_PLANSTRU.KOD_SGR*1000000000000000+KLS_PLANSTRU.KOD_SPG*1000000000000+KLS_PLANSTRU.KOD_RZD*1000000000+KLS_PLANSTRU.KOD_PRZ*1000000+KLS_PLANSTRU.KOD_GRP*1000+KLS_PLANSTRU.KOD_PGR) AS PLANSTRU_ORDER,
  KLS_PLANSTRU.LEVEL_POS,
  KLS_PLANSTRU.NAME AS PLANSTRU_NAME,
  A.DOG_ID,
  KLS_DOG.DOG_NUMBER,
  KLS_DOG.PREDPR_ID  AS plat_id,
  KLS_PREDPR.SHORT_NAME AS plat_name,
  refinery.ID AS refinery_id,
  refinery.PREDPR_NAME as refinery_name,
  v_org_structure.ID AS orgstru_id,
  v_org_structure.NAME || ' - (' || v_org_structure.FILIAL_NAME || ')' as orgstru_name,
  kls_payform.ID AS payform_id,
  kls_payform.payform_NAME as payform_name,
  A.CAT_CEN_ID AS CAT_CEN_ID,
  A.DATE_CENA AS DATE_CENA,
  A.PLAN_CENA AS PLAN_CENA,
  A.PLAN_VES AS PLAN_VES,
  A.PLAN_SUM AS PLAN_SUM
FROM PLAN_POST A, KLS_PROD, KLS_DOG, KLS_PREDPR, KLS_PLANSTRU, kls_predpr refinery, v_org_structure, KLS_PAYFORM
WHERE A.PROD_ID_NPR = KLS_PROD.ID_NPR
  AND A.DOG_ID = KLS_DOG.ID
  AND KLS_DOG.PREDPR_ID = KLS_PREDPR.ID
  AND A.PLANSTRU_ID = KLS_PLANSTRU.ID
  AND a.REFINERY_ID=refinery.id(+)
  AND a.ORGSTRU_ID=v_org_structure.id(+)
  AND a.PAYFORM_ID=KLS_PAYFORM.ID(+)
/*GROUP BY PLAN_ID,
  A.PLAN_ID,
  A.PLAN_PER_ID,
  A.PROD_ID_NPR,
  KLS_PROD.NAME_NPR,
  TO_CHAR(KLS_PLANSTRU.KOD_SGR*1000000000000000+KLS_PLANSTRU.KOD_SPG*1000000000000+KLS_PLANSTRU.KOD_RZD*1000000000+KLS_PLANSTRU.KOD_PRZ*1000000+KLS_PLANSTRU.KOD_GRP*1000+KLS_PLANSTRU.KOD_PGR),
  A.PLANSTRU_ID,
  KLS_PLANSTRU.LEVEL_POS,
  KLS_PLANSTRU.NAME,
  A.DOG_ID,
  KLS_DOG.DOG_NUMBER,
  KLS_DOG.PREDPR_ID,
  KLS_PREDPR.SHORT_NAME,
  refinery.ID,
  refinery.PREDPR_NAME,
  org_structure.ID,
  org_structure.NAME*/
;


