--
-- V_PLAN_FACT_DEC  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_FACT_DEC
(GROUP_ORDER, GROUP_NAME, GROUP_VISIBLE, POD_GROUP_ORDER, POD_GROUP_NAME, 
 POD_GROUP_VISIBLE, PROD_ORDER, NAZN_OTG_ID, PROD_ID_NPR, NAME_NPR, 
 DATE_PLAN, PLAN_MON, PLAN_NAR, PLAN_NAR_RASP, OBR_MON, 
 OBR_NAR, OBR_NAR_RASP, DATE_FACT, TIME_FACT, NUM_DECADA, 
 FACT, FACT_SUT, FACT_DECADA_1, FACT_DECADA_2, FACT_DECADA_3, 
 PLAN_DECADA_1, PLAN_DECADA_2, PLAN_DECADA_3)
AS 
SELECT
  NVL(GR.GROUP_ORDER,99000000) AS GROUP_ORDER,
  NVL(GR.GROUP_NAME,'') AS GROUP_NAME,
  NVL(GR.GROUP_VISIBLE,0) AS GROUP_VISIBLE,
  NVL(POD_GR.GROUP_ORDER,99900000) AS POD_GROUP_ORDER,
  NVL(POD_GR.GROUP_NAME,'') AS POD_GROUP_NAME,
  NVL(POD_GR.GROUP_VISIBLE,0) AS POD_GROUP_VISIBLE,
  DECODE(PR.PROD_ID_NPR,NULL,A.PROD_ORDER,PR.GROUP_ORDER) AS PROD_ORDER,
  DECODE(KLS_PLANSTRU.NAZN_OTG_ID,9,9,1) as NAZN_OTG_ID,
  DECODE(PR.PROD_ID_NPR,NULL,A.PROD_ID_NPR,TO_CHAR(PR.GROUP_ORDER)) AS PROD_ID_NPR,
  DECODE(PR.PROD_ID_NPR,NULL,KLS_PROD.NAME_NPR,PR.GROUP_NAME),
  MAX(A.DATE_PLAN) as DATE_PLAN,
  SUM(NVL(A.PLAN_MON_V,0)) as PLAN_MON,
  SUM(NVL(A.PLAN_NAR_V,0)) as PLAN_NAR,
  SUM(NVL(A.PLAN_NAR_RASP,0)) as PLAN_NAR_RASP,
  SUM(NVL(A.OBR_MON_V,0)) as OBR_MON,
  SUM(NVL(A.OBR_NAR_V,0)) as OBR_NAR,
  SUM(NVL(A.OBR_NAR_RASP,0)) as OBR_NAR_RASP,
  MAX(A.DATE_FACT) as DATE_FACT,
  MAX(A.TIME_FACT) as TIME_FACT,
  MAX(A.NUM_DECADA) as NUM_DECADA,
  SUM(NVL(A.FACT_V,0)) as FACT,
  SUM(NVL(A.FACT_SUT_V,0)) as FACT_SUT,
  SUM(NVL(A.FACT_DECADA_1,0)) AS FACT_DECADA_1,
  SUM(NVL(A.FACT_DECADA_2,0)) AS FACT_DECADA_2,
  SUM(NVL(A.FACT_DECADA_3,0)) AS FACT_DECADA_3,
  SUM(NVL(A.PLAN_DECADA_1,0)) AS PLAN_DECADA_1,
  SUM(NVL(A.PLAN_DECADA_2,0)) AS PLAN_DECADA_2,
  SUM(NVL(A.PLAN_DECADA_3,0)) AS PLAN_DECADA_3
FROM PLAN_FACT A, KLS_PROD, KLS_PLANSTRU,
  (SELECT AA.PROD_ID_NPR,BB.GROUP_ORDER,BB.GROUP_NAME,BB.GROUP_VISIBLE FROM KLS_PROD_GROUPS_DESC AA, KLS_PROD_GROUPS BB WHERE AA.PROD_GROUPS_ID=BB.ID AND BB.PROD_TYPE_GRP_ID=1) GR,
  (SELECT AA.PROD_ID_NPR,BB.GROUP_ORDER,BB.GROUP_NAME,BB.GROUP_VISIBLE FROM KLS_PROD_GROUPS_DESC AA, KLS_PROD_GROUPS BB WHERE AA.PROD_GROUPS_ID=BB.ID AND BB.PROD_TYPE_GRP_ID=7) POD_GR,
  (SELECT AA.PROD_ID_NPR,BB.GROUP_ORDER,BB.GROUP_NAME,BB.GROUP_VISIBLE FROM KLS_PROD_GROUPS_DESC AA, KLS_PROD_GROUPS BB WHERE AA.PROD_GROUPS_ID=BB.ID AND BB.PROD_TYPE_GRP_ID=3) PR
WHERE A.TIP_ROW='ондейюдмн'
  AND A.TERMINAL_NAME = For_Init.GetCurrTerm
  AND A.OSUSER_NAME = For_Init.GetCurrUser
  AND A.PLANSTRU_ID=KLS_PLANSTRU.ID
  AND A.PROD_ID_NPR=KLS_PROD.ID_NPR
  AND KLS_PROD.ID_NPR=GR.PROD_ID_NPR(+)
  AND KLS_PROD.ID_NPR=POD_GR.PROD_ID_NPR(+)
  AND KLS_PROD.ID_NPR=PR.PROD_ID_NPR(+)
GROUP BY
  NVL(GR.GROUP_ORDER,99000000),
  NVL(GR.GROUP_NAME,''),
  NVL(GR.GROUP_VISIBLE,0),
  NVL(POD_GR.GROUP_ORDER,99900000),
  NVL(POD_GR.GROUP_NAME,''),
  NVL(POD_GR.GROUP_VISIBLE,0),
  DECODE(PR.PROD_ID_NPR,NULL,A.PROD_ORDER,PR.GROUP_ORDER),
  DECODE(KLS_PLANSTRU.NAZN_OTG_ID,9,9,1),
  DECODE(PR.PROD_ID_NPR,NULL,A.PROD_ID_NPR,TO_CHAR(PR.GROUP_ORDER)),
  DECODE(PR.PROD_ID_NPR,NULL,KLS_PROD.NAME_NPR,PR.GROUP_NAME);


