--
-- V_PLAN_REALIZ_FOR_PARUS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PLAN_REALIZ_FOR_PARUS
(DATE_PLAN, STORE_RN, NOMEN_RN, PLAN_VES_KG)
AS 
select
  A.DATE_PLAN,
  C.STORE_RN,
  B.PARUS_PRN as NOMEN_RN,
  SUM(A.VES*1000)
from
  plan_realiz A,
  V_KLS_PROD_NOMENKLATOR_GRP B,
  (select ORG_STRU_ID,STORE_RN from PARUS_STORE_ORG_STRU_LINK where is_main=1) C
where A.PROD_ID_NPR=B.PROD
  and A.SKLAD_ID=C.ORG_STRU_ID
  AND A.PARUS_RN IS NULL -- Планы реализации
GROUP BY
  A.DATE_PLAN,
  C.STORE_RN,
  B.PARUS_PRN;


