--
-- V_PODACHA_PRINT  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PODACHA_PRINT
(POD_NUM, POD_DATE, GOTOV_TIME, BEG_NALIV_TIME, END_NALIV_TIME, 
 VETKA_NAME, POD_POS, PROD_NAME, NUM_CIST, KALIBR_ID, 
 VES_CIST, CAPACITY, VAGOWNER_NAME, VZLIV, PLOMBA1, 
 PLOMBA2, VES, KOL_NET, SVED_NUM)
AS 
SELECT
  a.POD_NUM,
  a.POD_DATE,
  a.GOTOV_DATE as GOTOV_TIME,
  a.NALIV_DATE as BEG_NALIV_TIME,
  a.END_NALIV_DATE as END_NALIV_TIME,
  KLS_VETKA_OTP.VETKA_NAME as VETKA_NAME,
  b.NUM_POS as POD_POS,
  KLS_PROD.ABBR_NPR as PROD_NAME,
  b.NUM_CIST,
  b.KALIBR_ID,
  DECODE(NVL(b.VES_CIST,0),0,NULL,b.VES_CIST) as VES_CIST,
  b.CAPACITY,
  DECODE(NVL(KLS_VAGOWNER.ID,0),0,'',KLS_VAGOWNER.SHORT_NAME) as VAGOWNER_NAME,
  DECODE(NVL(b.VZLIV,0),0,NULL,b.VZLIV) as VZLIV,
  b.PLOMBA1,
  b.PLOMBA2,
  b.VES,
  b.KOL_NET,
  b.SVED_NUM
FROM PODACHA_ROWS b, PODACHA a, KLS_PROD, KLS_VAGOWNER, KLS_VETKA_OTP
WHERE b.PODACHA_ID=a.ID
  AND b.PROD_ID_NPR=KLS_PROD.ID_NPR(+)
  AND b.VAGOWNER_ID=KLS_VAGOWNER.ID(+)
  AND a.VETKA_OTP_ID=KLS_VETKA_OTP.ID
  AND a.ID=NVL(FOR_TEMP.GET_AS_NUM('PODACHA_ID','MASTER','MO_MNOS.XLS'),0)
ORDER BY b.NUM_POS,b.NUM_CIST;


