--
-- V_PROD_OK  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PROD_OK
(KOD, KOD_10)
AS 
SELECT MIN(A.ID_NPR) AS KOD, A.KOD_10 FROM master.kls_prod A 
WHERE A.ID_NPR<>'10320' AND A.ID_NPR<>'10313' AND A.KOD_10 IS NOT NULL
GROUP BY A.KOD_10;


