--
-- V_PVZ_OTGR_604  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_PVZ_OTGR_604
(AGNABBR, CODE, KSSS_AGN, MODIF_CODE, KSSS_PROD, 
 DOCDATE, STORE, POST, KSSS_POST, KSSS_MH, 
 VAL, VAL_S, ACCNUMB, ACCDATE, CAR_NUMBER, 
 NUM_DOC, RN_SP, DIRNUMB, KSSS_LUK, KSSS_NAD, 
 STORE_TYPE, CONTRACT, TTN)
AS 
select otgr.*, 
 --'1'  as contract,
-- '2' as TTN
trim(GET_CONTRACT_PARUS_VZ(NUM_DOC,'AUTO_CONT',DOCDATE)) as contract,
trim(GET_CONTRACT_PARUS_VZ(NUM_DOC,'AUTO_ACC',DOCDATE)) as TTN
  from  PVZ.V_PVZ_OTGR@oracle otgr;


