/* This object may not be sorted properly in the script due to cirular references. */
--
-- V_R3_YFRT  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_R3_YFRT
(VBELN, WAERS, KSCHL, MEINS, DOGOVOR, 
 EKKO_EBELN, ASNUM, ASNUM_NAME, KERNEL_ID, KERNEL_TAG, 
 CONTRACT_ATTR)
AS 
SELECT DISTINCT R3_OA.VBAK_VBELN,
	   R3_OA.KONV_WAERS,
	   R3_KONV.KSCHL,
	   R3_SC.ASMD_MEINS,
	   R3_SC.EKKO_ZZ021,
	   R3_CC.EKKO_EBELN,
	   R3_SC.ASNUM,
	   R3_SC.ASMDT_ASKTX,
	   R3_SC.KERNEL_ID,
	   R3_SC.KERNEL_TAG,
	   R3_VBAK.CONTRACTOR_ATTR
FROM R3_OA,R3_SC, R3_CC, R3_VBAK, R3_KONV
WHERE R3_OA.KONV_KSCHL = R3_KONV.KSCHL
  AND R3_KONV.MATCH_ASNUM=R3_SC.ASNUM
  AND R3_SC.KERNEL_TAG = 'OUT_WBILL_RW_OS$PLAT'
  AND R3_SC.EKKO_ZZ021=R3_CC.EKKO_ZZ021
  AND R3_OA.VBAK_VBELN=R3_VBAK.VBELN
  AND R3_VBAK.CONTRACTOR_ATTR=3;


