--
-- V_RASCH_VOZN  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_RASCH_VOZN
(BEG_DATE, END_DATE, MON_KVIT, PLAT_NAME, VES, 
 SOBS_NAME, SUMMA_TARIF_BN, SUMMA_TARIF_NDS, SUMMA_TARIF, USL_SUM, 
 SUMMA_VOZN_BN, TARIF_MPS, SUMMA_RAZN_BN, SUMMA_AGEN_BN, SUMMA_AGEN_NDS, 
 SUMMA_AGEN)
AS 
SELECT
  BEG_DATE,
  END_DATE,
  MON_KVIT,
  PLAT_NAME,
  SUM(VES) as VES,
  SOBS_NAME,
  SUM(SUMMA_TARIF_BN) as SUMMA_TARIF_BN,    
  SUM(SUMMA_TARIF_NDS) as SUMMA_TARIF_NDS,    
  SUM(SUMMA_TARIF) as SUMMA_TARIF,    
  MAX(USL_SUM) as USL_SUM,
  SUM(SUMMA_VOZN_BN) as SUMMA_VOZN_BN,
  SUM(CASE
        WHEN SUMMA_RAZN_BN<>0 THEN TARIF_MPS
       ELSE 0
  END) as TARIF_MPS, 
  SUM(SUMMA_RAZN_BN) as SUMMA_RAZN_BN,
  SUM(SUMMA_AGEN_BN) as SUMMA_AGEN_BN,
  SUM(SUMMA_AGEN_NDS) as SUMMA_AGEN_NDS,
  SUM(SUMMA_AGEN) as SUMMA_AGEN
FROM
(
SELECT
  BEG_DATE,
  END_DATE,
  (CASE 
    WHEN MON_KVIT=BEG_DATE THEN MON_KVIT
 ELSE TRUNC(BEG_DATE-1,'MONTH')
   END) as MON_KVIT,
  PLAT_NAME,
  NOM_DOK,
  KVIT_ID,
  MAX(VES) as VES,
  MAX(CASE
     WHEN VAGOWN_TYP_ID=2 THEN 'Ñîáñò.'
     WHEN VAGOWN_TYP_ID=1 THEN 'Àðåíä.'
     ELSE 'ÎÀÎ "ÐÆÄ"'
   END) as SOBS_NAME,
  SUM(SUMMA_TARIF-SUMMA_TARIF_NDS+SUMMA_OHRANA-SUMMA_OHRANA_NDS) as SUMMA_TARIF_BN,    
  SUM(SUMMA_TARIF_NDS+SUMMA_OHRANA_NDS) as SUMMA_TARIF_NDS,    
  SUM(SUMMA_TARIF+SUMMA_OHRANA) as SUMMA_TARIF,    
  MAX(DECODE(SUMMA_VOZN_11_BN,0,DECODE(SUMMA_VOZN_12_BN,0,0,DECODE(NVL(VES,0),0,0,ROUND(SUMMA_VOZN_BN/VES,0))),USL_SUM)) as USL_SUM,
  SUM(SUMMA_VOZN_BN) as SUMMA_VOZN_BN,
  SUM(CASE
        WHEN SUMMA_RAZN_BN<>0 THEN TARIF_MPS
       ELSE 0
  END) as TARIF_MPS, 
  SUM(SUMMA_RAZN_BN) as SUMMA_RAZN_BN,
  SUM(SUMMA_AGEN-SUMMA_AGEN_NDS) as SUMMA_AGEN_BN,
  SUM(SUMMA_AGEN_NDS) as SUMMA_AGEN_NDS,
  SUM(SUMMA_AGEN) as SUMMA_AGEN
FROM V_RASCH_VOZN_BEFORE
GROUP BY
 BEG_DATE,
 END_DATE,
 (CASE 
    WHEN MON_KVIT=BEG_DATE THEN MON_KVIT
 ELSE TRUNC(BEG_DATE-1,'MONTH')
   END),
 PLAT_NAME,
 NOM_DOK,
 KVIT_ID
)
GROUP BY
  BEG_DATE,
  END_DATE,
  MON_KVIT,
  PLAT_NAME,
  SOBS_NAME
HAVING SUM(SUMMA_TARIF)>0 OR  SUM(SUMMA_AGEN)>0  
ORDER BY MON_KVIT,SOBS_NAME,PLAT_NAME;


