--
-- V_REE_MONTH_GRAFIK  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_REE_MONTH_GRAFIK
(ORDER_NPR, KIND_NPR, PLAT_NAME, PLATSNP_NAME, FILIAL_NAME, 
 FILIAL_TRANSIT, KINDPROD_NAME, DOG_NUMBER, ABBR_NPR, INPUT_DATE, 
 NOM_ZD, TONN_DECLARED, TONN_LOADED, CIST_LOADED, POLU_NAME, 
 NAIM_REGION, STAN_NAME, GDOR_NAME, FLG_ALLOW_8_AXES, LOAD_ABBR, 
 NORMOTGR, CENA_OTP, PRIM, OST, PLANMOSCOWDOG, 
 PLANMOSCOWDOGWITHFOR, PLANOURDOG, PLANOURDOGWITHFOR, PLANMOSCOWPROD, PLANMOSCOWPRODOPT, 
 PLANOURPROD, PLANOURPRODOPT, FACTDOG, FACTDOGWITHFOR, FACTPROD, 
 ETRAN_NUM, ETRAN_DATE, ETRAN_SOGL, GU12_A_ID, STAN_ID, 
 PROD_ID_NPR, KOD_ISU, TONN_REE, PRIORITY, GU12_GRAFIK, 
 GU12_LOAD_ABBR)
AS 
select /*+ RULE */ a."ORDER_NPR",a."KIND_NPR",a."PLAT_NAME",a."PLATSNP_NAME",a."FILIAL_NAME",a."FILIAL_TRANSIT",a."KINDPROD_NAME",a."DOG_NUMBER",a."ABBR_NPR",a."INPUT_DATE",a."NOM_ZD",a."TONN_DECLARED",a."TONN_LOADED",a."CIST_LOADED",a."POLU_NAME",a."NAIM_REGION",a."STAN_NAME",a."GDOR_NAME",a."FLG_ALLOW_8_AXES",a."LOAD_ABBR",a."NORMOTGR",a."CENA_OTP",a."PRIM",a."OST",a."PLANMOSCOWDOG",a."PLANMOSCOWDOGWITHFOR",a."PLANOURDOG",a."PLANOURDOGWITHFOR",a."PLANMOSCOWPROD",a."PLANMOSCOWPRODOPT",a."PLANOURPROD",a."PLANOURPRODOPT",a."FACTDOG",a."FACTDOGWITHFOR",a."FACTPROD",a."ETRAN_NUM",a."ETRAN_DATE",a."ETRAN_SOGL",a."GU12_A_ID",a."STAN_ID",a."PROD_ID_NPR",a."KOD_ISU",a."TONN_REE",a."PRIORITY",a."GU12_GRAFIK",a."GU12_LOAD_ABBR"
from V_REE_MONTH_UHTA a, V_TEMP_REESTR_PARAMS b
where
  -- Ограничение по графику отгрузки
/*  exists (select null from zakaz_hist c, zakaz_grafik d
           where c.id=d.zakaz_hist_id
		     AND c.nom_zd=a.nom_zd
			 AND d.date_load BETWEEN b.GRAFIK_FROM AND b.GRAFIK_TO)*/
  exists (/* График */
           SELECT nom_zd, SUM(gu12_br.KOL_VAG) as KOL_VAG , SUM(gu12_br.VES) as VES
                 FROM month,gu12_a,gu12_b,gu12_br,V_TEMP_REESTR_PARAMS b
                WHERE month.GU12_A_ID=gu12_a.id
				  AND nom_zd=a.nom_zd
                  AND gu12_a.id=gu12_b.id_a
                  AND gu12_b.STAN_ID=month.STAN_ID
                  AND gu12_b.id=gu12_br.id_b
                  AND gu12_br.date_r<=b.GRAFIK_TO
				  AND month.nom_zd=a.nom_zd
				  AND gu12_b.ISCOR<>2
		  GROUP BY nom_zd HAVING SUM(gu12_br.KOL_VAG)-a.CIST_LOADED>0 /*AND SUM(gu12_br.VES)-a.TONN_LOADED>=40*/
		 )
  or a.load_abbr in (select load_abbr from kls_vid_otgr where load_type_id<>1)
  or a.kind_npr>='90000';


