--
-- V_RENEW_BILLS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_RENEW_BILLS
(NOM_DOK, IS_AGENT, NOM_SF, NPO_SF, DATE_VYP_SF, 
 DATE_BUXG, DATE_KVIT, SUMMA_DOK, NDS_DOK, AKCIZ_DOK, 
 GSM_DOK, PRIM, FIO_ISPOL, KOL_DN, OLD_NOM_DOK, 
 NOM_ZD, OWNER_ID, DOG_ID, USL_NUMBER, PROD_ID_NPR, 
 PROD_SUM, PROD_NDS, PROD_AKCIZ, PROD_GSM, DATE_MOS, 
 OLD_NOM_SF, NUM_5_DAY, KORR_5_DAY, LUK_DOG_ID, LUK_USL_NUMBER, 
 LUK_KOL_DN, LUK_SUMMA_DOK, LUK_NDS_DOK, SNP_KOL_DN, SNP_DOG_ID, 
 SNP_USL_NUMBER, KOD_OTGR, PROTO_NUM, PROTO_DATE, NO_AKCIZ)
AS 
SELECT a.nom_dok,
	   KLS_DOG_MAIN.IS_AGENT AS IS_AGENT,
	   a.NOM_SF,
	   UPPER(k2n.NPO_SF) AS NPO_SF,
	   a.DATA_DOK AS DATE_VYP_SF,
	   a.DATA_BUXG AS DATE_BUXG,
	   a.DATA_KVIT AS DATE_KVIT,
	   a.SUMMA_DOK,
       a.d_194+a.ndc_nal20+a.ndc_tr20+d_191+NDC_DOPTAR AS NDS_DOK,
	   a.SUM_AKCIZ AS AKCIZ_DOK,
	   a.D_67 AS GSM_DOK,
	   a.PRIM,
	   a.FIO_ISPOL,
	   a.KOL_DN,
	   a.OLD_NOM AS OLD_NOM_DOK,
       a.NOM_ZD,
	   (CASE
		  WHEN NVL(MONTH.NPR_SOBSTV_ID,0)=0 AND A.DATA_KVIT<TO_DATE('01.01.2005','dd.mm.yyyy') THEN 1
		  WHEN NVL(MONTH.NPR_SOBSTV_ID,0)=0 AND A.DATA_KVIT>=TO_DATE('01.01.2005','dd.mm.yyyy') THEN 8
		  ELSE NVL(MONTH.NPR_SOBSTV_ID,0)
		END) AS OWNER_ID,
	   NVL(KLS_DOG.ID,0) AS DOG_ID,
	   a.K_USL AS USL_NUMBER,
	   a.KOD_NFP AS PROD_ID_NPR,
	   a.d_41+a.d_191+a.SUM_AKCIZ+a.D_67 AS PROD_SUM,
	   a.d_191 AS PROD_NDS,
	   a.SUM_AKCIZ AS PROD_AKCIZ,
	   a.D_67 AS PROD_GSM,
	   NVL(a.DATE_MOS,a.DATA_KVIT) AS DATE_MOS,
	   old_bills.NOM_SF AS OLD_NOM_SF,
	   DECODE(TO_NUMBER(TO_CHAR(NVL(a.DATE_MOS,a.DATA_KVIT),'DD')),31,6,
         TRUNC((TO_NUMBER(TO_CHAR(NVL(a.DATE_MOS,a.DATA_KVIT),'DD'))-1)/5)+1) AS NUM_5_DAY,
	   DECODE(TO_NUMBER(TO_CHAR(a.DATA_KVIT,'DD')),31,6,
         TRUNC((TO_NUMBER(TO_CHAR(a.DATA_KVIT,'DD'))-1)/5)+1) AS KORR_5_DAY,
	   (CASE
	      WHEN A.DATA_KVIT<TO_DATE('01.01.2005','dd.mm.yyyy') THEN
		    CASE
			  WHEN NVL(KLS_DOG.LUKDOG_ID,0)=0 THEN KLS_DOG.ID
			  ELSE KLS_DOG.LUKDOG_ID
			END
		  ELSE MAIN_DOG.ID
		END) AS LUK_DOG_ID,
	   (CASE
	      WHEN A.DATA_KVIT<TO_DATE('01.01.2005','dd.mm.yyyy') THEN
		    CASE
			  WHEN NVL(KLS_DOG.LUKDOG_ID,0)=793 THEN 1
			  ELSE a.K_USL
			END
		  ELSE 1
		END) AS LUK_USL_NUMBER,
	   (CASE
	      WHEN A.DATA_KVIT<TO_DATE('01.01.2005','dd.mm.yyyy') THEN a.KOL_DN
		  ELSE NULL
		END) AS LUK_KOL_DN,
	   (CASE
	      WHEN A.DATA_KVIT<TO_DATE('01.01.2005','dd.mm.yyyy') THEN
		    CASE
              WHEN KLS_DOG.IS_AGENT IN (1,3) THEN a.SUMMA_DOK
			  ELSE a.d_41+a.d_191+a.SUM_AKCIZ+a.D_67
			END
		  ELSE a.d_41+a.d_191+a.SUM_AKCIZ+a.D_67
		END) AS LUK_SUMMA_DOK,
	   (CASE
	      WHEN A.DATA_KVIT<TO_DATE('01.01.2005','dd.mm.yyyy') THEN
		    CASE
              WHEN KLS_DOG.IS_AGENT IN (1,3) THEN a.d_194+a.ndc_nal20+a.ndc_tr20+a.d_191
			  ELSE a.d_191
			END
		  ELSE a.d_191
		END) AS LUK_NDS_DOK,
       DECODE(NVL(MONTH.NPODOG_ID,0),0,a.KOL_DN,SNP_USL_OPL.KOL_DN) AS SNP_KOL_DN,
       DECODE(NVL(MONTH.NPODOG_ID,0),0,KLS_DOG.ID,MONTH.NPODOG_ID) AS SNP_DOG_ID,
       DECODE(NVL(MONTH.NPODOG_ID,0),0,a.K_USL,1) AS SNP_USL_NUMBER,
	   a.KOD_OTGR,
	   a.proto_num,
	   a.proto_date,
	   Iif(A.no_akciz,1,0)
     FROM load_buffer.out_plat A,
	      KLS_DOG,
		  KTU_2_NPO_SF k2n,
		  KLS_DOG SNP_DOG,
		  KLS_USL_OPL SNP_USL_OPL,
		  MONTH,
		  BILLS old_bills,
		  KLS_DOG_MAIN,
		  KLS_DOG MAIN_DOG
    WHERE /*A.nom_dok=BILLS.nom_dok
	  AND */A.NOM_DOG=KLS_DOG.SHORT_NUMBER
	  AND A.NOM_DOK=k2n.NOM_DOK(+)
	  AND A.old_nom=old_bills.nom_dok (+)
	  AND A.nom_zd=MONTH.nom_zd(+)
	  AND MONTH.NPODOG_ID=SNP_DOG.ID (+)
	  AND SNP_DOG.USL_OPL_ID=SNP_USL_OPL.ID (+)
      AND KLS_DOG.IS_AGENT=KLS_DOG_MAIN.IS_AGENT
      AND A.DATA_KVIT BETWEEN KLS_DOG_MAIN.FROM_DATE AND KLS_DOG_MAIN.TO_DATE
	  AND KLS_DOG_MAIN.DOG_ID=MAIN_DOG.ID(+)
--	  AND KLS_DOG_MAIN.IS_AGENT=4
;


