--
-- V_RITM_POST  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_RITM_POST
(BEGIN_DATE, END_DATE, PERIOD_NAME, PLAT_ID, PLAT_NAME, 
 PLAN, GRAF_1, FACT_1, GRAF_2, FACT_2, 
 GRAF_3, FACT_3)
AS 
SELECT 
  --Анализ ритмичности: План/Факт поставок 
  r.BEGIN_DATE, 
  r.END_DATE, 
  RusMonth(r.END_DATE) AS Period_Name, 
  a.PLAT_ID,a.PLAT_NAME, 
  SUM(PLAN_VES) AS PLAN, 
  SUM(GRAF_1) AS GRAF_1, 
  SUM(FACT_1) AS FACT_1, 
  SUM(GRAF_2) AS GRAF_2, 
  SUM(FACT_2) AS FACT_2, 
  SUM(GRAF_3) AS GRAF_3, 
  SUM(FACT_3) AS FACT_3 
FROM 
( 
  SELECT 
    PLAT_ID,PLAT_NAME,PLAN_VES, 
    0 AS GRAF_1, 
    0 AS FACT_1, 
    0 AS GRAF_2, 
    0 AS FACT_2, 
    0 AS GRAF_3, 
    0 AS FACT_3 
  FROM V_RITM_POST_PLAN 
  UNION ALL 
  SELECT 
    PLAT_ID, 
	PLAT_NAME, 
	0 AS PLAN_VES, 
    DECODE(NUM_DECADA,1,GRAF_VES,0) AS GRAF_1, 
    0 AS FACT_1, 
    DECODE(NUM_DECADA,2,GRAF_VES,0) AS GRAF_2, 
    0 AS FACT_2, 
    DECODE(NUM_DECADA,3,GRAF_VES,0) AS GRAF_3, 
    0 AS FACT_3 
  FROM V_RITM_POST_GRAFIK 
  UNION ALL 
  SELECT 
    PLAT_ID, 
	PLAT_NAME, 
	0 AS PLAN_VES, 
    0 AS GRAF_1, 
    DECODE(NUM_DECADA,1,FACT_VES,0) AS FACT_1, 
    0 AS GRAF_2, 
    DECODE(NUM_DECADA,2,FACT_VES,0) AS FACT_2, 
    0 AS GRAF_3, 
    DECODE(NUM_DECADA,3,FACT_VES,0) AS FACT_3 
  FROM V_RITM_POST_FACT 
) a, (SELECT * FROM V_MASTER_REPORTS WHERE NLS_UPPER(REPORT_FILE)='RITM_POST.XLS') r 
GROUP BY 
  r.BEGIN_DATE, 
  r.END_DATE, 
  a.PLAT_ID, 
  a.PLAT_NAME;


