--
-- V_SF_SIGNS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_SF_SIGNS
(BOSS, BLAVBUH, SF_DOVER_ID)
AS 
SELECT "BOSS","BLAVBUH","SF_DOVER_ID" FROM SF_SIGNS 
WHERE Terminal_name=For_Init.GetCurrTerm() 
  AND User_name=For_Init.GetCurrUser();


