--
-- V_SF_DOVER  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_SF_DOVER
(POST_COMPANY, POST_DOLJ, POST_FIO, POST_DOVER, POKUP_COMPANY, 
 POKUP_DOLJ, POKUP_FIO, POKUP_DOVER, POST_DOLJ_SIGN, POST_FIO_SIGN, 
 POKUP_DOLJ_SIGN, POKUP_FIO_SIGN, POKUP_COMPANY_SIGN)
AS 
SELECT POST_COMPANY, POST_DOLJ, POST_FIO, POST_DOVER, POKUP_COMPANY, POKUP_DOLJ, POKUP_FIO, POKUP_DOVER, 
POST_DOLJ_SIGN,POST_FIO_SIGN,POKUP_DOLJ_SIGN, POKUP_FIO_SIGN,POKUP_COMPANY_SIGN FROM SF_SIGNS, SF_DOVER 
WHERE Terminal_name=For_Init.GetCurrTerm() 
  AND User_name=For_Init.GetCurrUser() 
  AND SF_SIGNS.SF_DOVER_ID=SF_DOVER.ID(+);


