--
-- V_SF_POS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_SF_POS
(ABBR_NPR, LONG_NAME_NPR, NOM_DOK, BILL_POS_ID, VES, 
 CENA, SUMMA, SUMMA_BN, SUMMA_NDS20, PAYED_SUMMA)
AS 
SELECT
  kls_prod.ABBR_NPR,
  kls_prod.NAME_NPR as LONG_NAME_NPR,
  BILL_POS.NOM_DOK,
  BILL_POS.BILL_POS_ID,
  BILL_POS.VES,
  BILL_POS.CENA_BN,
  BILL_POS.SUMMA,
  BILL_POS.SUMMA_BN,
  BILL_POS.SUMMA_NDS20,
  SUM(payments_on_bills.SUMMA) AS payed_summa
FROM
  BILL_POS,kls_prod,payments_on_bills
WHERE
  bill_pos.PROD_ID_NPR=kls_prod.ID_NPR(+) and
  bill_pos.NOM_DOK=payments_on_bills.NOM_DOK(+) and
  bill_pos.BILL_POS_ID=payments_on_bills.BILL_POS_ID(+)
GROUP BY
  kls_prod.ABBR_NPR,
  kls_prod.NAME_NPR,
  BILL_POS.VES,
  BILL_POS.CENA_BN,
  BILL_POS.SUMMA,
  BILL_POS.SUMMA_BN,
  BILL_POS.SUMMA_NDS20,
  BILL_POS.NOM_DOK,
  BILL_POS.BILL_POS_ID;


