--
-- V_SLIV_NEFT  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_SLIV_NEFT
(PROD_ID_NPR, PROD_NAME, NUM_CIST, NUM_KVIT, SVED_NUM, 
 VAGOWNER_NAME, VES_KVIT, DATE_IN_STAN, DATE_VOZ, STAN_VOZ_NAME, 
 PRIM, SVED_POS, SVED_DATE)
AS 
SELECT
  Si.PROD_ID_NPR,
  P.NAME_NPR as PROD_NAME,
  Ri.NUM_CIST,
  DECODE(Ri.NUM_KVIT,99999,'?',LPAD(TO_CHAR(Ri.NUM_KVIT),6,'0')) as NUM_KVIT,
  TO_CHAR(Si.SVED_NUM) as SVED_NUM,
  V.DISPLAY_NAME as VAGOWNER_NAME,
  Ri.VES_KVIT,
  Ri.DATE_IN_STAN,
  Ri.DATE_VOZ,
  SV.STAN_KOD || ' ' || SV.STAN_NAME as STAN_VOZ_NAME,
  (CASE
    WHEN Ri.DATE_IN_STAN+2<NVL(Ri.DATE_VOZ,r.END_DATE) THEN 'Просрочка'
	ELSE ''
   END) as PRIM,
  Ri.SVED_POS,
  Si.SVED_DATE
FROM
  SVED_IN Si, REESTR_IN Ri, KLS_PROD P, KLS_VAGOWNER V, KLS_STAN SV,
  v_master_reports r
WHERE
  Si.ID=Ri.SVED_IN_ID AND
  Si.PROD_ID_NPR=P.ID_NPR AND
  Ri.VAGOWNER_ID=V.ID(+) AND
  Ri.STAN_VOZ_ID=SV.ID(+) AND
  NLS_UPPER(TRIM(r.report_file))='SLIV_NEFT.XLS' AND
/*  Ri.DATE_IN_STAN>=r.begin_date AND
  Ri.DATE_IN_STAN<=r.end_date AND */
  Si.PROD_ID_NPR=DECODE(r.PROD_ID_NPR,'*',Si.PROD_ID_NPR,r.PROD_ID_NPR);


