--
-- V_SNP_DEBITOR_SF  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_SNP_DEBITOR_SF
(NOM_SF, NOM_DOK, LUKDOG_ID, PLAT_ID, DOG_ID, 
 IS_PROD, DATE_KVIT, KOL_DN, DATE_TO_OPL, SUMMA_DOK)
AS 
SELECT
  BILLS_SNP.nom_sf AS nom_sf,
  BILLS_SNP.nom_dok AS nom_dok,
  DECODE(NVL(KLS_DOG.LUKDOG_ID,0),0,BILLS_SNP.DOG_ID,KLS_DOG.LUKDOG_ID) AS LUKDOG_ID,
  KLS_DOG.PREDPR_ID AS NPOPLAT_ID,
  BILLS_SNP.DOG_ID AS NPODOG_ID,
  DECODE(SIGN(bp.BILL_POS_SNP_ID-10),-1,1,0),
  MAX(BILLS_SNP.DATE_KVIT),
  MAX(BILLS_SNP.KOL_DN),
  MAX(BILLS_SNP.DATE_KVIT+BILLS_SNP.KOL_DN),
  SUM(bp.summa) AS summa_dok
FROM BILLS, BILLS_SNP, BILL_POS_SNP bp, KLS_DOG
WHERE BILLS_SNP.DATE_KVIT>=TO_DATE('01.04.2002','dd.mm.yyyy')
  AND BILLS.DATE_KVIT>=TO_DATE('01.04.2002','dd.mm.yyyy')
  AND BILLS_SNP.NOM_DOK=BILLS.nom_dok
  AND BILLS_SNP.DOG_ID = KLS_DOG.ID
  AND bp.nom_dok = BILLS_SNP.nom_dok
GROUP BY
  BILLS_SNP.nom_sf,
  BILLS_SNP.nom_dok,
  DECODE(NVL(KLS_DOG.LUKDOG_ID,0),0,BILLS_SNP.DOG_ID,KLS_DOG.LUKDOG_ID),
  KLS_DOG.PREDPR_ID,
  BILLS_SNP.DOG_ID,
  DECODE(SIGN(bp.BILL_POS_SNP_ID-10),-1,1,0)
UNION ALL
SELECT
  0 AS nom_sf,
  0 AS nom_dok,
  KLS_DOG.LUKDOG_ID AS LUKDOG_ID,
  KLS_PREDPR.ID AS NPOPLAT_ID,
  KLS_DOG.ID AS NPODOG_ID,
  1,
  TO_DATE('31.03.2002','dd.mm.yyyy'),
  KLS_USL_OPL.KOL_DN,
  TO_DATE('31.03.2002','dd.mm.yyyy')+KLS_USL_OPL.KOL_DN,
  KLS_DOG.SALDO_01042002_PROD
FROM KLS_DOG,KLS_PREDPR,KLS_USL_OPL
WHERE KLS_DOG.SALDO_01042002<>0
  AND KLS_DOG.USL_OPL_ID = KLS_USL_OPL.ID (+)
  AND KLS_DOG.PREDPR_ID = KLS_PREDPR.ID
UNION ALL
SELECT
  0 AS nom_sf,
  0 AS nom_dok,
  KLS_DOG.LUKDOG_ID AS LUKDOG_ID,
  KLS_PREDPR.ID AS NPOPLAT_ID,
  KLS_DOG.ID AS NPODOG_ID,
  0,
  TO_DATE('31.03.2002','dd.mm.yyyy'),
  KLS_USL_OPL.KOL_DN,
  TO_DATE('31.03.2002','dd.mm.yyyy')+KLS_USL_OPL.KOL_DN,
  KLS_DOG.SALDO_01042002-KLS_DOG.SALDO_01042002_PROD
FROM KLS_DOG,KLS_PREDPR,KLS_USL_OPL
WHERE KLS_DOG.SALDO_01042002<>0
  AND KLS_DOG.USL_OPL_ID = KLS_USL_OPL.ID (+)
  AND KLS_DOG.PREDPR_ID = KLS_PREDPR.ID;


