--
-- V_SNP_DISP_AZS_OPER_OST_PSV  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_SNP_DISP_AZS_OPER_OST_PSV
(STORE_RN, NOMEN_RN, OUT_O_PREV_VOL, OUT_O_PREV_MAS, OUT_O_PREV_SUM, 
 IN_VOL, IN_MAS, IN_SUM, IN_HR_VOL, IN_HR_MAS, 
 IN_HR_SUM, IN_I_VOL, IN_I_MAS, IN_I_SUM, IN_O_VOL, 
 IN_O_MAS, IN_O_SUM, OUT_VOL, OUT_MAS, OUT_SUM, 
 OUT_HR_VOL, OUT_HR_MAS, OUT_HR_SUM, OUT_I_VOL, OUT_I_MAS, 
 OUT_I_SUM, OUT_O_VOL, OUT_O_MAS, OUT_O_SUM, OUT_O_VED_VOL, 
 OUT_O_VED_MAS, OUT_O_VED_SUM, OUT_O_BK_VOL, OUT_O_BK_MAS, OUT_O_BK_SUM, 
 OUT_O_KR_VOL, OUT_O_KR_MAS, OUT_O_KR_SUM, OUT_O_NAL_VOL, OUT_O_NAL_MAS, 
 OUT_O_NAL_SUM, OUT_O_FIL_VOL, OUT_O_FIL_MAS, OUT_O_FIL_SUM, OUT_O_LIC_VOL, 
 OUT_O_LIC_MAS, OUT_O_LIC_SUM, END_VOLUME, END_MASSA, END_FULL, 
 END_WATER, IN_TTN_VOL, IN_TTN_MAS, IN_TTN_SUM, OUT_O_1_VOL, 
 OUT_O_1_MAS, OUT_O_2_VOL, OUT_O_2_MAS, OUT_O_3_VOL, OUT_O_3_MAS, 
 OUT_O_4_VOL, OUT_O_4_MAS, OUT_O_5_VOL, OUT_O_5_MAS, OUT_O_6_VOL, 
 OUT_O_6_MAS, OUT_O_7_VOL, OUT_O_7_MAS, IN_LAST_VOL, IN_LAST_MAS, 
 IN_LAST_SUM, IN_WAY_VOL, IN_WAY_MAS, IN_WAY_SUM)
AS 
SELECT
 STORE_RN,
 NOMEN_RN,
 SUM(OUT_O_PREV_VOL),
 SUM(OUT_O_PREV_MAS),
 SUM(OUT_O_PREV_SUM),
 SUM(IN_VOL),
 SUM(IN_MAS),
 SUM(IN_SUM),
 SUM(IN_HR_VOL),
 SUM(IN_HR_MAS),
 SUM(IN_HR_SUM),
 SUM(IN_I_VOL),
 SUM(IN_I_MAS),
 SUM(IN_I_SUM),
 SUM(IN_O_VOL),
 SUM(IN_O_MAS),
 SUM(IN_O_SUM),
 SUM(OUT_VOL),
 SUM(OUT_MAS),
 SUM(OUT_SUM),
 SUM(OUT_HR_VOL),
 SUM(OUT_HR_MAS),
 SUM(OUT_HR_SUM),
 SUM(OUT_I_VOL),
 SUM(OUT_I_MAS),
 SUM(OUT_I_SUM),
 SUM(OUT_O_VOL),
 SUM(OUT_O_MAS),
 SUM(OUT_O_SUM),
 SUM(OUT_O_VED_VOL),
 SUM(OUT_O_VED_MAS),
 SUM(OUT_O_VED_SUM),
 SUM(OUT_O_BK_VOL),
 SUM(OUT_O_BK_MAS),
 SUM(OUT_O_BK_SUM),
 SUM(OUT_O_KR_VOL),
 SUM(OUT_O_KR_MAS),
 SUM(OUT_O_KR_SUM),
 SUM(OUT_O_NAL_VOL),
 SUM(OUT_O_NAL_MAS),
 SUM(OUT_O_NAL_SUM),
 SUM(OUT_O_FIL_VOL),
 SUM(OUT_O_FIL_MAS),
 SUM(OUT_O_FIL_SUM),
 SUM(OUT_O_LIC_VOL),
 SUM(OUT_O_LIC_MAS),
 SUM(OUT_O_LIC_SUM),
 SUM(END_VOLUME),
 SUM(END_MASSA),
 SUM(END_FULL),
 SUM(END_WATER),
 SUM(IN_TTN_VOL),
 SUM(IN_TTN_MAS),
 SUM(IN_TTN_SUM),
 SUM(OUT_O_1_VOL) as OUT_O_1_VOL,
 SUM(OUT_O_1_MAS) as OUT_O_1_MAS,
 SUM(OUT_O_2_VOL) as OUT_O_2_VOL,
 SUM(OUT_O_2_MAS) as OUT_O_2_MAS,
 SUM(OUT_O_3_VOL) as OUT_O_3_VOL,
 SUM(OUT_O_3_MAS) as OUT_O_3_MAS,
 SUM(OUT_O_4_VOL) as OUT_O_4_VOL,
 SUM(OUT_O_4_MAS) as OUT_O_4_MAS,
 SUM(OUT_O_5_VOL) as OUT_O_5_VOL,
 SUM(OUT_O_5_MAS) as OUT_O_5_MAS,
 SUM(OUT_O_6_VOL) as OUT_O_6_VOL,
 SUM(OUT_O_6_MAS) as OUT_O_6_MAS,
 SUM(OUT_O_7_VOL) as OUT_O_7_VOL,
 SUM(OUT_O_7_MAS) as OUT_O_7_MAS,
 SUM(IN_LAST_VOL),
 SUM(IN_LAST_MAS),
 SUM(IN_LAST_SUM),
 SUM(IN_WAY_VOL),
 SUM(IN_WAY_MAS),
 SUM(IN_WAY_SUM)
FROM
(
SELECT
     STORE_RN,
     NOMEN_RN,
     0 as OUT_O_PREV_VOL,
     0 as OUT_O_PREV_MAS,
     0 as OUT_O_PREV_SUM,
     0 as IN_VOL,
     0 as IN_MAS,
     0 as IN_SUM,
     0 as IN_HR_VOL,
     0 as IN_HR_MAS,
     0 as IN_HR_SUM,
     0 as IN_I_VOL,
     0 as IN_I_MAS,
     0 as IN_I_SUM,
     0 as IN_O_VOL,
     0 as IN_O_MAS,
     0 as IN_O_SUM,
     0 as OUT_VOL,
     0 as OUT_MAS,
     0 as OUT_SUM,
     0 as OUT_HR_VOL,
     0 as OUT_HR_MAS,
     0 as OUT_HR_SUM,
     0 as OUT_I_VOL,
     0 as OUT_I_MAS,
     0 as OUT_I_SUM,
     0 as OUT_O_VOL,
     0 as OUT_O_MAS,
     0 as OUT_O_SUM,
     0 as OUT_O_VED_VOL,
     0 as OUT_O_VED_MAS,
     0 as OUT_O_VED_SUM,
     0 as OUT_O_BK_VOL,
     0 as OUT_O_BK_MAS,
     0 as OUT_O_BK_SUM,
     0 as OUT_O_KR_VOL,
     0 as OUT_O_KR_MAS,
     0 as OUT_O_KR_SUM,
     0 as OUT_O_NAL_VOL,
     0 as OUT_O_NAL_MAS,
     0 as OUT_O_NAL_SUM,
     0 as OUT_O_FIL_VOL,
     0 as OUT_O_FIL_MAS,
     0 as OUT_O_FIL_SUM,
     0 as OUT_O_LIC_VOL,
     0 as OUT_O_LIC_MAS,
     0 as OUT_O_LIC_SUM,
     END_VOLUME,
     END_MASSA,
     END_FULL,
     END_WATER,
     0 as IN_TTN_VOL,
     0 as IN_TTN_MAS,
     0 as IN_TTN_SUM,
     0 as OUT_O_1_VOL,
     0 as OUT_O_1_MAS,
     0 as OUT_O_2_VOL,
     0 as OUT_O_2_MAS,
     0 as OUT_O_3_VOL,
     0 as OUT_O_3_MAS,
     0 as OUT_O_4_VOL,
     0 as OUT_O_4_MAS,
     0 as OUT_O_5_VOL,
     0 as OUT_O_5_MAS,
     0 as OUT_O_6_VOL,
     0 as OUT_O_6_MAS,
     0 as OUT_O_7_VOL,
     0 as OUT_O_7_MAS,
     0 as IN_LAST_VOL,
     0 as IN_LAST_MAS,
     0 as IN_LAST_SUM,
     0 as IN_WAY_VOL,
     0 as IN_WAY_MAS,
     0 as IN_WAY_SUM
   FROM MASTER.V_SNP_DISP_AZS_OST_GRP_PSV
   UNION ALL
   SELECT
     STORE_RN,
     NOMEN_RN,
     0 as OUT_O_PREV_VOL,
     0 as OUT_O_PREV_MAS,
     0 as OUT_O_PREV_SUM,
     IN_VOL,
     IN_MAS,
     IN_SUM,
     IN_HR_VOL,
     IN_HR_MAS,
     IN_HR_SUM,
     IN_I_VOL,
     IN_I_MAS,
     IN_I_SUM,
     IN_O_VOL,
     IN_O_MAS,
     IN_O_SUM,
     OUT_VOL,
     OUT_MAS,
     OUT_SUM,
     OUT_HR_VOL,
     OUT_HR_MAS,
     OUT_HR_SUM,
     OUT_I_VOL,
     OUT_I_MAS,
     OUT_I_SUM,
     OUT_O_VOL,
     OUT_O_MAS,
     OUT_O_SUM,
     OUT_O_VED_VOL,
     OUT_O_VED_MAS,
     OUT_O_VED_SUM,
     OUT_O_BK_VOL,
     OUT_O_BK_MAS,
     OUT_O_BK_SUM,
     OUT_O_KR_VOL,
     OUT_O_KR_MAS,
     OUT_O_KR_SUM,
     OUT_O_NAL_VOL,
     OUT_O_NAL_MAS,
     OUT_O_NAL_SUM,
     OUT_O_FIL_VOL,
     OUT_O_FIL_MAS,
     OUT_O_FIL_SUM,
     OUT_O_LIC_VOL,
     OUT_O_LIC_MAS,
     OUT_O_LIC_SUM,
     0 as END_VOLUME,
     0 as END_MASSA,
     0 as END_FULL,
     0 as END_WATER,
     IN_TTN_VOL,
     IN_TTN_MAS,
     IN_TTN_SUM,
     0 as OUT_O_1_VOL,
     0 as OUT_O_1_MAS,
     0 as OUT_O_2_VOL,
     0 as OUT_O_2_MAS,
     0 as OUT_O_3_VOL,
     0 as OUT_O_3_MAS,
     0 as OUT_O_4_VOL,
     0 as OUT_O_4_MAS,
     0 as OUT_O_5_VOL,
     0 as OUT_O_5_MAS,
     0 as OUT_O_6_VOL,
     0 as OUT_O_6_MAS,
     0 as OUT_O_7_VOL,
     0 as OUT_O_7_MAS,
     0 as IN_LAST_VOL,
     0 as IN_LAST_MAS,
     0 as IN_LAST_SUM,
     0 as IN_WAY_VOL,
     0 as IN_WAY_MAS,
     0 as IN_WAY_SUM
   FROM MASTER.V_SNP_DISP_AZS_OPER_GRP_PSV
   UNION ALL
   SELECT
     STORE_RN,
     NOMEN_RN,
     OUT_O_PREV_VOL,
     OUT_O_PREV_MAS,
     OUT_O_PREV_SUM,
     0 as IN_VOL,
     0 as IN_MAS,
     0 as IN_SUM,
     0 as IN_HR_VOL,
     0 as IN_HR_MAS,
     0 as IN_HR_SUM,
     0 as IN_I_VOL,
     0 as IN_I_MAS,
     0 as IN_I_SUM,
     0 as IN_O_VOL,
     0 as IN_O_MAS,
     0 as IN_O_SUM,
     0 as OUT_VOL,
     0 as OUT_MAS,
     0 as OUT_SUM,
     0 as OUT_HR_VOL,
     0 as OUT_HR_MAS,
     0 as OUT_HR_SUM,
     0 as OUT_I_VOL,
     0 as OUT_I_MAS,
     0 as OUT_I_SUM,
     0 as OUT_O_VOL,
     0 as OUT_O_MAS,
     0 as OUT_O_SUM,
     0 as OUT_O_VED_VOL,
     0 as OUT_O_VED_MAS,
     0 as OUT_O_VED_SUM,
     0 as OUT_O_BK_VOL,
     0 as OUT_O_BK_MAS,
     0 as OUT_O_BK_SUM,
     0 as OUT_O_KR_VOL,
     0 as OUT_O_KR_MAS,
     0 as OUT_O_KR_SUM,
     0 as OUT_O_NAL_VOL,
     0 as OUT_O_NAL_MAS,
     0 as OUT_O_NAL_SUM,
     0 as OUT_O_FIL_VOL,
     0 as OUT_O_FIL_MAS,
     0 as OUT_O_FIL_SUM,
     0 as OUT_O_LIC_VOL,
     0 as OUT_O_LIC_MAS,
     0 as OUT_O_LIC_SUM,
     0 as END_VOLUME,
     0 as END_MASSA,
     0 as END_FULL,
     0 as END_WATER,
     0 as IN_TTN_VOL,
     0 as IN_TTN_MAS,
     0 as IN_TTN_SUM,
     0 as OUT_O_1_VOL,
     0 as OUT_O_1_MAS,
     0 as OUT_O_2_VOL,
     0 as OUT_O_2_MAS,
     0 as OUT_O_3_VOL,
     0 as OUT_O_3_MAS,
     0 as OUT_O_4_VOL,
     0 as OUT_O_4_MAS,
     0 as OUT_O_5_VOL,
     0 as OUT_O_5_MAS,
     0 as OUT_O_6_VOL,
     0 as OUT_O_6_MAS,
     0 as OUT_O_7_VOL,
     0 as OUT_O_7_MAS,
     0 as IN_LAST_VOL,
     0 as IN_LAST_MAS,
     0 as IN_LAST_SUM,
     0 as IN_WAY_VOL,
     0 as IN_WAY_MAS,
     0 as IN_WAY_SUM
   FROM MASTER.V_SNP_DISP_AZS_OPER_PREV_PSV
   UNION ALL
   SELECT
     STORE_RN,
     NOMEN_RN,
     0 as OUT_O_PREV_VOL,
     0 as OUT_O_PREV_MAS,
     0 as OUT_O_PREV_SUM,
     0 as IN_VOL,
     0 as IN_MAS,
     0 as IN_SUM,
     0 as IN_HR_VOL,
     0 as IN_HR_MAS,
     0 as IN_HR_SUM,
     0 as IN_I_VOL,
     0 as IN_I_MAS,
     0 as IN_I_SUM,
     0 as IN_O_VOL,
     0 as IN_O_MAS,
     0 as IN_O_SUM,
     0 as OUT_VOL,
     0 as OUT_MAS,
     0 as OUT_SUM,
     0 as OUT_HR_VOL,
     0 as OUT_HR_MAS,
     0 as OUT_HR_SUM,
     0 as OUT_I_VOL,
     0 as OUT_I_MAS,
     0 as OUT_I_SUM,
     0 as OUT_O_VOL,
     0 as OUT_O_MAS,
     0 as OUT_O_SUM,
     0 as OUT_O_VED_VOL,
     0 as OUT_O_VED_MAS,
     0 as OUT_O_VED_SUM,
     0 as OUT_O_BK_VOL,
     0 as OUT_O_BK_MAS,
     0 as OUT_O_BK_SUM,
     0 as OUT_O_KR_VOL,
     0 as OUT_O_KR_MAS,
     0 as OUT_O_KR_SUM,
     0 as OUT_O_NAL_VOL,
     0 as OUT_O_NAL_MAS,
     0 as OUT_O_NAL_SUM,
     0 as OUT_O_FIL_VOL,
     0 as OUT_O_FIL_MAS,
     0 as OUT_O_FIL_SUM,
     0 as OUT_O_LIC_VOL,
     0 as OUT_O_LIC_MAS,
     0 as OUT_O_LIC_SUM,
     0 as END_VOLUME,
     0 as END_MASSA,
     0 as END_FULL,
     0 as END_WATER,
     0 as IN_TTN_VOL,
     0 as IN_TTN_MAS,
     0 as IN_TTN_SUM,
     OUT_O_1_VOL,
     OUT_O_1_MAS,
     OUT_O_2_VOL,
     OUT_O_2_MAS,
     OUT_O_3_VOL,
     OUT_O_3_MAS,
     OUT_O_4_VOL,
     OUT_O_4_MAS,
     OUT_O_5_VOL,
     OUT_O_5_MAS,
     OUT_O_6_VOL,
     OUT_O_6_MAS,
     OUT_O_7_VOL,
     OUT_O_7_MAS,
     0 as IN_LAST_VOL,
     0 as IN_LAST_MAS,
     0 as IN_LAST_SUM,
     0 as IN_WAY_VOL,
     0 as IN_WAY_MAS,
     0 as IN_WAY_SUM
   FROM MASTER.V_SNP_DISP_AZS_OPER_WEEK_PSV
   UNION ALL
   SELECT
     STORE_RN,
     NOMEN_RN,
     0 as OUT_O_PREV_VOL,
     0 as OUT_O_PREV_MAS,
     0 as OUT_O_PREV_SUM,
     0 as IN_VOL,
     0 as IN_MAS,
     0 as IN_SUM,
     0 as IN_HR_VOL,
     0 as IN_HR_MAS,
     0 as IN_HR_SUM,
     0 as IN_I_VOL,
     0 as IN_I_MAS,
     0 as IN_I_SUM,
     0 as IN_O_VOL,
     0 as IN_O_MAS,
     0 as IN_O_SUM,
     0 as OUT_VOL,
     0 as OUT_MAS,
     0 as OUT_SUM,
     0 as OUT_HR_VOL,
     0 as OUT_HR_MAS,
     0 as OUT_HR_SUM,
     0 as OUT_I_VOL,
     0 as OUT_I_MAS,
     0 as OUT_I_SUM,
     0 as OUT_O_VOL,
     0 as OUT_O_MAS,
     0 as OUT_O_SUM,
     0 as OUT_O_VED_VOL,
     0 as OUT_O_VED_MAS,
     0 as OUT_O_VED_SUM,
     0 as OUT_O_BK_VOL,
     0 as OUT_O_BK_MAS,
     0 as OUT_O_BK_SUM,
     0 as OUT_O_KR_VOL,
     0 as OUT_O_KR_MAS,
     0 as OUT_O_KR_SUM,
     0 as OUT_O_NAL_VOL,
     0 as OUT_O_NAL_MAS,
     0 as OUT_O_NAL_SUM,
     0 as OUT_O_FIL_VOL,
     0 as OUT_O_FIL_MAS,
     0 as OUT_O_FIL_SUM,
     0 as OUT_O_LIC_VOL,
     0 as OUT_O_LIC_MAS,
     0 as OUT_O_LIC_SUM,
     0 as END_VOLUME,
     0 as END_MASSA,
     0 as END_FULL,
     0 as END_WATER,
     0 as IN_TTN_VOL,
     0 as IN_TTN_MAS,
     0 as IN_TTN_SUM,
     0 as OUT_O_1_VOL,
     0 as OUT_O_1_MAS,
     0 as OUT_O_2_VOL,
     0 as OUT_O_2_MAS,
     0 as OUT_O_3_VOL,
     0 as OUT_O_3_MAS,
     0 as OUT_O_4_VOL,
     0 as OUT_O_4_MAS,
     0 as OUT_O_5_VOL,
     0 as OUT_O_5_MAS,
     0 as OUT_O_6_VOL,
     0 as OUT_O_6_MAS,
     0 as OUT_O_7_VOL,
     0 as OUT_O_7_MAS,
     VOLUME as IN_LAST_VOL,
     MASSA as IN_LAST_MAS,
     SUMMA as IN_LAST_SUM,
     0 as IN_WAY_VOL,
     0 as IN_WAY_MAS,
     0 as IN_WAY_SUM
   FROM MASTER.V_SNP_DISP_AZS_IN_LAST_PSV
   UNION ALL
   SELECT
     STORE_RN,
     NOMEN_RN,
     0 as OUT_O_PREV_VOL,
     0 as OUT_O_PREV_MAS,
     0 as OUT_O_PREV_SUM,
     0 as IN_VOL,
     0 as IN_MAS,
     0 as IN_SUM,
     0 as IN_HR_VOL,
     0 as IN_HR_MAS,
     0 as IN_HR_SUM,
     0 as IN_I_VOL,
     0 as IN_I_MAS,
     0 as IN_I_SUM,
     0 as IN_O_VOL,
     0 as IN_O_MAS,
     0 as IN_O_SUM,
     0 as OUT_VOL,
     0 as OUT_MAS,
     0 as OUT_SUM,
     0 as OUT_HR_VOL,
     0 as OUT_HR_MAS,
     0 as OUT_HR_SUM,
     0 as OUT_I_VOL,
     0 as OUT_I_MAS,
     0 as OUT_I_SUM,
     0 as OUT_O_VOL,
     0 as OUT_O_MAS,
     0 as OUT_O_SUM,
     0 as OUT_O_VED_VOL,
     0 as OUT_O_VED_MAS,
     0 as OUT_O_VED_SUM,
     0 as OUT_O_BK_VOL,
     0 as OUT_O_BK_MAS,
     0 as OUT_O_BK_SUM,
     0 as OUT_O_KR_VOL,
     0 as OUT_O_KR_MAS,
     0 as OUT_O_KR_SUM,
     0 as OUT_O_NAL_VOL,
     0 as OUT_O_NAL_MAS,
     0 as OUT_O_NAL_SUM,
     0 as OUT_O_FIL_VOL,
     0 as OUT_O_FIL_MAS,
     0 as OUT_O_FIL_SUM,
     0 as OUT_O_LIC_VOL,
     0 as OUT_O_LIC_MAS,
     0 as OUT_O_LIC_SUM,
     0 as END_VOLUME,
     0 as END_MASSA,
     0 as END_FULL,
     0 as END_WATER,
     0 as IN_TTN_VOL,
     0 as IN_TTN_MAS,
     0 as IN_TTN_SUM,
     0 as OUT_O_1_VOL,
     0 as OUT_O_1_MAS,
     0 as OUT_O_2_VOL,
     0 as OUT_O_2_MAS,
     0 as OUT_O_3_VOL,
     0 as OUT_O_3_MAS,
     0 as OUT_O_4_VOL,
     0 as OUT_O_4_MAS,
     0 as OUT_O_5_VOL,
     0 as OUT_O_5_MAS,
     0 as OUT_O_6_VOL,
     0 as OUT_O_6_MAS,
     0 as OUT_O_7_VOL,
     0 as OUT_O_7_MAS,
     0 as IN_LAST_VOL,
     0 as IN_LAST_MAS,
     0 as IN_LAST_SUM,
     VOLUME as IN_WAY_VOL,
     MASSA as IN_WAY_MAS,
     SUMMA as IN_WAY_SUM
   FROM MASTER.V_SNP_DISP_AZS_WAY_PSV
)
GROUP BY STORE_RN,NOMEN_RN;


