--
-- V_SNP_DISP_AZS_OPER_WEEK_PSV  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_SNP_DISP_AZS_OPER_WEEK_PSV
(STORE_RN, NOMEN_RN, OUT_O_1_VOL, OUT_O_1_MAS, OUT_O_2_VOL, 
 OUT_O_2_MAS, OUT_O_3_VOL, OUT_O_3_MAS, OUT_O_4_VOL, OUT_O_4_MAS, 
 OUT_O_5_VOL, OUT_O_5_MAS, OUT_O_6_VOL, OUT_O_6_MAS, OUT_O_7_VOL, 
 OUT_O_7_MAS)
AS 
SELECT /*+ RULE Внешний расход на АЗС по сменным отчетам за предыдущий период по дням недели*/
  STORE_RN, -- Склад
  NOMEN_RN, -- Н/пр
  SUM(DECODE(WEEK_DAY,1,VOLUME,0)) as VOL_1,
  SUM(DECODE(WEEK_DAY,1,MASSA,0)) as MAS_1,
  SUM(DECODE(WEEK_DAY,2,VOLUME,0)) as VOL_2,
  SUM(DECODE(WEEK_DAY,2,MASSA,0)) as MAS_2,
  SUM(DECODE(WEEK_DAY,3,VOLUME,0)) as VOL_3,
  SUM(DECODE(WEEK_DAY,3,MASSA,0)) as MAS_3,
  SUM(DECODE(WEEK_DAY,4,VOLUME,0)) as VOL_4,
  SUM(DECODE(WEEK_DAY,4,MASSA,0)) as MAS_4,
  SUM(DECODE(WEEK_DAY,5,VOLUME,0)) as VOL_5,
  SUM(DECODE(WEEK_DAY,5,MASSA,0)) as MAS_5,
  SUM(DECODE(WEEK_DAY,6,VOLUME,0)) as VOL_6,
  SUM(DECODE(WEEK_DAY,6,MASSA,0)) as MAS_6,
  SUM(DECODE(WEEK_DAY,7,VOLUME,0)) as VOL_7,
  SUM(DECODE(WEEK_DAY,7,MASSA,0)) as MAS_7
FROM PARUS.TB_SNP_STORE_OPER_PSV@oracle.world AA, PARUS.AZSGSMWAYSTYPES@oracle.world way
WHERE USER_ID=NLS_UPPER(SYS_CONTEXT('USERENV','OS_USER'))
  AND SOURCE_ID=82
  AND AA.STOPER_RN = way.RN
  AND NOT (way.GSMWAYS_MNEMO LIKE 'РАСХПРОБ%' OR way.GSMWAYS_MNEMO = 'РАСХТАР' OR way.GSMWAYS_MNEMO LIKE 'СОБСТВ_НУЖДЫ%')
GROUP BY STORE_RN,NOMEN_RN;


