--
-- V_SNP_DISP_AZS_OPER_PREV_PSV  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_SNP_DISP_AZS_OPER_PREV_PSV
(STORE_RN, NOMEN_RN, OUT_O_PREV_VOL, OUT_O_PREV_MAS, OUT_O_PREV_SUM)
AS 
SELECT /*+ RULE Внешний расход на АЗС по сменным отчетам за предыдущий период */
  STORE_RN, -- Склад
  NOMEN_RN, -- Н/пр
  SUM(VOLUME) as VOLUME,
  SUM(MASSA) as MASSA,
  SUM(SUMMA) as SUMMA
FROM PARUS.TB_SNP_STORE_OPER_PSV@oracle.world AA, PARUS.AZSGSMWAYSTYPES@oracle.world way
WHERE USER_ID=NLS_UPPER(SYS_CONTEXT('USERENV','OS_USER'))
  AND SOURCE_ID=82
  AND AA.STOPER_RN = way.RN
  AND NOT (way.GSMWAYS_MNEMO LIKE 'РАСХПРОБ%' OR way.GSMWAYS_MNEMO = 'РАСХТАР' OR way.GSMWAYS_MNEMO LIKE 'СОБСТВ_НУЖДЫ%')
GROUP BY STORE_RN,NOMEN_RN;


