--
-- V_SNP_DISP_AZS_IN_LAST_PSV  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_SNP_DISP_AZS_IN_LAST_PSV
(OPER_ID, STORE_RN, NOMEN_RN, MIN_DAY, MAX_DAY, 
 VOLUME, MASSA, SUMMA)
AS 
SELECT /*+ RULE Приход на АЗС за последнюю смену по сменным отчетам */
  'IN_LAST' as OPER_ID, -- Тип операции
  STORE_RN, -- Склад
  NOMEN_RN, -- Н/пр
  MIN(MIN_DAY) as MIN_DAY,
  MAX(MAX_DAY) as MAX_DAY,
  SUM(VOLUME) as VOLUME,
  SUM(MASSA) as MASSA,
  SUM(SUMMA) as SUMMA
FROM PARUS.TB_SNP_STORE_OPER_PSV@oracle.world AA, PARUS.AZSGSMWAYSTYPES@oracle.world way
WHERE  USER_ID=NLS_UPPER(SYS_CONTEXT('USERENV','OS_USER'))
  AND SOURCE_ID=84
  AND AA.STOPER_RN = way.RN
  AND way.KEEP_SIGN=0
  AND NOT (way.GSMWAYS_MNEMO = 'ПРИХПРОБ' OR way.GSMWAYS_MNEMO = 'ПРИХТАР')
GROUP BY STORE_RN,NOMEN_RN;


