--
-- V_SNP_DISP_AZS_OPER_GRP_PSV  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_SNP_DISP_AZS_OPER_GRP_PSV
(STORE_RN, NOMEN_RN, IN_VOL, IN_MAS, IN_SUM, 
 IN_HR_VOL, IN_HR_MAS, IN_HR_SUM, IN_I_VOL, IN_I_MAS, 
 IN_I_SUM, IN_O_VOL, IN_O_MAS, IN_O_SUM, IN_TTN_VOL, 
 IN_TTN_MAS, IN_TTN_SUM, OUT_VOL, OUT_MAS, OUT_SUM, 
 OUT_HR_VOL, OUT_HR_MAS, OUT_HR_SUM, OUT_I_VOL, OUT_I_MAS, 
 OUT_I_SUM, OUT_O_VOL, OUT_O_MAS, OUT_O_SUM, OUT_O_VED_VOL, 
 OUT_O_VED_MAS, OUT_O_VED_SUM, OUT_O_BK_VOL, OUT_O_BK_MAS, OUT_O_BK_SUM, 
 OUT_O_KR_VOL, OUT_O_KR_MAS, OUT_O_KR_SUM, OUT_O_NAL_VOL, OUT_O_NAL_MAS, 
 OUT_O_NAL_SUM, OUT_O_FIL_VOL, OUT_O_FIL_MAS, OUT_O_FIL_SUM, OUT_O_LIC_VOL, 
 OUT_O_LIC_MAS, OUT_O_LIC_SUM)
AS 
SELECT /*+ RULE Движение на АЗС  */
      STORE_RN,
      NOMEN_RN,
      SUM(DECODE(A.OPER_ID,'IN',VOLUME,0)) as IN_VOL, -- Всего приход
      SUM(DECODE(A.OPER_ID,'IN',MASSA,0)) as IN_MAS,
      SUM(DECODE(A.OPER_ID,'IN',SUMMA,0)) as IN_SUM,
      SUM(DECODE(A.OPER_ID,'IN_HR',VOLUME,0)) as IN_HR_VOL, -- На хранение
      SUM(DECODE(A.OPER_ID,'IN_HR',MASSA,0)) as IN_HR_MAS,
      SUM(DECODE(A.OPER_ID,'IN_HR',SUMMA,0)) as IN_HR_SUM,
      SUM(DECODE(A.OPER_ID,'IN_I',VOLUME,0)) as IN_I_VOL, -- Внутренний приход
      SUM(DECODE(A.OPER_ID,'IN_I',MASSA,0)) as IN_I_MAS,
      SUM(DECODE(A.OPER_ID,'IN_I',SUMMA,0)) as IN_I_SUM,
      SUM(DECODE(A.OPER_ID,'IN_O',VOLUME,0)) as IN_O_VOL, -- Внешний приход
      SUM(DECODE(A.OPER_ID,'IN_O',MASSA,0)) as IN_O_MAS,
      SUM(DECODE(A.OPER_ID,'IN_O',SUMMA,0)) as IN_O_SUM,
      SUM(DECODE(A.OPER_ID,'IN_TTN',VOLUME,0)) as IN_TTN_VOL, -- Приход на АЗС по ТТН на отпуск в подразделения
      SUM(DECODE(A.OPER_ID,'IN_TTN',MASSA,0)) as IN_TTN_MAS,
      SUM(DECODE(A.OPER_ID,'IN_TTN',SUMMA,0)) as IN_TTN_SUM,
      SUM(DECODE(A.OPER_ID,'OUT',VOLUME,0)) as OUT_VOL, -- Всего расход
      SUM(DECODE(A.OPER_ID,'OUT',MASSA,0)) as OUT_MAS,
      SUM(DECODE(A.OPER_ID,'OUT',SUMMA,0)) as OUT_SUM,
      SUM(DECODE(A.OPER_ID,'OUT_HR',VOLUME,0)) as OUT_HR_VOL, -- С хранения
      SUM(DECODE(A.OPER_ID,'OUT_HR',MASSA,0)) as OUT_HR_MAS,
      SUM(DECODE(A.OPER_ID,'OUT_HR',SUMMA,0)) as OUT_HR_SUM,
      SUM(DECODE(A.OPER_ID,'OUT_I',VOLUME,0)) as OUT_I_VOL, -- Внутренний расход
      SUM(DECODE(A.OPER_ID,'OUT_I',MASSA,0)) as OUT_I_MAS,
      SUM(DECODE(A.OPER_ID,'OUT_I',SUMMA,0)) as OUT_I_SUM,
      SUM(DECODE(A.OPER_ID,'OUT_O',VOLUME,0)) as OUT_O_VOL, -- Всего внешний расход
      SUM(DECODE(A.OPER_ID,'OUT_O',MASSA,0)) as OUT_O_MAS,
      SUM(DECODE(A.OPER_ID,'OUT_O',SUMMA,0)) as OUT_O_SUM,
      SUM(DECODE(A.OPER_ID,'OUT_O_VED',VOLUME,0)) as OUT_O_VED_VOL, -- Заправка по ведомостям
      SUM(DECODE(A.OPER_ID,'OUT_O_VED',MASSA,0)) as OUT_O_VED_MAS,
      SUM(DECODE(A.OPER_ID,'OUT_O_VED',SUMMA,0)) as OUT_O_VED_SUM,
      SUM(DECODE(A.OPER_ID,'OUT_O_BK',VOLUME,0)) as OUT_O_BK_VOL, -- Заправка по банковским картам 
      SUM(DECODE(A.OPER_ID,'OUT_O_BK',MASSA,0)) as OUT_O_BK_MAS,
      SUM(DECODE(A.OPER_ID,'OUT_O_BK',SUMMA,0)) as OUT_O_BK_SUM,
      SUM(DECODE(A.OPER_ID,'OUT_O_KR',VOLUME,0)) as OUT_O_KR_VOL, -- Заправка по системе КРЕДИТ
      SUM(DECODE(A.OPER_ID,'OUT_O_KR',MASSA,0)) as OUT_O_KR_MAS,
      SUM(DECODE(A.OPER_ID,'OUT_O_KR',SUMMA,0)) as OUT_O_KR_SUM,
      SUM(DECODE(A.OPER_ID,'OUT_O_NAL',VOLUME,0)) as OUT_O_NAL_VOL, -- Заправка за наличный расчет
      SUM(DECODE(A.OPER_ID,'OUT_O_NAL',MASSA,0)) as OUT_O_NAL_MAS,
      SUM(DECODE(A.OPER_ID,'OUT_O_NAL',SUMMA,0)) as OUT_O_NAL_SUM,
      SUM(DECODE(A.OPER_ID,'OUT_O_FIL',VOLUME,0)) as OUT_O_FIL_VOL, -- Заправка филиалов
      SUM(DECODE(A.OPER_ID,'OUT_O_FIL',MASSA,0)) as OUT_O_FIL_MAS,
      SUM(DECODE(A.OPER_ID,'OUT_O_FIL',SUMMA,0)) as OUT_O_FIL_SUM,
      SUM(DECODE(A.OPER_ID,'OUT_O_LIC',VOLUME,0)) as OUT_O_LIC_VOL, -- Заправка по картам ЛИКАРД
      SUM(DECODE(A.OPER_ID,'OUT_O_LIC',MASSA,0)) as OUT_O_LIC_MAS,
      SUM(DECODE(A.OPER_ID,'OUT_O_LIC',SUMMA,0)) as OUT_O_LIC_SUM
    FROM 
      V_SNP_DISP_AZS_OPER_PSV A
    GROUP BY STORE_RN,NOMEN_RN;


