--
-- V_SNP_DISP_AZS_OST_GRP_PSV  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_SNP_DISP_AZS_OST_GRP_PSV
(STORE_RN, NOMEN_RN, END_VOLUME, END_MASSA, END_FULL, 
 END_WATER)
AS 
SELECT /*+ RULE Остатки на АЗС по сменным отчетам */
       STORE_RN,
       NOMEN_RN,
       SUM(END_VOLUME_FACT) as END_VOLUME,
       SUM(END_MASSA_FACT) as END_MASSA,
       SUM(END_FULL) as END_FULL,
       SUM(END_WATER) as END_WATER
     FROM PARUS.TB_SNP_STORE_OST_PSV@oracle.world
     WHERE USER_ID=NLS_UPPER(SYS_CONTEXT('USERENV','OS_USER'))
       AND SOURCE_ID=0
     GROUP BY STORE_RN,NOMEN_RN;


