--
-- V_SVED_U_VES  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_SVED_U_VES
(SVED_ID, U_VES)
AS 
SELECT /*+ index(KLS_VALSVED VALSVED_SVED_FK_I)*/ KLS_VALSVED.SVED_ID,NVL(KLS_VALSVED.QUAL,0) AS U_VES
FROM KLS_VALSVED
WHERE KLS_VALSVED.KODIF_ID=1;


