--
-- V_SVED_VALPASP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_SVED_VALPASP
(SVED_ID, U_VES, P_VOD, P_SER, T_VSP)
AS 
SELECT /*+ ordered use_nl(KLS_VALSVED,KLS_KODIF) index(KLS_VALSVED VALSVED_SVED_FK_I)*/
     KLS_VALSVED.SVED_ID,
	 MAX(DECODE(KLS_VALSVED.KODIF_ID,1,TRIM(NVL(KLS_VALSVED.QUAL,0)),0)) as U_VES,
	 MAX(DECODE(NLS_UPPER(KLS_KODIF.FIELD_SVED),'P_VOD',TRIM(NVL(KLS_VALSVED.QUAL,0)),0)) as P_VOD,
	 MAX(DECODE(NLS_UPPER(KLS_KODIF.FIELD_SVED),'P_SER',TRIM(NVL(KLS_VALSVED.QUAL,0)),0)) as P_SER,
	 MAX(DECODE(NLS_UPPER(KLS_KODIF.FIELD_SVED),'T_VSP',TRIM(NVL(KLS_VALSVED.QUAL,0)),0)) as T_VSP
   FROM KLS_VALSVED,KLS_KODIF
   WHERE KLS_VALSVED.KODIF_ID = KLS_KODIF.ID
  GROUP BY KLS_VALSVED.SVED_ID;


