--
-- V_SVED_T_VSP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_SVED_T_VSP
(SVED_ID, T_VSP)
AS 
SELECT /*+ ordered use_nl(KLS_VALSVED,KLS_KODIF) index(KLS_VALSVED VALSVED_SVED_FK_I)*/ KLS_VALSVED.SVED_ID, NVL(KLS_VALSVED.QUAL,0) AS T_VSP
FROM KLS_VALSVED,KLS_KODIF
WHERE KLS_VALSVED.KODIF_ID = KLS_KODIF.ID AND NLS_UPPER(KLS_KODIF.FIELD_SVED) = 'T_VSP';


