--
-- V_TEMPVARI  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_TEMPVARI
(ID, APP_NAME, UNIT_NAME, VARI_TYPE, VARI_NAME, 
 VARI_NUM, VARI_CHAR, VARI_DATE)
AS 
SELECT
TEMPVARI.ID,"APP_NAME","UNIT_NAME","VARI_TYPE","VARI_NAME",
"NUM1","CHAR1","DATE1"
FROM TEMPVARI
WHERE VARI_TYPE IS NOT NULL
  AND TERMINAL_NAME = For_Init.GetCurrTerm
  AND OSUSER_NAME = For_Init.GetCurrUser;


