--
-- V_TEMP_PAYMENTS_PROD  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_TEMP_PAYMENTS_PROD
(PAYMENTS_ID, PROD_ID_NPR)
AS 
SELECT "PAYMENTS_ID","PROD_ID_NPR"
FROM TEMP_PAYMENTS_PROD
WHERE OSUSER_NAME=FOR_INIT.GetCurrUser
  AND TERMINAL_NAME=FOR_INIT.GetCurrTerm;


