--
-- V_TEMPTABLE  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_TEMPTABLE
(ROW_ID, ID, APP_NAME, UNIT_NAME, TABLE_NAME, 
 NUM1, CHAR1, DATE1, NUM2, CHAR2, 
 DATE2, NUM3, CHAR3, DATE3, NUM4, 
 CHAR4, DATE4, NUM5, CHAR5, DATE5, 
 NUM6, CHAR6, DATE6, NUM7, CHAR7, 
 DATE7, NUM8, CHAR8, DATE8, NUM9, 
 CHAR9, DATE9, NUM10, CHAR10, DATE10)
AS 
SELECT
ROWID AS ROW_ID,ID, "APP_NAME","UNIT_NAME","VARI_NAME",
"NUM1","CHAR1","DATE1","NUM2","CHAR2","DATE2","NUM3","CHAR3","DATE3",
"NUM4","CHAR4","DATE4","NUM5","CHAR5","DATE5","NUM6","CHAR6","DATE6",
"NUM7","CHAR7","DATE7","NUM8","CHAR8","DATE8","NUM9","CHAR9","DATE9",
"NUM10","CHAR10","DATE10"
FROM TEMPVARI
WHERE VARI_TYPE IS NULL
  AND TERMINAL_NAME = For_Init.GetCurrTerm
  AND OSUSER_NAME = For_Init.GetCurrUser;


