--
-- V_TEMP_MREESTR_SNP_PARAMS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_TEMP_MREESTR_SNP_PARAMS
(DATE_PLAN, DATETIME_REPORT)
AS 
SELECT TO_DATE(DATE_PLAN,'dd.mm.yyyy'),TO_DATE(TO_CHAR(END_DATE,'dd.mm.yyyy')||' '||SUBSTR(END_TIME,1,5),'dd.mm.yyyy hh24:mi') FROM V_MASTER_REPORTS
WHERE NLS_UPPER(REPORT_FILE)='MREESTRSNP.XLS';


