--
-- V_TEMP_UNP_GARFIK_PARAMS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_TEMP_UNP_GARFIK_PARAMS
(BEGIN_DATE, END_DATE, PROD_ID_NPR, PLAT_ID, DOG_NUMBER, 
 GRP_ID_NPR, FROM_GRP_ID, TO_GRP_ID)
AS 
SELECT
  r.BEGIN_DATE,
  r.END_DATE,
  r.PROD_ID_NPR,
  r.PLAT_ID,
  r.DOG_NUMBER,
  r.GRP_ID_NPR,
  (CASE WHEN GRP_ID_NPR='*' THEN '00000' ELSE GRP_ID_NPR END) as FROM_GRP_ID,
  (CASE WHEN GRP_ID_NPR IN ('10100','*') THEN '99999' ELSE GRP_ID_NPR END) as TO_GRP_ID
FROM V_MASTER_REPORTS r
WHERE NLS_UPPER(TRIM(r.REPORT_FILE))='UNP_GRAFIK_PLAT.XLS';


