--
-- V_TEMP_BILL_KVIT  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_TEMP_BILL_KVIT
(KVIT_ID, NUM_KVIT, TERMINAL_NAME, OSUSER_NAME, NUM_CIST, 
 VES, TARIF, TARIF19, SVED_NUM, SUM_PROD, 
 SUM_AKCIZ, SUM_PROD_NDS, TARIF_NDS, SUM_VOZN11, SUM_VOZN11_NDS, 
 SUM_VOZN12, SUM_VOZN12_NDS, SUM_STRAH, CENA, CENA_OTP, 
 DATE_CENA, DATE_KVIT, PROTO_NUM, PROTO_DATE, CENA_VOZN, 
 TARIF_GUARD, TARIF_GUARD_NDS, NACENKA, NUM_AKT, BILL_POS_ID, 
 NO_AKCIZ, NPR_PRICES_ID, CAT_CEN_ID, ID_NPR, ABBR_NPR)
AS 
SELECT
  TEMP_BILL_KVIT."KVIT_ID",TEMP_BILL_KVIT."NUM_KVIT",TEMP_BILL_KVIT."TERMINAL_NAME",TEMP_BILL_KVIT."OSUSER_NAME",TEMP_BILL_KVIT."NUM_CIST",TEMP_BILL_KVIT."VES",TEMP_BILL_KVIT."TARIF",TEMP_BILL_KVIT."TARIF19",TEMP_BILL_KVIT."SVED_NUM",TEMP_BILL_KVIT."SUM_PROD",TEMP_BILL_KVIT."SUM_AKCIZ",TEMP_BILL_KVIT."SUM_PROD_NDS",TEMP_BILL_KVIT."TARIF_NDS",TEMP_BILL_KVIT."SUM_VOZN11",TEMP_BILL_KVIT."SUM_VOZN11_NDS",TEMP_BILL_KVIT."SUM_VOZN12",TEMP_BILL_KVIT."SUM_VOZN12_NDS",TEMP_BILL_KVIT."SUM_STRAH",TEMP_BILL_KVIT."CENA",TEMP_BILL_KVIT."CENA_OTP",TEMP_BILL_KVIT."DATE_CENA",TEMP_BILL_KVIT."DATE_KVIT",TEMP_BILL_KVIT."PROTO_NUM",TEMP_BILL_KVIT."PROTO_DATE",TEMP_BILL_KVIT."CENA_VOZN",TEMP_BILL_KVIT."TARIF_GUARD",TEMP_BILL_KVIT."TARIF_GUARD_NDS",TEMP_BILL_KVIT."NACENKA",TEMP_BILL_KVIT."NUM_AKT",TEMP_BILL_KVIT."BILL_POS_ID",TEMP_BILL_KVIT."NO_AKCIZ",TEMP_BILL_KVIT."NPR_PRICES_ID",TEMP_BILL_KVIT."CAT_CEN_ID",
  (SELECT prod_id_npr FROM kvit WHERE kvit.id=temp_bill_kvit.kvit_id) AS id_npr,
  (SELECT kls_prod.abbr_npr FROM kvit,kls_prod WHERE kvit.id=temp_bill_kvit.kvit_id AND kvit.prod_id_npr=kls_prod.id_npr) AS abbr_npr
  FROM TEMP_BILL_KVIT
  WHERE TERMINAL_NAME = For_Init.GetCurrTerm
    AND OSUSER_NAME = For_init.GetCurrUser;


