--
-- V_TEMP_REESTR_PARAMS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_TEMP_REESTR_PARAMS
(DATE_PLAN, DATE_REE, DATETIME_REPORT, GRAFIK_FROM, GRAFIK_TO, 
 USE_GRAFIK)
AS 
SELECT
  TO_DATE(DATE_PLAN,'dd.mm.yyyy') as DATE_PLAN,
  NVL(For_Temp.GET_AS_DATE('DATE_REE', 'MASTER', 'REESTRORA.XLS'),TRUNC(SYSDATE)+1) as DATE_REE,
  TO_DATE(TO_CHAR(END_DATE,'dd.mm.yyyy')||' '||SUBSTR(END_TIME,1,5),'dd.mm.yyyy hh24:mi') as DATETIME_REPORT,
  NVL(For_Temp.GET_AS_DATE('GRAFIK_FROM', 'MASTER', 'REESTRORA.XLS'),TRUNC(SYSDATE,'MONTH')) as GRAFIK_FROM,
  NVL(For_Temp.GET_AS_DATE('GRAFIK_TO', 'MASTER', 'REESTRORA.XLS'),TRUNC(SYSDATE)+1) as GRAFIK_TO,
  NVL(For_Temp.GET_AS_NUM('USE_GRAFIK', 'MASTER', 'REESTRORA.XLS'),0) as USE_GRAFIK
FROM V_MASTER_REPORTS
WHERE NLS_UPPER(REPORT_FILE)='REESTRORA.XLS';


