--
-- V_TEMP_VYP_GD_PARAMS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_TEMP_VYP_GD_PARAMS
(BEGIN_DATE, END_DATE)
AS 
SELECT BEGIN_DATE,END_DATE FROM V_MASTER_REPORTS
WHERE NLS_UPPER(REPORT_FILE)='GD_VYP.XLS';


