--
-- V_TEMP_BILL_POS_SUM  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_TEMP_BILL_POS_SUM
(TERMINAL_NAME, OSUSER_NAME, NOM_DOK, BILL_POS_ID, VES, 
 CENA_BN, CENA, SUMMA_BN, SUMMA_AKCIZ, SUMMA_NDS20, 
 SUMMA, PROD_ID_NPR)
AS 
SELECT
TERMINAL_NAME, OSUSER_NAME, NOM_DOK, BILL_POS_ID, SUM(VES) AS ves, 
 min(CENA_BN) AS cena_bn, min(CENA) as cena, SUM(SUMMA_BN) AS summa_bn, sum(SUMMA_AKCIZ) AS SUMMA_AKCIZ, sum(SUMMA_NDS20) as SUMMA_NDS20, 
 sum(SUMMA) as summa, min(PROD_ID_NPR) AS PROD_ID_NPR FROM TEMP_BILL_POS
WHERE TERMINAL_NAME = For_Init.GetCurrTerm
  AND OSUSER_NAME = For_init.GetCurrUser
GROUP BY
TERMINAL_NAME, OSUSER_NAME, NOM_DOK, BILL_POS_ID;


