--
-- V_TEMP_BILL_KVIT_POSSIBLE  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_TEMP_BILL_KVIT_POSSIBLE
(KVIT_ID, NUM_KVIT, TERMINAL_NAME, OSUSER_NAME, NUM_CIST, 
 VES, TARIF, TARIF19, SVED_NUM, SUM_PROD, 
 SUM_AKCIZ, SUM_PROD_NDS, TARIF_NDS, SUM_VOZN11, SUM_VOZN11_NDS, 
 SUM_VOZN12, SUM_VOZN12_NDS, SUM_STRAH, CENA, CENA_OTP, 
 DATE_CENA, DATE_KVIT, PROTO_NUM, PROTO_DATE, CENA_VOZN, 
 TARIF_GUARD, TARIF_GUARD_NDS, NACENKA, NUM_AKT, BILL_POS_ID, 
 NO_AKCIZ, NPR_PRICES_ID, CAT_CEN_ID)
AS 
SELECT
"KVIT_ID","NUM_KVIT","TERMINAL_NAME","OSUSER_NAME","NUM_CIST","VES","TARIF","TARIF19","SVED_NUM","SUM_PROD","SUM_AKCIZ","SUM_PROD_NDS","TARIF_NDS","SUM_VOZN11","SUM_VOZN11_NDS","SUM_VOZN12","SUM_VOZN12_NDS","SUM_STRAH","CENA","CENA_OTP","DATE_CENA","DATE_KVIT","PROTO_NUM","PROTO_DATE","CENA_VOZN","TARIF_GUARD","TARIF_GUARD_NDS","NACENKA","NUM_AKT","BILL_POS_ID","NO_AKCIZ","NPR_PRICES_ID","CAT_CEN_ID" FROM TEMP_BILL_KVIT_POSSIBLE
WHERE TERMINAL_NAME = For_Init.GetCurrTerm
  AND OSUSER_NAME = For_init.GetCurrUser;


