--
-- V_TEMP_BILL_KVIT_REKVIZITS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_TEMP_BILL_KVIT_REKVIZITS
(DOG_NUMBER, DOG_DATE, PLAT_NAME, POLUCH_NAME, POTR_NAME, 
 STAN_NAME, ID_NPR, LONG_NAME_NPR, CAT_CEN_ID, USL_NUMBER, 
 CAT_CEN_NAME, NOM_ZD)
AS 
SELECT /*+ FIRST_ROWS(1) */
KLS_DOG.DOG_NUMBER,
KLS_DOG.DOG_DATE,
plat.PREDPR_NAME AS plat_name,
pol.PREDPR_NAME AS poluch_name,
potr.PREDPR_NAME AS potr_name,
KLS_STAN.STAN_NAME || ' (' || TO_CHAR(KLS_STAN.RAST) || 'κμ)' AS stan_name,
KLS_PROD.ID_NPR,
KLS_PROD.LONG_NAME_NPR,
USL_DOG.CAT_CEN_ID,
USL_DOG.USL_NUMBER,
KLS_CAT_CEN.CAT_CEN_NAME,
MONTH.nom_zd
FROM KLS_DOG,USL_DOG,MONTH,TEMP_BILL_KVIT,KVIT,KLS_PREDPR plat,KLS_PREDPR pol,KLS_PREDPR potr,KLS_STAN,KLS_PROD,KLS_CAT_CEN
WHERE KLS_DOG.ID=DECODE(MONTH.POKUP_DOG_ID,NULL,MONTH.DOG_ID,MONTH.POKUP_DOG_ID)
  AND MONTH.NOM_ZD=KVIT.NOM_ZD
  AND KVIT.ID=TEMP_BILL_KVIT.KVIT_ID
  AND MONTH.POLUCH_ID=pol.id
  AND MONTH.POTREB_ID=potr.id
  AND KLS_DOG.PREDPR_ID=plat.id
  AND MONTH.STAN_ID=KLS_STAN.ID
  AND KVIT.PROD_ID_NPR=KLS_PROD.ID_NPR
  AND USL_DOG.DOG_ID=DECODE(MONTH.POKUP_DOG_ID,NULL,MONTH.DOG_ID,MONTH.POKUP_DOG_ID)
  AND USL_DOG.USL_NUMBER=DECODE(MONTH.POKUP_DOG_ID,NULL,MONTH.USL_NUMBER,MONTH.POKUP_USL_NUMBER)
  AND USL_DOG.CAT_CEN_ID=KLS_CAT_CEN.ID
  AND TERMINAL_NAME = For_Init.GetCurrTerm
  AND OSUSER_NAME = For_Init.GetCurrUser;


