--
-- V_TRIADA_RES  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_TRIADA_RES
(GR_PROD, PROD, PLAT, VES, TRIADA1_FACT, 
 TRIADA2_FACT, TRIADA3_FACT, TRIADA4_FACT, TRIADA5_FACT, TRIADA6_FACT, 
 TRIADA7_FACT, TRIADA8_FACT, TRIADA9_FACT, TRIADA1_GRAF, TRIADA2_GRAF, 
 TRIADA3_GRAF, TRIADA4_GRAF, TRIADA5_GRAF, TRIADA6_GRAF, TRIADA7_GRAF, 
 TRIADA8_GRAF, TRIADA9_GRAF)
AS 
SELECT PL.GR_PROD,
	  PL.PROD,
	  PL.PLAT,
	  PL.VES,
	  (SELECT sum(ves_fakt)  FROM V_TRIADA_RAZNAR WHERE TRIADA=1 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='fact' group by prod,plat) AS TRIADA1_FACT,
	  (SELECT sum(ves_fakt)  FROM V_TRIADA_RAZNAR WHERE TRIADA=2 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='fact' group by prod,plat) AS TRIADA2_FACT,
	  (SELECT sum(ves_fakt)  FROM V_TRIADA_RAZNAR WHERE TRIADA=3 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='fact' group by prod,plat) AS TRIADA3_FACT,
	  (SELECT sum(ves_fakt)  FROM V_TRIADA_RAZNAR WHERE TRIADA=4 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='fact' group by prod,plat) AS TRIADA4_FACT,
	  (SELECT sum(ves_fakt)  FROM V_TRIADA_RAZNAR WHERE TRIADA=5 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='fact' group by prod,plat) AS TRIADA5_FACT,
	  (SELECT sum(ves_fakt)  FROM V_TRIADA_RAZNAR WHERE TRIADA=6 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='fact' group by prod,plat) AS TRIADA6_FACT,
	  (SELECT sum(ves_fakt)  FROM V_TRIADA_RAZNAR WHERE TRIADA=7 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='fact' group by prod,plat) AS TRIADA7_FACT,
	  (SELECT sum(ves_fakt)  FROM V_TRIADA_RAZNAR WHERE TRIADA=8 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='fact' group by prod,plat) AS TRIADA8_FACT,
	  (SELECT sum(ves_fakt)  FROM V_TRIADA_RAZNAR WHERE TRIADA=9 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='fact' group by prod,plat) AS TRIADA9_FACT,
	  (SELECT sum(ves_plan)  FROM V_TRIADA_RAZNAR WHERE TRIADA=1 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='gu12' group by prod,plat) AS TRIADA1_GRAF,
	  (SELECT sum(ves_plan)  FROM V_TRIADA_RAZNAR WHERE TRIADA=2 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='gu12' group by prod,plat) AS TRIADA2_GRAF,
	  (SELECT sum(ves_plan)  FROM V_TRIADA_RAZNAR WHERE TRIADA=3 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='gu12' group by prod,plat) AS TRIADA3_GRAF,
	  (SELECT sum(ves_plan)  FROM V_TRIADA_RAZNAR WHERE TRIADA=4 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='gu12' group by prod,plat) AS TRIADA4_GRAF,
	  (SELECT sum(ves_plan)  FROM V_TRIADA_RAZNAR WHERE TRIADA=5 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='gu12' group by prod,plat) AS TRIADA5_GRAF,
	  (SELECT sum(ves_plan)  FROM V_TRIADA_RAZNAR WHERE TRIADA=6 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='gu12' group by prod,plat) AS TRIADA6_GRAF,
	  (SELECT sum(ves_plan)  FROM V_TRIADA_RAZNAR WHERE TRIADA=7 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='gu12' group by prod,plat) AS TRIADA7_GRAF,
	  (SELECT sum(ves_plan)  FROM V_TRIADA_RAZNAR WHERE TRIADA=8 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='gu12' group by prod,plat) AS TRIADA8_GRAF,
	  (SELECT sum(ves_plan)  FROM V_TRIADA_RAZNAR WHERE TRIADA=9 AND PROD=PL.PROD AND PLAT=PL.PLAT AND VID_DOC='gu12' group by prod,plat) AS TRIADA9_GRAF
FROM V_TRIADA_PLAN PL;


