--
-- V_UNP_REP_PREDYAV  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_UNP_REP_PREDYAV
(DATE_VYP_SF, DATE_BUXG, NOM_SF, OLD_NOM_SF, DATE_KVIT, 
 PROD_ID_NPR, VES_BRUTTO, NUM_KVIT, SUM_PROD, SUM_PROD_NDS, 
 TARIF, TARIF_NDS, SUM_STRAH, TARIF_GUARD, TARIF_GUARD_NDS, 
 NAME_NPR, ID_GROUP_NPR, GROUP_NPR_NAME, POLUCH_ID, POLUCH_NAME, 
 STAN_ID, STAN_NAME, NAZN_OTG_ID, SOBSTV_ID, SOBSTV_NAME, 
 N_DOG, DOG_ID, LOAD_TYPE_ID, LOAD_TYPE_NAME, PLAT_ID, 
 PLAT_NAME, DATE_OTGR, CENA_BN, CENA, SUM_VOZN11, 
 SUM_VOZN11_NDS, SUM_VOZN12, SUM_VOZN12_NDS, CAT_CEN_ID, USL_BEGIN_DATE, 
 USL_END_DATE, ID_KIND_NPR, SBOR, SHTRAF, KOL_DN, 
 DATE_PLAT, SUMMA_DOK, NDS_DOK, REGION_NAME)
AS 
SELECT /*+ RULE */
B.DATE_VYP_SF
,B.DATE_BUXG
,B.NOM_SF
,B.OLD_NOM_SF
,B.DATE_KVIT
,(CASE
      WHEN B.PROD_ID_NPR=10080 THEN BP.PROD_ID_NPR
   ELSE B.PROD_ID_NPR
  END) AS PROD_ID_NPR
,(CASE
     WHEN BP.BILL_POS_ID<10 THEN BP.VES
   ELSE 0
  END) AS VES_BRUTTO
,0 AS NUM_KVIT
,(CASE
     WHEN BP.BILL_POS_ID<10 THEN BP.SUMMA_BN
   ELSE 0
  END) AS SUM_PROD
,(CASE
     WHEN BP.BILL_POS_ID<10 THEN BP.SUMMA-BP.SUMMA_BN
   ELSE 0
  END) AS SUM_PROD_NDS
,(CASE
     WHEN BP.BILL_POS_ID=10 THEN BP.SUMMA_BN
   ELSE 0
  END) AS TARIF
,(CASE
     WHEN BP.BILL_POS_ID=10 THEN BP.SUMMA_NDS20
   ELSE 0
  END) AS TARIF_NDS
,(CASE
     WHEN BP.BILL_POS_ID=20 THEN BP.SUMMA_BN
   ELSE 0
  END) AS SUM_STRAH
,(CASE
     WHEN BP.BILL_POS_ID=13 THEN BP.SUMMA_BN
   ELSE 0
  END) AS TARIF_GUARD
,(CASE
     WHEN BP.BILL_POS_ID=13 THEN BP.SUMMA_NDS20
   ELSE 0
  END) AS TARIF_GUARD_NDS
--,0 AS SVED_NUM
,P1.NAME_NPR
,P1.ID_GROUP_NPR
,P2.NAME_NPR AS GROUP_NPR_NAME
,NVL(M.POTREB_ID,0) AS POLUCH_ID
,NVL(PR2.PREDPR_NAME,' ') AS POLUCH_NAME
,NVL(M.STAN_ID,0) AS STAN_ID
,NVL(S.STAN_NAME,' ') AS STAN_NAME
,M.NAZN_OTG_ID
,M.NPR_SOBSTV_ID AS SOBSTV_ID
,PR3.PREDPR_NAME AS SOBSTV_NAME
,D.SHORT_NUMBER AS N_DOG
,B.DOG_ID
,LT.ID AS LOAD_TYPE_ID
,LT.TYPE_OTGR_NAME AS LOAD_TYPE_NAME
--,0 AS OWN_VAG_ID
--,'' AS SOBVAG_NAME
,PR4.ID AS PLAT_ID
,PR4.PREDPR_NAME AS PLAT_NAME
--,0 AS SUM_VOZ
,B.DATE_KVIT AS DATE_OTGR
--,0 AS TARIF19
,BP.CENA_BN
,BP.CENA
,(CASE
     WHEN BP.BILL_POS_ID=11 AND P1.ID_KIND_NPR<>10050 AND P1.ID_KIND_NPR<>10060 THEN BP.SUMMA_BN
   ELSE 0
  END) AS SUM_VOZN11
,(CASE
     WHEN BP.BILL_POS_ID=11 AND P1.ID_KIND_NPR<>10050 AND P1.ID_KIND_NPR<>10060 THEN BP.SUMMA_NDS20
   ELSE 0
  END) AS SUM_VOZN11_NDS
,(CASE
     WHEN BP.BILL_POS_ID=12 THEN BP.SUMMA_BN
   ELSE 0
  END) AS SUM_VOZN12
,(CASE
     WHEN BP.BILL_POS_ID=12 THEN BP.SUMMA_NDS20
   ELSE 0
  END) AS SUM_VOZN12_NDS
,UD.CAT_CEN_ID
,UD.USL_BEGIN_DATE
,UD.USL_END_DATE
,P1.ID_KIND_NPR
,(CASE
     WHEN P1.ID_KIND_NPR=10050 THEN B.SUMMA_DOK
   ELSE 0
  END) AS SBOR
,(CASE
     WHEN P1.ID_KIND_NPR=10060 THEN B.SUMMA_DOK
   ELSE 0
  END) AS SHTRAF
,B.KOL_DN
,B.DATE_PLAT
,B.SUMMA_DOK
,B.NDS_DOK
,R.REGION_NAME
FROM BILLS B
,BILL_POS BP
,MONTH M
,KLS_PREDPR PR2 --получатель
,KLS_PREDPR PR3 --СОБСТВЕННИК ПРОД
,KLS_PREDPR PR4 --плательщик
,KLS_PROD P1
,KLS_PROD P2
,KLS_DOG D
,KLS_STAN S
,KLS_VID_OTGR VO
,KLS_LOAD_TYPE LT
,USL_DOG UD
,KLS_REGION R
WHERE
B.NOM_DOK=BP.NOM_DOK
AND B.NOM_ZD=M.NOM_ZD(+)
AND M.POTREB_ID=PR2.ID(+)
AND D.PREDPR_ID=PR4.ID(+)
AND (CASE WHEN B.PROD_ID_NPR=10080 THEN BP.PROD_ID_NPR
   ELSE B.PROD_ID_NPR
  END)=P1.ID_NPR
AND B.DOG_ID=D.ID(+)
AND P1.ID_GROUP_NPR=P2.ID_NPR
AND M.STAN_ID=S.ID(+)
AND M.NPR_SOBSTV_ID=PR3.ID(+)
AND M.LOAD_ABBR=VO.LOAD_ABBR(+)
AND (CASE WHEN B.PROD_ID_NPR=10080 THEN 1
   ELSE NVL(VO.LOAD_TYPE_ID,0)
  END)=LT.ID
AND B.DOG_ID=UD.DOG_ID(+)
AND B.USL_NUMBER=UD.USL_NUMBER
AND S.REGION_ID=R.ID(+)
--and B.PROD_ID_NPR=10080
;


