--
-- V_USER_BILLS  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_USER_BILLS
(NOM_DOK, BILL_POS_ID, NOM_SF, DATE_VYP_SF, DATE_KVIT, 
 DATE_BUXG, SUMMA_DOK, NDS_DOK, GSM_DOK, AKCIZ_DOK, 
 PRIM, FIO_ISPOL, KOL_DN, OLD_NOM_DOK, NOM_ZD, 
 OWNER_ID, DOG_ID, USL_NUMBER, PROD_ID_NPR, PROD_SUM, 
 PROD_NDS, PROD_GSM, PROD_AKCIZ, DATE_MOS, NPO_SF, 
 OLD_NOM_SF, IS_AGENT, NUM_5_DAY, LUK_DOG_ID, LUK_USL_NUMBER, 
 LUK_SUMMA_DOK, LUK_NDS_DOK, SNP_DOG_ID, SNP_USL_NUMBER, LUK_KOL_DN, 
 SNP_KOL_DN, NAZN_OTG_ID, KORR_5_DAY, PROTO_NUM, PROTO_DATE, 
 NO_AKCIZ, KORR_PROD, DATE_PLAT)
AS 
SELECT /*+  */
  A.NOM_DOK,
  NVL(B.BILL_POS_ID,0) as BILL_POS_ID,
  A.NOM_SF, A.DATE_VYP_SF, A.DATE_KVIT, A.DATE_BUXG,
  NVL(B.SUMMA_DOK,A.SUMMA_DOK) as SUMMA_DOK,
  NVL(B.NDS_DOK,A.NDS_DOK) as NDS_DOK,
  NVL(B.GSM_DOK,A.GSM_DOK) as GSM_DOK,
  NVL(B.AKCIZ_DOK,A.AKCIZ_DOK) as AKCIZ_DOK,
  A.PRIM, A.FIO_ISPOL, A.KOL_DN, A.OLD_NOM_DOK, A.NOM_ZD, A.OWNER_ID, A.DOG_ID, A.USL_NUMBER,
  NVL(B.PROD_ID_NPR,A.PROD_ID_NPR) as PROD_ID_NPR,
  NVL(B.PROD_SUM,A.PROD_SUM) as PROD_SUM,
  NVL(B.PROD_NDS,A.PROD_NDS) as PROD_NDS,
  NVL(B.PROD_GSM,A.PROD_GSM) as PROD_GSM,
  NVL(B.PROD_AKCIZ,A.PROD_AKCIZ) as PROD_AKCIZ,
  A.DATE_MOS, A.NPO_SF, A.OLD_NOM_SF, A.IS_AGENT, A.NUM_5_DAY, A.LUK_DOG_ID, A.LUK_USL_NUMBER,
  NVL(B.LUK_SUMMA_DOK,A.LUK_SUMMA_DOK) as LUK_SUMMA_DOK,
  NVL(B.LUK_NDS_DOK,A.LUK_NDS_DOK) as LUK_NDS_DOK,
  A.SNP_DOG_ID, A.SNP_USL_NUMBER, A.LUK_KOL_DN, A.SNP_KOL_DN, A.NAZN_OTG_ID, A.KORR_5_DAY, A.PROTO_NUM, A.PROTO_DATE,
  A.NO_AKCIZ, A.KORR_PROD, A.DATE_PLAT
FROM BILLS A,
(
 SELECT /*+  —˜ÂÚ‡ À” Œ…ÀÛ Ò 2005 „Ó‰‡ */
  AA.NOM_DOK, BB.BILL_POS_ID,
  BB.SUMMA as SUMMA_DOK, BB.SUMMA_NDS20 as NDS_DOK, BB.SUMMA_GSM25 as GSM_DOK, BB.SUMMA_AKCIZ as AKCIZ_DOK,
  BB.PROD_ID_NPR, BB.SUMMA as PROD_SUM, BB.SUMMA_NDS20 as PROD_NDS, BB.SUMMA_GSM25 as PROD_GSM, BB.SUMMA_AKCIZ as PROD_AKCIZ,
  BB.SUMMA as LUK_SUMMA_DOK, BB.SUMMA_NDS20 as LUK_NDS_DOK
 FROM BILLS AA,BILL_POS BB
 WHERE AA.NOM_DOK=BB.NOM_DOK
   AND AA.PROD_ID_NPR='10080'
) B
WHERE A.NOM_DOK=B.NOM_DOK(+);


