--
-- V_VALPASP_UNP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_VALPASP_UNP
(PASP_ID, KODIF_ID, NORMTU, NORMTU_NUM, QUAL, 
 QUAL_NUM, NPP, SORTBY, NAME, DISPLAY_NAME, 
 FIELD_SVED, FIELD_TYPE, FIELD_LEN, FIELD_DEC)
AS 
SELECT /*+ RULE */
vv.PASP_ID,
vv.kodif_id,
vv.normtu,
vv.normtu_num,
vv.QUAL,
vv.QUAL_NUM,
vv.NPP,
vv.SORTBY,
vv.NAME,
DECODE(vv.NPP,0,'    ',TO_CHAR(vv.NPP)||'. ')||vv.NAME as DISPLAY_NAME,
vv.FIELD_SVED,
vv.FIELD_TYPE,
vv.FIELD_LEN,
vv.FIELD_DEC
FROM
(
SELECT
  v.PASP_ID,
  v.KODIF_ID,
  MAX(v.NPP) as NPP,
  MAX(v.SORTBY) as SORTBY,
  v.NAME,
  MAX(v.NORMTU) as NORMTU,
  MAX(v.NORMTU_NUM) as NORMTU_NUM,
  MAX(SUBSTR(v.QUAL,1,20)) as QUAL,
  MAX(v.QUAL_NUM) as QUAL_NUM,
  MAX(NLS_UPPER(v.FIELD_SVED)) as FIELD_SVED,
  MAX(NLS_UPPER(v.FIELD_TYPE)) as FIELD_TYPE,
  MAX(NLS_UPPER(v.FIELD_LEN)) as FIELD_LEN,
  MAX(NLS_UPPER(v.FIELD_DEC)) as FIELD_DEC
FROM
(
SELECT /*+ RULE */
  NULL as NPP,
  0 as SORTBY,
  a.ID_PASPORT as PASP_ID,
  NVL(k.ID,0) as KODIF_ID,
  NVL(k.NAME,sp.NAME_POKAZATEL) as NAME,
  NULL as NORMTU,
  0 as NORMTU_NUM,
  (CASE
     WHEN a.FACT_PASP IS NOT NULL THEN ORA_NUM_TO_CHAR(a.FACT_PASP)
	 ELSE a.TEXT_VAL
   END) as QUAL,
  (CASE
     WHEN a.FACT_PASP IS NOT NULL THEN a.FACT_PASP
     ELSE ORA_CHAR_TO_NUM(a.TEXT_VAL)
   END) as QUAL_NUM,
  k.FIELD_TYPE,
  k.FIELD_LEN,
  k.FIELD_DEC,
  k.FIELD_SVED
FROM UNP_FACT_PASP a, KLS_KODIF_PASP_UNP i, kls_kodif k, UNP_SPRAV_POKAZATEL sp
WHERE /*a.ID_PASPORT=TO_NUMBER(:PASP_ID)
  AND */a.KOD_POKAZATEL=sp.KOD_POKAZATEL
  AND a.KOD_POKAZATEL=i.KOD_POKAZATEL(+)
  and i.KODIF_ID=k.id(+)
UNION ALL
SELECT /*+ RULE */
  NULL as NPP,
  -1 as SORTBY,
  a.ID_PASPORT as PASP_ID,
  kk.ID as KODIF_ID,
  kk.NAME as NAME,
  NULL as NORMTU,
  0 as NORMTU_NUM,
  (CASE
     WHEN a.FACT_PASP IS NOT NULL THEN ORA_NUM_TO_CHAR(a.FACT_PASP/1000)
	 ELSE ORA_NUM_TO_CHAR(ORA_CHAR_TO_NUM(a.TEXT_VAL)/1000)
   END) as QUAL,
  (CASE
     WHEN a.FACT_PASP IS NOT NULL THEN a.FACT_PASP/1000
	 ELSE ORA_CHAR_TO_NUM(a.TEXT_VAL)/1000
   END) as QUAL_NUM,
  kk.FIELD_TYPE,
  kk.FIELD_LEN,
  kk.FIELD_DEC,
  kk.FIELD_SVED
FROM UNP_FACT_PASP a, KLS_KODIF_PASP_UNP i, kls_kodif k, kls_kodif kk, UNP_SPRAV_POKAZATEL sp
WHERE /*a.ID_PASPORT=TO_NUMBER(:PASP_ID)
  AND */a.KOD_POKAZATEL=sp.KOD_POKAZATEL
  and 1=kk.id
  AND a.KOD_POKAZATEL=i.KOD_POKAZATEL
  and i.KODIF_ID=k.id
  and k.FIELD_SVED='PL20_KG'

UNION ALL
SELECT /*+ RULE */
  NULL as NPP,
  -2 as SORTBY,
  a.ID_PASPORT as PASP_ID,
  kk.ID as KODIF_ID,
  kk.NAME as NAME,
  NULL as NORMTU,
  0 as NORMTU_NUM,
  (CASE
     WHEN a.FACT_PASP IS NOT NULL THEN ORA_NUM_TO_CHAR(a.FACT_PASP/1000)
	 ELSE ORA_NUM_TO_CHAR(ORA_CHAR_TO_NUM(a.TEXT_VAL)/1000)
   END) as QUAL,
  (CASE
     WHEN a.FACT_PASP IS NOT NULL THEN a.FACT_PASP/1000
	 ELSE ORA_CHAR_TO_NUM(a.TEXT_VAL)/1000
   END) as QUAL_NUM,
  kk.FIELD_TYPE,
  kk.FIELD_LEN,
  kk.FIELD_DEC,
  kk.FIELD_SVED
FROM UNP_FACT_PASP a, KLS_KODIF_PASP_UNP i, kls_kodif k, kls_kodif kk, UNP_SPRAV_POKAZATEL sp
WHERE /*a.ID_PASPORT=TO_NUMBER(:PASP_ID)
  AND */a.KOD_POKAZATEL=sp.KOD_POKAZATEL
  and 602=kk.id
  AND a.KOD_POKAZATEL=i.KOD_POKAZATEL
  and i.KODIF_ID=k.id
  and k.FIELD_SVED='PL15_KG'
UNION ALL
SELECT
  b.NOMER_PP as NPP,
  b.NOMER_PP*100+b.NOMER_INSIDE as SORTBY,
  p.ID_PASPORT as PASP_ID,
  k.ID as KODIF_ID,
  k.NAME as NAME,
  b.NORM_POKAZATEL as NORMTU,
  ORA_CHAR_TO_NUM(b.NORM_POKAZATEL) as NORMTU_NUM,
  NULL as QUAL,
  0 as QUAL_NUM,
  k.FIELD_TYPE,
  k.FIELD_LEN,
  k.FIELD_DEC,
  k.FIELD_SVED
FROM UNP_PASPORT p, UNP_NORM_PASP b, KLS_KODIF_PASP_UNP i, kls_kodif k
WHERE /*p.ID_PASPORT=TO_NUMBER(:PASP_ID)
  AND */p.KOD_OIL_PRODUCT=b.KOD_OIL_PRODUCT
  AND b.KOD_POKAZATEL=i.KOD_POKAZATEL
  and i.KODIF_ID=k.id
) v
GROUP BY
  v.PASP_ID,
  v.KODIF_ID,
  v.NAME
) vv;


