--
-- V_VALPASP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_VALPASP
(PASP_ID, KODIF_ID, NORMTU, NORMTU_NUM, QUAL, 
 QUAL_NUM, NPP, SORTBY, NAME, DISPLAY_NAME, 
 FIELD_SVED, FIELD_TYPE, FIELD_LEN, FIELD_DEC)
AS 
SELECT /*+ RULE */
vv.PASP_ID,
vv.kodif_id,
vv.normtu,
vv.normtu_num,
vv.QUAL,
vv.QUAL_NUM,
vv.NPP,
vv.SORTBY,
vv.NAME,
DECODE(vv.NPP,0,'    ',TO_CHAR(vv.NPP)||'. ')||vv.NAME as DISPLAY_NAME,
vv.FIELD_SVED,
vv.FIELD_TYPE,
vv.FIELD_LEN,
vv.FIELD_DEC
FROM
(
SELECT
  v.PASP_ID,
  v.KODIF_ID,
  MAX(v.NPP) as NPP,
  MAX(v.SORTBY) as SORTBY,
  v.NAME,
  MAX(v.NORMTU) as NORMTU,
  MAX(v.NORMTU_NUM) as NORMTU_NUM,
  MAX(v.QUAL) as QUAL,
  MAX(v.QUAL_NUM) as QUAL_NUM,
  MAX(NLS_UPPER(v.FIELD_SVED)) as FIELD_SVED,
  MAX(NLS_UPPER(v.FIELD_TYPE)) as FIELD_TYPE,
  MAX(NLS_UPPER(v.FIELD_LEN)) as FIELD_LEN,
  MAX(NLS_UPPER(v.FIELD_DEC)) as FIELD_DEC
FROM
(
SELECT /*+ RULE */
  NULL as NPP,
  0 as SORTBY,
  a.PASP_ID,
  k.ID as KODIF_ID,
  k.NAME as NAME,
  NULL as NORMTU,
  0 as NORMTU_NUM,
  a.QUAL,
  ORA_CHAR_TO_NUM(a.QUAL) as QUAL_NUM,
  k.FIELD_TYPE,
  k.FIELD_LEN,
  k.FIELD_DEC,
  k.FIELD_SVED
FROM KLS_VALPASP a, kls_kodif k
WHERE a.KODIF_ID=k.id
UNION ALL
SELECT
  b.NPP,
  b.SORTBY,
  p.ID as PASP_ID,
  k.ID as KODIF_ID,
  k.NAME as NAME,
  b.NORMTU,
  ORA_CHAR_TO_NUM(b.NORMTU) as NORMTU_NUM,
  NULL as QUAL,
  0 as QUAL_NUM,
  k.FIELD_TYPE,
  k.FIELD_LEN,
  k.FIELD_DEC,
  k.FIELD_SVED
FROM KLS_PASP p, KLS_TABLPOK b, kls_kodif k
WHERE p.PROD_ID_NPR=b.PROD_ID_NPR
  and b.KODIF_ID=k.id
) v
GROUP BY
  v.PASP_ID,
  v.KODIF_ID,
  v.NAME
) vv;


