/* This object may not be sorted properly in the script due to cirular references. */
--
-- V_VBAK_LAST_POSNR  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_VBAK_LAST_POSNR
(VBAK_VBELN, VBAP_MATNR, VBAP_KWMENG, VBAP_KBMENG)
AS 
SELECT R3_VBAK.VBELN, B.VBAP_MATNR, B.VBAP_KWMENG, B.VBAP_KBMENG
FROM R3_VBAK,
   (SELECT R3_OD.VBAK_VBELN, R3_OD.VBAP_MATNR, POS.VBAP_KWMENG, POS.VBAP_KBMENG
    FROM R3_OD,
      (SELECT VBAK_VBELN,
         MAX(VBAP_POSNR) AS VBAP_POSNR,
         SUM(VBAP_KWMENG) AS VBAP_KWMENG,
         SUM(VBAP_KBMENG) AS VBAP_KBMENG
       FROM R3_OD WHERE V_TJ30_TXT04='0010'
       GROUP BY VBAK_VBELN) POS
    WHERE R3_OD.VBAK_VBELN=POS.VBAK_VBELN
      AND R3_OD.VBAP_POSNR=POS.VBAP_POSNR) B
WHERE R3_VBAK.VBELN=B.VBAK_VBELN(+);


