--
-- V_VED_OSMOTR_LAST_GRUZ  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_VED_OSMOTR_LAST_GRUZ
(REPORT_TIME, NUM_CIST, VED_ID, LAST_GRUZ)
AS 
SELECT  
SYSDATE as REPORT_TIME,
a.NUM_CIST, a.VED_ID,
FOR_CIST.LAST_GRUZ(b.VED_DATE,a.NUM_CIST,b.MESTO_ID,b.LOAD_TYPE_ID) as LAST_GRUZ
FROM VED_OSMOTR_ROW a, VED_OSMOTR b
WHERE /*a.VED_ID=FOR_TEMP.GET_AS_NUM('VED_ID','MASTER','Sved_gd.rpt')
  AND */a.VED_ID=b.ID
ORDER BY a.pod_pos;


