--
-- V_VED_POD_PRINT  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_VED_POD_PRINT
(POD_NUM, POD_DATE, TECH_TIME, GOTOV_TIME, BEG_NALIV_TIME, 
 END_NALIV_TIME, VETKA_NAME, POD_POS, PROD_NAME, NUM_CIST, 
 KALIBR_ID, VES_CIST, CAPACITY, VAGOWNER_NAME, VZLIV, 
 PLOMBA1, PLOMBA2, ROSINSPL1, ROSINSPL2)
AS 
SELECT
  a.POD_NUM,
  a.POD_DATE,
  a.TECH_TIME,
  a.GOTOV_TIME,
  a.BEG_NALIV_TIME,
  a.END_NALIV_TIME,
  KLS_VETKA_OTP.VETKA_NAME as VETKA_NAME,
  b.POD_POS,
  DECODE(b.PROD_ID_NPR,'',b.RAZMET_FACT,KLS_PROD.ABBR_NPR) as PROD_NAME,
  b.NUM_CIST,
  b.KALIBR_ID,
  DECODE(NVL(b.VES_CIST,0),0,NULL,b.VES_CIST) as VES_CIST,
  b.CAPACITY,
  DECODE(NVL(KLS_VAGOWNER.ID,0),0,'',KLS_VAGOWNER.SHORT_NAME) as VAGOWNER_NAME,
  DECODE(NVL(b.VZLIV,0),0,NULL,b.VZLIV) as VZLIV,
  b.PLOMBA1,
  b.PLOMBA2,
  b.ROSINSPL1,
  b.ROSINSPL2
FROM VED_POD_ROW b, VED_POD a, KLS_PROD, KLS_VAGOWNER, KLS_VETKA_OTP
WHERE b.VED_POD_ID=a.ID
  AND b.PROD_ID_NPR=KLS_PROD.ID_NPR(+)
  AND b.VAGOWNER_ID=KLS_VAGOWNER.ID(+)
  AND a.VETKA_OTP_ID=KLS_VETKA_OTP.ID
  AND a.MESTO_ID=NVL(FOR_TEMP.GET_AS_NUM('MESTO_ID','MASTER','MO_PODACHA.XLS'),0)
  AND a.LOAD_TYPE_ID=NVL(FOR_TEMP.GET_AS_NUM('LOAD_TYPE_ID','MASTER','MO_PODACHA.XLS'),0)
  AND a.ID=NVL(FOR_TEMP.GET_AS_NUM('VED_POD_ID','MASTER','MO_PODACHA.XLS'),0)
ORDER BY b.POD_POS,b.NUM_CIST;


