--
-- V_VED_OSMOTR_PRINT  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_VED_OSMOTR_PRINT
(VED_NUM, VED_DATE, FIO, SIGN, POD_POS, 
 POD_DATE, RAZMET_PER, PROD_NAME, NUM_CIST, KALIBR_ID, 
 VES_CIST, CAPACITY, VAGOWNER_NAME)
AS 
SELECT 
  a.VED_NUM, 
  a.VED_DATE, 
  TRIM(a.FIO1 || DECODE(a.FIO2,'','',' '||a.FIO2) || DECODE(a.FIO3,'','',' '||a.FIO3))||' ' as FIO, 
  a.SIGN1||' ' as SIGN, 
  b.POD_POS, 
  b.POD_DATE, 
  b.RAZMET_PER, 
  KLS_PROD.ABBR_NPR as PROD_NAME, 
  b.NUM_CIST, 
  b.KALIBR_ID, 
  DECODE(NVL(b.VES_CIST,0),0,NULL,b.VES_CIST) as VES_CIST, 
  b.CAPACITY, 
  DECODE(NVL(KLS_VAGOWNER.ID,0),0,'',KLS_VAGOWNER.SHORT_NAME) as VAGOWNER_NAME 
FROM VED_OSMOTR_ROW b, VED_OSMOTR a, KLS_PROD, KLS_VAGOWNER 
WHERE b.VED_ID=a.ID 
  AND b.PROD_ID_NPR=KLS_PROD.ID_NPR(+) 
  AND b.VAGOWNER_ID=KLS_VAGOWNER.ID(+) 
--  AND a.MESTO_ID=NVL(FOR_TEMP.GET_AS_NUM('MESTO_ID','MASTER','MO_VED_OSMOTR.XLS'),0) 
  AND a.LOAD_TYPE_ID=NVL(FOR_TEMP.GET_AS_NUM('LOAD_TYPE_ID','MASTER','MO_VED_OSMOTR.XLS'),0) 
  AND a.ID=NVL(FOR_TEMP.GET_AS_NUM('VED_OSMOTR_ID','MASTER','MO_VED_OSMOTR.XLS'),0) 
ORDER BY b.POD_POS,b.NUM_CIST;


