--
-- V_ZATRATY_ARENDA_VAG  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_ZATRATY_ARENDA_VAG
(POTREB, DATE_KVIT, NUM_KVIT, NUM_CIST, VAGOWNER_NAME, 
 VES_BRUTTO, STAN_NAME, PROD, RAST, STOIMOST)
AS 
SELECT /*+ ORDERED USE_NL(K,M,PR,PROD,S,D) */
PREDPR.SF_NAME AS POTREB 
,K.DATE_KVIT
,K.NUM_KVIT
,K.NUM_CIST
,OWN2.VAGOWNER_NAME
,K.VES_BRUTTO
,S.STAN_NAME
,PROD.SF_NAME AS PROD
,S.RAST
,SV.STOIMOST
FROM
KVIT K
,MONTH M
,KLS_DOG D
,KLS_PREDPR PREDPR
,KLS_VAGOWNER OWN1
,KLS_VAGOWNER OWN2
,KLS_STAN S
,KLS_PROD PROD
,KLS_VAG_STOIM_ISPOLZ SV
,KLS_VID_OTGR VO
WHERE
K.NOM_ZD=M.NOM_ZD
AND M.DOG_ID=D.ID
AND D.PREDPR_ID=PREDPR.ID
AND K.VAGOWNER_ID=OWN1.ID
AND M.STAN_ID=S.ID
AND K.PROD_ID_NPR=PROD.ID_NPR
AND (CASE 
		  WHEN NVL(For_Temp.GET_AS_NUM('LC_VAGOWNER', 'MASTER', 'ZATRATY_ARENDA_VAG.XLS'),0)=0 THEN OWN1.OWNER_ID
		  ELSE NVL(For_Temp.GET_AS_NUM('LC_VAGOWNER', 'MASTER', 'ZATRATY_ARENDA_VAG.XLS'),0)
     END)=OWN1.OWNER_ID 
AND OWN1.SOBSTV_ID=OWN2.ID
AND OWN1.OWNER_ID=SV.VAGOWNER_ID
AND S.RAST>=SV.BEG_DIST
AND S.RAST<SV.END_DIST+1
--AND SV.ID<29
AND K.DATE_KVIT>=SV.BEG_DATE
AND K.DATE_KVIT<=SV.END_DATE
AND M.IS_EXP=0
AND K.DATE_KVIT>=(SELECT BEGIN_DATE FROM V_MASTER_REPORTS WHERE REPORT_FILE='ZATRATY_ARENDA_VAG.XLS')
AND K.DATE_KVIT<=(SELECT END_DATE FROM V_MASTER_REPORTS WHERE REPORT_FILE='ZATRATY_ARENDA_VAG.XLS')
AND VO.LOAD_TYPE_ID = 1
AND M.LOAD_ABBR = VO.LOAD_ABBR
AND M.NAZN_OTG_ID <> 5
--AND K.DATE_OFORML>=TO_DATE(SUBSTR(FOR_TEMP.GET_AS_CHAR('DBEG_MONTH'),1,10)||' 17:00:00','DD.MM.YYYY HH24:MI:SS')-1
--AND K.DATE_OFORML<TO_DATE(SUBSTR(FOR_TEMP.GET_AS_CHAR('DEND_MONTH'),1,10)||' 17:00:00','DD.MM.YYYY HH24:MI:SS')
--AND
/*(CASE
WHEN K.DATE_OFORML>=TO_DATE(TO_CHAR(TRUNC(K.DATE_OFORML),'DD.MM.YYYY')||' 17:00:00','DD.MM.YYYY HH24:MI:SS') THEN TRUNC(K.DATE_OFORML)+1    
ELSE TRUNC(K.DATE_OFORML)  
END)>=(SELECT BEGIN_DATE FROM V_MASTER_REPORTS WHERE REPORT_FILE='ZATRATY_ARENDA_VAG.XLS')
AND
(CASE
WHEN K.DATE_OFORML>=TO_DATE(TO_CHAR(TRUNC(K.DATE_OFORML),'DD.MM.YYYY')||' 17:00:00','DD.MM.YYYY HH24:MI:SS') THEN TRUNC(K.DATE_OFORML)+1    
ELSE TRUNC(K.DATE_OFORML)  
END)<=(SELECT END_DATE FROM V_MASTER_REPORTS WHERE REPORT_FILE='ZATRATY_ARENDA_VAG.XLS') 
AND K.VAGOWNER_ID<>3
*/
;


