--
-- V_ZAKAZ_TEMP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_ZAKAZ_TEMP
(TERMINAL_NAME, USER_NAME, IS_AGENT, KIND_VALUE, FILIAL_ID, 
 PROD_ID_NPR, PARUS_NOMEN_TAG, PLAT_ID, PARUS_AGENT_TAG, DOG_ID, 
 PARUS_DOGOVOR, PROD_NAME, PLAN_NB, PLAN_AZS, PLAN_TRAN, 
 PLAN_VNCORPTR, PLAN_OTHER, PLAN_PROD, PLAN_DOG, ZAYV_ALL_PROD, 
 ZAYV_ACCEPT_PROD, ZAYV_FACT_PROD, ZAYV_ALL_PLAT, ZAYV_ACCEPT_PLAT, ZAYV_FACT_PLAT, 
 ZAYV_ALL_DOG, ZAYV_ACCEPT_DOG, ZAYV_FACT_DOG, SALDO)
AS 
SELECT "TERMINAL_NAME","USER_NAME","IS_AGENT","KIND_VALUE","FILIAL_ID","PROD_ID_NPR","PARUS_NOMEN_TAG","PLAT_ID","PARUS_AGENT_TAG","DOG_ID","PARUS_DOGOVOR","PROD_NAME","PLAN_NB","PLAN_AZS","PLAN_TRAN","PLAN_VNCORPTR","PLAN_OTHER","PLAN_PROD","PLAN_DOG","ZAYV_ALL_PROD","ZAYV_ACCEPT_PROD","ZAYV_FACT_PROD","ZAYV_ALL_PLAT","ZAYV_ACCEPT_PLAT","ZAYV_FACT_PLAT","ZAYV_ALL_DOG","ZAYV_ACCEPT_DOG","ZAYV_FACT_DOG","SALDO" FROM ZAKAZ_TEMP 
WHERE TERMINAL_NAME=For_Init.GetCurrTerm 
AND USER_NAME=For_Init.GetCurrUser;


