--
-- V_ZAKAZ_GRAFIK_TEMP  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.V_ZAKAZ_GRAFIK_TEMP
(TERMINAL_NAME, USER_NAME, DATE_LOAD, TONN_LOAD, CIST_LOAD)
AS 
SELECT "TERMINAL_NAME","USER_NAME","DATE_LOAD","TONN_LOAD","CIST_LOAD" FROM ZAKAZ_GRAFIK_TEMP 
WHERE TERMINAL_NAME=For_Init.GetCurrTerm 
AND USER_NAME=For_Init.GetCurrUser;


