--
-- XX101_ACTIVE_KLS_PREDPR  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.XX101_ACTIVE_KLS_PREDPR
(ID, PREDPR_NAME, SHORT_NAME, INN, POSTINDEX_J, 
 POSTINDEX_P, CITY_P, CITY_J, ADDRESS_P, ADDRESS_J, 
 OKONH, OKPO, EMAIL, FAX, PHONE, 
 BANK_KORS, REGION_ID, HOLDING_ID, PERTYPE_ID, TALGAR_ID, 
 GD_KOD, RS, BANKS_ID, STATES_ID, CLASS_ID, 
 EX_SVID, IS_BLOCK, OKVED, TAG, OGRN, 
 KSSS_PREDPR_ID, UNP_ID, KPP, REGION_P_ID, SF_NAME, 
 ISU_KOD_PLAT, FULL_ADDRESS_P, FULL_ADDRESS_J, LIFNR)
AS 
select "ID","PREDPR_NAME","SHORT_NAME","INN","POSTINDEX_J","POSTINDEX_P","CITY_P","CITY_J","ADDRESS_P","ADDRESS_J","OKONH","OKPO","EMAIL","FAX","PHONE","BANK_KORS","REGION_ID","HOLDING_ID","PERTYPE_ID","TALGAR_ID","GD_KOD","RS","BANKS_ID","STATES_ID","CLASS_ID","EX_SVID","IS_BLOCK","OKVED","TAG","OGRN","KSSS_PREDPR_ID","UNP_ID","KPP","REGION_P_ID","SF_NAME","ISU_KOD_PLAT","FULL_ADDRESS_P","FULL_ADDRESS_J","LIFNR" from kls_predpr a
where a.is_block<>1 
and a.id in
(
select id from
(
select ksss_predpr_id,max(id) as id from kls_predpr b 
where b.is_block<>1 or b.id in (select distinct predpr_id from kls_dog)
group by ksss_predpr_id
)
);


