--
-- XX101_ZKERP_PENDING_ACTION  (View) 
--
CREATE OR REPLACE FORCE VIEW MASTER.XX101_ZKERP_PENDING_ACTION
(FILENAME, PARSEDATETIME, PROPAGATESTATUS, FILEROWNUM, WAYBILLID, 
 WAYBILLROWID, TRANSPORTKIND, SHIPMENTDATE, SHIPMENTTIME, TRANSPORTNUM, 
 OWNERSHIPTYPE, OWNER, AXESCOUNT, TRANSPORTTYPECODE, TRANSPORTTYPE, 
 PRODUCTCODE, PRODUCTNAME, PASSPORTNUM, FILLINGHEIGHT, DENSITYFACT, 
 DENSITYONSTANDARTTEMP, STANDARTTEMP, TEMPOFFILLING, PUREWEIGHT, TOTALWEIGHT, 
 REESTRNUM, STATE, DELIVERYDIRECTION, KVITNUM, KVITDATE, 
 PACKINGITEMCOUNT, PACKINGITEMWEIGHT, TAREWEIGHTFORPACKING, ACTIONCODE, DEPOT, 
 ORDERCODE, TARIFF, TAREVAGONWEIGHT, SEAL1, SEAL2, 
 TTNSAMPLECODE, WARRANTNUM, WARRANTDATE, DRIVERFIO, VAGONTONNAGE, 
 GUARDPAYMENT, PRODUCTVOLUME, PANCOUNT, PANWEIGHT, PACKINGKIND, 
 TRANSPORTUNITTYPE, WEIGHTEVALUATEMETHOD)
AS 
SELECT /*+ ORDERED */ C.* 
      FROM XX101_ZKERP_DATA C JOIN  
    (SELECT A.FILENAME,max(A.FILEROWNUM) as FILEROWNUM FROM XX101_ZKERP_DATA A 
           JOIN (SELECT WAYBILLID,WAYBILLROWID,MAX(FILENAME) AS FILENAME FROM XX101_ZKERP_DATA 
                       GROUP BY WAYBILLID,WAYBILLROWID) B
           ON A.WAYBILLID=B.WAYBILLID  AND A.WAYBILLROWID=B.WAYBILLROWID AND A.FILENAME=B.FILENAME
     GROUP BY A.WAYBILLID,A.WAYBILLROWID,A.FILENAME) D
     ON C.FILENAME=D.FILENAME AND C.FILEROWNUM=D.FILEROWNUM
     WHERE C.PROPAGATESTATUS IS NULL;


