--
-- REESTR_RAIL_RGD_SF_BIU  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.REESTR_RAIL_RGD_SF_BIU
BEFORE INSERT OR UPDATE
ON MASTER.REESTR_RAIL_RGD_SF
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
   tmpVar := 0;
if :NEW.REESTR_RAIL_RGD_SF_ID is NULL or :NEW.REESTR_RAIL_RGD_SF_ID=0 then
   Select SEQ_REESTR_RAIL.NextVal into tmpVar from dual;
   :NEW.REESTR_RAIL_RGD_SF_ID := tmpVar;
end if;
END;
/


