--
-- T01_SEQ_KVIT_DATE_VIR  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.T01_SEQ_KVIT_DATE_VIR
BEFORE INSERT OR UPDATE
ON MASTER.KVIT_DATE_VIR
FOR EACH ROW
BEGIN

  -- ”никальный ID
  IF :new.ID=0 OR :new.ID IS NULL THEN
    SELECT SEQ_ID.NEXTVAL INTO :new.ID FROM DUAL;
  END IF;

END;
/


