--
-- T01_SEQ_ZAKAZ_HIST  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.T01_SEQ_ZAKAZ_HIST
BEFORE INSERT OR UPDATE
ON MASTER.ZAKAZ_HIST
FOR EACH ROW
BEGIN

  -- ”никальный ID
  IF :new.ID=0 OR :new.ID IS NULL THEN
    SELECT SEQ_MONTH_ALL.NEXTVAL INTO :new.ID FROM DUAL;
  END IF;

END;
/


