--
-- T11_BIR_ZAKAZ_GRAFIK_TEMP  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.T11_BIR_ZAKAZ_GRAFIK_TEMP
BEFORE INSERT
ON MASTER.ZAKAZ_GRAFIK_TEMP
FOR EACH ROW
BEGIN
  IF INSERTING() THEN
    :NEW.TERMINAL_NAME:=For_Init.GetCurrTerm;
    :NEW.USER_NAME:=For_Init.GetCurrUser;
  END IF;
END;
/


