--
-- T11_BIR_TEMP_PAYMENTS_TO_BILLS  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.T11_BIR_TEMP_PAYMENTS_TO_BILLS
BEFORE INSERT
ON MASTER.TEMP_PAYMENTS_TO_BILLS
FOR EACH ROW
BEGIN
  IF INSERTING() THEN
    :NEW.TERMINAL_NAME:=For_Init.GetCurrTerm;
    :NEW.OSUSER_NAME:=For_Init.GetCurrUser;
  END IF;
END;
/


