--
-- T11_BIR_KLS_DOC_RESERV  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.T11_BIR_KLS_DOC_RESERV
BEFORE INSERT
ON MASTER.KLS_DOC_RESERV
FOR EACH ROW
BEGIN
  IF INSERTING() THEN
    :NEW.TERMINAL_NAME:=For_Init.GetCurrTerm;
    :NEW.OSUSER_NAME:=For_Init.GetCurrUser;
  END IF;
END;
/


