--
-- T_DEL_ISU_BILL_POS_ROW  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.T_DEL_ISU_BILL_POS_ROW
AFTER DELETE
ON MASTER.ISU_BILLS
FOR EACH ROW
DECLARE
tmpVar VARCHAR2(10);
BEGIN
  	 
	 tmpVar := :OLD.ISU_KOD; 
	 
   	 DELETE FROM ISU_BILL_POS WHERE SUBSTR(ISU_KOD_POS,1,10)=tmpVar;
   	 DELETE FROM ISU_BILL_POS_ROW WHERE ISU_KOD=tmpVar;

END T_DEL_ISU_BILL_POS_ROW;
/


