--
-- T_GU12_A_ID  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.T_GU12_A_ID
BEFORE INSERT OR UPDATE
ON MASTER.GU12_A 
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
   tmpVar := 0;
   :new.NOM_Z:=TRIM(:new.NOM_Z);

   IF :NEW.ID IS NULL OR :NEW.ID = 0
   THEN
      SELECT seq_gu12_a.NEXTVAL
        INTO tmpvar
        FROM DUAL;

      :NEW.ID := tmpvar;
   END IF;

END T_GU12_A_ID;
/


