--
-- TEMP_REESTR_PARAMS_BIR  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TEMP_REESTR_PARAMS_BIR
BEFORE INSERT
ON MASTER.TEMP_REESTR_PARAMS
FOR EACH ROW
DECLARE
BEGIN
  IF INSERTING() THEN
    :NEW.TERMINAL_NAME:=For_Init.GetCurrTerm;
	:NEW.OSUSER_NAME:=For_Init.GetCurrUser;
  END IF;
END TEMP_REESTR_PARAMS_BIR;
/


