--
-- TEMP_BILL_KVIT_POSSIBLE_BIR  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TEMP_BILL_KVIT_POSSIBLE_BIR
BEFORE INSERT
ON MASTER.TEMP_BILL_KVIT_POSSIBLE
FOR EACH ROW
DECLARE
BEGIN
  IF INSERTING() THEN
    :NEW.TERMINAL_NAME:=For_Init.GetCurrTerm;
	:NEW.OSUSER_NAME:=For_Init.GetCurrUser;
  END IF;
END TEMP_BILL_KVIT_POSSIBLE_BIR;
/


