--
-- TRG_BIUDR_PODACHA_ROWS  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BIUDR_PODACHA_ROWS
BEFORE INSERT OR DELETE OR UPDATE
ON MASTER.PODACHA_ROWS
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN

    IF INSERTING() OR UPDATING() THEN
      IF :new.ID=0 OR :new.ID IS NULL THEN
        SELECT SEQ_PODACHA_ROWS.nextval INTO :new.ID FROM DUAL;
      END IF;
      -- Проверка новых значений
      NULL;
    END IF;

END;
/


