--
-- TRG_BEFORE_OSTSAT_VYRAB  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BEFORE_OSTSAT_VYRAB
BEFORE INSERT
ON MASTER.OSTAT_VYRAB
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
   tmpVar := 0;
IF :NEW.ID IS NULL OR :NEW.ID=0 THEN
   SELECT seq_plan_refinery.NEXTVAL INTO tmpVar FROM dual;
   :NEW.ID := tmpVar;
END IF;
END ;
/


