--
-- TRG_MASTER_REPORTS  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_MASTER_REPORTS
BEFORE INSERT OR UPDATE
ON MASTER.MASTER_REPORTS
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
  IF INSERTING() OR UPDATING() THEN
    IF :NEW.ID=0 OR :NEW.ID IS NULL THEN
      tmpVar := 0;
      SELECT seq_TempVari.NEXTVAL INTO tmpVar FROM dual;
     :NEW.ID := tmpVar;
    END IF;
	:NEW.TERMINAL_NAME:=NLS_UPPER(For_Init.GetCurrTerm);
	:NEW.OSUSER_NAME:=NLS_UPPER(For_Init.GetCurrUser);
	:NEW.APP_NAME:=NLS_UPPER(:NEW.APP_NAME);
	:NEW.REPORT_FILE:=NLS_UPPER(:NEW.REPORT_FILE);
  END IF;
END TRG_MASTER_REPORTS;
/


