--
-- TRG_BIR_MESTO_LOG  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BIR_MESTO_LOG
BEFORE INSERT
ON MASTER.MESTO_LOG
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
  IF :NEW.ID=0 OR :NEW.ID IS NULL THEN
    tmpVar := 0;
    SELECT seq_mesto_log.NEXTVAL INTO tmpVar FROM dual;
   :NEW.ID := tmpVar;
  END IF;
END TRG_BIR_MESTO_LOG;
/


