--
-- TRG_PAYMENTS_BIR  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_PAYMENTS_BIR
BEFORE INSERT
ON MASTER.PAYMENTS
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
   tmpVar := 0;
   SELECT Seq_Payments.NEXTVAL INTO tmpVar FROM dual;
   IF :NEW.ID is null THEN
     :NEW.ID := tmpVar;
   END IF;
END ;
/


