--
-- TRG_MASTER_QUERY_TYPES_DESC  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_MASTER_QUERY_TYPES_DESC
BEFORE INSERT OR UPDATE
ON MASTER.MASTER_QUERY_TYPES_DESC
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
  IF INSERTING() OR UPDATING() THEN
    IF :NEW.ID=0 OR :NEW.ID IS NULL THEN
      tmpVar := 0;
      SELECT seq_MASTER_QUERY_TYPES_DESC.NEXTVAL INTO tmpVar FROM dual;
     :NEW.ID := tmpVar;
    END IF;
  END IF;
END TRG_MASTER_QUERY_TYPES_DESC;
/


