--
-- TRG_BIUDR_SVED_IN  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BIUDR_SVED_IN
BEFORE INSERT OR DELETE OR UPDATE
ON MASTER.SVED_IN
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN
  IF INSERTING() OR UPDATING() THEN
    -- ”никальный ID
    IF :new.ID||' '=' ' OR :new.ID IS NULL THEN
      SELECT SEQ_SVED_IN.nextval INTO v_tmp FROM DUAL;
	  :new.ID:=TO_CHAR(v_tmp);
    END IF;
	-- вычисление % солей
	IF NVL(:NEW.P_SOL,0)=0 AND NVL(:NEW.MG_SOL,0)<>0 THEN 
	  IF NVL(:NEW.PL15,0)<>0 THEN
	    :NEW.P_SOL:=ROUND(:NEW.MG_SOL/:NEW.PL15/10000,4);
	  ELSIF NVL(:NEW.PL,0)<>0 THEN
	    :NEW.P_SOL:=ROUND(:NEW.MG_SOL/:NEW.PL/10000,4);
	  ELSE
	  	:NEW.P_SOL:=0;
	  END IF;	
	END IF;
  END IF;
END;
/


