--
-- TRG_AIUDR_KLS_PLANSTRU  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_AIUDR_KLS_PLANSTRU
AFTER INSERT OR DELETE OR UPDATE OF ID, NAME, KOD_GRP, KOD_SPG, BEGIN_DATE, INPUT_DATE, KOD_PRZ, KOD_RZD, KOD_SGR, END_DATE, PARENT_ID, NAZN_OTG_ID, LEVEL_POS, KOD_PGR
ON MASTER.KLS_PLANSTRU
FOR EACH ROW
DECLARE
  v_old KLS_PLANSTRU%ROWTYPE;
  v_new KLS_PLANSTRU%ROWTYPE;
  v_tmp NUMBER;
BEGIN

  IF DELETING() OR UPDATING() THEN
    -- Старые значения
    v_old.ID := :OLD.ID;
    v_old.BEGIN_DATE := :OLD.BEGIN_DATE;
    v_old.END_DATE := :OLD.END_DATE;
    v_old.NAME := :OLD.NAME;
    v_old.LEVEL_POS := :OLD.LEVEL_POS;
    v_old.INPUT_DATE := :OLD.INPUT_DATE;
    v_old.KOD_SGR := :OLD.KOD_SGR;
    v_old.KOD_SPG := :OLD.KOD_SPG;
    v_old.KOD_RZD := :OLD.KOD_RZD;
    v_old.KOD_PRZ := :OLD.KOD_PRZ;
    v_old.KOD_GRP := :OLD.KOD_GRP;
    v_old.KOD_PGR := :OLD.KOD_PGR;
    v_old.PARENT_ID := :OLD.PARENT_ID;
    v_old.NAZN_OTG_ID := :OLD.NAZN_OTG_ID;
  END IF;

  -- После удаления
  IF DELETING() THEN
    NULL;
    -- Удаление из теневой таблицы
    DELETE FROM MASTER_SHADOW.KLS_PLANSTRU_SHADOW
     WHERE ID=v_old.ID;
  END IF;

  IF INSERTING() OR UPDATING() THEN
    -- Новые значения
    v_new.ID := :NEW.ID;
    v_new.BEGIN_DATE := :NEW.BEGIN_DATE;
    v_new.END_DATE := :NEW.END_DATE;
    v_new.NAME := :NEW.NAME;
    v_new.LEVEL_POS := :NEW.LEVEL_POS;
    v_new.INPUT_DATE := :NEW.INPUT_DATE;
    v_new.KOD_SGR := :NEW.KOD_SGR;
    v_new.KOD_SPG := :NEW.KOD_SPG;
    v_new.KOD_RZD := :NEW.KOD_RZD;
    v_new.KOD_PRZ := :NEW.KOD_PRZ;
    v_new.KOD_GRP := :NEW.KOD_GRP;
    v_new.KOD_PGR := :NEW.KOD_PGR;
    v_new.PARENT_ID := :NEW.PARENT_ID;
    v_new.NAZN_OTG_ID := :NEW.NAZN_OTG_ID;

    -- Обновление теневой таблицы
    UPDATE MASTER_SHADOW.KLS_PLANSTRU_SHADOW SET
      (ID,BEGIN_DATE,END_DATE,NAME,LEVEL_POS,INPUT_DATE,KOD_SGR,KOD_SPG,KOD_RZD,KOD_PRZ,KOD_GRP,KOD_PGR,PARENT_ID,NAZN_OTG_ID)=
      (SELECT v_new.ID,v_new.BEGIN_DATE,v_new.END_DATE,v_new.NAME,v_new.LEVEL_POS,v_new.INPUT_DATE,v_new.KOD_SGR,v_new.KOD_SPG,v_new.KOD_RZD,v_new.KOD_PRZ,v_new.KOD_GRP,v_new.KOD_PGR,v_new.PARENT_ID,v_new.NAZN_OTG_ID FROM dual)
      WHERE ID=v_old.ID;

    IF SQL%NOTFOUND THEN
      INSERT INTO MASTER_SHADOW.KLS_PLANSTRU_SHADOW
        (ID,BEGIN_DATE,END_DATE,NAME,LEVEL_POS,INPUT_DATE,KOD_SGR,KOD_SPG,KOD_RZD,KOD_PRZ,KOD_GRP,KOD_PGR,PARENT_ID,NAZN_OTG_ID)
        VALUES
        (v_new.ID,v_new.BEGIN_DATE,v_new.END_DATE,v_new.NAME,v_new.LEVEL_POS,v_new.INPUT_DATE,v_new.KOD_SGR,v_new.KOD_SPG,v_new.KOD_RZD,v_new.KOD_PRZ,v_new.KOD_GRP,v_new.KOD_PGR,v_new.PARENT_ID,v_new.NAZN_OTG_ID);
    END IF;

    -- После обновления
    IF UPDATING() THEN
      NULL;
    END IF;

    -- После добавления
    IF INSERTING() THEN
      NULL;
    END IF;

  END IF;
END;
/


