--
-- TRG_BIR_AZC_TARIF  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BIR_AZC_TARIF
BEFORE INSERT OR UPDATE
ON MASTER.AZC_TARIF
FOR EACH ROW
BEGIN
  IF (:NEW.ID IS NULL) OR (:NEW.ID=0) THEN
    SELECT seq_azc_tarif.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
--  :NEW.DATE_INTO:=SYSDATE;
END trg_bir_azc_tarif;
/


