--
-- TRG_BIUDR_SVED  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BIUDR_SVED
BEFORE INSERT OR DELETE OR UPDATE
ON MASTER.SVED
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN
  IF INSERTING() OR UPDATING() THEN
    -- ”никальный ID
    IF :new.ID||' '=' ' OR :new.ID IS NULL THEN
      SELECT SEQ_SVED.nextval INTO v_tmp FROM DUAL;
	  :new.ID:=TO_CHAR(v_tmp);
    END IF;
  END IF;
END;
/


