--
-- TRG_BIUDR_UVED  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BIUDR_UVED
BEFORE INSERT OR DELETE OR UPDATE
ON MASTER.UVED
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN

  IF INSERTING() OR UPDATING() THEN
    -- ”никальный ID
    IF :new.ID||' '=' ' OR :new.ID IS NULL THEN
      SELECT SEQ_ID.nextval INTO :new.ID FROM DUAL;
    END IF;
  END IF;
  
END;
/


