--
-- TRG_BIUDR_VED_POD  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BIUDR_VED_POD
BEFORE INSERT OR DELETE OR UPDATE
ON MASTER.VED_POD
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN


  IF INSERTING() OR UPDATING() THEN
      IF :new.ID=0 OR :new.ID IS NULL THEN
        SELECT SEQ_ID.nextval INTO :new.ID FROM DUAL;
      END IF;
  END IF;


END;
/


