--
-- TRG_AIUDR_KLS_DOG  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_AIUDR_KLS_DOG
AFTER INSERT OR DELETE OR UPDATE
ON MASTER.KLS_DOG
FOR EACH ROW
DECLARE
  v_old KLS_DOG%ROWTYPE;
  v_new KLS_DOG%ROWTYPE;
  v_tmp NUMBER;
  LogId NUMBER;
  cl_WhatWasDone CLOB;
  WriteStr VARCHAR2(250);
  WritePos NUMBER;
BEGIN

  IF DELETING() OR UPDATING() THEN
    -- Старые значения
    v_old.ID := :OLD.ID;
    v_old.DOG_NUMBER := :OLD.DOG_NUMBER;
    v_old.SHORT_NUMBER := :OLD.SHORT_NUMBER;
    v_old.DOG_BEGIN_DATE := :OLD.DOG_BEGIN_DATE;
    v_old.DOG_END_DATE := :OLD.DOG_END_DATE;
    v_old.DOG_DATE := :OLD.DOG_DATE;
    v_old.DOG_YEAR := :OLD.DOG_YEAR;
    v_old.REP_KOD := :OLD.REP_KOD;
    v_old.PREDPR_ID := :OLD.PREDPR_ID;
    v_old.INSURE_ID := :OLD.INSURE_ID;
    v_old.VIDDOG_ID := :OLD.VIDDOG_ID;
    v_old.GROUPDOG_ID := :OLD.GROUPDOG_ID;
    v_old.GOSPROG_ID := :OLD.GOSPROG_ID;
    v_old.LUKDOG_ID := :OLD.LUKDOG_ID;
    v_old.USL_OPL_ID := :OLD.USL_OPL_ID;
    v_old.SALDO_01042002 := :OLD.SALDO_01042002;
    v_old.SALDO_01042002_PROD := :OLD.SALDO_01042002_PROD;
    v_old.MAINDOG_ID := :OLD.MAINDOG_ID;
    v_old.SALDO_01072002 := :OLD.SALDO_01072002;
    v_old.SALDO_01_07_2002 := :OLD.SALDO_01_07_2002;
    v_old.APPL_TAG := :OLD.APPL_TAG;
    v_old.SALDO_01122002 := :OLD.SALDO_01122002;
    v_old.IS_AGENT := :OLD.IS_AGENT;
    v_old.AGENT_ID := :OLD.AGENT_ID;
  END IF;

  -- После удаления
  IF DELETING() THEN
    NULL;
    -- Удаление из теневой таблицы
    DELETE FROM MASTER_SHADOW.KLS_DOG_SHADOW
     WHERE ID=v_old.ID;
  END IF;

  IF INSERTING() OR UPDATING() THEN
    -- Новые значения
    v_new.ID := :NEW.ID;
    v_new.DOG_NUMBER := :NEW.DOG_NUMBER;
    v_new.SHORT_NUMBER := :NEW.SHORT_NUMBER;
    v_new.DOG_BEGIN_DATE := :NEW.DOG_BEGIN_DATE;
    v_new.DOG_END_DATE := :NEW.DOG_END_DATE;
    v_new.DOG_DATE := :NEW.DOG_DATE;
    v_new.DOG_YEAR := :NEW.DOG_YEAR;
    v_new.REP_KOD := :NEW.REP_KOD;
    v_new.PREDPR_ID := :NEW.PREDPR_ID;
    v_new.INSURE_ID := :NEW.INSURE_ID;
    v_new.VIDDOG_ID := :NEW.VIDDOG_ID;
    v_new.GROUPDOG_ID := :NEW.GROUPDOG_ID;
    v_new.GOSPROG_ID := :NEW.GOSPROG_ID;
    v_new.LUKDOG_ID := :NEW.LUKDOG_ID;
    v_new.USL_OPL_ID := :NEW.USL_OPL_ID;
    v_new.SALDO_01042002 := :NEW.SALDO_01042002;
    v_new.SALDO_01042002_PROD := :NEW.SALDO_01042002_PROD;
    v_new.MAINDOG_ID := :NEW.MAINDOG_ID;
    v_new.SALDO_01072002 := :NEW.SALDO_01072002;
    v_new.SALDO_01_07_2002 := :NEW.SALDO_01_07_2002;
    v_new.APPL_TAG := :NEW.APPL_TAG;
    v_new.SALDO_01122002 := :NEW.SALDO_01122002;
    v_new.IS_AGENT := :NEW.IS_AGENT;
    v_new.AGENT_ID := :NEW.AGENT_ID;

    -- Обновление теневой таблицы
    UPDATE MASTER_SHADOW.KLS_DOG_SHADOW SET
      (ID,DOG_NUMBER,SHORT_NUMBER,DOG_BEGIN_DATE,DOG_END_DATE,DOG_DATE,DOG_YEAR,REP_KOD,PREDPR_ID,INSURE_ID,VIDDOG_ID,GROUPDOG_ID,GOSPROG_ID,LUKDOG_ID,USL_OPL_ID,SALDO_01042002,SALDO_01042002_PROD,MAINDOG_ID,SALDO_01072002,SALDO_01_07_2002,APPL_TAG,SALDO_01122002,IS_AGENT,AGENT_ID)=
      (SELECT v_new.ID,v_new.DOG_NUMBER,v_new.SHORT_NUMBER,v_new.DOG_BEGIN_DATE,v_new.DOG_END_DATE,v_new.DOG_DATE,v_new.DOG_YEAR,v_new.REP_KOD,v_new.PREDPR_ID,v_new.INSURE_ID,v_new.VIDDOG_ID,v_new.GROUPDOG_ID,v_new.GOSPROG_ID,v_new.LUKDOG_ID,v_new.USL_OPL_ID,v_new.SALDO_01042002,v_new.SALDO_01042002_PROD,v_new.MAINDOG_ID,v_new.SALDO_01072002,v_new.SALDO_01_07_2002,v_new.APPL_TAG,v_new.SALDO_01122002,v_new.IS_AGENT,v_new.AGENT_ID FROM dual)
      WHERE ID=v_old.ID;

    IF SQL%NOTFOUND THEN
      INSERT INTO MASTER_SHADOW.KLS_DOG_SHADOW
        (ID,DOG_NUMBER,SHORT_NUMBER,DOG_BEGIN_DATE,DOG_END_DATE,DOG_DATE,DOG_YEAR,REP_KOD,PREDPR_ID,INSURE_ID,VIDDOG_ID,GROUPDOG_ID,GOSPROG_ID,LUKDOG_ID,USL_OPL_ID,SALDO_01042002,SALDO_01042002_PROD,MAINDOG_ID,SALDO_01072002,SALDO_01_07_2002,APPL_TAG,SALDO_01122002,IS_AGENT,AGENT_ID)
        VALUES
        (v_new.ID,v_new.DOG_NUMBER,v_new.SHORT_NUMBER,v_new.DOG_BEGIN_DATE,v_new.DOG_END_DATE,v_new.DOG_DATE,v_new.DOG_YEAR,v_new.REP_KOD,v_new.PREDPR_ID,v_new.INSURE_ID,v_new.VIDDOG_ID,v_new.GROUPDOG_ID,v_new.GOSPROG_ID,v_new.LUKDOG_ID,v_new.USL_OPL_ID,v_new.SALDO_01042002,v_new.SALDO_01042002_PROD,v_new.MAINDOG_ID,v_new.SALDO_01072002,v_new.SALDO_01_07_2002,v_new.APPL_TAG,v_new.SALDO_01122002,v_new.IS_AGENT,v_new.AGENT_ID);
    END IF;

    -- После обновления
    IF UPDATING() THEN
      NULL;
    END IF;

    -- После добавления
    IF INSERTING() THEN
      NULL;
    END IF;

  END IF;
END;
/


