--
-- TRG_REPORT_GROUPS  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_REPORT_GROUPS
BEFORE INSERT
ON MASTER.REPORT_GROUPS
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
  IF INSERTING() THEN
    IF :NEW.ID=0 OR :NEW.ID is NULL THEN
      tmpVar := 0;
      Select seq_Report_Groups.NextVal into tmpVar from dual;
     :NEW.ID := tmpVar;
    END IF;
	:NEW.SORTBY := :NEW.ID;
  END IF;
END TRG_REPORT_GROUPS;
/


