--
-- TRG_REPORTS  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_REPORTS
BEFORE INSERT
ON MASTER.REPORTS
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
  IF INSERTING() THEN
    IF :NEW.ID=0 OR :NEW.ID IS NULL THEN
      tmpVar := 0;
      SELECT seq_Reports.NEXTVAL INTO tmpVar FROM dual;
     :NEW.ID := tmpVar;
    END IF;
    IF :NEW.sortby=0 OR :NEW.sortby IS NULL THEN
  	  :NEW.SORTBY := :NEW.ID;
	END IF;  
  END IF;
END TRG_REPORTS;
/


