--
-- TRG_BIUDR_KLS_PROD_GR2GR_DESC  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BIUDR_KLS_PROD_GR2GR_DESC
BEFORE INSERT OR DELETE OR UPDATE
ON MASTER.KLS_PROD_GR2GR_DESC
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN


  IF INSERTING() OR UPDATING() THEN
    -- Новые значения
	BEGIN
	  SELECT prod_type_grp_id INTO :new.prod_type_grp_id_1
	    FROM KLS_PROD_GROUPS
 	   WHERE id=:new.PROD_GROUPS_ID_1;
	EXCEPTION
	  WHEN OTHERS THEN
        :new.PROD_TYPE_GRP_ID_1 := NULL;
	END;      	

	BEGIN
	  SELECT prod_type_grp_id INTO :new.prod_type_grp_id_2
	    FROM KLS_PROD_GROUPS
 	   WHERE id=:new.PROD_GROUPS_ID_2;
	EXCEPTION
	  WHEN OTHERS THEN
        :new.PROD_TYPE_GRP_ID_2 := NULL;
	END;      	

    IF :new.ID=0 OR :new.ID IS NULL THEN
      SELECT SEQ_KLS_PROD_GROUPS_DESC.NEXTVAL INTO :new.ID FROM DUAL;
    END IF;

  END IF;
END;
/


