--
-- TRG_AIUDR_KLS_NAR_LINE  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_AIUDR_KLS_NAR_LINE
AFTER INSERT OR DELETE OR UPDATE
ON MASTER.KLS_NAR_LINE
FOR EACH ROW
BEGIN
  -- Обновляем факт отгрузки в заявке
  IF INSERTING() THEN
    UPDATE MONTH
	   SET CIST_FACT=NVL(CIST_FACT,0)+NVL(:NEW.FACT_KOL,0),
	       TONN_FACT=NVL(TONN_FACT,0)+NVL(:NEW.FACT_VES,0)
 	 WHERE NOM_ZD=:NEW.NOM_ZD;
  END IF;
  IF DELETING() THEN
    UPDATE MONTH
	   SET CIST_FACT=NVL(CIST_FACT,0)-NVL(:OLD.FACT_KOL,0),
	       TONN_FACT=NVL(TONN_FACT,0)-NVL(:OLD.FACT_VES,0)
	 WHERE NOM_ZD=:OLD.NOM_ZD;
  END IF;
  IF UPDATING('FACT_VES') OR UPDATING('FACT_KOL') THEN
    UPDATE MONTH
	   SET CIST_FACT=NVL(CIST_FACT,0)-NVL(:OLD.FACT_KOL,0)+NVL(:NEW.FACT_KOL,0),
	       TONN_FACT=NVL(TONN_FACT,0)-NVL(:OLD.FACT_VES,0)+NVL(:NEW.FACT_VES,0)
	 WHERE NOM_ZD=:NEW.NOM_ZD;
  END IF;


END;
/


