--
-- TRG_BIUDR_KTU_2_NPO_SF  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BIUDR_KTU_2_NPO_SF
BEFORE INSERT OR DELETE OR UPDATE
ON MASTER.KTU_2_NPO_SF
FOR EACH ROW
BEGIN
  IF INSERTING OR (UPDATING('NPO_SF')) THEN
    BEGIN
	  UPDATE BILLS SET NPO_SF=:NEW.NPO_SF WHERE BILLS.NOM_DOK=:NEW.NOM_DOK
	    AND BILLS.DATE_KVIT>=TO_DATE('01.04.2002','dd.mm.yyyy');
	EXCEPTION
	  WHEN OTHERS THEN
	    NULL;
	END;
    BEGIN
	  UPDATE BILLS_SNP SET NPO_SF=:NEW.NPO_SF WHERE BILLS_SNP.NOM_DOK=:NEW.NOM_DOK
	    AND BILLS_SNP.DATE_KVIT>=TO_DATE('01.04.2002','dd.mm.yyyy');
	EXCEPTION
	  WHEN OTHERS THEN
	    NULL;
	END;
  ELSE 
    IF DELETING THEN
      BEGIN
	    UPDATE BILLS SET NPO_SF=NULL WHERE BILLS.NOM_DOK=:OLD.NOM_DOK
  	      AND BILLS.DATE_KVIT>=TO_DATE('01.04.2002','dd.mm.yyyy');
      EXCEPTION
	    WHEN OTHERS THEN
	      NULL;
      END;
      BEGIN
	    UPDATE BILLS_SNP SET NPO_SF=NULL WHERE BILLS_SNP.NOM_DOK=:OLD.NOM_DOK
  	     AND BILLS_SNP.DATE_KVIT>=TO_DATE('01.04.2002','dd.mm.yyyy');
      EXCEPTION
	    WHEN OTHERS THEN
	      NULL;
      END;
	END IF;   
  END IF;
END TRG_BIUDR_KTU_2_NPO_SF;
/


