--
-- TRG_BIUDR_KLS_DOC_TYPES  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BIUDR_KLS_DOC_TYPES
BEFORE INSERT OR DELETE OR UPDATE
ON MASTER.KLS_DOC_TYPES
FOR EACH ROW
BEGIN
  IF INSERTING() OR UPDATING() THEN
    -- ”никальный ID
    IF :new.ID=0 OR :new.ID IS NULL THEN
      SELECT SEQ_KLS.nextval INTO :new.ID FROM DUAL;
    END IF;
  END IF;
END;
/


