--
-- TRG_AIUDR_SVED_IN  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_AIUDR_SVED_IN
AFTER INSERT OR DELETE OR UPDATE
ON MASTER.SVED_IN
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN
  IF UPDATING('SVED_DATE') THEN
    UPDATE REESTR_IN SET DATE_OTGR=:NEW.SVED_DATE WHERE SVED_IN_ID=:new.ID;
  END IF;	
END;
/


