--
-- TRG_USER_RIGHTS  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_USER_RIGHTS
BEFORE INSERT OR DELETE OR UPDATE
ON MASTER.USER_RIGHTS
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
  SELECT seq_table_activity_log.NEXTVAL INTO tmpVar FROM dual;
  IF UPDATING() THEN
    INSERT INTO MASTER_SHADOW.TABLE_ACTIVITY_LOG (id,TABLE_NAME,TABLE_ID,OSUSER,TERMINAL,MODULE,EVENT_TIME,EVENT_TYPE)
      SELECT tmpVar,'USER_RIGHTS' AS table_name,'',osuser,terminal,MODULE,SYSDATE,'U'
	    FROM sys.V_$SESSION
  	    WHERE audsid=USERENV('sessionid');
  END IF;
  IF INSERTING() THEN
    INSERT INTO MASTER_SHADOW.TABLE_ACTIVITY_LOG (id,TABLE_NAME,TABLE_ID,OSUSER,TERMINAL,MODULE,EVENT_TIME,EVENT_TYPE)
      SELECT tmpVar,'USER_RIGHTS' AS table_name,'',osuser,terminal,MODULE,SYSDATE,'I'
	    FROM sys.V_$SESSION
  	    WHERE audsid=USERENV('sessionid');
  END IF;
  IF DELETING() THEN
    INSERT INTO MASTER_SHADOW.TABLE_ACTIVITY_LOG (id,TABLE_NAME,TABLE_ID,OSUSER,TERMINAL,MODULE,EVENT_TIME,EVENT_TYPE)
      SELECT tmpVar,'USER_RIGHTS' AS table_name,'',osuser,terminal,MODULE,SYSDATE,'D'
	    FROM sys.V_$SESSION
  	    WHERE audsid=USERENV('sessionid');
  END IF;
END TRG_USER_RIGHTS;
/


