--
-- TRG_BIR_INF2PB_ACCOUNTS  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BIR_INF2PB_ACCOUNTS
BEFORE INSERT
ON MASTER.INF2PB_ACCOUNTS
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN

  IF :NEW.ID=0 OR :NEW.ID is NULL THEN
    tmpVar := 0;
    Select seq_INF2PB_ACCOUNTS.NextVal into tmpVar from dual;
   :NEW.ID := tmpVar;
  END IF;
END TRG_BIR_INF2PB_ACCOUNTS;
/


