--
-- TRG_BIUR_NARIAD  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BIUR_NARIAD
BEFORE INSERT OR UPDATE
ON MASTER.KLS_NARIAD
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
  IF :NEW.ID=0 OR :NEW.ID is NULL THEN
    tmpVar := 0;
    Select seq_NARIAD.NextVal into tmpVar from dual;
   :NEW.ID := tmpVar;
  END IF;
  IF :NEW.DATE_BEG IS NULL THEN
    :NEW.DATE_BEG:=:NEW.DATE_NAR;
  END IF;
END TRG_BIR_NARIAD;
/


