--
-- TRG_BIUDR_PODACHA  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BIUDR_PODACHA
BEFORE INSERT OR DELETE OR UPDATE
ON MASTER.PODACHA
FOR EACH ROW
DECLARE
  v_tmp NUMBER;
BEGIN


  IF INSERTING() OR UPDATING() THEN

      IF :new.ID=0 OR :new.ID IS NULL THEN
        SELECT SEQ_PODACHA.nextval INTO :new.ID FROM DUAL;
      END IF;
  END IF;


END;
/


