--
-- TRG_BIR_AZC_OPERATION  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BIR_AZC_OPERATION
BEFORE INSERT OR UPDATE
ON MASTER.AZC_OPERATION
FOR EACH ROW
BEGIN
  IF (:NEW.ID IS NULL) OR (:NEW.ID=0) THEN
    SELECT seq_azc_operation.NEXTVAL INTO :NEW.ID FROM DUAL;
  END iF;
  :NEW.DATE_INTO:=SYSDATE;
  IF :NEW.DENCITY>2 THEN
    :NEW.DENCITY:=0;
  END IF;
END trg_bir_azc_operation;
/


