--
-- TRG_MASTER_KLS_FIELD_STRUCTURE  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_MASTER_KLS_FIELD_STRUCTURE
BEFORE INSERT OR UPDATE
ON MASTER.MASTER_KLS_FIELD_STRUCTURE
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
  IF INSERTING() OR UPDATING() THEN
    IF :NEW.ID=0 OR :NEW.ID IS NULL THEN
      tmpVar := 0;
      SELECT seq_MASTER_KLS_FIELD_STRUCTURE.NEXTVAL INTO tmpVar FROM dual;
     :NEW.ID := tmpVar;
    END IF;
  END IF;
END TRG_MASTER_KLS_FIELD_STRUCTURE;
/


