--
-- TRG_BIR_NAR_LINE  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_BIR_NAR_LINE
BEFORE INSERT
ON MASTER.KLS_NAR_LINE
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
  IF :NEW.ID=0 OR :NEW.ID is NULL THEN
    tmpVar := 0;
    Select seq_NARIAD.NextVal into tmpVar from dual;
   :NEW.ID := tmpVar;
  END IF;
END TRG_BIR_NAR_LINE;
/


