--
-- TRG_PAYMENTS_ON_BILLS_BIR  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_PAYMENTS_ON_BILLS_BIR
BEFORE INSERT
ON MASTER.PAYMENTS_ON_BILLS
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
   tmpVar := 0;
   SELECT Seq_Payments.NEXTVAL INTO tmpVar FROM dual;
--   IF :NEW.ID is null THEN
     :NEW.ID := tmpVar;
--   END IF;
END ;
/


