--
-- TRG_SF_SIGNS  (Trigger) 
--
CREATE OR REPLACE TRIGGER MASTER.TRG_SF_SIGNS
BEFORE INSERT OR UPDATE
ON MASTER.SF_SIGNS
FOR EACH ROW
BEGIN
  :NEW.TERMINAL_NAME:=For_Init.GetCurrTerm;
  :NEW.USER_NAME:=For_Init.GetCurrUser;
END TRG_SF_SIGNS;
/


