unit SystemConstants;
interface
CONST
      CONST_UNDEFINED=0;
      CONST_INVALID=1;
      CONST_OK=2;
      CONST_NOT=3;
      CONST_CANCEL=4;
      CONST_NOT_SUPPORTED=5;
      CONST_INVALID_DATA=6;
      CONST_ERROR=7;
      CONST_EXCEPTION=8;
      CONST_DOUBLE_EXCEPTION=9;
      CONST_EMPTY=10;
      CONST_INSUFFICIENT_SPACE=11;
      CONST_UNKNOWN_FORMAT=12;

      CONST_TRUE=CONST_OK;
      CONST_FALSE=CONST_NOT;


      DEFAULT_TEXTURE_SIZE_U=256;
      DEFAULT_TEXTURE_SIZE_V=256;
      DEFAULT_TEXTURE_SIZE_W=128;

implementation



end.
