-- 
-- Non Foreign Key Constraints for Table ARC_REZ 
-- 
ALTER TABLE MASTER.ARC_REZ ADD (
  CHECK ("DATEUPLOAD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ARC_REZ ADD (
  CHECK ("REZ_NUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ARC_REZ ADD (
  CHECK ("VOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ARC_REZ ADD (
  CHECK ("DEAD_VOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ARC_REZ ADD (
  CHECK ("MAX_VOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ARC_REZ ADD (
  CHECK ("AR_TOV_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ARC_REZ ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

