-- 
-- Non Foreign Key Constraints for Table AZC_PLACE_SEND 
-- 
ALTER TABLE MASTER.AZC_PLACE_SEND ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_PLACE_SEND ADD (
  CONSTRAINT PLACE_SEND_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PLACE_SEND_PK
  ENABLE VALIDATE);

