-- 
-- Foreign Key Constraints for Table AZC_GOOD_IN_WAY 
-- 
ALTER TABLE MASTER.AZC_GOOD_IN_WAY ADD (
  CONSTRAINT IN_WAY_ORG_STRU_FK 
  FOREIGN KEY (ORG_STRU_ID) 
  REFERENCES MASTER.ORG_STRUCTURE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_GOOD_IN_WAY ADD (
  CONSTRAINT IN_WAY_PLACE_SEND_FK 
  FOREIGN KEY (PLACE_SEND_ID) 
  REFERENCES MASTER.AZC_PLACE_SEND (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_GOOD_IN_WAY ADD (
  CONSTRAINT IN_WAY_PREDPR_FK 
  FOREIGN KEY (PREDPR_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_GOOD_IN_WAY ADD (
  CONSTRAINT IN_WAY_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

