-- 
-- Non Foreign Key Constraints for Table AZC_SYS_COMM 
-- 
ALTER TABLE MASTER.AZC_SYS_COMM ADD (
  CHECK ("ID_PAGE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_SYS_COMM ADD (
  CHECK ("ID_FIELD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_SYS_COMM ADD (
  CONSTRAINT PK_AZC_SYS_COMM
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_AZC_SYS_COMM
  ENABLE VALIDATE);

