-- 
-- Non Foreign Key Constraints for Table AZC_OPERATION_TMP 
-- 
ALTER TABLE MASTER.AZC_OPERATION_TMP ADD (
  CHECK ("DATE_OPER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_TMP ADD (
  CHECK ("DENCITY" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_TMP ADD (
  CHECK ("VOLUME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_TMP ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_TMP ADD (
  CHECK ("TYPE_OPER_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_TMP ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_TMP ADD (
  CHECK ("SOBSTV_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_TMP ADD (
  CHECK ("ORG_STRU_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_TMP ADD (
  CONSTRAINT PK_AZC_OPERATION_TMP
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_AZC_OPERATION_TMP
  ENABLE VALIDATE);

