-- 
-- Non Foreign Key Constraints for Table AZC_OPERATION 
-- 
ALTER TABLE MASTER.AZC_OPERATION ADD (
  CHECK ("DATE_OPER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION ADD (
  CHECK ("DENCITY" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION ADD (
  CHECK ("VOLUME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION ADD (
  CHECK ("TYPE_OPER_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION ADD (
  CHECK ("SOBSTV_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION ADD (
  CHECK ("ORG_STRU_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION ADD (
  CONSTRAINT OPERATION_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.OPERATION_PK
  ENABLE VALIDATE);

