-- 
-- Non Foreign Key Constraints for Table AZC_SYS_FIELDS 
-- 
ALTER TABLE MASTER.AZC_SYS_FIELDS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_SYS_FIELDS ADD (
  CHECK ("ALIAS_" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_SYS_FIELDS ADD (
  CONSTRAINT PK_AZC_SYS_FIELDS
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_AZC_SYS_FIELDS
  ENABLE VALIDATE);

