-- 
-- Non Foreign Key Constraints for Table AZC_OPER_MAIN 
-- 
ALTER TABLE MASTER.AZC_OPER_MAIN ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPER_MAIN ADD (
  CONSTRAINT PK_AZC_OPER_MAIN
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_AZC_OPER_MAIN
  ENABLE VALIDATE);

ALTER TABLE MASTER.AZC_OPER_MAIN ADD (
  UNIQUE (NAME)
  USING INDEX
    TABLESPACE USERSINDX
  ENABLE VALIDATE);

