-- 
-- Non Foreign Key Constraints for Table AZC_OPERATION_ARCH 
-- 
ALTER TABLE MASTER.AZC_OPERATION_ARCH ADD (
  CHECK ("DATE_OPER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_ARCH ADD (
  CHECK ("DENCITY" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_ARCH ADD (
  CHECK ("VOLUME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_ARCH ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_ARCH ADD (
  CHECK ("TYPE_OPER_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_ARCH ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_ARCH ADD (
  CHECK ("SOBSTV_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_ARCH ADD (
  CHECK ("ORG_STRU_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION_ARCH ADD (
  CONSTRAINT ARCH_OPERATION_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.ARCH_OPERATION_PK
  ENABLE VALIDATE);

