-- 
-- Non Foreign Key Constraints for Table AZC_PROD_GROUP 
-- 
ALTER TABLE MASTER.AZC_PROD_GROUP ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_PROD_GROUP ADD (
  CONSTRAINT AZC_PR_GRP_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.AZC_PR_GRP_PK
  ENABLE VALIDATE);

