-- 
-- Foreign Key Constraints for Table AZC_SYS_COMM 
-- 
ALTER TABLE MASTER.AZC_SYS_COMM ADD (
  CONSTRAINT PK_AZC_SYS_COMM_RF1 
  FOREIGN KEY (ID_FIELD) 
  REFERENCES MASTER.AZC_SYS_FIELDS (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_SYS_COMM ADD (
  CONSTRAINT PK_AZC_SYS_FIELDS_RF2 
  FOREIGN KEY (ID_PAGE) 
  REFERENCES MASTER.AZC_SYS_PAGE (ID)
  ENABLE NOVALIDATE);

