-- 
-- Foreign Key Constraints for Table AZC_REALIZ_LIKARD 
-- 
ALTER TABLE MASTER.AZC_REALIZ_LIKARD ADD (
  CONSTRAINT REL_LIKARD_ORG_STRU_FK 
  FOREIGN KEY (ORG_STRU_ID) 
  REFERENCES MASTER.ORG_STRUCTURE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_REALIZ_LIKARD ADD (
  CONSTRAINT REL_LIKARD_PREDPR_FK 
  FOREIGN KEY (SOBSTV_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_REALIZ_LIKARD ADD (
  CONSTRAINT REL_LIKARD_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

