-- 
-- Foreign Key Constraints for Table AZC_OPERATION 
-- 
ALTER TABLE MASTER.AZC_OPERATION ADD (
  CONSTRAINT OPERATION_ORG_STRU_FK 
  FOREIGN KEY (ORG_STRU_ID) 
  REFERENCES MASTER.ORG_STRUCTURE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION ADD (
  CONSTRAINT OPERATION_PLACE_SEND_FK 
  FOREIGN KEY (PLACE_SEND_ID) 
  REFERENCES MASTER.AZC_PLACE_SEND (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION ADD (
  CONSTRAINT OPERATION_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION ADD (
  CONSTRAINT OPERATION_SOBSTV_FK 
  FOREIGN KEY (SOBSTV_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPERATION ADD (
  CONSTRAINT OPERATION_TYPE_OPER_FK 
  FOREIGN KEY (TYPE_OPER_ID) 
  REFERENCES MASTER.AZC_TYPE_OPERATION (ID)
  ENABLE NOVALIDATE);

