-- 
-- Non Foreign Key Constraints for Table AZC_OPER_FIELDS 
-- 
ALTER TABLE MASTER.AZC_OPER_FIELDS ADD (
  CHECK ("N_PAGE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPER_FIELDS ADD (
  CHECK ("N_ORDER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPER_FIELDS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPER_FIELDS ADD (
  CHECK ("CAPTION" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZC_OPER_FIELDS ADD (
  CONSTRAINT PK_AZC_OPER_FIELDS
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_AZC_OPER_FIELDS
  ENABLE VALIDATE);

