-- 
-- Non Foreign Key Constraints for Table AZS_REPORTS_TMP 
-- 
ALTER TABLE MASTER.AZS_REPORTS_TMP ADD (
  CHECK ("OSUSER_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZS_REPORTS_TMP ADD (
  CHECK ("TYPE_OPER_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZS_REPORTS_TMP ADD (
  CHECK ("ORG_STRU_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZS_REPORTS_TMP ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZS_REPORTS_TMP ADD (
  CHECK ("OPER_DAY" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZS_REPORTS_TMP ADD (
  CHECK ("PRICE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZS_REPORTS_TMP ADD (
  CHECK ("VOLUME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZS_REPORTS_TMP ADD (
  CHECK ("MASSA" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.AZS_REPORTS_TMP ADD (
  CHECK ("SUMMA" IS NOT NULL)
  DISABLE NOVALIDATE);

