-- 
-- Foreign Key Constraints for Table BILLS 
-- 
ALTER TABLE MASTER.BILLS ADD (
  CONSTRAINT BILLS_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

