-- 
-- Foreign Key Constraints for Table BILL_POS_PREPAY 
-- 
ALTER TABLE MASTER.BILL_POS_PREPAY ADD (
  CONSTRAINT BILLPOS_PP_BILLS_PREP_FK 
  FOREIGN KEY (NOM_DOK) 
  REFERENCES MASTER.BILLS_PREPAY (NOM_DOK)
  ENABLE NOVALIDATE);

