-- 
-- Non Foreign Key Constraints for Table BILL_POS_PREPAY 
-- 
ALTER TABLE MASTER.BILL_POS_PREPAY ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILL_POS_PREPAY ADD (
  CHECK ("CENA_BN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILL_POS_PREPAY ADD (
  CHECK ("CENA" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILL_POS_PREPAY ADD (
  CHECK ("SUMMA_BN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILL_POS_PREPAY ADD (
  CHECK ("SUMMA_AKCIZ" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILL_POS_PREPAY ADD (
  CHECK ("SUMMA_NDS20" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILL_POS_PREPAY ADD (
  CHECK ("SUMMA_GSM25" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILL_POS_PREPAY ADD (
  CHECK ("SUMMA" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILL_POS_PREPAY ADD (
  CHECK ("OWNERSHIP_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILL_POS_PREPAY ADD (
  CONSTRAINT BILLPOS_PP_PK
  PRIMARY KEY
  (NOM_DOK, BILL_POS_PREPAY_ID)
  USING INDEX MASTER.BILLPOS_PP_PK
  ENABLE VALIDATE);

