-- 
-- Foreign Key Constraints for Table BILL_POS 
-- 
ALTER TABLE MASTER.BILL_POS ADD (
  CONSTRAINT BILL_POS_BILLS_FK 
  FOREIGN KEY (NOM_DOK) 
  REFERENCES MASTER.BILLS (NOM_DOK)
  ENABLE NOVALIDATE);

