-- 
-- Non Foreign Key Constraints for Table BILLS_PRIMARY 
-- 
ALTER TABLE MASTER.BILLS_PRIMARY ADD (
  CHECK ("BEGIN_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PRIMARY ADD (
  CHECK ("END_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PRIMARY ADD (
  CHECK ("PRIMARY_APPL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PRIMARY ADD (
  CONSTRAINT PK_BILLS_PRIMARY
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_BILLS_PRIMARY
  ENABLE VALIDATE);

