-- 
-- Foreign Key Constraints for Table BILLS_PARUS 
-- 
ALTER TABLE MASTER.BILLS_PARUS ADD (
  CONSTRAINT BILLS_P_DOG_FK 
  FOREIGN KEY (DOG_ID) 
  REFERENCES MASTER.KLS_DOG (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CONSTRAINT BILLS_P_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

