-- 
-- Foreign Key Constraints for Table BILLS_SNP 
-- 
ALTER TABLE MASTER.BILLS_SNP ADD (
  CONSTRAINT BILLS_SNP_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

