-- 
-- Foreign Key Constraints for Table BILL_POS_SNP 
-- 
ALTER TABLE MASTER.BILL_POS_SNP ADD (
  CONSTRAINT BILL_POS_SNP_BILLS_FK 
  FOREIGN KEY (NOM_DOK) 
  REFERENCES MASTER.BILLS_SNP (NOM_DOK)
  ENABLE NOVALIDATE);

