-- 
-- Non Foreign Key Constraints for Table BILLS 
-- 
ALTER TABLE MASTER.BILLS ADD (
  CHECK ("NOM_SF" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("DATE_VYP_SF" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("DATE_KVIT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("DATE_BUXG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("SUMMA_DOK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("NDS_DOK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("GSM_DOK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("AKCIZ_DOK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("KOL_DN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("OWNER_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("PROD_SUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("PROD_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("PROD_GSM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("PROD_AKCIZ" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("DATE_MOS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("IS_KORR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CHECK ("TO_KORR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS ADD (
  CONSTRAINT BILLS_PK
  PRIMARY KEY
  (NOM_DOK)
  USING INDEX MASTER.BILLS_PK
  ENABLE VALIDATE);

