-- 
-- Non Foreign Key Constraints for Table BILLS_PARUS 
-- 
ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("PREF_SF" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("NOM_SF" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("NPO_SF" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("DATE_VYP_SF" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("DATE_KVIT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("DATE_BUXG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("SUMMA_DOK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("SUMMA_PROD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("SUMMA_PROD_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("SUMMA_AKCIZ" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("SUMMA_GSM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("SUMMA_TARIF" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("SUMMA_TARIF_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("SUMMA_VOZN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("SUMMA_VOZN_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("SUMMA_STRAH" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("KOL_DN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CHECK ("USL_NUMBER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.BILLS_PARUS ADD (
  CONSTRAINT BILLS_P_PK
  PRIMARY KEY
  (NOM_DOK)
  USING INDEX MASTER.BILLS_P_PK
  ENABLE VALIDATE);

