-- 
-- Non Foreign Key Constraints for Table BUF_V_INT 
-- 
ALTER TABLE MASTER.BUF_V_INT ADD (
  CONSTRAINT BUF_V_INT_PK
  PRIMARY KEY
  (DD_MM_YYYY, SYB_RNK, N_OB, N_FID, MIN_0, MIN_1, N_INTER_RAS, N_GR_TY)
  USING INDEX MASTER.BUF_V_INT_PK
  ENABLE VALIDATE);

