-- 
-- Foreign Key Constraints for Table DAYLY_FACT 
-- 
ALTER TABLE MASTER.DAYLY_FACT ADD (
  CONSTRAINT D_FACT_PLAN_REF_FK 
  FOREIGN KEY (KOD_PLAN) 
  REFERENCES MASTER.PLAN_REFINERY (KOD)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.DAYLY_FACT ADD (
  CONSTRAINT D_FACT_PROD_FK 
  FOREIGN KEY (PROD) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

