-- 
-- Non Foreign Key Constraints for Table DIAGRAM 
-- 
ALTER TABLE MASTER.DIAGRAM ADD (
  CHECK ("TERMINAL_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DIAGRAM ADD (
  CHECK ("OSUSER_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

