-- 
-- Non Foreign Key Constraints for Table DIS_GRANTS_ 
-- 
ALTER TABLE MASTER.DIS_GRANTS_ ADD (
  CHECK ("OWNER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DIS_GRANTS_ ADD (
  CONSTRAINT DIS_DG_PK
  PRIMARY KEY
  (DOCUMENT_ID, GRANTEE)
  USING INDEX MASTER.DIS_DG_PK
  ENABLE VALIDATE);

