-- 
-- Non Foreign Key Constraints for Table DIS_DOCS_ 
-- 
ALTER TABLE MASTER.DIS_DOCS_ ADD (
  CHECK ("OWNER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DIS_DOCS_ ADD (
  CHECK ("DOCUMENT_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DIS_DOCS_ ADD (
  CHECK ("CREATE_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DIS_DOCS_ ADD (
  CHECK ("DOC_LENGTH" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DIS_DOCS_ ADD (
  CONSTRAINT DIS_DD_PK
  PRIMARY KEY
  (DOCUMENT_ID)
  USING INDEX MASTER.DIS_DD_PK
  ENABLE VALIDATE);

