-- 
-- Foreign Key Constraints for Table DIS_GRANTS_ 
-- 
ALTER TABLE MASTER.DIS_GRANTS_ ADD (
  CONSTRAINT DIS_DG_DD_FK 
  FOREIGN KEY (DOCUMENT_ID) 
  REFERENCES MASTER.DIS_DOCS_ (DOCUMENT_ID)
  DISABLE NOVALIDATE);

