-- 
-- Non Foreign Key Constraints for Table DISP_AZS_MANUAL 
-- 
ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OSUSER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("TERMINAL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("ORG_STRU_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("IN_O_VOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("IN_O_MAS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_VOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_MAS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("END_VOLUME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("END_MASSA" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_1_VOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_1_MAS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_2_VOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_2_MAS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_3_VOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_3_MAS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_4_VOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_4_MAS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_5_VOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_5_MAS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_6_VOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_6_MAS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_7_VOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CHECK ("OUT_O_7_MAS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DISP_AZS_MANUAL ADD (
  CONSTRAINT PK_DISP_AZS_MANUAL
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_DISP_AZS_MANUAL
  ENABLE VALIDATE);

