-- 
-- Non Foreign Key Constraints for Table DOC_STREAM 
-- 
ALTER TABLE MASTER.DOC_STREAM ADD (
  CHECK ("TAG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DOC_STREAM ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.DOC_STREAM ADD (
  CONSTRAINT PK_DOC_STREAM
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_DOC_STREAM
  ENABLE VALIDATE);

