-- 
-- Non Foreign Key Constraints for Table ENVIRONMENT_GRP 
-- 
ALTER TABLE MASTER.ENVIRONMENT_GRP ADD (
  CONSTRAINT ENV_GRP_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.ENV_GRP_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.ENVIRONMENT_GRP ADD (
  CONSTRAINT ENV_GRP_ENV_GRP_AK_UK
  UNIQUE (GRP_NAME)
  USING INDEX MASTER.ENV_GRP_ENV_GRP_AK_UK
  ENABLE VALIDATE);

