-- 
-- Foreign Key Constraints for Table ENVIRONMENT 
-- 
ALTER TABLE MASTER.ENVIRONMENT ADD (
  CONSTRAINT ENV_ENV_FK 
  FOREIGN KEY (MASTER_ID) 
  REFERENCES MASTER.ENVIRONMENT (ID)
  ENABLE NOVALIDATE);

