-- 
-- Non Foreign Key Constraints for Table ENVIRONMENT 
-- 
ALTER TABLE MASTER.ENVIRONMENT ADD (
  CHECK ("ENV_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ENVIRONMENT ADD (
  CHECK ("ENV_TYPES_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ENVIRONMENT ADD (
  CHECK ("APPL_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ENVIRONMENT ADD (
  CONSTRAINT ENV_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.ENV_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.ENVIRONMENT ADD (
  CONSTRAINT ENV_UK
  UNIQUE (APPL_NAME, ENV_GRP_ID, NETUSER, ENV_NAME)
  USING INDEX MASTER.ENV_UK
  ENABLE VALIDATE);

