-- 
-- Non Foreign Key Constraints for Table ENVIRONMENT_TYPES 
-- 
ALTER TABLE MASTER.ENVIRONMENT_TYPES ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ENVIRONMENT_TYPES ADD (
  CONSTRAINT ENV_TYPES_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.ENV_TYPES_PK
  ENABLE VALIDATE);

