-- 
-- Non Foreign Key Constraints for Table EUL_BATCH_PARAMS 
-- 
ALTER TABLE MASTER.EUL_BATCH_PARAMS ADD (
  CHECK ("BP_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BATCH_PARAMS ADD (
  CHECK ("BP_VALUE1" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BATCH_PARAMS ADD (
  CHECK ("BP_BS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BATCH_PARAMS ADD (
  CONSTRAINT EUL_BP_PK
  PRIMARY KEY
  (BP_ID)
  USING INDEX MASTER.EUL_BP_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_BATCH_PARAMS ADD (
  CONSTRAINT EUL_BP_BP1_UK
  UNIQUE (BP_BS_ID, BP_NAME)
  USING INDEX MASTER.EUL_BP_BP1_UK
  ENABLE VALIDATE);

