-- 
-- Non Foreign Key Constraints for Table EUL_SQ_CRRLTNS 
-- 
ALTER TABLE MASTER.EUL_SQ_CRRLTNS ADD (
  CHECK ("SQC_SQ_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SQ_CRRLTNS ADD (
  CHECK ("SQC_IT_INNER_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SQ_CRRLTNS ADD (
  CHECK ("SQC_IT_OUTER_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SQ_CRRLTNS ADD (
  CONSTRAINT EUL_SQC_PK
  PRIMARY KEY
  (SQC_ID)
  USING INDEX MASTER.EUL_SQC_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_SQ_CRRLTNS ADD (
  CONSTRAINT EUL_SQC_SQC2_UK
  UNIQUE (SQC_SQ_ID, SQC_IT_INNER_ID, SQC_IT_OUTER_ID)
  USING INDEX MASTER.EUL_SQC_SQC2_UK
  ENABLE VALIDATE);

