-- 
-- Non Foreign Key Constraints for Table EUL_FREQ_UNITS 
-- 
ALTER TABLE MASTER.EUL_FREQ_UNITS ADD (
  CHECK ("RFU_NAME_MN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FREQ_UNITS ADD (
  CHECK ("RFU_SQL_EXPRESSION" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FREQ_UNITS ADD (
  CONSTRAINT EUL_RFU_PK
  PRIMARY KEY
  (RFU_ID)
  USING INDEX MASTER.EUL_RFU_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_FREQ_UNITS ADD (
  CONSTRAINT EUL_RFU_RFU2_UK
  UNIQUE (RFU_NAME_MN)
  USING INDEX MASTER.EUL_RFU_RFU2_UK
  ENABLE VALIDATE);

