-- 
-- Foreign Key Constraints for Table EUL_HIERARCHIES 
-- 
ALTER TABLE MASTER.EUL_HIERARCHIES ADD (
  CONSTRAINT EUL_IBH_DBH_FK 
  FOREIGN KEY (IBH_DBH_ID) 
  REFERENCES MASTER.EUL_HIERARCHIES (HI_ID)
  ENABLE NOVALIDATE);

