-- 
-- Non Foreign Key Constraints for Table EUL_BA_OBJ_LINKS 
-- 
ALTER TABLE MASTER.EUL_BA_OBJ_LINKS ADD (
  CHECK ("BOL_BA_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BA_OBJ_LINKS ADD (
  CHECK ("BOL_OBJ_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BA_OBJ_LINKS ADD (
  CONSTRAINT EUL_BOL_PK
  PRIMARY KEY
  (BOL_ID)
  USING INDEX MASTER.EUL_BOL_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_BA_OBJ_LINKS ADD (
  CONSTRAINT EUL_BOL_BOL1_UK
  UNIQUE (BOL_BA_ID, BOL_OBJ_ID)
  USING INDEX MASTER.EUL_BOL_BOL1_UK
  ENABLE VALIDATE);

