-- 
-- Non Foreign Key Constraints for Table EUL_BATCH_REPORTS 
-- 
ALTER TABLE MASTER.EUL_BATCH_REPORTS ADD (
  CONSTRAINT EUL_BR_CHECK_1
  CHECK ( br_auto_refresh IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BATCH_REPORTS ADD (
  CHECK ("BR_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BATCH_REPORTS ADD (
  CHECK ("BR_WORKBOOK_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BATCH_REPORTS ADD (
  CHECK ("BR_EU_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BATCH_REPORTS ADD (
  CHECK ("BR_RFU_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BATCH_REPORTS ADD (
  CHECK ("BR_AUTO_REFRESH" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BATCH_REPORTS ADD (
  CHECK ("BR_REPORT_SCHEMA" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BATCH_REPORTS ADD (
  CONSTRAINT EUL_BR_PK
  PRIMARY KEY
  (BR_ID)
  USING INDEX MASTER.EUL_BR_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_BATCH_REPORTS ADD (
  CONSTRAINT EUL_BR_BR2_UK
  UNIQUE (BR_NAME)
  USING INDEX MASTER.EUL_BR_BR2_UK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_BATCH_REPORTS ADD (
  CONSTRAINT EUL_BR_BR3_UK
  UNIQUE (BR_JOB_ID)
  USING INDEX MASTER.EUL_BR_BR3_UK
  ENABLE VALIDATE);

