-- 
-- Foreign Key Constraints for Table EUL_IG_EXP_LINKS 
-- 
ALTER TABLE MASTER.EUL_IG_EXP_LINKS ADD (
  CONSTRAINT EUL_HIL_HN_FK 
  FOREIGN KEY (HIL_HN_ID) 
  REFERENCES MASTER.EUL_HI_NODES (HN_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_IG_EXP_LINKS ADD (
  CONSTRAINT EUL_HIL_IT_FK 
  FOREIGN KEY (HIL_EXP_ID) 
  REFERENCES MASTER.EUL_EXPRESSIONS (EXP_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_IG_EXP_LINKS ADD (
  CONSTRAINT EUL_KIL_IT_FK 
  FOREIGN KEY (KIL_EXP_ID) 
  REFERENCES MASTER.EUL_EXPRESSIONS (EXP_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_IG_EXP_LINKS ADD (
  CONSTRAINT EUL_KIL_KEY_FK 
  FOREIGN KEY (KIL_KEY_ID) 
  REFERENCES MASTER.EUL_KEY_CONS (KEY_ID)
  ENABLE NOVALIDATE);

