-- 
-- Non Foreign Key Constraints for Table EUL_FUN_ARGUMENTS 
-- 
ALTER TABLE MASTER.EUL_FUN_ARGUMENTS ADD (
  CONSTRAINT EUL_FA_CHECK_1
  CHECK ( fa_name_s is not null or fa_name_mn is not null )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUN_ARGUMENTS ADD (
  CONSTRAINT EUL_FA_CHECK_2
  CHECK ( fa_data_type IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUN_ARGUMENTS ADD (
  CONSTRAINT EUL_FA_CHECK_3
  CHECK ( fa_optional IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUN_ARGUMENTS ADD (
  CHECK ("FA_DATA_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUN_ARGUMENTS ADD (
  CHECK ("FA_OPTIONAL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUN_ARGUMENTS ADD (
  CHECK ("FA_POSITION" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUN_ARGUMENTS ADD (
  CHECK ("FA_FUN_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUN_ARGUMENTS ADD (
  CONSTRAINT EUL_FA_PK
  PRIMARY KEY
  (FA_ID)
  USING INDEX MASTER.EUL_FA_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_FUN_ARGUMENTS ADD (
  CONSTRAINT EUL_FA_FA1_UK
  UNIQUE (FA_POSITION, FA_FUN_ID)
  USING INDEX MASTER.EUL_FA_FA1_UK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_FUN_ARGUMENTS ADD (
  CONSTRAINT EUL_FA_FA2_UK
  UNIQUE (FA_NAME_MN, FA_NAME_S, FA_FUN_ID)
  USING INDEX MASTER.EUL_FA_FA2_UK
  ENABLE VALIDATE);

