-- 
-- Non Foreign Key Constraints for Table EUL_FUNCTIONS 
-- 
ALTER TABLE MASTER.EUL_FUNCTIONS ADD (
  CONSTRAINT EUL_FUN_CHECK_1
  CHECK ( nvl(fun_maximum_args, fun_minimum_args) >= fun_minimum_args )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUNCTIONS ADD (
  CONSTRAINT EUL_FUN_CHECK_2
  CHECK ( fun_function_type IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUNCTIONS ADD (
  CONSTRAINT EUL_FUN_CHECK_3
  CHECK ( fun_hidden IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUNCTIONS ADD (
  CONSTRAINT EUL_FUN_CHECK_4
  CHECK ( fun_data_type IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUNCTIONS ADD (
  CONSTRAINT EUL_FUN_CHECK_5
  CHECK ( fun_available IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUNCTIONS ADD (
  CONSTRAINT EUL_FUN_CHECK_6
  CHECK ( fun_built_in IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUNCTIONS ADD (
  CHECK ("FUN_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUNCTIONS ADD (
  CHECK ("FUN_FUNCTION_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUNCTIONS ADD (
  CHECK ("FUN_HIDDEN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUNCTIONS ADD (
  CHECK ("FUN_DATA_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUNCTIONS ADD (
  CHECK ("FUN_AVAILABLE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUNCTIONS ADD (
  CHECK ("FUN_MINIMUM_ARGS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUNCTIONS ADD (
  CHECK ("FUN_BUILT_IN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUNCTIONS ADD (
  CONSTRAINT EUL_FUN_PK
  PRIMARY KEY
  (FUN_ID)
  USING INDEX MASTER.EUL_FUN_PK
  ENABLE VALIDATE);

