-- 
-- Non Foreign Key Constraints for Table EUL_BR_RUNS 
-- 
ALTER TABLE MASTER.EUL_BR_RUNS ADD (
  CONSTRAINT EUL_BRR_CHECK_1
  CHECK ( brr_state in (0,  1,  2,  3,  4,  5,  6,  7,  8,  9) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BR_RUNS ADD (
  CHECK ("BRR_BR_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BR_RUNS ADD (
  CHECK ("BRR_RUN_NUMBER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BR_RUNS ADD (
  CHECK ("BRR_STATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BR_RUNS ADD (
  CONSTRAINT EUL_BRR_PK
  PRIMARY KEY
  (BRR_ID)
  USING INDEX MASTER.EUL_BRR_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_BR_RUNS ADD (
  CONSTRAINT EUL_BRR_BRR2_UK
  UNIQUE (BRR_BR_ID, BRR_RUN_NUMBER)
  USING INDEX MASTER.EUL_BRR_BRR2_UK
  ENABLE VALIDATE);

