-- 
-- Non Foreign Key Constraints for Table EUL_ACCESS_PRIVS 
-- 
ALTER TABLE MASTER.EUL_ACCESS_PRIVS ADD (
  CONSTRAINT EUL_AP_CHECK_1
  CHECK ( ap_type IN ( 'GBA' ,  'GP' ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_ACCESS_PRIVS ADD (
  CONSTRAINT EUL_AP_CHECK_2
  CHECK ( gba_admin_priv IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_ACCESS_PRIVS ADD (
  CHECK ("AP_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_ACCESS_PRIVS ADD (
  CHECK ("AP_EU_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_ACCESS_PRIVS ADD (
  CONSTRAINT EUL_AP_PK
  PRIMARY KEY
  (AP_ID)
  USING INDEX MASTER.EUL_AP_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_ACCESS_PRIVS ADD (
  CONSTRAINT EUL_AP_AP1_UK
  UNIQUE (GP_APP_ID, GBA_BA_ID, AP_EU_ID)
  USING INDEX MASTER.EUL_AP_AP1_UK
  ENABLE VALIDATE);

