-- 
-- Non Foreign Key Constraints for Table EUL_SUB_QUERIES 
-- 
ALTER TABLE MASTER.EUL_SUB_QUERIES ADD (
  CHECK ("SQ_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUB_QUERIES ADD (
  CHECK ("SQ_OBJ_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUB_QUERIES ADD (
  CHECK ("SQ_IT_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUB_QUERIES ADD (
  CHECK ("SQ_FIL_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUB_QUERIES ADD (
  CONSTRAINT EUL_SQ_PK
  PRIMARY KEY
  (SQ_ID)
  USING INDEX MASTER.EUL_SQ_PK
  ENABLE VALIDATE);

