-- 
-- Non Foreign Key Constraints for Table EUL_OBJS 
-- 
ALTER TABLE MASTER.EUL_OBJS ADD (
  CONSTRAINT EUL_OBJ_CHECK_1
  CHECK ( obj_type IN ( 'COBJ' ,  'SOBJ',  'CUO' ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_OBJS ADD (
  CONSTRAINT EUL_OBJ_CHECK_2
  CHECK ( obj_hidden IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_OBJS ADD (
  CONSTRAINT EUL_OBJ_CHECK_3
  CHECK ( obj_distinct_flag IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_OBJS ADD (
  CHECK ("OBJ_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_OBJS ADD (
  CHECK ("OBJ_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_OBJS ADD (
  CHECK ("OBJ_HIDDEN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_OBJS ADD (
  CHECK ("OBJ_DISTINCT_FLAG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_OBJS ADD (
  CONSTRAINT EUL_OBJ_PK
  PRIMARY KEY
  (OBJ_ID)
  USING INDEX MASTER.EUL_OBJ_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_OBJS ADD (
  CONSTRAINT EUL_OBJ_OBJ1_UK
  UNIQUE (OBJ_NAME)
  USING INDEX MASTER.EUL_OBJ_OBJ1_UK
  ENABLE VALIDATE);

