-- 
-- Non Foreign Key Constraints for Table EUL_VERSIONS 
-- 
ALTER TABLE MASTER.EUL_VERSIONS ADD (
  CHECK ("VER_EUL_TIMESTAMP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_VERSIONS ADD (
  CHECK ("VER_MIN_CODE_VER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_VERSIONS ADD (
  CHECK ("VER_RELEASE" IS NOT NULL)
  DISABLE NOVALIDATE);

