-- 
-- Foreign Key Constraints for Table EUL_HI_NODES 
-- 
ALTER TABLE MASTER.EUL_HI_NODES ADD (
  CONSTRAINT EUL_HN_IBH_FK 
  FOREIGN KEY (HN_HI_ID) 
  REFERENCES MASTER.EUL_HIERARCHIES (HI_ID)
  ENABLE NOVALIDATE);

