-- 
-- Non Foreign Key Constraints for Table EUL_DBH_NODES 
-- 
ALTER TABLE MASTER.EUL_DBH_NODES ADD (
  CHECK ("DHN_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_DBH_NODES ADD (
  CHECK ("DHN_DATA_FMT_MSK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_DBH_NODES ADD (
  CHECK ("DHN_DISP_FMT_MSK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_DBH_NODES ADD (
  CHECK ("DHN_HI_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_DBH_NODES ADD (
  CONSTRAINT EUL_DHN_PK
  PRIMARY KEY
  (DHN_ID)
  USING INDEX MASTER.EUL_DHN_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_DBH_NODES ADD (
  CONSTRAINT EUL_DHN_DHN1_UK
  UNIQUE (DHN_HI_ID, DHN_NAME)
  USING INDEX MASTER.EUL_DHN_DHN1_UK
  ENABLE VALIDATE);

