-- 
-- Non Foreign Key Constraints for Table EUL_GATEWAYS 
-- 
ALTER TABLE MASTER.EUL_GATEWAYS ADD (
  CONSTRAINT EUL_GW_CHECK_1
  CHECK ( gw_type IN ('EGW',  'BGW') )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_GATEWAYS ADD (
  CONSTRAINT EUL_GW_CHECK_2
  CHECK ( egw_sql_paradigm in ('TABLE', 'OBJECT') )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_GATEWAYS ADD (
  CHECK ("GW_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_GATEWAYS ADD (
  CHECK ("GW_GATEWAY_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_GATEWAYS ADD (
  CHECK ("GW_PRODUCT_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_GATEWAYS ADD (
  CONSTRAINT EUL_GW_PK
  PRIMARY KEY
  (GW_ID)
  USING INDEX MASTER.EUL_GW_PK
  ENABLE VALIDATE);

