-- 
-- Foreign Key Constraints for Table EUL_BATCH_SHEETS 
-- 
ALTER TABLE MASTER.EUL_BATCH_SHEETS ADD (
  CONSTRAINT EUL_BS_BR_FK 
  FOREIGN KEY (BS_BR_ID) 
  REFERENCES MASTER.EUL_BATCH_REPORTS (BR_ID)
  ENABLE NOVALIDATE);

