-- 
-- Non Foreign Key Constraints for Table EUL_JOIN_COMBS 
-- 
ALTER TABLE MASTER.EUL_JOIN_COMBS ADD (
  CONSTRAINT EUL_JC_CHECK_1
  CHECK ( jc_type IN ( 'HSP' ,  'JC' ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_JOIN_COMBS ADD (
  CHECK ("JC_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_JOIN_COMBS ADD (
  CONSTRAINT EUL_JC_PK
  PRIMARY KEY
  (JC_ID)
  USING INDEX MASTER.EUL_JC_PK
  ENABLE VALIDATE);

