-- 
-- Non Foreign Key Constraints for Table EUL_SEQUENCES 
-- 
ALTER TABLE MASTER.EUL_SEQUENCES ADD (
  CHECK ("SEQ_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SEQUENCES ADD (
  CHECK ("SEQ_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SEQUENCES ADD (
  CHECK ("SEQ_NEXTVAL" IS NOT NULL)
  DISABLE NOVALIDATE);

