-- 
-- Non Foreign Key Constraints for Table EUL_BATCH_QUERIES 
-- 
ALTER TABLE MASTER.EUL_BATCH_QUERIES ADD (
  CHECK ("BQ_BS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BATCH_QUERIES ADD (
  CHECK ("BQ_QUERY_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BATCH_QUERIES ADD (
  CONSTRAINT EUL_BQ_PK
  PRIMARY KEY
  (BQ_ID)
  USING INDEX MASTER.EUL_BQ_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_BATCH_QUERIES ADD (
  CONSTRAINT EUL_BQ_BQ1_UK
  UNIQUE (BQ_BS_ID, BQ_QUERY_ID)
  USING INDEX MASTER.EUL_BQ_BQ1_UK
  ENABLE VALIDATE);

