-- 
-- Non Foreign Key Constraints for Table EUL_KEY_CONS 
-- 
ALTER TABLE MASTER.EUL_KEY_CONS ADD (
  CONSTRAINT EUL_KEY_CHECK_1
  CHECK ( key_type IN ( 'PK' ,  'CK' ,  'FK' ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_KEY_CONS ADD (
  CONSTRAINT EUL_KEY_CHECK_2
  CHECK ( key_type != 'FK' or key_obj_id != fk_obj_id_remote )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_KEY_CONS ADD (
  CONSTRAINT EUL_KEY_CHECK_3
  CHECK ( key_type != 'FK' or fk_mandatory = 0 or fk_outer_detail = 0 )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_KEY_CONS ADD (
  CONSTRAINT EUL_KEY_CHECK_4
  CHECK ( fk_mandatory IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_KEY_CONS ADD (
  CONSTRAINT EUL_KEY_CHECK_5
  CHECK ( fk_one_to_one IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_KEY_CONS ADD (
  CONSTRAINT EUL_KEY_CHECK_6
  CHECK ( fk_outer_detail IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_KEY_CONS ADD (
  CONSTRAINT EUL_KEY_CHECK_7
  CHECK ( fk_outer_master IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_KEY_CONS ADD (
  CHECK ("KEY_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_KEY_CONS ADD (
  CHECK ("KEY_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_KEY_CONS ADD (
  CHECK ("KEY_OBJ_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_KEY_CONS ADD (
  CONSTRAINT EUL_KEY_PK
  PRIMARY KEY
  (KEY_ID)
  USING INDEX MASTER.EUL_KEY_PK
  ENABLE VALIDATE);

