-- 
-- Foreign Key Constraints for Table EUL_SBO_DSGN_ELEMS 
-- 
ALTER TABLE MASTER.EUL_SBO_DSGN_ELEMS ADD (
  CONSTRAINT EUL_SAIL_IT_FK 
  FOREIGN KEY (SAIL_EXP_ID) 
  REFERENCES MASTER.EUL_EXPRESSIONS (EXP_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SBO_DSGN_ELEMS ADD (
  CONSTRAINT EUL_SDE_SBO_FK 
  FOREIGN KEY (SDE_SUMO_ID) 
  REFERENCES MASTER.EUL_SUMMARY_OBJS (SUMO_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SBO_DSGN_ELEMS ADD (
  CONSTRAINT EUL_SMIL_FUN_FK 
  FOREIGN KEY (SMIL_FUN_ID) 
  REFERENCES MASTER.EUL_FUNCTIONS (FUN_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SBO_DSGN_ELEMS ADD (
  CONSTRAINT EUL_SMIL_IT_FK 
  FOREIGN KEY (SMIL_EXP_ID) 
  REFERENCES MASTER.EUL_EXPRESSIONS (EXP_ID)
  ENABLE NOVALIDATE);

