-- 
-- Non Foreign Key Constraints for Table EUL_SUMMARY_OBJS 
-- 
ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CONSTRAINT EUL_SUMO_CHECK_1
  CHECK ( sumo_type = 'SBO' or sdo_bitmap_pos is not null )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CONSTRAINT EUL_SUMO_CHECK_2
  CHECK ( sumo_type IN ( 'SBO' ,  'MSDO' ,  'NMSDO' ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CONSTRAINT EUL_SUMO_CHECK_3
  CHECK ( sumo_internal IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CONSTRAINT EUL_SUMO_CHECK_4
  CHECK ( sumo_item_deleted IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CONSTRAINT EUL_SUMO_CHECK_5
  CHECK ( sumo_item_modified IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CONSTRAINT EUL_SUMO_CHECK_6
  CHECK ( sumo_join_state IN ( 1 ,  2 ,  3 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CONSTRAINT EUL_SUMO_CHECK_7
  CHECK ( sumo_validity IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CONSTRAINT EUL_SUMO_CHECK_8
  CHECK ( sdo_state IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CHECK ("SUMO_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CHECK ("SUMO_INTERNAL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CHECK ("SUMO_ITEM_DELETED" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CHECK ("SUMO_ITEM_MODIFIED" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CHECK ("SUMO_JOIN_STATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CHECK ("SUMO_VALIDITY" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CONSTRAINT EUL_SUMO_PK
  PRIMARY KEY
  (SUMO_ID)
  USING INDEX MASTER.EUL_SUMO_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_SUMMARY_OBJS ADD (
  CONSTRAINT EUL_SUMO_SUMO1_UK
  UNIQUE (SBO_SRS_ID, SDO_BITMAP_POS, SBO_NAME)
  USING INDEX MASTER.EUL_SUMO_SUMO1_UK
  ENABLE VALIDATE);

