-- 
-- Foreign Key Constraints for Table EUL_BQ_TABLES 
-- 
ALTER TABLE MASTER.EUL_BQ_TABLES ADD (
  CONSTRAINT EUL_BQT_BQ_FK 
  FOREIGN KEY (BQT_BQ_ID) 
  REFERENCES MASTER.EUL_BATCH_QUERIES (BQ_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BQ_TABLES ADD (
  CONSTRAINT EUL_BQT_BRR_FK 
  FOREIGN KEY (BQT_BRR_ID) 
  REFERENCES MASTER.EUL_BR_RUNS (BRR_ID)
  ENABLE NOVALIDATE);

