-- 
-- Non Foreign Key Constraints for Table EUL_FUN_CATEGORIES 
-- 
ALTER TABLE MASTER.EUL_FUN_CATEGORIES ADD (
  CONSTRAINT EUL_FC_CHECK_1
  CHECK ( fc_name_s is not null or fc_name_mn is not null )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUN_CATEGORIES ADD (
  CONSTRAINT EUL_FC_PK
  PRIMARY KEY
  (FC_ID)
  USING INDEX MASTER.EUL_FC_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_FUN_CATEGORIES ADD (
  CONSTRAINT EUL_FC_FC2_UK
  UNIQUE (FC_NAME_MN, FC_NAME_S)
  USING INDEX MASTER.EUL_FC_FC2_UK
  ENABLE VALIDATE);

