-- 
-- Non Foreign Key Constraints for Table EUL_BQ_TABLES 
-- 
ALTER TABLE MASTER.EUL_BQ_TABLES ADD (
  CHECK ("BQT_BQ_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BQ_TABLES ADD (
  CHECK ("BQT_BRR_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BQ_TABLES ADD (
  CHECK ("BQT_TABLE_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BQ_TABLES ADD (
  CONSTRAINT EUL_BQT_PK
  PRIMARY KEY
  (BQT_ID)
  USING INDEX MASTER.EUL_BQT_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_BQ_TABLES ADD (
  CONSTRAINT EUL_BQT_BQT2_UK
  UNIQUE (BQT_TABLE_NAME)
  USING INDEX MASTER.EUL_BQT_BQT2_UK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_BQ_TABLES ADD (
  CONSTRAINT EUL_BQT_BQT3_UK
  UNIQUE (BQT_BQ_ID, BQT_BRR_ID)
  USING INDEX MASTER.EUL_BQT_BQT3_UK
  ENABLE VALIDATE);

