-- 
-- Non Foreign Key Constraints for Table EUL_SBO_DSGN_ELEMS 
-- 
ALTER TABLE MASTER.EUL_SBO_DSGN_ELEMS ADD (
  CONSTRAINT EUL_SDE_CHECK_1
  CHECK ( sde_type IN ( 'SAIL' ,  'SMIL' ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SBO_DSGN_ELEMS ADD (
  CONSTRAINT EUL_SDE_CHECK_2
  CHECK ( sde_formula_mod IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SBO_DSGN_ELEMS ADD (
  CHECK ("SDE_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SBO_DSGN_ELEMS ADD (
  CHECK ("SDE_SUMO_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SBO_DSGN_ELEMS ADD (
  CHECK ("SDE_FORMULA_MOD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SBO_DSGN_ELEMS ADD (
  CONSTRAINT EUL_SDE_PK
  PRIMARY KEY
  (SDE_ID)
  USING INDEX MASTER.EUL_SDE_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_SBO_DSGN_ELEMS ADD (
  CONSTRAINT EUL_SDE_SDE1_UK
  UNIQUE (SDE_SUMO_ID, SAIL_EXP_ID, SMIL_EXP_ID, SMIL_FUN_ID)
  USING INDEX MASTER.EUL_SDE_SDE1_UK
  ENABLE VALIDATE);

