-- 
-- Foreign Key Constraints for Table EUL_HI_SEGMENTS 
-- 
ALTER TABLE MASTER.EUL_HI_SEGMENTS ADD (
  CONSTRAINT EUL_DHS_DBH_FK 
  FOREIGN KEY (DHS_HI_ID) 
  REFERENCES MASTER.EUL_HIERARCHIES (HI_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_HI_SEGMENTS ADD (
  CONSTRAINT EUL_DHS_DHN_C_FK 
  FOREIGN KEY (DHS_DHN_ID_PARENT) 
  REFERENCES MASTER.EUL_DBH_NODES (DHN_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_HI_SEGMENTS ADD (
  CONSTRAINT EUL_DHS_DHN_P_FK 
  FOREIGN KEY (DHS_DHN_ID_CHILD) 
  REFERENCES MASTER.EUL_DBH_NODES (DHN_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_HI_SEGMENTS ADD (
  CONSTRAINT EUL_IHS_HN_C_FK 
  FOREIGN KEY (IHS_HN_ID_PARENT) 
  REFERENCES MASTER.EUL_HI_NODES (HN_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_HI_SEGMENTS ADD (
  CONSTRAINT EUL_IHS_HN_P_FK 
  FOREIGN KEY (IHS_HN_ID_CHILD) 
  REFERENCES MASTER.EUL_HI_NODES (HN_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_HI_SEGMENTS ADD (
  CONSTRAINT EUL_IHS_HSP_FK 
  FOREIGN KEY (IHS_JC_ID) 
  REFERENCES MASTER.EUL_JOIN_COMBS (JC_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_HI_SEGMENTS ADD (
  CONSTRAINT EUL_IHS_IBH_FK 
  FOREIGN KEY (IHS_HI_ID) 
  REFERENCES MASTER.EUL_HIERARCHIES (HI_ID)
  ENABLE NOVALIDATE);

