-- 
-- Non Foreign Key Constraints for Table EUL_OBJ_JOIN_USGS 
-- 
ALTER TABLE MASTER.EUL_OBJ_JOIN_USGS ADD (
  CONSTRAINT EUL_OJU_CHECK_1
  CHECK ( (oju_obj_id is null and oju_sumo_id is not null) or (oju_obj_id is not null and oju_sumo_id is null) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_OBJ_JOIN_USGS ADD (
  CONSTRAINT EUL_OJU_CHECK_2
  CHECK ( oju_join_modified IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_OBJ_JOIN_USGS ADD (
  CHECK ("OJU_JOIN_MODIFIED" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_OBJ_JOIN_USGS ADD (
  CHECK ("OJU_KEY_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_OBJ_JOIN_USGS ADD (
  CONSTRAINT EUL_OJU_PK
  PRIMARY KEY
  (OJU_ID)
  USING INDEX MASTER.EUL_OJU_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_OBJ_JOIN_USGS ADD (
  CONSTRAINT EUL_OJU_OJU2_UK
  UNIQUE (OJU_OBJ_ID, OJU_KEY_ID, OJU_SUMO_ID)
  USING INDEX MASTER.EUL_OJU_OJU2_UK
  ENABLE VALIDATE);

