-- 
-- Non Foreign Key Constraints for Table EUL_HI_SEGMENTS 
-- 
ALTER TABLE MASTER.EUL_HI_SEGMENTS ADD (
  CONSTRAINT EUL_HS_CHECK_1
  CHECK ( (hs_type != 'DHS' or dhs_dhn_id_child != dhs_dhn_id_parent) and (hs_type != 'IHS' or ihs_hn_id_child != ihs_hn_id_parent) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_HI_SEGMENTS ADD (
  CONSTRAINT EUL_HS_CHECK_2
  CHECK ( hs_type IN ( 'IHS' ,  'DHS' ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_HI_SEGMENTS ADD (
  CHECK ("HS_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_HI_SEGMENTS ADD (
  CONSTRAINT EUL_HS_PK
  PRIMARY KEY
  (HS_ID)
  USING INDEX MASTER.EUL_HS_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_HI_SEGMENTS ADD (
  CONSTRAINT EUL_HS_HS1_UK
  UNIQUE (IHS_HN_ID_CHILD, IHS_HN_ID_PARENT, IHS_HI_ID, DHS_HI_ID, DHS_DHN_ID_CHILD, DHS_DHN_ID_PARENT)
  USING INDEX MASTER.EUL_HS_HS1_UK
  ENABLE VALIDATE);

