-- 
-- Foreign Key Constraints for Table EUL_ACCESS_PRIVS 
-- 
ALTER TABLE MASTER.EUL_ACCESS_PRIVS ADD (
  CONSTRAINT EUL_AP_EU_FK 
  FOREIGN KEY (AP_EU_ID) 
  REFERENCES MASTER.EUL_EUL_USERS (EU_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_ACCESS_PRIVS ADD (
  CONSTRAINT EUL_GBA_BA_FK 
  FOREIGN KEY (GBA_BA_ID) 
  REFERENCES MASTER.EUL_BUSINESS_AREAS (BA_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_ACCESS_PRIVS ADD (
  CONSTRAINT EUL_GP_PRI_FK 
  FOREIGN KEY (GP_APP_ID) 
  REFERENCES MASTER.EUL_APP_PARAMS (APP_ID)
  ENABLE NOVALIDATE);

