-- 
-- Foreign Key Constraints for Table EUL_EXP_DEPS 
-- 
ALTER TABLE MASTER.EUL_EXP_DEPS ADD (
  CONSTRAINT EUL_CD_CI_FK 
  FOREIGN KEY (CD_EXP_ID) 
  REFERENCES MASTER.EUL_EXPRESSIONS (EXP_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_EXP_DEPS ADD (
  CONSTRAINT EUL_CFD_FUN_FK 
  FOREIGN KEY (CFD_FUN_ID) 
  REFERENCES MASTER.EUL_FUNCTIONS (FUN_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_EXP_DEPS ADD (
  CONSTRAINT EUL_CID_IT_FK 
  FOREIGN KEY (CID_EXP_ID) 
  REFERENCES MASTER.EUL_EXPRESSIONS (EXP_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_EXP_DEPS ADD (
  CONSTRAINT EUL_CPD_PAR_FK 
  FOREIGN KEY (CPD_EXP_ID) 
  REFERENCES MASTER.EUL_EXPRESSIONS (EXP_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_EXP_DEPS ADD (
  CONSTRAINT EUL_PD_P_FK 
  FOREIGN KEY (PD_P_ID) 
  REFERENCES MASTER.EUL_EXPRESSIONS (EXP_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_EXP_DEPS ADD (
  CONSTRAINT EUL_PED_EXP_FK 
  FOREIGN KEY (PED_EXP_ID) 
  REFERENCES MASTER.EUL_EXPRESSIONS (EXP_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_EXP_DEPS ADD (
  CONSTRAINT EUL_PFD_FUN_FK 
  FOREIGN KEY (PFD_FUN_ID) 
  REFERENCES MASTER.EUL_FUNCTIONS (FUN_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_EXP_DEPS ADD (
  CONSTRAINT EUL_PSD_SQ_FK 
  FOREIGN KEY (PSD_SQ_ID) 
  REFERENCES MASTER.EUL_SUB_QUERIES (SQ_ID)
  ENABLE NOVALIDATE);

