-- 
-- Non Foreign Key Constraints for Table EUL_BATCH_SHEETS 
-- 
ALTER TABLE MASTER.EUL_BATCH_SHEETS ADD (
  CHECK ("BS_BR_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BATCH_SHEETS ADD (
  CHECK ("BS_SHEET_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BATCH_SHEETS ADD (
  CHECK ("BS_SHEET_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BATCH_SHEETS ADD (
  CONSTRAINT EUL_BS_PK
  PRIMARY KEY
  (BS_ID)
  USING INDEX MASTER.EUL_BS_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_BATCH_SHEETS ADD (
  CONSTRAINT EUL_BS_BS2_UK
  UNIQUE (BS_BR_ID, BS_SHEET_ID)
  USING INDEX MASTER.EUL_BS_BS2_UK
  ENABLE VALIDATE);

