-- 
-- Non Foreign Key Constraints for Table EUL_BUSINESS_AREAS 
-- 
ALTER TABLE MASTER.EUL_BUSINESS_AREAS ADD (
  CHECK ("BA_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_BUSINESS_AREAS ADD (
  CONSTRAINT EUL_BA_PK
  PRIMARY KEY
  (BA_ID)
  USING INDEX MASTER.EUL_BA_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_BUSINESS_AREAS ADD (
  CONSTRAINT EUL_BA_BA1_UK
  UNIQUE (BA_NAME)
  USING INDEX MASTER.EUL_BA_BA1_UK
  ENABLE VALIDATE);

