-- 
-- Non Foreign Key Constraints for Table EUL_FUN_FC_LINKS 
-- 
ALTER TABLE MASTER.EUL_FUN_FC_LINKS ADD (
  CHECK ("FFL_FUN_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUN_FC_LINKS ADD (
  CHECK ("FFL_FC_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUN_FC_LINKS ADD (
  CONSTRAINT EUL_FFL_PK
  PRIMARY KEY
  (FFL_ID)
  USING INDEX MASTER.EUL_FFL_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_FUN_FC_LINKS ADD (
  CONSTRAINT EUL_FFL_FFL2_UK
  UNIQUE (FFL_FUN_ID, FFL_FC_ID)
  USING INDEX MASTER.EUL_FFL_FFL2_UK
  ENABLE VALIDATE);

