-- 
-- Foreign Key Constraints for Table EUL_NMSDO_JC_USGS 
-- 
ALTER TABLE MASTER.EUL_NMSDO_JC_USGS ADD (
  CONSTRAINT EUL_NJU_JC_FK 
  FOREIGN KEY (NJU_JC_ID) 
  REFERENCES MASTER.EUL_JOIN_COMBS (JC_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_NMSDO_JC_USGS ADD (
  CONSTRAINT EUL_NJU_NMSDO_FK 
  FOREIGN KEY (NJU_NMSDO_ID) 
  REFERENCES MASTER.EUL_SUMMARY_OBJS (SUMO_ID)
  ENABLE NOVALIDATE);

