-- 
-- Non Foreign Key Constraints for Table EUL_OBJ_DEPS 
-- 
ALTER TABLE MASTER.EUL_OBJ_DEPS ADD (
  CONSTRAINT EUL_OD_CHECK_1
  CHECK ( od_obj_id_from != od_obj_id_to )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_OBJ_DEPS ADD (
  CHECK ("OD_OBJ_ID_FROM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_OBJ_DEPS ADD (
  CHECK ("OD_OBJ_ID_TO" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_OBJ_DEPS ADD (
  CONSTRAINT EUL_OD_PK
  PRIMARY KEY
  (OD_ID)
  USING INDEX MASTER.EUL_OD_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_OBJ_DEPS ADD (
  CONSTRAINT EUL_OD_OD1_UK
  UNIQUE (OD_OBJ_ID_FROM, OD_OBJ_ID_TO)
  USING INDEX MASTER.EUL_OD_OD1_UK
  ENABLE VALIDATE);

