-- 
-- Foreign Key Constraints for Table EUL_BR_RUNS 
-- 
ALTER TABLE MASTER.EUL_BR_RUNS ADD (
  CONSTRAINT EUL_BRR_BR_FK 
  FOREIGN KEY (BRR_BR_ID) 
  REFERENCES MASTER.EUL_BATCH_REPORTS (BR_ID)
  ENABLE NOVALIDATE);

