-- 
-- Non Foreign Key Constraints for Table EUL_HIERARCHIES 
-- 
ALTER TABLE MASTER.EUL_HIERARCHIES ADD (
  CONSTRAINT EUL_HI_CHECK_1
  CHECK ( hi_type IN ( 'DBH' ,  'IBH' ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_HIERARCHIES ADD (
  CONSTRAINT EUL_HI_CHECK_2
  CHECK ( hi_sys_generated IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_HIERARCHIES ADD (
  CONSTRAINT EUL_HI_CHECK_3
  CHECK ( dbh_default IN ( 1 ,  0 ) )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_HIERARCHIES ADD (
  CHECK ("HI_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_HIERARCHIES ADD (
  CHECK ("HI_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_HIERARCHIES ADD (
  CHECK ("HI_SYS_GENERATED" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_HIERARCHIES ADD (
  CONSTRAINT EUL_HI_PK
  PRIMARY KEY
  (HI_ID)
  USING INDEX MASTER.EUL_HI_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_HIERARCHIES ADD (
  CONSTRAINT EUL_HI_HI1_UK
  UNIQUE (HI_NAME)
  USING INDEX MASTER.EUL_HI_HI1_UK
  ENABLE VALIDATE);

