-- 
-- Foreign Key Constraints for Table EUL_SEGMENTS 
-- 
ALTER TABLE MASTER.EUL_SEGMENTS ADD (
  CONSTRAINT EUL_OSS_BQ_FK 
  FOREIGN KEY (OSS_BQ_ID) 
  REFERENCES MASTER.EUL_BATCH_QUERIES (BQ_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SEGMENTS ADD (
  CONSTRAINT EUL_OSS_CUO_FK 
  FOREIGN KEY (OSS_CUO_ID) 
  REFERENCES MASTER.EUL_OBJS (OBJ_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SEGMENTS ADD (
  CONSTRAINT EUL_OSS_EXP_FK 
  FOREIGN KEY (OSS_EXP_ID) 
  REFERENCES MASTER.EUL_EXPRESSIONS (EXP_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SEGMENTS ADD (
  CONSTRAINT EUL_OSS_OBJ_FK 
  FOREIGN KEY (OSS_OBJ_ID) 
  REFERENCES MASTER.EUL_OBJS (OBJ_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SEGMENTS ADD (
  CONSTRAINT EUL_OSS_SDO_FK 
  FOREIGN KEY (OSS_SUMO_ID) 
  REFERENCES MASTER.EUL_SUMMARY_OBJS (SUMO_ID)
  ENABLE NOVALIDATE);

