-- 
-- Foreign Key Constraints for Table EUL_FUN_FC_LINKS 
-- 
ALTER TABLE MASTER.EUL_FUN_FC_LINKS ADD (
  CONSTRAINT EUL_FFL_FC_FK 
  FOREIGN KEY (FFL_FC_ID) 
  REFERENCES MASTER.EUL_FUN_CATEGORIES (FC_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_FUN_FC_LINKS ADD (
  CONSTRAINT EUL_FFL_FUN_FK 
  FOREIGN KEY (FFL_FUN_ID) 
  REFERENCES MASTER.EUL_FUNCTIONS (FUN_ID)
  ENABLE NOVALIDATE);

