-- 
-- Non Foreign Key Constraints for Table EUL_SUM_BITMAPS 
-- 
ALTER TABLE MASTER.EUL_SUM_BITMAPS ADD (
  CONSTRAINT EUL_SB_CHECK_1
  CHECK ( sb_exp_id is null or sb_key_id is null )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUM_BITMAPS ADD (
  CONSTRAINT EUL_SB_CHECK_2
  CHECK ( sb_fun_id is null or sb_key_id is null )
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUM_BITMAPS ADD (
  CHECK ("SB_BITMAP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUM_BITMAPS ADD (
  CHECK ("SB_SEQUENCE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.EUL_SUM_BITMAPS ADD (
  CONSTRAINT EUL_SB_PK
  PRIMARY KEY
  (SB_ID)
  USING INDEX MASTER.EUL_SB_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.EUL_SUM_BITMAPS ADD (
  CONSTRAINT EUL_SB_SB2_UK
  UNIQUE (SB_EXP_ID, SB_KEY_ID, SB_FUN_ID, SB_SEQUENCE)
  USING INDEX MASTER.EUL_SB_SB2_UK
  ENABLE VALIDATE);

