-- 
-- Non Foreign Key Constraints for Table GD_PLAN 
-- 
ALTER TABLE MASTER.GD_PLAN ADD (
  CHECK ("DATE_PLAN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CHECK ("FROM_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CHECK ("TO_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CHECK ("GROTP_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CHECK ("NAPR_MOS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CHECK ("LOAD_TYPE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CHECK ("VAGOWNER_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CHECK ("STANOTP_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CHECK ("TIP_PLAN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CONSTRAINT GD_PLAN_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.GD_PLAN_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CONSTRAINT GD_PLAN_GD_PLAN_AK_UK
  UNIQUE (TIP_PLAN, DATE_PLAN, GROTP_ID, NAPR_MOS_ID, PROD_ID_NPR, LOAD_TYPE_ID, VAGOWNER_ID, STANOTP_ID)
  USING INDEX MASTER.GD_PLAN_GD_PLAN_AK_UK
  ENABLE VALIDATE);

