-- 
-- Foreign Key Constraints for Table GD_PLAN 
-- 
ALTER TABLE MASTER.GD_PLAN ADD (
  CONSTRAINT GD_PLAN_LOAD_TYPE_FK 
  FOREIGN KEY (LOAD_TYPE_ID) 
  REFERENCES MASTER.KLS_LOAD_TYPE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CONSTRAINT GD_PLAN_NAPR_MOS_FK 
  FOREIGN KEY (NAPR_MOS_ID) 
  REFERENCES MASTER.KLS_NAPR_MOS (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CONSTRAINT GD_PLAN_PREDPR_FK 
  FOREIGN KEY (GROTP_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CONSTRAINT GD_PLAN_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CONSTRAINT GD_PLAN_STAN_FK 
  FOREIGN KEY (STANOTP_ID) 
  REFERENCES MASTER.KLS_STAN (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.GD_PLAN ADD (
  CONSTRAINT GD_PLAN_VAGOWNER_FK 
  FOREIGN KEY (VAGOWNER_ID) 
  REFERENCES MASTER.KLS_VAGOWNER (ID)
  ENABLE NOVALIDATE);

