-- 
-- Foreign Key Constraints for Table GD_RAZN_PATH 
-- 
ALTER TABLE MASTER.GD_RAZN_PATH ADD (
  CONSTRAINT GD_RZ_PATH_GD_RAZNPOS_FK 
  FOREIGN KEY (GD_RAZNPOS_ID) 
  REFERENCES MASTER.GD_RAZN_POS (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_PATH ADD (
  CONSTRAINT GD_RZ_PATH_PREDPR_FK 
  FOREIGN KEY (PREDPR_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_PATH ADD (
  CONSTRAINT GD_RZ_PATH_TIP_PATH_FK 
  FOREIGN KEY (TIP_PATH_ID) 
  REFERENCES MASTER.KLS_GD_TIP_PATH (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_PATH ADD (
  CONSTRAINT GD_RZ_PATH_VETKA_FK 
  FOREIGN KEY (VETKA_ID) 
  REFERENCES MASTER.KLS_VETKA (ID)
  ENABLE NOVALIDATE);

