-- 
-- Non Foreign Key Constraints for Table GD_RAZN 
-- 
ALTER TABLE MASTER.GD_RAZN ADD (
  CHECK ("DATE_PLAN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CHECK ("FROM_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CHECK ("TO_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CHECK ("STAN_OTP_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CHECK ("GD_OTPR_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CHECK ("LOAD_TYPE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CHECK ("GD_SOOB_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CHECK ("GD_PODACH_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CHECK ("NAPR_MOS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CONSTRAINT GD_RAZN_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.GD_RAZN_PK
  ENABLE VALIDATE);

