-- 
-- Foreign Key Constraints for Table GD_RAZN 
-- 
ALTER TABLE MASTER.GD_RAZN ADD (
  CONSTRAINT GD_RAZN_EXPED_FK 
  FOREIGN KEY (EXPED_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CONSTRAINT GD_RAZN_GD_GROUP_FK 
  FOREIGN KEY (GD_GROUP_ID) 
  REFERENCES MASTER.KLS_GD_GROUP (ID)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CONSTRAINT GD_RAZN_GD_OTPR_FK 
  FOREIGN KEY (GD_OTPR_ID) 
  REFERENCES MASTER.KLS_GD_OTPR (ID)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CONSTRAINT GD_RAZN_GD_PODACH_FK 
  FOREIGN KEY (GD_PODACH_ID) 
  REFERENCES MASTER.KLS_GD_PODACH (ID)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CONSTRAINT GD_RAZN_GD_SOOB_FK 
  FOREIGN KEY (GD_SOOB_ID) 
  REFERENCES MASTER.KLS_GD_SOOB (ID)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CONSTRAINT GD_RAZN_STAN_OTP_FK 
  FOREIGN KEY (STAN_OTP_ID) 
  REFERENCES MASTER.KLS_STAN (ID)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CONSTRAINT GD_RAZN_TRANSPORTER_FK 
  FOREIGN KEY (TRANSPORTER_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN ADD (
  CONSTRAINT GD_RAZN_VETKA_OTP_FK 
  FOREIGN KEY (VETKA_OTP_ID) 
  REFERENCES MASTER.KLS_VETKA_OTP (ID)
  DISABLE NOVALIDATE);

