-- 
-- Non Foreign Key Constraints for Table GD_RAZN_PATH 
-- 
ALTER TABLE MASTER.GD_RAZN_PATH ADD (
  CHECK ("GD_RAZNPOS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_PATH ADD (
  CHECK ("SORTBY" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_PATH ADD (
  CHECK ("TIP_PATH_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_PATH ADD (
  CHECK ("STAN_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_PATH ADD (
  CONSTRAINT GD_RZ_PATH_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.GD_RZ_PATH_PK
  ENABLE VALIDATE);

