-- 
-- Non Foreign Key Constraints for Table GD_RAZN_POS 
-- 
ALTER TABLE MASTER.GD_RAZN_POS ADD (
  CHECK ("GD_RAZN_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_POS ADD (
  CHECK ("KOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_POS ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_POS ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_POS ADD (
  CHECK ("GD_PRINVAG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_POS ADD (
  CONSTRAINT GD_RAZNPOS_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.GD_RAZNPOS_PK
  ENABLE VALIDATE);

