-- 
-- Foreign Key Constraints for Table GD_RAZN_POS 
-- 
ALTER TABLE MASTER.GD_RAZN_POS ADD (
  CONSTRAINT GD_RAZNPOS_GD_PRINVAG_FK 
  FOREIGN KEY (GD_PRINVAG_ID) 
  REFERENCES MASTER.KLS_GD_PRINVAG (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_POS ADD (
  CONSTRAINT GD_RAZNPOS_GD_RAZN_FK 
  FOREIGN KEY (GD_RAZN_ID) 
  REFERENCES MASTER.GD_RAZN (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_POS ADD (
  CONSTRAINT GD_RAZNPOS_GD_VAGTYPE_FK 
  FOREIGN KEY (GD_VAGTYPE_ID) 
  REFERENCES MASTER.KLS_GD_VAGTYPE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_POS ADD (
  CONSTRAINT GD_RAZNPOS_POLUCH_FK 
  FOREIGN KEY (POLUCH_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_POS ADD (
  CONSTRAINT GD_RAZNPOS_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_POS ADD (
  CONSTRAINT GD_RAZNPOS_STAN_FK 
  FOREIGN KEY (STAN_ID) 
  REFERENCES MASTER.KLS_STAN (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_POS ADD (
  CONSTRAINT GD_RAZNPOS_VETKA_FK 
  FOREIGN KEY (VETKA_ID) 
  REFERENCES MASTER.KLS_VETKA (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.GD_RAZN_POS ADD (
  CONSTRAINT GD_RAZNPOS_VID_OTPR_FK 
  FOREIGN KEY (VID_OTPR_ID) 
  REFERENCES MASTER.KLS_GD_VID_OTPR (ID)
  ENABLE NOVALIDATE);

