-- 
-- Non Foreign Key Constraints for Table GU12_A 
-- 
ALTER TABLE MASTER.GU12_A ADD (
  CHECK ("FROM_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GU12_A ADD (
  CHECK ("TO_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GU12_A ADD (
  CHECK ("PROD_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GU12_A ADD (
  CHECK ("FOX_KOD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GU12_A ADD (
  CONSTRAINT GU12_A_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.GU12_A_PK
  ENABLE VALIDATE);

