-- 
-- Non Foreign Key Constraints for Table GU12_BR 
-- 
ALTER TABLE MASTER.GU12_BR ADD (
  CHECK ("ID_B" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GU12_BR ADD (
  CHECK ("DATE_R" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GU12_BR ADD (
  CHECK ("KOL_VAG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GU12_BR ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GU12_BR ADD (
  CONSTRAINT GU12_BR_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.GU12_BR_PK
  ENABLE VALIDATE);

