-- 
-- Foreign Key Constraints for Table GU12_BR 
-- 
ALTER TABLE MASTER.GU12_BR ADD (
  CONSTRAINT GU12_BR_GU12_B_FK 
  FOREIGN KEY (ID_B) 
  REFERENCES MASTER.GU12_B (ID)
  ON DELETE CASCADE
  ENABLE NOVALIDATE);

