-- 
-- Non Foreign Key Constraints for Table GU12_B 
-- 
ALTER TABLE MASTER.GU12_B ADD (
  CHECK ("STAN_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GU12_B ADD (
  CHECK ("KOL_VAG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GU12_B ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GU12_B ADD (
  CHECK ("ID_A" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GU12_B ADD (
  CHECK ("FOX_KOD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.GU12_B ADD (
  CONSTRAINT GU12_B_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.GU12_B_PK
  ENABLE VALIDATE);

