-- 
-- Non Foreign Key Constraints for Table INF2PB_SCH 
-- 
ALTER TABLE MASTER.INF2PB_SCH ADD (
  CHECK ("SCH" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.INF2PB_SCH ADD (
  CHECK ("CONT_AN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.INF2PB_SCH ADD (
  CHECK ("RAS_AN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.INF2PB_SCH ADD (
  CONSTRAINT INF2PB_SCH_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.INF2PB_SCH_PK
  ENABLE VALIDATE);

