-- 
-- Foreign Key Constraints for Table INF2PB_ACCOUNTS 
-- 
ALTER TABLE MASTER.INF2PB_ACCOUNTS ADD (
  CONSTRAINT INF2PB_ACC_INF2PB_SCH_FK 
  FOREIGN KEY (INF2PB_SCH_ID) 
  REFERENCES MASTER.INF2PB_SCH (ID)
  ENABLE NOVALIDATE);

