-- 
-- Non Foreign Key Constraints for Table INF2PB_ACCOUNTS 
-- 
ALTER TABLE MASTER.INF2PB_ACCOUNTS ADD (
  CHECK ("INF2PB_SCH_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.INF2PB_ACCOUNTS ADD (
  CHECK ("PROMIS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.INF2PB_ACCOUNTS ADD (
  CHECK ("PAY_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.INF2PB_ACCOUNTS ADD (
  CHECK ("STATUS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.INF2PB_ACCOUNTS ADD (
  CONSTRAINT INF2PB_ACC_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.INF2PB_ACC_PK
  ENABLE VALIDATE);

