-- 
-- Non Foreign Key Constraints for Table ISU_TAX_FILES 
-- 
ALTER TABLE MASTER.ISU_TAX_FILES ADD (
  CONSTRAINT ISU_TAX_FILES_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.ISU_TAX_FILES_PK
  ENABLE VALIDATE);

