-- 
-- Non Foreign Key Constraints for Table ISU_TAX_PACKAGE 
-- 
ALTER TABLE MASTER.ISU_TAX_PACKAGE ADD (
  CONSTRAINT ISU_TAX_PACK_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.ISU_TAX_PACK_PK
  ENABLE VALIDATE);

