-- 
-- Non Foreign Key Constraints for Table ISU_BILLS 
-- 
ALTER TABLE MASTER.ISU_BILLS ADD (
  CONSTRAINT ISU_BILLS_PK
  PRIMARY KEY
  (ISU_KOD)
  USING INDEX MASTER.ISU_BILLS_PK
  ENABLE VALIDATE);

