-- 
-- Non Foreign Key Constraints for Table ISU_TAX_REASON 
-- 
ALTER TABLE MASTER.ISU_TAX_REASON ADD (
  CONSTRAINT ISU_TAX_REASON_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.ISU_TAX_REASON_PK
  ENABLE VALIDATE);

