-- 
-- Non Foreign Key Constraints for Table ISU_BILL_POS 
-- 
ALTER TABLE MASTER.ISU_BILL_POS ADD (
  CONSTRAINT ISU_BILL_POS_PK
  PRIMARY KEY
  (ISU_KOD_POS)
  USING INDEX MASTER.ISU_BILL_POS_PK
  ENABLE VALIDATE);

