-- 
-- Non Foreign Key Constraints for Table ISU_TAX_USER 
-- 
ALTER TABLE MASTER.ISU_TAX_USER ADD (
  CONSTRAINT ISU_TAX_USER_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.ISU_TAX_USER_PK
  ENABLE VALIDATE);

