-- 
-- Non Foreign Key Constraints for Table ISU_TAX_DOCS 
-- 
ALTER TABLE MASTER.ISU_TAX_DOCS ADD (
  CONSTRAINT ISU_TAX_DODCS_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.ISU_TAX_DODCS_PK
  ENABLE VALIDATE);

