-- 
-- Non Foreign Key Constraints for Table ISU_BILL_POS_ROW 
-- 
ALTER TABLE MASTER.ISU_BILL_POS_ROW ADD (
  CONSTRAINT ISU_BILL_POS_ROW_PK
  PRIMARY KEY
  (ISU_KOD, ISU_KOD_POS, ISU_TTN_ID)
  USING INDEX MASTER.ISU_BILL_POS_ROW_PK
  ENABLE VALIDATE);

