-- 
-- Non Foreign Key Constraints for Table JKALLOW 
-- 
ALTER TABLE MASTER.JKALLOW ADD (
  CHECK ("DATE_ALLOW" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.JKALLOW ADD (
  CHECK ("SROK_ALLOW" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.JKALLOW ADD (
  CHECK ("USERNAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.JKALLOW ADD (
  CONSTRAINT JKA_PK
  PRIMARY KEY
  (MESTO_ID, JKA_DATE, SVED_NUM)
  USING INDEX MASTER.JKA_PK
  ENABLE VALIDATE);

