-- 
-- Foreign Key Constraints for Table JKCOMMIT 
-- 
ALTER TABLE MASTER.JKCOMMIT ADD (
  CONSTRAINT JKC_JKC_SES_FK 
  FOREIGN KEY (JKC_SES_ID) 
  REFERENCES MASTER.JKCOMMIT_SESSION (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.JKCOMMIT ADD (
  CONSTRAINT JKC_MESTO_FK 
  FOREIGN KEY (MESTO_ID) 
  REFERENCES MASTER.KLS_MESTO (ID)
  ENABLE NOVALIDATE);

