-- 
-- Non Foreign Key Constraints for Table JKCOMMIT 
-- 
ALTER TABLE MASTER.JKCOMMIT ADD (
  CHECK ("SVED_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.JKCOMMIT ADD (
  CHECK ("SVED_CNT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.JKCOMMIT ADD (
  CHECK ("SVED_VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.JKCOMMIT ADD (
  CONSTRAINT JKC_PK
  PRIMARY KEY
  (JKC_SES_ID, MESTO_ID, NOM_ZD, SVED_NUM)
  USING INDEX MASTER.JKC_PK
  ENABLE VALIDATE);

