-- 
-- Non Foreign Key Constraints for Table JKCOMMIT_SESSION 
-- 
ALTER TABLE MASTER.JKCOMMIT_SESSION ADD (
  CHECK ("SESSION_TIME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.JKCOMMIT_SESSION ADD (
  CONSTRAINT JKC_SES_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.JKC_SES_PK
  ENABLE VALIDATE);

