-- 
-- Foreign Key Constraints for Table JKCOMMIT_PROD2CENN 
-- 
ALTER TABLE MASTER.JKCOMMIT_PROD2CENN ADD (
  CONSTRAINT PROD2CENN_CAT_CEN_FK 
  FOREIGN KEY (CAT_CEN_ID) 
  REFERENCES MASTER.KLS_CAT_CEN (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.JKCOMMIT_PROD2CENN ADD (
  CONSTRAINT PROD2CENN_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

