-- 
-- Non Foreign Key Constraints for Table JKCOMMIT_PLAN2DOG 
-- 
ALTER TABLE MASTER.JKCOMMIT_PLAN2DOG ADD (
  CHECK ("PLANSTRU_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.JKCOMMIT_PLAN2DOG ADD (
  CHECK ("DOG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.JKCOMMIT_PLAN2DOG ADD (
  CONSTRAINT PLAN2DOG_PLAN2DOG_UK
  UNIQUE (DOG_ID, PLANSTRU_ID)
  USING INDEX MASTER.PLAN2DOG_PLAN2DOG_UK
  ENABLE VALIDATE);

