-- 
-- Non Foreign Key Constraints for Table KLS_PROD_GROUPS 
-- 
ALTER TABLE MASTER.KLS_PROD_GROUPS ADD (
  CHECK ("PROD_TYPE_GRP_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_GROUPS ADD (
  CHECK ("GROUP_ORDER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_GROUPS ADD (
  CHECK ("GROUP_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_GROUPS ADD (
  CHECK ("GROUP_VISIBLE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_GROUPS ADD (
  CONSTRAINT PK_KLS_PROD_GROUPS
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_PROD_GROUPS
  ENABLE VALIDATE);

