-- 
-- Non Foreign Key Constraints for Table KLS_PROD_NOMENKLATOR 
-- 
ALTER TABLE MASTER.KLS_PROD_NOMENKLATOR ADD (
  CHECK ("MODIF" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_NOMENKLATOR ADD (
  CHECK ("NAME_PR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_NOMENKLATOR ADD (
  CHECK ("IS_AUTO_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_NOMENKLATOR ADD (
  CONSTRAINT PROD_NOMEN_PK
  PRIMARY KEY
  (PARUS_RN, PARUS_PRN)
  USING INDEX MASTER.PROD_NOMEN_PK
  ENABLE VALIDATE);

