-- 
-- Non Foreign Key Constraints for Table KLS_KTS 
-- 
ALTER TABLE MASTER.KLS_KTS ADD (
  CHECK ("GTD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_KTS ADD (
  CONSTRAINT KTS_PK
  PRIMARY KEY
  (KTS)
  USING INDEX MASTER.KTS_PK
  ENABLE VALIDATE);

