-- 
-- Non Foreign Key Constraints for Table KLS_PROD_MOSGRP 
-- 
ALTER TABLE MASTER.KLS_PROD_MOSGRP ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_MOSGRP ADD (
  CHECK ("ORDER_GDPL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_MOSGRP ADD (
  CHECK ("NAME_GDPL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_MOSGRP ADD (
  CHECK ("COLOR_GDPL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_MOSGRP ADD (
  CHECK ("COLOR_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_MOSGRP ADD (
  CHECK ("IS_SEND" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_MOSGRP ADD (
  CONSTRAINT MOS_GRP_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.MOS_GRP_PK
  ENABLE VALIDATE);

