-- 
-- Non Foreign Key Constraints for Table KLS_PROD_NAR 
-- 
ALTER TABLE MASTER.KLS_PROD_NAR ADD (
  CHECK ("NAME_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_NAR ADD (
  CHECK ("ORDER_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_NAR ADD (
  CONSTRAINT PROD_NAR_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PROD_NAR_PK
  ENABLE VALIDATE);

