-- 
-- Non Foreign Key Constraints for Table KLS_GD_VAGTYPE 
-- 
ALTER TABLE MASTER.KLS_GD_VAGTYPE ADD (
  CHECK ("ABBR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GD_VAGTYPE ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GD_VAGTYPE ADD (
  CHECK ("COLOR_GDPL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GD_VAGTYPE ADD (
  CHECK ("COLOR_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GD_VAGTYPE ADD (
  CONSTRAINT GD_VAGTYPE_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.GD_VAGTYPE_PK
  ENABLE VALIDATE);

