-- 
-- Non Foreign Key Constraints for Table KLS_STATES 
-- 
ALTER TABLE MASTER.KLS_STATES ADD (
  CHECK ("STATE_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_STATES ADD (
  CHECK ("NAPR_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_STATES ADD (
  CONSTRAINT STATES_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.STATES_PK
  ENABLE VALIDATE);

