-- 
-- Foreign Key Constraints for Table KLS_VETKA_OTP 
-- 
ALTER TABLE MASTER.KLS_VETKA_OTP ADD (
  CONSTRAINT VETKA_OTP_LOAD_TYPE_FK 
  FOREIGN KEY (LOAD_TYPE_ID) 
  REFERENCES MASTER.KLS_LOAD_TYPE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VETKA_OTP ADD (
  CONSTRAINT VETKA_OTP_MESTO_FK 
  FOREIGN KEY (MESTO_ID) 
  REFERENCES MASTER.KLS_MESTO (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VETKA_OTP ADD (
  CONSTRAINT VETKA_OTP_OWNER_FK 
  FOREIGN KEY (OWNER_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

