-- 
-- Non Foreign Key Constraints for Table KLS_GOST_OLD 
-- 
ALTER TABLE MASTER.KLS_GOST_OLD ADD (
  CHECK ("KOEF" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GOST_OLD ADD (
  CONSTRAINT PK_KLS_GOST_OLD
  PRIMARY KEY
  (PL1, PL2)
  USING INDEX MASTER.PK_KLS_GOST_OLD
  ENABLE VALIDATE);

