-- 
-- Non Foreign Key Constraints for Table KLS_VID_USL 
-- 
ALTER TABLE MASTER.KLS_VID_USL ADD (
  CHECK ("USL_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VID_USL ADD (
  CONSTRAINT VID_USL_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.VID_USL_PK
  ENABLE VALIDATE);

