-- 
-- Non Foreign Key Constraints for Table KLS_VAGOWNER_MOS 
-- 
ALTER TABLE MASTER.KLS_VAGOWNER_MOS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VAGOWNER_MOS ADD (
  CONSTRAINT VAGOWN_MOS_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.VAGOWN_MOS_PK
  ENABLE VALIDATE);

