-- 
-- Foreign Key Constraints for Table KLS_PAYFORM 
-- 
ALTER TABLE MASTER.KLS_PAYFORM ADD (
  CONSTRAINT PAYFORM_PAYFORM_GR_FK 
  FOREIGN KEY (PAYFORM_GR_ID) 
  REFERENCES MASTER.KLS_PAYFORM_GRP (ID)
  ENABLE NOVALIDATE);

