-- 
-- Non Foreign Key Constraints for Table KLS_PREDPR_KONS 
-- 
ALTER TABLE MASTER.KLS_PREDPR_KONS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PREDPR_KONS ADD (
  CHECK ("INN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PREDPR_KONS ADD (
  CHECK ("IS_AUTO" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PREDPR_KONS ADD (
  CONSTRAINT PREDPRKONS_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PREDPRKONS_PK
  ENABLE VALIDATE);

