-- 
-- Non Foreign Key Constraints for Table KLS_INCOTERM 
-- 
ALTER TABLE MASTER.KLS_INCOTERM ADD (
  CONSTRAINT PK_KLS_INCOTERM
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_INCOTERM
  ENABLE VALIDATE);

