-- 
-- Non Foreign Key Constraints for Table KLS_KODIF 
-- 
ALTER TABLE MASTER.KLS_KODIF ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_KODIF ADD (
  CONSTRAINT KODIF_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.KODIF_PK
  ENABLE VALIDATE);

