-- 
-- Non Foreign Key Constraints for Table KLS_FORMNAKL 
-- 
ALTER TABLE MASTER.KLS_FORMNAKL ADD (
  CHECK ("FLG_DOSTUP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_FORMNAKL ADD (
  CHECK ("FORM_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_FORMNAKL ADD (
  CHECK ("FLG_GROUP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_FORMNAKL ADD (
  CHECK ("IS_RUS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_FORMNAKL ADD (
  CHECK ("LOAD_TYPE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_FORMNAKL ADD (
  CONSTRAINT FORMNAKL_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.FORMNAKL_PK
  ENABLE VALIDATE);

