-- 
-- Non Foreign Key Constraints for Table KLS_TIP_REAL_KONS 
-- 
ALTER TABLE MASTER.KLS_TIP_REAL_KONS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_TIP_REAL_KONS ADD (
  CONSTRAINT TIP_REAL_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.TIP_REAL_PK
  ENABLE VALIDATE);

