-- 
-- Non Foreign Key Constraints for Table KLS_GD_PODACH 
-- 
ALTER TABLE MASTER.KLS_GD_PODACH ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GD_PODACH ADD (
  CONSTRAINT GD_PODACH_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.GD_PODACH_PK
  ENABLE VALIDATE);

