-- 
-- Non Foreign Key Constraints for Table KLS_NAPR_POST 
-- 
ALTER TABLE MASTER.KLS_NAPR_POST ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_NAPR_POST ADD (
  CONSTRAINT PK_KLS_NAPR_POST
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_NAPR_POST
  ENABLE VALIDATE);

