-- 
-- Foreign Key Constraints for Table KLS_PLAN 
-- 
ALTER TABLE MASTER.KLS_PLAN ADD (
  CONSTRAINT PLAN_BROTHER_FK 
  FOREIGN KEY (BROTHER_ID) 
  REFERENCES MASTER.KLS_PLAN (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLAN ADD (
  CONSTRAINT PLAN_PLAN_KIND_FK 
  FOREIGN KEY (PLAN_KIND_ID) 
  REFERENCES MASTER.KLS_PLAN_KIND (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLAN ADD (
  CONSTRAINT PLAN_PLAN_OWNER_FK 
  FOREIGN KEY (PLAN_OWNER_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

