-- 
-- Non Foreign Key Constraints for Table KLS_VETKA_OTP 
-- 
ALTER TABLE MASTER.KLS_VETKA_OTP ADD (
  CHECK ("VETKA_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VETKA_OTP ADD (
  CHECK ("SHORT_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VETKA_OTP ADD (
  CHECK ("DOSTUP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VETKA_OTP ADD (
  CHECK ("ORDNUNG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VETKA_OTP ADD (
  CHECK ("MESTO_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VETKA_OTP ADD (
  CHECK ("LOAD_TYPE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VETKA_OTP ADD (
  CONSTRAINT VETKA_OTP_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.VETKA_OTP_PK
  ENABLE VALIDATE);

