-- 
-- Non Foreign Key Constraints for Table KLS_FORMSHAB 
-- 
ALTER TABLE MASTER.KLS_FORMSHAB ADD (
  CHECK ("FORMNAKL_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_FORMSHAB ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_FORMSHAB ADD (
  CHECK ("DOSTUP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_FORMSHAB ADD (
  CHECK ("IS_RUS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_FORMSHAB ADD (
  CHECK ("IS_OPD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_FORMSHAB ADD (
  CHECK ("LOAD_TYPE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_FORMSHAB ADD (
  CONSTRAINT PK_KLS_FORMSHAB
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_FORMSHAB
  ENABLE VALIDATE);

