-- 
-- Non Foreign Key Constraints for Table KLS_VZISKTXT 
-- 
ALTER TABLE MASTER.KLS_VZISKTXT ADD (
  CONSTRAINT PK_KLS_VZISKTXT
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_VZISKTXT
  ENABLE VALIDATE);

