-- 
-- Non Foreign Key Constraints for Table KLS_PLANSTRU 
-- 
ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CHECK ("BEGIN_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CHECK ("END_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CHECK ("LEVEL_POS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CHECK ("INPUT_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CHECK ("KOD_SGR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CHECK ("KOD_SPG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CHECK ("KOD_RZD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CHECK ("KOD_PRZ" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CHECK ("KOD_GRP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CHECK ("KOD_PGR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CHECK ("PARENT_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CHECK ("IS_RESURS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CONSTRAINT PLANSTRU_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PLANSTRU_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CONSTRAINT PLANSTRU_PLANSTRU_AK_UK
  UNIQUE (LEVEL_POS, KOD_SGR, KOD_SPG, KOD_RZD, KOD_PRZ, KOD_GRP, KOD_PGR)
  USING INDEX MASTER.PLANSTRU_PLANSTRU_AK_UK
  ENABLE VALIDATE);

