-- 
-- Non Foreign Key Constraints for Table KLS_GD_PRINVAG 
-- 
ALTER TABLE MASTER.KLS_GD_PRINVAG ADD (
  CHECK ("ABBR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GD_PRINVAG ADD (
  CONSTRAINT GD_PRINVAG_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.GD_PRINVAG_PK
  ENABLE VALIDATE);

