-- 
-- Non Foreign Key Constraints for Table KLS_STAN 
-- 
ALTER TABLE MASTER.KLS_STAN ADD (
  CHECK ("STAN_KOD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_STAN ADD (
  CHECK ("STAN_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_STAN ADD (
  CHECK ("RAST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_STAN ADD (
  CHECK ("REGION_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_STAN ADD (
  CHECK ("GDOR_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_STAN ADD (
  CONSTRAINT STAN_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.STAN_PK
  ENABLE VALIDATE);

