-- 
-- Foreign Key Constraints for Table KLS_GP_NAPR 
-- 
ALTER TABLE MASTER.KLS_GP_NAPR ADD (
  CONSTRAINT GP_NAPR_GOSPROG_FK 
  FOREIGN KEY (GOSPROG_ID) 
  REFERENCES MASTER.KLS_GOSPROG (ID)
  ENABLE NOVALIDATE);

