-- 
-- Foreign Key Constraints for Table KLS_NARIAD 
-- 
ALTER TABLE MASTER.KLS_NARIAD ADD (
  CONSTRAINT NARIAD_DOVER_FK 
  FOREIGN KEY (DOVER_ID) 
  REFERENCES MASTER.KLS_DOVER (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_NARIAD ADD (
  CONSTRAINT NARIAD_MESTO_FK 
  FOREIGN KEY (MESTO_ID) 
  REFERENCES MASTER.KLS_MESTO (ID)
  ENABLE NOVALIDATE);

