-- 
-- Non Foreign Key Constraints for Table KLS_PROD_TYPE_GRP 
-- 
ALTER TABLE MASTER.KLS_PROD_TYPE_GRP ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_TYPE_GRP ADD (
  CONSTRAINT PK_KLS_PROD_TYPE_GRP
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_PROD_TYPE_GRP
  ENABLE VALIDATE);

