-- 
-- Non Foreign Key Constraints for Table KLS_PAYDELAY 
-- 
ALTER TABLE MASTER.KLS_PAYDELAY ADD (
  CHECK ("PAYDELAY_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PAYDELAY ADD (
  CHECK ("SHORT_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PAYDELAY ADD (
  CONSTRAINT PAYDELAY_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PAYDELAY_PK
  ENABLE VALIDATE);

