-- 
-- Non Foreign Key Constraints for Table KLS_PROD_GR2GR_DESC 
-- 
ALTER TABLE MASTER.KLS_PROD_GR2GR_DESC ADD (
  CHECK ("PROD_GROUPS_ID_1" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_GR2GR_DESC ADD (
  CHECK ("IS_AUTO_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_GR2GR_DESC ADD (
  CONSTRAINT PK_KLS_PROD_GR2GR_DESC
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_PROD_GR2GR_DESC
  ENABLE VALIDATE);

