-- 
-- Non Foreign Key Constraints for Table KLS_TABLPOK 
-- 
ALTER TABLE MASTER.KLS_TABLPOK ADD (
  CHECK ("DATEUPLOAD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_TABLPOK ADD (
  CONSTRAINT TABLPOK_PK
  PRIMARY KEY
  (PROD_ID_NPR, KODIF_ID)
  USING INDEX MASTER.TABLPOK_PK
  ENABLE VALIDATE);

