-- 
-- Non Foreign Key Constraints for Table KLS_DOV_LINE 
-- 
ALTER TABLE MASTER.KLS_DOV_LINE ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOV_LINE ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOV_LINE ADD (
  CHECK ("DOVER_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOV_LINE ADD (
  CHECK ("IS_LOADED" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOV_LINE ADD (
  CONSTRAINT DOV_LINE_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.DOV_LINE_PK
  ENABLE VALIDATE);

