-- 
-- Non Foreign Key Constraints for Table KLS_VID_REAL_KONS 
-- 
ALTER TABLE MASTER.KLS_VID_REAL_KONS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VID_REAL_KONS ADD (
  CONSTRAINT VID_REAL_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.VID_REAL_PK
  ENABLE VALIDATE);

