-- 
-- Non Foreign Key Constraints for Table KLS_VOZN_RST 
-- 
ALTER TABLE MASTER.KLS_VOZN_RST ADD (
  CHECK ("IS_AGENT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VOZN_RST ADD (
  CHECK ("BEGIN_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VOZN_RST ADD (
  CHECK ("END_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VOZN_RST ADD (
  CHECK ("VAGOWN_TYP_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VOZN_RST ADD (
  CHECK ("RAST_MIN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VOZN_RST ADD (
  CHECK ("RAST_MAX" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VOZN_RST ADD (
  CHECK ("CENA_VOZN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VOZN_RST ADD (
  CONSTRAINT VOZN_RST_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.VOZN_RST_PK
  ENABLE VALIDATE);

