-- 
-- Non Foreign Key Constraints for Table KLS_CIST 
-- 
ALTER TABLE MASTER.KLS_CIST ADD (
  CHECK ("AXES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_CIST ADD (
  CONSTRAINT KLS_CIST_PK
  PRIMARY KEY
  (NUM_CIST)
  USING INDEX MASTER.KLS_CIST_PK
  ENABLE VALIDATE);

