-- 
-- Non Foreign Key Constraints for Table KLS_SHABEXP 
-- 
ALTER TABLE MASTER.KLS_SHABEXP ADD (
  CHECK ("FLG_DOSTUP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_SHABEXP ADD (
  CHECK ("DOG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_SHABEXP ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_SHABEXP ADD (
  CHECK ("STAN_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_SHABEXP ADD (
  CONSTRAINT SHABEXP_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.SHABEXP_PK
  ENABLE VALIDATE);

