-- 
-- Non Foreign Key Constraints for Table KLS_GD_VID_OTPR 
-- 
ALTER TABLE MASTER.KLS_GD_VID_OTPR ADD (
  CHECK ("TAG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GD_VID_OTPR ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GD_VID_OTPR ADD (
  CONSTRAINT VID_OTPR_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.VID_OTPR_PK
  ENABLE VALIDATE);

