-- 
-- Non Foreign Key Constraints for Table KLS_ZPU_TYPES 
-- 
ALTER TABLE MASTER.KLS_ZPU_TYPES ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_ZPU_TYPES ADD (
  CONSTRAINT PK_KLS_ZPU_TYPES
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_ZPU_TYPES
  ENABLE VALIDATE);

