-- 
-- Foreign Key Constraints for Table KLS_VAGOWNER 
-- 
ALTER TABLE MASTER.KLS_VAGOWNER ADD (
  CONSTRAINT VAGOWNER_PREDPR_FK 
  FOREIGN KEY (PREDPR_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VAGOWNER ADD (
  CONSTRAINT VAGOWNER_VAGOWNER_FK 
  FOREIGN KEY (SOBSTV_ID) 
  REFERENCES MASTER.KLS_VAGOWNER (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VAGOWNER ADD (
  CONSTRAINT VAGOWNER_VAGOWN_MOS_FK 
  FOREIGN KEY (VAGOWN_MOS_ID) 
  REFERENCES MASTER.KLS_VAGOWNER_MOS (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VAGOWNER ADD (
  CONSTRAINT VAGOWNER_VAGOWN_TYP_FK 
  FOREIGN KEY (VAGOWN_TYP_ID) 
  REFERENCES MASTER.KLS_VAGOWNER_TYPES (ID)
  ENABLE NOVALIDATE);

