-- 
-- Non Foreign Key Constraints for Table KLS_PROD_PASP_UNP 
-- 
ALTER TABLE MASTER.KLS_PROD_PASP_UNP ADD (
  CHECK ("IS_AUTO_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_PASP_UNP ADD (
  CONSTRAINT PK_KLS_PROD_PASP_UNP
  PRIMARY KEY
  (KOD_OIL_PRODUCT)
  USING INDEX MASTER.PK_KLS_PROD_PASP_UNP
  ENABLE VALIDATE);

