-- 
-- Foreign Key Constraints for Table KLS_PLANSTRU 
-- 
ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CONSTRAINT PLANSTRU_NAZN_OTG_FK 
  FOREIGN KEY (NAZN_OTG_ID) 
  REFERENCES MASTER.KLS_NAZN_OTG (ID)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLANSTRU ADD (
  CONSTRAINT PLANSTRU_PARENT_FK 
  FOREIGN KEY (PARENT_ID) 
  REFERENCES MASTER.KLS_PLANSTRU (ID)
  ENABLE NOVALIDATE);

