-- 
-- Non Foreign Key Constraints for Table KLS_TYPE_ZAKAZ 
-- 
ALTER TABLE MASTER.KLS_TYPE_ZAKAZ ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_TYPE_ZAKAZ ADD (
  CONSTRAINT PK_KLS_TYPE_ZAKAZ
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_TYPE_ZAKAZ
  ENABLE VALIDATE);

