-- 
-- Non Foreign Key Constraints for Table KLS_LOAD_TYPE_MOS 
-- 
ALTER TABLE MASTER.KLS_LOAD_TYPE_MOS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_LOAD_TYPE_MOS ADD (
  CONSTRAINT LOAD_MOS_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.LOAD_MOS_PK
  ENABLE VALIDATE);

