-- 
-- Non Foreign Key Constraints for Table KLS_MESTO 
-- 
ALTER TABLE MASTER.KLS_MESTO ADD (
  CHECK ("MESTO_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_MESTO ADD (
  CONSTRAINT MESTO_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.MESTO_PK
  ENABLE VALIDATE);

