-- 
-- Non Foreign Key Constraints for Table KLS_ANALIT 
-- 
ALTER TABLE MASTER.KLS_ANALIT ADD (
  CHECK ("ANALIT_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_ANALIT ADD (
  CONSTRAINT ANALIT_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.ANALIT_PK
  ENABLE VALIDATE);

