-- 
-- Non Foreign Key Constraints for Table KLS_CAT_CEN 
-- 
ALTER TABLE MASTER.KLS_CAT_CEN ADD (
  CHECK ("CAT_CEN_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_CAT_CEN ADD (
  CHECK ("CAT_CEN_GROUP_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_CAT_CEN ADD (
  CONSTRAINT CAT_CEN_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.CAT_CEN_PK
  ENABLE VALIDATE);

