-- 
-- Non Foreign Key Constraints for Table KLS_DOG 
-- 
ALTER TABLE MASTER.KLS_DOG ADD (
  CONSTRAINT KLS_DOG_CHECK_UNP
  CHECK (AGENT_ID<>8 OR PREDPR_ID=8 OR UNP_ID>0)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("DOG_NUMBER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("SHORT_NUMBER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("DOG_BEGIN_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("DOG_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("DOG_YEAR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("PREDPR_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("INSURE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("VIDDOG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("GROUPDOG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("GOSPROG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("LUKDOG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("USL_OPL_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("SALDO_01072002" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("SALDO_01_07_2002" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("SALDO_01122002" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("IS_AGENT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CHECK ("AGENT_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG ADD (
  CONSTRAINT DOG_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.DOG_PK
  ENABLE VALIDATE);

