-- 
-- Foreign Key Constraints for Table KLS_LOAD_TYPE 
-- 
ALTER TABLE MASTER.KLS_LOAD_TYPE ADD (
  CONSTRAINT LOAD_TYPE_LOAD_MOS_FK 
  FOREIGN KEY (LOAD_MOS_ID) 
  REFERENCES MASTER.KLS_LOAD_TYPE_MOS (ID)
  ENABLE NOVALIDATE);

