-- 
-- Foreign Key Constraints for Table KLS_PROD_GU12 
-- 
ALTER TABLE MASTER.KLS_PROD_GU12 ADD (
  CONSTRAINT PROD_GU12_GD_GROUP_FK 
  FOREIGN KEY (GD_GROUP_ID) 
  REFERENCES MASTER.KLS_GD_GROUP (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_GU12 ADD (
  CONSTRAINT PROD_GU12_GD_VAGTYPE_FK 
  FOREIGN KEY (GD_VAGTYPE_ID) 
  REFERENCES MASTER.KLS_GD_VAGTYPE (ID)
  ENABLE NOVALIDATE);

