-- 
-- Non Foreign Key Constraints for Table KLS_PAYFORM 
-- 
ALTER TABLE MASTER.KLS_PAYFORM ADD (
  CHECK ("PAYFORM_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PAYFORM ADD (
  CHECK ("PAYFORM_GR_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PAYFORM ADD (
  CONSTRAINT PAYFORM_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PAYFORM_PK
  ENABLE VALIDATE);

