-- 
-- Non Foreign Key Constraints for Table KLS_RIGHTS 
-- 
ALTER TABLE MASTER.KLS_RIGHTS ADD (
  CONSTRAINT PK_KLS_RIGHTS
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_RIGHTS
  ENABLE VALIDATE);

