-- 
-- Foreign Key Constraints for Table KLS_PREDPR 
-- 
ALTER TABLE MASTER.KLS_PREDPR ADD (
  CONSTRAINT PREDPR_BANK_FK 
  FOREIGN KEY (BANK_KORS) 
  REFERENCES MASTER.KLS_BANK (KORS)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PREDPR ADD (
  CONSTRAINT PREDPR_BANKS_FK 
  FOREIGN KEY (BANKS_ID) 
  REFERENCES MASTER.KLS_BANKS (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PREDPR ADD (
  CONSTRAINT PREDPR_HOLDING_FK 
  FOREIGN KEY (HOLDING_ID) 
  REFERENCES MASTER.KLS_HOLDING (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PREDPR ADD (
  CONSTRAINT PREDPR_PERTYPE_FK 
  FOREIGN KEY (PERTYPE_ID) 
  REFERENCES MASTER.KLS_PERTYPE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PREDPR ADD (
  CONSTRAINT PREDPR_REGION_FK 
  FOREIGN KEY (REGION_ID) 
  REFERENCES MASTER.KLS_REGION (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PREDPR ADD (
  CONSTRAINT PREDPR_STATES_FK 
  FOREIGN KEY (STATES_ID) 
  REFERENCES MASTER.KLS_STATES (ID)
  ENABLE NOVALIDATE);

