-- 
-- Non Foreign Key Constraints for Table KLS_PROD_KONS_GROUPS_DESC 
-- 
ALTER TABLE MASTER.KLS_PROD_KONS_GROUPS_DESC ADD (
  CHECK ("PROD_KONS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_KONS_GROUPS_DESC ADD (
  CHECK ("PROD_GROUPS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_KONS_GROUPS_DESC ADD (
  CHECK ("IS_AUTO_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_KONS_GROUPS_DESC ADD (
  CONSTRAINT PK_KLS_PROD_KONS_GROUPS_DESC
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_PROD_KONS_GROUPS_DESC
  ENABLE VALIDATE);

