-- 
-- Non Foreign Key Constraints for Table KLS_DOG_MAIN 
-- 
ALTER TABLE MASTER.KLS_DOG_MAIN ADD (
  CHECK ("IS_AGENT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG_MAIN ADD (
  CHECK ("FROM_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOG_MAIN ADD (
  CONSTRAINT PK_KLS_DOG_MAIN
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_DOG_MAIN
  ENABLE VALIDATE);

