-- 
-- Non Foreign Key Constraints for Table KLS_ZAKAZ_TIP_CORP 
-- 
ALTER TABLE MASTER.KLS_ZAKAZ_TIP_CORP ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_ZAKAZ_TIP_CORP ADD (
  CONSTRAINT PK_ID
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_ID
  ENABLE VALIDATE);

