-- 
-- Non Foreign Key Constraints for Table KLS_ST_RASH_KONS 
-- 
ALTER TABLE MASTER.KLS_ST_RASH_KONS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_ST_RASH_KONS ADD (
  CONSTRAINT ST_RASH_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.ST_RASH_PK
  ENABLE VALIDATE);

