-- 
-- Foreign Key Constraints for Table KLS_VID_OTGR 
-- 
ALTER TABLE MASTER.KLS_VID_OTGR ADD (
  CONSTRAINT VID_OTGR_LOAD_TYPE_FK 
  FOREIGN KEY (LOAD_TYPE_ID) 
  REFERENCES MASTER.KLS_LOAD_TYPE (ID)
  ENABLE NOVALIDATE);

