-- 
-- Non Foreign Key Constraints for Table KLS_VID_POST_KONS 
-- 
ALTER TABLE MASTER.KLS_VID_POST_KONS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VID_POST_KONS ADD (
  CONSTRAINT VID_POST_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.VID_POST_PK
  ENABLE VALIDATE);

