-- 
-- Foreign Key Constraints for Table KLS_PREDPR_KONS 
-- 
ALTER TABLE MASTER.KLS_PREDPR_KONS ADD (
  CONSTRAINT PREDPRKONS_PREDPR_FK 
  FOREIGN KEY (PREDPR_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

