-- 
-- Non Foreign Key Constraints for Table KLS_BILLS_ALGORTHMS 
-- 
ALTER TABLE MASTER.KLS_BILLS_ALGORTHMS ADD (
  CONSTRAINT PK_KLS_BILLS_ALGORTHMS
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_BILLS_ALGORTHMS
  ENABLE VALIDATE);

