-- 
-- Non Foreign Key Constraints for Table KLS_PLAN 
-- 
ALTER TABLE MASTER.KLS_PLAN ADD (
  CHECK ("PLAN_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLAN ADD (
  CHECK ("PLAN_KIND_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLAN ADD (
  CHECK ("ONLY_UNP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLAN ADD (
  CONSTRAINT PLAN_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PLAN_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.KLS_PLAN ADD (
  CONSTRAINT PLAN_PLAN_AK_UK
  UNIQUE (PLAN_KIND_ID, PLAN_NAME)
  USING INDEX MASTER.PLAN_PLAN_AK_UK
  ENABLE VALIDATE);

