-- 
-- Non Foreign Key Constraints for Table KLS_DOC_NUMS 
-- 
ALTER TABLE MASTER.KLS_DOC_NUMS ADD (
  CHECK ("DOC_TYPE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOC_NUMS ADD (
  CHECK ("LAST_DOC_NUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOC_NUMS ADD (
  CHECK ("MESTO_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOC_NUMS ADD (
  CHECK ("MIN_DOC_NUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOC_NUMS ADD (
  CHECK ("DOC_RULE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOC_NUMS ADD (
  CONSTRAINT KLS_DOC_NUMS_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.KLS_DOC_NUMS_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.KLS_DOC_NUMS ADD (
  CONSTRAINT KLS_DOC_NUMS_UK
  UNIQUE (DOC_TYPE_ID, MESTO_ID, DOC_PREFIX, FROM_DATE, TO_DATE)
  USING INDEX MASTER.KLS_DOC_NUMS_UK
  ENABLE VALIDATE);

