-- 
-- Non Foreign Key Constraints for Table KLS_GD_SOOB 
-- 
ALTER TABLE MASTER.KLS_GD_SOOB ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GD_SOOB ADD (
  CONSTRAINT GD_SOOB_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.GD_SOOB_PK
  ENABLE VALIDATE);

