-- 
-- Non Foreign Key Constraints for Table KLS_TIP_AKCIZ 
-- 
ALTER TABLE MASTER.KLS_TIP_AKCIZ ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_TIP_AKCIZ ADD (
  CONSTRAINT TIP_AKCIZ_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.TIP_AKCIZ_PK
  ENABLE VALIDATE);

