-- 
-- Non Foreign Key Constraints for Table KLS_LOAD_TYPE 
-- 
ALTER TABLE MASTER.KLS_LOAD_TYPE ADD (
  CHECK ("TYPE_OTGR_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_LOAD_TYPE ADD (
  CONSTRAINT LOAD_TYPE_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.LOAD_TYPE_PK
  ENABLE VALIDATE);

