-- 
-- Non Foreign Key Constraints for Table KLS_ORATODBF 
-- 
ALTER TABLE MASTER.KLS_ORATODBF ADD (
  CONSTRAINT KLS_ORATODBF_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.KLS_ORATODBF_PK
  ENABLE VALIDATE);

