-- 
-- Non Foreign Key Constraints for Table KLS_REGION 
-- 
ALTER TABLE MASTER.KLS_REGION ADD (
  CHECK ("REGION_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_REGION ADD (
  CHECK ("KOD_MOSCOW" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_REGION ADD (
  CHECK ("SHORT_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_REGION ADD (
  CHECK ("STATES_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_REGION ADD (
  CONSTRAINT REGION_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.REGION_PK
  ENABLE VALIDATE);

