-- 
-- Non Foreign Key Constraints for Table KLS_ORG_KIND_RELATIONS 
-- 
ALTER TABLE MASTER.KLS_ORG_KIND_RELATIONS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_ORG_KIND_RELATIONS ADD (
  CONSTRAINT KIND_RELA_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.KIND_RELA_PK
  ENABLE VALIDATE);

