-- 
-- Non Foreign Key Constraints for Table KLS_VIDDOG 
-- 
ALTER TABLE MASTER.KLS_VIDDOG ADD (
  CHECK ("VIDDOG_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VIDDOG ADD (
  CONSTRAINT VIDDOG_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.VIDDOG_PK
  ENABLE VALIDATE);

