-- 
-- Foreign Key Constraints for Table KLS_PROD_PLAN 
-- 
ALTER TABLE MASTER.KLS_PROD_PLAN ADD (
  CONSTRAINT PROD_PLAN_PARENT_FK 
  FOREIGN KEY (PARENT_ID) 
  REFERENCES MASTER.KLS_PROD_PLAN (ID)
  ENABLE NOVALIDATE);

