-- 
-- Non Foreign Key Constraints for Table KLS_GROUPDOG 
-- 
ALTER TABLE MASTER.KLS_GROUPDOG ADD (
  CHECK ("GROUPDOG_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GROUPDOG ADD (
  CONSTRAINT GROUPDOG_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.GROUPDOG_PK
  ENABLE VALIDATE);

