-- 
-- Non Foreign Key Constraints for Table KLS_GD_PRICH 
-- 
ALTER TABLE MASTER.KLS_GD_PRICH ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GD_PRICH ADD (
  CHECK ("SORTBY" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GD_PRICH ADD (
  CONSTRAINT GD_PRICH_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.GD_PRICH_PK
  ENABLE VALIDATE);

