-- 
-- Non Foreign Key Constraints for Table KLS_VAGON_VZLIV 
-- 
ALTER TABLE MASTER.KLS_VAGON_VZLIV ADD (
  CHECK ("VOLUME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VAGON_VZLIV ADD (
  CONSTRAINT PK_KLS_CIST_VZLIV
  PRIMARY KEY
  (KALIBR_ID, VZLIV)
  USING INDEX MASTER.PK_KLS_CIST_VZLIV
  ENABLE VALIDATE);

