-- 
-- Non Foreign Key Constraints for Table KLS_CIST_DENI 
-- 
ALTER TABLE MASTER.KLS_CIST_DENI ADD (
  CONSTRAINT CIST_DENI_PK
  PRIMARY KEY
  (NUM_CIST, BEG_DENI)
  USING INDEX MASTER.CIST_DENI_PK
  ENABLE VALIDATE);

