-- 
-- Foreign Key Constraints for Table KLS_GD_VAGTYPE 
-- 
ALTER TABLE MASTER.KLS_GD_VAGTYPE ADD (
  CONSTRAINT GD_VAGTYPE_VAGONTYPE_FK 
  FOREIGN KEY (VAGONTYPE_ID) 
  REFERENCES MASTER.KLS_VAGONTYPE (ID)
  ENABLE NOVALIDATE);

