-- 
-- Non Foreign Key Constraints for Table KLS_TIP_OP_KONS 
-- 
ALTER TABLE MASTER.KLS_TIP_OP_KONS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_TIP_OP_KONS ADD (
  CONSTRAINT TIP_OP_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.TIP_OP_PK
  ENABLE VALIDATE);

