-- 
-- Non Foreign Key Constraints for Table KLS_PRICHIN 
-- 
ALTER TABLE MASTER.KLS_PRICHIN ADD (
  CONSTRAINT KLS_PRICHIN_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.KLS_PRICHIN_PK
  ENABLE VALIDATE);

