-- 
-- Non Foreign Key Constraints for Table KLS_PLAN_KIND 
-- 
ALTER TABLE MASTER.KLS_PLAN_KIND ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PLAN_KIND ADD (
  CONSTRAINT PLAN_KIND_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PLAN_KIND_PK
  ENABLE VALIDATE);

