-- 
-- Non Foreign Key Constraints for Table KLS_DIAGRAM_KIND 
-- 
ALTER TABLE MASTER.KLS_DIAGRAM_KIND ADD (
  CONSTRAINT PK_KLS_DIAGRAM_KIND
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_DIAGRAM_KIND
  ENABLE VALIDATE);

