-- 
-- Foreign Key Constraints for Table KLS_DOC_NUMS 
-- 
ALTER TABLE MASTER.KLS_DOC_NUMS ADD (
  CONSTRAINT KLS_DOC_NUMS_DOC_TYPE_FK 
  FOREIGN KEY (DOC_TYPE_ID) 
  REFERENCES MASTER.KLS_DOC_TYPES (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOC_NUMS ADD (
  CONSTRAINT KLS_DOC_NUMS_RULE_FK 
  FOREIGN KEY (DOC_RULE_ID) 
  REFERENCES MASTER.KLS_DOC_RULES (ID)
  ENABLE NOVALIDATE);

