-- 
-- Foreign Key Constraints for Table KLS_STAN 
-- 
ALTER TABLE MASTER.KLS_STAN ADD (
  CONSTRAINT STAN_GDOR_FK 
  FOREIGN KEY (GDOR_ID) 
  REFERENCES MASTER.KLS_GDOR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_STAN ADD (
  CONSTRAINT STAN_REGION_FK 
  FOREIGN KEY (REGION_ID) 
  REFERENCES MASTER.KLS_REGION (ID)
  ENABLE NOVALIDATE);

