-- 
-- Foreign Key Constraints for Table KLS_NAPR 
-- 
ALTER TABLE MASTER.KLS_NAPR ADD (
  CONSTRAINT NAPR_NAPR_MOS_FK 
  FOREIGN KEY (NAPR_MOS_ID) 
  REFERENCES MASTER.KLS_NAPR_MOS (ID)
  ENABLE NOVALIDATE);

