-- 
-- Non Foreign Key Constraints for Table KLS_ISKL_TAR 
-- 
ALTER TABLE MASTER.KLS_ISKL_TAR ADD (
  CONSTRAINT PK_KLS_ISKL_TAR
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_ISKL_TAR
  ENABLE VALIDATE);

