-- 
-- Non Foreign Key Constraints for Table KLS_DEFI_MASS 
-- 
ALTER TABLE MASTER.KLS_DEFI_MASS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DEFI_MASS ADD (
  CONSTRAINT PK_KLS_DEFI_MASS
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_DEFI_MASS
  ENABLE VALIDATE);

