-- 
-- Non Foreign Key Constraints for Table KLS_OTGR_POST_KONS 
-- 
ALTER TABLE MASTER.KLS_OTGR_POST_KONS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_OTGR_POST_KONS ADD (
  CONSTRAINT OTGR_POST_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.OTGR_POST_PK
  ENABLE VALIDATE);

