-- 
-- Foreign Key Constraints for Table KLS_PROD 
-- 
ALTER TABLE MASTER.KLS_PROD ADD (
  CONSTRAINT PROD_AZC_PR_GRP_FK 
  FOREIGN KEY (AZC_PR_GRP_ID) 
  REFERENCES MASTER.AZC_PROD_GROUP (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD ADD (
  CONSTRAINT PROD_MOS_GRP_FK 
  FOREIGN KEY (MOS_GRP_ID) 
  REFERENCES MASTER.KLS_PROD_MOSGRP (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD ADD (
  CONSTRAINT PROD_PROD_GR_FK 
  FOREIGN KEY (KOD_OKDP) 
  REFERENCES MASTER.KLS_PROD_GR_KONS (ID_GR)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD ADD (
  CONSTRAINT PROD_PROD_GU12_FK 
  FOREIGN KEY (PROD_GU12_ID) 
  REFERENCES MASTER.KLS_PROD_GU12 (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD ADD (
  CONSTRAINT PROD_PROD_NAR_FK 
  FOREIGN KEY (PROD_NAR_ID) 
  REFERENCES MASTER.KLS_PROD_NAR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD ADD (
  CONSTRAINT PROD_PROD_PLAN_FK 
  FOREIGN KEY (PROD_PLAN_ID) 
  REFERENCES MASTER.KLS_PROD_PLAN (ID)
  DISABLE NOVALIDATE);

