-- 
-- Non Foreign Key Constraints for Table KLS_GOST 
-- 
ALTER TABLE MASTER.KLS_GOST ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GOST ADD (
  CONSTRAINT PK_KLS_GOST
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_GOST
  ENABLE VALIDATE);

