-- 
-- Non Foreign Key Constraints for Table KLS_ORG_KIND 
-- 
ALTER TABLE MASTER.KLS_ORG_KIND ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_ORG_KIND ADD (
  CONSTRAINT ORG_KIND_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.ORG_KIND_PK
  ENABLE VALIDATE);

