-- 
-- Non Foreign Key Constraints for Table KLS_ROLE 
-- 
ALTER TABLE MASTER.KLS_ROLE ADD (
  CHECK ("PREDPR_ROLE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_ROLE ADD (
  CONSTRAINT ROLE_SPR_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.ROLE_SPR_PK
  ENABLE VALIDATE);

