-- 
-- Non Foreign Key Constraints for Table KLS_DECADA 
-- 
ALTER TABLE MASTER.KLS_DECADA ADD (
  CHECK ("DATEPLAN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DECADA ADD (
  CHECK ("DEC" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DECADA ADD (
  CHECK ("DATEDECN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DECADA ADD (
  CHECK ("DATEDECK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DECADA ADD (
  CONSTRAINT DEC_PK
  PRIMARY KEY
  (KOD)
  USING INDEX MASTER.DEC_PK
  ENABLE VALIDATE);

