-- 
-- Foreign Key Constraints for Table KLS_PREDPR_CONTACTS 
-- 
ALTER TABLE MASTER.KLS_PREDPR_CONTACTS ADD (
  CONSTRAINT PREDPR_CONTACTS_PREDPR_FK 
  FOREIGN KEY (PREDPR_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

