-- 
-- Non Foreign Key Constraints for Table KLS_PROD_KONS 
-- 
ALTER TABLE MASTER.KLS_PROD_KONS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_KONS ADD (
  CHECK ("PROD_KONS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_KONS ADD (
  CHECK ("FLAG_FAS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_KONS ADD (
  CHECK ("KOEF_KG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_KONS ADD (
  CHECK ("KOEF_LIT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_KONS ADD (
  CHECK ("TIP_AKCIZ_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_KONS ADD (
  CONSTRAINT PROD_KONS_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PROD_KONS_PK
  ENABLE VALIDATE);

