-- 
-- Non Foreign Key Constraints for Table KLS_GD_TIP_PATH 
-- 
ALTER TABLE MASTER.KLS_GD_TIP_PATH ADD (
  CHECK ("NAME_STAN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GD_TIP_PATH ADD (
  CONSTRAINT TIP_PATH_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.TIP_PATH_PK
  ENABLE VALIDATE);

