-- 
-- Non Foreign Key Constraints for Table KLS_PROD_RAZMET 
-- 
ALTER TABLE MASTER.KLS_PROD_RAZMET ADD (
  CHECK ("IS_AUTO_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD_RAZMET ADD (
  CONSTRAINT PROD_RAZMET_PK
  PRIMARY KEY
  (RAZMET)
  USING INDEX MASTER.PROD_RAZMET_PK
  ENABLE VALIDATE);

