-- 
-- Non Foreign Key Constraints for Table KLS_GOSPROG 
-- 
ALTER TABLE MASTER.KLS_GOSPROG ADD (
  CHECK ("GOSPROG_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_GOSPROG ADD (
  CONSTRAINT GOSPROG_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.GOSPROG_PK
  ENABLE VALIDATE);

