-- 
-- Foreign Key Constraints for Table KLS_PASP 
-- 
ALTER TABLE MASTER.KLS_PASP ADD (
  CONSTRAINT PASP_MESTO_FK 
  FOREIGN KEY (MESTO_ID) 
  REFERENCES MASTER.KLS_MESTO (ID)
  ENABLE NOVALIDATE);

