-- 
-- Non Foreign Key Constraints for Table KLS_TEX_PD 
-- 
ALTER TABLE MASTER.KLS_TEX_PD ADD (
  CHECK ("PLATTARIF_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_TEX_PD ADD (
  CHECK ("TEX_PD_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_TEX_PD ADD (
  CONSTRAINT TEX_PD_PK
  PRIMARY KEY
  (ID, GROTP_ID)
  USING INDEX MASTER.TEX_PD_PK
  ENABLE VALIDATE);

