-- 
-- Non Foreign Key Constraints for Table KLS_ZAKAZ_PERIOD 
-- 
ALTER TABLE MASTER.KLS_ZAKAZ_PERIOD ADD (
  CONSTRAINT KLS_ZAKAZ_PERIOD_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.KLS_ZAKAZ_PERIOD_PK
  ENABLE VALIDATE);

