-- 
-- Foreign Key Constraints for Table KLS_VALSVED 
-- 
ALTER TABLE MASTER.KLS_VALSVED ADD (
  CONSTRAINT VALSVED_KODIF_FK 
  FOREIGN KEY (KODIF_ID) 
  REFERENCES MASTER.KLS_KODIF (ID)
  ENABLE NOVALIDATE);

