-- 
-- Non Foreign Key Constraints for Table KLS_STATUS_ZAKAZ 
-- 
ALTER TABLE MASTER.KLS_STATUS_ZAKAZ ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_STATUS_ZAKAZ ADD (
  CONSTRAINT PK_KLS_STATUS_ZAKAZ
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_STATUS_ZAKAZ
  ENABLE VALIDATE);

