-- 
-- Non Foreign Key Constraints for Table KLS_VAG_STATUS 
-- 
ALTER TABLE MASTER.KLS_VAG_STATUS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_VAG_STATUS ADD (
  CONSTRAINT PK_KLS_VAG_STATUS
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_VAG_STATUS
  ENABLE VALIDATE);

