-- 
-- Non Foreign Key Constraints for Table KLS_BILL_POS_TYPE 
-- 
ALTER TABLE MASTER.KLS_BILL_POS_TYPE ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_BILL_POS_TYPE ADD (
  CONSTRAINT PK_KLS_PAYMENTS_DEST
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_PAYMENTS_DEST
  ENABLE VALIDATE);

