-- 
-- Non Foreign Key Constraints for Table KLS_DOC_RULES 
-- 
ALTER TABLE MASTER.KLS_DOC_RULES ADD (
  CONSTRAINT PK_KLS_DOC_RULES
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_DOC_RULES
  ENABLE VALIDATE);

