-- 
-- Non Foreign Key Constraints for Table KLS_RS 
-- 
ALTER TABLE MASTER.KLS_RS ADD (
  CHECK ("RS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_RS ADD (
  CONSTRAINT PK_KLS_RS
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_RS
  ENABLE VALIDATE);

