-- 
-- Non Foreign Key Constraints for Table KLS_KODIF_PASP_UNP 
-- 
ALTER TABLE MASTER.KLS_KODIF_PASP_UNP ADD (
  CHECK ("KODIF_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_KODIF_PASP_UNP ADD (
  CHECK ("IS_AUTO_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_KODIF_PASP_UNP ADD (
  CONSTRAINT PK_KLS_KODIF_PASP_UNP
  PRIMARY KEY
  (KOD_POKAZATEL)
  USING INDEX MASTER.PK_KLS_KODIF_PASP_UNP
  ENABLE VALIDATE);

