-- 
-- Non Foreign Key Constraints for Table KLS_PROD 
-- 
ALTER TABLE MASTER.KLS_PROD ADD (
  CHECK ("ID_GROUP_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD ADD (
  CHECK ("NAME_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD ADD (
  CHECK ("LONG_NAME_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD ADD (
  CHECK ("ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD ADD (
  CHECK ("FLG_ALLOWED" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD ADD (
  CHECK ("PROD_NAR_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD ADD (
  CHECK ("SF_GROTP_VIEW" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD ADD (
  CHECK ("SF_POLUCH_VIEW" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD ADD (
  CHECK ("SF_NDS_VIEW" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PROD ADD (
  CONSTRAINT PROD_PK
  PRIMARY KEY
  (ID_NPR)
  USING INDEX MASTER.PROD_PK
  ENABLE VALIDATE);

