-- 
-- Non Foreign Key Constraints for Table KLS_NARIAD 
-- 
ALTER TABLE MASTER.KLS_NARIAD ADD (
  CHECK ("NUM_NAR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_NARIAD ADD (
  CHECK ("DATE_NAR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_NARIAD ADD (
  CHECK ("DATE_END" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_NARIAD ADD (
  CHECK ("MESTO_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_NARIAD ADD (
  CHECK ("IS_LOADED" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_NARIAD ADD (
  CONSTRAINT NARIAD_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.NARIAD_PK
  ENABLE VALIDATE);

