-- 
-- Non Foreign Key Constraints for Table KLS_USL_OPL 
-- 
ALTER TABLE MASTER.KLS_USL_OPL ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_USL_OPL ADD (
  CHECK ("KOL_DN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_USL_OPL ADD (
  CONSTRAINT USL_OPL_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.USL_OPL_PK
  ENABLE VALIDATE);

