-- 
-- Non Foreign Key Constraints for Table KLS_PERTYPE 
-- 
ALTER TABLE MASTER.KLS_PERTYPE ADD (
  CHECK ("PERTYPE_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PERTYPE ADD (
  CHECK ("SORTBY" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PERTYPE ADD (
  CONSTRAINT PERTYPE_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PERTYPE_PK
  ENABLE VALIDATE);

