-- 
-- Non Foreign Key Constraints for Table KLS_INSURE 
-- 
ALTER TABLE MASTER.KLS_INSURE ADD (
  CHECK ("INSURE_NUMBER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_INSURE ADD (
  CHECK ("INSURE_YEAR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_INSURE ADD (
  CHECK ("INSURE_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_INSURE ADD (
  CHECK ("FULL_SUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_INSURE ADD (
  CONSTRAINT INSURE_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.INSURE_PK
  ENABLE VALIDATE);

