-- 
-- Non Foreign Key Constraints for Table KLS_PASP_INSP 
-- 
ALTER TABLE MASTER.KLS_PASP_INSP ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_PASP_INSP ADD (
  CONSTRAINT PK_KLS_PASP_INSP
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KLS_PASP_INSP
  ENABLE VALIDATE);

