-- 
-- Foreign Key Constraints for Table KLS_REGION 
-- 
ALTER TABLE MASTER.KLS_REGION ADD (
  CONSTRAINT REGION_STATES_FK 
  FOREIGN KEY (STATES_ID) 
  REFERENCES MASTER.KLS_STATES (ID)
  ENABLE NOVALIDATE);

