-- 
-- Non Foreign Key Constraints for Table KLS_RASST 
-- 
ALTER TABLE MASTER.KLS_RASST ADD (
  CHECK ("MIN_RASST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_RASST ADD (
  CHECK ("MAX_RASST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_RASST ADD (
  CHECK ("NAME_RASST" IS NOT NULL)
  DISABLE NOVALIDATE);

