-- 
-- Non Foreign Key Constraints for Table KLS_DATES 
-- 
ALTER TABLE MASTER.KLS_DATES ADD (
  CHECK ("IS_WORK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DATES ADD (
  CONSTRAINT PK_KLS_DATES
  PRIMARY KEY
  (VALUE)
  USING INDEX MASTER.PK_KLS_DATES
  ENABLE VALIDATE);

