-- 
-- Non Foreign Key Constraints for Table KLS_DOVER 
-- 
ALTER TABLE MASTER.KLS_DOVER ADD (
  CHECK ("NUM_DOVER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOVER ADD (
  CHECK ("DATE_DOVER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOVER ADD (
  CHECK ("DATE_END" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOVER ADD (
  CHECK ("PREDPR_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOVER ADD (
  CHECK ("IS_LOADED" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KLS_DOVER ADD (
  CONSTRAINT DOVER_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.DOVER_PK
  ENABLE VALIDATE);

