-- 
-- Non Foreign Key Constraints for Table KSSS_PREDPR_R3_CUSTOMERS_DESC 
-- 
ALTER TABLE MASTER.KSSS_PREDPR_R3_CUSTOMERS_DESC ADD (
  CHECK ("IS_AUTO_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KSSS_PREDPR_R3_CUSTOMERS_DESC ADD (
  CONSTRAINT KSSS_PREDPR_R3_CUST_DESC_PK
  PRIMARY KEY
  (KSSS_PREDPR_ID, R3_CUSTOMERS)
  USING INDEX MASTER.KSSS_PREDPR_R3_CUST_DESC_PK
  ENABLE VALIDATE);

