-- 
-- Non Foreign Key Constraints for Table KSSS_MATERIAL 
-- 
ALTER TABLE MASTER.KSSS_MATERIAL ADD (
  CONSTRAINT MATERIAL_ID_PK
  PRIMARY KEY
  (MATERIAL_ID)
  USING INDEX MASTER.MATERIAL_ID_PK
  ENABLE VALIDATE);

