-- 
-- Foreign Key Constraints for Table KSSS_PREDPR_R3_CUSTOMERS_DESC 
-- 
ALTER TABLE MASTER.KSSS_PREDPR_R3_CUSTOMERS_DESC ADD (
  CONSTRAINT KSSS_PREDPR_R3_CUSTOMERS_FK 
  FOREIGN KEY (R3_CUSTOMERS) 
  REFERENCES MASTER.R3_CUSTOMERS (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KSSS_PREDPR_R3_CUSTOMERS_DESC ADD (
  CONSTRAINT KSSS_PREDPR_R3_CUST_PREDPR_FK 
  FOREIGN KEY (KSSS_PREDPR_ID) 
  REFERENCES MASTER.KSSS_PREDPR (KSSS_PREDPR_ID)
  ENABLE NOVALIDATE);

