-- 
-- Non Foreign Key Constraints for Table KSSS_PREDPR 
-- 
ALTER TABLE MASTER.KSSS_PREDPR ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KSSS_PREDPR ADD (
  CONSTRAINT KSSS_PREDPR_PK
  PRIMARY KEY
  (KSSS_PREDPR_ID)
  USING INDEX MASTER.KSSS_PREDPR_PK
  ENABLE VALIDATE);

