-- 
-- Non Foreign Key Constraints for Table KTU_2_NPO_PREF_SVED 
-- 
ALTER TABLE MASTER.KTU_2_NPO_PREF_SVED ADD (
  CONSTRAINT PK_KTU_2_NPO_PREF_SVED
  PRIMARY KEY
  (PREF_NAME)
  USING INDEX MASTER.PK_KTU_2_NPO_PREF_SVED
  ENABLE VALIDATE);

