-- 
-- Non Foreign Key Constraints for Table KVIT_DATE_VIR 
-- 
ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("BILL_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("KVIT_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("BILL_POS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("DATE_VIR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("VES_CIST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("VZLIV" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("KOL_NET" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("SUM_PROD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("SUM_PROD_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("SUM_AKCIZ" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("SUM_GSM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("TARIF_ORIG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("TARIF_ALT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("TARIF" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("TARIF_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("TARIF_GUARD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("TARIF_GUARD_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("SUM_VOZN11" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("SUM_VOZN11_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("SUM_VOZN12" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("SUM_VOZN12_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("SUM_STRAH" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("TARIF19" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("VES_BRUTTO" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CHECK ("OWNERSHIP_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_DATE_VIR ADD (
  CONSTRAINT PK_KVIT_DATE_VIR
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_KVIT_DATE_VIR
  ENABLE VALIDATE);

