-- 
-- Non Foreign Key Constraints for Table KVIT_VNEPLAN 
-- 
ALTER TABLE MASTER.KVIT_VNEPLAN ADD (
  CONSTRAINT KVIT_VNEPLAN_PK
  PRIMARY KEY
  (NUM_KVIT, NOM_Z)
  USING INDEX MASTER.KVIT_VNEPLAN_PK
  ENABLE VALIDATE);

