-- 
-- Foreign Key Constraints for Table KVIT 
-- 
ALTER TABLE MASTER.KVIT ADD (
  CONSTRAINT KVIT_EXPED_FK 
  FOREIGN KEY (EXPED_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT ADD (
  CONSTRAINT KVIT_FORMNAKL_FK 
  FOREIGN KEY (FORMNAKL_ID) 
  REFERENCES MASTER.KLS_FORMNAKL (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT ADD (
  CONSTRAINT KVIT_MESTO_FK 
  FOREIGN KEY (MESTO_ID) 
  REFERENCES MASTER.KLS_MESTO (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT ADD (
  CONSTRAINT KVIT_MONTH_FK 
  FOREIGN KEY (NOM_ZD) 
  REFERENCES MASTER.MONTH (NOM_ZD)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT ADD (
  CONSTRAINT KVIT_PERER_FK 
  FOREIGN KEY (PERER_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT ADD (
  CONSTRAINT KVIT_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT ADD (
  CONSTRAINT KVIT_UPAK_FK 
  FOREIGN KEY (UPAK_ID) 
  REFERENCES MASTER.KLS_UPAK (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT ADD (
  CONSTRAINT KVIT_VAGONTYPE_FK 
  FOREIGN KEY (VAGONTYPE_ID) 
  REFERENCES MASTER.KLS_VAGONTYPE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT ADD (
  CONSTRAINT KVIT_VAGOWNER_FK 
  FOREIGN KEY (VAGOWNER_ID) 
  REFERENCES MASTER.KLS_VAGOWNER (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT ADD (
  CONSTRAINT KVIT_VETKA_OTP_FK 
  FOREIGN KEY (VETKA_OTP_ID) 
  REFERENCES MASTER.KLS_VETKA_OTP (ID)
  ENABLE NOVALIDATE);

