-- 
-- Non Foreign Key Constraints for Table KVIT_ALFA 
-- 
ALTER TABLE MASTER.KVIT_ALFA ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_ALFA ADD (
  CHECK ("KOL_NET" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.KVIT_ALFA ADD (
  CONSTRAINT KVIT_ALFA_PK
  PRIMARY KEY
  (CON_ID, KVIT_ID)
  USING INDEX MASTER.KVIT_ALFA_PK
  ENABLE VALIDATE);

