-- 
-- Non Foreign Key Constraints for Table LINK_PARUS_PREDPR 
-- 
ALTER TABLE MASTER.LINK_PARUS_PREDPR ADD (
  CHECK ("RN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LINK_PARUS_PREDPR ADD (
  CHECK ("PREDPR_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LINK_PARUS_PREDPR ADD (
  CHECK ("IS_AUTO_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LINK_PARUS_PREDPR ADD (
  CONSTRAINT PK_PARUS_PREDPR_LINK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_PARUS_PREDPR_LINK
  ENABLE VALIDATE);

