-- 
-- Foreign Key Constraints for Table LOAD_FIL_ORG 
-- 
ALTER TABLE MASTER.LOAD_FIL_ORG ADD (
  CONSTRAINT FIL_ORG_FILIAL_FK 
  FOREIGN KEY (FILIAL_ID) 
  REFERENCES MASTER.ORG_STRUCTURE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_ORG ADD (
  CONSTRAINT FIL_ORG_ORG_STRU_FK 
  FOREIGN KEY (ORG_STRU_ID) 
  REFERENCES MASTER.ORG_STRUCTURE (ID)
  ENABLE NOVALIDATE);

