-- 
-- Non Foreign Key Constraints for Table LOAD_FIL_REALIZ 
-- 
ALTER TABLE MASTER.LOAD_FIL_REALIZ ADD (
  CHECK ("FILIAL_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_REALIZ ADD (
  CHECK ("FIL_PERIOD_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_REALIZ ADD (
  CHECK ("FIL_ORG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_REALIZ ADD (
  CHECK ("FIL_PROD_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_REALIZ ADD (
  CHECK ("REP_TYPE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_REALIZ ADD (
  CHECK ("TYPE_OPER_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_REALIZ ADD (
  CHECK ("FACT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_REALIZ ADD (
  CHECK ("FACT_SUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_REALIZ ADD (
  CONSTRAINT FIL_REALIZ_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.FIL_REALIZ_PK
  ENABLE VALIDATE);

