-- 
-- Non Foreign Key Constraints for Table LOAD_FIL_PERIODS 
-- 
ALTER TABLE MASTER.LOAD_FIL_PERIODS ADD (
  CHECK ("DATE_REPORT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_PERIODS ADD (
  CONSTRAINT FIL_PERIOD_PK
  PRIMARY KEY
  (ID, FILIAL_ID, REP_TYPE_ID)
  USING INDEX MASTER.FIL_PERIOD_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.LOAD_FIL_PERIODS ADD (
  CONSTRAINT FIL_PERIOD_FIL_PERIOD_AK_UK
  UNIQUE (FILIAL_ID, DATE_REPORT, REP_TYPE_ID)
  USING INDEX MASTER.FIL_PERIOD_FIL_PERIOD_AK_UK
  ENABLE VALIDATE);

