-- 
-- Non Foreign Key Constraints for Table LOAD_FIL_ORG 
-- 
ALTER TABLE MASTER.LOAD_FIL_ORG ADD (
  CHECK ("TAG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_ORG ADD (
  CHECK ("ORG_KIND_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_ORG ADD (
  CHECK ("IS_AUTO_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_ORG ADD (
  CHECK ("FILIAL_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_ORG ADD (
  CONSTRAINT FIL_ORG_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.FIL_ORG_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.LOAD_FIL_ORG ADD (
  CONSTRAINT FIL_ORG_FIL_ORG_AK_UK
  UNIQUE (FILIAL_ID, TAG)
  USING INDEX MASTER.FIL_ORG_FIL_ORG_AK_UK
  ENABLE VALIDATE);

