-- 
-- Foreign Key Constraints for Table LOAD_FIL_PERIODS 
-- 
ALTER TABLE MASTER.LOAD_FIL_PERIODS ADD (
  CONSTRAINT FIL_PERIOD_ORG_STRU_FK 
  FOREIGN KEY (FILIAL_ID) 
  REFERENCES MASTER.ORG_STRUCTURE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_PERIODS ADD (
  CONSTRAINT FIL_PERIOD_REP_TYPE_FK 
  FOREIGN KEY (REP_TYPE_ID) 
  REFERENCES MASTER.LOAD_FIL_REP_TYPES (ID)
  ENABLE NOVALIDATE);

