-- 
-- Foreign Key Constraints for Table LOAD_FIL_REALIZ 
-- 
ALTER TABLE MASTER.LOAD_FIL_REALIZ ADD (
  CONSTRAINT FIL_REALIZ_FIL_ORG_FK 
  FOREIGN KEY (FIL_ORG_ID) 
  REFERENCES MASTER.LOAD_FIL_ORG (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_REALIZ ADD (
  CONSTRAINT FIL_REALIZ_FIL_PERIOD_FK 
  FOREIGN KEY (FIL_PERIOD_ID, FILIAL_ID, REP_TYPE_ID) 
  REFERENCES MASTER.LOAD_FIL_PERIODS (ID,FILIAL_ID,REP_TYPE_ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.LOAD_FIL_REALIZ ADD (
  CONSTRAINT FIL_REALIZ_FIL_PROD_FK 
  FOREIGN KEY (FIL_PROD_ID) 
  REFERENCES MASTER.LOAD_FIL_PROD (ID)
  ENABLE NOVALIDATE);

