-- 
-- Non Foreign Key Constraints for Table MAP_SETTLEMENTS 
-- 
ALTER TABLE MASTER.MAP_SETTLEMENTS ADD (
  CHECK ("ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MAP_SETTLEMENTS ADD (
  CHECK ("X" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MAP_SETTLEMENTS ADD (
  CHECK ("Y" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MAP_SETTLEMENTS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MAP_SETTLEMENTS ADD (
  CHECK ("SIZE1" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MAP_SETTLEMENTS ADD (
  CHECK ("SIZE2" IS NOT NULL)
  DISABLE NOVALIDATE);

