-- 
-- Non Foreign Key Constraints for Table MAP_REGIONS 
-- 
ALTER TABLE MASTER.MAP_REGIONS ADD (
  CONSTRAINT PK_MAP_REGIONS
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_MAP_REGIONS
  ENABLE VALIDATE);

