-- 
-- Non Foreign Key Constraints for Table MAP_PRIMITIVES 
-- 
ALTER TABLE MASTER.MAP_PRIMITIVES ADD (
  CHECK ("X" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MAP_PRIMITIVES ADD (
  CHECK ("Y" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MAP_PRIMITIVES ADD (
  CHECK ("ORDER_REC" IS NOT NULL)
  DISABLE NOVALIDATE);

