-- 
-- Non Foreign Key Constraints for Table MASTER_QUERY_TYPES_DESC 
-- 
ALTER TABLE MASTER.MASTER_QUERY_TYPES_DESC ADD (
  CHECK ("STRUCTURE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_QUERY_TYPES_DESC ADD (
  CHECK ("TYPE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_QUERY_TYPES_DESC ADD (
  CHECK ("IS_AUTO_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_QUERY_TYPES_DESC ADD (
  CONSTRAINT PK_MASTER_QUERY_TYPES_DESC
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_MASTER_QUERY_TYPES_DESC
  ENABLE VALIDATE);

