-- 
-- Non Foreign Key Constraints for Table MASTER_QUERY_TYPES 
-- 
ALTER TABLE MASTER.MASTER_QUERY_TYPES ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_QUERY_TYPES ADD (
  CONSTRAINT PK_MASTER_QUERY_TYPES
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_MASTER_QUERY_TYPES
  ENABLE VALIDATE);

