-- 
-- Non Foreign Key Constraints for Table MASTER_LINKS_STRUCTURE 
-- 
ALTER TABLE MASTER.MASTER_LINKS_STRUCTURE ADD (
  CHECK ("ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_LINKS_STRUCTURE ADD (
  CHECK ("CAPTION" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_LINKS_STRUCTURE ADD (
  CHECK ("TABLE_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_LINKS_STRUCTURE ADD (
  CHECK ("TABLE_LINK_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_LINKS_STRUCTURE ADD (
  CHECK ("TABLE_LINK_PK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_LINKS_STRUCTURE ADD (
  CHECK ("TABLE_LINK_PK_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_LINKS_STRUCTURE ADD (
  CHECK ("TABLE_LINK_ONE_PK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_LINKS_STRUCTURE ADD (
  CHECK ("TABLE_ONE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_LINKS_STRUCTURE ADD (
  CHECK ("TABLE_LINK_TWO_PK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_LINKS_STRUCTURE ADD (
  CHECK ("TABLE_TWO" IS NOT NULL)
  DISABLE NOVALIDATE);

