-- 
-- Non Foreign Key Constraints for Table MASTER_KLS_STRUCTURE 
-- 
ALTER TABLE MASTER.MASTER_KLS_STRUCTURE ADD (
  CHECK ("CAPTION" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_KLS_STRUCTURE ADD (
  CHECK ("UNIQUE_FIELD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_KLS_STRUCTURE ADD (
  CHECK ("QUERY" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_KLS_STRUCTURE ADD (
  CHECK ("VIEW_TIME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_KLS_STRUCTURE ADD (
  CONSTRAINT PK_MASTER_KLS_STRUCTURE
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_MASTER_KLS_STRUCTURE
  ENABLE VALIDATE);

