-- 
-- Non Foreign Key Constraints for Table MASTER_KLS_FIELD_STRUCTURE 
-- 
ALTER TABLE MASTER.MASTER_KLS_FIELD_STRUCTURE ADD (
  CHECK ("STRUCTURE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_KLS_FIELD_STRUCTURE ADD (
  CHECK ("FIELD_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_KLS_FIELD_STRUCTURE ADD (
  CHECK ("FIELD_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_KLS_FIELD_STRUCTURE ADD (
  CHECK ("FIELD_CAPTION" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_KLS_FIELD_STRUCTURE ADD (
  CHECK ("FIELD_READONLY" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_KLS_FIELD_STRUCTURE ADD (
  CHECK ("FIELD_KIND" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MASTER_KLS_FIELD_STRUCTURE ADD (
  CONSTRAINT MASTER_KLS_FIELD_STRUCTURE_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.MASTER_KLS_FIELD_STRUCTURE_PK
  ENABLE VALIDATE);

