-- 
-- Non Foreign Key Constraints for Table MESTO_LOG 
-- 
ALTER TABLE MASTER.MESTO_LOG ADD (
  CHECK ("ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MESTO_LOG ADD (
  CHECK ("LOG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MESTO_LOG ADD (
  CHECK ("DATE_LOG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MESTO_LOG ADD (
  CHECK ("MESTO_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MESTO_LOG ADD (
  CHECK ("EVENT_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MESTO_LOG ADD (
  CHECK ("USER_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

