-- 
-- Foreign Key Constraints for Table MONTH_REESTR 
-- 
ALTER TABLE MASTER.MONTH_REESTR ADD (
  CONSTRAINT MONTH_REESTR_STATUS_FK 
  FOREIGN KEY (STATUS) 
  REFERENCES MASTER.KLS_STATUS_MONTH_REESTR (ID)
  ENABLE NOVALIDATE);

