-- 
-- Foreign Key Constraints for Table MONTH 
-- 
ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_FORMA_2_FK 
  FOREIGN KEY (FLG_FORMA_2) 
  REFERENCES MASTER.KLS_FORMA_2 (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_GOSPROG_FK 
  FOREIGN KEY (GOSPROG_ID) 
  REFERENCES MASTER.KLS_GOSPROG (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_GP_NAPR_FK 
  FOREIGN KEY (GP_NAPR_ID) 
  REFERENCES MASTER.KLS_GP_NAPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_NAZN_OTG_FK 
  FOREIGN KEY (NAZN_OTG_ID) 
  REFERENCES MASTER.KLS_NAZN_OTG (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_NPR_SOBSTV_FK 
  FOREIGN KEY (NPR_SOBSTV_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_PLANSTRU_FK 
  FOREIGN KEY (PLANSTRU_ID) 
  REFERENCES MASTER.KLS_PLANSTRU (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_POLUCH_FK 
  FOREIGN KEY (POLUCH_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_POTREB_FK 
  FOREIGN KEY (POTREB_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_STAN_FK 
  FOREIGN KEY (STAN_ID) 
  REFERENCES MASTER.KLS_STAN (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_STANOTP_FK 
  FOREIGN KEY (STANOTP_ID) 
  REFERENCES MASTER.KLS_STAN (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_SUPPLIER_FK 
  FOREIGN KEY (SUPPLIER_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_USL_DOG_FK 
  FOREIGN KEY (DOG_ID, USL_NUMBER) 
  REFERENCES MASTER.USL_DOG (DOG_ID,USL_NUMBER)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_VETKA_FK 
  FOREIGN KEY (VETKA_ID) 
  REFERENCES MASTER.KLS_VETKA (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_VID_OTGR_FK 
  FOREIGN KEY (LOAD_ABBR) 
  REFERENCES MASTER.KLS_VID_OTGR (LOAD_ABBR)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT NPODOG_FK 
  FOREIGN KEY (NPODOG_ID) 
  REFERENCES MASTER.KLS_DOG (ID)
  ENABLE NOVALIDATE);

