-- 
-- Non Foreign Key Constraints for Table MONTH_ALFA 
-- 
ALTER TABLE MASTER.MONTH_ALFA ADD (
  CHECK ("XCONFIRM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH_ALFA ADD (
  CHECK ("DATE_PLAN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH_ALFA ADD (
  CHECK ("KOL_NET" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH_ALFA ADD (
  CHECK ("MON_DOB" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH_ALFA ADD (
  CHECK ("MON_DELIV" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH_ALFA ADD (
  CHECK ("STATUS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH_ALFA ADD (
  CONSTRAINT MONTH_ALFA_PK
  PRIMARY KEY
  (CON_ID)
  USING INDEX MASTER.MONTH_ALFA_PK
  ENABLE VALIDATE);

