-- 
-- Foreign Key Constraints for Table MONTH_REESTR_POS 
-- 
ALTER TABLE MASTER.MONTH_REESTR_POS ADD (
  CONSTRAINT MON_REE_POS_MON_REE_FK 
  FOREIGN KEY (MONTH_REESTR_ID) 
  REFERENCES MASTER.MONTH_REESTR (ID)
  ON DELETE CASCADE
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH_REESTR_POS ADD (
  CONSTRAINT MON_REE_POS_PRIORITY_FK 
  FOREIGN KEY (PRIORITY) 
  REFERENCES MASTER.KLS_PRIORITY_MONTH_REESTR (ID)
  ENABLE NOVALIDATE);

