-- 
-- Non Foreign Key Constraints for Table MONTH_REE 
-- 
ALTER TABLE MASTER.MONTH_REE ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH_REE ADD (
  CONSTRAINT MONTH_REE_PK
  PRIMARY KEY
  (DATE_REE, DOP_REE, NOM_ZD)
  USING INDEX MASTER.MONTH_REE_PK
  ENABLE VALIDATE);

