-- 
-- Non Foreign Key Constraints for Table MONTH 
-- 
ALTER TABLE MASTER.MONTH ADD (
  CHECK ("STANOTP_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("NPR_SOBSTV_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("STAN_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("VETKA_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("POLUCH_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("TEX_PD_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("NAZN_OTG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("LOAD_ABBR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("DOG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("USL_NUMBER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("GOSPROG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("TONN_DECLARED" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("TONN_LOADED" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("CIST_DECLARED" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("CIST_LOADED" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("FLG_ALLOW_8_AXES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("FLG_UPPER_SLIV" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("FLG_DOP_CIST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("FLG_FORMA_2" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("FLG_OBOGR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("DATE_PLAN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("INPUT_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("UPDATE_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("POTREB_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("GROTP_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("IS_EXP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("CIST_FACT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CHECK ("TONN_FACT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH ADD (
  CONSTRAINT MONTH_PK
  PRIMARY KEY
  (NOM_ZD)
  USING INDEX MASTER.MONTH_PK
  ENABLE VALIDATE);

