-- 
-- Non Foreign Key Constraints for Table MONTH_VISIR 
-- 
ALTER TABLE MASTER.MONTH_VISIR ADD (
  CHECK ("DATE_REE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH_VISIR ADD (
  CHECK ("DOP_REE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH_VISIR ADD (
  CHECK ("NOM_ZD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH_VISIR ADD (
  CHECK ("APP_USERS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.MONTH_VISIR ADD (
  CONSTRAINT MON_VISIR_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.MON_VISIR_PK
  ENABLE VALIDATE);

