-- 
-- Non Foreign Key Constraints for Table NAKL 
-- 
ALTER TABLE MASTER.NAKL ADD (
  CHECK ("MESTO_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.NAKL ADD (
  CHECK ("LOAD_TYPE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.NAKL ADD (
  CHECK ("NAKL_NUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.NAKL ADD (
  CHECK ("NAKL_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.NAKL ADD (
  CHECK ("FORMNAKL_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.NAKL ADD (
  CHECK ("VES_CIST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.NAKL ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.NAKL ADD (
  CHECK ("UPAK_VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.NAKL ADD (
  CHECK ("VES_ALL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.NAKL ADD (
  CONSTRAINT NAKL_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.NAKL_PK
  ENABLE VALIDATE);

