-- 
-- Foreign Key Constraints for Table NPR_PRICES 
-- 
ALTER TABLE MASTER.NPR_PRICES ADD (
  CONSTRAINT NPR_PRICES_CAT_CEN_FK 
  FOREIGN KEY (CAT_CEN_ID) 
  REFERENCES MASTER.KLS_CAT_CEN (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.NPR_PRICES ADD (
  CONSTRAINT NPR_PRICES_OWNERSHIP_FK 
  FOREIGN KEY (OWNERSHIP_ID) 
  REFERENCES MASTER.KLS_OWNERSHIP (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.NPR_PRICES ADD (
  CONSTRAINT NPR_PRICES_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.NPR_PRICES ADD (
  CONSTRAINT NPR_PRICES_SUPPLIER_FK 
  FOREIGN KEY (SUPPLIER_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

