-- 
-- Non Foreign Key Constraints for Table OBOROT_KONS 
-- 
ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("DATE_OPER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("KOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("KG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("LIT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("CENA_POKUP_BN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("CENA_POKUP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("SUMMA_POKUP_BN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("SUMMA_POKUP_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("SUMMA_POKUP_AKCIZ" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("SUMMA_POKUP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("CENA_REALIZ_BN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("CENA_REALIZ" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("SUMMA_REALIZ_BN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("SUMMA_REALIZ_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("SUMMA_REALIZ_AKCIZ" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("SUMMA_REALIZ" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("CENA_UCHET" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("SUMMA_UCHET" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("UPDATE_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("AKCIZ_SVED" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("ORG_STRU_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("PREDPR_KONS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("PROD_KONS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("PREDPR_CLASS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("TIP_OP_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("LOAD_TYPE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CHECK ("ORG_POLUCH_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OBOROT_KONS ADD (
  CONSTRAINT OBOROT_PK
  PRIMARY KEY
  (FILIAL_ID, ID_OPER)
  USING INDEX MASTER.OBOROT_PK
  ENABLE VALIDATE);

