-- 
-- Non Foreign Key Constraints for Table OIL_GRAFIK 
-- 
ALTER TABLE MASTER.OIL_GRAFIK ADD (
  CONSTRAINT OIL_GRAFIK_PK
  PRIMARY KEY
  (KOD)
  USING INDEX MASTER.OIL_GRAFIK_PK
  ENABLE VALIDATE);

