-- 
-- Non Foreign Key Constraints for Table OIL_MESTOR 
-- 
ALTER TABLE MASTER.OIL_MESTOR ADD (
  CONSTRAINT OIL_MESTOR_PK
  PRIMARY KEY
  (KOD)
  USING INDEX MASTER.OIL_MESTOR_PK
  ENABLE VALIDATE);

