-- 
-- Non Foreign Key Constraints for Table OPL 
-- 
ALTER TABLE MASTER.OPL ADD (
  CHECK ("SUMMA" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OPL ADD (
  CHECK ("DATA_POST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OPL ADD (
  CHECK ("NOM_DOG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OPL ADD (
  CHECK ("NOM_DOK" IS NOT NULL)
  DISABLE NOVALIDATE);

