-- 
-- Non Foreign Key Constraints for Table ORG_RELATIONS 
-- 
ALTER TABLE MASTER.ORG_RELATIONS ADD (
  CHECK ("KIND_RELA_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ORG_RELATIONS ADD (
  CONSTRAINT ORG_REL_PK
  PRIMARY KEY
  (ORG_STRU_1_ID, ORG_STRU_2_ID)
  USING INDEX MASTER.ORG_REL_PK
  ENABLE VALIDATE);

