-- 
-- Foreign Key Constraints for Table ORG_STRUCTURE 
-- 
ALTER TABLE MASTER.ORG_STRUCTURE ADD (
  CONSTRAINT ORG_STRU_ORG_KIND_FK 
  FOREIGN KEY (ORG_KIND_ID) 
  REFERENCES MASTER.KLS_ORG_KIND (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.ORG_STRUCTURE ADD (
  CONSTRAINT ORG_STRU_ORG_TYPE_FK 
  FOREIGN KEY (ORG_TYPE_ID) 
  REFERENCES MASTER.KLS_ORG_TYPE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.ORG_STRUCTURE ADD (
  CONSTRAINT ORG_STRU_PREDPR_FK 
  FOREIGN KEY (PREDPR_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

