-- 
-- Non Foreign Key Constraints for Table ORG_STRUCTURE 
-- 
ALTER TABLE MASTER.ORG_STRUCTURE ADD (
  CONSTRAINT CHECK_LOAD_FAS
  CHECK (LOAD_FAS_FROM_PARUS+LOAD_FAS_FROM_XLS<2)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.ORG_STRUCTURE ADD (
  CONSTRAINT CHECK_LOAD_NALIV
  CHECK (LOAD_NALIV_FROM_PARUS+LOAD_NALIV_FROM_XLS<2)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.ORG_STRUCTURE ADD (
  CHECK ("ADRESS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ORG_STRUCTURE ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ORG_STRUCTURE ADD (
  CHECK ("ORG_KIND_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ORG_STRUCTURE ADD (
  CHECK ("ORG_TYPE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ORG_STRUCTURE ADD (
  CONSTRAINT ORG_STRU_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.ORG_STRU_PK
  ENABLE VALIDATE);

