-- 
-- Foreign Key Constraints for Table OSTAT_VYRAB 
-- 
ALTER TABLE MASTER.OSTAT_VYRAB ADD (
  CONSTRAINT OSTAT_VYRAB_PROD 
  FOREIGN KEY (ID_PROD_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

