-- 
-- Non Foreign Key Constraints for Table OSTAT_VYRAB 
-- 
ALTER TABLE MASTER.OSTAT_VYRAB ADD (
  CHECK ("ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.OSTAT_VYRAB ADD (
  UNIQUE (ID)
  USING INDEX
    TABLESPACE USERSINDX
  ENABLE VALIDATE);

