-- 
-- Non Foreign Key Constraints for Table PARUS_STORE_ORG_STRU_LINK 
-- 
ALTER TABLE MASTER.PARUS_STORE_ORG_STRU_LINK ADD (
  CHECK ("STORE_RN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PARUS_STORE_ORG_STRU_LINK ADD (
  CHECK ("ORG_STRU_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PARUS_STORE_ORG_STRU_LINK ADD (
  CHECK ("IS_AUTO_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PARUS_STORE_ORG_STRU_LINK ADD (
  CHECK ("IS_MAIN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PARUS_STORE_ORG_STRU_LINK ADD (
  CONSTRAINT PK_PARUS_STORE_ORG_STRU_LINK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_PARUS_STORE_ORG_STRU_LINK
  ENABLE VALIDATE);

