-- 
-- Foreign Key Constraints for Table PAYMENTS_ON_BILLS 
-- 
ALTER TABLE MASTER.PAYMENTS_ON_BILLS ADD (
  CONSTRAINT PAYMENTS_ON_BILLS_FK1 
  FOREIGN KEY (BILL_POS_ID, NOM_DOK) 
  REFERENCES MASTER.BILL_POS (BILL_POS_ID,NOM_DOK)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PAYMENTS_ON_BILLS ADD (
  CONSTRAINT PAYMENTS_ON_BILLS_FK2 
  FOREIGN KEY (PAYMENTS_ID) 
  REFERENCES MASTER.PAYMENTS (ID)
  ENABLE NOVALIDATE);

