-- 
-- Non Foreign Key Constraints for Table PAYMENTS_ON_BILL_050208 
-- 
ALTER TABLE MASTER.PAYMENTS_ON_BILL_050208 ADD (
  CHECK ("ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PAYMENTS_ON_BILL_050208 ADD (
  CHECK ("NOM_DOK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PAYMENTS_ON_BILL_050208 ADD (
  CHECK ("BILL_POS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PAYMENTS_ON_BILL_050208 ADD (
  CHECK ("PAYMENTS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PAYMENTS_ON_BILL_050208 ADD (
  CHECK ("SUMMA" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PAYMENTS_ON_BILL_050208 ADD (
  CHECK ("DATE_REALIZ" IS NOT NULL)
  DISABLE NOVALIDATE);

