-- 
-- Foreign Key Constraints for Table PAYMENTS_TO_BILLS 
-- 
ALTER TABLE MASTER.PAYMENTS_TO_BILLS ADD (
  CONSTRAINT PAYMENTS_TO_BILLS_FK1 
  FOREIGN KEY (NOM_DOK) 
  REFERENCES MASTER.BILLS (NOM_DOK)
  ON DELETE CASCADE
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.PAYMENTS_TO_BILLS ADD (
  CONSTRAINT PAYMETS_TO_BILLS_FK2 
  FOREIGN KEY (PAYMENTS_ID) 
  REFERENCES MASTER.PAYMENTS (ID)
  ON DELETE CASCADE
  ENABLE NOVALIDATE);

