-- 
-- Foreign Key Constraints for Table PAYMENTS_PROD 
-- 
ALTER TABLE MASTER.PAYMENTS_PROD ADD (
  CONSTRAINT PAYMENTS_PROD_NPR_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ON DELETE CASCADE
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.PAYMENTS_PROD ADD (
  CONSTRAINT PAYMENTS_PROD_PAY_FK 
  FOREIGN KEY (PAYMENTS_ID) 
  REFERENCES MASTER.PAYMENTS (ID)
  ON DELETE CASCADE
  ENABLE NOVALIDATE);

