-- 
-- Non Foreign Key Constraints for Table PAYMENTS 
-- 
ALTER TABLE MASTER.PAYMENTS ADD (
  CHECK ("PAYFORM_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PAYMENTS ADD (
  CHECK ("DEST_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PAYMENTS ADD (
  CHECK ("RS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PAYMENTS ADD (
  CONSTRAINT PK_PAYMENTS
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_PAYMENTS
  ENABLE VALIDATE);

