-- 
-- Non Foreign Key Constraints for Table PLAN_RESU 
-- 
ALTER TABLE MASTER.PLAN_RESU ADD (
  CHECK ("PLAN_UTMSK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_RESU ADD (
  CHECK ("HRAN_UTMSK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_RESU ADD (
  CHECK ("OSTAT_UTMSK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_RESU ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_RESU ADD (
  CHECK ("PLAN_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_RESU ADD (
  CHECK ("PLAN_PER_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_RESU ADD (
  CHECK ("SOBSTV_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_RESU ADD (
  CHECK ("REFINER_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_RESU ADD (
  CONSTRAINT PLAN_RESU_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PLAN_RESU_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.PLAN_RESU ADD (
  CONSTRAINT PLAN_RESU_PLAN_RESU_AK_UK
  UNIQUE (PLAN_ID, PLAN_PER_ID, PROD_ID_NPR, REFINER_ID, SOBSTV_ID)
  USING INDEX MASTER.PLAN_RESU_PLAN_RESU_AK_UK
  ENABLE VALIDATE);

