-- 
-- Non Foreign Key Constraints for Table PLAN_POST_HIST 
-- 
ALTER TABLE MASTER.PLAN_POST_HIST ADD (
  CHECK ("PLAN_CENA" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_HIST ADD (
  CHECK ("PLAN_VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_HIST ADD (
  CHECK ("PLAN_SUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_HIST ADD (
  CHECK ("PLAN_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_HIST ADD (
  CHECK ("PLAN_PER_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_HIST ADD (
  CHECK ("PLANSTRU_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_HIST ADD (
  CHECK ("DOG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_HIST ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_HIST ADD (
  CHECK ("PAYFORM_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_HIST ADD (
  CONSTRAINT PL_PST_HST_PK
  PRIMARY KEY
  (ID, NUM_IZM)
  USING INDEX MASTER.PL_PST_HST_PK
  ENABLE VALIDATE);

