-- 
-- Foreign Key Constraints for Table PLAN_POST 
-- 
ALTER TABLE MASTER.PLAN_POST ADD (
  CONSTRAINT PLAN_POST_CAT_CEN_FK 
  FOREIGN KEY (CAT_CEN_ID) 
  REFERENCES MASTER.KLS_CAT_CEN (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST ADD (
  CONSTRAINT PLAN_POST_DOG_FK 
  FOREIGN KEY (DOG_ID) 
  REFERENCES MASTER.KLS_DOG (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST ADD (
  CONSTRAINT PLAN_POST_PAYFORM_FK 
  FOREIGN KEY (PAYFORM_ID) 
  REFERENCES MASTER.KLS_PAYFORM (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST ADD (
  CONSTRAINT PLAN_POST_PLAN_PER_FK 
  FOREIGN KEY (PLAN_ID, PLAN_PER_ID) 
  REFERENCES MASTER.PLAN_PERIODS (PLAN_ID,ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST ADD (
  CONSTRAINT PLAN_POST_PLANSTRU_FK 
  FOREIGN KEY (PLANSTRU_ID) 
  REFERENCES MASTER.KLS_PLANSTRU (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST ADD (
  CONSTRAINT PLAN_POST_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

