-- 
-- Non Foreign Key Constraints for Table PLAN_POST_SVOD 
-- 
ALTER TABLE MASTER.PLAN_POST_SVOD ADD (
  CHECK ("DATE_PLAN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_SVOD ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_SVOD ADD (
  CHECK ("HRAN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_SVOD ADD (
  CHECK ("SUPPLIER_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_SVOD ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_SVOD ADD (
  CHECK ("PLANSTRU_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_SVOD ADD (
  CHECK ("IS_KORR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_SVOD ADD (
  CONSTRAINT PLANPOST_S_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PLANPOST_S_PK
  ENABLE VALIDATE);

