-- 
-- Foreign Key Constraints for Table PLAN_PERIODS 
-- 
ALTER TABLE MASTER.PLAN_PERIODS ADD (
  CONSTRAINT PLAN_PER_PLAN_FK 
  FOREIGN KEY (PLAN_ID) 
  REFERENCES MASTER.KLS_PLAN (ID)
  ENABLE NOVALIDATE);

