-- 
-- Non Foreign Key Constraints for Table PLAN_PERIODS 
-- 
ALTER TABLE MASTER.PLAN_PERIODS ADD (
  CHECK ("DATE_PLAN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_PERIODS ADD (
  CHECK ("NUM_IZM_POST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_PERIODS ADD (
  CHECK ("NUM_IZM_RESU" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_PERIODS ADD (
  CHECK ("BEGIN_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_PERIODS ADD (
  CONSTRAINT PLAN_PER_PK
  PRIMARY KEY
  (PLAN_ID, ID)
  USING INDEX MASTER.PLAN_PER_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.PLAN_PERIODS ADD (
  CONSTRAINT PLAN_PER_PLAN_PER_AK_UK
  UNIQUE (PLAN_ID, DATE_PLAN, BEGIN_DATE)
  USING INDEX MASTER.PLAN_PER_PLAN_PER_AK_UK
  ENABLE VALIDATE);

