-- 
-- Foreign Key Constraints for Table PLAN_RESU 
-- 
ALTER TABLE MASTER.PLAN_RESU ADD (
  CONSTRAINT PLAN_RESU_PLAN_PER_FK 
  FOREIGN KEY (PLAN_ID, PLAN_PER_ID) 
  REFERENCES MASTER.PLAN_PERIODS (PLAN_ID,ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_RESU ADD (
  CONSTRAINT PLAN_RESU_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_RESU ADD (
  CONSTRAINT PLAN_RESU_REFINER_FK 
  FOREIGN KEY (REFINER_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_RESU ADD (
  CONSTRAINT PLAN_RESU_SOBSTV_FK 
  FOREIGN KEY (SOBSTV_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

