-- 
-- Foreign Key Constraints for Table PLAN_POST_SVOD 
-- 
ALTER TABLE MASTER.PLAN_POST_SVOD ADD (
  CONSTRAINT PLANPOST_S_PREDPR_FK 
  FOREIGN KEY (SUPPLIER_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.PLAN_POST_SVOD ADD (
  CONSTRAINT PLANPOST_S_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

