-- 
-- Foreign Key Constraints for Table PODACHA 
-- 
ALTER TABLE MASTER.PODACHA ADD (
  CONSTRAINT PODACHA_LOAD_TYPE_FK 
  FOREIGN KEY (LOAD_TYPE_ID) 
  REFERENCES MASTER.KLS_LOAD_TYPE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.PODACHA ADD (
  CONSTRAINT PODACHA_MESTO_FK 
  FOREIGN KEY (MESTO_ID) 
  REFERENCES MASTER.KLS_MESTO (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.PODACHA ADD (
  CONSTRAINT PODACHA_VETKA_OTP_FK 
  FOREIGN KEY (VETKA_OTP_ID) 
  REFERENCES MASTER.KLS_VETKA_OTP (ID)
  ENABLE NOVALIDATE);

