-- 
-- Non Foreign Key Constraints for Table PODACHA_ROWS 
-- 
ALTER TABLE MASTER.PODACHA_ROWS ADD (
  CHECK ("PODACHA_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PODACHA_ROWS ADD (
  CHECK ("NUM_CIST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PODACHA_ROWS ADD (
  CONSTRAINT POD_ROWS_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.POD_ROWS_PK
  ENABLE VALIDATE);

