-- 
-- Non Foreign Key Constraints for Table PREDPR_ROLE 
-- 
ALTER TABLE MASTER.PREDPR_ROLE ADD (
  CHECK ("PREDPR_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PREDPR_ROLE ADD (
  CHECK ("KLS_ROLE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.PREDPR_ROLE ADD (
  CONSTRAINT ROLE_PR_ROLE_PR_UK
  UNIQUE (PREDPR_ID, KLS_ROLE_ID)
  USING INDEX MASTER.ROLE_PR_ROLE_PR_UK
  ENABLE VALIDATE);

