-- 
-- Foreign Key Constraints for Table PREDPR_ROLE 
-- 
ALTER TABLE MASTER.PREDPR_ROLE ADD (
  CONSTRAINT ROLE_PR_PREDPR_FK 
  FOREIGN KEY (PREDPR_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.PREDPR_ROLE ADD (
  CONSTRAINT ROLE_PR_ROLE_SPR_FK 
  FOREIGN KEY (KLS_ROLE_ID) 
  REFERENCES MASTER.KLS_ROLE (ID)
  ENABLE NOVALIDATE);

