-- 
-- Non Foreign Key Constraints for Table PROGRAM_USERS 
-- 
ALTER TABLE MASTER.PROGRAM_USERS ADD (
  CONSTRAINT PROGRAM_USERS_PK
  PRIMARY KEY
  (ORGANIZATION, APPLICATION, FIO)
  USING INDEX MASTER.PROGRAM_USERS_PK
  ENABLE VALIDATE);

