-- 
-- Non Foreign Key Constraints for Table R3_BILL_POS 
-- 
ALTER TABLE MASTER.R3_BILL_POS ADD (
  CHECK ("CENA_BN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_BILL_POS ADD (
  CHECK ("CENA" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_BILL_POS ADD (
  CHECK ("SUMMA_BN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_BILL_POS ADD (
  CHECK ("SUMMA_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_BILL_POS ADD (
  CHECK ("SUMMA_AKCIZ" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_BILL_POS ADD (
  CHECK ("SUMMA" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_BILL_POS ADD (
  CHECK ("VBAP_MATNR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_BILL_POS ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_BILL_POS ADD (
  CONSTRAINT R3_BILLPOS_PK
  PRIMARY KEY
  (VBELN, R3_BILL_POS_ID)
  USING INDEX MASTER.R3_BILLPOS_PK
  ENABLE VALIDATE);

