-- 
-- Non Foreign Key Constraints for Table R3_BLOCKS 
-- 
ALTER TABLE MASTER.R3_BLOCKS ADD (
  CONSTRAINT BLOCKS_PK
  PRIMARY KEY
  (V_TJ30_TXT04)
  USING INDEX MASTER.BLOCKS_PK
  ENABLE VALIDATE);

