-- 
-- Non Foreign Key Constraints for Table R3_CAT_CEN 
-- 
ALTER TABLE MASTER.R3_CAT_CEN ADD (
  CHECK ("IS_AUTO_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_CAT_CEN ADD (
  CONSTRAINT PK_R3_CAT_CEN
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_R3_CAT_CEN
  ENABLE VALIDATE);

