-- 
-- Non Foreign Key Constraints for Table R3_CUSTOMERS 
-- 
ALTER TABLE MASTER.R3_CUSTOMERS ADD (
  CHECK ("IS_AUTO_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_CUSTOMERS ADD (
  CONSTRAINT CUSTOMERS_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.CUSTOMERS_PK
  ENABLE VALIDATE);

