-- 
-- Foreign Key Constraints for Table R3_CC 
-- 
ALTER TABLE MASTER.R3_CC ADD (
  CONSTRAINT CC_CUSTOMERS_FK 
  FOREIGN KEY (CUSTOMERS_ID) 
  REFERENCES MASTER.R3_CUSTOMERS (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.R3_CC ADD (
  CONSTRAINT CC_DOG_FK 
  FOREIGN KEY (DOG_ID) 
  REFERENCES MASTER.KLS_DOG (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.R3_CC ADD (
  CONSTRAINT CC_EKKO_LIFNR_FK 
  FOREIGN KEY (EKKO_LIFNR) 
  REFERENCES MASTER.R3_VENDORS (ID)
  ENABLE NOVALIDATE);

