-- 
-- Foreign Key Constraints for Table R3_CUSTOMERS 
-- 
ALTER TABLE MASTER.R3_CUSTOMERS ADD (
  CONSTRAINT CUSTOMERS_PREDPR_FK 
  FOREIGN KEY (PREDPR_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.R3_CUSTOMERS ADD (
  CONSTRAINT CUSTOMERS_VENDORS_FK 
  FOREIGN KEY (VENDORS_ID) 
  REFERENCES MASTER.R3_VENDORS (ID)
  ENABLE NOVALIDATE);

