-- 
-- Non Foreign Key Constraints for Table R3_KVIT2SAP 
-- 
ALTER TABLE MASTER.R3_KVIT2SAP ADD (
  CONSTRAINT KVIT2SAP_PK
  PRIMARY KEY
  (ID_MS)
  USING INDEX MASTER.KVIT2SAP_PK
  ENABLE VALIDATE);

