-- 
-- Foreign Key Constraints for Table R3_MATERIALS 
-- 
ALTER TABLE MASTER.R3_MATERIALS ADD (
  CONSTRAINT MATERIALS_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.R3_MATERIALS ADD (
  CONSTRAINT MATERIALS_R3_MAT_GRP_FK 
  FOREIGN KEY (GROUP_S) 
  REFERENCES MASTER.R3_MATERIALS_GRP (GROUP_S)
  ENABLE NOVALIDATE);

