-- 
-- Non Foreign Key Constraints for Table R3_MATERIALS_GRP 
-- 
ALTER TABLE MASTER.R3_MATERIALS_GRP ADD (
  CONSTRAINT R3_MAT_GRP_PK
  PRIMARY KEY
  (GROUP_S)
  USING INDEX MASTER.R3_MAT_GRP_PK
  ENABLE VALIDATE);

