-- 
-- Non Foreign Key Constraints for Table R3_OD 
-- 
ALTER TABLE MASTER.R3_OD ADD (
  CHECK ("ZZZZ_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_OD ADD (
  CHECK ("VBAP_KWMENG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_OD ADD (
  CHECK ("VBAP_UEBTO" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_OD ADD (
  CHECK ("VBAP_KBMENG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_OD ADD (
  CONSTRAINT OD_PK
  PRIMARY KEY
  (VBAK_VBELN, VBAP_POSNR)
  USING INDEX MASTER.OD_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.R3_OD ADD (
  CONSTRAINT OD_R3_OD_AK_UK
  UNIQUE (ZZZZ_ID)
  USING INDEX MASTER.OD_R3_OD_AK_UK
  ENABLE VALIDATE);

