-- 
-- Foreign Key Constraints for Table R3_OA 
-- 
ALTER TABLE MASTER.R3_OA ADD (
  CONSTRAINT OA_KONV_FK 
  FOREIGN KEY (KONV_KSCHL) 
  REFERENCES MASTER.R3_KONV (KSCHL)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.R3_OA ADD (
  CONSTRAINT OA_OD_FK 
  FOREIGN KEY (VBAK_VBELN, VBAP_POSNR) 
  REFERENCES MASTER.R3_OD (VBAK_VBELN,VBAP_POSNR)
  ENABLE NOVALIDATE);

