-- 
-- Foreign Key Constraints for Table R3_ROUTES 
-- 
ALTER TABLE MASTER.R3_ROUTES ADD (
  CONSTRAINT ROUTES_KNANF_FK 
  FOREIGN KEY (KNANF) 
  REFERENCES MASTER.R3_ROUTENODES (KNOTE)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.R3_ROUTES ADD (
  CONSTRAINT ROUTES_KNEND_FK 
  FOREIGN KEY (KNEND) 
  REFERENCES MASTER.R3_ROUTENODES (KNOTE)
  ENABLE NOVALIDATE);

