-- 
-- Non Foreign Key Constraints for Table R3_ROUTENODES 
-- 
ALTER TABLE MASTER.R3_ROUTENODES ADD (
  CONSTRAINT ROUTENODES_PK
  PRIMARY KEY
  (KNOTE)
  USING INDEX MASTER.ROUTENODES_PK
  ENABLE VALIDATE);

