-- 
-- Foreign Key Constraints for Table R3_ROUTENODES 
-- 
ALTER TABLE MASTER.R3_ROUTENODES ADD (
  CONSTRAINT ROUTENODES_R3_GD_FK 
  FOREIGN KEY (BAHNR) 
  REFERENCES MASTER.R3_GD (BAHNR)
  ENABLE NOVALIDATE);

