-- 
-- Non Foreign Key Constraints for Table R3_VENDORS 
-- 
ALTER TABLE MASTER.R3_VENDORS ADD (
  CHECK ("IS_AUTO_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VENDORS ADD (
  CONSTRAINT VENDORS_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.VENDORS_PK
  ENABLE VALIDATE);

