-- 
-- Foreign Key Constraints for Table R3_VENDORS 
-- 
ALTER TABLE MASTER.R3_VENDORS ADD (
  CONSTRAINT VENDORS_CUSTOMERS_FK 
  FOREIGN KEY (CUSTOMERS_ID) 
  REFERENCES MASTER.R3_CUSTOMERS (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VENDORS ADD (
  CONSTRAINT VENDORS_PREDPR_FK 
  FOREIGN KEY (PREDPR_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

