-- 
-- Foreign Key Constraints for Table R3_VBAK 
-- 
ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_AUART_FK 
  FOREIGN KEY (VBAK_AUART) 
  REFERENCES MASTER.R3_AUART (VBAK_AUART)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_BLOCKS_FK 
  FOREIGN KEY (V_TJ30_TXT04) 
  REFERENCES MASTER.R3_BLOCKS (V_TJ30_TXT04)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_CC_FK 
  FOREIGN KEY (VBAK_ZZ021) 
  REFERENCES MASTER.R3_CC (EKKO_ZZ021)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_MATERIALS_FK 
  FOREIGN KEY (VBAP_MATNR) 
  REFERENCES MASTER.R3_MATERIALS (VBAP_MATNR)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_NP_OWNER_FK 
  FOREIGN KEY (NP_OWNER) 
  REFERENCES MASTER.R3_VENDORS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_NP_PRODR_FK 
  FOREIGN KEY (NP_PRODR) 
  REFERENCES MASTER.R3_VENDORS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_OT_LIFNR_FK 
  FOREIGN KEY (OT_LIFNR) 
  REFERENCES MASTER.R3_VENDORS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_ROUTES_FK 
  FOREIGN KEY (VBAP_ROUTE) 
  REFERENCES MASTER.R3_ROUTES (ROUTE)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_SH_KUNNR_FK 
  FOREIGN KEY (SH_KUNNR) 
  REFERENCES MASTER.R3_CUSTOMERS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_TRATY_FK 
  FOREIGN KEY (VBKD_TRATY) 
  REFERENCES MASTER.R3_TRATY (VBKD_TRATY)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_VBPA_KUNNR_FK 
  FOREIGN KEY (VBPA_KUNNR) 
  REFERENCES MASTER.R3_CUSTOMERS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_VBPA_KUNNR_SP_FK 
  FOREIGN KEY (VBPA_KUNNR_SP) 
  REFERENCES MASTER.R3_CUSTOMERS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_VSART_FK 
  FOREIGN KEY (VBKD_VSART) 
  REFERENCES MASTER.R3_VSART (VBKD_VSART)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_VSBED_FK 
  FOREIGN KEY (VBAK_VSBED) 
  REFERENCES MASTER.R3_VSBED (VBAK_VSBED)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_VSTEL_FK 
  FOREIGN KEY (VBAP_VSTEL) 
  REFERENCES MASTER.R3_VSTEL (VBAP_VSTEL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.R3_VBAK ADD (
  CONSTRAINT VBAK_WERK_LGORT_FK 
  FOREIGN KEY (VBAP_WERKS, LGORT) 
  REFERENCES MASTER.R3_WERKS_LGORT (VBAP_WERKS,LGORT)
  DISABLE NOVALIDATE);

