-- 
-- Foreign Key Constraints for Table R3_VAGOWNER 
-- 
ALTER TABLE MASTER.R3_VAGOWNER ADD (
  CONSTRAINT R3_VAGOWNER_R3_VENDORS_FK 
  FOREIGN KEY (R3_VENDORS_ID) 
  REFERENCES MASTER.R3_VENDORS (ID)
  ENABLE NOVALIDATE);

