-- 
-- Non Foreign Key Constraints for Table R3_WERKS_LGORT 
-- 
ALTER TABLE MASTER.R3_WERKS_LGORT ADD (
  CONSTRAINT WERK_LGORT_PK
  PRIMARY KEY
  (VBAP_WERKS, LGORT)
  USING INDEX MASTER.WERK_LGORT_PK
  ENABLE VALIDATE);

