-- 
-- Non Foreign Key Constraints for Table REAL_OPL_KTU 
-- 
ALTER TABLE MASTER.REAL_OPL_KTU ADD (
  CHECK ("NOM_DOK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REAL_OPL_KTU ADD (
  CHECK ("UN_DOK" IS NOT NULL)
  DISABLE NOVALIDATE);

