-- 
-- Non Foreign Key Constraints for Table REESTR_IN 
-- 
ALTER TABLE MASTER.REESTR_IN ADD (
  CHECK ("SVED_IN_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REESTR_IN ADD (
  CHECK ("MESTO_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REESTR_IN ADD (
  CHECK ("DATE_OTGR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REESTR_IN ADD (
  CHECK ("NUM_CIST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REESTR_IN ADD (
  CHECK ("EMPTY_VOZ" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REESTR_IN ADD (
  CHECK ("GOST_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REESTR_IN ADD (
  CHECK ("BAD_NUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REESTR_IN ADD (
  CONSTRAINT REESTR_IN_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.REESTR_IN_PK
  ENABLE VALIDATE);

