-- 
-- Non Foreign Key Constraints for Table REESTR_RAIL_DOP_SF 
-- 
ALTER TABLE MASTER.REESTR_RAIL_DOP_SF ADD (
  CHECK ("V_DOK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REESTR_RAIL_DOP_SF ADD (
  CHECK ("V_PLAY" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REESTR_RAIL_DOP_SF ADD (
  CONSTRAINT REESTR_RAIL_DOP_SF_PK
  PRIMARY KEY
  (REESTR_RAIL_DOP_SF_ID)
  USING INDEX MASTER.REESTR_RAIL_DOP_SF_PK
  ENABLE VALIDATE);

