-- 
-- Foreign Key Constraints for Table REESTR_IN 
-- 
ALTER TABLE MASTER.REESTR_IN ADD (
  CONSTRAINT REESTR_IN_KALIBR_FK_I 
  FOREIGN KEY (KALIBR_ID) 
  REFERENCES MASTER.KLS_KALIBR (ID)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REESTR_IN ADD (
  CONSTRAINT REESTR_IN_SVED_IN_FK 
  FOREIGN KEY (SVED_IN_ID) 
  REFERENCES MASTER.SVED_IN (ID)
  ENABLE NOVALIDATE);

