-- 
-- Non Foreign Key Constraints for Table REESTR_RAIL 
-- 
ALTER TABLE MASTER.REESTR_RAIL ADD (
  CONSTRAINT REESTR_RAIL_PK
  PRIMARY KEY
  (REESTR_RAIL_ID)
  USING INDEX MASTER.REESTR_RAIL_PK
  ENABLE VALIDATE);

