-- 
-- Foreign Key Constraints for Table REESTR 
-- 
ALTER TABLE MASTER.REESTR ADD (
  CONSTRAINT REESTR_FORMNAKL_FK 
  FOREIGN KEY (FORMNAKL_ID) 
  REFERENCES MASTER.KLS_FORMNAKL (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.REESTR ADD (
  CONSTRAINT REESTR_NAR_LINE_FK 
  FOREIGN KEY (NAR_LINE_ID) 
  REFERENCES MASTER.KLS_NAR_LINE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.REESTR ADD (
  CONSTRAINT REESTR_UPAK_FK 
  FOREIGN KEY (UPAK_ID) 
  REFERENCES MASTER.KLS_UPAK (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.REESTR ADD (
  CONSTRAINT REESTR_VAGONTYPE_FK 
  FOREIGN KEY (VAGONTYPE_ID) 
  REFERENCES MASTER.KLS_VAGONTYPE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.REESTR ADD (
  CONSTRAINT REESTR_VAGOWNER_FK 
  FOREIGN KEY (VAGOWNER_ID) 
  REFERENCES MASTER.KLS_VAGOWNER (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.REESTR ADD (
  CONSTRAINT REESTR_VETKA_OTP_FK 
  FOREIGN KEY (VETKA_OTP_ID) 
  REFERENCES MASTER.KLS_VETKA_OTP (ID)
  ENABLE NOVALIDATE);

