-- 
-- Foreign Key Constraints for Table REPL_SITE_DESC 
-- 
ALTER TABLE MASTER.REPL_SITE_DESC ADD (
  CONSTRAINT R_SITE_DS_R_SITE_FK 
  FOREIGN KEY (REPL_SITE) 
  REFERENCES MASTER.REPL_SITE (ID)
  ENABLE NOVALIDATE);

