-- 
-- Non Foreign Key Constraints for Table REPL_PROC_TYPES 
-- 
ALTER TABLE MASTER.REPL_PROC_TYPES ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_PROC_TYPES ADD (
  CONSTRAINT R_P_TYPE_1_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.R_P_TYPE_1_PK
  ENABLE VALIDATE);

