-- 
-- Non Foreign Key Constraints for Table REPL_SESSION 
-- 
ALTER TABLE MASTER.REPL_SESSION ADD (
  CHECK ("STATUS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_SESSION ADD (
  CHECK ("OSUSER_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_SESSION ADD (
  CHECK ("TERMINAL_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_SESSION ADD (
  CONSTRAINT R_SESS_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.R_SESS_PK
  ENABLE VALIDATE);

