-- 
-- Non Foreign Key Constraints for Table REPL_DEPENDENCE 
-- 
ALTER TABLE MASTER.REPL_DEPENDENCE ADD (
  CHECK ("REPL_PARENT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_DEPENDENCE ADD (
  CHECK ("REPL_CHILD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_DEPENDENCE ADD (
  CONSTRAINT R_DEPEND_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.R_DEPEND_PK
  ENABLE VALIDATE);

