-- 
-- Non Foreign Key Constraints for Table REPL_SITE_TYPES 
-- 
ALTER TABLE MASTER.REPL_SITE_TYPES ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_SITE_TYPES ADD (
  CONSTRAINT R_S_TYPE_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.R_S_TYPE_PK
  ENABLE VALIDATE);

