-- 
-- Non Foreign Key Constraints for Table REPL_LIST 
-- 
ALTER TABLE MASTER.REPL_LIST ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CHECK ("TAG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CHECK ("REPL_KIND" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CHECK ("SRC_SITE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CHECK ("DST_SITE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CHECK ("SP_TYPE_BF" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CHECK ("SP_TYPE_AF" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CHECK ("CHECK_MODE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CHECK ("F_APPL_TAG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CHECK ("F_CONFIRM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CHECK ("IS_ACTIVE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CHECK ("IS_TRACKING" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CONSTRAINT R_LIST_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.R_LIST_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CONSTRAINT R_LIST_R_LIST_AK_UK
  UNIQUE (TAG)
  USING INDEX MASTER.R_LIST_R_LIST_AK_UK
  ENABLE VALIDATE);

