-- 
-- Non Foreign Key Constraints for Table REPL_FILE_TYPES 
-- 
ALTER TABLE MASTER.REPL_FILE_TYPES ADD (
  CHECK ("TAG" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_FILE_TYPES ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_FILE_TYPES ADD (
  CHECK ("FILE_KIND" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_FILE_TYPES ADD (
  CONSTRAINT R_FILETYP_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.R_FILETYP_PK
  ENABLE VALIDATE);

