-- 
-- Non Foreign Key Constraints for Table REPL_SITE_DESC 
-- 
ALTER TABLE MASTER.REPL_SITE_DESC ADD (
  CHECK ("REPL_SITE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_SITE_DESC ADD (
  CHECK ("REPL_LIST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_SITE_DESC ADD (
  CHECK ("ACTIVE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_SITE_DESC ADD (
  CHECK ("IS_AUTO_LINK" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_SITE_DESC ADD (
  CONSTRAINT R_SITE_DS_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.R_SITE_DS_PK
  ENABLE VALIDATE);

