-- 
-- Non Foreign Key Constraints for Table REPL_SESSION_LOG 
-- 
ALTER TABLE MASTER.REPL_SESSION_LOG ADD (
  CHECK ("SESSION_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_SESSION_LOG ADD (
  CHECK ("STATUS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_SESSION_LOG ADD (
  CHECK ("LOG_TIME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_SESSION_LOG ADD (
  CONSTRAINT R_SESS_L_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.R_SESS_L_PK
  ENABLE VALIDATE);

