-- 
-- Non Foreign Key Constraints for Table REPL_CONFIG 
-- 
ALTER TABLE MASTER.REPL_CONFIG ADD (
  CONSTRAINT R_CONFIG_PK
  PRIMARY KEY
  (REPL_SITE)
  USING INDEX MASTER.R_CONFIG_R_SITE_FK_I
  ENABLE VALIDATE);

