-- 
-- Non Foreign Key Constraints for Table REPL_DSN_TYPES 
-- 
ALTER TABLE MASTER.REPL_DSN_TYPES ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_DSN_TYPES ADD (
  CHECK ("CHECK_FILE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_DSN_TYPES ADD (
  CONSTRAINT R_DSNTYP_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.R_DSNTYP_PK
  ENABLE VALIDATE);

