-- 
-- Foreign Key Constraints for Table REPL_LIST 
-- 
ALTER TABLE MASTER.REPL_LIST ADD (
  CONSTRAINT R_LIST_DST_SITE_FK 
  FOREIGN KEY (DST_SITE) 
  REFERENCES MASTER.REPL_SITE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CONSTRAINT R_LIST_FILE_TYPE_I_FK 
  FOREIGN KEY (FILE_TYPE_I) 
  REFERENCES MASTER.REPL_FILE_TYPES (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CONSTRAINT R_LIST_FILE_TYPE_O_FK 
  FOREIGN KEY (FILE_TYPE_O) 
  REFERENCES MASTER.REPL_FILE_TYPES (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CONSTRAINT R_LIST_R_CHK_M_FK 
  FOREIGN KEY (CHECK_MODE) 
  REFERENCES MASTER.REPL_CHECK_MODES (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CONSTRAINT R_LIST_R_INFO_T_FK 
  FOREIGN KEY (SRC_INFO_T) 
  REFERENCES MASTER.REPL_INFO_TYPES (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CONSTRAINT R_LIST_R_KIND_FK 
  FOREIGN KEY (REPL_KIND) 
  REFERENCES MASTER.REPL_KINDS (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CONSTRAINT R_LIST_R_P_TYPE_1_FK 
  FOREIGN KEY (SP_TYPE_AF) 
  REFERENCES MASTER.REPL_PROC_TYPES (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CONSTRAINT R_LIST_SP_TYPE_FK 
  FOREIGN KEY (SP_TYPE_BF) 
  REFERENCES MASTER.REPL_PROC_TYPES (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_LIST ADD (
  CONSTRAINT R_LIST_SRC_SITE_FK 
  FOREIGN KEY (SRC_SITE) 
  REFERENCES MASTER.REPL_SITE (ID)
  ENABLE NOVALIDATE);

