-- 
-- Non Foreign Key Constraints for Table REPL_FILE_KINDS 
-- 
ALTER TABLE MASTER.REPL_FILE_KINDS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_FILE_KINDS ADD (
  CONSTRAINT R_FILKND_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.R_FILKND_PK
  ENABLE VALIDATE);

