-- 
-- Non Foreign Key Constraints for Table REPL_CALL_OUT 
-- 
ALTER TABLE MASTER.REPL_CALL_OUT ADD (
  CHECK ("REPL_LIST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_CALL_OUT ADD (
  CHECK ("SRC_SITE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_CALL_OUT ADD (
  CHECK ("DST_SITE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_CALL_OUT ADD (
  CHECK ("REPL_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_CALL_OUT ADD (
  CHECK ("REPL_SQL1" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_CALL_OUT ADD (
  CHECK ("OSUSER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_CALL_OUT ADD (
  CHECK ("FILE_TYPE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_CALL_OUT ADD (
  CONSTRAINT R_CALL_O_PK
  PRIMARY KEY
  (REPL_ID)
  USING INDEX MASTER.R_CALL_O_PK
  ENABLE VALIDATE);

