-- 
-- Non Foreign Key Constraints for Table REPL_KINDS 
-- 
ALTER TABLE MASTER.REPL_KINDS ADD (
  CHECK ("NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPL_KINDS ADD (
  CONSTRAINT R_KIND_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.R_KIND_PK
  ENABLE VALIDATE);

