-- 
-- Non Foreign Key Constraints for Table REPORTS_REALIZ 
-- 
ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("BEGIN_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("END_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("IS_CRT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("NUM_REP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("INN_SRC" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("REP_ROW" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("REP_CRT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("KVIT_NUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("KV_DATA" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("INN_CNTR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("DOG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("PLT_NUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("PLT_DATA" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("TOVAR_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("PACK_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("TOV_SRC" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("TOV_CLS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("WEGHT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("CLR_PRC" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("AKCIZ" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("FULL_PRC" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("CLR_CST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("FULL_CST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("INN_RES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("REG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("USERCREATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("DATECREATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CHECK ("BILL_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_REALIZ ADD (
  CONSTRAINT PK_REPORTS_REALIZ
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_REPORTS_REALIZ
  ENABLE VALIDATE);

