-- 
-- Non Foreign Key Constraints for Table REPORTS_PARAM 
-- 
ALTER TABLE MASTER.REPORTS_PARAM ADD (
  CHECK ("REPORTS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_PARAM ADD (
  CONSTRAINT PK_REPORTS_PARAM
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_REPORTS_PARAM
  ENABLE VALIDATE);

