-- 
-- Non Foreign Key Constraints for Table REPORTS_NUM_REP 
-- 
ALTER TABLE MASTER.REPORTS_NUM_REP ADD (
  CHECK ("REP_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_NUM_REP ADD (
  CHECK ("BEGIN_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_NUM_REP ADD (
  CHECK ("END_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_NUM_REP ADD (
  CHECK ("IS_CRT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_NUM_REP ADD (
  CHECK ("NUM_REP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS_NUM_REP ADD (
  CONSTRAINT REPORTS_NUM_REP_UK
  UNIQUE (REP_ID, BEGIN_DATE, END_DATE, IS_CRT)
  USING INDEX MASTER.REPORTS_NUM_REP_UK
  ENABLE VALIDATE);

