-- 
-- Non Foreign Key Constraints for Table REPORT_GROUPS 
-- 
ALTER TABLE MASTER.REPORT_GROUPS ADD (
  CHECK ("REPORT_GROUP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORT_GROUPS ADD (
  CHECK ("REPORT_GROUP_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORT_GROUPS ADD (
  CONSTRAINT PK_REPORT_GROUPS
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_REPORT_GROUPS
  ENABLE VALIDATE);

