-- 
-- Non Foreign Key Constraints for Table REPORTS 
-- 
ALTER TABLE MASTER.REPORTS ADD (
  CHECK ("REPORT_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS ADD (
  CHECK ("REPORT_FILE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS ADD (
  CHECK ("IS_MSSQL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS ADD (
  CHECK ("IS_VIP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS ADD (
  CHECK ("ASK_RUN_PROC" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS ADD (
  CHECK ("ZIP_CSV" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORTS ADD (
  CONSTRAINT PK_REPORTS
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_REPORTS
  ENABLE VALIDATE);

