-- 
-- Non Foreign Key Constraints for Table REPORT_TIP_DATES 
-- 
ALTER TABLE MASTER.REPORT_TIP_DATES ADD (
  CHECK ("REP_KIND" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORT_TIP_DATES ADD (
  CHECK ("TIP_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORT_TIP_DATES ADD (
  CHECK ("DEF_TIP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.REPORT_TIP_DATES ADD (
  CHECK ("VIEW_TIME" IS NOT NULL)
  DISABLE NOVALIDATE);

