-- 
-- Non Foreign Key Constraints for Table SAIO_CHECK 
-- 
ALTER TABLE MASTER.SAIO_CHECK ADD (
  CHECK ("SELECTQUERY" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SAIO_CHECK ADD (
  CHECK ("CREATEQUERY" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SAIO_CHECK ADD (
  CHECK ("IS_ACTIVE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SAIO_CHECK ADD (
  CONSTRAINT PK_SAIO_CHECK
  PRIMARY KEY
  (OUTPUTFILE)
  USING INDEX MASTER.PK_SAIO_CHECK
  ENABLE VALIDATE);

