-- 
-- Foreign Key Constraints for Table SPECIF 
-- 
ALTER TABLE MASTER.SPECIF ADD (
  CONSTRAINT SPECIF_DOG_FK 
  FOREIGN KEY (DOG_ID) 
  REFERENCES MASTER.KLS_DOG (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CONSTRAINT SPECIF_POLUCH_FK 
  FOREIGN KEY (POLUCH_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CONSTRAINT SPECIF_POTREB_FK 
  FOREIGN KEY (POTREB_ID) 
  REFERENCES MASTER.KLS_PREDPR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CONSTRAINT SPECIF_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CONSTRAINT SPECIF_STAN_FK 
  FOREIGN KEY (STAN_ID) 
  REFERENCES MASTER.KLS_STAN (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CONSTRAINT SPECIF_STANOTP_FK 
  FOREIGN KEY (STANOTP_ID) 
  REFERENCES MASTER.KLS_STAN (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CONSTRAINT SPECIF_VETKA_FK 
  FOREIGN KEY (VETKA_ID) 
  REFERENCES MASTER.KLS_VETKA (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CONSTRAINT SPECIF_VID_OTGR_FK 
  FOREIGN KEY (LOAD_ABBR) 
  REFERENCES MASTER.KLS_VID_OTGR (LOAD_ABBR)
  ENABLE NOVALIDATE);

