-- 
-- Non Foreign Key Constraints for Table SPECIF 
-- 
ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("DOG_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("STANOTP_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("STAN_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("VETKA_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("POLUCH_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("POTREB_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("PRIM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("BEGIN_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("END_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("M1" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("M2" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("M3" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("M4" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("M5" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("M6" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("M7" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("M8" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("M9" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("M10" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("M11" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("M12" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("KV1" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("KV2" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("KV3" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("KV4" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("VES_ALL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CHECK ("UPDATE_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SPECIF ADD (
  CONSTRAINT SPECIF_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.SPECIF_PK
  ENABLE VALIDATE);

