-- 
-- Non Foreign Key Constraints for Table STAN_ROLE 
-- 
ALTER TABLE MASTER.STAN_ROLE ADD (
  CHECK ("STAN_KOD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.STAN_ROLE ADD (
  CHECK ("KLS_ROLE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

