-- 
-- Foreign Key Constraints for Table SVED 
-- 
ALTER TABLE MASTER.SVED ADD (
  CONSTRAINT SVED_MESTO_FK 
  FOREIGN KEY (MESTO_ID) 
  REFERENCES MASTER.KLS_MESTO (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.SVED ADD (
  CONSTRAINT SVED_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

