-- 
-- Non Foreign Key Constraints for Table SVED 
-- 
ALTER TABLE MASTER.SVED ADD (
  CHECK ("SVED_NUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED ADD (
  CHECK ("SVED_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED ADD (
  CHECK ("SVED_VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED ADD (
  CHECK ("SVED_CNT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED ADD (
  CHECK ("MESTO_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED ADD (
  CHECK ("VES_CIST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED ADD (
  CHECK ("KOL_NET" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED ADD (
  CHECK ("VES_ALL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED ADD (
  CHECK ("FROM_DBF" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED ADD (
  CONSTRAINT SVED_PK
  PRIMARY KEY
  (ID, FLG_OPERDATA)
  USING INDEX MASTER.SVED_PK
  ENABLE VALIDATE);

