-- 
-- Non Foreign Key Constraints for Table SVED_IN 
-- 
ALTER TABLE MASTER.SVED_IN ADD (
  CHECK ("SVED_NUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED_IN ADD (
  CHECK ("SVED_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED_IN ADD (
  CHECK ("SVED_VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED_IN ADD (
  CHECK ("SVED_CNT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED_IN ADD (
  CHECK ("PROD_ID_NPR" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED_IN ADD (
  CHECK ("MESTO_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED_IN ADD (
  CHECK ("VES_NETTO" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED_IN ADD (
  CHECK ("VES_KVIT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.SVED_IN ADD (
  CONSTRAINT PK_SVED_OIL
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_SVED_OIL
  ENABLE VALIDATE);

