-- 
-- Non Foreign Key Constraints for Table T_SNPORDEXP_UPLOADORD_KSE 
-- 
ALTER TABLE MASTER.T_SNPORDEXP_UPLOADORD_KSE ADD (
  CONSTRAINT T_SNPORDEXP_UPLOADORD_UK1_KSE
  UNIQUE (ORDERID, LOAD_VES)
  USING INDEX MASTER.T_SNPORDEXP_UPLOADORD_UK1_KSE
  ENABLE VALIDATE);

