-- 
-- Non Foreign Key Constraints for Table TEMP_PAYMENTS_PROD 
-- 
ALTER TABLE MASTER.TEMP_PAYMENTS_PROD ADD (
  CONSTRAINT PK_TEMP_PAYMENTS_PROD
  PRIMARY KEY
  (OSUSER_NAME, TERMINAL_NAME, PAYMENTS_ID, PROD_ID_NPR)
  USING INDEX MASTER.PK_TEMP_PAYMENTS_PROD
  ENABLE VALIDATE);

