-- 
-- Non Foreign Key Constraints for Table TEMP_REESTR_PARAMS 
-- 
ALTER TABLE MASTER.TEMP_REESTR_PARAMS ADD (
  CHECK ("DATE_PLAN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TEMP_REESTR_PARAMS ADD (
  CHECK ("DATETIME_REPORT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TEMP_REESTR_PARAMS ADD (
  CONSTRAINT PK_TEMP_REESTR_PARAMS
  PRIMARY KEY
  (TERMINAL_NAME, OSUSER_NAME)
  USING INDEX MASTER.PK_TEMP_REESTR_PARAMS
  ENABLE VALIDATE);

