-- 
-- Non Foreign Key Constraints for Table TEMP_BILL_KVIT_POSSIBLE 
-- 
ALTER TABLE MASTER.TEMP_BILL_KVIT_POSSIBLE ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TEMP_BILL_KVIT_POSSIBLE ADD (
  CHECK ("TARIF" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TEMP_BILL_KVIT_POSSIBLE ADD (
  CHECK ("TARIF19" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TEMP_BILL_KVIT_POSSIBLE ADD (
  CHECK ("SUM_PROD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TEMP_BILL_KVIT_POSSIBLE ADD (
  CHECK ("SUM_AKCIZ" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TEMP_BILL_KVIT_POSSIBLE ADD (
  CHECK ("SUM_PROD_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TEMP_BILL_KVIT_POSSIBLE ADD (
  CHECK ("TARIF_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TEMP_BILL_KVIT_POSSIBLE ADD (
  CHECK ("SUM_VOZN11" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TEMP_BILL_KVIT_POSSIBLE ADD (
  CHECK ("SUM_VOZN11_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TEMP_BILL_KVIT_POSSIBLE ADD (
  CHECK ("SUM_VOZN12" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TEMP_BILL_KVIT_POSSIBLE ADD (
  CHECK ("SUM_VOZN12_NDS" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TEMP_BILL_KVIT_POSSIBLE ADD (
  CHECK ("SUM_STRAH" IS NOT NULL)
  DISABLE NOVALIDATE);

