-- 
-- Non Foreign Key Constraints for Table TEST 
-- 
ALTER TABLE MASTER.TEST ADD (
  CONSTRAINT TEST_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.TEST_PK
  ENABLE VALIDATE);

ALTER TABLE MASTER.TEST ADD (
  CONSTRAINT TEST_TEST_AK_UK
  UNIQUE (NAME)
  USING INDEX MASTER.TEST_TEST_AK_UK
  ENABLE VALIDATE);

