-- 
-- Non Foreign Key Constraints for Table TOW_PUT_KONS 
-- 
ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("DATE_OPER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("KOL_1" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("KG_1" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("CENA_POK_BN_1" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("CENA_POK_1" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("SUMMA_POK_BN_1" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("SUMMA_POK_NDS_1" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("SUMMA_POK_AKCIZ_1" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("SUMMA_POK_1" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("KOL_2" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("KG_2" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("CENA_POK_BN_2" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("CENA_POK_2" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("SUMMA_POK_BN_2" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("SUMMA_POK_NDS_2" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("SUMMA_POK_AKCIZ_2" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("SUMMA_POK_2" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("ORG_STRU_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("PREDPR_KONS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("PROD_KONS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("LOAD_TYPE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CHECK ("ORG_POLUCH_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TOW_PUT_KONS ADD (
  CONSTRAINT TOW_PUT_PK
  PRIMARY KEY
  (FILIAL_ID, ID_OPER)
  USING INDEX MASTER.TOW_PUT_PK
  ENABLE VALIDATE);

