-- 
-- Foreign Key Constraints for Table TRANS 
-- 
ALTER TABLE MASTER.TRANS ADD (
  CONSTRAINT TRANS_LOAD_MOS_FK 
  FOREIGN KEY (LOAD_MOS_ID) 
  REFERENCES MASTER.KLS_LOAD_TYPE_MOS (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CONSTRAINT TRANS_MOS_GRP_FK 
  FOREIGN KEY (MOS_GRP_ID) 
  REFERENCES MASTER.KLS_PROD_MOSGRP (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CONSTRAINT TRANS_NAPR_MOS_FK 
  FOREIGN KEY (NAPR_MOS_ID) 
  REFERENCES MASTER.KLS_NAPR_MOS (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CONSTRAINT TRANS_PROD_GU12_FK 
  FOREIGN KEY (PROD_GU12_ID) 
  REFERENCES MASTER.KLS_PROD_GU12 (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CONSTRAINT TRANS_VAGOWN_MOS_FK 
  FOREIGN KEY (VAGOWN_MOS_ID) 
  REFERENCES MASTER.KLS_VAGOWNER_MOS (ID)
  ENABLE NOVALIDATE);

