-- 
-- Non Foreign Key Constraints for Table TRANS 
-- 
ALTER TABLE MASTER.TRANS ADD (
  CHECK ("DATE_REP" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CHECK ("PLAN_CIST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CHECK ("PLAN_VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CHECK ("PLANDAY_C" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CHECK ("PLANDAY_V" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CHECK ("FACTDAY_C" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CHECK ("FACTDAY_V" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CHECK ("PLANNAR_C" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CHECK ("PLANNAR_V" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CHECK ("FACTNAR_C" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CHECK ("FACTNAR_V" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CHECK ("CIST_EMPTY" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CHECK ("CIST_READY" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CHECK ("VAGOWN_MOS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CHECK ("LOAD_MOS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CHECK ("NAPR_MOS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.TRANS ADD (
  CONSTRAINT TRANS_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.TRANS_PK
  ENABLE VALIDATE);

