-- 
-- Non Foreign Key Constraints for Table UNP_FACT_PASP 
-- 
ALTER MATERIALIZED VIEW MASTER.UNP_FACT_PASP ADD (
  CONSTRAINT SYS_C008340
  PRIMARY KEY
  (ID_FACT_PASP)
  USING INDEX
    TABLESPACE USERSINDX
  ENABLE VALIDATE);
