-- 
-- Non Foreign Key Constraints for Table UNP_SPRAV_OIL_PRODUCT 
-- 
ALTER MATERIALIZED VIEW MASTER.UNP_SPRAV_OIL_PRODUCT ADD (
  CONSTRAINT SYS_C008331
  PRIMARY KEY
  (KOD_OIL_PRODUCT)
  USING INDEX
    TABLESPACE USERSINDX
  ENABLE VALIDATE);
