-- 
-- Foreign Key Constraints for Table USER_RIGHTS 
-- 
ALTER TABLE MASTER.USER_RIGHTS ADD (
  CONSTRAINT USER_RIGHTS_FK_I 
  FOREIGN KEY (GIVENRIGHT) 
  REFERENCES MASTER.KLS_RIGHTS (ID)
  ENABLE NOVALIDATE);

