-- 
-- Non Foreign Key Constraints for Table USER_RIGHTS 
-- 
ALTER TABLE MASTER.USER_RIGHTS ADD (
  CHECK ("GIVENRIGHT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.USER_RIGHTS ADD (
  CHECK ("USERNAME" IS NOT NULL)
  DISABLE NOVALIDATE);

