-- 
-- Foreign Key Constraints for Table USL_DOG 
-- 
ALTER TABLE MASTER.USL_DOG ADD (
  CONSTRAINT USL_DOG_CAT_CEN_FK 
  FOREIGN KEY (CAT_CEN_ID) 
  REFERENCES MASTER.KLS_CAT_CEN (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CONSTRAINT USL_DOG_DOG_FK 
  FOREIGN KEY (DOG_ID) 
  REFERENCES MASTER.KLS_DOG (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CONSTRAINT USL_DOG_PAYDELAY_FK 
  FOREIGN KEY (PAYDELAY_ID) 
  REFERENCES MASTER.KLS_PAYDELAY (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CONSTRAINT USL_DOG_VID_USL_FK 
  FOREIGN KEY (VID_USL_ID) 
  REFERENCES MASTER.KLS_VID_USL (ID)
  ENABLE NOVALIDATE);

