-- 
-- Non Foreign Key Constraints for Table USL_DOG 
-- 
ALTER TABLE MASTER.USL_DOG ADD (
  CHECK ("USL_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CHECK ("USL_BEGIN_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CHECK ("VID_USL_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CHECK ("PAYDELAY_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CHECK ("KOL_DN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CHECK ("USL_AKT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CHECK ("USL_UTV" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CHECK ("USL_BAZ" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CHECK ("PROC_PRED" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CHECK ("USL_SUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CHECK ("PAYFORM_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CHECK ("CAT_CEN_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CHECK ("ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.USL_DOG ADD (
  CONSTRAINT USL_DOG_PK
  PRIMARY KEY
  (DOG_ID, USL_NUMBER)
  USING INDEX MASTER.USL_DOG_PK
  ENABLE VALIDATE);

