-- 
-- Non Foreign Key Constraints for Table UVED 
-- 
ALTER TABLE MASTER.UVED ADD (
  CHECK ("UVED_NUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.UVED ADD (
  CHECK ("UVED_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.UVED ADD (
  CHECK ("LOAD_TYPE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.UVED ADD (
  CHECK ("MESTO_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.UVED ADD (
  CONSTRAINT PK_UVED
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.PK_UVED
  ENABLE VALIDATE);

