-- 
-- Non Foreign Key Constraints for Table VAL_INT 
-- 
ALTER TABLE MASTER.VAL_INT ADD (
  CONSTRAINT VAL_INT_PK
  PRIMARY KEY
  (DD_MM_YYYY, SYB_RNK, N_OB, N_GR_INTEGR, MIN_0, MIN_1)
  USING INDEX MASTER.VAL_INT_PK
  ENABLE VALIDATE);

