-- 
-- Non Foreign Key Constraints for Table VED_OSMOTR_PODPIS 
-- 
ALTER TABLE MASTER.VED_OSMOTR_PODPIS ADD (
  CONSTRAINT VED_OSM_PODPIS_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.VED_OSM_PODPIS_PK
  ENABLE VALIDATE);

