-- 
-- Foreign Key Constraints for Table VED_OSMOTR_ROW 
-- 
ALTER TABLE MASTER.VED_OSMOTR_ROW ADD (
  CONSTRAINT VED_OSMORT_ROW_VED_FK 
  FOREIGN KEY (VED_ID) 
  REFERENCES MASTER.VED_OSMOTR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.VED_OSMOTR_ROW ADD (
  CONSTRAINT VED_OSMOTR_ROW_KALIBR_FK 
  FOREIGN KEY (KALIBR_ID) 
  REFERENCES MASTER.KLS_KALIBR (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.VED_OSMOTR_ROW ADD (
  CONSTRAINT VED_OSMOTR_ROW_PROD_FK 
  FOREIGN KEY (PROD_ID_NPR) 
  REFERENCES MASTER.KLS_PROD (ID_NPR)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.VED_OSMOTR_ROW ADD (
  CONSTRAINT VED_OSMOTR_ROW_VAGONTYPE_FK 
  FOREIGN KEY (VAGONTYPE_ID) 
  REFERENCES MASTER.KLS_VAGONTYPE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.VED_OSMOTR_ROW ADD (
  CONSTRAINT VED_OSMOTR_ROW_VAGOWNER_FK 
  FOREIGN KEY (VAGOWNER_ID) 
  REFERENCES MASTER.KLS_VAGOWNER (ID)
  ENABLE NOVALIDATE);

