-- 
-- Foreign Key Constraints for Table VED_OSMOTR 
-- 
ALTER TABLE MASTER.VED_OSMOTR ADD (
  CONSTRAINT VED_OSMOTR_LOAD_TYPE_FK 
  FOREIGN KEY (LOAD_TYPE_ID) 
  REFERENCES MASTER.KLS_LOAD_TYPE (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.VED_OSMOTR ADD (
  CONSTRAINT VED_OSMOTR_MESTO_FK 
  FOREIGN KEY (MESTO_ID) 
  REFERENCES MASTER.KLS_MESTO (ID)
  ENABLE NOVALIDATE);

