-- 
-- Non Foreign Key Constraints for Table VED_POD_ROW 
-- 
ALTER TABLE MASTER.VED_POD_ROW ADD (
  CHECK ("VED_POD_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.VED_POD_ROW ADD (
  CHECK ("NUM_CIST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.VED_POD_ROW ADD (
  CONSTRAINT VED_POD_ROW_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.VED_POD_ROW_PK
  ENABLE VALIDATE);

