-- 
-- Non Foreign Key Constraints for Table VED_OSMOTR 
-- 
ALTER TABLE MASTER.VED_OSMOTR ADD (
  CHECK ("VED_NUM" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.VED_OSMOTR ADD (
  CHECK ("VED_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.VED_OSMOTR ADD (
  CHECK ("MESTO_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.VED_OSMOTR ADD (
  CHECK ("LOAD_TYPE_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.VED_OSMOTR ADD (
  CHECK ("KOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.VED_OSMOTR ADD (
  CONSTRAINT VED_OSMOTR_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.VED_OSMOTR_PK
  ENABLE VALIDATE);

