-- 
-- Non Foreign Key Constraints for Table VED_OSMOTR_ROW 
-- 
ALTER TABLE MASTER.VED_OSMOTR_ROW ADD (
  CHECK ("VED_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.VED_OSMOTR_ROW ADD (
  CHECK ("POD_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.VED_OSMOTR_ROW ADD (
  CHECK ("NUM_CIST" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.VED_OSMOTR_ROW ADD (
  CHECK ("VAG_STATUS_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.VED_OSMOTR_ROW ADD (
  CONSTRAINT VED_OSMOTR_ROW_C06
  CHECK (gost1510 in (1,2,3,4,5))
  ENABLE VALIDATE);

ALTER TABLE MASTER.VED_OSMOTR_ROW ADD (
  CONSTRAINT VED_OSMORT_ROW_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.VED_OSMORT_ROW_PK
  ENABLE VALIDATE);

