-- 
-- Non Foreign Key Constraints for Table XX101_ZKERP_DATA_X 
-- 
ALTER TABLE MASTER.XX101_ZKERP_DATA_X ADD (
  PRIMARY KEY
  (FILENAME, FILEROWNUM)
  USING INDEX
    TABLESPACE USERS
  ENABLE VALIDATE);

