-- 
-- Non Foreign Key Constraints for Table XX101_ZRAZNAR 
-- 
ALTER TABLE MASTER.XX101_ZRAZNAR ADD (
  CONSTRAINT XX101_ZRAZNAR_PK
  PRIMARY KEY
  (ORDERNUM)
  USING INDEX MASTER.XX101_ZRAZNAR_PK
  ENABLE VALIDATE);

