-- 
-- Non Foreign Key Constraints for Table ZAKAZ_PARUS 
-- 
ALTER TABLE MASTER.ZAKAZ_PARUS ADD (
  CHECK ("DATE_PLAN" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_PARUS ADD (
  CHECK ("INPUT_NUMBER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_PARUS ADD (
  CHECK ("INPUT_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_PARUS ADD (
  CHECK ("IS_ACCEPT" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_PARUS ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_PARUS ADD (
  CHECK ("FACT_VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_PARUS ADD (
  CONSTRAINT ZAKAZ_PARUS_RN_I
  PRIMARY KEY
  (PARUS_RN)
  USING INDEX MASTER.ZAKAZ_PARUS_RN_I
  ENABLE VALIDATE);

