-- 
-- Foreign Key Constraints for Table ZAKAZ 
-- 
ALTER TABLE MASTER.ZAKAZ ADD (
  CONSTRAINT FK_TIP_CORP 
  FOREIGN KEY (TIP_CORP_ID) 
  REFERENCES MASTER.KLS_ZAKAZ_TIP_CORP (ID)
  ENABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ ADD (
  CONSTRAINT ZAKAZ_R01 
  FOREIGN KEY (PERIOD_ID) 
  REFERENCES MASTER.KLS_ZAKAZ_PERIOD (ID)
  ENABLE NOVALIDATE);

