-- 
-- Non Foreign Key Constraints for Table ZAKAZ_SNP_LINKS 
-- 
ALTER TABLE MASTER.ZAKAZ_SNP_LINKS ADD (
  CONSTRAINT ZAKAZ_SNP_LINKS_PK
  PRIMARY KEY
  (DOC301_ID)
  USING INDEX MASTER.ZAKAZ_SNP_LINKS_PK
  ENABLE VALIDATE);

