-- 
-- Non Foreign Key Constraints for Table ZAKAZ_HIST_ISU 
-- 
ALTER TABLE MASTER.ZAKAZ_HIST_ISU ADD (
  CONSTRAINT ZAKAZ_HIST_ISU_PK
  PRIMARY KEY
  (ZAKAZ_HIST_ID)
  USING INDEX MASTER.ZAKAZ_HIST_ISU_PK
  ENABLE VALIDATE);

