-- 
-- Non Foreign Key Constraints for Table ZAKAZ_TEMP 
-- 
ALTER TABLE MASTER.ZAKAZ_TEMP ADD (
  CHECK ("TERMINAL_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_TEMP ADD (
  CHECK ("USER_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

