-- 
-- Foreign Key Constraints for Table ZAKAZ_HIST 
-- 
ALTER TABLE MASTER.ZAKAZ_HIST ADD (
  CONSTRAINT ZAKAZ_HIST_ZAKAZ_FK 
  FOREIGN KEY (ZAKAZ_ID) 
  REFERENCES MASTER.ZAKAZ (ID)
  ON DELETE CASCADE
  ENABLE NOVALIDATE);

