-- 
-- Non Foreign Key Constraints for Table ZAKAZ_HIST 
-- 
ALTER TABLE MASTER.ZAKAZ_HIST ADD (
  CHECK ("ZAKAZ_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_HIST ADD (
  CHECK ("STATUS_ZAKAZ_ID" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_HIST ADD (
  CHECK ("INPUT_NUMBER" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_HIST ADD (
  CHECK ("INPUT_DATE" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_HIST ADD (
  CHECK ("VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_HIST ADD (
  CHECK ("KOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_HIST ADD (
  CHECK ("SPEED_VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_HIST ADD (
  CHECK ("SPEED_KOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_HIST ADD (
  CHECK ("FACT_VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_HIST ADD (
  CHECK ("FACT_KOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_HIST ADD (
  CHECK ("IS_AUTO" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_HIST ADD (
  CHECK ("LOAD_VES" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_HIST ADD (
  CHECK ("LOAD_KOL" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_HIST ADD (
  CONSTRAINT ZAKAZ_HIST_PK
  PRIMARY KEY
  (ID)
  USING INDEX MASTER.ZAKAZ_HIST_PK
  ENABLE VALIDATE);

