-- 
-- Non Foreign Key Constraints for Table ZAKAZ_GRAFIK_TEMP 
-- 
ALTER TABLE MASTER.ZAKAZ_GRAFIK_TEMP ADD (
  CHECK ("TERMINAL_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_GRAFIK_TEMP ADD (
  CHECK ("USER_NAME" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_GRAFIK_TEMP ADD (
  CHECK ("DATE_LOAD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_GRAFIK_TEMP ADD (
  CHECK ("TONN_LOAD" IS NOT NULL)
  DISABLE NOVALIDATE);

ALTER TABLE MASTER.ZAKAZ_GRAFIK_TEMP ADD (
  CHECK ("CIST_LOAD" IS NOT NULL)
  DISABLE NOVALIDATE);

