--
-- CLOSE_OLD_PRICES  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.CLOSE_OLD_PRICES (DATE_PRICE DATE,CAT_CEN NUMBER,PROD_ID VARCHAR2) IS
BEGIN
  UPDATE npr_prices SET
    END_DATE=LAST_DAY(BEGIN_DATE)
	WHERE 
	  END_DATE is NULL AND 
	  BEGIN_DATE<TRUNC(date_price) AND
	  PROD_ID_NPR=prod_id AND
	  CAT_CEN_ID=cat_cen;
  COMMIT;
END CLOSE_OLD_PRICES;

/

