--
-- P_GU12_BACKOTKAZ  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.P_GU12_BACKOTKAZ (IDREIS INTEGER
                                          ,OLDID INTEGER) IS
NEW_SUMKOL NUMBER;
NEW_SUMVES NUMBER;

BEGIN

NEW_SUMKOL:=0;
NEW_SUMVES:=0;

FOR rec IN (SELECT * FROM GU12_B WHERE ID=IDREIS)
LOOP

   NEW_SUMKOL:=rec.KOL_VAG;
   NEW_SUMVES:=rec.VES;

END LOOP;

  UPDATE GU12_B SET KOL_VAG=KOL_VAG+NEW_SUMKOL,VES=VES+NEW_SUMVES
  WHERE ID=OLDID;

  UPDATE GU12_BR SET ID_B=OLDID WHERE ID_B=IDREIS;
  
  DELETE FROM GU12_B WHERE ID=IDREIS;
  
COMMIT;

END P_GU12_BACKOTKAZ;

/

