--
-- P_LOAD_SF_R3_FILLNOMSF_TEST  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.P_LOAD_SF_R3_FILLNOMSF_TEST (vDATE DATE,vFIRSTNUM NUMBER) IS
SFNUM NUMBER;
BEGIN

	SFNUM:=vFIRSTNUM;

	IF vFIRSTNUM>0 THEN
	  FOR LCUR IN (SELECT NOM_DOK FROM BILLS_TMP K
				          WHERE K.DATE_KVIT=vDATE
				          AND ISU_NOM_SF||' '<>' '
				          AND NOM_SF=0
			       )
	   LOOP

				UPDATE BILLS_TMP SET NOM_SF=SFNUM WHERE NOM_DOK=LCUR.NOM_DOK;

				SFNUM:=SFNUM+1;

	  END LOOP;

	  -- заполнение KVIT_NOMSF
	  DELETE FROM KVIT_NOMSF
	  WHERE KVIT_ID IN (SELECT ID FROM KVIT_TMP WHERE DATE_KVIT=vDATE);

	  INSERT INTO KVIT_NOMSF
	  SELECT DISTINCT K.ID AS KVIT_ID,B.NOM_SF
      FROM KVIT_TMP K,BILLS_TMP B
      WHERE K.DATE_KVIT=vDATE
      AND K.BILL_ID=B.NOM_DOK
      AND K.BILL_ID<>0;

	END IF;

	COMMIT;

END P_LOAD_SF_R3_FILLNOMSF_TEST;

/

