--
-- P_LOAD_SF_R3_FILLNOMSF  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.P_LOAD_SF_R3_FILLNOMSF (vDATE DATE,vFIRSTNUM NUMBER) IS
SFNUM NUMBER;
BEGIN
	
	SFNUM:=vFIRSTNUM;
	 
	IF vFIRSTNUM>0 THEN
	  FOR LCUR IN (SELECT NOM_DOK,DOG_ID FROM BILLS K 
				          WHERE K.DATE_KVIT=vDATE
				          AND ISU_NOM_SF||' '<>' '
				          AND NOM_SF=0	
			       ) 
	   LOOP
		
				UPDATE BILLS SET NOM_SF=SFNUM WHERE NOM_DOK=LCUR.NOM_DOK;
    			
				--ÕŒÃ≈– ¿ “¿
				IF LCUR.DOG_ID=2519 THEN
				   UPDATE KVIT SET NUM_AKT=SFNUM WHERE BILL_ID=LCUR.NOM_DOK; 
				   UPDATE BILL_POS SET NUM_AKT=SFNUM WHERE NOM_DOK=LCUR.NOM_DOK AND BILL_POS_ID<10;
				END IF;
				    		
				SFNUM:=SFNUM+1;

	  END LOOP;		
	  
	  -- Á‡ÔÓÎÌÂÌËÂ KVIT_NOMSF
	  DELETE FROM KVIT_NOMSF
	  WHERE KVIT_ID IN (SELECT ID FROM KVIT WHERE DATE_KVIT=vDATE);

	  INSERT INTO KVIT_NOMSF 
	  SELECT DISTINCT K.ID AS KVIT_ID,B.NOM_SF
      FROM KVIT K,BILLS B
      WHERE K.DATE_KVIT=vDATE
      AND K.BILL_ID=B.NOM_DOK
      AND K.BILL_ID<>0;
      	
	END IF;

	
	
	COMMIT;

END P_LOAD_SF_R3_FILLNOMSF;

/

