--
-- RENEW_KLS_VALPASP  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.RENEW_KLS_VALPASP (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

 UPDATE KLS_VALPASP
    set (QUAL,DATEUPLOAD) =
	    (SELECT A.QUAL,a.DATEUPLOAD FROM load_buffer.VALPASP A
		  WHERE A.KOD=KLS_VALPASP.PASP_ID AND
		        A.KODIF_ID=KLS_VALPASP.KODIF_ID)
  where exists (SELECT * FROM load_buffer.VALPASP
                 where load_buffer.VALPASP.KOD=KLS_VALPASP.PASP_ID AND
				       load_buffer.VALPASP.KODIF_ID=KLS_VALPASP.KODIF_ID);

  COMMIT;

  INSERT INTO KLS_VALPASP (PASP_ID,KODIF_ID,QUAL,DATEUPLOAD)
    (SELECT C.KOD,C.KODIF_ID,C.QUAL,C.DATEUPLOAD FROM load_buffer.VALPASP C
      WHERE not exists (SELECT * FROM KLS_VALPASP
                 WHERE C.KOD=KLS_VALPASP.PASP_ID AND
				       C.KODIF_ID=KLS_VALPASP.KODIF_ID));

  COMMIT;

  DELETE FROM KLS_VALPASP WHERE NOT EXISTS (SELECT * from load_buffer.VALPASP E WHERE E.KOD = KLS_VALPASP.PASP_ID AND E.KODIF_ID=KLS_VALPASP.KODIF_ID) AND
     KLS_VALPASP.DATEUPLOAD BETWEEN date_beg AND date_end;

  COMMIT;
END RENEW_KLS_VALPASP;

/

