--
-- RENEW_VOZVRAT  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_vozvrat (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
  date_inc DATE;
BEGIN

UPDATE load_buffer.VOZVRAT SET time_e='00:00' WHERE SUBSTR(time_e,1,1)=' ' OR time_e IS NULL;
UPDATE load_buffer.VOZVRAT SET date_e=date_nakl WHERE date_e IS NULL;

UPDATE /*+ RULE */ MASTER.VOZVRAT A SET
  (DATE_KVIT, NUM_NAKL, DATE_NAKL, DATE_VOZ, TIME_VOZ, DATE_RASK, TARIF, SUMMA, NUM_AKT, NUM_PERECH, DAT_PERECH, VOZVRAT, FLG_KVIT, 
   OLD_KVIT, SF_POROJN, DAT_POROJN, SOBST, PRSTBETW1, PRSTBETT1, PRSTBETW2, PRSTBETT2, PRSTBETSF, STAN_ID, PRST_N_AKT, 
   PRST_S_AKT, PRIM, DATE_OTP, TIME_OTP, OTSTOI, DATE_REP, DATE_EDIT, KVIT_ID)
 = (SELECT k.DATE_KVIT, v.NUM_NAKL, v.DATE_NAKL, v.DATE_VOZ, v.TIME_VOZ, v.DATE_RASK, v.TARIF, v.SUMMA, v.NUM_AKT, v.NUM_PERECH, 
           v.DAT_PERECH, v.VOZVRAT, v.FLG_KVIT, v.OLD_KVIT, v.SF_POROJN, v.DAT_POROJN, v.SOBST, v.PRSTBETW1, v.PRSTBETT1, 
		   v.PRSTBETW2, v.PRSTBETT2, v.PRSTBETSF, s.ID, v.PRST_N_AKT, v.PRST_S_AKT, v.PROD_NAME, v.DATE_OTP, v.TIME_OTP, 
		   v.OTSTOI, v.DATE_REP, TO_DATE(TO_CHAR(v.DATE_E,'dd.mm.yyyy ') || SUBSTR(v.TIME_E,1,5),'dd.mm.yyyy hh24:mi'),k.ID
      FROM load_buffer.VOZVRAT v, (select * from master.KVIT where date_kvit>=to_date('01.11.2007','dd.mm.yyyy')) k, master.KLS_STAN s 
		  WHERE v.NUM_CIST=a.NUM_CIST
		    AND v.NUM_KVIT=a.NUM_KVIT
			AND v.NUM_CIST=k.NUM_CIST(+)
		    AND v.NUM_KVIT=k.NUM_KVIT(+)
			AND v.KST=s.STAN_KOD(+))
  WHERE EXISTS 
   (SELECT NULL
      FROM load_buffer.VOZVRAT v 
		  WHERE v.NUM_CIST=a.NUM_CIST
		    AND v.NUM_KVIT=a.NUM_KVIT)
AND a.DATE_EDIT>=DATE_BEG 
AND a.DATE_EDIT<DATE_END+1;

INSERT INTO MASTER.VOZVRAT
   (NUM_CIST,NUM_KVIT,DATE_KVIT,NUM_NAKL, DATE_NAKL, DATE_VOZ, TIME_VOZ, DATE_RASK, TARIF, SUMMA, NUM_AKT, NUM_PERECH, 
    DAT_PERECH, VOZVRAT, FLG_KVIT, OLD_KVIT, SF_POROJN, DAT_POROJN, SOBST, PRSTBETW1, PRSTBETT1, PRSTBETW2, PRSTBETT2, 
	PRSTBETSF, STAN_ID, PRST_N_AKT, PRST_S_AKT, PRIM, DATE_OTP, TIME_OTP, OTSTOI, DATE_REP, DATE_EDIT, KVIT_ID)
 (SELECT /*+ ORDERED */ v.NUM_CIST,v.NUM_KVIT,k.DATE_KVIT, v.NUM_NAKL, v.DATE_NAKL, v.DATE_VOZ, v.TIME_VOZ, v.DATE_RASK, 
          v.TARIF, v.SUMMA, v.NUM_AKT, v.NUM_PERECH, v.DAT_PERECH, v.VOZVRAT, v.FLG_KVIT, v.OLD_KVIT, v.SF_POROJN, 
		  v.DAT_POROJN, v.SOBST, v.PRSTBETW1, v.PRSTBETT1, v.PRSTBETW2, v.PRSTBETT2, v.PRSTBETSF, s.ID, v.PRST_N_AKT, 
		  v.PRST_S_AKT, v.PROD_NAME, v.DATE_OTP, v.TIME_OTP, v.OTSTOI, v.DATE_REP,
		  TO_DATE(TO_CHAR(v.DATE_E,'dd.mm.yyyy ') || SUBSTR(v.TIME_E,1,5),'dd.mm.yyyy hh24:mi'),k.ID
    FROM load_buffer.VOZVRAT v, (select * from master.KVIT where date_kvit>=to_date('01.11.2007','dd.mm.yyyy')) k, master.KLS_STAN s 
   WHERE v.KST=s.STAN_KOD(+)
 	 AND v.NUM_CIST=k.NUM_CIST(+)
	 AND v.NUM_KVIT=k.NUM_KVIT(+)
	 AND v.NUM_CIST IS NOT NULL AND v.NUM_CIST<>'0'
     AND NOT EXISTS (SELECT NULL FROM MASTER.VOZVRAT A 
                      WHERE A.NUM_CIST=v.NUM_CIST
					    AND A.NUM_KVIT=v.NUM_KVIT));
						
/*DELETE FROM MASTER.VOZVRAT A WHERE 
    NOT EXISTS (SELECT NULL FROM load_buffer.VOZVRAT k WHERE k.NUM_CIST=A.NUM_CIST AND k.NUM_KVIT=A.NUM_KVIT) AND
    AND a.DATE_EDIT>=DATE_BEG 
    AND a.DATE_EDIT<DATE_END+1;*/

COMMIT;

END Renew_vozvrat; 
/

