--
-- RENEW_RAZNAR  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Raznar (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE MASTER.RAZNAR M_R
    SET (DATE_RAZN, DATE_SEND, TIME_SEND, USER_SEND, MESTO_ID, FLAG_SEND, 
	     TONN_RAZNAR, CIST_RAZNAR) = 
	   (SELECT DATE_RAZN, DATA_S, VREMA_S, USERNAME, MESTO, Iif(PERED,1,0), TONN, KOL_CIST
          FROM load_buffer.RAZNAR L_R
		 WHERE L_R.nom_zd=M_R.nom_zd 
		   AND L_R.ID = M_R.ID)
    WHERE EXISTS 
	   (SELECT NULL
          FROM load_buffer.RAZNAR L_R
		 WHERE L_R.nom_zd=M_R.nom_zd 
		   AND L_R.ID = M_R.ID);
  COMMIT;

  INSERT INTO MASTER.RAZNAR
        (ID,nom_zd,DATE_RAZN, DATE_SEND, TIME_SEND, USER_SEND, MESTO_ID, FLAG_SEND, 
	     TONN_RAZNAR, CIST_RAZNAR)
	   (SELECT ID,NOM_ZD,DATE_RAZN, DATA_S, VREMA_S, USERNAME, MESTO, Iif(PERED,1,0), TONN, KOL_CIST
          FROM load_buffer.RAZNAR L_R
		 WHERE NOT EXISTS (SELECT NULL FROM MASTER.RAZNAR M_R WHERE M_R.ID=L_R.ID AND M_R.nom_zd=L_R.nom_zd));
   COMMIT;

  DELETE FROM MASTER.RAZNAR M_R WHERE NOT EXISTS (SELECT NULL FROM load_buffer.RAZNAR L_R WHERE L_R.NOM_ZD = M_R.NOM_ZD AND L_R.ID=M_R.ID) 
    AND M_R.date_razn BETWEEN date_beg AND date_end;

  COMMIT;

END Renew_RAZNAR;

/

