--
-- RENEW_MONTH_ALFA  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_MONTH_ALFA (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH_ALFA') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE MASTER.MONTH_ALFA M_M
    SET (XCONFIRM, DATE_PLAN, KOL_NET, MON_DOB, MON_DELIV, 
	     N_MAR_POR, N_MAR_DATE, PRODUCER_ID, PRODUCER_NAME, ROUT_NAME, 
		 CONTRACT, CONTRACT_DATE, BUYER_ID, BUYER_NAME, EXPED_ID, EXPED_NAME, 
		 GROTP_ID, GROTP_NAME, POLUCH_ID, POLUCH_NAME, 
		 INCOTERMS_RUS_ID, INCOTERMS_RUS_NAME, STAN_ID, STAN_NAME, STAN_KOD, STATUS
		 )
	 = (SELECT XCONFIRM, M_Y, QUANTITY, MON_D, MON_DELIV, 
	     TELEGA, T_DATE, RES_ID, JL, ROUT_NAME, 
		 CONTRACT, DATA, BUYER_ID, BUYER, EXPEDITOR, EXPED_NAME, 
		 OTPRAV, OTPR_NAME, POLU, POLU_NAME, 
		 INCO, TERMS_RUS, STAN, POINT_NAME, UUN, ORD_STATUS
          FROM load_buffer.ALFAMON L_M 
		 WHERE L_M.con_id=M_M.con_id)
    WHERE EXISTS (SELECT NULL
          FROM load_buffer.ALFAMON L_M
		 WHERE L_M.con_id=M_M.con_id);

  INSERT INTO MASTER.MONTH_ALFA
        (CON_ID, XCONFIRM, DATE_PLAN, KOL_NET, MON_DOB, MON_DELIV, 
	     N_MAR_POR, N_MAR_DATE, PRODUCER_ID, PRODUCER_NAME, ROUT_NAME, 
		 CONTRACT, CONTRACT_DATE, BUYER_ID, BUYER_NAME, EXPED_ID, EXPED_NAME, 
		 GROTP_ID, GROTP_NAME, POLUCH_ID, POLUCH_NAME, 
		 INCOTERMS_RUS_ID, INCOTERMS_RUS_NAME, STAN_ID, STAN_NAME, STAN_KOD, STATUS)
	 (SELECT CON_ID, XCONFIRM, M_Y, QUANTITY, MON_D, MON_DELIV, 
	     TELEGA, T_DATE, RES_ID, JL, ROUT_NAME, 
		 CONTRACT, DATA, BUYER_ID, BUYER, EXPEDITOR, EXPED_NAME, 
		 OTPRAV, OTPR_NAME, POLU, POLU_NAME, 
		 INCO, TERMS_RUS, STAN, POINT_NAME, UUN, ORD_STATUS
          FROM load_buffer.ALFAMON L_M 
		 WHERE NOT EXISTS (SELECT NULL FROM MASTER.MONTH_ALFA M_M WHERE M_M.con_id=L_M.con_id));

  DELETE FROM MASTER.MONTH_ALFA M_M 
   WHERE NOT EXISTS (SELECT NULL FROM load_buffer.ALFAMON L_M WHERE L_M.con_id = M_M.con_id) 
    AND M_M.date_plan BETWEEN date_beg AND date_end;

  COMMIT;

END Renew_MONTH_ALFA;

/

