--
-- RENEW_KLS_GDOR  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.RENEW_KLS_GDOR(DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE KLS_GDOR
    SET (GDOR_NAME, SHORT_NAME) = (SELECT A.NAIM, A.S_NAIM FROM load_buffer.gdor A WHERE A.KOD=KLS_GDOR.ID)
                     WHERE EXISTS (SELECT B.KOD            FROM load_buffer.gdor B WHERE B.KOD=KLS_GDOR.ID);

  INSERT INTO kls_gdor (ID, GDOR_NAME, SHORT_NAME) (SELECT C.KOD, C.NAIM, C.S_NAIM FROM load_buffer.GDOR C
      WHERE NOT EXISTS (SELECT D.ID FROM kls_gdor D WHERE D.ID=C.KOD));

  COMMIT;

END RENEW_KLS_GDOR;

/

