--
-- RENEW_REAL_OPL_KTU  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_real_opl_ktu (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
  date_inc DATE;
BEGIN
return;

UPDATE master.real_opl_ktu SET
  (D_41POK,VID_OPL,NDC_TR20,NDC_NAL03,CPEC_PROD,KR,UN_DOK,D_67,NDC_TR03,D_67POK,SUMMA_DOK1,CORR_DATE,
   N_SCHET,CN_PPZT,D_443,VES,DATASCHF,UBIT,USL_PPZT,NDC_NAL20,NDC_PPZT,ID_UB,D_191POK,DOG_REALP,
   D_442,SUM_AKCIZ,CPEC_TARIF,D_191,D_41,AVANS,DATA_POST,SUM_NACEN,SUM_NALIV,KOD_NFP,KOD_KR,
   OST_SUM,NDC_VN20,CLOSE_DATE,DATA_BUXG,NDC_VN03,CENA_NFP,CENA_POK,TAX_SALE,KOD_REALP,D_194,D_441,NOM_SF)
 = (SELECT D_41POK,VID_OPL,NDC_TR20,NDC_NAL03,CPEC_PROD,KR,UN_DOK,D_67,NDC_TR03,D_67POK,SUMMA_DOK1,CORR_DATE,
           N_SCHET,CN_PPZT,D_443,VES,DATASCHF,UBIT,USL_PPZT,NDC_NAL20,NDC_PPZT,ID_UB,D_191POK,DOG_REALP,
           D_442,SUM_AKCIZ,CPEC_TARIF,D_191,D_41,AVANS,DATA_POST,SUM_NACEN,SUM_NALIV,KOD_NFP,KOD_KR,
           OST_SUM,NDC_VN20,CLOSE_DATE,DATA_BUXG,NDC_VN03,CENA_NFP,CENA_POK,TAX_SALE,KOD_REALP,D_194,D_441,NOM_SF
      FROM load_buffer.real_opl_ktu
	 WHERE real_opl_ktu.NOM_DOK=master.real_opl_ktu.NOM_DOK AND real_opl_ktu.SOBSTV=master.real_opl_ktu.SOBSTV AND real_opl_ktu.ID=master.real_opl_ktu.ID)
WHERE EXISTS (SELECT real_opl_ktu.NOM_DOK FROM load_buffer.real_opl_ktu WHERE real_opl_ktu.NOM_DOK=master.real_opl_ktu.NOM_DOK AND real_opl_ktu.SOBSTV=master.real_opl_ktu.SOBSTV AND real_opl_ktu.ID=master.real_opl_ktu.ID);

COMMIT;


INSERT INTO master.real_opl_ktu
     (NOM_DOK,SOBSTV,ID,D_41POK,VID_OPL,NDC_TR20,NDC_NAL03,CPEC_PROD,KR,UN_DOK,D_67,NDC_TR03,D_67POK,SUMMA_DOK1,CORR_DATE,
      N_SCHET,CN_PPZT,D_443,VES,DATASCHF,UBIT,USL_PPZT,NDC_NAL20,NDC_PPZT,ID_UB,D_191POK,DOG_REALP,
      D_442,SUM_AKCIZ,CPEC_TARIF,D_191,D_41,AVANS,DATA_POST,SUM_NACEN,SUM_NALIV,KOD_NFP,KOD_KR,
      OST_SUM,NDC_VN20,CLOSE_DATE,DATA_BUXG,NDC_VN03,CENA_NFP,CENA_POK,TAX_SALE,KOD_REALP,D_194,D_441,NOM_SF)
     (SELECT NOM_DOK,SOBSTV,ID,D_41POK,VID_OPL,NDC_TR20,NDC_NAL03,CPEC_PROD,KR,UN_DOK,D_67,NDC_TR03,D_67POK,SUMMA_DOK1,CORR_DATE,
             N_SCHET,CN_PPZT,D_443,VES,DATASCHF,UBIT,USL_PPZT,NDC_NAL20,NDC_PPZT,ID_UB,D_191POK,DOG_REALP,
             D_442,SUM_AKCIZ,CPEC_TARIF,D_191,D_41,AVANS,DATA_POST,SUM_NACEN,SUM_NALIV,KOD_NFP,KOD_KR,
             OST_SUM,NDC_VN20,CLOSE_DATE,DATA_BUXG,NDC_VN03,CENA_NFP,CENA_POK,TAX_SALE,KOD_REALP,D_194,D_441,NOM_SF
        FROM load_buffer.real_opl_ktu
       WHERE NOT EXISTS (SELECT master.real_opl_ktu.NOM_DOK FROM master.real_opl_ktu WHERE master.real_opl_ktu.NOM_DOK=load_buffer.real_opl_ktu.NOM_DOK
             AND master.real_opl_ktu.SOBSTV=load_buffer.real_opl_ktu.SOBSTV AND master.real_opl_ktu.ID=load_buffer.real_opl_ktu.ID));

COMMIT;

DELETE FROM master.real_opl_ktu A WHERE
    NOT EXISTS (SELECT k.NOM_DOK FROM load_buffer.real_opl_ktu k WHERE k.NOM_DOK = A.NOM_DOK AND k.SOBSTV = A.SOBSTV AND k.ID = A.ID) ;

COMMIT;

END Renew_real_opl_ktu;
/

