--
-- RENEW_KLS_GTD  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.RENEW_KLS_GTD (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE kls_gtd
    SET (DATE_GTD,N_NP,T_GTD,PRED_DEC,KVED,KOLG,STOF,STOS,STOT,V_10,V_11,V_25,V_26,KURS,DVYP,
         TAMG,KNMT,OTVL,NAGN,DKTS,S_GR) =
   (SELECT A.DATE_GTD,A.N_NP,A.T_GTD,A.PRED_DEC,A.KVED,A.KOLG,A.STOF,A.STOS,A.STOT,A.V_10,A.V_11,
           A.V_25,A.V_26,A.KURS,A.DVYP,A.TAMG,A.KNMT,A.OTVL,A.NAGN,A.DKTS,A.S_GR FROM load_buffer.gtd_all A WHERE A.nomdec=kls_gtd.gtd)
    WHERE EXISTS (SELECT * FROM load_buffer.gtd_all B WHERE B.nomdec=kls_gtd.gtd);

  INSERT INTO kls_gtd (GTD,DATE_GTD,N_NP,T_GTD,PRED_DEC,KVED,KOLG,STOF,STOS,STOT,V_10,V_11,V_25,V_26,KURS,DVYP,
         TAMG,KNMT,OTVL,NAGN,DKTS,S_GR)
   (SELECT C.NOMDEC,C.DATE_GTD,C.N_NP,C.T_GTD,C.PRED_DEC,C.KVED,C.KOLG,C.STOF,C.STOS,C.STOT,C.V_10,C.V_11,
           C.V_25,C.V_26,C.KURS,C.DVYP,C.TAMG,C.KNMT,C.OTVL,C.NAGN,C.DKTS,C.S_GR FROM load_buffer.gtd_all C
    WHERE not exists (SELECT * FROM kls_gtd WHERE kls_gtd.gtd=C.NOMDEC));

  INSERT INTO kls_gtd (GTD)
   (SELECT DISTINCT '00000/000000/0000000' FROM load_buffer.gtd_all
     WHERE not exists (SELECT * FROM kls_gtd WHERE kls_gtd.gtd='00000/000000/0000000'));

  COMMIT;
END RENEW_KLS_GTD;

/

