--
-- RENEW_GD_PLAN  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Gd_Plan (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
  vTipPlan VARCHAR2(50);
BEGIN

  IF param1 || ' ' =' ' OR (NLS_UPPER(param1)<>'DAY' AND NLS_UPPER(param1)<>'MON') THEN
    RETURN;
  ELSE
    vTipPlan:=NLS_UPPER(param1);
  END IF;

  -- Обновление плана  	 
  UPDATE GD_PLAN C
    SET (FROM_DATE, TO_DATE, PLAN_CIST, PLAN_VES, KORR_CIST, KORR_VES, MARSHRUT_CIST, STANOTP_ID)
 	 = (SELECT A.FROM_DATE, A.TO_DATE, 
			   A.PLAN_CIST,A.PLAN_VES, A.KORR_CIST, A.KORR_VES, A.MARSHRUTED,A.STANOTP_ID  
 		FROM load_buffer.V_GD_PLAN A
		WHERE A.KOD_PREDPR=C.GROTP_ID
		  AND A.DATE_PLAN=C.DATE_PLAN
		  AND A.TIP_OTGR=C.LOAD_TYPE_ID
		  AND A.KOD_NPR=C.PROD_ID_NPR
		  AND A.EXPORT=C.NAPR_MOS_ID
		  AND A.VAGOWNER_ID=C.VAGOWNER_ID)
	WHERE C.TIP_PLAN=vTipPlan
	  AND EXISTS (SELECT NULL 
  		    FROM load_buffer.V_GD_PLAN A
		   WHERE A.KOD_PREDPR=C.GROTP_ID
		     AND A.DATE_PLAN=C.DATE_PLAN
		     AND A.TIP_OTGR=C.LOAD_TYPE_ID
		     AND A.KOD_NPR=C.PROD_ID_NPR
		     AND A.EXPORT=C.NAPR_MOS_ID
  	  	     AND A.VAGOWNER_ID=C.VAGOWNER_ID);

  COMMIT;
 
  -- Добавление плана  
  INSERT INTO GD_PLAN (TIP_PLAN, DATE_PLAN, FROM_DATE, TO_DATE, PLAN_CIST, PLAN_VES, KORR_CIST, KORR_VES, MARSHRUT_CIST, 
        GROTP_ID, NAPR_MOS_ID, PROD_ID_NPR, LOAD_TYPE_ID, VAGOWNER_ID, STANOTP_ID)
   (SELECT vTipPlan, A.DATE_PLAN, A.FROM_DATE, A.TO_DATE,
		   A.PLAN_CIST,A.PLAN_VES, A.KORR_CIST, A.KORR_VES, A.MARSHRUTED,
		   A.KOD_PREDPR, A.EXPORT, A.KOD_NPR, A.TIP_OTGR, A.VAGOWNER_ID, A.STANOTP_ID 
		FROM load_buffer.V_GD_PLAN A
		WHERE NOT EXISTS 
		    (SELECT NULL 
			 FROM GD_PLAN C 
			 WHERE C.TIP_PLAN=vTipPlan
			   AND VAGOWNER_ID=A.VAGOWNER_ID
			   AND C.DATE_PLAN=A.DATE_PLAN
			   AND C.GROTP_ID=A.KOD_PREDPR
			   AND C.LOAD_TYPE_ID=A.TIP_OTGR
			   AND C.PROD_ID_NPR=A.KOD_NPR
			   AND C.NAPR_MOS_ID=A.EXPORT));

  COMMIT;
  
  -- Удаление плана  
  DELETE FROM GD_PLAN C
    WHERE C.TIP_PLAN=vTipPlan
	  AND C.DATE_PLAN BETWEEN DATE_BEG AND DATE_END
--      AND C.APPL_TAG<>'MASTER'
	  AND NOT EXISTS (SELECT NULL 
		FROM load_buffer.v_gd_plan A
		WHERE A.KOD_PREDPR=C.GROTP_ID
		  AND A.DATE_PLAN=C.DATE_PLAN
		  AND A.TIP_OTGR=C.LOAD_TYPE_ID
		  AND A.KOD_NPR=C.PROD_ID_NPR
		  AND A.EXPORT=C.NAPR_MOS_ID
		  AND A.VAGOWNER_ID=C.VAGOWNER_ID);
		  
  COMMIT;

END Renew_Gd_Plan;

/

