--
-- RENEW_KLS_PROD_KONS  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Kls_Prod_Kons (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE KLS_PROD_KONS
    SET (NAME, PROD_KONS_ID, UPAK_ID, DOP_ID, FLAG_FAS, KOEF_KG, KOEF_LIT, GR_KONS_ID, TIP_AKCIZ_ID, P_YEAR)
	  = (SELECT PROD_NAME, PROD_COMP_, PROD_UPAK, DOP_KOD, PROD_UCHET, K_KG, K_LIT, PROD_KOD, DECODE(T_AKC,6,1,7,2,8,3,9,4,10,1,11,2,12,3,13,4,T_AKC),P_YEAR
  	     FROM load_buffer.produkts A WHERE A.kod=KLS_PROD_KONS.ID)
    WHERE EXISTS (SELECT NULL FROM load_buffer.produkts A WHERE A.kod=KLS_PROD_KONS.ID);

  INSERT INTO KLS_PROD_KONS (ID,NAME, PROD_KONS_ID, UPAK_ID, DOP_ID, FLAG_FAS, KOEF_KG, KOEF_LIT, GR_KONS_ID, TIP_AKCIZ_ID, P_YEAR)
	(SELECT kod,PROD_NAME, PROD_COMP_, PROD_UPAK, DOP_KOD, PROD_UCHET, K_KG, K_LIT, PROD_KOD, DECODE(T_AKC,6,1,7,2,8,3,9,4,10,1,11,2,12,3,13,4,T_AKC),P_YEAR
  	   FROM load_buffer.produkts A
      WHERE NOT EXISTS (SELECT NULL FROM KLS_PROD_KONS C WHERE C.ID=A.kod));

		  
  -- Привяжем фасованные масла
  UPDATE KLS_PROD_KONS C SET PROD_ID_NPR='80018'
  WHERE IS_AUTO_LINK=1 AND GR_KONS_ID='0253000000' and FLAG_FAS=1;
  
  UPDATE KLS_PROD_KONS_GROUPS_DESC C SET PROD_GROUPS_ID=176
  WHERE IS_AUTO_LINK=1 AND EXISTS
	(SELECT NULL
  	   FROM KLS_PROD_KONS A
      WHERE a.GR_KONS_ID='0253000000' and a.FLAG_FAS=1 and C.PROD_KONS_ID=A.ID);
  	   
  INSERT INTO KLS_PROD_KONS_GROUPS_DESC (PROD_KONS_ID, PROD_GROUPS_ID)
	(SELECT ID,176
  	   FROM KLS_PROD_KONS A
      WHERE a.GR_KONS_ID='0253000000' and a.FLAG_FAS=1
	    AND NOT EXISTS (SELECT NULL FROM KLS_PROD_KONS_GROUPS_DESC C WHERE C.PROD_KONS_ID=A.ID));
  	  
  -- Привяжем НЕ фасованные масла	   
/*  UPDATE KLS_PROD_KONS C SET PROD_ID_NPR='11900'
  WHERE IS_AUTO_LINK=1 AND GR_KONS_ID='0253000000' and FLAG_FAS=0;

  UPDATE KLS_PROD_KONS_GROUPS_DESC C SET PROD_GROUPS_ID=178
  WHERE IS_AUTO_LINK=1 AND EXISTS
	(SELECT NULL
  	   FROM KLS_PROD_KONS A
      WHERE a.GR_KONS_ID='0253000000' and a.FLAG_FAS=0 and C.PROD_KONS_ID=A.ID);

  INSERT INTO KLS_PROD_KONS_GROUPS_DESC (PROD_KONS_ID, PROD_GROUPS_ID)
	(SELECT ID,178
  	   FROM KLS_PROD_KONS A
      WHERE a.GR_KONS_ID='0253000000' and a.FLAG_FAS=0
	    AND NOT EXISTS (SELECT NULL FROM KLS_PROD_KONS_GROUPS_DESC C WHERE C.PROD_KONS_ID=A.ID));*/

  -- Привяжем ТТХ	   
  UPDATE KLS_PROD_KONS C SET PROD_ID_NPR='80020'
   WHERE IS_AUTO_LINK=1 AND GR_KONS_ID='2380000000';

  UPDATE KLS_PROD_KONS_GROUPS_DESC C SET PROD_GROUPS_ID=161
  WHERE IS_AUTO_LINK=1 AND EXISTS
	(SELECT NULL
  	   FROM KLS_PROD_KONS A
      WHERE a.GR_KONS_ID='2380000000' and C.PROD_KONS_ID=A.ID);

  INSERT INTO KLS_PROD_KONS_GROUPS_DESC (PROD_KONS_ID, PROD_GROUPS_ID)
	(SELECT ID,161
  	   FROM KLS_PROD_KONS A
      WHERE a.GR_KONS_ID='2380000000' 
	    AND NOT EXISTS (SELECT NULL FROM KLS_PROD_KONS_GROUPS_DESC C WHERE C.PROD_KONS_ID=A.ID));

  -- Привяжем Прочие продукты фасованные	   
  UPDATE KLS_PROD_KONS C SET PROD_ID_NPR='80019'
  WHERE IS_AUTO_LINK=1 AND GR_KONS_ID='0299910000' and FLAG_FAS=1;
  
  UPDATE KLS_PROD_KONS_GROUPS_DESC C SET PROD_GROUPS_ID=279
  WHERE IS_AUTO_LINK=1 AND EXISTS
	(SELECT NULL
  	   FROM KLS_PROD_KONS A
      WHERE a.GR_KONS_ID='0299910000' and a.FLAG_FAS=1 and C.PROD_KONS_ID=A.ID);

  INSERT INTO KLS_PROD_KONS_GROUPS_DESC (PROD_KONS_ID, PROD_GROUPS_ID)
	(SELECT ID,279
  	   FROM KLS_PROD_KONS A
      WHERE a.GR_KONS_ID='0299910000' and a.FLAG_FAS=1 
	    AND NOT EXISTS (SELECT NULL FROM KLS_PROD_KONS_GROUPS_DESC C WHERE C.PROD_KONS_ID=A.ID));
	  
  COMMIT;
  	   
END Renew_Kls_Prod_Kons;
/

