--
-- RENEW_KLS_LOAD_TYPE_MOS  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Kls_Load_Type_mos (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

 UPDATE KLS_LOAD_TYPE_MOS
    SET (NAME) =
	    (SELECT TRANSPORT_NAME FROM load_buffer.trans_transport A WHERE A.transport=KLS_LOAD_TYPE_MOS.ID)
  WHERE EXISTS (SELECT NULL FROM load_buffer.trans_transport A WHERE A.transport=KLS_LOAD_TYPE_MOS.ID);

  INSERT INTO KLS_LOAD_TYPE_MOS (ID,NAME)
    (SELECT TRANSPORT,TRANSPORT_NAME FROM load_buffer.trans_transport A
      WHERE NOT EXISTS (SELECT NULL FROM KLS_LOAD_TYPE_MOS WHERE KLS_LOAD_TYPE_MOS.ID=A.transport));

  COMMIT;

END Renew_Kls_Load_Type_mos;

/

