--
-- RENEW_KLS_PERTYPE  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.RENEW_KLS_PERTYPE(DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') AS
BEGIN

  UPDATE KLS_PERTYPE
    SET (PERTYPE_NAME, BOSS) = (SELECT A.NAME,A.BOSS FROM load_buffer.PERTYPE A WHERE A.ID=KLS_PERTYPE.ID)
                 WHERE EXISTS (SELECT C.ID   FROM load_buffer.PERTYPE C WHERE C.ID=KLS_PERTYPE.ID AND KLS_PERTYPE.ID<>10);

  UPDATE KLS_PERTYPE
    SET (PERTYPE_NAME) = (SELECT A.NAME FROM load_buffer.PERTYPE A WHERE A.ID=KLS_PERTYPE.ID)
                 WHERE EXISTS (SELECT C.ID   FROM load_buffer.PERTYPE C WHERE C.ID=KLS_PERTYPE.ID AND KLS_PERTYPE.ID=10);

  INSERT INTO KLS_PERTYPE (ID,PERTYPE_NAME,BOSS) (SELECT D.ID, D.NAME, D.BOSS FROM load_buffer.PERTYPE D
          WHERE NOT EXISTS (SELECT E.ID FROM KLS_PERTYPE E WHERE E.ID=D.ID) AND D.ID<>10);

  INSERT INTO KLS_PERTYPE (ID,PERTYPE_NAME) (SELECT D.ID, D.NAME FROM load_buffer.PERTYPE D
          WHERE NOT EXISTS (SELECT E.ID FROM KLS_PERTYPE E WHERE E.ID=D.ID) AND D.ID=10);

  COMMIT;

END RENEW_KLS_PERTYPE;

/

