--
-- RENEW_GP_NAPR  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_gp_napr (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE KLS_GP_NAPR A
    SET (NAME, GOSPROG_ID,KSSS_ID) = 
	(SELECT NAIM, PROGRAM, kSSS FROM load_buffer.gp_napr B WHERE B.KOD_POLUCH=A.ID)
    WHERE EXISTS (SELECT NULL FROM load_buffer.gp_napr B WHERE B.KOD_POLUCH=A.ID);

  INSERT INTO KLS_GP_NAPR (ID,NAME,gosprog_id,ksss_id)
   (SELECT KOD_POLUCH,naim,program,ksss FROM load_buffer.gp_napr B
    WHERE NOT EXISTS (SELECT NULL FROM KLS_GP_NAPR A WHERE A.ID=B.KOD_POLUCH));

  COMMIT;

END Renew_gp_napr;

/

