--
-- RENEW_SPECIF  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Specif (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE MASTER.SPECIF M_S
    SET (DOG_ID, PROD_ID_NPR, LOAD_ABBR, STANOTP_ID, STAN_ID, VETKA_ID, POLUCH_ID, POTREB_ID, 
	     PRIM, GR4, BEGIN_DATE, END_DATE, M1, M2, M3, M4, M5, M6, M7, M8, M9, M10, M11, M12, 
		 KV1, KV2, KV3, KV4, VES_ALL, UPDATE_DATE, MONTH_ALL_ID)
	 = (SELECT D.ID, L_S.kod_npr, L_S.otgr, 2250, S.ID, L_S.KVET, DECODE(L_S.KOD_POLUCH,99999,0,L_S.KOD_POLUCH), L_S.KOD_POTREB,
	     NVL(L_S.PRIM,' '), L_S.GR4, L_S.VV_DAT, TO_DATE('31.12.'||TO_CHAR(L_S.GOD_SP),'dd.mm.yyyy'), 
		 M1, M2, M3, M4, M5, M6, M7, M8, M9, M10, M11, M12, KV1, KV2, KV3, KV4, VSEGO,L_S.KR_DAT,L_S.ZAKAZ_ID 
        FROM load_buffer.SPECIF L_S, KLS_DOG D, KLS_STAN S
		 WHERE L_S.NUM_DOG = D.SHORT_NUMBER 
		   AND L_S.KST = S.STAN_KOD
		   AND L_S.ID=M_S.ID)
    WHERE EXISTS (SELECT NULL
        FROM load_buffer.SPECIF L_S, KLS_DOG D, KLS_STAN S
		 WHERE L_S.NUM_DOG = D.SHORT_NUMBER 
		   AND L_S.KST = S.STAN_KOD
		   AND L_S.ID=M_S.ID);
  COMMIT;

  INSERT INTO MASTER.SPECIF
        (ID, DOG_ID, PROD_ID_NPR, LOAD_ABBR, STANOTP_ID, STAN_ID, VETKA_ID, POLUCH_ID, POTREB_ID, 
	     PRIM, GR4, BEGIN_DATE, END_DATE, M1, M2, M3, M4, M5, M6, M7, M8, M9, M10, M11, M12, 
		 KV1, KV2, KV3, KV4, VES_ALL, UPDATE_DATE, MONTH_ALL_ID)
	 (SELECT L_S.ID, D.ID,L_S.kod_npr,L_S.otgr,2250,S.ID,L_S.KVET,DECODE(L_S.KOD_POLUCH,99999,0,L_S.KOD_POLUCH),
	     L_S.KOD_POTREB, NVL(L_S.PRIM,' '), L_S.GR4, L_S.VV_DAT,TO_DATE('31.12.'||TO_CHAR(L_S.GOD_SP),'dd.mm.yyyy'),  
		 M1, M2, M3, M4, M5, M6, M7, M8, M9, M10, M11, M12, KV1, KV2, KV3, KV4, VSEGO,L_S.KR_DAT,L_S.ZAKAZ_ID 
        FROM load_buffer.SPECIF L_S, KLS_DOG D, KLS_STAN S
		 WHERE L_S.NUM_DOG = D.SHORT_NUMBER 
		   AND L_S.KST = S.STAN_KOD
		   AND NOT EXISTS (SELECT NULL FROM MASTER.SPECIF M_S WHERE M_S.ID=L_S.ID)); 
   COMMIT;

  DELETE FROM MASTER.SPECIF M_S 
   WHERE NOT EXISTS (SELECT NULL FROM load_buffer.SPECIF L_S WHERE L_S.ID=M_S.ID)
     AND M_S.update_date BETWEEN date_beg AND date_end;

  COMMIT;

END Renew_Specif;

/

