--
-- RENEW_KLS_EVENT  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.RENEW_KLS_EVENT(DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE KLS_EVENT
    SET EVENT_NAME = (SELECT A.EVENT_NAME FROM load_buffer.LOG_EVENTS A WHERE A.EVENT_ID=KLS_EVENT.ID)
        WHERE EXISTS (SELECT B.EVENT_ID   FROM load_buffer.LOG_EVENTS B WHERE B.EVENT_ID=KLS_EVENT.ID);

  INSERT INTO KLS_EVENT (ID, EVENT_NAME) (SELECT C.EVENT_ID, C.EVENT_NAME FROM load_buffer.LOG_EVENTS C
        WHERE NOT EXISTS (SELECT KLS_EVENT.ID FROM KLS_EVENT WHERE KLS_EVENT.ID = C.EVENT_ID));

  DELETE FROM KLS_EVENT WHERE NOT EXISTS (SELECT D.EVENT_ID from load_buffer.LOG_EVENTS D WHERE D.EVENT_ID=KLS_EVENT.ID);

  COMMIT;

END RENEW_KLS_EVENT;

/

