--
-- RENEW_KLS_PROD_GU12  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Kls_Prod_Gu12 (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  RETURN;

  --- Справочник групп н/продуктов (для ГУ-12)
  UPDATE KLS_PROD_GU12
    SET (NAME, NAME_GU12, ORDER_GDPL, NAME_GDPL, STAT_NAGR, GD_VAGTYPE_ID, GD_GROUP_ID,GROUP_PLAN)
	  = (SELECT NAIM, NAIM_GU12, ORDER_GDPL, NAME_GDPL, STAT_NAGR, ROD_VAG, 3, GROUP_PLAN
  	     FROM load_buffer.prodgu12 WHERE kod=KLS_PROD_GU12.ID)
     WHERE EXISTS (SELECT NULL FROM load_buffer.prodgu12 WHERE kod=KLS_PROD_GU12.ID);

  INSERT INTO KLS_PROD_GU12 (ID,NAME, NAME_GU12, ORDER_GDPL, NAME_GDPL, STAT_NAGR, GD_VAGTYPE_ID, GD_GROUP_ID,GROUP_PLAN)
	(SELECT kod,NAIM, NAIM_GU12, ORDER_GDPL, NAME_GDPL, STAT_NAGR, ROD_VAG, 3, GROUP_PLAN
	  FROM load_buffer.prodgu12 A
      WHERE NOT EXISTS (SELECT NULL FROM KLS_PROD_GU12 C WHERE C.ID=A.kod));

  COMMIT;
END Renew_Kls_Prod_Gu12;

/

