--
-- RENEW_KLS_PRICHIN  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.RENEW_KLS_PRICHIN(DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE KLS_PRICHIN B
    SET (KOD_CLASS, KOD_GROUP, NAME) = 
	(SELECT KOD_CLASS, KOD_GROUP, PRICH_NAME 
	  FROM load_buffer.KLS_PRCH A WHERE A.KOD_PRICH=B.ID)
  WHERE EXISTS 
    (SELECT NULL
	  FROM load_buffer.KLS_PRCH A WHERE A.KOD_PRICH=B.ID);

  INSERT INTO KLS_PRICHIN (ID, KOD_CLASS, KOD_GROUP, NAME) 
    (SELECT KOD_PRICH, KOD_CLASS, KOD_GROUP, PRICH_NAME
	  FROM load_buffer.KLS_PRCH A
     WHERE NOT EXISTS 
      (SELECT NULL 
	    FROM KLS_PRICHIN B WHERE A.KOD_PRICH=B.ID));

  COMMIT;

END RENEW_KLS_PRICHIN;

/

