--
-- RENEW_OPL  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Opl (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
  date_inc DATE;
BEGIN
/*
UPDATE master.OPL SET
  (KOL,DAV_ORG,PLAT_POR,NOM_POR,KOD_PLD,N_SCHET,DEN_SOP,PR_DOG,BANK,NAZN_PLAT,EMITENT,K_SCHET,
   SUMMA,VZ,INV,DATA_POST,KOD_PLP,RS_PLD,STN_DOK,NOM_DOG,DATA_VIP,BANK_NOM,TIP,PLAT_DOG,PROGRAM,
   T_DATE,PATH,NAM_VEK,MFO_PLD,T_TIME,AVIZO,DISKONT,DATECANCEL,DATA_POR,dog_id,is_snp)
 = (SELECT KOL,DAV_ORG,PLAT_POR,NOM_POR,KOD_PLD,N_SCHET,IIF(DEN_SOP,1,0),opl.PR_DOG,BANK,NAZN_PLAT,EMITENT,K_SCHET,
     SUMMA,IIF(VZ,1,0),INV,DATA_POST,KOD_PLP,RS_PLD,STN_DOK,NOM_DOG,DATA_VIP,BANK_NOM,TIP,PLAT_DOG,opl.PROGRAM,
     T_DATE,PATH,NAM_VEK,MFO_PLD,T_TIME,IIF(AVIZO,1,0),DISKONT,DATECANCEL,DATA_POR,dog.ID,poluch
      FROM load_buffer.opl, load_buffer.DOG
	 WHERE opl.NOM_DOG=dog.NUM_DOG AND OPL.NOM_DOK=master.OPL.NOM_DOK)
WHERE EXISTS (SELECT OPL.NOM_DOK FROM load_buffer.opl, load_buffer.DOG WHERE opl.NOM_DOG=dog.NUM_DOG AND OPL.NOM_DOK=master.OPL.NOM_DOK);

COMMIT;


INSERT  INTO master.opl
     (nom_dok,KOL,DAV_ORG,PLAT_POR,NOM_POR,KOD_PLD,N_SCHET,DEN_SOP,PR_DOG,BANK,NAZN_PLAT,EMITENT,K_SCHET,
      SUMMA,VZ,INV,DATA_POST,KOD_PLP,RS_PLD,STN_DOK,NOM_DOG,DATA_VIP,BANK_NOM,TIP,PLAT_DOG,PROGRAM,
      T_DATE,PATH,NAM_VEK,MFO_PLD,T_TIME,AVIZO,DISKONT,DATECANCEL,DATA_POR,dog_id,is_snp)
     (SELECT NOM_DOK,KOL,DAV_ORG,PLAT_POR,NOM_POR,KOD_PLD,N_SCHET,IIF(DEN_SOP,1,0),opl.PR_DOG,BANK,NAZN_PLAT,EMITENT,K_SCHET,
             SUMMA,IIF(VZ,1,0),INV,DATA_POST,KOD_PLP,RS_PLD,STN_DOK,NOM_DOG,DATA_VIP,BANK_NOM,TIP,PLAT_DOG,opl.PROGRAM,
             T_DATE,PATH,NAM_VEK,MFO_PLD,T_TIME,IIF(AVIZO,1,0),DISKONT,DATECANCEL,DATA_POR,dog.ID,poluch
        FROM load_buffer.opl, load_buffer.DOG
       WHERE load_buffer.opl.NOM_DOG=load_buffer.DOG.NUM_DOG and
	         NOT EXISTS (SELECT master.OPL.NOM_DOK FROM master.OPL WHERE master.OPL.NOM_DOK=load_buffer.opl.NOM_DOK));
*/
COMMIT;
/*
DELETE FROM master.OPL A WHERE
    NOT EXISTS (SELECT k.NOM_DOK FROM load_buffer.OPL k WHERE k.NOM_DOK = A.NOM_DOK) AND
    A.DATA_POST BETWEEN date_beg AND date_end;
*/
COMMIT;

END Renew_OPL;

/

