--
-- RENEW_R3_BILLS  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_R3_Bills (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') AS
  IsFull NUMBER(1);
BEGIN
  RETURN;
  
  IF param1 || ' ' = ' ' THEN
    IsFull:=1;
  ELSE
    IsFull:=0;
  END IF;

  -- Обновление счетов R3 
  UPDATE R3_BILLS
    SET (NOM_R3, NOM_DOK, DATE_VYP_SF, IS_AGENT, NOM_SF, SUMMA_DOK, SUMMA_PROD, SUMMA_PROD_NDS, SUMMA_AKCIZ, 
	     SUMMA_TARIF, SUMMA_TARIF_NDS, SUMMA_VOZN, SUMMA_VOZN_NDS, SUMMA_STRAH, VBAP_MATNR,VES) =
	(SELECT 
	   A.NOM_R3, NULL, A.DATE_VYP_SF, 3, A.NOM_SF, A.SUMMA_DOK,A.SUMMA_PROD,A.SUMMA_PROD_NDS,A.SUMMA_AKCIZ,
	     A.SUMMA_TARIF,A.SUMMA_TARIF_NDS,A.SUMMA_VOZN,A.SUMMA_VOZN_NDS,A.SUMMA_STRAH,A.VBAP_MATNR,A.VES
     FROM load_buffer.v_r3_bills A
    WHERE A.VBELN=R3_BILLS.VBELN) 
   WHERE EXISTS 
	(SELECT NULL 
     FROM load_buffer.v_r3_bills A
    WHERE A.VBELN=R3_BILLS.VBELN); 
  COMMIT;

  -- Добавление счетов R3   
  INSERT INTO R3_BILLS
    (VBELN, NOM_R3, NOM_DOK, DATE_VYP_SF, IS_AGENT, NOM_SF, SUMMA_DOK, SUMMA_PROD, SUMMA_PROD_NDS, 
	 SUMMA_AKCIZ, SUMMA_TARIF, SUMMA_TARIF_NDS, SUMMA_VOZN, SUMMA_VOZN_NDS, SUMMA_STRAH,VBAP_MATNR,VES)
	(SELECT A.VBELN, A.NOM_R3, NULL, A.DATE_VYP_SF, 3, A.NOM_SF, A.SUMMA_DOK,A.SUMMA_PROD,A.SUMMA_PROD_NDS,A.SUMMA_AKCIZ,
	     A.SUMMA_TARIF,A.SUMMA_TARIF_NDS,A.SUMMA_VOZN,A.SUMMA_VOZN_NDS,A.SUMMA_STRAH,A.VBAP_MATNR,A.VES
	FROM load_buffer.v_r3_bills A
     WHERE NOT EXISTS (SELECT NULL FROM R3_BILLS C WHERE C.VBELN=A.VBELN));
  COMMIT;

  -- Проставить NOM_DOK
  UPDATE R3_BILLS
    SET (NOM_DOK,IS_AGENT) =
	(SELECT DISTINCT A.NOM_DOK,A.IS_AGENT
       FROM BILLS A 
      WHERE A.nom_sf=R3_BILLS.nom_sf AND A.DATE_VYP_SF>=TO_DATE('01.01.2003','dd.mm.yyyy') AND NVL(A.OLD_NOM_DOK,0)=0)
   WHERE EXISTS 
	(SELECT NULL
       FROM BILLS A 
      WHERE A.nom_sf=R3_BILLS.nom_sf AND A.DATE_VYP_SF>=TO_DATE('01.01.2003','dd.mm.yyyy') AND NVL(A.OLD_NOM_DOK,0)=0);
  COMMIT;
   
-- Обновление позиций счетов  
  Renew_R3_Bill_Pos(DATE_BEG,DATE_END,PARAM1);

  IF IsFull=1 THEN
    DELETE FROM R3_BILLS WHERE NOT EXISTS
      (SELECT NULL FROM load_buffer.v_r3_bills a WHERE a.VBELN=R3_BILLS.VBELN);
    NULL; 
  END IF;
  COMMIT;
END Renew_R3_Bills;

/

