--
-- RENEW_KLS_PROD_MOSGRP  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_KLS_PROD_MOSGRP (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  --- Справочник групп н/продуктов (для Москвы)
  UPDATE KLS_PROD_MOSGRP
    SET (NAME, ORDER_GDPL, NAME_GDPL, COLOR_GDPL, COLOR_NAME, IS_SEND)
	  = (SELECT NAME_GDPL, ORDER_GDPL, NAME_GDPL, COLOR_GDPL, COLOR_NAME, Iif(IS_SEND,1,0)
  	     FROM load_buffer.prod10gr WHERE kod_10_grp=KLS_PROD_MOSGRP.ID)
     WHERE EXISTS (SELECT NULL FROM load_buffer.prod10gr WHERE kod_10_grp=KLS_PROD_MOSGRP.ID);

  INSERT INTO KLS_PROD_MOSGRP (ID,NAME, ORDER_GDPL, NAME_GDPL, COLOR_GDPL, COLOR_NAME, IS_SEND)
	(SELECT kod_10_grp,NAME_GDPL, ORDER_GDPL, NAME_GDPL, COLOR_GDPL, COLOR_NAME, Iif(IS_SEND,1,0)
	  FROM load_buffer.prod10gr A
      WHERE NOT EXISTS (SELECT NULL FROM KLS_PROD_MOSGRP C WHERE C.ID=A.kod_10_grp));

  COMMIT;
END Renew_KLS_PROD_MOSGRP;

/

