--
-- RENEW_KLS_NARIAD  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Kls_Nariad (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

 RETURN;
  
 UPDATE KLS_NARIAD
    SET (NUM_NAR,DATE_NAR,DATE_END,DOVER_ID,MESTO_ID) =
	    (SELECT A.NUM_NAR,A.DATE_NAR,TO_DATE(A.DATE_END,'dd.mm.yyyy'),
		        A.ID_DOVER,0
		   FROM load_buffer.NARIAD A
		  WHERE A.ID_NARIAD=KLS_NARIAD.id)
  WHERE IS_LOADED=1 
    AND EXISTS (SELECT load_buffer.NARIAD.ID_NARIAD FROM load_buffer.NARIAD
                 WHERE load_buffer.NARIAD.ID_NARIAD=KLS_NARIAD.id);

  COMMIT;

  INSERT INTO KLS_NARIAD (ID,NUM_NAR,DATE_NAR,DATE_END,DOVER_ID,MESTO_ID,IS_LOADED)
     (SELECT A.ID_NARIAD,A.NUM_NAR,A.DATE_NAR,TO_DATE(A.DATE_END,'dd.mm.yyyy'),
		        A.ID_DOVER,0,1
		   FROM load_buffer.NARIAD A
      WHERE NOT EXISTS (SELECT KLS_NARIAD.id FROM KLS_NARIAD WHERE KLS_NARIAD.id=A.ID_NARIAD AND IS_LOADED=1));

  COMMIT;
  
  Renew_Kls_Nar_line(DATE_BEG,DATE_END);

  DELETE FROM KLS_NARIAD WHERE IS_LOADED=1 AND NOT EXISTS (SELECT E.ID_NARIAD FROM load_buffer.NARIAD E WHERE E.ID_NARIAD = KLS_NARIAD.ID);

  COMMIT;
END Renew_Kls_Nariad;

/

