--
-- RENEW_KLS_PREDPR_CONTACTS  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Kls_Predpr_contacts (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE KLS_PREDPR_CONTACTS
    SET (IS_BOSS, SHORTNAME, FIRSTNAME, MIDDLENAME, 
	     LASTNAME1, FIRSTNAME1, MIDDLENAME1, 
		 LASTNAME2, FIRSTNAME2, MIDDLENAME2, PHONE, 
		 STAFF, STAFF1, STAFF2, SEX, NA_OSNOV) =
        (SELECT IIF(BOSS,1,0), SHORTNAME, FIRSTNAME, MIDDLENAME, 
		 LASTNAME_, FIRST_, MIDDLE_, 
		 LAST2, FIRST2, MIDDLE2,  PHONE, 
		 STAFF, STAFF_, STAFF2, SEX, NA_OSNOV
        FROM load_buffer.contacts A 
		WHERE A.kod_predpr=KLS_PREDPR_CONTACTS.PREDPR_ID
		  AND NLS_UPPER(TRIM(A.LASTNAME))=NLS_UPPER(TRIM(KLS_PREDPR_CONTACTS.LASTNAME)))
   WHERE EXISTS 
        (SELECT NULL
        FROM load_buffer.contacts A 
		WHERE A.kod_predpr=KLS_PREDPR_CONTACTS.PREDPR_ID
		  AND NLS_UPPER(TRIM(A.LASTNAME))=NLS_UPPER(TRIM(KLS_PREDPR_CONTACTS.LASTNAME)));

  COMMIT;

  INSERT INTO KLS_PREDPR_CONTACTS (PREDPR_ID, LASTNAME,
         IS_BOSS, SHORTNAME, FIRSTNAME, MIDDLENAME, 
	     LASTNAME1, FIRSTNAME1, MIDDLENAME1, 
		 LASTNAME2, FIRSTNAME2, MIDDLENAME2, PHONE, 
		 STAFF, STAFF1, STAFF2, SEX, NA_OSNOV)
        (SELECT C.kod_predpr,C.lastname,
		 IIF(BOSS,1,0), SHORTNAME, FIRSTNAME, MIDDLENAME,
		 LASTNAME_, FIRST_, MIDDLE_, 
		 LAST2, FIRST2, MIDDLE2,  PHONE, 
		 STAFF, STAFF_, STAFF2, SEX, NA_OSNOV
	   FROM load_buffer.contacts C
	WHERE NOT EXISTS (SELECT NULL FROM KLS_PREDPR_CONTACTS D 
	WHERE C.kod_predpr=D.PREDPR_ID
		  AND NLS_UPPER(TRIM(C.LASTNAME))=NLS_UPPER(TRIM(D.LASTNAME))));

  COMMIT;

END Renew_Kls_Predpr_contacts;

/

