--
-- RENEW_KLS_DOVER  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Kls_Dover (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

 UPDATE KLS_DOVER
    SET (NUM_DOVER,DATE_DOVER,DATE_END,FIO_DOVER,DOLJ_DOVER,PREDPR_ID) =
	    (SELECT A.NUM_DOVER,A.DATE_DOVER,TO_DATE(A.DATE_END,'dd.mm.yyyy'),
		        A.FIO_DOVER,A.DOLJ_DOVER,A.KOD_PREDPR
		   FROM load_buffer.DOVER A
		  WHERE A.ID_DOVER=KLS_DOVER.id)
  WHERE IS_LOADED=1 
    AND EXISTS (SELECT load_buffer.DOVER.ID_DOVER FROM load_buffer.DOVER
                 WHERE load_buffer.DOVER.ID_DOVER=KLS_DOVER.id);

  COMMIT;

  INSERT INTO KLS_DOVER (ID,NUM_DOVER,DATE_DOVER,DATE_END,FIO_DOVER,DOLJ_DOVER,PREDPR_ID,IS_LOADED)
     (SELECT A.ID_DOVER,A.NUM_DOVER,A.DATE_DOVER,TO_DATE(A.DATE_END,'dd.mm.yyyy'),
		        A.FIO_DOVER,A.DOLJ_DOVER,A.KOD_PREDPR,1
		   FROM load_buffer.DOVER A
      WHERE NOT EXISTS (SELECT KLS_DOVER.id FROM KLS_DOVER WHERE KLS_DOVER.id=A.ID_DOVER AND IS_LOADED=1));

  COMMIT;
  
  Renew_Kls_Dov_Line (DATE_BEG,DATE_END);
  Renew_Kls_Nariad (DATE_BEG,DATE_END);

  DELETE FROM KLS_DOVER WHERE IS_LOADED=1 AND NOT EXISTS (SELECT E.ID_DOVER FROM load_buffer.DOVER E WHERE E.ID_DOVER = KLS_DOVER.ID);

  COMMIT;
END Renew_Kls_Dover;

/

