--
-- RENEW_KLS_CIST_DENI  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Kls_cist_deni (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE KLS_CIST_DENI B
    SET (END_DENI,PRIM)
	  = (SELECT A.END_DENI,A.PRIM
  	     FROM load_buffer.deni_otg A
		 WHERE A.NUM_CIST=B.NUM_CIST AND A.BEG_DENI=B.BEG_DENI)
    WHERE EXISTS 
	   (SELECT NULL
  	     FROM load_buffer.deni_otg A
		 WHERE A.NUM_CIST=B.NUM_CIST AND A.BEG_DENI=B.BEG_DENI);

  INSERT INTO KLS_CIST_DENI (NUM_CIST,BEG_DENI,END_DENI,PRIM)
	(SELECT  A.NUM_CIST,A.BEG_DENI,A.END_DENI,A.PRIM 
  	   FROM load_buffer.deni_otg A
      WHERE NOT EXISTS 
	   (SELECT NULL FROM KLS_CIST_DENI B WHERE A.NUM_CIST=B.NUM_CIST AND A.BEG_DENI=B.BEG_DENI));

  DELETE FROM KLS_CIST_DENI B WHERE 
    NOT EXISTS (SELECT NULL from load_buffer.deni_otg A WHERE A.NUM_CIST=B.NUM_CIST AND A.BEG_DENI=B.BEG_DENI); 
--	 AND KLS_PASP.DATEUPLOAD BETWEEN date_beg AND date_end;

  COMMIT; 
END Renew_Kls_cist_deni;

/

