--
-- RENEW_PLAN_POST  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Plan_Post (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
  PlanPerId NUMBER;
  PlanDate DATE;
  PlanId NUMBER;
BEGIN

  PlanDate:=TO_DATE(param1,'dd.mm.yyyy');
  PlanId:=TO_NUMBER(param2);
  
  
  -- Определяем плановые периоды 
  SELECT ID INTO PlanPerId
    FROM PLAN_PERIODS
   WHERE PLAN_ID=PlanId
     AND DATE_PLAN=TRUNC(PlanDate,'MONTH')
	 AND BEGIN_DATE=TRUNC(PlanDate,'MONTH')
	 AND END_DATE=LAST_DAY(PlanDate);

  -- Обновление плана	 
  UPDATE PLAN_POST C
    SET (PLAN_CENA, PLAN_VES, PLAN_SUM, DATE_CENA, CAT_CEN_ID)
 	 = (SELECT A.CENA_OTP, A.T_ITOG, A.D_ITOG, A.DATE_CEN, A.CAT_CEN 
		FROM load_buffer.plotg A, KLS_PLANSTRU B, KLS_DOG D
		WHERE A.KOD_POS=B.LEVEL_POS
		  AND A.KOD_SGR=B.KOD_SGR
		  AND A.KOD_SPG=B.KOD_SPG
		  AND A.KOD_RZD=B.KOD_RZD
		  AND A.KOD_PRZ=B.KOD_PRZ
		  AND A.KOD_GRP=B.KOD_GRP
		  AND A.KOD_PGR=B.KOD_PGR
		  AND A.N_DOG=D.SHORT_NUMBER
		  AND D.ID=C.DOG_ID
		  AND B.ID=C.PLANSTRU_ID
		  AND A.kod_npr=C.PROD_ID_NPR)
	WHERE EXISTS (SELECT NULL 
		FROM load_buffer.plotg A, KLS_PLANSTRU B, KLS_DOG D
		WHERE A.KOD_POS=B.LEVEL_POS
		  AND A.KOD_SGR=B.KOD_SGR
		  AND A.KOD_SPG=B.KOD_SPG
		  AND A.KOD_RZD=B.KOD_RZD
		  AND A.KOD_PRZ=B.KOD_PRZ
		  AND A.KOD_GRP=B.KOD_GRP
		  AND A.KOD_PGR=B.KOD_PGR
		  AND A.N_DOG=D.SHORT_NUMBER
		  AND D.ID=C.DOG_ID
		  AND B.ID=C.PLANSTRU_ID
		  AND A.kod_npr=C.PROD_ID_NPR)
	  AND C.PLAN_ID=PlanId
	  AND C.PLAN_PER_ID=PlanPerId
	  AND C.PAYFORM_ID=10;

  COMMIT;

  -- Добавление в план  
  INSERT INTO PLAN_POST (PLAN_CENA, PLAN_VES, PLAN_SUM, PLAN_ID, PLAN_PER_ID, PLANSTRU_ID, 
       DOG_ID, PROD_ID_NPR, PAYFORM_ID, DATE_CENA, CAT_CEN_ID, APPL_TAG)
   (SELECT A.CENA_OTP, A.T_ITOG, A.D_ITOG, PlanId, PlanPerId, B.ID, 
       D.ID, A.kod_npr, 10, A.DATE_CEN, A.CAT_CEN, '' 
		FROM load_buffer.plotg A, KLS_PLANSTRU B, KLS_DOG D
		WHERE A.KOD_POS=B.LEVEL_POS
		  AND A.KOD_SGR=B.KOD_SGR
		  AND A.KOD_SPG=B.KOD_SPG
		  AND A.KOD_RZD=B.KOD_RZD
		  AND A.KOD_PRZ=B.KOD_PRZ
		  AND A.KOD_GRP=B.KOD_GRP
		  AND A.KOD_PGR=B.KOD_PGR
		  AND A.N_DOG=D.SHORT_NUMBER
  		  AND NOT EXISTS 
		    (SELECT NULL 
			 FROM PLAN_POST C 
			 WHERE C.PLAN_ID=PlanId
			   AND C.PLAN_PER_ID=PlanPerId
			   AND C.PAYFORM_ID=10
			   AND C.DOG_ID=D.ID
			   AND C.PLANSTRU_ID=B.ID
			   AND C.PROD_ID_NPR=A.kod_npr));

  COMMIT;

  -- Удаление из рабочего плана  
  DELETE FROM PLAN_POST C
    WHERE C.PLAN_ID=PlanId
	  AND C.PLAN_PER_ID=PlanPerId
	  AND C.PAYFORM_ID=10
      AND (C.APPL_TAG<>'MASTER' or C.APPL_TAG IS NULL)
	  AND NOT EXISTS (SELECT NULL 
		FROM load_buffer.plotg A, KLS_PLANSTRU B, KLS_DOG D
		WHERE A.KOD_POS=B.LEVEL_POS
		  AND A.KOD_SGR=B.KOD_SGR
		  AND A.KOD_SPG=B.KOD_SPG
		  AND A.KOD_RZD=B.KOD_RZD
		  AND A.KOD_PRZ=B.KOD_PRZ
		  AND A.KOD_GRP=B.KOD_GRP
		  AND A.KOD_PGR=B.KOD_PGR
		  AND A.N_DOG=D.SHORT_NUMBER
          AND D.ID=C.DOG_ID
		  AND B.ID=C.PLANSTRU_ID
		  AND A.kod_npr=C.PROD_ID_NPR);
  COMMIT;

END Renew_Plan_Post; 
/

