--
-- RENEW_KLS_VAGOWNER_MOS  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Kls_Vagowner_mos (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN
  UPDATE KLS_VAGOWNER_MOS
    SET (ABBR,NAME) =
	(SELECT TIPV_SHORT, TIPV_NAME 
	   FROM load_buffer.TRANS_TYPES WHERE tipv=ID)
    WHERE EXISTS (SELECT NULL FROM load_buffer.TRANS_TYPES B WHERE B.tipv=KLS_VAGOWNER_MOS.ID);

  INSERT INTO KLS_VAGOWNER_MOS (ID,abbr,NAME)
	(SELECT tipv,TIPV_SHORT, TIPV_NAME 
	   FROM load_buffer.TRANS_TYPES
    WHERE NOT EXISTS (SELECT NULL FROM KLS_VAGOWNER_MOS WHERE ID=tipv));

  COMMIT;

END Renew_Kls_Vagowner_mos;

/

