--
-- RENEW_KLS_PREDPR_AKCIZ  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Kls_Predpr_Akciz (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

 /* UPDATE KLS_PREDPR_AKCIZ
    SET (PLAT_ID, DATE_BEG, DATE_END, EX_SVID, EX_SVID_PREF, EX_SVID_NUMB, DATE_CANCEL, DATE_GIVE, IS_OPT, IS_ROZN, PROD_GROUPS_ID) =
        (SELECT KOD_PLAT, DATE_BEG, DATE_END, EX_SVID, EX_PREF, EX_NUMB, DATE_OUT, DATE_GIVE, IS_OPT, IS_ROZN, PROD_GRP
           FROM load_buffer.predpr_a A WHERE A.ID=KLS_PREDPR_AKCIZ.ID)
   WHERE EXISTS (SELECT NULL FROM load_buffer.predpr_a B WHERE b.ID=KLS_PREDPR_AKCIZ.ID);

  COMMIT;

  INSERT INTO KLS_PREDPR_AKCIZ (ID, PLAT_ID, DATE_BEG, DATE_END, EX_SVID,EX_SVID_PREF, EX_SVID_NUMB, DATE_CANCEL, DATE_GIVE, IS_OPT, IS_ROZN, PROD_GROUPS_ID)
        (SELECT c.ID,KOD_PLAT, DATE_BEG, DATE_END, EX_SVID, EX_PREF, EX_NUMB, DATE_OUT, DATE_GIVE, IS_OPT, IS_ROZN, PROD_GRP 
	   FROM load_buffer.predpr_a C
	WHERE NOT EXISTS (SELECT NULL FROM KLS_PREDPR_AKCIZ D WHERE D.ID=c.ID));

  COMMIT;

  DELETE FROM KLS_PREDPR_AKCIZ WHERE NOT EXISTS
    (SELECT NULL FROM load_buffer.predpr_a E WHERE E.ID= KLS_PREDPR_AKCIZ.ID);*/
  NULL;
END Renew_Kls_Predpr_Akciz;

/

