--
-- RENEW_KLS_ST_RASH_KONS  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Kls_St_RASH_KONS(DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE KLS_ST_RASH_KONS
    SET (NAME) =
	    (SELECT A.naim_ras FROM load_buffer.st_ras A WHERE A.st_ras=KLS_ST_RASH_KONS.ID)
    WHERE EXISTS (SELECT NULL FROM load_buffer.st_ras A WHERE A.st_ras=KLS_ST_RASH_KONS.ID);

  INSERT INTO KLS_ST_RASH_KONS (ID,NAME)
    SELECT C.st_ras, C.naim_ras FROM load_buffer.st_ras C
    WHERE NOT EXISTS (SELECT NULL FROM KLS_ST_RASH_KONS D WHERE D.ID=C.ST_ras);

  COMMIT;

END Renew_Kls_St_RASH_KONS;

/

