--
-- RENEW_KLS_PREDPR_KONS  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Kls_Predpr_Kons (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE KLS_PREDPR_KONS
    SET (NAME, INN) =
        (SELECT NVL(POST_NAME,'?'), NVL(POST_INN,'?')
           FROM load_buffer.kod_post A WHERE NVL(TO_NUMBER(A.post_inn),0)=KLS_PREDPR_KONS.ID)
   WHERE EXISTS (SELECT NULL FROM load_buffer.kod_post B WHERE NVL(TO_NUMBER(B.post_inn),0)=KLS_PREDPR_KONS.ID);

  COMMIT;

  INSERT INTO KLS_PREDPR_KONS (ID, NAME,INN)
        (SELECT NVL(TO_NUMBER(POST_INN),0),NVL(POST_NAME,'?'),NVL(POST_INN,'?') 
	   FROM load_buffer.kod_post C
	WHERE NOT EXISTS (SELECT NULL FROM KLS_PREDPR_KONS D WHERE D.ID=NVL(TO_NUMBER(C.POST_INN),0)));

  COMMIT;

END Renew_Kls_Predpr_Kons;

/

