--
-- RENEW_DUMMY  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.RENEW_DUMMY (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN
  COMMIT;
END RENEW_DUMMY;

/

