--
-- RENEW_PRICHIN  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Prichin (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE MASTER.PLAN_POST_PRICHIN M_P
    SET (TO_MOS, ORDNUNG, PLAN, IZM_PLAN, OBPR, NORMA, NORMA_OBPR, FACT, 
	     RAZN_TONN, RAZN_DAT, ZAYV_TONN, ZAYV_DAT, 
		 PRICHIN_ID, NOTE
		 )
	 = (SELECT TO_MOS, ORDNUNG, PLAN, IZM_PLAN, OBPR, NORMA, NORMA_OBPR, FACT, 
	           RAZN_TONN, RAZN_DAT, ZAYV_TONN, ZAYV_DAT, 
			   KOD_PRICH, NOTE
          FROM load_buffer.PRICHIN L_P, (SELECT * FROM KLS_PLANSTRU WHERE KOD_PGR=0) S
		 WHERE L_P.KOD_SGR=S.KOD_SGR
		   AND L_P.KOD_SPG=S.KOD_SPG
		   AND L_P.KOD_RZD=S.KOD_RZD
		   AND L_P.KOD_PRZ=S.KOD_PRZ
		   AND L_P.KOD_GRP=S.KOD_GRP
		   AND L_P.BEG_DATE=M_P.BEG_DATE
		   AND L_P.END_DATE=M_P.END_DATE
		   AND L_P.KOD_NPR=M_P.PROD_ID_NPR
		   AND S.ID=M_P.PLANSTRU_ID
		   AND L_P.KOD_SOBS=M_P.OWNER_ID)
    WHERE EXISTS (SELECT NULL
          FROM load_buffer.PRICHIN L_P, (SELECT * FROM KLS_PLANSTRU WHERE KOD_PGR=0) S
		 WHERE L_P.KOD_SGR=S.KOD_SGR
		   AND L_P.KOD_SPG=S.KOD_SPG
		   AND L_P.KOD_RZD=S.KOD_RZD
		   AND L_P.KOD_PRZ=S.KOD_PRZ
		   AND L_P.KOD_GRP=S.KOD_GRP
		   AND L_P.BEG_DATE=M_P.BEG_DATE
		   AND L_P.END_DATE=M_P.END_DATE
		   AND L_P.KOD_NPR=M_P.PROD_ID_NPR
		   AND S.ID=M_P.PLANSTRU_ID
		   AND L_P.KOD_SOBS=M_P.OWNER_ID);
  COMMIT;

  INSERT INTO MASTER.PLAN_POST_PRICHIN 
        (BEG_DATE, END_DATE, TO_MOS, ORDNUNG, PROD_ID_NPR, PLANSTRU_ID, OWNER_ID, 
		 PLAN, IZM_PLAN, OBPR, NORMA, NORMA_OBPR, FACT, RAZN_TONN, RAZN_DAT, 
		 ZAYV_TONN, ZAYV_DAT, PRICHIN_ID, NOTE)
	 (SELECT L_P.BEG_DATE, L_P.END_DATE, TO_MOS, ORDNUNG, KOD_NPR, S.ID, KOD_SOBS, 
	         PLAN, IZM_PLAN, OBPR, NORMA, NORMA_OBPR, FACT, RAZN_TONN, RAZN_DAT, 
			 ZAYV_TONN, ZAYV_DAT, KOD_PRICH, NOTE
          FROM load_buffer.PRICHIN L_P,(SELECT * FROM KLS_PLANSTRU WHERE KOD_PGR=0) S 
		 WHERE L_P.KOD_SGR=S.KOD_SGR
		   AND L_P.KOD_SPG=S.KOD_SPG
		   AND L_P.KOD_RZD=S.KOD_RZD
		   AND L_P.KOD_PRZ=S.KOD_PRZ
		   AND L_P.KOD_GRP=S.KOD_GRP
		   AND NOT EXISTS (SELECT NULL FROM MASTER.PLAN_POST_PRICHIN M_P 
		                    WHERE L_P.BEG_DATE=M_P.BEG_DATE
                              AND L_P.END_DATE=M_P.END_DATE
                              AND L_P.KOD_NPR=M_P.PROD_ID_NPR
                              AND S.ID=M_P.PLANSTRU_ID
                              AND L_P.KOD_SOBS=M_P.OWNER_ID));

   COMMIT;

  DELETE FROM MASTER.PLAN_POST_PRICHIN M_P 
    WHERE NOT EXISTS 
	  (SELECT NULL FROM load_buffer.PRICHIN L_P,(SELECT * FROM KLS_PLANSTRU WHERE KOD_PGR=0) S
		 WHERE L_P.KOD_SGR=S.KOD_SGR
		   AND L_P.KOD_SPG=S.KOD_SPG
		   AND L_P.KOD_RZD=S.KOD_RZD
		   AND L_P.KOD_PRZ=S.KOD_PRZ
		   AND L_P.KOD_GRP=S.KOD_GRP
		   AND L_P.BEG_DATE=M_P.BEG_DATE
		   AND L_P.END_DATE=M_P.END_DATE
		   AND L_P.KOD_NPR=M_P.PROD_ID_NPR
		   AND S.ID=M_P.PLANSTRU_ID
		   AND L_P.KOD_SOBS=M_P.OWNER_ID)
    AND M_P.END_DATE BETWEEN date_beg AND date_end;

  COMMIT;

END Renew_Prichin;

/

