--
-- RENEW_KLS_ST_PRIH_KONS  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Kls_St_PRIH_KONS(DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE KLS_ST_PRIH_KONS
    SET (NAME) =
	    (SELECT A.naim_st FROM load_buffer.st_prich A WHERE A.st_prich=KLS_ST_PRIH_KONS.ID)
    WHERE EXISTS (SELECT NULL FROM load_buffer.st_prich A WHERE A.st_prich=KLS_ST_PRIH_KONS.ID);

  INSERT INTO KLS_ST_PRIH_KONS (ID,NAME)
    SELECT C.st_prich, C.naim_st FROM load_buffer.st_prich C
    WHERE NOT EXISTS (SELECT NULL FROM KLS_ST_PRIH_KONS D WHERE D.ID=C.ST_PRICH);

  COMMIT;

END Renew_Kls_St_PRIH_KONS;

/

