--
-- RENEW_KLS_UPAK  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Kls_Upak (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE KLS_UPAK
        SET (NAME, ABBR, VOL_FAS, KOD_MOSC)
        = (SELECT A.NAIM_UP, a.NAIUP_K, A.VOL_FAS, A.KOD_MOSK
			 FROM load_buffer.vid_upak A
			 WHERE A.TARA=KLS_UPAK.ID)
    WHERE EXISTS (SELECT NULL
			 FROM load_buffer.vid_upak A
			 WHERE A.TARA=KLS_UPAK.ID);
  COMMIT;

  INSERT INTO KLS_UPAK (ID,NAME,ABBR, VOL_FAS,KOD_MOSC)
	           (SELECT A.TARA, A.NAIM_UP, a.NAIUP_K, A.VOL_FAS, A.KOD_MOSK 
			   FROM load_buffer.vid_upak A
      WHERE NOT EXISTS (SELECT D.ID FROM KLS_UPAK D WHERE D.ID=A.TARA));
  COMMIT;

END Renew_Kls_Upak;

/

