--
-- RENEW_SOOB_EXP  (Procedure) 
--
CREATE OR REPLACE PROCEDURE MASTER.Renew_Soob_Exp (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  UPDATE MASTER.SOOB_EXP M_S
    SET (SORTBY, DOG_ID, PROD_ID_NPR, STAN_ID, EXPED_ID, LOAD_TYPE_ID, 
	     FACT_YEAR, PLAN_POST, PLAN_IZM, OBPR, PLAN_GD, NORMA_MON, 
		 FACT_MON, FACT_SUT, IS_BAD, PRICH, ZAPR_MPS
		 )
	 = (SELECT SORTBY, D.ID, PROD_KOD, S.ID, E.PREDPR_ID, VID_TRANS, 
	     FACT_YEAR, PLAN_POST, PLAN_IZM, OBPR, PLAN_GD, NORMA_MON, 
		 FACT_MON, FACT_SUT, IS_BAD, PRICH, ZAPR_MPS
          FROM load_buffer.SOOB_EXP L_S, KLS_DOG D, KLS_STAN S, PREDPR_ROLE E
		 WHERE L_S.NUM_DOG=D.SHORT_NUMBER
		   AND TO_NUMBER(L_S.STAN_KOD)=S.STAN_KOD
		   AND L_S.EXPED_KOD=E.KOD_MOSCOW
		   AND E.KLS_ROLE_ID=3
		   AND L_S.REP_DATE=M_S.REP_DATE
		   AND L_S.ID=M_S.POS_ID)
    WHERE EXISTS (SELECT NULL
          FROM load_buffer.SOOB_EXP L_S
		 WHERE L_S.REP_DATE=M_S.REP_DATE
		   AND L_S.ID=M_S.POS_ID);
  COMMIT;

  INSERT INTO MASTER.SOOB_EXP 
        (REP_DATE, POS_ID, SORTBY, DOG_ID, PROD_ID_NPR, STAN_ID, EXPED_ID, 
		 LOAD_TYPE_ID, FACT_YEAR, PLAN_POST, PLAN_IZM, OBPR, PLAN_GD, NORMA_MON, 
		 FACT_MON, FACT_SUT, IS_BAD, PRICH, ZAPR_MPS)
	 (SELECT REP_DATE,L_S.ID,SORTBY, D.ID, PROD_KOD, S.ID, E.PREDPR_ID, VID_TRANS, 
  	         FACT_YEAR, PLAN_POST, PLAN_IZM, OBPR, PLAN_GD, NORMA_MON, 
		     FACT_MON, FACT_SUT, IS_BAD, PRICH, ZAPR_MPS
          FROM load_buffer.SOOB_EXP L_S, KLS_DOG D, KLS_STAN S, PREDPR_ROLE E
		 WHERE L_S.NUM_DOG=D.SHORT_NUMBER
		   AND TO_NUMBER(L_S.STAN_KOD)=S.STAN_KOD
		   AND L_S.EXPED_KOD=E.KOD_MOSCOW
		   AND E.KLS_ROLE_ID=3
		   AND NOT EXISTS (SELECT NULL FROM MASTER.SOOB_EXP M_S 
                        	 WHERE L_S.REP_DATE=M_S.REP_DATE
                    		   AND L_S.ID=M_S.POS_ID));

   COMMIT;

  DELETE FROM MASTER.SOOB_EXP M_S 
    WHERE NOT EXISTS 
	  (SELECT NULL 
          FROM load_buffer.SOOB_EXP L_S
		 WHERE L_S.REP_DATE=M_S.REP_DATE
		   AND L_S.ID=M_S.POS_ID)
    AND M_S.REP_DATE BETWEEN date_beg AND date_end;

  COMMIT;

END Renew_Soob_Exp;

/

