--
-- FOR_ENVIRONMENT  (Package Body) 
--
CREATE OR REPLACE PACKAGE BODY SNP_REPL.For_Environment AS

-- Возвратить значение переменной
FUNCTION GET_ENV(pAPPL_NAME VARCHAR2, pGRP_NAME VARCHAR2, pENV_NAME VARCHAR2, pNETUSER VARCHAR2:=NULL) RETURN VARCHAR2 IS
  res VARCHAR2(250);
BEGIN
  res:='';
  BEGIN
    -- Ищем переменную конкретного пользователя
    SELECT ENV_VALUE INTO res FROM ENVIRONMENT
	WHERE NLS_UPPER(ENV_NAME)=NLS_UPPER(pENV_NAME)
	  AND ENV_TYPES_ID=1
      AND NLS_UPPER(APPL_NAME) = NLS_UPPER(pAPPL_NAME)
      AND NETUSER = pNETUSER;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
	  -- Ищем общую для всех переменную
      BEGIN
        SELECT ENV_VALUE INTO res FROM ENVIRONMENT
         WHERE NLS_UPPER(ENV_NAME)=NLS_UPPER(pENV_NAME)
  	       AND ENV_TYPES_ID=1
           AND NLS_UPPER(APPL_NAME) = NLS_UPPER(pAPPL_NAME)
           AND NETUSER IS NULL;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
	      res:='';
	  END;
  END;
  RETURN res;
END;

-- Присвоить значение переменной (если нет - добавить переменную)
PROCEDURE SET_ENV(pAPPL_NAME VARCHAR2, pGRP_NAME VARCHAR2, pENV_NAME VARCHAR2, pENV_VALUE VARCHAR2:=NULL, pNETUSER VARCHAR2:=NULL) IS
  grp_id NUMBER;
BEGIN
  UPDATE ENVIRONMENT SET ENV_VALUE=pENV_VALUE
   WHERE NLS_UPPER(ENV_NAME)=NLS_UPPER(pENV_NAME)
     AND ENV_TYPES_ID=1
     AND NLS_UPPER(APPL_NAME) = NLS_UPPER(pAPPL_NAME)
     AND NETUSER = pNETUSER;
  IF SQL%NOTFOUND THEN
    BEGIN
	  IF pGRP_NAME||' '<>' ' THEN
	    -- Поиск группы
        SELECT ID INTO grp_id FROM ENVIRONMENT_GRP
	     WHERE NLS_UPPER(GRP_NAME)=NLS_UPPER(pGRP_NAME);
        IF SQL%NOTFOUND THEN
          INSERT INTO ENVIRONMENT_GRP (GRP_NAME) VALUES (NLS_UPPER(pGRP_NAME));
	  	  COMMIT;
          SELECT ID INTO grp_id FROM ENVIRONMENT_GRP
		    WHERE NLS_UPPER(GRP_NAME)=NLS_UPPER(pGRP_NAME);
	    END IF;
	  ELSE
	    grp_id:=NULL;
	  END IF;
      INSERT INTO ENVIRONMENT (APPL_NAME,ENV_NAME, ENV_VALUE, ENV_TYPES_ID, ENV_GRP_ID, NETUSER)
	    VALUES (NLS_UPPER(pAPPL_NAME),NLS_UPPER(pENV_NAME),pENV_VALUE,1,grp_id,pNETUSER);
	EXCEPTION
	  WHEN OTHERS THEN
	    NULL;
	END;
  END IF;
  COMMIT;
END;

-- Удалить переменную
PROCEDURE DEL_ENV(pAPPL_NAME VARCHAR2, pENV_NAME VARCHAR2, pNETUSER VARCHAR2:=NULL) IS
BEGIN
  DELETE FROM ENVIRONMENT
   WHERE NLS_UPPER(ENV_NAME)=NLS_UPPER(pENV_NAME)
     AND NLS_UPPER(APPL_NAME) = NLS_UPPER(pAPPL_NAME)
     AND NETUSER=pNETUSER;
  COMMIT;
END;

END;
/


