--
-- FOR_INIT  (Package Body) 
--
CREATE OR REPLACE PACKAGE BODY SNP_REPL.For_Init AS
  xTERMINAL_NAME VARCHAR2(200);
  xOSUSER_NAME VARCHAR2(200);
  xIsTestMode NUMBER(1);

PROCEDURE Init_MASTER IS
BEGIN
  Dbms_Session.SET_NLS('NLS_DATE_FORMAT','''dd.mm.yyyy hh24:mi''');
  Dbms_Session.SET_NLS('NLS_LANGUAGE','''RUSSIAN''');
  execute immediate 'alter session set CURSOR_SHARING=FORCE';
  execute immediate 'alter session set current_schema='||FOR_REPL.gREPL_NAME;
END;

-- Текущий пользователь
FUNCTION GetCurrUser RETURN VARCHAR2 IS
BEGIN
  IF xOSUSER_NAME IS NULL THEN
    xOSUSER_NAME:=NLS_UPPER(SYS_CONTEXT('USERENV','OS_USER'));
	IF xOSUSER_NAME IS NULL THEN
	  xOSUSER_NAME:='UNKNOWN';
	END IF;
  END IF;
  RETURN xOSUSER_NAME;
EXCEPTION
  WHEN OTHERS THEN
    RETURN '';
END;


-- Текущая машина
FUNCTION GetCurrTerm RETURN VARCHAR2 IS
BEGIN
  IF xTERMINAL_NAME IS NULL THEN
    xTERMINAL_NAME:=NLS_UPPER(SYS_CONTEXT('USERENV','TERMINAL'));
    IF xTERMINAL_NAME IS NULL THEN
	  xTERMINAL_NAME:='UNKNOWN';
	END IF;
  END IF;
  RETURN xTERMINAL_NAME;
EXCEPTION
  WHEN OTHERS THEN
    RETURN '';
END;

END;
/


