--
-- AZC_TEST  (Package Body) 
--
CREATE OR REPLACE PACKAGE BODY MASTER.Azc_Test AS

FUNCTION GET_AZC_OST_VES_TEST(pORG_STRU_ID NUMBER, pPROD_ID_NPR VARCHAR2, pSOBSTV_ID NUMBER,  pDATE_OPER DATE DEFAULT SYSDATE, FIRST_DAY NUMBER DEFAULT 1) RETURN NUMBER IS
  v_lastost DATE;
  v_ost NUMBER;
  v_prih NUMBER;
  v_rash NUMBER;
  v_num_fil NUMBER;  
  
BEGIN

  IF pORG_STRU_ID IS NULL THEN
    RETURN 0;
  END IF;	

  IF pPROD_ID_NPR IS NULL THEN
    RETURN 0;
  END IF;	

  IF pSOBSTV_ID IS NULL THEN
    RETURN 0;
  END IF;	

  -- Находим дату ввода последнего остатка
  BEGIN
    SELECT C.ORG_STRU_2_ID, MAX(A.DATE_OPER) INTO v_num_fil,v_lastost 
	  FROM AZC_OPERATION A, AZC_TYPE_OPERATION B, ORG_RELATIONS C	
	 WHERE A.ORG_STRU_ID=pORG_STRU_ID
	   AND A.PROD_ID_NPR=pPROD_ID_NPR
	   AND A.SOBSTV_ID=pSOBSTV_ID
	   AND A.TYPE_OPER_ID=B.ID
	   AND B.KIND_OPER=0
	   AND A.ORG_STRU_ID = C.ORG_STRU_1_ID
	   AND A.DATE_OPER<=LAST_DAY(pDATE_OPER)
	   GROUP BY C.ORG_STRU_2_ID;
  EXCEPTION
     WHEN OTHERS THEN
	   v_lastost:=NULL;
  END;

  IF v_num_fil=31 THEN
  -- ухтинский район 
  -- Начальный остаток  
  IF v_lastost IS NULL THEN
    v_ost:=0;
	v_lastost:=TO_DATE('01.01.1900','dd.mm.yyyy');
  ELSE
    SELECT VES INTO v_ost
	  FROM AZC_OPERATION A,	 AZC_TYPE_OPERATION B
	 WHERE A.ORG_STRU_ID=pORG_STRU_ID
	   AND A.PROD_ID_NPR=pPROD_ID_NPR
	   AND A.SOBSTV_ID=pSOBSTV_ID
	   AND A.TYPE_OPER_ID=B.ID
	   AND B.KIND_OPER=0
	   AND A.DATE_OPER=v_lastost;
  END IF;
  
  IF FIRST_DAY=0 THEN 
  RETURN NVL(v_ost,0)+NVL(v_prih,0)-NVL(v_rash,0);
  END IF;
  
  -- Приход
  SELECT SUM(A.VES) INTO v_prih 
     FROM AZC_OPERATION A, AZC_TYPE_OPERATION B	
	 WHERE A.ORG_STRU_ID=pORG_STRU_ID
	   AND A.PROD_ID_NPR=pPROD_ID_NPR
	   AND A.SOBSTV_ID=pSOBSTV_ID
	   AND A.TYPE_OPER_ID=B.ID
	   AND B.KIND_OPER=1
	   AND A.DATE_OPER>=v_lastost
	   AND A.DATE_OPER<=pDATE_OPER;

  -- Расход
  SELECT SUM(A.VES) INTO v_rash 
     FROM AZC_OPERATION A, AZC_TYPE_OPERATION B	
	 WHERE A.ORG_STRU_ID=pORG_STRU_ID
	   AND A.PROD_ID_NPR=pPROD_ID_NPR
	   AND A.SOBSTV_ID=pSOBSTV_ID
	   AND A.TYPE_OPER_ID=B.ID
	   AND B.KIND_OPER=2
	   AND A.DATE_OPER>=v_lastost
	   AND A.DATE_OPER<=pDATE_OPER;

  RETURN NVL(v_ost,0)+NVL(v_prih,0)-NVL(v_rash,0);
  ELSE
  --Филиалы
    SELECT A.VES INTO v_ost FROM AZC_OPERATION A, AZC_TYPE_OPERATION B
	WHERE 
	A.DATE_OPER = v_lastost
	AND A.TYPE_OPER_ID = B.ID
	AND A.ORG_STRU_ID=pORG_STRU_ID
	AND A.PROD_ID_NPR=pPROD_ID_NPR
	AND A.SOBSTV_ID=pSOBSTV_ID
	AND B.KIND_OPER = 0;
	RETURN NVL(V_ost,0);
  END IF;  	   	     	
END;

FUNCTION GET_AZC_OST_VOL_TEST(pORG_STRU_ID NUMBER, pPROD_ID_NPR VARCHAR2, pSOBSTV_ID NUMBER,  pDATE_OPER DATE DEFAULT SYSDATE, FIRST_DAY NUMBER DEFAULT 1) RETURN NUMBER IS
  v_lastost DATE;
  v_ost NUMBER;
  v_prih NUMBER;
  v_rash NUMBER;
  v_num_fil NUMBER;  
  
BEGIN

  IF pORG_STRU_ID IS NULL THEN
    RETURN 0;
  END IF;	

  IF pPROD_ID_NPR IS NULL THEN
    RETURN 0;
  END IF;	

  IF pSOBSTV_ID IS NULL THEN
    RETURN 0;
  END IF;	

  -- Находим дату ввода последнего остатка
  BEGIN
    SELECT C.ORG_STRU_2_ID, MAX(A.DATE_OPER) INTO v_num_fil,v_lastost 
	  FROM AZC_OPERATION A, AZC_TYPE_OPERATION B, ORG_RELATIONS C	
	 WHERE A.ORG_STRU_ID=pORG_STRU_ID
	   AND A.PROD_ID_NPR=pPROD_ID_NPR
	   AND A.SOBSTV_ID=pSOBSTV_ID
	   AND A.TYPE_OPER_ID=B.ID
	   AND B.KIND_OPER=0
	   AND A.ORG_STRU_ID = C.ORG_STRU_1_ID
	   AND A.DATE_OPER<=LAST_DAY(pDATE_OPER)
	   GROUP BY C.ORG_STRU_2_ID;
  EXCEPTION
     WHEN OTHERS THEN
	   v_lastost:=NULL;
  END;

  IF v_num_fil=31 THEN
  -- ухтинский район 
  -- Начальный остаток  
  IF v_lastost IS NULL THEN
    v_ost:=0;
	v_lastost:=TO_DATE('01.01.1900','dd.mm.yyyy');
  ELSE
    SELECT VOLUME INTO v_ost
	  FROM AZC_OPERATION A,	 AZC_TYPE_OPERATION B
	 WHERE A.ORG_STRU_ID=pORG_STRU_ID
	   AND A.PROD_ID_NPR=pPROD_ID_NPR
	   AND A.SOBSTV_ID=pSOBSTV_ID
	   AND A.TYPE_OPER_ID=B.ID
	   AND B.KIND_OPER=0
	   AND A.DATE_OPER=v_lastost;
  END IF;
  
  IF FIRST_DAY=0 THEN 
  RETURN NVL(v_ost,0)+NVL(v_prih,0)-NVL(v_rash,0);
  END IF;
  
  -- Приход
  SELECT SUM(A.VOLUME) INTO v_prih 
     FROM AZC_OPERATION A, AZC_TYPE_OPERATION B	
	 WHERE A.ORG_STRU_ID=pORG_STRU_ID
	   AND A.PROD_ID_NPR=pPROD_ID_NPR
	   AND A.SOBSTV_ID=pSOBSTV_ID
	   AND A.TYPE_OPER_ID=B.ID
	   AND B.KIND_OPER=1
	   AND A.DATE_OPER>=v_lastost
	   AND A.DATE_OPER<=pDATE_OPER;

  -- Расход
  SELECT SUM(A.VOLUME) INTO v_rash 
     FROM AZC_OPERATION A, AZC_TYPE_OPERATION B	
	 WHERE A.ORG_STRU_ID=pORG_STRU_ID
	   AND A.PROD_ID_NPR=pPROD_ID_NPR
	   AND A.SOBSTV_ID=pSOBSTV_ID
	   AND A.TYPE_OPER_ID=B.ID
	   AND B.KIND_OPER=2
	   AND A.DATE_OPER>=v_lastost
	   AND A.DATE_OPER<=pDATE_OPER;

  RETURN NVL(v_ost,0)+NVL(v_prih,0)-NVL(v_rash,0);
  ELSE
  --Филиалы
    SELECT A.VOLUME INTO v_ost FROM AZC_OPERATION A, AZC_TYPE_OPERATION B
	WHERE 
	A.DATE_OPER = v_lastost
    AND A.ORG_STRU_ID=pORG_STRU_ID
    AND A.PROD_ID_NPR=pPROD_ID_NPR
    AND A.SOBSTV_ID=pSOBSTV_ID
	AND A.TYPE_OPER_ID = B.ID
	AND B.KIND_OPER = 0;
	RETURN NVL(V_ost,0);
  END IF;  	   	     	
END;
END;

/

