--
-- FOR_PARUS_SNAPSHOTS  (Package Body) 
--
CREATE OR REPLACE PACKAGE BODY MASTER.FOR_PARUS_SNAPSHOTS AS

PROCEDURE RENEW_SNAPSHOTS (DATE_BEG DATE:=TRUNC(SYSDATE,'MONTH') ,DATE_END DATE:=SYSDATE, param1 VARCHAR2:='', param2 VARCHAR2:='', param3 VARCHAR2:='') IS
BEGIN

  DELETE FROM LOAD_BUFFER.PARUS_DICACCFO;
  DELETE FROM LOAD_BUFFER.PARUS_DICLACFO;
  
  INSERT INTO LOAD_BUFFER.PARUS_DICACCFO (RN, PREF_SF, NPO_SF, ACC_DATE, BASE_NUMB, BASE_DATE, CONF_NUMB, CONF_DATE, SENDER, PRIM, SUM_WOUT, SUM_NDS, SUM_GSM, SUM_TOTAL, KOL_DN, NOM_ZD)
    SELECT RN, PREF_SF, NPO_SF, ACC_DATE, BASE_NUMB, BASE_DATE, CONF_NUMB, CONF_DATE, SENDER, PRIM, SUM_WOUT, SUM_NDS, SUM_GSM, SUM_TOTAL, KOL_DN, NOM_ZD 
	FROM VANEEV.V_DICACCFO_NEW@ORACLE.WORLD
    WHERE ACC_DATE>=DATE_BEG
      AND ACC_DATE<=DATE_END;

  INSERT INTO LOAD_BUFFER.PARUS_DICLACFO (RN, PRN, FOOD_RN, FOOD_PRN, FOOD_CODE, FOOD_TYPE, FOOD_NAME, AMOUNT, MES_UNIT, MES_UNIT_NAME, CENA_BN, SUM_BN, AKCIZ, GSM, SUM_WOUT, RATE_NDS, SUM_NDS, CENA, SUM_TOTAL)
    SELECT RN, PRN, FOOD_RN, FOOD_PRN, FOOD_CODE, FOOD_TYPE, FOOD_NAME, AMOUNT, MES_UNIT, MES_UNIT_NAME, CENA_BN, SUM_BN, AKCIZ, GSM, SUM_WOUT, RATE_NDS, SUM_NDS, CENA, SUM_TOTAL 
	FROM VANEEV.V_DICLACFO_NEW@ORACLE.WORLD
    WHERE ACC_DATE>=DATE_BEG
      AND ACC_DATE<=DATE_END;
	  
  FOR_PARUS.UPDATE_SNAPSHOTS_REQV;  	
  
  COMMIT;

END RENEW_SNAPSHOTS;
 
END;
/

