--
-- FOR_ENVIRONMENT  (Package Body) 
--
CREATE OR REPLACE PACKAGE BODY MASTER.For_Environment AS

-- Возвратить значение переменной 
FUNCTION GET_ENV(pAPPL_NAME VARCHAR2, pGRP_NAME VARCHAR2, pENV_NAME VARCHAR2, pNETUSER VARCHAR2:=NULL) RETURN VARCHAR2 IS
  res VARCHAR2(250);
BEGIN
  res:='';
  BEGIN
    -- Ищем переменную конкретного пользователя
    SELECT TRIM(ENV_VALUE) INTO res FROM ENVIRONMENT a, ENVIRONMENT_GRP b 
	WHERE a.ENV_GRP_ID=b.ID
	  AND NLS_UPPER(TRIM(APPL_NAME))||' ' = NLS_UPPER(TRIM(pAPPL_NAME))||' '
      AND NLS_UPPER(TRIM(b.GRP_NAME))||' ' = NLS_UPPER(TRIM(pGRP_NAME))||' '
      AND NLS_UPPER(TRIM(ENV_NAME))||' ' = NLS_UPPER(TRIM(pENV_NAME))||' ' 
	  AND NLS_UPPER(TRIM(NETUSER))||' ' = NLS_UPPER(TRIM(pNETUSER))||' ';
  EXCEPTION 
    WHEN NO_DATA_FOUND THEN
	  -- Ищем общую для всех переменную
      BEGIN
        SELECT TRIM(ENV_VALUE) INTO res FROM ENVIRONMENT a, ENVIRONMENT_GRP b 
	     WHERE a.ENV_GRP_ID=b.ID
    	   AND NLS_UPPER(TRIM(APPL_NAME))||' ' = NLS_UPPER(TRIM(pAPPL_NAME))||' '
           AND NLS_UPPER(TRIM(b.GRP_NAME))||' ' = NLS_UPPER(TRIM(pGRP_NAME))||' '
           AND NLS_UPPER(TRIM(ENV_NAME))||' ' = NLS_UPPER(TRIM(pENV_NAME))||' '
           AND NETUSER IS NULL;
      EXCEPTION 
        WHEN NO_DATA_FOUND THEN
	      res:='';
	  END;	  
  END;
  RETURN res;
END;  	  	

FUNCTION GET_ENV_USER(pAPPL_NAME VARCHAR2, pGRP_NAME VARCHAR2, pENV_NAME VARCHAR2) RETURN VARCHAR2 IS
  res VARCHAR2(250);
BEGIN
  RETURN GET_ENV(pAPPL_NAME,pGRP_NAME,pENV_NAME,FOR_INIT.GetCurrUser);
END;    

-- Присвоить значение переменной (если нет - добавить переменную)
PROCEDURE SET_ENV(pAPPL_NAME VARCHAR2, pGRP_NAME VARCHAR2, pENV_NAME VARCHAR2, pENV_VALUE VARCHAR2:=NULL, pNETUSER VARCHAR2:=NULL) IS
PRAGMA AUTONOMOUS_TRANSACTION;
  grp_id NUMBER;
BEGIN
  IF TRIM(pGRP_NAME)||' '<>' ' THEN
	-- Поиск группы
    SELECT ID INTO grp_id FROM ENVIRONMENT_GRP 
	 WHERE NLS_UPPER(TRIM(GRP_NAME))=NLS_UPPER(TRIM(pGRP_NAME));
    IF SQL%NOTFOUND THEN
      INSERT INTO ENVIRONMENT_GRP (GRP_NAME) VALUES (NLS_UPPER(TRIM(pGRP_NAME)));
	  COMMIT;
      SELECT ID INTO grp_id FROM ENVIRONMENT_GRP 
	   WHERE NLS_UPPER(TRIM(GRP_NAME))=NLS_UPPER(TRIM(pGRP_NAME));
	END IF;
  ELSE
    grp_id:=0;
  END IF;		

  UPDATE ENVIRONMENT SET ENV_VALUE=TRIM(pENV_VALUE) 
   WHERE NLS_UPPER(TRIM(APPL_NAME))||' ' = NLS_UPPER(TRIM(pAPPL_NAME))||' '
     AND ENV_GRP_ID = grp_id
     AND NLS_UPPER(TRIM(ENV_NAME))||' ' = NLS_UPPER(TRIM(pENV_NAME))||' ' 
     AND NLS_UPPER(TRIM(NETUSER))||' ' = NLS_UPPER(TRIM(pNETUSER))||' ';
  IF SQL%NOTFOUND THEN
    BEGIN
      INSERT INTO ENVIRONMENT (APPL_NAME,ENV_NAME, ENV_VALUE, ENV_TYPES_ID, ENV_GRP_ID, NETUSER) 
	    VALUES (NLS_UPPER(TRIM(pAPPL_NAME)),NLS_UPPER(TRIM(pENV_NAME)),TRIM(pENV_VALUE),1,grp_id,NLS_UPPER(TRIM(pNETUSER)));
	EXCEPTION
	  WHEN OTHERS THEN
	    NULL;
	END;
  END IF;		  	 
  COMMIT;
END;  

PROCEDURE SET_ENV_USER(pAPPL_NAME VARCHAR2, pGRP_NAME VARCHAR2, pENV_NAME VARCHAR2, pENV_VALUE VARCHAR2:=NULL) IS
BEGIN
  SET_ENV(pAPPL_NAME,pGRP_NAME,pENV_NAME,pENV_VALUE,FOR_INIT.GetCurrUser);
END;

-- Удалить переменную
PROCEDURE DEL_ENV(pAPPL_NAME VARCHAR2, pGRP_NAME VARCHAR2, pENV_NAME VARCHAR2, pNETUSER VARCHAR2:=NULL) IS
PRAGMA AUTONOMOUS_TRANSACTION;
  grp_id NUMBER;
BEGIN
  IF TRIM(pGRP_NAME)||' '<>' ' THEN
	-- Поиск группы
    SELECT ID INTO grp_id FROM ENVIRONMENT_GRP 
	 WHERE NLS_UPPER(TRIM(GRP_NAME))=NLS_UPPER(TRIM(pGRP_NAME));
    IF SQL%NOTFOUND THEN
      INSERT INTO ENVIRONMENT_GRP (GRP_NAME) VALUES (NLS_UPPER(TRIM(pGRP_NAME)));
	  COMMIT;
      SELECT ID INTO grp_id FROM ENVIRONMENT_GRP 
	   WHERE NLS_UPPER(TRIM(GRP_NAME))=NLS_UPPER(TRIM(pGRP_NAME));
	END IF;
  ELSE
    grp_id:=0;
  END IF;		

  DELETE FROM ENVIRONMENT 
   WHERE NLS_UPPER(TRIM(APPL_NAME))||' ' = NLS_UPPER(TRIM(pAPPL_NAME))||' '
     AND ENV_GRP_ID = grp_id
     AND NLS_UPPER(TRIM(ENV_NAME))||' ' = NLS_UPPER(TRIM(pENV_NAME))||' ' 
     AND NLS_UPPER(TRIM(NETUSER))||' ' = NLS_UPPER(TRIM(pNETUSER))||' ';
  COMMIT;
END;  

PROCEDURE DEL_ENV_USER(pAPPL_NAME VARCHAR2, pGRP_NAME VARCHAR2, pENV_NAME VARCHAR2, pNETUSER VARCHAR2:=NULL) IS
BEGIN
  DEL_ENV(pAPPL_NAME,pGRP_NAME,pENV_NAME,FOR_INIT.GetCurrUser);
END;

END;

/

