--
-- FOR_INIT  (Package Body) 
--
CREATE OR REPLACE PACKAGE BODY MASTER.For_Init AS
  xTERMINAL_NAME VARCHAR2(200);
  xOSUSER_NAME VARCHAR2(200);
  xAPP_USER_ID NUMBER;
  xSESSIONID NUMBER;
  xAPP_USER_NAME APP_USERS.NAME%TYPE;
  xAPP_USER_POST APP_USERS.POST%TYPE;
  xAPP_USER_SNP APP_USERS.SNP%TYPE;
  xAPP_USER_UNP APP_USERS.UNP%TYPE;
  xAPP_USER_MNOS APP_USERS.MNOS%TYPE;

PROCEDURE Init_MASTER IS
BEGIN
  Dbms_Session.SET_NLS('NLS_DATE_FORMAT','''dd.mm.yyyy hh24:mi''');
  Dbms_Session.SET_NLS('NLS_LANGUAGE','''RUSSIAN''');
END;

-- Текущий пользователь
FUNCTION GetCurrUser RETURN VARCHAR2 IS
BEGIN
  IF xOSUSER_NAME||' '=' ' THEN
    xOSUSER_NAME:=replace(NLS_UPPER(SYS_CONTEXT('USERENV','OS_USER')),'CORP\','');
	IF xOSUSER_NAME||' '=' ' THEN
	  xOSUSER_NAME:='UNKNOWN';
	END IF;  
  END IF;
  RETURN xOSUSER_NAME;	
EXCEPTION
  WHEN OTHERS THEN
    RETURN '';  
END;


-- Текущая машина
FUNCTION GetCurrTerm RETURN VARCHAR2 IS
BEGIN
  IF xTERMINAL_NAME||' '=' ' THEN
    xTERMINAL_NAME:=NLS_UPPER(SYS_CONTEXT('USERENV','TERMINAL'));
    IF xTERMINAL_NAME||' '=' ' THEN
      xTERMINAL_NAME:=REPLACE(NLS_UPPER(SYS_CONTEXT('USERENV','HOST')),'SNP\','');
      IF xTERMINAL_NAME||' '=' ' THEN
  	    xTERMINAL_NAME:='UNKNOWN';
	  END IF; 	
	END IF;  
  END IF;
  RETURN xTERMINAL_NAME;	
EXCEPTION
  WHEN OTHERS THEN
    RETURN '';  
END;

-- Текущая сессия
FUNCTION GetCurrSessionId RETURN NUMBER IS
BEGIN
  IF xSESSIONID IS NULL THEN
    xSESSIONID:=USERENV('SESSIONID');
  END IF;
  IF xSESSIONID IS NULL THEN
    xSESSIONID:=0;
  END IF;     
  RETURN xSESSIONID;    
EXCEPTION
  WHEN OTHERS THEN
    RETURN 0;  
END;


-- Текущий пользователь приложения: ID
FUNCTION AppUserId RETURN NUMBER IS
  CURSOR C1 IS 
	SELECT ID
	FROM MASTER.APP_USERS
	WHERE NETNAME=GetCurrUser;
BEGIN
  IF xAPP_USER_ID IS NULL THEN
    OPEN  C1;
	FETCH C1 INTO xAPP_USER_ID;
    CLOSE C1;
  END IF;
  RETURN xAPP_USER_ID;	
EXCEPTION
  WHEN OTHERS THEN
    RETURN 0;  
END;
    
-- Текущий пользователь приложения: NAME
FUNCTION AppUserName RETURN VARCHAR2 IS
  CURSOR C1 IS 
	SELECT NAME
	FROM MASTER.APP_USERS
	WHERE NETNAME=GetCurrUser;
BEGIN
  IF xAPP_USER_NAME||' '=' ' THEN
    OPEN  C1;
	FETCH C1 INTO xAPP_USER_NAME;
    CLOSE C1;
  END IF;
  RETURN xAPP_USER_NAME;	
EXCEPTION
  WHEN OTHERS THEN
    RETURN '';  
END;

-- Должность текущего пользователя приложения: POST
FUNCTION AppUserPost RETURN VARCHAR2 IS
  CURSOR C1 IS 
	SELECT POST
	FROM MASTER.APP_USERS
	WHERE NETNAME=GetCurrUser;
BEGIN
  IF xAPP_USER_POST||' '=' ' THEN
    OPEN  C1;
	FETCH C1 INTO xAPP_USER_POST;
    CLOSE C1;
  END IF;
  RETURN xAPP_USER_POST;	
EXCEPTION
  WHEN OTHERS THEN
    RETURN '';  
END;

-- Текущий пользователь приложения: SNP
FUNCTION AppUserSNP RETURN NUMBER IS
  CURSOR C1 IS 
	SELECT SNP
	FROM MASTER.APP_USERS
	WHERE NETNAME=GetCurrUser;
BEGIN
  IF xAPP_USER_SNP IS NULL THEN
    OPEN  C1;
	FETCH C1 INTO xAPP_USER_SNP;
    CLOSE C1;
  END IF;
  RETURN xAPP_USER_SNP;	
EXCEPTION
  WHEN OTHERS THEN
    RETURN 0;  
END;

-- Текущий пользователь приложения: UNP
FUNCTION AppUserUNP RETURN NUMBER IS
  CURSOR C1 IS 
	SELECT UNP
	FROM MASTER.APP_USERS
	WHERE NETNAME=GetCurrUser;
BEGIN
  IF xAPP_USER_UNP IS NULL THEN
    OPEN  C1;
	FETCH C1 INTO xAPP_USER_UNP;
    CLOSE C1;
  END IF;
  RETURN xAPP_USER_UNP;	
EXCEPTION
  WHEN OTHERS THEN
    RETURN 0;  
END;

-- Текущий пользователь приложения: MNOS
FUNCTION AppUserMNOS RETURN NUMBER IS
  CURSOR C1 IS 
	SELECT MNOS
	FROM MASTER.APP_USERS
	WHERE NETNAME=GetCurrUser;
BEGIN
  IF xAPP_USER_MNOS IS NULL THEN
    OPEN  C1;
	FETCH C1 INTO xAPP_USER_MNOS;
    CLOSE C1;
  END IF;
  RETURN xAPP_USER_MNOS;	
EXCEPTION
  WHEN OTHERS THEN
    RETURN 0;  
END;

-- Обновление статистики
PROCEDURE UPDATE_STAT IS
BEGIN
  BEGIN
    SYS.DBMS_UTILITY.ANALYZE_SCHEMA('MASTER', 'COMPUTE');
  EXCEPTION
     WHEN OTHERS THEN 
	   NULL;
  END;
END;

END;
/

