--
-- FOR_CRYSTAL2  (Package Body) 
--
CREATE OR REPLACE PACKAGE BODY MASTER.For_Crystal2 AS
PROCEDURE CR_SF_PRINT(DATE_BEG VARCHAR2, DATE_END VARCHAR2,
  PLAT_ID VARCHAR2,DOG_ID VARCHAR2,
  NUM_SF1 VARCHAR2,NUM_SF2 VARCHAR2,
  CRS IN OUT CURSTYPE) IS
BEGIN
  OPEN CRS FOR
    SELECT * FROM V_SF_PRINT
	  WHERE TO_NUMBER(sf_no) BETWEEN TO_NUMBER(NUM_SF1) AND TO_NUMBER(NUM_SF2);
END;
END;

/

