--
-- PARUSREPL  (Tablespace) 
--
CREATE TABLESPACE PARUSREPL DATAFILE 
  'D:\DB_ORCL\PARUSREPL.ORA' SIZE 900M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M,
  'D:\DB_ORCL\PARUSREPL2.ORA' SIZE 800M AUTOEXTEND ON NEXT 100M MAXSIZE 15974M,
  'D:\DB_ORCL\PARUSREPL3.ORA' SIZE 500M AUTOEXTEND ON NEXT 100M MAXSIZE 500M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL;


