--
-- ENVIRONMENT_GRP  (Table) 
--
CREATE TABLE SNP_REPL.ENVIRONMENT_GRP
(
  ID           NUMBER(10)                       NOT NULL,
  GRP_NAME     VARCHAR2(30 BYTE)                NOT NULL,
  GRP_COMMENT  VARCHAR2(100 BYTE)
);

COMMENT ON TABLE SNP_REPL.ENVIRONMENT_GRP IS 'Группы переменных окружения';

COMMENT ON COLUMN SNP_REPL.ENVIRONMENT_GRP.ID IS 'Группа переменных';

COMMENT ON COLUMN SNP_REPL.ENVIRONMENT_GRP.GRP_NAME IS 'Наименование группы';

COMMENT ON COLUMN SNP_REPL.ENVIRONMENT_GRP.GRP_COMMENT IS 'Описание группы';


