--
-- KLS_EVENTS  (Table) 
--
CREATE TABLE SNP_REPL.KLS_EVENTS
(
  RN    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(100 BYTE)
);

COMMENT ON TABLE SNP_REPL.KLS_EVENTS IS 'Справочник событий (REPL_SESSION,REPL_SESSION_LOG,REPL_STATUS)';

COMMENT ON COLUMN SNP_REPL.KLS_EVENTS.RN IS 'ID';

COMMENT ON COLUMN SNP_REPL.KLS_EVENTS.NAME IS 'Наименование';


