--
-- KLS_STATUS  (Table) 
--
CREATE TABLE SNP_REPL.KLS_STATUS
(
  RN    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(100 BYTE)
);

COMMENT ON TABLE SNP_REPL.KLS_STATUS IS 'Справочник статусов (REPL_CALL*, REPL_ANSW)';

COMMENT ON COLUMN SNP_REPL.KLS_STATUS.RN IS 'ID';

COMMENT ON COLUMN SNP_REPL.KLS_STATUS.NAME IS 'Наименование';


