--
-- LN_TMP  (Table) 
--
CREATE TABLE SNP_REPL.LN_TMP
(
  LN_RN           NUMBER(17),
  OPERATION       VARCHAR2(2 BYTE),
  FACEACC_BEFORE  NUMBER(17),
  FACEACC_AFTER   NUMBER(17)
);

COMMENT ON TABLE SNP_REPL.LN_TMP IS 'Таблица для промежуточного хранения списка лицевых счетов (для пересчета)';

COMMENT ON COLUMN SNP_REPL.LN_TMP.LN_RN IS 'LIABILITYNOTES.RN';

COMMENT ON COLUMN SNP_REPL.LN_TMP.OPERATION IS 'Операция';

COMMENT ON COLUMN SNP_REPL.LN_TMP.FACEACC_BEFORE IS 'LIABILITYNOTES.FACEACC до репликации';

COMMENT ON COLUMN SNP_REPL.LN_TMP.FACEACC_AFTER IS 'LIABILITYNOTES.FACEACC после репликации';


