--
-- REPL_SESSION_LOG  (Table) 
--
CREATE TABLE SNP_REPL.REPL_SESSION_LOG
(
  ID           NUMBER(10)                       NOT NULL,
  SESSION_ID   NUMBER(10)                       NOT NULL,
  STATUS       NUMBER(10)                       DEFAULT 0                     NOT NULL,
  DESCRIPT     VARCHAR2(500 BYTE),
  LOG_TIME     DATE                             NOT NULL,
  MODULE_NAME  VARCHAR2(30 BYTE),
  SITE_RN      NUMBER(17),
  CALL_RN      NUMBER(17),
  PROC_NAME    VARCHAR2(30 BYTE),
  SEND_MAIL    NUMBER(1)                        DEFAULT 1                     NOT NULL
);

COMMENT ON TABLE SNP_REPL.REPL_SESSION_LOG IS 'Журнал сессий';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION_LOG.ID IS 'ID этапа сессии';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION_LOG.SESSION_ID IS 'Сессия';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION_LOG.STATUS IS 'Статус';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION_LOG.DESCRIPT IS 'Описание';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION_LOG.LOG_TIME IS 'Дата записи в журнал';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION_LOG.MODULE_NAME IS 'Модуль приложения';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION_LOG.SITE_RN IS 'Узел, где произошло событие';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION_LOG.CALL_RN IS 'Оператор';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION_LOG.PROC_NAME IS 'Процедура приложения';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION_LOG.SEND_MAIL IS '1-Отсылать по почте';


