--
-- REPL_SESSION  (Table) 
--
CREATE TABLE SNP_REPL.REPL_SESSION
(
  ID             NUMBER(10)                     NOT NULL,
  STATUS         NUMBER(10)                     DEFAULT 0                     NOT NULL,
  DATE_START     DATE                           DEFAULT SYSDATE               NOT NULL,
  DATE_FINISH    DATE,
  DESCRIPT       VARCHAR2(100 BYTE),
  OSUSER_NAME    VARCHAR2(30 BYTE)              NOT NULL,
  TERMINAL_NAME  VARCHAR2(30 BYTE)              NOT NULL,
  APPL_NAME      VARCHAR2(30 BYTE)
);

COMMENT ON TABLE SNP_REPL.REPL_SESSION IS 'Сессии приложений';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION.ID IS 'Сессия';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION.STATUS IS 'Статус';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION.DATE_START IS 'Старт';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION.DATE_FINISH IS 'Финиш';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION.DESCRIPT IS 'Доп.текст';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION.OSUSER_NAME IS 'Пользователь';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION.TERMINAL_NAME IS 'Машина';

COMMENT ON COLUMN SNP_REPL.REPL_SESSION.APPL_NAME IS 'Приложение';


