--
-- REPL_TABLE  (Table) 
--
CREATE TABLE SNP_REPL.REPL_TABLE
(
  RN              NUMBER(17)                    NOT NULL,
  REPL_USERNAME   VARCHAR2(30 BYTE)             NOT NULL,
  REPL_TABLENAME  VARCHAR2(50 BYTE)             NOT NULL,
  NOTE            VARCHAR2(100 BYTE),
  USERNAME        VARCHAR2(30 BYTE),
  TABLENAME       VARCHAR2(50 BYTE),
  RNNAME          VARCHAR2(15 BYTE)             DEFAULT 'RN'                  NOT NULL
);

COMMENT ON TABLE SNP_REPL.REPL_TABLE IS 'Справочник таблиц';

COMMENT ON COLUMN SNP_REPL.REPL_TABLE.RN IS 'REPL_TABLES_RN';

COMMENT ON COLUMN SNP_REPL.REPL_TABLE.REPL_USERNAME IS 'Схема таблицы из таблицы репликации';

COMMENT ON COLUMN SNP_REPL.REPL_TABLE.REPL_TABLENAME IS 'Название таблицы из таблицы репликации';

COMMENT ON COLUMN SNP_REPL.REPL_TABLE.NOTE IS 'Комментарий';

COMMENT ON COLUMN SNP_REPL.REPL_TABLE.USERNAME IS 'Схема таблицы в операторе';

COMMENT ON COLUMN SNP_REPL.REPL_TABLE.TABLENAME IS 'Название таблицы в операторе';

COMMENT ON COLUMN SNP_REPL.REPL_TABLE.RNNAME IS 'Поле RN в операторе';


