--
-- REPL_CALL_OUT_HIST  (Table) 
--
CREATE TABLE SNP_REPL.REPL_CALL_OUT_HIST
(
  RN              NUMBER(17),
  UPDATE_RN       NUMBER(17),
  SITE_SOURCE_RN  NUMBER(17),
  SITE_DEST_RN    NUMBER(17),
  SCHEMA_RN       NUMBER(17),
  SCHEMAROW_RN    NUMBER(17),
  TABLERN         NUMBER(17),
  REPL_RN         NUMBER(17),
  OPERATION       VARCHAR2(1 BYTE),
  MODIFDATE       DATE,
  COUNTER         NUMBER(2),
  STATUS          NUMBER(5),
  SENDDATE        DATE,
  FILENAME        VARCHAR2(30 BYTE),
  SQL1_TEXT       VARCHAR2(4000 BYTE),
  SQL2_TEXT       VARCHAR2(4000 BYTE),
  DATE_EXEC       DATE,
  DATE_HIST       DATE,
  DAY_OF_WEEK     NUMBER(2)
)
PARTITION BY RANGE (DAY_OF_WEEK)
(  
  PARTITION DAY_1 VALUES LESS THAN (2),  
  PARTITION DAY_2 VALUES LESS THAN (3),  
  PARTITION DAY_3 VALUES LESS THAN (4),  
  PARTITION DAY_4 VALUES LESS THAN (5),  
  PARTITION DAY_5 VALUES LESS THAN (6),  
  PARTITION DAY_6 VALUES LESS THAN (7),  
  PARTITION DAY_7 VALUES LESS THAN (8),  
  PARTITION DAY_BAD VALUES LESS THAN (MAXVALUE)
);

COMMENT ON TABLE SNP_REPL.REPL_CALL_OUT_HIST IS 'История исходящих запросов';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.RN IS 'REPL_CALL_OUT_RN';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.UPDATE_RN IS 'UPDATE оператор';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.SITE_SOURCE_RN IS 'Узел-источник';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.SITE_DEST_RN IS 'Узел-назначение';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.SCHEMA_RN IS 'Схема';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.SCHEMAROW_RN IS 'Строка схемы';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.TABLERN IS 'RN таблицы';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.REPL_RN IS 'RN таблицы репликации (UPDATELIST)';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.OPERATION IS 'операция';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.MODIFDATE IS 'Дата операции';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.COUNTER IS 'Счетчик повторов';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.STATUS IS 'Статус (1-успешно, <0-код ошибки)';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.SENDDATE IS 'Дата выгрузки';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.FILENAME IS 'Транспортный файл';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.DATE_EXEC IS 'Дата выполнения оператора на сервере-назначении';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT_HIST.DATE_HIST IS 'Дата переноса в архив';


