--
-- REPL_CALL_OUT  (Table) 
--
CREATE TABLE SNP_REPL.REPL_CALL_OUT
(
  RN              NUMBER(17)                    NOT NULL,
  UPDATE_RN       NUMBER(17),
  SITE_SOURCE_RN  NUMBER(17)                    NOT NULL,
  SITE_DEST_RN    NUMBER(17)                    NOT NULL,
  SCHEMA_RN       NUMBER(17)                    NOT NULL,
  SCHEMAROW_RN    NUMBER(17)                    NOT NULL,
  TABLERN         NUMBER(17)                    NOT NULL,
  REPL_RN         NUMBER(17)                    NOT NULL,
  OPERATION       VARCHAR2(1 BYTE)              NOT NULL,
  MODIFDATE       DATE                          NOT NULL,
  COUNTER         NUMBER(2)                     NOT NULL,
  STATUS          NUMBER(5)                     NOT NULL,
  SENDDATE        DATE,
  FILENAME        VARCHAR2(30 BYTE),
  SQL1_TEXT       VARCHAR2(4000 BYTE)           NOT NULL,
  SQL2_TEXT       VARCHAR2(4000 BYTE)
);

COMMENT ON TABLE SNP_REPL.REPL_CALL_OUT IS 'Буфер исходящих запросов';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT.RN IS 'REPL_CALL_OUT_RN';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT.UPDATE_RN IS 'UPDATE оператор';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT.SITE_SOURCE_RN IS 'Узел-источник';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT.SITE_DEST_RN IS 'Узел-назначение';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT.SCHEMA_RN IS 'Схема';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT.SCHEMAROW_RN IS 'Строка схемы';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT.TABLERN IS 'RN таблицы';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT.REPL_RN IS 'RN таблицы репликации (UPDATELIST)';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT.OPERATION IS 'операция';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT.MODIFDATE IS 'Дата операции';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT.COUNTER IS 'Счетчик повторов';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT.STATUS IS 'Статус (1-успешно, <0-код ошибки)';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT.SENDDATE IS 'Дата выгрузки';

COMMENT ON COLUMN SNP_REPL.REPL_CALL_OUT.FILENAME IS 'Транспортный файл';


