--
-- REPL_INIT  (Table) 
--
CREATE TABLE SNP_REPL.REPL_INIT
(
  RN               NUMBER(17)                   NOT NULL,
  SITE_RN          NUMBER(17)                   NOT NULL,
  IS_CURRENT       NUMBER(1)                    DEFAULT 0                     NOT NULL,
  BOX_IN           VARCHAR2(100 BYTE),
  BOX_OUT          VARCHAR2(100 BYTE),
  EMAIL_ADMIN      VARCHAR2(50 BYTE),
  REPL_SCHEMANAME  VARCHAR2(30 BYTE),
  USE_DBLINK       NUMBER(1)                    DEFAULT 0,
  DBLINK           VARCHAR2(100 BYTE),
  EXP_PATH         VARCHAR2(100 BYTE),
  IMP_PATH         VARCHAR2(100 BYTE),
  REPL_PASSWORD    VARCHAR2(10 BYTE),
  TMP_PATH         VARCHAR2(100 BYTE),
  ZIP_CMD          VARCHAR2(50 BYTE),
  ARH_IN           VARCHAR2(100 BYTE),
  ARH_OUT          VARCHAR2(100 BYTE),
  DBLINK_ERR_EXP   NUMBER(1)                    DEFAULT 0
);

COMMENT ON TABLE SNP_REPL.REPL_INIT IS 'Настройка репликации';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.RN IS 'REPL_INIT_RN';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.SITE_RN IS 'Узел';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.IS_CURRENT IS 'Текущий узел';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.BOX_IN IS 'Входящий каталог';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.BOX_OUT IS 'Исходящий каталог';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.EMAIL_ADMIN IS 'Почтовый адрес Админа';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.REPL_SCHEMANAME IS 'Пользователь репликации';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.USE_DBLINK IS 'Передать через DBLINK';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.DBLINK IS 'DBLINK';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.EXP_PATH IS 'Путь к утилите экспорта';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.IMP_PATH IS 'Путь к утилите импорта';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.REPL_PASSWORD IS 'Пароль к схеме репликации';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.TMP_PATH IS 'Временный каталог';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.ZIP_CMD IS 'Команда на упаковку';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.ARH_IN IS 'Архив входящего каталога';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.ARH_OUT IS 'Архив исходящего каталога';

COMMENT ON COLUMN SNP_REPL.REPL_INIT.DBLINK_ERR_EXP IS 'Выгружать в транспортный файл при ошибке передачи через DBlink';


