--
-- REPL_SCHEMA  (Table) 
--
CREATE TABLE SNP_REPL.REPL_SCHEMA
(
  RN              NUMBER(17)                    NOT NULL,
  SITE_SOURCE_RN  NUMBER(17)                    NOT NULL,
  SITE_DEST_RN    NUMBER(17)                    NOT NULL,
  NAME            VARCHAR2(100 BYTE)            NOT NULL,
  SORTBY          NUMBER(10)                    NOT NULL,
  IS_ACTIVE       NUMBER(1)                     DEFAULT 0                     NOT NULL
);

COMMENT ON TABLE SNP_REPL.REPL_SCHEMA IS 'Схемы репликации';

COMMENT ON COLUMN SNP_REPL.REPL_SCHEMA.RN IS 'REPL_SCHEMA_RN';

COMMENT ON COLUMN SNP_REPL.REPL_SCHEMA.SITE_SOURCE_RN IS 'SNP_REPL_SITE_RN';

COMMENT ON COLUMN SNP_REPL.REPL_SCHEMA.SITE_DEST_RN IS 'SNP_REPL_SITE_RN';

COMMENT ON COLUMN SNP_REPL.REPL_SCHEMA.NAME IS 'Название схемы';

COMMENT ON COLUMN SNP_REPL.REPL_SCHEMA.SORTBY IS 'Порядок репликации';

COMMENT ON COLUMN SNP_REPL.REPL_SCHEMA.IS_ACTIVE IS 'Активная схема';


