--
-- REPL_ANSW  (Table) 
--
CREATE TABLE SNP_REPL.REPL_ANSW
(
  RN              NUMBER(17)                    NOT NULL,
  SITE_SOURCE_RN  NUMBER(17)                    NOT NULL,
  SITE_DEST_RN    NUMBER(17)                    NOT NULL,
  CALL_OUT_RN     NUMBER(17)                    NOT NULL,
  SENDDATE        DATE,
  FILENAME        VARCHAR2(30 BYTE),
  STATUS          NUMBER(5)                     NOT NULL,
  NOTE            VARCHAR2(500 BYTE),
  DATE_LOG        DATE
);

COMMENT ON TABLE SNP_REPL.REPL_ANSW IS 'Буфер ответов';

COMMENT ON COLUMN SNP_REPL.REPL_ANSW.RN IS 'REPL_ANSW_RN';

COMMENT ON COLUMN SNP_REPL.REPL_ANSW.SITE_SOURCE_RN IS 'Узел-источник';

COMMENT ON COLUMN SNP_REPL.REPL_ANSW.SITE_DEST_RN IS 'Узел-назначение';

COMMENT ON COLUMN SNP_REPL.REPL_ANSW.CALL_OUT_RN IS 'Исходящий оператор';

COMMENT ON COLUMN SNP_REPL.REPL_ANSW.SENDDATE IS 'Дата выгрузки';

COMMENT ON COLUMN SNP_REPL.REPL_ANSW.FILENAME IS 'Транспотрный файл';

COMMENT ON COLUMN SNP_REPL.REPL_ANSW.STATUS IS 'Статус (1-успешно, <0 - код ошибки)';

COMMENT ON COLUMN SNP_REPL.REPL_ANSW.NOTE IS 'Сообщение';

COMMENT ON COLUMN SNP_REPL.REPL_ANSW.DATE_LOG IS 'Дата обработки';


