--
-- REPL_CALL  (Table) 
--
CREATE TABLE SNP_REPL.REPL_CALL
(
  RN              NUMBER(17)                    NOT NULL,
  UPDATE_RN       NUMBER(17),
  SITE_SOURCE_RN  NUMBER(17)                    NOT NULL,
  SITE_DEST_RN    NUMBER(17)                    NOT NULL,
  SCHEMA_RN       NUMBER(17)                    NOT NULL,
  SCHEMAROW_RN    NUMBER(17)                    NOT NULL,
  TABLERN         NUMBER(17)                    NOT NULL,
  REPL_RN         NUMBER(17)                    NOT NULL,
  OPERATION       VARCHAR2(1 BYTE)              NOT NULL,
  MODIFDATE       DATE                          NOT NULL,
  COUNTER         NUMBER(2)                     NOT NULL,
  STATUS          NUMBER(5)                     NOT NULL,
  SENDDATE        DATE,
  FILENAME        VARCHAR2(30 BYTE),
  SQL1_TEXT       VARCHAR2(4000 BYTE)           NOT NULL,
  SQL2_TEXT       VARCHAR2(4000 BYTE)
);

COMMENT ON TABLE SNP_REPL.REPL_CALL IS 'Буфер запросов';

COMMENT ON COLUMN SNP_REPL.REPL_CALL.SQL1_TEXT IS 'SQL-запрос (часть 1)';

COMMENT ON COLUMN SNP_REPL.REPL_CALL.SQL2_TEXT IS 'SQL-запрос (часть 2)';

COMMENT ON COLUMN SNP_REPL.REPL_CALL.FILENAME IS 'Транспортный файл';

COMMENT ON COLUMN SNP_REPL.REPL_CALL.COUNTER IS 'Счетчик повторов';

COMMENT ON COLUMN SNP_REPL.REPL_CALL.STATUS IS 'Статус (1-успешно, <0-код ошибки)';

COMMENT ON COLUMN SNP_REPL.REPL_CALL.SENDDATE IS 'Дата выгрузки';

COMMENT ON COLUMN SNP_REPL.REPL_CALL.RN IS 'REPL_CALL_RN';

COMMENT ON COLUMN SNP_REPL.REPL_CALL.UPDATE_RN IS 'UPDATE оператор';

COMMENT ON COLUMN SNP_REPL.REPL_CALL.SITE_SOURCE_RN IS 'Узел-источник';

COMMENT ON COLUMN SNP_REPL.REPL_CALL.SITE_DEST_RN IS 'Узел-назначение';

COMMENT ON COLUMN SNP_REPL.REPL_CALL.SCHEMA_RN IS 'Строка схемы';

COMMENT ON COLUMN SNP_REPL.REPL_CALL.TABLERN IS 'RN таблицы';

COMMENT ON COLUMN SNP_REPL.REPL_CALL.REPL_RN IS 'RN таблицы репликации (UPDATELIST)';

COMMENT ON COLUMN SNP_REPL.REPL_CALL.OPERATION IS 'операция';

COMMENT ON COLUMN SNP_REPL.REPL_CALL.MODIFDATE IS 'Дата операции';


