--
-- SOJ_TMP  (Table) 
--
CREATE TABLE SNP_REPL.SOJ_TMP
(
  SOJ_RN         NUMBER(17)                     NOT NULL,
  OPERATION      VARCHAR2(2 BYTE),
  SUPPLY_BEFORE  NUMBER(17),
  SUPPLY_AFTER   NUMBER(17)
);

COMMENT ON TABLE SNP_REPL.SOJ_TMP IS 'Таблица для промежуточного хранения списка товарных запасов (для пересчета)';

COMMENT ON COLUMN SNP_REPL.SOJ_TMP.SOJ_RN IS 'STOREOPERJOURN.RN';

COMMENT ON COLUMN SNP_REPL.SOJ_TMP.OPERATION IS 'Операция';

COMMENT ON COLUMN SNP_REPL.SOJ_TMP.SUPPLY_BEFORE IS 'STOREOPERJOURN.GOODSSUPLY до репликации';

COMMENT ON COLUMN SNP_REPL.SOJ_TMP.SUPPLY_AFTER IS 'STOREOPERJOURN.GOODSSUPLY после';


