--
-- AGENT_GDPLAN_FOR_ANTON  (Table) 
--
CREATE TABLE MASTER.AGENT_GDPLAN_FOR_ANTON
(
  STAN_ID      NUMBER,
  PROD_NPR_ID  VARCHAR2(5 BYTE),
  VES          NUMBER,
  TARIF        NUMBER,
  PLAT_ID      NUMBER,
  DATE_PLAN    DATE
)
TABLESPACE USERS2
NOCOMPRESS ;


