--
-- APPL_SESSION  (Table) 
--
CREATE TABLE MASTER.APPL_SESSION
(
  SID           NUMBER,
  DATETIME      DATE,
  USERNAME      VARCHAR2(30 BYTE),
  STATUS        VARCHAR2(8 BYTE),
  OSUSER        VARCHAR2(120 BYTE),
  COMPUTER      VARCHAR2(64 BYTE),
  MODULE        VARCHAR2(256 BYTE),
  PROGRAM       VARCHAR2(9 BYTE),
  LOGON_TIME    DATE,
  LAST_CALL_ET  NUMBER
)
TABLESPACE USERS
NOCOMPRESS ;


