--
-- AZC_SYS_COMM  (Table) 
--
CREATE TABLE MASTER.AZC_SYS_COMM
(
  ID        NUMBER                              NOT NULL,
  ID_PAGE   NUMBER,
  ID_FIELD  NUMBER,
  ORDER_    NUMBER(2)
)
TABLESPACE USERS2
NOCOMPRESS ;


