--
-- AZC_TYPE_OPERATION  (Table) 
--
CREATE TABLE MASTER.AZC_TYPE_OPERATION
(
  ID          NUMBER(10)                        NOT NULL,
  NAME        VARCHAR2(50 BYTE),
  KIND_OPER   NUMBER(1),
  PRICE_FLAG  VARCHAR2(1 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.AZC_TYPE_OPERATION.NAME IS 'Вид операции (отгрузка и т.д.)';



