--
-- AZC_TARIF  (Table) 
--
CREATE TABLE MASTER.AZC_TARIF
(
  ID           NUMBER(10),
  AGENT        VARCHAR2(255 BYTE),
  SKLAD_FROM   VARCHAR2(255 BYTE),
  SKLAD_TO     VARCHAR2(255 BYTE),
  DISTANCE     NUMBER(10),
  TARIF_TONN   NUMBER(10,2),
  TARIF_1000V  NUMBER(10,2),
  DATE_        DATE
)
TABLESPACE USERS2
NOCOMPRESS ;


