--
-- AZC_SYS_FIELDS  (Table) 
--
CREATE TABLE MASTER.AZC_SYS_FIELDS
(
  ID        NUMBER                              NOT NULL,
  NAME      VARCHAR2(50 BYTE),
  QUERY_    VARCHAR2(210 BYTE),
  ALIAS_    VARCHAR2(21 BYTE),
  NOTE      VARCHAR2(21 BYTE),
  TYPE_OBJ  VARCHAR2(11 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


