--
-- AZC_OPER_FIELDS  (Table) 
--
CREATE TABLE MASTER.AZC_OPER_FIELDS
(
  ID          NUMBER,
  N_PAGE      NUMBER,
  N_ORDER     NUMBER,
  NAME        VARCHAR2(20 BYTE),
  CAPTION     VARCHAR2(20 BYTE),
  SIZE_FIELD  NUMBER                            DEFAULT 100
)
TABLESPACE USERS2
NOCOMPRESS ;


