--
-- AZC_OPERATION_ARCH  (Table) 
--
CREATE TABLE MASTER.AZC_OPERATION_ARCH
(
  ID             NUMBER(15)                     NOT NULL,
  DATE_OPER      DATE,
  DENCITY        NUMBER(6,4)                    DEFAULT 0,
  VOLUME         NUMBER(10)                     DEFAULT 0,
  VES            NUMBER(12,2)                   DEFAULT 0,
  NOTE           VARCHAR2(100 BYTE),
  TYPE_OPER_ID   NUMBER(10),
  PLACE_SEND_ID  NUMBER(10),
  PROD_ID_NPR    VARCHAR2(5 BYTE),
  SOBSTV_ID      NUMBER(6),
  ORG_STRU_ID    NUMBER(10),
  SUMMA          NUMBER(10,2),
  PRICE          NUMBER(10,2),
  DISCOUNT       NUMBER(5)                      DEFAULT 0,
  DISCOUNT_TYPE  CHAR(17 BYTE),
  DATE_INTO      DATE                           DEFAULT SYSDATE
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.AZC_OPERATION_ARCH IS 'Архив AZC_operation_arch';

COMMENT ON COLUMN MASTER.AZC_OPERATION_ARCH.ID IS 'ID операции';

COMMENT ON COLUMN MASTER.AZC_OPERATION_ARCH.DATE_OPER IS 'Дата операции';

COMMENT ON COLUMN MASTER.AZC_OPERATION_ARCH.DENCITY IS 'Плотность подукта';

COMMENT ON COLUMN MASTER.AZC_OPERATION_ARCH.VOLUME IS 'Объем продукта';

COMMENT ON COLUMN MASTER.AZC_OPERATION_ARCH.VES IS 'Вес продукиа';

COMMENT ON COLUMN MASTER.AZC_OPERATION_ARCH.NOTE IS 'Примечание';

COMMENT ON COLUMN MASTER.AZC_OPERATION_ARCH.ORG_STRU_ID IS 'ID ОСЕ';



