--
-- AZC_FROM_PARUS  (Table) 
--
CREATE TABLE MASTER.AZC_FROM_PARUS
(
  ID             NUMBER(10)                     NOT NULL,
  OSUSER_NAME    VARCHAR2(30 BYTE),
  TERMINAL_NAME  VARCHAR2(30 BYTE),
  NNOMEN         NUMBER(17),
  SNOMEN         VARCHAR2(20 BYTE),
  NSTORE         NUMBER(17),
  SSTORE         VARCHAR2(20 BYTE),
  REALIZ_ALL     NUMBER(20,3)                   DEFAULT 0,
  REALIZ_AZC     NUMBER(20,3)                   DEFAULT 0,
  OSTATOK        NUMBER(20,3)                   DEFAULT 0,
  IS_AZC         NUMBER(1)                      DEFAULT 0,
  REALIZ_AVG     NUMBER(20,3)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.AZC_FROM_PARUS IS 'Реализация из Паруса';

COMMENT ON COLUMN MASTER.AZC_FROM_PARUS.ID IS 'Реализация из Паруса';

COMMENT ON COLUMN MASTER.AZC_FROM_PARUS.OSUSER_NAME IS 'Пользователь';

COMMENT ON COLUMN MASTER.AZC_FROM_PARUS.TERMINAL_NAME IS 'Терминал';

COMMENT ON COLUMN MASTER.AZC_FROM_PARUS.NNOMEN IS 'Продукт';

COMMENT ON COLUMN MASTER.AZC_FROM_PARUS.SNOMEN IS 'Продукт';

COMMENT ON COLUMN MASTER.AZC_FROM_PARUS.NSTORE IS 'Склад';

COMMENT ON COLUMN MASTER.AZC_FROM_PARUS.SSTORE IS 'Склад';

COMMENT ON COLUMN MASTER.AZC_FROM_PARUS.REALIZ_ALL IS 'Реализовано всего';

COMMENT ON COLUMN MASTER.AZC_FROM_PARUS.REALIZ_AZC IS 'Реализовано с АЗС';

COMMENT ON COLUMN MASTER.AZC_FROM_PARUS.OSTATOK IS 'Остаток';

COMMENT ON COLUMN MASTER.AZC_FROM_PARUS.IS_AZC IS 'Признак АЗС';

COMMENT ON COLUMN MASTER.AZC_FROM_PARUS.REALIZ_AVG IS 'Средневная реализация';



