--
-- AZC_GOOD_IN_WAY  (Table) 
--
CREATE TABLE MASTER.AZC_GOOD_IN_WAY
(
  DENCITY        NUMBER(6,4)                    DEFAULT 0,
  ID             NUMBER(10)                     NOT NULL,
  NOTE           VARCHAR2(100 BYTE),
  VES            NUMBER(10)                     DEFAULT 0,
  DATE_OPER      DATE,
  VOLUME         NUMBER(10)                     DEFAULT 0,
  PROD_ID_NPR    VARCHAR2(5 BYTE),
  ORG_STRU_ID    NUMBER(10),
  PLACE_SEND_ID  NUMBER(10),
  PREDPR_ID      NUMBER(6),
  DATE_INTO      DATE                           DEFAULT SYSDATE
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.AZC_GOOD_IN_WAY IS 'Груз в пути';

COMMENT ON COLUMN MASTER.AZC_GOOD_IN_WAY.DENCITY IS 'плотность';

COMMENT ON COLUMN MASTER.AZC_GOOD_IN_WAY.VES IS 'груз в пути (кг)';

COMMENT ON COLUMN MASTER.AZC_GOOD_IN_WAY.DATE_OPER IS 'Дата';

COMMENT ON COLUMN MASTER.AZC_GOOD_IN_WAY.VOLUME IS 'груз в пути (л)';

COMMENT ON COLUMN MASTER.AZC_GOOD_IN_WAY.ORG_STRU_ID IS 'ID ОСЕ';



