--
-- AZC_OPER_MAIN  (Table) 
--
CREATE TABLE MASTER.AZC_OPER_MAIN
(
  ID    NUMBER                                  NOT NULL,
  NAME  VARCHAR2(20 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.AZC_OPER_MAIN.ID IS 'ID закладки';



