--
-- AZS_REPORTS_TMP  (Table) 
--
CREATE TABLE MASTER.AZS_REPORTS_TMP
(
  TERMINAL_NAME  VARCHAR2(30 BYTE),
  OSUSER_NAME    VARCHAR2(30 BYTE),
  TYPE_OPER_ID   NUMBER(10),
  ORG_STRU_ID    NUMBER(10),
  PROD_ID_NPR    NUMBER(10),
  OPER_DAY       DATE,
  PRICE          NUMBER(20,3)                   DEFAULT 0,
  VOLUME         NUMBER(20,3)                   DEFAULT 0,
  MASSA          NUMBER(20,3)                   DEFAULT 0,
  SUMMA          NUMBER(20,3)                   DEFAULT 0,
  DISCOUNT       NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


