--
-- BILL_POS_ROW  (Table) 
--
CREATE TABLE MASTER.BILL_POS_ROW
(
  NOM_DOK      NUMBER(7),
  BILL_POS_ID  NUMBER(7),
  VES          NUMBER(15,6)                     DEFAULT 0,
  CENA_BN      NUMBER(16,6)                     DEFAULT 0,
  CENA         NUMBER(16,6)                     DEFAULT 0,
  SUMMA_BN     NUMBER(20,6)                     DEFAULT 0,
  SUMMA_AKCIZ  NUMBER(20,6)                     DEFAULT 0,
  SUMMA_NDS20  NUMBER(20,6)                     DEFAULT 0,
  SUMMA        NUMBER(20,6)                     DEFAULT 0,
  PROD_ID_NPR  VARCHAR2(5 BYTE),
  NPP          NUMBER(10)                       DEFAULT 0
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.BILL_POS_ROW.NOM_DOK IS 'ID СФ';

COMMENT ON COLUMN MASTER.BILL_POS_ROW.BILL_POS_ID IS '№ позиции';

COMMENT ON COLUMN MASTER.BILL_POS_ROW.VES IS 'Вес';

COMMENT ON COLUMN MASTER.BILL_POS_ROW.CENA_BN IS 'Цена без налогов';

COMMENT ON COLUMN MASTER.BILL_POS_ROW.CENA IS 'Отпускная цена';

COMMENT ON COLUMN MASTER.BILL_POS_ROW.SUMMA_BN IS 'Сумма без налогов';

COMMENT ON COLUMN MASTER.BILL_POS_ROW.SUMMA_AKCIZ IS 'Акциз';

COMMENT ON COLUMN MASTER.BILL_POS_ROW.SUMMA_NDS20 IS 'НДС';

COMMENT ON COLUMN MASTER.BILL_POS_ROW.SUMMA IS 'Сумма с налогами';

COMMENT ON COLUMN MASTER.BILL_POS_ROW.PROD_ID_NPR IS 'Продукт';



