--
-- BILLS_PREPAY  (Table) 
--
CREATE TABLE MASTER.BILLS_PREPAY
(
  NOM_DOK          NUMBER(10)                   NOT NULL,
  NOM_SF           NUMBER(10),
  PROD_ID_NPR      VARCHAR2(5 BYTE),
  DATE_VYP_SF      DATE,
  DATE_KVIT        DATE,
  DATE_BUXG        DATE,
  DATE_MOS         DATE,
  DATE_OTGR        DATE,
  SVED_NUM         NUMBER(10),
  NUM_5_DAY        NUMBER(1),
  SUMMA_DOK        NUMBER(15,2)                 DEFAULT 0,
  SUMMA_PROD       NUMBER(15,2)                 DEFAULT 0,
  SUMMA_PROD_NDS   NUMBER(15,2)                 DEFAULT 0,
  SUMMA_AKCIZ      NUMBER(15,2)                 DEFAULT 0,
  SUMMA_GSM        NUMBER(15,2)                 DEFAULT 0,
  SUMMA_TARIF      NUMBER(15,2)                 DEFAULT 0,
  SUMMA_TARIF_NDS  NUMBER(15,2)                 DEFAULT 0,
  SUMMA_VOZN       NUMBER(15,2)                 DEFAULT 0,
  SUMMA_VOZN_NDS   NUMBER(15,2)                 DEFAULT 0,
  SUMMA_STRAH      NUMBER(15,2)                 DEFAULT 0,
  NOM_ZD           VARCHAR2(12 BYTE),
  OWNER_ID         NUMBER(6),
  IS_AGENT         NUMBER(1),
  DOG_ID           NUMBER(10),
  USL_NUMBER       NUMBER(3),
  KOL_DN           NUMBER(5)                    DEFAULT 0,
  LUK_DOG_ID       NUMBER(10),
  LUK_USL_NUMBER   NUMBER(3),
  LUK_SUMMA_DOK    NUMBER(15,2),
  LUK_NDS_DOK      NUMBER(15,2),
  LUK_KOL_DN       NUMBER(15,2),
  SNP_DOG_ID       NUMBER(10),
  SNP_USL_NUMBER   NUMBER(3),
  SNP_KOL_DN       NUMBER(15,2),
  NAZN_OTG_ID      NUMBER(2)                    DEFAULT 1
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.BILLS_PREPAY IS 'Счета на предоплату';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.NOM_DOK IS 'Счет на предоплату';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.NOM_SF IS 'N счета на предоплату';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.DATE_VYP_SF IS 'Дата выписки счета';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.DATE_KVIT IS 'Дата квитанции';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.DATE_BUXG IS 'Дата бухгалтерии';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.DATE_MOS IS 'Дата пятидневки';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.DATE_OTGR IS 'Дата сведения';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.SVED_NUM IS 'N сведения';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.NUM_5_DAY IS 'N пятидневки';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.SUMMA_DOK IS 'Сумма счета';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.SUMMA_PROD IS 'Сумма за продукт (вкл.акциз и НДС)';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.SUMMA_PROD_NDS IS 'НДС за продукт';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.SUMMA_AKCIZ IS 'Акциз';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.SUMMA_GSM IS 'ГСМ';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.SUMMA_TARIF IS 'Тариф (вкл.НДС)';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.SUMMA_TARIF_NDS IS 'НДС за тариф';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.SUMMA_VOZN IS 'Вознаграждение (вкл.НДС)';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.SUMMA_VOZN_NDS IS 'НДС за вознаграждение';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.SUMMA_STRAH IS 'Страхование';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.IS_AGENT IS 'Группа договора';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.KOL_DN IS 'Отсрочка';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.LUK_SUMMA_DOK IS 'Сумма по счету от ЛУКОЙЛ''а';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.LUK_NDS_DOK IS 'НДС по счету от ЛУКОЙЛ''а';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.LUK_KOL_DN IS 'Отсрочка по счету от ЛУКОЙЛ''а';

COMMENT ON COLUMN MASTER.BILLS_PREPAY.SNP_KOL_DN IS 'Отсрочка по счету НПО';



