--
-- BILLS_PRIMARY  (Table) 
--
CREATE TABLE MASTER.BILLS_PRIMARY
(
  ID            NUMBER(10)                      NOT NULL,
  BEGIN_DATE    DATE,
  END_DATE      DATE,
  PRIMARY_APPL  VARCHAR2(10 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.BILLS_PRIMARY IS 'Таблица первичных систем, в которых выставлялись счета-фактуры от ЛУКОЙЛ''а';

COMMENT ON COLUMN MASTER.BILLS_PRIMARY.ID IS 'Период выставления счетов';

COMMENT ON COLUMN MASTER.BILLS_PRIMARY.BEGIN_DATE IS 'С даты';

COMMENT ON COLUMN MASTER.BILLS_PRIMARY.END_DATE IS 'По дату';

COMMENT ON COLUMN MASTER.BILLS_PRIMARY.PRIMARY_APPL IS 'Первичная система';



