--
-- BILL_POS_PREPAY  (Table) 
--
CREATE TABLE MASTER.BILL_POS_PREPAY
(
  NOM_DOK             NUMBER(10)                NOT NULL,
  BILL_POS_PREPAY_ID  NUMBER(10)                NOT NULL,
  VES                 NUMBER(15,6)              DEFAULT 0,
  CENA_BN             NUMBER(15,6)              DEFAULT 0,
  CENA                NUMBER(15,6)              DEFAULT 0,
  SUMMA_BN            NUMBER(20,6)              DEFAULT 0,
  SUMMA_AKCIZ         NUMBER(20,6)              DEFAULT 0,
  SUMMA_NDS20         NUMBER(20,6)              DEFAULT 0,
  SUMMA_GSM25         NUMBER(20,6)              DEFAULT 0,
  SUMMA               NUMBER(20,6)              DEFAULT 0,
  DATE_REALIZ         DATE,
  PROD_ID_NPR         VARCHAR2(5 BYTE),
  OWNERSHIP_ID        NUMBER(3),
  IS_AGENT            NUMBER(1),
  IS_LUK              NUMBER(1)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.BILL_POS_PREPAY.NOM_DOK IS 'Счет на предоплату';

COMMENT ON COLUMN MASTER.BILL_POS_PREPAY.BILL_POS_PREPAY_ID IS 'Позиция счета на предоплату';

COMMENT ON COLUMN MASTER.BILL_POS_PREPAY.VES IS 'Вес';

COMMENT ON COLUMN MASTER.BILL_POS_PREPAY.CENA_BN IS 'Цена без налогов';

COMMENT ON COLUMN MASTER.BILL_POS_PREPAY.CENA IS 'Отпускная цена';

COMMENT ON COLUMN MASTER.BILL_POS_PREPAY.SUMMA_BN IS 'Сумма без налогов';

COMMENT ON COLUMN MASTER.BILL_POS_PREPAY.SUMMA_AKCIZ IS 'Акциз';

COMMENT ON COLUMN MASTER.BILL_POS_PREPAY.SUMMA_NDS20 IS 'НДС';

COMMENT ON COLUMN MASTER.BILL_POS_PREPAY.SUMMA_GSM25 IS 'ГСМ';

COMMENT ON COLUMN MASTER.BILL_POS_PREPAY.SUMMA IS 'Сумма с налогами';

COMMENT ON COLUMN MASTER.BILL_POS_PREPAY.DATE_REALIZ IS 'Дата реализации';

COMMENT ON COLUMN MASTER.BILL_POS_PREPAY.IS_AGENT IS 'Группа договоров';

COMMENT ON COLUMN MASTER.BILL_POS_PREPAY.IS_LUK IS 'Позиция счета от ЛУКОЙЛ''а';



