--
-- CHAINED_ROWS  (Table) 
--
CREATE TABLE MASTER.CHAINED_ROWS
(
  OWNER_NAME         VARCHAR2(30 BYTE),
  TABLE_NAME         VARCHAR2(30 BYTE),
  CLUSTER_NAME       VARCHAR2(30 BYTE),
  PARTITION_NAME     VARCHAR2(30 BYTE),
  SUBPARTITION_NAME  VARCHAR2(30 BYTE),
  HEAD_ROWID         ROWID,
  ANALYZE_TIMESTAMP  DATE
)
TABLESPACE USERS2
NOCOMPRESS ;


