--
-- DIS_DOCS_  (Table) 
--
CREATE TABLE MASTER.DIS_DOCS_
(
  DOCUMENT_ID    NUMBER(10)                     NOT NULL,
  OWNER          VARCHAR2(30 BYTE),
  DOCUMENT_NAME  VARCHAR2(254 BYTE),
  COMMENTS       VARCHAR2(254 BYTE),
  CREATE_DATE    DATE,
  MODIFIED_DATE  DATE,
  MODIFIED_BY    VARCHAR2(30 BYTE),
  DOC_LENGTH     NUMBER(22),
  DOCUMENT       LONG RAW,
  BATCH          NUMBER(1)
)
TABLESPACE USERS2
NOCOMPRESS ;


