--
-- DOC_STREAM_STAGES  (Table) 
--
CREATE TABLE MASTER.DOC_STREAM_STAGES
(
  ID                NUMBER(10)                  NOT NULL,
  STREAM_ID         NUMBER(10),
  TABLE_TAG         VARCHAR2(50 BYTE),
  MASTER_ID         NUMBER(10),
  MASTER_CONDITION  VARCHAR2(100 BYTE),
  NEXT_ID           NUMBER(10),
  NEXT_CONDITION    VARCHAR2(100 BYTE),
  TITLE_MASK        VARCHAR2(100 BYTE),
  CONDITION         VARCHAR2(100 BYTE),
  RIGHT_ID          VARCHAR2(20 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.DOC_STREAM_STAGES IS 'Этапы потока документов';

COMMENT ON COLUMN MASTER.DOC_STREAM_STAGES.ID IS 'ID документа в потоке';

COMMENT ON COLUMN MASTER.DOC_STREAM_STAGES.STREAM_ID IS 'ID потока';

COMMENT ON COLUMN MASTER.DOC_STREAM_STAGES.TABLE_TAG IS 'ТЕГ документа (MASTER_KLS_STRUCTURE)';

COMMENT ON COLUMN MASTER.DOC_STREAM_STAGES.MASTER_ID IS 'Родительский документ';

COMMENT ON COLUMN MASTER.DOC_STREAM_STAGES.MASTER_CONDITION IS 'Условие поиска родительского док-та';

COMMENT ON COLUMN MASTER.DOC_STREAM_STAGES.NEXT_ID IS 'Дочерний документ';

COMMENT ON COLUMN MASTER.DOC_STREAM_STAGES.NEXT_CONDITION IS 'Условие поиска дочернего документа';

COMMENT ON COLUMN MASTER.DOC_STREAM_STAGES.TITLE_MASK IS 'Шаблон заголовка, отображаемый в форме';

COMMENT ON COLUMN MASTER.DOC_STREAM_STAGES.CONDITION IS 'Условие для идентификации текущего документа';

COMMENT ON COLUMN MASTER.DOC_STREAM_STAGES.RIGHT_ID IS 'Право на просмотр';



