--
-- DOC_STREAM  (Table) 
--
CREATE TABLE MASTER.DOC_STREAM
(
  ID    NUMBER(10)                              NOT NULL,
  TAG   VARCHAR2(10 BYTE),
  NAME  VARCHAR2(50 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.DOC_STREAM IS 'Потоки документов';

COMMENT ON COLUMN MASTER.DOC_STREAM.ID IS 'Потоки документов';

COMMENT ON COLUMN MASTER.DOC_STREAM.TAG IS 'Тег потока';

COMMENT ON COLUMN MASTER.DOC_STREAM.NAME IS 'Наименование';



