--
-- ENVIRONMENT  (Table) 
--
CREATE TABLE MASTER.ENVIRONMENT
(
  ID            NUMBER(10)                      NOT NULL,
  ENV_NAME      VARCHAR2(30 BYTE),
  ENV_VALUE     VARCHAR2(200 BYTE),
  ENV_COMMENT   VARCHAR2(100 BYTE),
  SOURCESQL     VARCHAR2(200 BYTE),
  ENV_TYPES_ID  NUMBER(10),
  ENV_GRP_ID    NUMBER(10),
  MASTER_ID     NUMBER(10),
  NETUSER       VARCHAR2(50 BYTE),
  APPL_NAME     VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.ENVIRONMENT IS 'Переменные окружения';

COMMENT ON COLUMN MASTER.ENVIRONMENT.ID IS 'Переменная окружения';

COMMENT ON COLUMN MASTER.ENVIRONMENT.ENV_NAME IS 'Наименование (идентификатор)';

COMMENT ON COLUMN MASTER.ENVIRONMENT.ENV_VALUE IS 'Значение переменной';

COMMENT ON COLUMN MASTER.ENVIRONMENT.ENV_COMMENT IS 'Наименование (комментарий)';

COMMENT ON COLUMN MASTER.ENVIRONMENT.SOURCESQL IS 'SQL-запрос возможных значений';

COMMENT ON COLUMN MASTER.ENVIRONMENT.ENV_TYPES_ID IS 'Тип переменной';

COMMENT ON COLUMN MASTER.ENVIRONMENT.ENV_GRP_ID IS 'Группа переменных';

COMMENT ON COLUMN MASTER.ENVIRONMENT.MASTER_ID IS 'Переменная окружения';

COMMENT ON COLUMN MASTER.ENVIRONMENT.NETUSER IS 'Сетевое имя пользователя';

COMMENT ON COLUMN MASTER.ENVIRONMENT.APPL_NAME IS 'Приложение';



