--
-- ENVIRONMENT_GRP  (Table) 
--
CREATE TABLE MASTER.ENVIRONMENT_GRP
(
  ID           NUMBER(10)                       NOT NULL,
  GRP_NAME     VARCHAR2(30 BYTE),
  GRP_COMMENT  VARCHAR2(100 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.ENVIRONMENT_GRP IS 'Группы переменных окружения';

COMMENT ON COLUMN MASTER.ENVIRONMENT_GRP.ID IS 'Группа переменных';

COMMENT ON COLUMN MASTER.ENVIRONMENT_GRP.GRP_NAME IS 'Наименование группы';

COMMENT ON COLUMN MASTER.ENVIRONMENT_GRP.GRP_COMMENT IS 'Описание группы';



