--
-- EUL_BA_OBJ_LINKS  (Table) 
--
CREATE TABLE MASTER.EUL_BA_OBJ_LINKS
(
  BOL_ID        NUMBER(10)                      NOT NULL,
  BOL_BA_ID     NUMBER(10),
  BOL_OBJ_ID    NUMBER(10),
  BOL_SEQUENCE  NUMBER(22),
  NOTM          NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


