/* This object may not be sorted properly in the script due to cirular references. */
--
-- EUL_EXPRESSIONS  (Table) 
--
CREATE TABLE MASTER.EUL_EXPRESSIONS
(
  EXP_ID              NUMBER(10)                NOT NULL,
  EXP_TYPE            VARCHAR2(10 BYTE),
  EXP_NAME            VARCHAR2(100 BYTE),
  EXP_DESCRIPTION     VARCHAR2(240 BYTE),
  EXP_FORMULA1        VARCHAR2(250 BYTE),
  EXP_DATA_TYPE       NUMBER(2),
  EXP_SEQUENCE        NUMBER(22),
  ITE_DOM_ID          NUMBER(10),
  ITE_FORMAT_MASK     VARCHAR2(100 BYTE),
  ITE_MAX_DATA_WIDTH  NUMBER(22),
  ITE_OBJ_ID          NUMBER(10),
  ITE_EU_ID           NUMBER(10),
  ITE_ALIGNMENT       NUMBER(2),
  ITE_WORD_WRAP       NUMBER(1),
  ITE_MAX_DISP_WIDTH  NUMBER(22),
  PAR_DEFAULT_VALUE   VARCHAR2(240 BYTE),
  PAR_EXP_ID_ASSOC    NUMBER(10),
  PAR_PROMPT          VARCHAR2(100 BYTE),
  PAR_MULTIPLE_VALS   NUMBER(1),
  IT_SUMMARY_COUNT    NUMBER(22),
  IT_DISP_NULL_VAL    VARCHAR2(100 BYTE),
  IT_EXP_ID_DESC_FOR  NUMBER(10),
  IT_FUN_ID           NUMBER(10),
  IT_HEADING          VARCHAR2(240 BYTE),
  IT_HIDDEN           NUMBER(1),
  IT_KEY_ID_DESC_FOR  NUMBER(10),
  IT_ORD_POSITION     NUMBER(22),
  IT_ORD_DIRECTION    NUMBER(2),
  IT_PLACEMENT        NUMBER(2),
  IT_USER_DEF_FMT     VARCHAR2(100 BYTE),
  IT_CASE_STORAGE     NUMBER(2),
  IT_CASE_DISPLAY     NUMBER(2),
  IT_EXT_COLUMN       VARCHAR2(64 BYTE),
  CI_IT_ID            NUMBER(10),
  CI_AGGREGATE_ITEM   NUMBER(1),
  CO_NULLABLE         NUMBER(1),
  P_CASE_SENSITIVE    NUMBER(1),
  JP_KEY_ID           NUMBER(10),
  NJP_OBJ_ID_OWNER    NUMBER(10),
  NJP_EU_ID           NUMBER(10),
  FIL_MANDATORY       NUMBER(1),
  FIL_EXT_FILTER      VARCHAR2(64 BYTE),
  NOTM                NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


