--
-- EUL_ACCESS_PRIVS  (Table) 
--
CREATE TABLE MASTER.EUL_ACCESS_PRIVS
(
  AP_ID           NUMBER(10)                    NOT NULL,
  AP_TYPE         VARCHAR2(10 BYTE),
  AP_EU_ID        NUMBER(10),
  GP_APP_ID       NUMBER(10),
  GBA_BA_ID       NUMBER(10),
  GBA_ADMIN_PRIV  NUMBER(1),
  NOTM            NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


