--
-- EUL_BUSINESS_AREAS  (Table) 
--
CREATE TABLE MASTER.EUL_BUSINESS_AREAS
(
  BA_ID           NUMBER(10)                    NOT NULL,
  BA_NAME         VARCHAR2(100 BYTE),
  BA_DESCRIPTION  VARCHAR2(240 BYTE),
  NOTM            NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


