--
-- EUL_SUMMARY_OBJS  (Table) 
--
CREATE TABLE MASTER.EUL_SUMMARY_OBJS
(
  SUMO_ID             NUMBER(10)                NOT NULL,
  SUMO_TYPE           VARCHAR2(10 BYTE),
  SUMO_INTERNAL       NUMBER(1),
  SUMO_ITEM_DELETED   NUMBER(1),
  SUMO_ITEM_MODIFIED  NUMBER(1),
  SUMO_JOIN_STATE     NUMBER(1),
  SUMO_VALIDITY       NUMBER(1),
  SUMO_EXT_OBJECT     VARCHAR2(64 BYTE),
  SUMO_EXT_OWNER      VARCHAR2(64 BYTE),
  SUMO_EXT_DB_LINK    VARCHAR2(64 BYTE),
  SBO_SRS_ID          NUMBER(10),
  SBO_NAME            VARCHAR2(100 BYTE),
  SBO_DESCRIPTION     VARCHAR2(240 BYTE),
  SBO_MAX_ITEM_COMB   NUMBER(22),
  SDO_SBO_ID          NUMBER(10),
  SDO_NUM_JOINS       NUMBER(22),
  SDO_NUM_USGS        NUMBER(22),
  SDO_NUM_AXIS_ITEMS  NUMBER(22),
  SDO_NUM_ROWS        NUMBER(22),
  SDO_BITMAP_POS      NUMBER(22),
  SDO_OBJECT_SQL1     VARCHAR2(250 BYTE),
  SDO_OBJECT_SQL2     VARCHAR2(250 BYTE),
  SDO_OBJECT_SQL3     VARCHAR2(250 BYTE),
  SDO_LAST_REFRESH    DATE,
  SDO_STATE           NUMBER(2),
  SDO_SVR_ERR_CODE    NUMBER(22),
  SDO_SVR_ERR_TEXT    VARCHAR2(240 BYTE),
  NMSDO_SDO_ID        NUMBER(10),
  MSDO_TABLE_NAME     VARCHAR2(64 BYTE),
  MSDO_TABLE_OWNER    VARCHAR2(64 BYTE),
  MSDO_DATABASE_LINK  VARCHAR2(64 BYTE),
  MSDO_COMMIT_SIZE    NUMBER(22),
  NOTM                NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


