--
-- EUL_BR_RUNS  (Table) 
--
CREATE TABLE MASTER.EUL_BR_RUNS
(
  BRR_ID             NUMBER(10)                 NOT NULL,
  BRR_BR_ID          NUMBER(10),
  BRR_RUN_NUMBER     NUMBER(22),
  BRR_STATE          NUMBER(2),
  BRR_RUN_DATE       DATE,
  BRR_SVR_ERR_CODE   NUMBER(22),
  BRR_SVR_ERR_TEXT   VARCHAR2(240 BYTE),
  BRR_ACT_ELAP_TIME  NUMBER(22),
  NOTM               NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


