--
-- EUL_FUNCTIONS  (Table) 
--
CREATE TABLE MASTER.EUL_FUNCTIONS
(
  FUN_ID              NUMBER(10)                NOT NULL,
  FUN_NAME            VARCHAR2(100 BYTE),
  FUN_DESCRIPTION_S   VARCHAR2(240 BYTE),
  FUN_DESCRIPTION_MN  NUMBER(10),
  FUN_FUNCTION_TYPE   NUMBER(2),
  FUN_HIDDEN          NUMBER(1),
  FUN_DATA_TYPE       NUMBER(2),
  FUN_AVAILABLE       NUMBER(1),
  FUN_MAXIMUM_ARGS    NUMBER(22),
  FUN_MINIMUM_ARGS    NUMBER(22),
  FUN_BUILT_IN        NUMBER(1),
  FUN_PACKAGE         VARCHAR2(64 BYTE),
  FUN_OWNER           VARCHAR2(64 BYTE),
  FUN_DATABASE_LINK   VARCHAR2(64 BYTE),
  FUN_DISPLAY_NAME    VARCHAR2(100 BYTE),
  NOTM                NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


