--
-- EUL_FUN_CATEGORIES  (Table) 
--
CREATE TABLE MASTER.EUL_FUN_CATEGORIES
(
  FC_ID              NUMBER(10)                 NOT NULL,
  FC_NAME_S          VARCHAR2(100 BYTE),
  FC_NAME_MN         NUMBER(10),
  FC_DESCRIPTION_S   VARCHAR2(240 BYTE),
  FC_DESCRIPTION_MN  NUMBER(10),
  NOTM               NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


