--
-- EUL_FUN_ARGUMENTS  (Table) 
--
CREATE TABLE MASTER.EUL_FUN_ARGUMENTS
(
  FA_ID              NUMBER(10)                 NOT NULL,
  FA_NAME_S          VARCHAR2(100 BYTE),
  FA_DESCRIPTION_MN  NUMBER(10),
  FA_NAME_MN         NUMBER(10),
  FA_DESCRIPTION_S   VARCHAR2(240 BYTE),
  FA_DATA_TYPE       NUMBER(2),
  FA_OPTIONAL        NUMBER(1),
  FA_POSITION        NUMBER(22),
  FA_FUN_ID          NUMBER(10),
  NOTM               NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


