--
-- EUL_GATEWAYS  (Table) 
--
CREATE TABLE MASTER.EUL_GATEWAYS
(
  GW_ID              NUMBER(10)                 NOT NULL,
  GW_TYPE            VARCHAR2(10 BYTE),
  GW_GATEWAY_NAME    VARCHAR2(100 BYTE),
  GW_PRODUCT_NAME    VARCHAR2(100 BYTE),
  GW_DESCRIPTION     VARCHAR2(240 BYTE),
  EGW_VERSION        VARCHAR2(30 BYTE),
  EGW_DATABASE_LINK  VARCHAR2(64 BYTE),
  EGW_SCHEMA         VARCHAR2(64 BYTE),
  EGW_SQL_PARADIGM   VARCHAR2(10 BYTE),
  NOTM               NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


