--
-- EUL_VERSIONS  (Table) 
--
CREATE TABLE MASTER.EUL_VERSIONS
(
  VER_EUL_TIMESTAMP  VARCHAR2(30 BYTE),
  VER_MIN_CODE_VER   VARCHAR2(30 BYTE),
  VER_RELEASE        VARCHAR2(30 BYTE),
  VER_SA             NUMBER(22),
  VER_NAME           VARCHAR2(100 BYTE),
  VER_DESCRIPTION    VARCHAR2(240 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


