--
-- EUL_BATCH_SHEETS  (Table) 
--
CREATE TABLE MASTER.EUL_BATCH_SHEETS
(
  BS_ID          NUMBER(10)                     NOT NULL,
  BS_BR_ID       NUMBER(10),
  BS_SHEET_NAME  VARCHAR2(240 BYTE),
  BS_SHEET_ID    VARCHAR2(240 BYTE),
  NOTM           NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


