--
-- EUL_HI_NODES  (Table) 
--
CREATE TABLE MASTER.EUL_HI_NODES
(
  HN_ID           NUMBER(10)                    NOT NULL,
  HN_NAME         VARCHAR2(100 BYTE),
  HN_DESCRIPTION  VARCHAR2(240 BYTE),
  HN_HI_ID        NUMBER(10),
  HN_EXT_NODE     VARCHAR2(64 BYTE),
  NOTM            NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


