--
-- EUL_FUN_FC_LINKS  (Table) 
--
CREATE TABLE MASTER.EUL_FUN_FC_LINKS
(
  FFL_ID      NUMBER(10)                        NOT NULL,
  FFL_FUN_ID  NUMBER(10),
  FFL_FC_ID   NUMBER(10),
  NOTM        NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


