--
-- EUL_BATCH_QUERIES  (Table) 
--
CREATE TABLE MASTER.EUL_BATCH_QUERIES
(
  BQ_ID            NUMBER(10)                   NOT NULL,
  BQ_BS_ID         NUMBER(10),
  BQ_QUERY_ID      VARCHAR2(240 BYTE),
  BQ_RESULT_SQL_1  VARCHAR2(250 BYTE),
  BQ_RESULT_SQL_2  VARCHAR2(250 BYTE),
  BQ_RESULT_SQL_3  VARCHAR2(250 BYTE),
  BQ_RESULT_SQL_4  VARCHAR2(250 BYTE),
  NOTM             NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


