--
-- EUL_JOIN_COMBS  (Table) 
--
CREATE TABLE MASTER.EUL_JOIN_COMBS
(
  JC_ID    NUMBER(10)                           NOT NULL,
  JC_TYPE  VARCHAR2(10 BYTE),
  NOTM     NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


