--
-- EUL_FREQ_UNITS  (Table) 
--
CREATE TABLE MASTER.EUL_FREQ_UNITS
(
  RFU_ID              NUMBER(10)                NOT NULL,
  RFU_NAME_MN         NUMBER(10),
  RFU_SQL_EXPRESSION  VARCHAR2(240 BYTE),
  RFU_SEQUENCE        NUMBER(22),
  NOTM                NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


