--
-- EUL_OBJ_DEPS  (Table) 
--
CREATE TABLE MASTER.EUL_OBJ_DEPS
(
  OD_ID           NUMBER(10)                    NOT NULL,
  OD_OBJ_ID_FROM  NUMBER(10),
  OD_OBJ_ID_TO    NUMBER(10),
  NOTM            NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


