--
-- EUL_EUL_USERS  (Table) 
--
CREATE TABLE MASTER.EUL_EUL_USERS
(
  EU_ID               NUMBER(10)                NOT NULL,
  EU_USERNAME         VARCHAR2(64 BYTE),
  EU_USE_PUB_PRIVS    NUMBER(1),
  EU_QUERY_TIME_LMT   NUMBER(22),
  EU_QUERY_EST_LMT    NUMBER(22),
  EU_ROW_FETCH_LMT    NUMBER(22),
  EU_ROLE_FLAG        NUMBER(1),
  EU_BATCH_JOBS_LMT   NUMBER(22),
  EU_BATCH_WND_START  DATE,
  EU_BATCH_WND_END    DATE,
  EU_BATCH_QTIME_LMT  NUMBER(22),
  EU_BATCH_EXPIRY     NUMBER(22),
  EU_BATCH_CMT_SZ     NUMBER(22),
  EU_BATCH_REP_USER   VARCHAR2(64 BYTE),
  NOTM                NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


