--
-- EUL_OBJS  (Table) 
--
CREATE TABLE MASTER.EUL_OBJS
(
  OBJ_ID             NUMBER(10)                 NOT NULL,
  OBJ_TYPE           VARCHAR2(10 BYTE),
  OBJ_NAME           VARCHAR2(100 BYTE),
  OBJ_DESCRIPTION    VARCHAR2(240 BYTE),
  OBJ_HIDDEN         NUMBER(1),
  OBJ_DISTINCT_FLAG  NUMBER(1),
  OBJ_CBO_HINT       VARCHAR2(240 BYTE),
  OBJ_EXT_OBJECT     VARCHAR2(64 BYTE),
  OBJ_EXT_OWNER      VARCHAR2(64 BYTE),
  OBJ_EXT_DB_LINK    VARCHAR2(64 BYTE),
  OBJ_OBJECT_SQL1    VARCHAR2(250 BYTE),
  OBJ_OBJECT_SQL2    VARCHAR2(250 BYTE),
  OBJ_OBJECT_SQL3    VARCHAR2(250 BYTE),
  OBJ_OBJECT_SQL4    VARCHAR2(250 BYTE),
  SOBJ_EXT_TABLE     VARCHAR2(64 BYTE),
  NOTM               NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


