--
-- EUL_JC_JOIN_LINKS  (Table) 
--
CREATE TABLE MASTER.EUL_JC_JOIN_LINKS
(
  JJL_ID      NUMBER(10)                        NOT NULL,
  JJL_JC_ID   NUMBER(10),
  JJL_KEY_ID  NUMBER(10),
  NOTM        NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


