--
-- EUL_PLAN_TABLE  (Table) 
--
CREATE TABLE MASTER.EUL_PLAN_TABLE
(
  STATEMENT_ID     VARCHAR2(30 BYTE),
  TIMESTAMP        DATE,
  REMARKS          VARCHAR2(80 BYTE),
  OPERATION        VARCHAR2(30 BYTE),
  OPTIONS          VARCHAR2(30 BYTE),
  OBJECT_NODE      VARCHAR2(128 BYTE),
  OBJECT_OWNER     VARCHAR2(30 BYTE),
  OBJECT_NAME      VARCHAR2(30 BYTE),
  OBJECT_INSTANCE  NUMBER,
  OBJECT_TYPE      VARCHAR2(30 BYTE),
  OPTIMIZER        VARCHAR2(255 BYTE),
  SEARCH_COLUMNS   NUMBER(38),
  ID               NUMBER(38),
  PARENT_ID        NUMBER(38),
  POSITION         NUMBER(38),
  COST             NUMBER(38),
  CARDINALITY      NUMBER(38),
  BYTES            NUMBER(38),
  OTHER_TAG        VARCHAR2(255 BYTE),
  PARTITION_START  VARCHAR2(255 BYTE),
  PARTITION_STOP   VARCHAR2(255 BYTE),
  PARTITION_ID     NUMBER,
  OTHER            LONG
)
TABLESPACE USERS2
NOCOMPRESS ;


