--
-- EXPORT2INFIN  (Table) 
--
CREATE TABLE MASTER.EXPORT2INFIN
(
  KLS_NAME    VARCHAR2(50 BYTE),
  QUERY_TEXT  VARCHAR2(4000 BYTE),
  FNAME       VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


