--
-- FORMULA  (Table) 
--
CREATE TABLE MASTER.FORMULA
(
  ID            NUMBER(10)                      NOT NULL,
  TAG           VARCHAR2(15 BYTE),
  DESCRIPT      VARCHAR2(50 BYTE),
  FORMULA_KIND  VARCHAR2(15 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.FORMULA IS 'Справочник формул';

COMMENT ON COLUMN MASTER.FORMULA.ID IS 'Уникальный код';

COMMENT ON COLUMN MASTER.FORMULA.TAG IS 'ТЕГ';

COMMENT ON COLUMN MASTER.FORMULA.DESCRIPT IS 'Описание';

COMMENT ON COLUMN MASTER.FORMULA.FORMULA_KIND IS 'Вид формулы';



