--
-- GD_PLAN  (Table) 
--
CREATE TABLE MASTER.GD_PLAN
(
  ID             NUMBER(10)                     NOT NULL,
  DATE_PLAN      DATE,
  FROM_DATE      DATE,
  TO_DATE        DATE,
  PLAN_CIST      NUMBER(10),
  PLAN_VES       NUMBER(14,3),
  DATE_KORR      DATE,
  KORR_CIST      NUMBER(10),
  KORR_VES       NUMBER(14,3),
  MARSHRUT_CIST  NUMBER(10),
  MARSHRUT_VES   NUMBER(14,3),
  GROTP_ID       NUMBER(6),
  NAPR_MOS_ID    NUMBER(10),
  PROD_ID_NPR    VARCHAR2(5 BYTE),
  LOAD_TYPE_ID   NUMBER(2),
  VAGOWNER_ID    NUMBER(10),
  STANOTP_ID     NUMBER(10),
  TIP_PLAN       VARCHAR2(3 BYTE),
  APPL_TAG       VARCHAR2(6 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.GD_PLAN IS 'План перевозок';

COMMENT ON COLUMN MASTER.GD_PLAN.ID IS 'План перевозок';

COMMENT ON COLUMN MASTER.GD_PLAN.DATE_PLAN IS 'Дата плана';

COMMENT ON COLUMN MASTER.GD_PLAN.FROM_DATE IS 'Действует с';

COMMENT ON COLUMN MASTER.GD_PLAN.TO_DATE IS 'Действует по';

COMMENT ON COLUMN MASTER.GD_PLAN.PLAN_CIST IS 'План - цистерн';

COMMENT ON COLUMN MASTER.GD_PLAN.PLAN_VES IS 'План - тонн';

COMMENT ON COLUMN MASTER.GD_PLAN.DATE_KORR IS 'Дата корректировки';

COMMENT ON COLUMN MASTER.GD_PLAN.KORR_CIST IS 'Корректировка - цистерн';

COMMENT ON COLUMN MASTER.GD_PLAN.KORR_VES IS 'Корректировка - тонн';

COMMENT ON COLUMN MASTER.GD_PLAN.MARSHRUT_CIST IS 'Маршрут - цистерн';

COMMENT ON COLUMN MASTER.GD_PLAN.MARSHRUT_VES IS 'Маршрут - тонн';

COMMENT ON COLUMN MASTER.GD_PLAN.GROTP_ID IS 'Грузоотправитель';

COMMENT ON COLUMN MASTER.GD_PLAN.NAPR_MOS_ID IS 'Направление отгрузки';

COMMENT ON COLUMN MASTER.GD_PLAN.PROD_ID_NPR IS 'Продукт';

COMMENT ON COLUMN MASTER.GD_PLAN.LOAD_TYPE_ID IS 'Тип транспортировки';

COMMENT ON COLUMN MASTER.GD_PLAN.VAGOWNER_ID IS 'Собственник вагонов';

COMMENT ON COLUMN MASTER.GD_PLAN.STANOTP_ID IS 'Станция отправления';

COMMENT ON COLUMN MASTER.GD_PLAN.TIP_PLAN IS 'Тип плана';



