--
-- GD_RAZN_POS  (Table) 
--
CREATE TABLE MASTER.GD_RAZN_POS
(
  ID             NUMBER(10)                     NOT NULL,
  GD_RAZN_ID     NUMBER(10),
  NUM_POS        NUMBER(10),
  DATE_POS       DATE,
  KOL            NUMBER(10),
  VES            NUMBER(14,3),
  PRIM           VARCHAR2(50 BYTE),
  PROD_ID_NPR    VARCHAR2(5 BYTE),
  STAN_ID        NUMBER(10),
  VETKA_ID       NUMBER(4),
  POLUCH_ID      NUMBER(6),
  VID_OTPR_ID    NUMBER(10),
  GD_VAGTYPE_ID  NUMBER(10),
  GD_PRINVAG_ID  NUMBER(10),
  VAGOWNER_ID    NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.GD_RAZN_POS IS 'Позиции месячной заявки';

COMMENT ON COLUMN MASTER.GD_RAZN_POS.ID IS 'Позиции заявки';

COMMENT ON COLUMN MASTER.GD_RAZN_POS.GD_RAZN_ID IS 'Месячная заявка';

COMMENT ON COLUMN MASTER.GD_RAZN_POS.NUM_POS IS 'Номер позиции';

COMMENT ON COLUMN MASTER.GD_RAZN_POS.DATE_POS IS 'Дата погрузки';

COMMENT ON COLUMN MASTER.GD_RAZN_POS.KOL IS 'Кол-во';

COMMENT ON COLUMN MASTER.GD_RAZN_POS.VES IS 'Вес';

COMMENT ON COLUMN MASTER.GD_RAZN_POS.PRIM IS 'Примечание';

COMMENT ON COLUMN MASTER.GD_RAZN_POS.PROD_ID_NPR IS 'Продукт';

COMMENT ON COLUMN MASTER.GD_RAZN_POS.STAN_ID IS 'Станция назначения';

COMMENT ON COLUMN MASTER.GD_RAZN_POS.VETKA_ID IS 'Ветка получателя';

COMMENT ON COLUMN MASTER.GD_RAZN_POS.POLUCH_ID IS 'Получатель';

COMMENT ON COLUMN MASTER.GD_RAZN_POS.VID_OTPR_ID IS 'Вид отправки';

COMMENT ON COLUMN MASTER.GD_RAZN_POS.GD_VAGTYPE_ID IS 'Род вагона (для ГУ-12)';

COMMENT ON COLUMN MASTER.GD_RAZN_POS.GD_PRINVAG_ID IS 'Принадлежность вагонов';

COMMENT ON COLUMN MASTER.GD_RAZN_POS.VAGOWNER_ID IS 'Собственник вагонов';



