--
-- GD_RAZN  (Table) 
--
CREATE TABLE MASTER.GD_RAZN
(
  ID              NUMBER(10)                    NOT NULL,
  TRANSPORTER_ID  NUMBER(6),
  NUM_ZAYV        VARCHAR2(15 BYTE),
  DATE_PLAN       DATE,
  FROM_DATE       DATE,
  TO_DATE         DATE,
  DATE_SOGL       DATE,
  DATE_REG        DATE,
  DATE_UTV        DATE,
  GD_DOGOVOR      VARCHAR2(10 BYTE),
  STAN_OTP_ID     NUMBER(10),
  VETKA_OTP_ID    NUMBER(10),
  GD_OTPR_ID      NUMBER(10),
  GROTP_ID        NUMBER(6),
  TEX_PD_ID       NUMBER(10),
  LOAD_TYPE_ID    NUMBER(2),
  EXPED_ID        NUMBER(6),
  GD_GROUP_ID     NUMBER(10),
  GD_SOOB_ID      NUMBER(10),
  GD_PODACH_ID    NUMBER(10),
  NAPR_MOS_ID     NUMBER(10),
  SOGL            INTEGER
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.GD_RAZN IS 'Месячная разнарядка';

COMMENT ON COLUMN MASTER.GD_RAZN.ID IS 'Месячная заявка';

COMMENT ON COLUMN MASTER.GD_RAZN.TRANSPORTER_ID IS 'Перевозчик';

COMMENT ON COLUMN MASTER.GD_RAZN.NUM_ZAYV IS 'Номер заявки';

COMMENT ON COLUMN MASTER.GD_RAZN.DATE_PLAN IS 'Дата плана';

COMMENT ON COLUMN MASTER.GD_RAZN.FROM_DATE IS 'С даты';

COMMENT ON COLUMN MASTER.GD_RAZN.TO_DATE IS 'По дату';

COMMENT ON COLUMN MASTER.GD_RAZN.DATE_SOGL IS 'Дата согласования';

COMMENT ON COLUMN MASTER.GD_RAZN.DATE_REG IS 'Дата регистрации';

COMMENT ON COLUMN MASTER.GD_RAZN.DATE_UTV IS 'Дата утверждения';

COMMENT ON COLUMN MASTER.GD_RAZN.GD_DOGOVOR IS '№ договора об организации перевозок';

COMMENT ON COLUMN MASTER.GD_RAZN.STAN_OTP_ID IS 'Станция отправления';

COMMENT ON COLUMN MASTER.GD_RAZN.VETKA_OTP_ID IS 'Ветка отправителя';

COMMENT ON COLUMN MASTER.GD_RAZN.GD_OTPR_ID IS 'Признак отправки';

COMMENT ON COLUMN MASTER.GD_RAZN.GROTP_ID IS 'Отправитель';

COMMENT ON COLUMN MASTER.GD_RAZN.TEX_PD_ID IS 'Плательщик тарифа';

COMMENT ON COLUMN MASTER.GD_RAZN.LOAD_TYPE_ID IS 'Тип транспортировки';

COMMENT ON COLUMN MASTER.GD_RAZN.EXPED_ID IS 'Экспедитор';

COMMENT ON COLUMN MASTER.GD_RAZN.GD_GROUP_ID IS 'Группа груза';

COMMENT ON COLUMN MASTER.GD_RAZN.GD_SOOB_ID IS 'Вид сообщения';

COMMENT ON COLUMN MASTER.GD_RAZN.GD_PODACH_ID IS 'Вид подачи';

COMMENT ON COLUMN MASTER.GD_RAZN.NAPR_MOS_ID IS 'Направление ЭКСПОРТ_ВНУТР РЫНОК';

COMMENT ON COLUMN MASTER.GD_RAZN.SOGL IS 'Отметка о согласовании';



