--
-- GU12_PODPIS  (Table) 
--
CREATE TABLE MASTER.GU12_PODPIS
(
  ID         NUMBER(3),
  FIO        VARCHAR2(30 BYTE),
  DOLGNOST   VARCHAR2(100 BYTE),
  DOVER      VARCHAR2(30 BYTE),
  DOVER_OLD  VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


