--
-- GU12_A_TEST  (Table) 
--
CREATE TABLE MASTER.GU12_A_TEST
(
  ID            NUMBER(10),
  NOM_Z         VARCHAR2(15 BYTE),
  FROM_DATE     DATE,
  TO_DATE       DATE,
  SOGL_DATE     DATE,
  REG_DATE      DATE,
  DOGOVOR       VARCHAR2(10 BYTE),
  STANOTPR_ID   NUMBER(10),
  GROTP_ID      NUMBER(10),
  EXPED_ID      NUMBER(6),
  GR_GRUZ_ID    NUMBER(10),
  VIDSOOB_ID    NUMBER(10),
  PODACH_ID     NUMBER(10),
  SOGL          INTEGER,
  PLATTAR_ID    NUMBER(7),
  PROD_ID       NUMBER(6),
  PRIZNOTPR_ID  INTEGER,
  VLADPUT_ID    INTEGER,
  RODVAG_ID     INTEGER,
  ID_NOSOGL     NUMBER(10),
  FOX_KOD       VARCHAR2(10 BYTE),
  ISCOR         NUMBER
)
TABLESPACE USERS2
NOCOMPRESS ;


