--
-- GU12_A  (Table) 
--
CREATE TABLE MASTER.GU12_A
(
  ID            NUMBER(10)                      NOT NULL,
  NOM_Z         VARCHAR2(20 BYTE),
  FROM_DATE     DATE,
  TO_DATE       DATE,
  SOGL_DATE     DATE,
  REG_DATE      DATE,
  DOGOVOR       VARCHAR2(10 BYTE),
  STANOTPR_ID   NUMBER(10),
  GROTP_ID      NUMBER(10),
  EXPED_ID      NUMBER(6),
  GR_GRUZ_ID    NUMBER(10),
  VIDSOOB_ID    NUMBER(10),
  PODACH_ID     NUMBER(10),
  SOGL          INTEGER,
  PLATTAR_ID    NUMBER(7),
  PROD_ID       NUMBER(6),
  PRIZNOTPR_ID  INTEGER,
  VLADPUT_ID    INTEGER,
  RODVAG_ID     INTEGER,
  ID_NOSOGL     NUMBER(10),
  FOX_KOD       VARCHAR2(10 BYTE),
  ISCOR         NUMBER,
  ZAKR_DATE     DATE
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.GU12_A IS 'Месячная разнарядка';

COMMENT ON COLUMN MASTER.GU12_A.ID IS 'Месячная заявка';

COMMENT ON COLUMN MASTER.GU12_A.NOM_Z IS 'Номер заявки';

COMMENT ON COLUMN MASTER.GU12_A.FROM_DATE IS 'С даты';

COMMENT ON COLUMN MASTER.GU12_A.TO_DATE IS 'По дату';

COMMENT ON COLUMN MASTER.GU12_A.SOGL_DATE IS 'Дата согласования';

COMMENT ON COLUMN MASTER.GU12_A.REG_DATE IS 'Дата регистрации';

COMMENT ON COLUMN MASTER.GU12_A.DOGOVOR IS '№ договора об организации перевозок';

COMMENT ON COLUMN MASTER.GU12_A.STANOTPR_ID IS 'Станция отправления';

COMMENT ON COLUMN MASTER.GU12_A.GROTP_ID IS 'Грузоотравитель';

COMMENT ON COLUMN MASTER.GU12_A.EXPED_ID IS 'Экспедитор';

COMMENT ON COLUMN MASTER.GU12_A.GR_GRUZ_ID IS 'Группа груза';

COMMENT ON COLUMN MASTER.GU12_A.VIDSOOB_ID IS 'Вид сообщения';

COMMENT ON COLUMN MASTER.GU12_A.PODACH_ID IS 'Вид подачи';

COMMENT ON COLUMN MASTER.GU12_A.SOGL IS 'Отметка о согласовании';

COMMENT ON COLUMN MASTER.GU12_A.PLATTAR_ID IS 'Плательщик тарифа';

COMMENT ON COLUMN MASTER.GU12_A.PROD_ID IS 'Груз';

COMMENT ON COLUMN MASTER.GU12_A.PRIZNOTPR_ID IS 'Признак отправки';

COMMENT ON COLUMN MASTER.GU12_A.VLADPUT_ID IS 'Владелец пути';

COMMENT ON COLUMN MASTER.GU12_A.RODVAG_ID IS 'Род вагона';

COMMENT ON COLUMN MASTER.GU12_A.ID_NOSOGL IS 'Несогласованная заявка';



