--
-- INF2PB_SCH  (Table) 
--
CREATE TABLE MASTER.INF2PB_SCH
(
  ID         NUMBER(10)                         NOT NULL,
  SCH        VARCHAR2(4 BYTE),
  CONT_AN    NUMBER(1),
  RAS_AN     NUMBER(1),
  SCH_NAME   VARCHAR2(50 BYTE),
  DOG_AN     NUMBER(1),
  NUM_AN     NUMBER(1),
  PAYOFF_AN  NUMBER(1)
)
TABLESPACE USERS2
NOCOMPRESS ;


