--
-- INF2PB_ACCOUNTS  (Table) 
--
CREATE TABLE MASTER.INF2PB_ACCOUNTS
(
  ID             NUMBER(10)                     NOT NULL,
  INF2PB_SCH_ID  NUMBER(10),
  CONT_ID        VARCHAR2(10 BYTE),
  RAS_ID         VARCHAR2(10 BYTE),
  DEB            VARCHAR2(4 BYTE),
  KRED           VARCHAR2(4 BYTE),
  PROMIS         VARCHAR2(1 BYTE),
  PAY_TYPE       VARCHAR2(3 BYTE),
  ACC_CODE       VARCHAR2(21 BYTE),
  STATUS         VARCHAR2(1 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


