--
-- ISU_BILL_POS_ROW  (Table) 
--
CREATE TABLE MASTER.ISU_BILL_POS_ROW
(
  ISU_KOD      VARCHAR2(10 BYTE)                NOT NULL,
  ISU_KOD_POS  VARCHAR2(16 BYTE)                NOT NULL,
  ISU_TTN_ID   VARCHAR2(16 BYTE)                NOT NULL,
  TTN_ID       VARCHAR2(20 BYTE),
  VES          NUMBER(13,6),
  KVIT_ID      NUMBER(16)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.ISU_BILL_POS_ROW IS 'Соответствие позиции поставки – позиции счет-фактуры из ИСУ Переработка';

COMMENT ON COLUMN MASTER.ISU_BILL_POS_ROW.ISU_KOD IS 'Код счета-фактуры';

COMMENT ON COLUMN MASTER.ISU_BILL_POS_ROW.ISU_KOD_POS IS 'Код позиции счета-фактуры';

COMMENT ON COLUMN MASTER.ISU_BILL_POS_ROW.ISU_TTN_ID IS 'Код позиции ТТН';

COMMENT ON COLUMN MASTER.ISU_BILL_POS_ROW.TTN_ID IS 'Код ТТН';

COMMENT ON COLUMN MASTER.ISU_BILL_POS_ROW.VES IS 'Вес';



