--
-- ISU_TAX_FILES  (Table) 
--
CREATE TABLE MASTER.ISU_TAX_FILES
(
  ID           NUMBER,
  FILE_NAME    VARCHAR2(255 BYTE),
  USER_ID      NUMBER,
  SOURCE_ID    NUMBER,
  UPLOAD_DATE  DATE
)
TABLESPACE USERS
NOCOMPRESS ;


