--
-- ISU_BILL_POS  (Table) 
--
CREATE TABLE MASTER.ISU_BILL_POS
(
  ISU_KOD_POS      VARCHAR2(16 BYTE)            NOT NULL,
  ISU_KOD_POS_OLD  VARCHAR2(16 BYTE),
  MATERIAL_KSSS    VARCHAR2(10 BYTE),
  AKCIZ_GRP        NUMBER(2),
  PRICE            NUMBER(10,2),
  VES              NUMBER(13,6),
  SUMMA_BN         NUMBER(12,2),
  SUMMA_AKCIZ      NUMBER(12,2),
  SUMMA_NDS        NUMBER(12,2),
  SUMMA            NUMBER(12,2),
  OWNER_KSSS       VARCHAR2(10 BYTE),
  NDS              NUMBER(6,3),
  TARIF_BN         NUMBER(12,2),
  SUMMA_RAZN_BN    NUMBER(12,2),
  TARIF_NDS        NUMBER(12,2),
  TARIF_GUARD_BN   NUMBER(12,2),
  TARIF_GUARD_NDS  NUMBER(12,2),
  SUMMA_VOZN_BN    NUMBER(12,2),
  SUMMA_OSOB       NUMBER(12,2),
  IS_AKCIZ         NUMBER(1),
  EX_SVID          VARCHAR2(30 BYTE),
  PRICE_WITH_NDS   NUMBER(10,2),
  AKCIZ_RUB        NUMBER(10,2)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.ISU_BILL_POS IS 'Позиции счет-фактуры из ИСУ Переработка';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.ISU_KOD_POS IS 'Код позиции счета-фактуры';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.ISU_KOD_POS_OLD IS 'Код позиции сторнируемого счета-фактуры';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.MATERIAL_KSSS IS 'Код нефтепродукта';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.AKCIZ_GRP IS 'Группа акциза';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.PRICE IS 'Цена';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.VES IS 'Вес';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.SUMMA_BN IS 'Сумма без НДС';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.SUMMA_AKCIZ IS 'Сумма акциза';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.SUMMA_NDS IS 'Сумма НДС';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.SUMMA IS 'Сумма общая';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.OWNER_KSSS IS 'Код собственника';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.NDS IS 'Ставка НДС';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.TARIF_BN IS 'Провозная плата';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.SUMMA_RAZN_BN IS 'Разница тарифов (по арендованным вагонам)';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.TARIF_NDS IS 'НДС провозной платы';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.TARIF_GUARD_BN IS 'Охрана вагона';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.TARIF_GUARD_NDS IS 'НДС Охраны вагона';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.SUMMA_VOZN_BN IS 'Вознаграждение';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.SUMMA_OSOB IS 'Перевозка Особые Условия';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.IS_AKCIZ IS 'Признак наличие свидетельства';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.EX_SVID IS 'Номер свидетельства';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.PRICE_WITH_NDS IS 'Цена нефтепродукта с НДС';

COMMENT ON COLUMN MASTER.ISU_BILL_POS.AKCIZ_RUB IS 'Акциз в руб./тонну';



