--
-- ISU_TAX_DOCS  (Table) 
--
CREATE TABLE MASTER.ISU_TAX_DOCS
(
  ID             NUMBER,
  DOC_NUM        VARCHAR2(50 BYTE),
  DOC_DATE       DATE,
  PACKAGE_ID     NUMBER,
  FILE_ID        NUMBER,
  FILE_POS_NUM   NUMBER,
  CONTRACTOR_ID  NUMBER
)
TABLESPACE USERS
NOCOMPRESS ;


