--
-- JKALLOW  (Table) 
--
CREATE TABLE MASTER.JKALLOW
(
  JKA_DATE    DATE                              NOT NULL,
  MESTO_ID    NUMBER(2)                         NOT NULL,
  SVED_NUM    NUMBER(6)                         NOT NULL,
  DATE_ALLOW  DATE,
  SROK_ALLOW  NUMBER(3),
  USERNAME    VARCHAR2(20 BYTE),
  SVED_ID     VARCHAR2(9 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


