--
-- JKCOMMIT_PLAN2CENN  (Table) 
--
CREATE TABLE MASTER.JKCOMMIT_PLAN2CENN
(
  PLANSTRU_ID  NUMBER(20)                       NOT NULL,
  CAT_CEN_ID   NUMBER(3)                        NOT NULL
)
TABLESPACE USERS2
NOCOMPRESS ;


