--
-- KLS_PROD_GR_KONS  (Table) 
--
CREATE TABLE MASTER.KLS_PROD_GR_KONS
(
  ID_GR           VARCHAR2(12 BYTE)             NOT NULL,
  NAME            VARCHAR2(30 BYTE),
  ABBR            VARCHAR2(12 BYTE),
  ID_GLOBAL_GR    VARCHAR2(12 BYTE),
  NAME_GLOBAL_GR  VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_PROD_GR_KONS IS 'Конс.отчетность: Группа нефтепродуктов';

COMMENT ON COLUMN MASTER.KLS_PROD_GR_KONS.ID_GR IS 'Группа нефтепродуктов';

COMMENT ON COLUMN MASTER.KLS_PROD_GR_KONS.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_PROD_GR_KONS.ABBR IS 'Краткое наименование';



