--
-- KLS_GTD  (Table) 
--
CREATE TABLE MASTER.KLS_GTD
(
  GTD       VARCHAR2(20 BYTE)                   NOT NULL,
  DATE_GTD  DATE,
  N_NP      VARCHAR2(24 BYTE),
  T_GTD     VARCHAR2(1 BYTE),
  PRED_DEC  VARCHAR2(20 BYTE),
  KVED      VARCHAR2(10 BYTE),
  KOLG      NUMBER(10,3),
  STOF      NUMBER(12,2),
  STOS      NUMBER(12,2),
  STOT      NUMBER(12,2),
  V_10      NUMBER(12,2),
  V_11      NUMBER(12,2),
  V_25      NUMBER(12,2),
  V_26      NUMBER(12,2),
  KURS      NUMBER(9,4),
  DVYP      DATE,
  TAMG      VARCHAR2(5 BYTE),
  KNMT      NUMBER(2),
  OTVL      VARCHAR2(24 BYTE),
  NAGN      VARCHAR2(24 BYTE),
  DKTS      DATE,
  S_GR      VARCHAR2(24 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


