--
-- KLS_STATUS_ZAKAZ  (Table) 
--
CREATE TABLE MASTER.KLS_STATUS_ZAKAZ
(
  ID     NUMBER(10)                             NOT NULL,
  NAME   VARCHAR2(50 BYTE),
  NAME2  VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_STATUS_ZAKAZ IS 'Статус заказа потребителя';

COMMENT ON COLUMN MASTER.KLS_STATUS_ZAKAZ.ID IS 'ID';

COMMENT ON COLUMN MASTER.KLS_STATUS_ZAKAZ.NAME IS 'Наименование';



