--
-- KLS_PROD_GROUPS  (Table) 
--
CREATE TABLE MASTER.KLS_PROD_GROUPS
(
  ID                NUMBER(10)                  NOT NULL,
  PROD_TYPE_GRP_ID  NUMBER(10),
  GROUP_ORDER       NUMBER(10),
  GROUP_NAME        VARCHAR2(50 BYTE),
  GROUP_VISIBLE     NUMBER(1)                   DEFAULT 1,
  GROUP_ABBR        VARCHAR2(10 BYTE),
  MOSCOW_ID         NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_PROD_GROUPS IS 'Виды группировок продуктов в рамках классификации группировок';

COMMENT ON COLUMN MASTER.KLS_PROD_GROUPS.ID IS 'Виды группировок продуктов';

COMMENT ON COLUMN MASTER.KLS_PROD_GROUPS.PROD_TYPE_GRP_ID IS 'Тип группировки';

COMMENT ON COLUMN MASTER.KLS_PROD_GROUPS.GROUP_ORDER IS 'Порядок';

COMMENT ON COLUMN MASTER.KLS_PROD_GROUPS.GROUP_NAME IS 'Наименование группы';

COMMENT ON COLUMN MASTER.KLS_PROD_GROUPS.GROUP_VISIBLE IS 'Видима в отчетах';

COMMENT ON COLUMN MASTER.KLS_PROD_GROUPS.GROUP_ABBR IS 'Сокращенное наименование';

COMMENT ON COLUMN MASTER.KLS_PROD_GROUPS.MOSCOW_ID IS 'Код для Москвы';



