--
-- KLS_PREDPR_AKCIZ  (Table) 
--
CREATE TABLE MASTER.KLS_PREDPR_AKCIZ
(
  ID              NUMBER(10)                    NOT NULL,
  PLAT_ID         NUMBER(10),
  DATE_BEG        DATE,
  DATE_END        DATE,
  EX_SVID         NUMBER(10)                    DEFAULT 0,
  EX_SVID_PREF    VARCHAR2(15 BYTE),
  EX_SVID_NUMB    VARCHAR2(30 BYTE),
  DATE_CANCEL     DATE,
  DATE_GIVE       DATE,
  IS_OPT          NUMBER(1)                     DEFAULT 1,
  IS_ROZN         NUMBER(1)                     DEFAULT 1,
  PROD_GROUPS_ID  NUMBER(10)                    DEFAULT 114,
  NAPR_POST_ID    NUMBER(10)                    DEFAULT 1
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_PREDPR_AKCIZ IS 'Периоды действия акцизных свидетельств';

COMMENT ON COLUMN MASTER.KLS_PREDPR_AKCIZ.ID IS 'ID';

COMMENT ON COLUMN MASTER.KLS_PREDPR_AKCIZ.PLAT_ID IS 'Плательщик';

COMMENT ON COLUMN MASTER.KLS_PREDPR_AKCIZ.DATE_BEG IS 'С даты';

COMMENT ON COLUMN MASTER.KLS_PREDPR_AKCIZ.DATE_END IS 'По дату';

COMMENT ON COLUMN MASTER.KLS_PREDPR_AKCIZ.EX_SVID IS 'Признак действия акцизного свидетельства';

COMMENT ON COLUMN MASTER.KLS_PREDPR_AKCIZ.EX_SVID_PREF IS 'Серия';

COMMENT ON COLUMN MASTER.KLS_PREDPR_AKCIZ.EX_SVID_NUMB IS 'Номер';

COMMENT ON COLUMN MASTER.KLS_PREDPR_AKCIZ.DATE_CANCEL IS 'Дата аннулирования';

COMMENT ON COLUMN MASTER.KLS_PREDPR_AKCIZ.DATE_GIVE IS 'Дата выдачи';

COMMENT ON COLUMN MASTER.KLS_PREDPR_AKCIZ.IS_OPT IS 'Опт';

COMMENT ON COLUMN MASTER.KLS_PREDPR_AKCIZ.IS_ROZN IS 'Розница';

COMMENT ON COLUMN MASTER.KLS_PREDPR_AKCIZ.PROD_GROUPS_ID IS 'Группа продуктов';

COMMENT ON COLUMN MASTER.KLS_PREDPR_AKCIZ.NAPR_POST_ID IS 'Направление поставки';



