--
-- KLS_VAGOWNER  (Table) 
--
CREATE TABLE MASTER.KLS_VAGOWNER
(
  ID               NUMBER(10)                   NOT NULL,
  VAGOWNER_NAME    VARCHAR2(30 BYTE),
  SHORT_NAME       VARCHAR2(10 BYTE),
  PREDPR_ID        NUMBER(6),
  VAGOWN_MOS_ID    NUMBER(10),
  VAGOWN_TYP_ID    NUMBER(10),
  SOBSTV_ID        NUMBER(10),
  DISPLAY_NAME     VARCHAR2(50 BYTE),
  OWNER_ID         NUMBER(10),
  SMN_NAME         VARCHAR2(30 BYTE),
  SORTBY           NUMBER(10),
  LOAD_TYPE_ID     NUMBER(2),
  RAZR_MPS         VARCHAR2(40 BYTE),
  VZISK1           VARCHAR2(40 BYTE),
  VZISK2           VARCHAR2(40 BYTE),
  VZISK1_EX        VARCHAR2(40 BYTE),
  VZISK2_EX        VARCHAR2(40 BYTE),
  GR1_TXT          VARCHAR2(50 BYTE),
  GR2_TXT          VARCHAR2(50 BYTE),
  GR1_TXT_EX       VARCHAR2(50 BYTE),
  GR2_TXT_EX       VARCHAR2(50 BYTE),
  PRN_NAME         VARCHAR2(50 BYTE),
  R3_VSART_ID      VARCHAR2(5 BYTE),
  R3_VENDORS_ID    VARCHAR2(10 BYTE),
  ISU_POSTAV_ID    VARCHAR2(10 BYTE),
  ISU_POSTAV_NAME  VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_VAGOWNER IS 'Владельцы вагонов';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.ID IS 'Владелец вагона (ID)';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.VAGOWNER_NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.SHORT_NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.PREDPR_ID IS 'Контрагент';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.VAGOWN_MOS_ID IS 'Владелец (Москва)';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.VAGOWN_TYP_ID IS 'Тип собственности';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.SOBSTV_ID IS 'Собственник тр ср-ва';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.DISPLAY_NAME IS 'Отображаемое в интерфейсе наименование';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.OWNER_ID IS 'Владелец вагона';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.SMN_NAME IS 'Название собственника из реестра СМН';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.SORTBY IS 'Порядок';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.RAZR_MPS IS 'Разрешение на кусирование';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.VZISK1 IS 'Доп. взыск 1';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.VZISK2 IS 'Доп. взыск2';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.VZISK1_EX IS 'Доп. взыск 1 экспорт';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.VZISK2_EX IS 'Доп. взыск 2 экспорт';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.GR1_TXT IS 'Под наименованием груза 1';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.GR2_TXT IS 'Под наименованием груза 2';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.GR1_TXT_EX IS 'Под наименованием груза 1 экспорт';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.GR2_TXT_EX IS 'Под наименованием груза 2 экспорт';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER.PRN_NAME IS 'Имя для печати';



