--
-- KLS_FORMSHAB  (Table) 
--
CREATE TABLE MASTER.KLS_FORMSHAB
(
  ID            NUMBER(10)                      NOT NULL,
  FORMNAKL_ID   NUMBER(10),
  NAME          VARCHAR2(30 BYTE),
  DOSTUP        NUMBER(1)                       DEFAULT 0,
  FILENAME      VARCHAR2(20 BYTE),
  IS_RUS        NUMBER(1)                       DEFAULT 0,
  IS_OPD        NUMBER(1)                       DEFAULT 0,
  LOAD_TYPE_ID  NUMBER(10),
  P_RAZR_MPS    NUMBER(1)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_FORMSHAB IS 'Формы накладных';

COMMENT ON COLUMN MASTER.KLS_FORMSHAB.ID IS 'Шаблон накладной';

COMMENT ON COLUMN MASTER.KLS_FORMSHAB.FORMNAKL_ID IS 'Форма накладной';

COMMENT ON COLUMN MASTER.KLS_FORMSHAB.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_FORMSHAB.DOSTUP IS '1-Доступна';

COMMENT ON COLUMN MASTER.KLS_FORMSHAB.FILENAME IS 'Имя файла';

COMMENT ON COLUMN MASTER.KLS_FORMSHAB.IS_RUS IS '1-Русская';

COMMENT ON COLUMN MASTER.KLS_FORMSHAB.IS_OPD IS '1-ОПД';

COMMENT ON COLUMN MASTER.KLS_FORMSHAB.LOAD_TYPE_ID IS 'Тип транспортировки';

COMMENT ON COLUMN MASTER.KLS_FORMSHAB.P_RAZR_MPS IS '1-печатать разрешение МПС на курсирование';



