--
-- KLS_CIST  (Table) 
--
CREATE TABLE MASTER.KLS_CIST
(
  NUM_CIST      NUMBER(9)                       NOT NULL,
  KALIBR_ID     VARCHAR2(5 BYTE),
  CAPACITY      VARCHAR2(10 BYTE),
  DATE_BILD     DATE,
  PLACE_BILD    VARCHAR2(5 BYTE),
  VES_CIST      NUMBER(10,3),
  DATE_TO       DATE,
  DATE_REMONT   DATE,
  VAGOWNER_ID   NUMBER(10),
  MODEL         VARCHAR2(10 BYTE),
  GR1_TXT       VARCHAR2(60 BYTE),
  GR2_TXT       VARCHAR2(60 BYTE),
  WES1          VARCHAR2(5 BYTE),
  TIP1          VARCHAR2(5 BYTE),
  VAGONTYPE_ID  NUMBER(10),
  AXES          NUMBER(2)                       DEFAULT 4,
  RAZMET_FACT   VARCHAR2(30 BYTE),
  NCISTDOP      NUMBER(2)                       DEFAULT 20,
  PROD_ID_NPR   VARCHAR2(5 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_CIST IS 'Справочник цистерн';

COMMENT ON COLUMN MASTER.KLS_CIST.NUM_CIST IS 'Вагон';

COMMENT ON COLUMN MASTER.KLS_CIST.KALIBR_ID IS 'Тип вагона';

COMMENT ON COLUMN MASTER.KLS_CIST.CAPACITY IS 'Грузоподъемность';

COMMENT ON COLUMN MASTER.KLS_CIST.DATE_BILD IS 'Дата постройки';

COMMENT ON COLUMN MASTER.KLS_CIST.PLACE_BILD IS 'Место постройки';

COMMENT ON COLUMN MASTER.KLS_CIST.VES_CIST IS 'Вес вагона';

COMMENT ON COLUMN MASTER.KLS_CIST.DATE_TO IS 'Дата ТО';

COMMENT ON COLUMN MASTER.KLS_CIST.DATE_REMONT IS 'Дата ремонта';

COMMENT ON COLUMN MASTER.KLS_CIST.VAGOWNER_ID IS 'Собственник / владелец';

COMMENT ON COLUMN MASTER.KLS_CIST.MODEL IS 'Модель';

COMMENT ON COLUMN MASTER.KLS_CIST.GR1_TXT IS 'Под наименованием груза 1';

COMMENT ON COLUMN MASTER.KLS_CIST.GR2_TXT IS 'Под наименованием груза 2';

COMMENT ON COLUMN MASTER.KLS_CIST.WES1 IS 'через / для ПВ и КВ';

COMMENT ON COLUMN MASTER.KLS_CIST.TIP1 IS '61205 для 25 типа';

COMMENT ON COLUMN MASTER.KLS_CIST.VAGONTYPE_ID IS 'Род вагона';

COMMENT ON COLUMN MASTER.KLS_CIST.AXES IS 'Кол-во осей';

COMMENT ON COLUMN MASTER.KLS_CIST.RAZMET_FACT IS 'Разметка под груз';

COMMENT ON COLUMN MASTER.KLS_CIST.NCISTDOP IS 'Признак дорог СНГ';

COMMENT ON COLUMN MASTER.KLS_CIST.PROD_ID_NPR IS 'Последний продукт';



