--
-- KLS_LOAD_TYPE  (Table) 
--
CREATE TABLE MASTER.KLS_LOAD_TYPE
(
  ID              NUMBER(2)                     NOT NULL,
  TYPE_OTGR_NAME  VARCHAR2(30 BYTE),
  LOAD_MOS_ID     NUMBER(10),
  SF_POKUP_VTR    NUMBER(2),
  ISU_KOD         VARCHAR2(1 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KLS_LOAD_TYPE.ISU_KOD IS ' Ó‰ »—”';



