--
-- KLS_PREDPR_CONTACTS  (Table) 
--
CREATE TABLE MASTER.KLS_PREDPR_CONTACTS
(
  ID           NUMBER(10)                       NOT NULL,
  PREDPR_ID    NUMBER(6),
  IS_BOSS      NUMBER(1)                        DEFAULT 0,
  LASTNAME     VARCHAR2(15 BYTE),
  SHORTNAME    VARCHAR2(15 BYTE),
  FIRSTNAME    VARCHAR2(15 BYTE),
  MIDDLENAME   VARCHAR2(15 BYTE),
  LASTNAME1    VARCHAR2(15 BYTE),
  FIRSTNAME1   VARCHAR2(15 BYTE),
  MIDDLENAME1  VARCHAR2(15 BYTE),
  LASTNAME2    VARCHAR2(15 BYTE),
  FIRSTNAME2   VARCHAR2(15 BYTE),
  MIDDLENAME2  VARCHAR2(15 BYTE),
  PHONE        VARCHAR2(20 BYTE),
  STAFF        VARCHAR2(50 BYTE),
  STAFF1       VARCHAR2(50 BYTE),
  STAFF2       VARCHAR2(50 BYTE),
  SEX          NUMBER(1)                        DEFAULT 1,
  NA_OSNOV     VARCHAR2(100 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_PREDPR_CONTACTS IS 'Контакты';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.ID IS 'Контакт';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.PREDPR_ID IS 'Предприятие';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.IS_BOSS IS '0-Работник,1-Руководитель, 2-Главбух, 3-Зам';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.LASTNAME IS 'Именительный - Ф';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.SHORTNAME IS 'Именительный - И.О.';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.FIRSTNAME IS 'Именительный - И';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.MIDDLENAME IS 'Именительный - О';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.LASTNAME1 IS 'Дательный - Ф';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.FIRSTNAME1 IS 'Дательный - И';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.MIDDLENAME1 IS 'Дательный - О';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.LASTNAME2 IS 'Родительный - Ф';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.FIRSTNAME2 IS 'Родительный - И';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.MIDDLENAME2 IS 'Родительный - О';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.PHONE IS 'Телефон';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.STAFF IS 'Именительный - Должность';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.STAFF1 IS 'Дательный - Должность';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.STAFF2 IS 'Родительный - Должность';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.SEX IS '1-М, 0-Ж';

COMMENT ON COLUMN MASTER.KLS_PREDPR_CONTACTS.NA_OSNOV IS 'На основании';



