--
-- KLS_PROD_KONS  (Table) 
--
CREATE TABLE MASTER.KLS_PROD_KONS
(
  ID            VARCHAR2(21 BYTE)               NOT NULL,
  NAME          VARCHAR2(50 BYTE),
  PROD_KONS_ID  VARCHAR2(21 BYTE),
  UPAK_ID       NUMBER(10),
  DOP_ID        VARCHAR2(2 BYTE),
  FLAG_FAS      NUMBER(1)                       DEFAULT 0,
  KOEF_KG       NUMBER(12,4)                    DEFAULT 0,
  KOEF_LIT      NUMBER(12,4)                    DEFAULT 0,
  GR_KONS_ID    VARCHAR2(12 BYTE),
  PROD_ID_NPR   VARCHAR2(5 BYTE),
  TIP_AKCIZ_ID  NUMBER(10),
  IS_AUTO_LINK  NUMBER(1)                       DEFAULT 1,
  P_YEAR        VARCHAR2(2 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_PROD_KONS IS 'Конс.отчетность: Справочник продуктов';

COMMENT ON COLUMN MASTER.KLS_PROD_KONS.ID IS 'Продукт (конс.отчетность)';

COMMENT ON COLUMN MASTER.KLS_PROD_KONS.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_PROD_KONS.PROD_KONS_ID IS 'Основной код продукта';

COMMENT ON COLUMN MASTER.KLS_PROD_KONS.UPAK_ID IS 'Упаковка';

COMMENT ON COLUMN MASTER.KLS_PROD_KONS.DOP_ID IS 'Дополнительный код';

COMMENT ON COLUMN MASTER.KLS_PROD_KONS.FLAG_FAS IS '1 - Фасовка';

COMMENT ON COLUMN MASTER.KLS_PROD_KONS.KOEF_KG IS 'Коэф. перевода в кг';

COMMENT ON COLUMN MASTER.KLS_PROD_KONS.KOEF_LIT IS 'Коэф. перевода в литры';

COMMENT ON COLUMN MASTER.KLS_PROD_KONS.GR_KONS_ID IS 'Группа нефтепродуктов';

COMMENT ON COLUMN MASTER.KLS_PROD_KONS.TIP_AKCIZ_ID IS 'Тип акциза';

COMMENT ON COLUMN MASTER.KLS_PROD_KONS.IS_AUTO_LINK IS 'Автоматическая привязка';

COMMENT ON COLUMN MASTER.KLS_PROD_KONS.P_YEAR IS 'Год ввода';



