--
-- KLS_SHABEXP  (Table) 
--
CREATE TABLE MASTER.KLS_SHABEXP
(
  ID           NUMBER(10)                       NOT NULL,
  FLG_DOSTUP   NUMBER(1),
  DOG_ID       NUMBER(5),
  PROD_ID_NPR  VARCHAR2(5 BYTE),
  STAN_ID      NUMBER(10),
  PRIM_DOG     VARCHAR2(20 BYTE),
  OSOB1        VARCHAR2(33 BYTE),
  OSOB2        VARCHAR2(33 BYTE),
  OSOB3        VARCHAR2(33 BYTE),
  OSOB4        VARCHAR2(33 BYTE),
  POL1         VARCHAR2(30 BYTE),
  POL2         VARCHAR2(30 BYTE),
  POL3         VARCHAR2(30 BYTE),
  POL4         VARCHAR2(30 BYTE),
  NEOB1        VARCHAR2(40 BYTE),
  NEOB2        VARCHAR2(40 BYTE),
  NEOB3        VARCHAR2(40 BYTE),
  NEOB4        VARCHAR2(40 BYTE),
  STAN1        VARCHAR2(40 BYTE),
  STAN2        VARCHAR2(40 BYTE),
  STAN3        VARCHAR2(40 BYTE),
  STAN4        VARCHAR2(40 BYTE),
  DORST1       VARCHAR2(40 BYTE),
  DORST2       VARCHAR2(40 BYTE),
  NM_GR1       VARCHAR2(26 BYTE),
  NM_GR2       VARCHAR2(26 BYTE),
  NM_GR3       VARCHAR2(26 BYTE),
  NM_GR4       VARCHAR2(26 BYTE),
  NM_GR5       VARCHAR2(26 BYTE),
  NM_GR6       VARCHAR2(26 BYTE),
  NM_GR7       VARCHAR2(26 BYTE),
  NM_GR8       VARCHAR2(26 BYTE),
  NM_GR9       VARCHAR2(26 BYTE),
  PLT_OT1      VARCHAR2(35 BYTE),
  PLT_OT2      VARCHAR2(35 BYTE),
  PLT_OT3      VARCHAR2(35 BYTE),
  PLT_OT4      VARCHAR2(35 BYTE),
  DOCS1        VARCHAR2(35 BYTE),
  DOCS2        VARCHAR2(35 BYTE),
  DOCS3        VARCHAR2(35 BYTE),
  DOCS4        VARCHAR2(35 BYTE),
  TAM1         VARCHAR2(35 BYTE),
  TAM2         VARCHAR2(35 BYTE),
  POS33        VARCHAR2(10 BYTE),
  POS34        VARCHAR2(10 BYTE),
  POS35        VARCHAR2(10 BYTE),
  POS36        VARCHAR2(10 BYTE),
  SHTAMP1      VARCHAR2(50 BYTE),
  SHTAMP2      VARCHAR2(50 BYTE),
  SHTAMP3      VARCHAR2(50 BYTE),
  SHTAMP4      VARCHAR2(50 BYTE),
  SHTAMP5      VARCHAR2(50 BYTE),
  GR1_TXT_EX   VARCHAR2(60 BYTE),
  GR2_TXT_EX   VARCHAR2(60 BYTE),
  MESTO_PAY    VARCHAR2(30 BYTE),
  CNT_VED      NUMBER(4),
  TEX_PD_ID    NUMBER(10),
  INSNUM       VARCHAR2(20 BYTE),
  INSDAT       DATE
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KLS_SHABEXP.FLG_DOSTUP IS '1-активный шаблон';

COMMENT ON COLUMN MASTER.KLS_SHABEXP.DOG_ID IS 'Договор';

COMMENT ON COLUMN MASTER.KLS_SHABEXP.PROD_ID_NPR IS 'Продукт';

COMMENT ON COLUMN MASTER.KLS_SHABEXP.STAN_ID IS 'Станция назначения';

COMMENT ON COLUMN MASTER.KLS_SHABEXP.PRIM_DOG IS 'примечание к договору';

COMMENT ON COLUMN MASTER.KLS_SHABEXP.OSOB1 IS 'Особые отметки';

COMMENT ON COLUMN MASTER.KLS_SHABEXP.INSNUM IS '№ Инструкции экспедитора';

COMMENT ON COLUMN MASTER.KLS_SHABEXP.INSDAT IS 'Дата инструкции экспедитора';



