--
-- KLS_NAPR  (Table) 
--
CREATE TABLE MASTER.KLS_NAPR
(
  ID           NUMBER(2)                        NOT NULL,
  NAPR_NAME    VARCHAR2(50 BYTE),
  NAPR_MOS_ID  NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


