--
-- KLS_PROD  (Table) 
--
CREATE TABLE MASTER.KLS_PROD
(
  ID_NPR           VARCHAR2(5 BYTE)             NOT NULL,
  ID_KIND_NPR      VARCHAR2(5 BYTE),
  ID_GROUP_NPR     VARCHAR2(5 BYTE),
  NAME_NPR         VARCHAR2(40 BYTE),
  LONG_NAME_NPR    VARCHAR2(250 BYTE),
  ABBR_NPR         VARCHAR2(20 BYTE),
  ID               NUMBER(10),
  FLG_ALLOWED      NUMBER(1),
  GOST_NPR         VARCHAR2(40 BYTE),
  GD_KOD_NPR       VARCHAR2(6 BYTE),
  GD_NAME_NPR      VARCHAR2(100 BYTE),
  KOD_10           VARCHAR2(10 BYTE),
  KOD_OKDP         VARCHAR2(12 BYTE),
  KOD_FAS_MSK      NUMBER(3),
  ED_IZ            VARCHAR2(5 BYTE),
  NORMOTGR         NUMBER(4,1),
  FASOVKA          NUMBER(1),
  VOL_FAS          NUMBER(6,3),
  DOR_NALOG        NUMBER(2),
  AKCIZ            NUMBER(1),
  PROD_NAR_ID      NUMBER(10)                   DEFAULT 0,
  PROD_PLAN_ID     NUMBER(10),
  PROD_GU12_ID     VARCHAR2(10 BYTE),
  MOS_GRP_ID       VARCHAR2(10 BYTE),
  AZC_PR_GRP_ID    NUMBER(10),
  ID_GROUP_NPR_GD  VARCHAR2(5 BYTE),
  AVG_FACT_PL      NUMBER(6,4),
  SF_NAME          VARCHAR2(250 BYTE),
  KSSS_PROD_ID     VARCHAR2(8 BYTE),
  MATNR            VARCHAR2(8 BYTE),
  UNP_ID           NUMBER(10),
  ANALIT           NUMBER,
  BILL_POS         NUMBER(10),
  VID_USL_ID       NUMBER(10),
  NAME_GOST        VARCHAR2(250 BYTE),
  SF_GROTP_VIEW    NUMBER(1)                    DEFAULT 1,
  SF_POLUCH_VIEW   NUMBER(1)                    DEFAULT 1,
  SF_NDS_VIEW      NUMBER(1)                    DEFAULT 1,
  NAME_REFINERY    VARCHAR2(50 BYTE),
  AV_KART          NUMBER(6),
  RAZRESH          VARCHAR2(50 BYTE),
  AV_KART_EX       NUMBER(3),
  ISU_KOD          VARCHAR2(8 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_PROD IS 'Справочник продуктов';

COMMENT ON COLUMN MASTER.KLS_PROD.ID_NPR IS 'Нефтепродукт';

COMMENT ON COLUMN MASTER.KLS_PROD.ID_KIND_NPR IS 'Группа (План поставок) - VARCHAR2';

COMMENT ON COLUMN MASTER.KLS_PROD.ID_GROUP_NPR IS 'Группа - ссылка на KLS_PROD.ID_NPR';

COMMENT ON COLUMN MASTER.KLS_PROD.NAME_NPR IS 'Наименование - краткое';

COMMENT ON COLUMN MASTER.KLS_PROD.LONG_NAME_NPR IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_PROD.ABBR_NPR IS 'Аббревиатура';

COMMENT ON COLUMN MASTER.KLS_PROD.ID IS 'ID';

COMMENT ON COLUMN MASTER.KLS_PROD.FLG_ALLOWED IS '1 - может быть отгружен';

COMMENT ON COLUMN MASTER.KLS_PROD.GOST_NPR IS 'ГОСТ или ТУ';

COMMENT ON COLUMN MASTER.KLS_PROD.GD_KOD_NPR IS 'ЖД код';

COMMENT ON COLUMN MASTER.KLS_PROD.GD_NAME_NPR IS 'ЖД наименование';

COMMENT ON COLUMN MASTER.KLS_PROD.KOD_10 IS 'Код ОКП';

COMMENT ON COLUMN MASTER.KLS_PROD.KOD_OKDP IS 'Группа нефтепродуктов';

COMMENT ON COLUMN MASTER.KLS_PROD.KOD_FAS_MSK IS 'Упаковка';

COMMENT ON COLUMN MASTER.KLS_PROD.ED_IZ IS 'Ед.изм.';

COMMENT ON COLUMN MASTER.KLS_PROD.NORMOTGR IS 'Норма отгрузки';

COMMENT ON COLUMN MASTER.KLS_PROD.FASOVKA IS '1 - фасовка';

COMMENT ON COLUMN MASTER.KLS_PROD.VOL_FAS IS 'Объем фасовки';

COMMENT ON COLUMN MASTER.KLS_PROD.AKCIZ IS '1 - Подакцизный';

COMMENT ON COLUMN MASTER.KLS_PROD.PROD_NAR_ID IS 'Группа (Наряды)';

COMMENT ON COLUMN MASTER.KLS_PROD.PROD_PLAN_ID IS 'Группа (План поставок) - NUMBER';

COMMENT ON COLUMN MASTER.KLS_PROD.PROD_GU12_ID IS 'Группа (ГУ12)';

COMMENT ON COLUMN MASTER.KLS_PROD.MOS_GRP_ID IS 'Группа (Для Москвы)';

COMMENT ON COLUMN MASTER.KLS_PROD.AZC_PR_GRP_ID IS 'Группа (АЗС)';

COMMENT ON COLUMN MASTER.KLS_PROD.ID_GROUP_NPR_GD IS 'ID группы нефтепродукта (ЖД)';

COMMENT ON COLUMN MASTER.KLS_PROD.AVG_FACT_PL IS 'Средневзвешенная фактическая плотность';

COMMENT ON COLUMN MASTER.KLS_PROD.SF_NAME IS 'Название для СФ';

COMMENT ON COLUMN MASTER.KLS_PROD.KSSS_PROD_ID IS 'Код КССС';

COMMENT ON COLUMN MASTER.KLS_PROD.MATNR IS 'Код SAP';

COMMENT ON COLUMN MASTER.KLS_PROD.UNP_ID IS 'Код УНП';

COMMENT ON COLUMN MASTER.KLS_PROD.BILL_POS IS 'N позиции в BILL_POS';

COMMENT ON COLUMN MASTER.KLS_PROD.VID_USL_ID IS 'Вид услуги';

COMMENT ON COLUMN MASTER.KLS_PROD.SF_GROTP_VIEW IS 'Отображать наименование грузоотправителя в СФ';

COMMENT ON COLUMN MASTER.KLS_PROD.SF_POLUCH_VIEW IS 'Отображать получателя в СФ';

COMMENT ON COLUMN MASTER.KLS_PROD.SF_NDS_VIEW IS 'Отображать НДС в СФ';

COMMENT ON COLUMN MASTER.KLS_PROD.NAME_REFINERY IS 'Наименование заводское';

COMMENT ON COLUMN MASTER.KLS_PROD.AV_KART IS 'Аварийная  карта';

COMMENT ON COLUMN MASTER.KLS_PROD.AV_KART_EX IS 'Аварийная карта на экспорт';



