--
-- KLS_ST_PRIH_KONS  (Table) 
--
CREATE TABLE MASTER.KLS_ST_PRIH_KONS
(
  ID    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(50 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_ST_PRIH_KONS IS 'Конс.отчетность: Статьи прихода';

COMMENT ON COLUMN MASTER.KLS_ST_PRIH_KONS.ID IS 'Статья прихода';

COMMENT ON COLUMN MASTER.KLS_ST_PRIH_KONS.NAME IS 'Наименование';



