--
-- KLS_PROD_PLAN  (Table) 
--
CREATE TABLE MASTER.KLS_PROD_PLAN
(
  ID           NUMBER(10)                       NOT NULL,
  NAME_NPR     VARCHAR2(40 BYTE),
  ABBR_NPR     VARCHAR2(20 BYTE),
  ORDER_NPR    NUMBER(3),
  PARENT_ID    NUMBER(10),
  FLG_ALLOWED  NUMBER(1)                        DEFAULT 0,
  AVG_FACT_PL  NUMBER(6,4)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KLS_PROD_PLAN.AVG_FACT_PL IS '—редневзвешенна€ фактическа€ плотность';



