--
-- KLS_PASP  (Table) 
--
CREATE TABLE MASTER.KLS_PASP
(
  ID           VARCHAR2(9 BYTE)                 NOT NULL,
  PASP_NUM     VARCHAR2(15 BYTE),
  REZ_NUM      VARCHAR2(15 BYTE),
  PASP_DATE    DATE,
  INSPEKTOR    VARCHAR2(20 BYTE),
  DATE_OFORML  DATE,
  PROD_ID_NPR  VARCHAR2(5 BYTE),
  MESTO_ID     NUMBER(2),
  DATEUPLOAD   DATE,
  DATE_VIR     DATE,
  PASP_TYP     NUMBER(2)                        DEFAULT 1,
  VZLIV        NUMBER(10,2)                     DEFAULT 0,
  PERER_ID     NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_PASP IS 'Паспорта';

COMMENT ON COLUMN MASTER.KLS_PASP.ID IS 'Паспорт';

COMMENT ON COLUMN MASTER.KLS_PASP.PASP_NUM IS 'N паспорта';

COMMENT ON COLUMN MASTER.KLS_PASP.REZ_NUM IS 'N резервуара';

COMMENT ON COLUMN MASTER.KLS_PASP.PASP_DATE IS 'Дата выписки паспорта';

COMMENT ON COLUMN MASTER.KLS_PASP.INSPEKTOR IS 'Инспектор';

COMMENT ON COLUMN MASTER.KLS_PASP.DATE_OFORML IS 'Дата ввода в систему';

COMMENT ON COLUMN MASTER.KLS_PASP.PROD_ID_NPR IS 'Продукт';

COMMENT ON COLUMN MASTER.KLS_PASP.MESTO_ID IS 'Место ввода';

COMMENT ON COLUMN MASTER.KLS_PASP.DATEUPLOAD IS 'Дата загрузки';

COMMENT ON COLUMN MASTER.KLS_PASP.DATE_VIR IS 'Дата изготовления продукта';

COMMENT ON COLUMN MASTER.KLS_PASP.PASP_TYP IS 'Тип паспорта (1-на отгрузку, 2-резервуарный)';

COMMENT ON COLUMN MASTER.KLS_PASP.VZLIV IS 'Взлив в см';

COMMENT ON COLUMN MASTER.KLS_PASP.PERER_ID IS 'Переработчик / производитель';



