--
-- KLS_TIP_AKCIZ  (Table) 
--
CREATE TABLE MASTER.KLS_TIP_AKCIZ
(
  ID    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(150 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_TIP_AKCIZ IS 'Конс.отчетность: Тип акциза';

COMMENT ON COLUMN MASTER.KLS_TIP_AKCIZ.ID IS 'Тип акциза';

COMMENT ON COLUMN MASTER.KLS_TIP_AKCIZ.NAME IS 'Наименование';



