--
-- KLS_ZPU_TYPES  (Table) 
--
CREATE TABLE MASTER.KLS_ZPU_TYPES
(
  ID          NUMBER(10)                        NOT NULL,
  NAME        VARCHAR2(30 BYTE),
  PREFIX      VARCHAR2(30 BYTE),
  PREFIX_NUM  VARCHAR2(10 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_ZPU_TYPES IS 'Справочник типов пломб';

COMMENT ON COLUMN MASTER.KLS_ZPU_TYPES.ID IS 'ID типа пломбы';

COMMENT ON COLUMN MASTER.KLS_ZPU_TYPES.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_ZPU_TYPES.PREFIX IS 'Тип пломбы';

COMMENT ON COLUMN MASTER.KLS_ZPU_TYPES.PREFIX_NUM IS 'Префикс перед номером';



