--
-- KLS_STATES  (Table) 
--
CREATE TABLE MASTER.KLS_STATES
(
  ID             NUMBER(3)                      NOT NULL,
  STATE_NAME     VARCHAR2(30 BYTE),
  SHORT_NAME     VARCHAR2(10 BYTE),
  KOD_STATISTIC  NUMBER(5),
  KOD_MOSCOW     VARCHAR2(3 BYTE),
  NAPR_ID        NUMBER(2),
  GD_KOD         VARCHAR2(10 BYTE),
  KSSS_ID        NUMBER,
  ISU_KOD        VARCHAR2(2 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KLS_STATES.GD_KOD IS '∆ƒ ÍÓ‰';

COMMENT ON COLUMN MASTER.KLS_STATES.ISU_KOD IS ' Ó‰ »—”';



