--
-- KLS_VETKA_OTP  (Table) 
--
CREATE TABLE MASTER.KLS_VETKA_OTP
(
  ID            NUMBER(10)                      NOT NULL,
  VETKA_NAME    VARCHAR2(40 BYTE),
  SHORT_NAME    VARCHAR2(10 BYTE),
  DOSTUP        NUMBER(1),
  ORDNUNG       NUMBER(10),
  MESTO_ID      NUMBER(2),
  LOAD_TYPE_ID  NUMBER(2),
  OWNER_ID      NUMBER(6),
  DOSTUP_VETL   NUMBER(1)                       DEFAULT 0
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_VETKA_OTP IS 'Ветки отправителя';

COMMENT ON COLUMN MASTER.KLS_VETKA_OTP.ID IS 'Ветка отправителя';

COMMENT ON COLUMN MASTER.KLS_VETKA_OTP.VETKA_NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_VETKA_OTP.SHORT_NAME IS 'Краткое наименование';

COMMENT ON COLUMN MASTER.KLS_VETKA_OTP.DOSTUP IS 'Доступ';

COMMENT ON COLUMN MASTER.KLS_VETKA_OTP.ORDNUNG IS 'Порядок';

COMMENT ON COLUMN MASTER.KLS_VETKA_OTP.MESTO_ID IS 'Место отгрузки';

COMMENT ON COLUMN MASTER.KLS_VETKA_OTP.LOAD_TYPE_ID IS 'Тип транспортировки';

COMMENT ON COLUMN MASTER.KLS_VETKA_OTP.OWNER_ID IS 'Владелец';

COMMENT ON COLUMN MASTER.KLS_VETKA_OTP.DOSTUP_VETL IS 'Доступ - на ст.Ветласян';



