--
-- KLS_ORG_KIND_RELATIONS  (Table) 
--
CREATE TABLE MASTER.KLS_ORG_KIND_RELATIONS
(
  ID    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(100 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


