--
-- KLS_MESTO  (Table) 
--
CREATE TABLE MASTER.KLS_MESTO
(
  ID              NUMBER(2)                     NOT NULL,
  MESTO_NAME      VARCHAR2(35 BYTE),
  MESTO_SVEDNAME  VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


