--
-- KLS_TIP_OP_KONS  (Table) 
--
CREATE TABLE MASTER.KLS_TIP_OP_KONS
(
  ID    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_TIP_OP_KONS IS 'Конс.отчетность: Типы операций';

COMMENT ON COLUMN MASTER.KLS_TIP_OP_KONS.ID IS 'Тип операции';

COMMENT ON COLUMN MASTER.KLS_TIP_OP_KONS.NAME IS 'Наименование';



