--
-- KLS_PROD_MOSGRP  (Table) 
--
CREATE TABLE MASTER.KLS_PROD_MOSGRP
(
  ID          VARCHAR2(10 BYTE)                 NOT NULL,
  NAME        VARCHAR2(30 BYTE),
  ORDER_GDPL  NUMBER(2),
  NAME_GDPL   VARCHAR2(30 BYTE),
  COLOR_GDPL  NUMBER(1),
  COLOR_NAME  VARCHAR2(20 BYTE),
  IS_SEND     NUMBER(1)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_PROD_MOSGRP IS 'Группа н/пр (для Москвы - сообщение ТРАНС)';

COMMENT ON COLUMN MASTER.KLS_PROD_MOSGRP.ID IS 'Группа н/пр (для Москвы)';

COMMENT ON COLUMN MASTER.KLS_PROD_MOSGRP.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_PROD_MOSGRP.ORDER_GDPL IS 'Порядок в сообщении ТРАНС';

COMMENT ON COLUMN MASTER.KLS_PROD_MOSGRP.NAME_GDPL IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_PROD_MOSGRP.COLOR_GDPL IS 'Порядок в сообщении ТРАНС';

COMMENT ON COLUMN MASTER.KLS_PROD_MOSGRP.COLOR_NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_PROD_MOSGRP.IS_SEND IS 'Признак отправки';



