--
-- KLS_GD_PRINVAG  (Table) 
--
CREATE TABLE MASTER.KLS_GD_PRINVAG
(
  ID    NUMBER(10)                              NOT NULL,
  ABBR  VARCHAR2(1 BYTE),
  NAME  VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


