--
-- KLS_GD_VID_OTPR  (Table) 
--
CREATE TABLE MASTER.KLS_GD_VID_OTPR
(
  ID    NUMBER(10)                              NOT NULL,
  TAG   VARCHAR2(10 BYTE),
  NAME  VARCHAR2(50 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_GD_VID_OTPR IS 'Виды отправки';

COMMENT ON COLUMN MASTER.KLS_GD_VID_OTPR.ID IS 'Вид отправки';

COMMENT ON COLUMN MASTER.KLS_GD_VID_OTPR.TAG IS 'ТЕГ';

COMMENT ON COLUMN MASTER.KLS_GD_VID_OTPR.NAME IS 'Наименование';



