--
-- KLS_ORATODBF  (Table) 
--
CREATE TABLE MASTER.KLS_ORATODBF
(
  ID                VARCHAR2(15 BYTE)           NOT NULL,
  SOURCEQUERY       CLOB,
  DESTINATIONTABLE  VARCHAR2(150 BYTE),
  COPYTOTABLE       VARCHAR2(150 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


