--
-- KLS_VIDDOG  (Table) 
--
CREATE TABLE MASTER.KLS_VIDDOG
(
  ID           NUMBER(2)                        NOT NULL,
  VIDDOG_NAME  VARCHAR2(30 BYTE),
  IS_AGENT     NUMBER(2),
  ISU_KOD      NUMBER(3)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KLS_VIDDOG.ISU_KOD IS 'Вид договора в ИСУ Переработка';



