--
-- KLS_VZISKTXT  (Table) 
--
CREATE TABLE MASTER.KLS_VZISKTXT
(
  ID      NUMBER,
  GR1     VARCHAR2(50 BYTE),
  GR2     VARCHAR2(50 BYTE),
  VZISK1  VARCHAR2(50 BYTE),
  VZISK2  VARCHAR2(50 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


