--
-- KLS_DOG  (Table) 
--
CREATE TABLE MASTER.KLS_DOG
(
  ID                   NUMBER(5)                DEFAULT 0                     NOT NULL,
  DOG_NUMBER           VARCHAR2(30 BYTE),
  SHORT_NUMBER         VARCHAR2(11 BYTE),
  DOG_BEGIN_DATE       DATE,
  DOG_END_DATE         DATE,
  DOG_DATE             DATE,
  DOG_YEAR             NUMBER(4),
  REP_KOD              VARCHAR2(6 BYTE),
  PREDPR_ID            NUMBER(6),
  INSURE_ID            NUMBER(5),
  VIDDOG_ID            NUMBER(2),
  GROUPDOG_ID          NUMBER(2),
  GOSPROG_ID           NUMBER(2),
  LUKDOG_ID            NUMBER(5),
  USL_OPL_ID           NUMBER(10),
  SALDO_01042002       NUMBER(15,2),
  SALDO_01042002_PROD  NUMBER(15,2),
  MAINDOG_ID           NUMBER(5),
  SALDO_01072002       NUMBER(18,2)             DEFAULT 0,
  SALDO_01_07_2002     NUMBER(18,2)             DEFAULT 0,
  APPL_TAG             VARCHAR2(6 BYTE),
  SALDO_01122002       NUMBER(12,2)             DEFAULT 0,
  IS_AGENT             NUMBER(10)               DEFAULT NULL,
  AGENT_ID             NUMBER(10),
  PLAT_DOG_NUMBER      VARCHAR2(30 BYTE),
  ZAKAZ_CONTACT_ID     NUMBER(10),
  UNP_ID               NUMBER(10),
  AGENT_DOG_NUMBER     VARCHAR2(30 BYTE),
  ISU_KOD_DOG_TEST     VARCHAR2(13 BYTE),
  ISU_KOD_DOG          VARCHAR2(13 BYTE),
  ISU_KOD_DOG_USLUG    VARCHAR2(10 BYTE),
  ISU_KOD_DOG_TAR      VARCHAR2(10 BYTE),
  ISU_KOD_DOG_VOZN     VARCHAR2(10 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_DOG IS 'Договора';

COMMENT ON COLUMN MASTER.KLS_DOG.DOG_NUMBER IS 'Полный номер договора';

COMMENT ON COLUMN MASTER.KLS_DOG.SHORT_NUMBER IS 'Краткий номер договора';

COMMENT ON COLUMN MASTER.KLS_DOG.DOG_BEGIN_DATE IS 'С даты';

COMMENT ON COLUMN MASTER.KLS_DOG.DOG_END_DATE IS 'По дату';

COMMENT ON COLUMN MASTER.KLS_DOG.DOG_DATE IS 'Дата регистрации';

COMMENT ON COLUMN MASTER.KLS_DOG.DOG_YEAR IS 'Год';

COMMENT ON COLUMN MASTER.KLS_DOG.PREDPR_ID IS 'Контрагент (с кем договор)';

COMMENT ON COLUMN MASTER.KLS_DOG.INSURE_ID IS 'Договор страхования';

COMMENT ON COLUMN MASTER.KLS_DOG.VIDDOG_ID IS 'Вид договора';

COMMENT ON COLUMN MASTER.KLS_DOG.GROUPDOG_ID IS 'Группа договоров';

COMMENT ON COLUMN MASTER.KLS_DOG.GOSPROG_ID IS 'Госпрограмма';

COMMENT ON COLUMN MASTER.KLS_DOG.LUKDOG_ID IS 'Договор с Компанией';

COMMENT ON COLUMN MASTER.KLS_DOG.USL_OPL_ID IS 'Условия оплаты';

COMMENT ON COLUMN MASTER.KLS_DOG.MAINDOG_ID IS 'В рамках договора с Компанией';

COMMENT ON COLUMN MASTER.KLS_DOG.IS_AGENT IS 'Принадлежность договора';

COMMENT ON COLUMN MASTER.KLS_DOG.AGENT_ID IS 'Владелец договора';

COMMENT ON COLUMN MASTER.KLS_DOG.PLAT_DOG_NUMBER IS 'Номер  договора у контрагента';

COMMENT ON COLUMN MASTER.KLS_DOG.UNP_ID IS 'ID из справочника договоров УНП';

COMMENT ON COLUMN MASTER.KLS_DOG.AGENT_DOG_NUMBER IS 'Номер договора у владельца';

COMMENT ON COLUMN MASTER.KLS_DOG.ISU_KOD_DOG_TEST IS 'Код договора в ИСУ (тестовая база)';

COMMENT ON COLUMN MASTER.KLS_DOG.ISU_KOD_DOG IS 'Код договора в ИСУ (продуктив)';



