--
-- KLS_DIAGRAM_TYPE  (Table) 
--
CREATE TABLE MASTER.KLS_DIAGRAM_TYPE
(
  ID    NUMBER(10)                              NOT NULL,
  TAG   VARCHAR2(10 BYTE),
  NAME  VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KLS_DIAGRAM_TYPE.ID IS 'Тип диаграммы';

COMMENT ON COLUMN MASTER.KLS_DIAGRAM_TYPE.TAG IS 'ТЕГ';

COMMENT ON COLUMN MASTER.KLS_DIAGRAM_TYPE.NAME IS 'Наименование';



