--
-- KLS_PROD_PASP_UNP  (Table) 
--
CREATE TABLE MASTER.KLS_PROD_PASP_UNP
(
  KOD_OIL_PRODUCT  NUMBER                       NOT NULL,
  PROD_ID_NPR      VARCHAR2(5 BYTE),
  IS_AUTO_LINK     NUMBER(1)                    DEFAULT 1
)
TABLESPACE USERS2
NOCOMPRESS ;


