--
-- KLS_PREDPR_RS  (Table) 
--
CREATE TABLE MASTER.KLS_PREDPR_RS
(
  ID         NUMBER(10)                         NOT NULL,
  PREDPR_ID  NUMBER(10),
  BANKS_ID   NUMBER(10),
  RS         VARCHAR2(20 BYTE),
  IS_MAIN    NUMBER(1)                          DEFAULT 0
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_PREDPR_RS IS 'Расчетные счета';

COMMENT ON COLUMN MASTER.KLS_PREDPR_RS.ID IS 'Расчетный счет';

COMMENT ON COLUMN MASTER.KLS_PREDPR_RS.PREDPR_ID IS 'Предприятие';

COMMENT ON COLUMN MASTER.KLS_PREDPR_RS.BANKS_ID IS 'Банк';

COMMENT ON COLUMN MASTER.KLS_PREDPR_RS.RS IS 'Расчетный счет';

COMMENT ON COLUMN MASTER.KLS_PREDPR_RS.IS_MAIN IS 'Признак - основной';



