--
-- KLS_SHABVOZ  (Table) 
--
CREATE TABLE MASTER.KLS_SHABVOZ
(
  ID           NUMBER(10),
  STANOTP_ID   NUMBER(10),
  TEX_PD_ID    NUMBER(10),
  GROTP_ID     NUMBER(6),
  STAN_ID      NUMBER(10),
  VETKA_ID     NUMBER(4),
  POLUCH_ID    NUMBER(6),
  FLG_FORMA_2  NUMBER(10),
  PROD_ID_NPR  VARCHAR2(5 BYTE),
  PRIM         VARCHAR2(100 BYTE),
  GR4          VARCHAR2(100 BYTE),
  K_TAR        VARCHAR2(10 BYTE),
  INPUT_DATE   DATE,
  TRANSPORT    VARCHAR2(20 BYTE),
  IS_EXP       NUMBER(1),
  EXPED_ID     NUMBER(6),
  GU12_A_ID    NUMBER(10),
  VZISK_ID     NUMBER(10),
  GROTP_BANK   VARCHAR2(60 BYTE),
  GROTP_RS     VARCHAR2(20 BYTE),
  TEX_PD_BANK  VARCHAR2(60 BYTE),
  TEX_PD_RS    VARCHAR2(20 BYTE),
  SHAB_NUM     NUMBER(10),
  SHAB_DATE    DATE,
  SHAB_NAME    VARCHAR2(30 BYTE),
  DOP_GRINF1   VARCHAR2(80 BYTE),
  DOP_GRINF2   VARCHAR2(80 BYTE),
  VZISK2       VARCHAR2(80 BYTE),
  VZISK3       VARCHAR2(80 BYTE),
  DOP_PLAT     VARCHAR2(60 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_SHABVOZ IS 'Шаблоны накладных на возврат';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.STANOTP_ID IS 'Станция отправления';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.TEX_PD_ID IS 'ТЕХ ПД';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.GROTP_ID IS 'Грузоотправитель';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.STAN_ID IS 'Станция назначения';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.VETKA_ID IS 'Ветка получателя';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.POLUCH_ID IS 'Получатель';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.FLG_FORMA_2 IS 'Вид расчета тарифа';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.PROD_ID_NPR IS 'Нефтепродукт';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.PRIM IS 'Примечание';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.GR4 IS 'Графа 4';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.K_TAR IS 'Код искл. тарифа';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.INPUT_DATE IS 'Дата ввода';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.TRANSPORT IS 'N транспорта';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.IS_EXP IS '1-Экспорт, 0-по России';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.EXPED_ID IS 'Экспедитор';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.GU12_A_ID IS 'Заявка на перевозку';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.GROTP_BANK IS 'Банк грузоотправителя';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.GROTP_RS IS 'Р/с грузоотправителя';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.TEX_PD_BANK IS 'Банк плательщика тарифа';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.TEX_PD_RS IS 'Р/с плательщика тарифа';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.SHAB_NUM IS 'N шаблона';

COMMENT ON COLUMN MASTER.KLS_SHABVOZ.SHAB_DATE IS 'Дата шаблона';



