--
-- KLS_PROD_GR2GR_DESC  (Table) 
--
CREATE TABLE MASTER.KLS_PROD_GR2GR_DESC
(
  ID                  NUMBER(10)                NOT NULL,
  PROD_GROUPS_ID_1    NUMBER(10),
  PROD_GROUPS_ID_2    NUMBER(10),
  IS_AUTO_LINK        NUMBER(1)                 DEFAULT 1,
  PROD_TYPE_GRP_ID_1  NUMBER(10),
  PROD_TYPE_GRP_ID_2  NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_PROD_GR2GR_DESC IS 'Группировки продуктов между собой';

COMMENT ON COLUMN MASTER.KLS_PROD_GR2GR_DESC.ID IS 'Группировки продуктов';

COMMENT ON COLUMN MASTER.KLS_PROD_GR2GR_DESC.PROD_GROUPS_ID_1 IS 'Группировка 1';

COMMENT ON COLUMN MASTER.KLS_PROD_GR2GR_DESC.PROD_GROUPS_ID_2 IS 'Группировка 2';

COMMENT ON COLUMN MASTER.KLS_PROD_GR2GR_DESC.IS_AUTO_LINK IS 'Автоматическая связь';

COMMENT ON COLUMN MASTER.KLS_PROD_GR2GR_DESC.PROD_TYPE_GRP_ID_1 IS 'Тип группировки 1';

COMMENT ON COLUMN MASTER.KLS_PROD_GR2GR_DESC.PROD_TYPE_GRP_ID_2 IS 'Тип группировки 2';



