--
-- KLS_DECADA  (Table) 
--
CREATE TABLE MASTER.KLS_DECADA
(
  KOD       NUMBER(5)                           NOT NULL,
  DATEPLAN  DATE,
  YEARDEC   NUMBER(4),
  MONTHDEC  NUMBER(2),
  DEC       NUMBER(1),
  DATEDECN  DATE,
  DATEDECK  DATE
)
TABLESPACE USERS2
NOCOMPRESS ;


