--
-- KLS_CAT_CEN_GROUP  (Table) 
--
CREATE TABLE MASTER.KLS_CAT_CEN_GROUP
(
  ID                  NUMBER(2)                 NOT NULL,
  CAT_CEN_GROUP_NAME  VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


