--
-- KLS_PLAN_KIND  (Table) 
--
CREATE TABLE MASTER.KLS_PLAN_KIND
(
  ID    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KLS_PLAN_KIND.NAME IS 'Наименование';



