--
-- KLS_BANKS  (Table) 
--
CREATE TABLE MASTER.KLS_BANKS
(
  ID         NUMBER(10)                         NOT NULL,
  KORS       VARCHAR2(20 BYTE),
  BIK        VARCHAR2(9 BYTE),
  BANK_NAME  VARCHAR2(100 BYTE),
  POSTINDEX  VARCHAR2(6 BYTE),
  ADDRESS    VARCHAR2(100 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_BANKS IS 'Банки';

COMMENT ON COLUMN MASTER.KLS_BANKS.ID IS 'ID';

COMMENT ON COLUMN MASTER.KLS_BANKS.KORS IS 'Корсчет';

COMMENT ON COLUMN MASTER.KLS_BANKS.BIK IS 'БИК';

COMMENT ON COLUMN MASTER.KLS_BANKS.BANK_NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_BANKS.POSTINDEX IS 'Почтовый индекс';

COMMENT ON COLUMN MASTER.KLS_BANKS.ADDRESS IS 'Адрес';



