--
-- KLS_PAYFORM  (Table) 
--
CREATE TABLE MASTER.KLS_PAYFORM
(
  ID             NUMBER(2)                      NOT NULL,
  PAYFORM_NAME   VARCHAR2(20 BYTE),
  PAYFORM_GR_ID  NUMBER(10),
  MOSCOW_ID      NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


