--
-- KLS_VAG_STOIM_ISPOLZ  (Table) 
--
CREATE TABLE MASTER.KLS_VAG_STOIM_ISPOLZ
(
  ID           NUMBER(10),
  VAGOWNER_ID  NUMBER(10),
  BEG_DIST     NUMBER(10),
  END_DIST     NUMBER(10),
  STOIMOST     NUMBER(10,2),
  KOL_DN       NUMBER(10),
  BEG_DATE     DATE,
  END_DATE     DATE
)
TABLESPACE USERS2
NOCOMPRESS ;


