--
-- KLS_GD_TIP_PATH  (Table) 
--
CREATE TABLE MASTER.KLS_GD_TIP_PATH
(
  ID           NUMBER(10)                       NOT NULL,
  NAME_STAN    VARCHAR2(100 BYTE),
  NAME_VETKA   VARCHAR2(100 BYTE),
  NAME_POLUCH  VARCHAR2(100 BYTE),
  NAME_STATE   VARCHAR2(100 BYTE),
  SORTBY       NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_GD_TIP_PATH IS 'Типы пунктов маршрута';

COMMENT ON COLUMN MASTER.KLS_GD_TIP_PATH.ID IS 'Тип пункта маршрута';

COMMENT ON COLUMN MASTER.KLS_GD_TIP_PATH.NAME_STAN IS 'Наименование типа станции';

COMMENT ON COLUMN MASTER.KLS_GD_TIP_PATH.NAME_VETKA IS 'Наименование типа ветки';

COMMENT ON COLUMN MASTER.KLS_GD_TIP_PATH.NAME_POLUCH IS 'Наименование типа получателя';

COMMENT ON COLUMN MASTER.KLS_GD_TIP_PATH.NAME_STATE IS 'Наименование типа страны';

COMMENT ON COLUMN MASTER.KLS_GD_TIP_PATH.SORTBY IS 'Порядок';



