--
-- KLS_DOG_MAIN  (Table) 
--
CREATE TABLE MASTER.KLS_DOG_MAIN
(
  ID           NUMBER(10)                       NOT NULL,
  DOG_ID       NUMBER(10),
  IS_AGENT     NUMBER(1),
  FROM_DATE    DATE,
  TO_DATE      DATE,
  NAME         VARCHAR2(30 BYTE),
  U_DOG_ID     NUMBER(10),
  NEFT_DOG_ID  NUMBER(10),
  HRAN_DOG_ID  NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_DOG_MAIN IS 'Базовые договора с Компанией';

COMMENT ON COLUMN MASTER.KLS_DOG_MAIN.ID IS 'ID';

COMMENT ON COLUMN MASTER.KLS_DOG_MAIN.DOG_ID IS 'Договор';

COMMENT ON COLUMN MASTER.KLS_DOG_MAIN.IS_AGENT IS 'Тип';

COMMENT ON COLUMN MASTER.KLS_DOG_MAIN.FROM_DATE IS 'С даты';

COMMENT ON COLUMN MASTER.KLS_DOG_MAIN.TO_DATE IS 'По дату';

COMMENT ON COLUMN MASTER.KLS_DOG_MAIN.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_DOG_MAIN.U_DOG_ID IS 'Базовое условие';

COMMENT ON COLUMN MASTER.KLS_DOG_MAIN.NEFT_DOG_ID IS 'Договор по перевалке нефти';

COMMENT ON COLUMN MASTER.KLS_DOG_MAIN.HRAN_DOG_ID IS 'Договор хранения';



