--
-- KLS_OWNERSHIP  (Table) 
--
CREATE TABLE MASTER.KLS_OWNERSHIP
(
  ID              NUMBER(3)                     NOT NULL,
  OWNERSHIP_NAME  VARCHAR2(70 BYTE),
  ANALIT_ID       NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


