--
-- KLS_DIAGRAM_KIND  (Table) 
--
CREATE TABLE MASTER.KLS_DIAGRAM_KIND
(
  ID            NUMBER(10)                      NOT NULL,
  TAG           VARCHAR2(30 BYTE),
  DIAGRAM_TYPE  VARCHAR2(10 BYTE),
  NAME          VARCHAR2(50 BYTE),
  SORTBY        NUMBER(10),
  ICON_NUM      NUMBER(2)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KLS_DIAGRAM_KIND.ID IS 'Вид диаграммы';

COMMENT ON COLUMN MASTER.KLS_DIAGRAM_KIND.TAG IS 'ТЕГ';

COMMENT ON COLUMN MASTER.KLS_DIAGRAM_KIND.DIAGRAM_TYPE IS 'Тип диаграммы';

COMMENT ON COLUMN MASTER.KLS_DIAGRAM_KIND.NAME IS 'Наименование';



