--
-- KLS_STATUS_MONTH_REESTR  (Table) 
--
CREATE TABLE MASTER.KLS_STATUS_MONTH_REESTR
(
  ID    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(50 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_STATUS_MONTH_REESTR IS 'Статус реестра заданий';



