--
-- KLS_VID_REAL_KONS  (Table) 
--
CREATE TABLE MASTER.KLS_VID_REAL_KONS
(
  ID    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_VID_REAL_KONS IS 'Конс.отчетность: Вид реализации';

COMMENT ON COLUMN MASTER.KLS_VID_REAL_KONS.ID IS 'Вид реализации';

COMMENT ON COLUMN MASTER.KLS_VID_REAL_KONS.NAME IS 'Наименование';



