--
-- KLS_TEX_PD  (Table) 
--
CREATE TABLE MASTER.KLS_TEX_PD
(
  ID                  NUMBER(10)                NOT NULL,
  GROTP_ID            NUMBER(6)                 NOT NULL,
  GROTP_OKPO          VARCHAR2(10 BYTE),
  PLATTARIF_ID        NUMBER(6),
  TEX_PD_NAME         VARCHAR2(50 BYTE),
  BANK                VARCHAR2(60 BYTE),
  RS                  VARCHAR2(20 BYTE),
  GROTP_SHORT_NAME    VARCHAR2(50 BYTE),
  PLATTAR_SHORT_NAME  VARCHAR2(50 BYTE),
  KSSS_PLATTARIF_ID   VARCHAR2(10 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


