--
-- KLS_KODIF_PASP_UNP  (Table) 
--
CREATE TABLE MASTER.KLS_KODIF_PASP_UNP
(
  KOD_POKAZATEL  NUMBER                         NOT NULL,
  KODIF_ID       NUMBER(10),
  IS_AUTO_LINK   NUMBER(1)                      DEFAULT 1
)
TABLESPACE USERS2
NOCOMPRESS ;


