--
-- KLS_NARIAD  (Table) 
--
CREATE TABLE MASTER.KLS_NARIAD
(
  ID            NUMBER(10)                      NOT NULL,
  NUM_NAR       VARCHAR2(15 BYTE),
  DATE_NAR      DATE,
  DATE_END      DATE,
  DOVER_ID      NUMBER(10),
  MESTO_ID      NUMBER(2),
  IS_LOADED     NUMBER(1)                       DEFAULT 0,
  LOAD_TYPE_ID  NUMBER(10),
  DATE_BEG      DATE
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_NARIAD IS 'Разрешения на отгрузку / Наряды';

COMMENT ON COLUMN MASTER.KLS_NARIAD.NUM_NAR IS '№ наряда';

COMMENT ON COLUMN MASTER.KLS_NARIAD.DATE_NAR IS 'Дата наряда';

COMMENT ON COLUMN MASTER.KLS_NARIAD.DATE_END IS 'Дата окончания действия';

COMMENT ON COLUMN MASTER.KLS_NARIAD.DOVER_ID IS 'Доверенность';

COMMENT ON COLUMN MASTER.KLS_NARIAD.MESTO_ID IS 'Место отгрузки';

COMMENT ON COLUMN MASTER.KLS_NARIAD.IS_LOADED IS '1 - загружен из DBF';

COMMENT ON COLUMN MASTER.KLS_NARIAD.LOAD_TYPE_ID IS 'тип транспортировки';

COMMENT ON COLUMN MASTER.KLS_NARIAD.DATE_BEG IS 'С даты';



