--
-- KLS_STAN  (Table) 
--
CREATE TABLE MASTER.KLS_STAN
(
  STAN_KOD      NUMBER(6),
  ID            NUMBER(10)                      NOT NULL,
  STAN_NAME     VARCHAR2(50 BYTE),
  AREN_DAYS     NUMBER(3),
  RAST          NUMBER(5),
  REGION_ID     NUMBER(3),
  GDOR_ID       NUMBER(2),
  OTDELENIE     VARCHAR2(2 BYTE),
  STATES_ID     NUMBER(10),
  KSSS_STAN_ID  NUMBER,
  ISU_KOD       VARCHAR2(7 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


