--
-- KLS_DOC_NUMS  (Table) 
--
CREATE TABLE MASTER.KLS_DOC_NUMS
(
  DOC_TYPE_ID   NUMBER(10),
  LAST_DOC_NUM  NUMBER(10)                      DEFAULT 0,
  MESTO_ID      NUMBER(10),
  MIN_DOC_NUM   NUMBER(10)                      DEFAULT 1,
  MAX_DOC_NUM   NUMBER(10),
  DOC_RULE_ID   NUMBER(10)                      DEFAULT 1,
  FROM_DATE     DATE,
  TO_DATE       DATE,
  ID            NUMBER(10)                      NOT NULL,
  DOC_PREFIX    VARCHAR2(15 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_DOC_NUMS IS 'Справочник номеров документов';

COMMENT ON COLUMN MASTER.KLS_DOC_NUMS.DOC_TYPE_ID IS 'Тип документа';

COMMENT ON COLUMN MASTER.KLS_DOC_NUMS.LAST_DOC_NUM IS 'Последний номер документа';

COMMENT ON COLUMN MASTER.KLS_DOC_NUMS.MESTO_ID IS 'Место отгрузки';

COMMENT ON COLUMN MASTER.KLS_DOC_NUMS.MIN_DOC_NUM IS 'Минимальный номер документа';

COMMENT ON COLUMN MASTER.KLS_DOC_NUMS.MAX_DOC_NUM IS 'Максимальный номер документа';

COMMENT ON COLUMN MASTER.KLS_DOC_NUMS.DOC_RULE_ID IS 'Правило формирования номера';

COMMENT ON COLUMN MASTER.KLS_DOC_NUMS.FROM_DATE IS 'Начало периода';

COMMENT ON COLUMN MASTER.KLS_DOC_NUMS.TO_DATE IS 'Окончание периода';

COMMENT ON COLUMN MASTER.KLS_DOC_NUMS.DOC_PREFIX IS 'Префикс документа';



