--
-- KLS_HOLDING  (Table) 
--
CREATE TABLE MASTER.KLS_HOLDING
(
  ID            NUMBER(3)                       NOT NULL,
  HOLDING_NAME  VARCHAR2(50 BYTE),
  BOSS          VARCHAR2(3 BYTE),
  SORTBY        NUMBER(10)                      DEFAULT 99
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KLS_HOLDING.SORTBY IS 'Порядок';



