--
-- KLS_MASTER_POGR  (Table) 
--
CREATE TABLE MASTER.KLS_MASTER_POGR
(
  ID    NUMBER(7),
  NAME  VARCHAR2(50 BYTE),
  POST  VARCHAR2(50 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_MASTER_POGR IS 'Справочник мастеров погрузки(для печати накладных из Модуля отгрузки)';

COMMENT ON COLUMN MASTER.KLS_MASTER_POGR.NAME IS 'ФИО мастера погрузки';

COMMENT ON COLUMN MASTER.KLS_MASTER_POGR.POST IS 'Должность';



