--
-- KLS_GD_SOBSTVVAG  (Table) 
--
CREATE TABLE MASTER.KLS_GD_SOBSTVVAG
(
  ID           NUMBER(12),
  NAME         VARCHAR2(30 BYTE),
  VAGOWNER_ID  NUMBER(10),
  LOAD_ABBR    VARCHAR2(3 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


