--
-- KLS_OTGR_POST_KONS  (Table) 
--
CREATE TABLE MASTER.KLS_OTGR_POST_KONS
(
  ID    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_OTGR_POST_KONS IS 'Конс.отчетность: Отгрузка/поставка';

COMMENT ON COLUMN MASTER.KLS_OTGR_POST_KONS.ID IS 'Отгрузка_поставка';

COMMENT ON COLUMN MASTER.KLS_OTGR_POST_KONS.NAME IS 'Наименование';



