--
-- KLS_ORG_KIND  (Table) 
--
CREATE TABLE MASTER.KLS_ORG_KIND
(
  ID               NUMBER(10)                   NOT NULL,
  NAME             VARCHAR2(70 BYTE),
  GROUP_KIND_ID    NUMBER(10),
  GROUP_KIND_NAME  VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KLS_ORG_KIND.NAME IS 'вид ОСЕ';

COMMENT ON COLUMN MASTER.KLS_ORG_KIND.GROUP_KIND_ID IS 'Группа объектов';

COMMENT ON COLUMN MASTER.KLS_ORG_KIND.GROUP_KIND_NAME IS 'Группа объектов';



