--
-- KLS_COUNTER  (Table) 
--
CREATE TABLE MASTER.KLS_COUNTER
(
  ID                NUMBER                      NOT NULL,
  COUNTER_NAME      VARCHAR2(50 BYTE),
  COUNTER_QUESRY    VARCHAR2(1024 BYTE),
  DETAIL_QUERY      VARCHAR2(1024 BYTE),
  XCAPTION          VARCHAR2(50 BYTE),
  YCAPTION          VARCHAR2(50 BYTE),
  DETAILINFO_QUERY  VARCHAR2(2048 BYTE),
  LOGIN             VARCHAR2(30 BYTE),
  PASSWORD          VARCHAR2(30 BYTE),
  DATABASE          VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


