--
-- KLS_GROUPDOG  (Table) 
--
CREATE TABLE MASTER.KLS_GROUPDOG
(
  ID             NUMBER(2)                      NOT NULL,
  GROUPDOG_NAME  VARCHAR2(40 BYTE),
  FIN_NAME1      VARCHAR2(40 BYTE),
  FIN_NAME2      VARCHAR2(40 BYTE),
  ISU_KOD        NUMBER(3)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KLS_GROUPDOG.ISU_KOD IS 'Вид договора из ИСУ Переработка';



