--
-- KLS_GP_NAPR  (Table) 
--
CREATE TABLE MASTER.KLS_GP_NAPR
(
  ID              NUMBER(10)                    NOT NULL,
  NAME            VARCHAR2(30 BYTE),
  GOSPROG_ID      NUMBER(2),
  KSSS_ID         VARCHAR2(10 BYTE),
  PARENT_KSSS_ID  VARCHAR2(10 BYTE),
  PARENT_NAME     VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KLS_GP_NAPR.ID IS 'Получатель по госпрограмме';

COMMENT ON COLUMN MASTER.KLS_GP_NAPR.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_GP_NAPR.KSSS_ID IS 'Код КССС';

COMMENT ON COLUMN MASTER.KLS_GP_NAPR.PARENT_KSSS_ID IS 'Код КССС для отчета';

COMMENT ON COLUMN MASTER.KLS_GP_NAPR.PARENT_NAME IS 'Наименование для отчета';



