--
-- KLS_REGION  (Table) 
--
CREATE TABLE MASTER.KLS_REGION
(
  ID             NUMBER(3)                      NOT NULL,
  REGION_NAME    VARCHAR2(30 BYTE),
  OKATO          VARCHAR2(3 BYTE),
  KOD_MOSCOW     VARCHAR2(3 BYTE),
  SHORT_NAME     VARCHAR2(15 BYTE),
  KOD_STATISTIC  VARCHAR2(5 BYTE),
  STATES_ID      NUMBER(3),
  KSSS_ID        NUMBER
)
TABLESPACE USERS2
NOCOMPRESS ;


