--
-- KLS_PAYDELAY  (Table) 
--
CREATE TABLE MASTER.KLS_PAYDELAY
(
  ID             NUMBER(2)                      NOT NULL,
  PAYDELAY_NAME  VARCHAR2(35 BYTE),
  SHORT_NAME     VARCHAR2(6 BYTE),
  ISU_KOD        VARCHAR2(10 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KLS_PAYDELAY.ISU_KOD IS 'Код отсрочки платежа в ИСУ Переработка';



