--
-- KLS_VID_POST_KONS  (Table) 
--
CREATE TABLE MASTER.KLS_VID_POST_KONS
(
  ID    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_VID_POST_KONS IS 'Конс.отчетность: Вид поставки';

COMMENT ON COLUMN MASTER.KLS_VID_POST_KONS.ID IS 'Вид поставки';

COMMENT ON COLUMN MASTER.KLS_VID_POST_KONS.NAME IS 'Наименование';



