--
-- KLS_ROLE  (Table) 
--
CREATE TABLE MASTER.KLS_ROLE
(
  ID           NUMBER(2)                        NOT NULL,
  PREDPR_ROLE  VARCHAR2(50 BYTE),
  STAN_ROLE    VARCHAR2(50 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


