--
-- KLS_DOG_PARUS  (Table) 
--
CREATE TABLE MASTER.KLS_DOG_PARUS
(
  BASE_NUMB     VARCHAR2(20 BYTE),
  DOG_ID        NUMBER(10),
  IS_AUTO_LINK  NUMBER(1)                       DEFAULT 1,
  NAME_PLAT     VARCHAR2(50 BYTE),
  IS_ACTUAL     NUMBER(1)                       DEFAULT 1
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_DOG_PARUS IS 'Связь договоро из Паруса и Финансов';

COMMENT ON COLUMN MASTER.KLS_DOG_PARUS.BASE_NUMB IS 'N договора из Паруса';

COMMENT ON COLUMN MASTER.KLS_DOG_PARUS.DOG_ID IS 'ID договора из Финансов';



