--
-- KLS_KALIBR  (Table) 
--
CREATE TABLE MASTER.KLS_KALIBR
(
  ID             VARCHAR2(5 BYTE)               NOT NULL,
  KALIBR_NAME    VARCHAR2(20 BYTE),
  VAGON_MAX_VES  NUMBER(10,3),
  VAGON_AXES     NUMBER(1),
  KOD_ISU        VARCHAR2(5 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


