--
-- KLS_PRIORITY_MONTH_REESTR  (Table) 
--
CREATE TABLE MASTER.KLS_PRIORITY_MONTH_REESTR
(
  ID          NUMBER(10)                        NOT NULL,
  NAME        VARCHAR2(50 BYTE),
  SHORT_NAME  VARCHAR2(10 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_PRIORITY_MONTH_REESTR IS 'Справочник приоритетов заданий в реестре';

COMMENT ON COLUMN MASTER.KLS_PRIORITY_MONTH_REESTR.ID IS 'ID';

COMMENT ON COLUMN MASTER.KLS_PRIORITY_MONTH_REESTR.NAME IS 'Наименование';



