--
-- KLS_VALPASP  (Table) 
--
CREATE TABLE MASTER.KLS_VALPASP
(
  PASP_ID     VARCHAR2(9 BYTE)                  NOT NULL,
  KODIF_ID    NUMBER(5)                         NOT NULL,
  QUAL        VARCHAR2(12 BYTE),
  DATEUPLOAD  DATE
)
TABLESPACE USERS2
NOCOMPRESS ;


