--
-- KLS_DOC_TYPES  (Table) 
--
CREATE TABLE MASTER.KLS_DOC_TYPES
(
  ID             NUMBER(10)                     NOT NULL,
  NAME           VARCHAR2(50 BYTE),
  FIELD_NUM      VARCHAR2(30 BYTE),
  FIELD_DATE     VARCHAR2(30 BYTE),
  FIELD_PREFIX   VARCHAR2(30 BYTE),
  TABLENAME      VARCHAR2(50 BYTE),
  FIELD_ID       VARCHAR2(30 BYTE),
  FIELD_MESTO    VARCHAR2(30 BYTE),
  FIELD_ID_TYPE  VARCHAR2(10 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_DOC_TYPES IS 'Справочник документов';

COMMENT ON COLUMN MASTER.KLS_DOC_TYPES.FIELD_NUM IS 'Поле НОМЕР';

COMMENT ON COLUMN MASTER.KLS_DOC_TYPES.FIELD_DATE IS 'Поле ДАТА';

COMMENT ON COLUMN MASTER.KLS_DOC_TYPES.FIELD_PREFIX IS 'Поле "Префикс номера"';

COMMENT ON COLUMN MASTER.KLS_DOC_TYPES.TABLENAME IS 'Таблица';

COMMENT ON COLUMN MASTER.KLS_DOC_TYPES.FIELD_ID IS 'Поле "ID"';

COMMENT ON COLUMN MASTER.KLS_DOC_TYPES.FIELD_MESTO IS 'Поле "Место оформления"';

COMMENT ON COLUMN MASTER.KLS_DOC_TYPES.FIELD_ID_TYPE IS 'Тип поля ID';



