--
-- KLS_VAGOWNER_TYPES  (Table) 
--
CREATE TABLE MASTER.KLS_VAGOWNER_TYPES
(
  ID       NUMBER(10)                           NOT NULL,
  NAME     VARCHAR2(30 BYTE),
  ISU_KOD  NUMBER(1)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KLS_VAGOWNER_TYPES.ID IS 'Тип собственности';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER_TYPES.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_VAGOWNER_TYPES.ISU_KOD IS 'Код ИСУ';



