--
-- KLS_PLANSTRU  (Table) 
--
CREATE TABLE MASTER.KLS_PLANSTRU
(
  ID               NUMBER(20)                   NOT NULL,
  BEGIN_DATE       DATE,
  END_DATE         DATE,
  NAME             VARCHAR2(50 BYTE),
  LEVEL_POS        NUMBER(5),
  INPUT_DATE       DATE,
  KOD_SGR          NUMBER(3),
  KOD_SPG          NUMBER(3),
  KOD_RZD          NUMBER(3),
  KOD_PRZ          NUMBER(3),
  KOD_GRP          NUMBER(3),
  KOD_PGR          NUMBER(3),
  PARENT_ID        NUMBER(20),
  NAZN_OTG_ID      NUMBER(2),
  VIEW_LEVEL       NUMBER(2),
  REGION_ID        NUMBER(10),
  ORG_KIND_ID      NUMBER(10),
  TIP_REAL_ID      NUMBER(10),
  FOR_ID           NUMBER(3)                    DEFAULT 0,
  FOR_NAME         VARCHAR2(60 BYTE),
  FOR_MOS_ID       NUMBER(20),
  SPF_GROUP_ORDER  NUMBER(2),
  SPF_GROUP_NAME   VARCHAR2(30 BYTE),
  SPF_ORDER        NUMBER(2),
  SPF_NAME         VARCHAR2(30 BYTE),
  LUKOIL_ID        VARCHAR2(10 BYTE),
  IS_RESURS        NUMBER(1)                    DEFAULT 0,
  IS_TO_HRAN       NUMBER(1)                    DEFAULT 0,
  POS_PREDPR_ID    NUMBER(10),
  ISU_KOD          VARCHAR2(15 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KLS_PLANSTRU.REGION_ID IS 'Регион';

COMMENT ON COLUMN MASTER.KLS_PLANSTRU.ORG_KIND_ID IS 'Вид подразделения (1-Нефтебаза, 5-АЗС)';

COMMENT ON COLUMN MASTER.KLS_PLANSTRU.TIP_REAL_ID IS 'Тип реализации (1-реализация, 2-транзит)';

COMMENT ON COLUMN MASTER.KLS_PLANSTRU.FOR_ID IS 'Порядок ДЛЯ''ки';

COMMENT ON COLUMN MASTER.KLS_PLANSTRU.FOR_NAME IS 'Наименование ДЛЯ''ки';

COMMENT ON COLUMN MASTER.KLS_PLANSTRU.FOR_MOS_ID IS 'ID плана поставки для Москвы';

COMMENT ON COLUMN MASTER.KLS_PLANSTRU.SPF_GROUP_ORDER IS 'Порядок группы позиций';

COMMENT ON COLUMN MASTER.KLS_PLANSTRU.SPF_GROUP_NAME IS 'Группа позиций';

COMMENT ON COLUMN MASTER.KLS_PLANSTRU.SPF_ORDER IS 'Порядок подгруппы позиций';

COMMENT ON COLUMN MASTER.KLS_PLANSTRU.SPF_NAME IS 'Подгруппа позиций';

COMMENT ON COLUMN MASTER.KLS_PLANSTRU.LUKOIL_ID IS 'Код плана для Москвы';

COMMENT ON COLUMN MASTER.KLS_PLANSTRU.IS_RESURS IS 'Признак нераспределенного ресурса';

COMMENT ON COLUMN MASTER.KLS_PLANSTRU.IS_TO_HRAN IS '1-Отгрузка на хранение';

COMMENT ON COLUMN MASTER.KLS_PLANSTRU.POS_PREDPR_ID IS 'Контрагент';



