--
-- KLS_VOZN_RST  (Table) 
--
CREATE TABLE MASTER.KLS_VOZN_RST
(
  ID             NUMBER(10)                     NOT NULL,
  IS_AGENT       NUMBER(10)                     DEFAULT NULL,
  BEGIN_DATE     DATE,
  END_DATE       DATE,
  ID_GROUP_NPR   VARCHAR2(5 BYTE),
  PROD_ID_NPR    VARCHAR2(5 BYTE),
  VAGOWN_TYP_ID  NUMBER(10),
  RAST_MIN       NUMBER(10)                     DEFAULT 0,
  RAST_MAX       NUMBER(10)                     DEFAULT 0,
  CENA_VOZN      NUMBER(15,2)                   DEFAULT 0
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_VOZN_RST IS 'Вознаграждения в зависимости от расстояния';

COMMENT ON COLUMN MASTER.KLS_VOZN_RST.ID IS 'Вознаграждение';

COMMENT ON COLUMN MASTER.KLS_VOZN_RST.IS_AGENT IS 'Признак вида договора с ЛУКОЙЛом';

COMMENT ON COLUMN MASTER.KLS_VOZN_RST.BEGIN_DATE IS 'Действет с';

COMMENT ON COLUMN MASTER.KLS_VOZN_RST.END_DATE IS 'Действует по';

COMMENT ON COLUMN MASTER.KLS_VOZN_RST.ID_GROUP_NPR IS 'Группа продукта';

COMMENT ON COLUMN MASTER.KLS_VOZN_RST.PROD_ID_NPR IS 'Продукт';

COMMENT ON COLUMN MASTER.KLS_VOZN_RST.VAGOWN_TYP_ID IS 'Тип собственности';

COMMENT ON COLUMN MASTER.KLS_VOZN_RST.RAST_MIN IS 'Минимальное расстояние';

COMMENT ON COLUMN MASTER.KLS_VOZN_RST.RAST_MAX IS 'Максимальное расстояние';

COMMENT ON COLUMN MASTER.KLS_VOZN_RST.CENA_VOZN IS 'Цена вознаграждения (руб за тн)';



