--
-- KLS_PREDPR_KONS  (Table) 
--
CREATE TABLE MASTER.KLS_PREDPR_KONS
(
  ID         NUMBER(20)                         NOT NULL,
  NAME       VARCHAR2(50 BYTE),
  INN        VARCHAR2(15 BYTE),
  IS_AUTO    NUMBER(1)                          DEFAULT 0,
  PREDPR_ID  NUMBER(6)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_PREDPR_KONS IS 'Конс.отчетность: Справочник предприятий';

COMMENT ON COLUMN MASTER.KLS_PREDPR_KONS.ID IS 'Предприятие';

COMMENT ON COLUMN MASTER.KLS_PREDPR_KONS.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.KLS_PREDPR_KONS.INN IS 'ИНН';

COMMENT ON COLUMN MASTER.KLS_PREDPR_KONS.IS_AUTO IS '0 - Связь в ручную';

COMMENT ON COLUMN MASTER.KLS_PREDPR_KONS.PREDPR_ID IS 'Связь с KLS_PREDPR';



