--
-- KLS_VAG_STATUS  (Table) 
--
CREATE TABLE MASTER.KLS_VAG_STATUS
(
  ID         NUMBER(10)                         NOT NULL,
  NAME       VARCHAR2(20 BYTE),
  FULL_NAME  VARCHAR2(50 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_VAG_STATUS IS 'Состояние вагона';



