--
-- KLS_DOC_RESERV  (Table) 
--
CREATE TABLE MASTER.KLS_DOC_RESERV
(
  TERMINAL_NAME  VARCHAR2(50 BYTE)              NOT NULL,
  OSUSER_NAME    VARCHAR2(50 BYTE)              NOT NULL,
  DOC_TYPE_ID    NUMBER(10)                     NOT NULL,
  MESTO_ID       NUMBER(10)                     NOT NULL,
  NEXT_DOC_NUM   NUMBER(10),
  DOC_NUMS_ID    NUMBER(10),
  DOC_PREFIX     VARCHAR2(15 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KLS_DOC_RESERV IS 'Зарезервированные номера документов';

COMMENT ON COLUMN MASTER.KLS_DOC_RESERV.TERMINAL_NAME IS 'Машина';

COMMENT ON COLUMN MASTER.KLS_DOC_RESERV.OSUSER_NAME IS 'Пользователь';

COMMENT ON COLUMN MASTER.KLS_DOC_RESERV.DOC_TYPE_ID IS 'Тип документа';

COMMENT ON COLUMN MASTER.KLS_DOC_RESERV.MESTO_ID IS 'Место отгрузки';

COMMENT ON COLUMN MASTER.KLS_DOC_RESERV.NEXT_DOC_NUM IS 'Следующий номер документа';

COMMENT ON COLUMN MASTER.KLS_DOC_RESERV.DOC_NUMS_ID IS 'Диапазон номеров';

COMMENT ON COLUMN MASTER.KLS_DOC_RESERV.DOC_PREFIX IS 'Префикс документа';



