--
-- KSSS_MATERIAL  (Table) 
--
CREATE TABLE MASTER.KSSS_MATERIAL
(
  MATERIAL_ID         NUMBER,
  MATNR               VARCHAR2(18 BYTE),
  KLS_NAME            VARCHAR2(40 BYTE),
  ZFASOVKA_ID         NUMBER,
  ZCRPOKP             VARCHAR2(30 BYTE),
  MATERIAL_GROUP1     VARCHAR2(10 BYTE),
  MATERIAL_GROUP2     VARCHAR2(10 BYTE),
  MATERIAL_GROUP3     VARCHAR2(10 BYTE),
  MATERIAL_GROUP4     VARCHAR2(10 BYTE),
  MATERIAL_GROUP5     VARCHAR2(10 BYTE),
  PLGTP               VARCHAR2(2 BYTE),
  EXCISE_GROUP_ID     NUMBER,
  EXCISE_GROUP        VARCHAR2(30 BYTE),
  LANGUAGE_ID         NUMBER,
  FULL_NAME           VARCHAR2(288 BYTE),
  MATERIAL_TYPE_ID    VARCHAR2(25 BYTE),
  UNIT_OF_MEASURE_ID  VARCHAR2(3 BYTE),
  ZCRPOST             VARCHAR2(30 BYTE),
  CLASS               VARCHAR2(18 BYTE),
  ATWRT_TU            VARCHAR2(30 BYTE),
  ATWRT_GOST          VARCHAR2(30 BYTE),
  GROUP_S             VARCHAR2(4 BYTE),
  ATWTB               VARCHAR2(30 BYTE),
  PARENT_MATERIAL_ID  NUMBER,
  S_FLAG              NUMBER,
  SPRAS               VARCHAR2(1 BYTE),
  DATE_FROM           VARCHAR2(9 BYTE),
  DATE_TO             VARCHAR2(9 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


