/* This object may not be sorted properly in the script due to cirular references. */
--
-- KSSS_PREDPR_R3_CUSTOMERS_DESC  (Table) 
--
CREATE TABLE MASTER.KSSS_PREDPR_R3_CUSTOMERS_DESC
(
  KSSS_PREDPR_ID  NUMBER(10)                    NOT NULL,
  R3_CUSTOMERS    VARCHAR2(10 BYTE)             NOT NULL,
  IS_AUTO_LINK    NUMBER(1)                     DEFAULT 1
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KSSS_PREDPR_R3_CUSTOMERS_DESC IS 'Связь КССС - Дебитор R3';

COMMENT ON COLUMN MASTER.KSSS_PREDPR_R3_CUSTOMERS_DESC.KSSS_PREDPR_ID IS 'Контрагент из КССС';

COMMENT ON COLUMN MASTER.KSSS_PREDPR_R3_CUSTOMERS_DESC.R3_CUSTOMERS IS 'Дебитор из R3';

COMMENT ON COLUMN MASTER.KSSS_PREDPR_R3_CUSTOMERS_DESC.IS_AUTO_LINK IS 'Признак автоматической привязки';



