--
-- KSSS_PARTNERS  (Table) 
--
CREATE TABLE MASTER.KSSS_PARTNERS
(
  CONTRAGENT_ID   NUMBER,
  LIFNR           VARCHAR2(10 BYTE),
  KUNNR           VARCHAR2(10 BYTE),
  KLS_NAME        VARCHAR2(140 BYTE),
  SHORTNAME       VARCHAR2(40 BYTE),
  FORM_ID         NUMBER,
  P1              VARCHAR2(16 BYTE),
  STCD2           VARCHAR2(11 BYTE),
  KPP             VARCHAR2(9 BYTE),
  BAHNSK          VARCHAR2(25 BYTE),
  BAHNSD          VARCHAR2(25 BYTE),
  STKZN           NUMBER,
  TYPE_ID         NUMBER,
  DEPENDCOMP_ID   NUMBER,
  HEADCOMP        VARCHAR2(10 BYTE),
  AM_COUNTRY_ID   NUMBER,
  AM_REGION_ID    NUMBER,
  POST_CODE1      VARCHAR2(10 BYTE),
  CITY_NAME       VARCHAR2(255 BYTE),
  STR_SUPPL1      VARCHAR2(255 BYTE),
  STREET          VARCHAR2(255 BYTE),
  HOUSE_NUM1      VARCHAR2(10 BYTE),
  TEL_NUMBER      VARCHAR2(30 BYTE),
  TEL_EXTENDS     VARCHAR2(10 BYTE),
  FAX_NUMBER      VARCHAR2(30 BYTE),
  SMTP_ADDR       VARCHAR2(241 BYTE),
  PA_COUNTRY_ID   NUMBER,
  PA_REGION_ID    NUMBER,
  PO_BOX          VARCHAR2(10 BYTE),
  PO_BOX_LOC      VARCHAR2(255 BYTE),
  STR_SUPPL2      VARCHAR2(40 BYTE),
  LOCATION        VARCHAR2(255 BYTE),
  KVERM           VARCHAR2(30 BYTE),
  S_FLAG          NUMBER(1),
  SPRAS           VARCHAR2(1 BYTE),
  PBG             NUMBER,
  BUDGET_UNIT_ID  NUMBER,
  PROJECT_ID      NUMBER,
  BBUDGMETH       NUMBER,
  BPBGZ_CAT       NUMBER,
  RESIDENT        NUMBER,
  MPS_PROVIDER    NUMBER,
  MPS_KLIENT      NUMBER,
  INDUSTRY_ID     NUMBER,
  DATE_FROM       VARCHAR2(8 BYTE),
  DATE_TO         VARCHAR2(8 BYTE),
  EXTERNAL_ID     NUMBER
)
TABLESPACE USERS2
NOCOMPRESS ;


