--
-- KSSS_PROD  (Table) 
--
CREATE TABLE MASTER.KSSS_PROD
(
  KSSS_PROD_ID  VARCHAR2(10 BYTE),
  FOX_ID        VARCHAR2(5 BYTE),
  NAIM_NPR      VARCHAR2(25 BYTE),
  MATNR         VARCHAR2(8 BYTE),
  OKDP          VARCHAR2(10 BYTE),
  IS_MAIN       NUMBER(1)                       DEFAULT 1
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.KSSS_PROD.IS_MAIN IS 'Основной';



