--
-- KVIT_DATE_VIR  (Table) 
--
CREATE TABLE MASTER.KVIT_DATE_VIR
(
  ID               NUMBER(10)                   NOT NULL,
  BILL_ID          NUMBER(10),
  KVIT_ID          NUMBER(16),
  BILL_POS_ID      NUMBER(10),
  DATE_VIR         DATE,
  VES              NUMBER(14,6)                 DEFAULT 0,
  VES_CIST         NUMBER(14,6)                 DEFAULT 0,
  VZLIV            NUMBER(6)                    DEFAULT 0,
  KOL_NET          NUMBER(14,6)                 DEFAULT 0,
  SUM_PROD         NUMBER(15,2)                 DEFAULT 0,
  SUM_PROD_NDS     NUMBER(15,2)                 DEFAULT 0,
  SUM_AKCIZ        NUMBER(15,2)                 DEFAULT 0,
  SUM_GSM          NUMBER(15,2)                 DEFAULT 0,
  TARIF_ORIG       NUMBER(15,2)                 DEFAULT 0,
  TARIF_ALT        NUMBER(15,2)                 DEFAULT 0,
  TARIF            NUMBER(15,2)                 DEFAULT 0,
  TARIF_NDS        NUMBER(15,2)                 DEFAULT 0,
  TARIF_GUARD      NUMBER(15,2)                 DEFAULT 0,
  TARIF_GUARD_NDS  NUMBER(15,2)                 DEFAULT 0,
  SUM_VOZN11       NUMBER(15,2)                 DEFAULT 0,
  SUM_VOZN11_NDS   NUMBER(15,2)                 DEFAULT 0,
  SUM_VOZN12       NUMBER(15,2)                 DEFAULT 0,
  SUM_VOZN12_NDS   NUMBER(15,2)                 DEFAULT 0,
  SUM_STRAH        NUMBER(15,2)                 DEFAULT 0,
  NOM_SF_POKUP     VARCHAR2(10 BYTE),
  NOM_DOK_POKUP    NUMBER(10),
  DATE_PLAN        DATE,
  TARIF19          NUMBER(15,2)                 DEFAULT 0,
  VES_BRUTTO       NUMBER(14,6)                 DEFAULT 0,
  OWNERSHIP_ID     NUMBER(1)                    DEFAULT 1
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.KVIT_DATE_VIR IS 'Счета фактуры и вагоны по дате выработки';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.ID IS 'ID';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.KVIT_ID IS 'Цистерна';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.BILL_POS_ID IS 'N позиции';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.DATE_VIR IS 'Дата выработки';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.VES IS 'Вес';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.VES_CIST IS 'Вес вагона';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.VZLIV IS 'Взлив или объем';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.KOL_NET IS 'Вес НЕТТО (для НЕФТИ)';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.SUM_PROD IS 'За продукт (без НДС)';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.SUM_PROD_NDS IS 'НДС';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.SUM_AKCIZ IS 'Акциз';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.SUM_GSM IS 'ГСМ';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.TARIF_ORIG IS 'Тариф из квитанции';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.TARIF_ALT IS 'Тариф по альтернативной схеме';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.TARIF IS 'Тариф (без НДС)';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.TARIF_NDS IS 'НДС';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.TARIF_GUARD IS 'За охрану';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.TARIF_GUARD_NDS IS 'НДС за охрану';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.SUM_VOZN11 IS 'Вознаграждение за тонну (без НДС)';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.SUM_VOZN11_NDS IS 'НДС';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.SUM_VOZN12 IS 'Вознаграждение 19-20 (без НДС)';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.SUM_VOZN12_NDS IS 'НДС';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.SUM_STRAH IS 'Страховка';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.NOM_SF_POKUP IS 'СФ на приобретение товара';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.NOM_DOK_POKUP IS 'ID сф на приобретение';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.DATE_PLAN IS 'Месяц';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.TARIF19 IS 'Тариф + Вознаграждение';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.VES_BRUTTO IS 'Вес';

COMMENT ON COLUMN MASTER.KVIT_DATE_VIR.OWNERSHIP_ID IS 'Собственный/Приобретенный';



