--
-- LINK_PARUS_PREDPR  (Table) 
--
CREATE TABLE MASTER.LINK_PARUS_PREDPR
(
  ID            NUMBER(10),
  RN            NUMBER(17),
  PREDPR_ID     NUMBER(6),
  IS_AUTO_LINK  NUMBER(1)                       DEFAULT 1
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.LINK_PARUS_PREDPR.ID IS 'Связь предприятий Паруса и предприятий Финансов';

COMMENT ON COLUMN MASTER.LINK_PARUS_PREDPR.RN IS 'Предприятие Паруса';

COMMENT ON COLUMN MASTER.LINK_PARUS_PREDPR.PREDPR_ID IS 'Предприятие Финансов';

COMMENT ON COLUMN MASTER.LINK_PARUS_PREDPR.IS_AUTO_LINK IS '1 - связь автоматическая';



