--
-- LOAD_FIL_PERIODS  (Table) 
--
CREATE TABLE MASTER.LOAD_FIL_PERIODS
(
  ID           NUMBER(10)                       NOT NULL,
  FILIAL_ID    NUMBER(10)                       NOT NULL,
  DATE_REPORT  DATE,
  FILENAME     VARCHAR2(100 BYTE),
  DATE_LOAD    DATE,
  USER_LOAD    VARCHAR2(240 BYTE),
  REP_TYPE_ID  NUMBER(10)                       NOT NULL,
  STATUS       NUMBER(2)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.LOAD_FIL_PERIODS IS 'Загруженные отчетные даты';

COMMENT ON COLUMN MASTER.LOAD_FIL_PERIODS.ID IS 'ID загрузки';

COMMENT ON COLUMN MASTER.LOAD_FIL_PERIODS.FILIAL_ID IS 'ID филиала';

COMMENT ON COLUMN MASTER.LOAD_FIL_PERIODS.DATE_REPORT IS 'Отчетная дата';

COMMENT ON COLUMN MASTER.LOAD_FIL_PERIODS.FILENAME IS 'Файл';

COMMENT ON COLUMN MASTER.LOAD_FIL_PERIODS.DATE_LOAD IS 'Дата время загрузки';

COMMENT ON COLUMN MASTER.LOAD_FIL_PERIODS.USER_LOAD IS 'Пользователь';

COMMENT ON COLUMN MASTER.LOAD_FIL_PERIODS.REP_TYPE_ID IS 'Тип загружаемого отчета';

COMMENT ON COLUMN MASTER.LOAD_FIL_PERIODS.STATUS IS 'Статус отчета: 0-Загружен в буфер, 1-Проверен, 2-Загружен в AZC_OPERATION';



