--
-- LOAD_FIL_ORG  (Table) 
--
CREATE TABLE MASTER.LOAD_FIL_ORG
(
  ID            NUMBER(10)                      NOT NULL,
  TAG           VARCHAR2(150 BYTE),
  NAME          VARCHAR2(100 BYTE),
  ORG_KIND_ID   NUMBER(10),
  IS_AUTO_LINK  NUMBER(1)                       DEFAULT 1,
  ORG_STRU_ID   NUMBER(10),
  FILIAL_ID     NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.LOAD_FIL_ORG IS 'Загружаемые подразделения';

COMMENT ON COLUMN MASTER.LOAD_FIL_ORG.ID IS 'Подразделение';

COMMENT ON COLUMN MASTER.LOAD_FIL_ORG.TAG IS 'ТЕГ';

COMMENT ON COLUMN MASTER.LOAD_FIL_ORG.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.LOAD_FIL_ORG.IS_AUTO_LINK IS 'Признак автоматической привязки';

COMMENT ON COLUMN MASTER.LOAD_FIL_ORG.ORG_STRU_ID IS 'ID подразделения';

COMMENT ON COLUMN MASTER.LOAD_FIL_ORG.FILIAL_ID IS 'ID филиала';



