--
-- LOAD_FIL_REALIZ  (Table) 
--
CREATE TABLE MASTER.LOAD_FIL_REALIZ
(
  ID             NUMBER(10)                     NOT NULL,
  FILIAL_ID      NUMBER(10),
  FIL_PERIOD_ID  NUMBER(10),
  FIL_ORG_ID     NUMBER(10),
  FIL_PROD_ID    NUMBER(10),
  REP_TYPE_ID    NUMBER(10),
  TYPE_OPER_ID   NUMBER(10),
  FACT           NUMBER(15,3)                   DEFAULT 0,
  DATE_OPER      DATE,
  FACT_SUM       NUMBER(15,2)                   DEFAULT 0
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.LOAD_FIL_REALIZ IS 'Загрузка реализации';

COMMENT ON COLUMN MASTER.LOAD_FIL_REALIZ.ID IS 'Реализация';

COMMENT ON COLUMN MASTER.LOAD_FIL_REALIZ.FILIAL_ID IS 'ID филиала';

COMMENT ON COLUMN MASTER.LOAD_FIL_REALIZ.FIL_PERIOD_ID IS 'ID загрузки';

COMMENT ON COLUMN MASTER.LOAD_FIL_REALIZ.FIL_ORG_ID IS 'Подразделение';

COMMENT ON COLUMN MASTER.LOAD_FIL_REALIZ.FIL_PROD_ID IS 'Загружаемый продукт';

COMMENT ON COLUMN MASTER.LOAD_FIL_REALIZ.REP_TYPE_ID IS 'Тип загружаемого отчета';

COMMENT ON COLUMN MASTER.LOAD_FIL_REALIZ.FACT IS 'Факт';

COMMENT ON COLUMN MASTER.LOAD_FIL_REALIZ.DATE_OPER IS 'Дата операции';

COMMENT ON COLUMN MASTER.LOAD_FIL_REALIZ.FACT_SUM IS 'Сумма';



