--
-- LOAD_FIL_PROD  (Table) 
--
CREATE TABLE MASTER.LOAD_FIL_PROD
(
  ID            NUMBER(10)                      NOT NULL,
  TAG           VARCHAR2(30 BYTE),
  NAME          VARCHAR2(50 BYTE),
  IS_AUTO_LINK  NUMBER(1)                       DEFAULT 1,
  PROD_ID_NPR   VARCHAR2(5 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.LOAD_FIL_PROD IS 'Загружаемые продукты';

COMMENT ON COLUMN MASTER.LOAD_FIL_PROD.ID IS 'Загружаемый продукт';

COMMENT ON COLUMN MASTER.LOAD_FIL_PROD.TAG IS 'ТЕГ';

COMMENT ON COLUMN MASTER.LOAD_FIL_PROD.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.LOAD_FIL_PROD.IS_AUTO_LINK IS 'Признак автомат.привязки';



