--
-- MAP_AZS  (Table) 
--
CREATE TABLE MASTER.MAP_AZS
(
  AZS_ID        NUMBER(17),
  X             NUMBER(10),
  Y             NUMBER(10),
  COL           NUMBER(10),
  NOTE          VARCHAR2(255 BYTE),
  VISIBLE       VARCHAR2(1 BYTE),
  SETLEMENT_ID  NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


