--
-- MAP_REGIONS  (Table) 
--
CREATE TABLE MASTER.MAP_REGIONS
(
  ID           NUMBER(10)                       NOT NULL,
  FIGURE       NUMBER(10),
  FILLCOLOR    NUMBER(10),
  BORDERCOLOR  NUMBER(10),
  CAPTION      VARCHAR2(100 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


