--
-- MASTER_LINKS_STRUCTURE  (Table) 
--
CREATE TABLE MASTER.MASTER_LINKS_STRUCTURE
(
  ID                  VARCHAR2(50 BYTE),
  CAPTION             VARCHAR2(100 BYTE),
  SORTBY              NUMBER(10),
  TABLE_LINK          VARCHAR2(50 BYTE),
  QUERY_LINK          VARCHAR2(300 BYTE),
  TABLE_LINK_TYPE     VARCHAR2(3 BYTE)          DEFAULT '1-1',
  TABLE_LINK_PK       VARCHAR2(50 BYTE),
  TABLE_LINK_PK_TYPE  VARCHAR2(1 BYTE),
  TABLE_LINK_ONE_PK   VARCHAR2(50 BYTE),
  TABLE_ONE           VARCHAR2(50 BYTE),
  TABLE_LINK_TWO_PK   VARCHAR2(50 BYTE),
  TABLE_TWO           VARCHAR2(50 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.MASTER_LINKS_STRUCTURE IS 'Описание ассоциаций (связи между таблицами)';

COMMENT ON COLUMN MASTER.MASTER_LINKS_STRUCTURE.ID IS 'ID связи';

COMMENT ON COLUMN MASTER.MASTER_LINKS_STRUCTURE.CAPTION IS 'Описание';

COMMENT ON COLUMN MASTER.MASTER_LINKS_STRUCTURE.SORTBY IS '№ по порядку';

COMMENT ON COLUMN MASTER.MASTER_LINKS_STRUCTURE.TABLE_LINK IS 'Таблица связи';

COMMENT ON COLUMN MASTER.MASTER_LINKS_STRUCTURE.QUERY_LINK IS 'Запрос - выборка всех записей из таблицы связи, относящихся к данной ассоциации';

COMMENT ON COLUMN MASTER.MASTER_LINKS_STRUCTURE.TABLE_LINK_TYPE IS 'Тип связи';

COMMENT ON COLUMN MASTER.MASTER_LINKS_STRUCTURE.TABLE_LINK_PK IS 'PK таблицы связи';

COMMENT ON COLUMN MASTER.MASTER_LINKS_STRUCTURE.TABLE_LINK_PK_TYPE IS 'Тип PK таблицы связи';

COMMENT ON COLUMN MASTER.MASTER_LINKS_STRUCTURE.TABLE_LINK_ONE_PK IS 'PK таблицы "Что привязываем"';

COMMENT ON COLUMN MASTER.MASTER_LINKS_STRUCTURE.TABLE_ONE IS 'Таблица "Что привязываем"';

COMMENT ON COLUMN MASTER.MASTER_LINKS_STRUCTURE.TABLE_LINK_TWO_PK IS 'PK таблицы "К чему привязываем"';

COMMENT ON COLUMN MASTER.MASTER_LINKS_STRUCTURE.TABLE_TWO IS 'Таблица "К чему привязываем"';



