--
-- MASTER_QUERY_TYPES_DESC  (Table) 
--
CREATE TABLE MASTER.MASTER_QUERY_TYPES_DESC
(
  ID            NUMBER(10)                      NOT NULL,
  STRUCTURE_ID  VARCHAR2(50 BYTE),
  TYPE_ID       NUMBER(10),
  IS_AUTO_LINK  NUMBER(1)                       DEFAULT 0
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.MASTER_QUERY_TYPES_DESC IS 'Таблица связи "Запросы" - "Типы запросов"';

COMMENT ON COLUMN MASTER.MASTER_QUERY_TYPES_DESC.ID IS 'Пересечение Запрос-Тип';

COMMENT ON COLUMN MASTER.MASTER_QUERY_TYPES_DESC.STRUCTURE_ID IS 'Запрос';

COMMENT ON COLUMN MASTER.MASTER_QUERY_TYPES_DESC.TYPE_ID IS 'Тип запроса';

COMMENT ON COLUMN MASTER.MASTER_QUERY_TYPES_DESC.IS_AUTO_LINK IS 'Признак автоматической связи';



