--
-- MASTER_KLS_FIELD_STRUCTURE  (Table) 
--
CREATE TABLE MASTER.MASTER_KLS_FIELD_STRUCTURE
(
  ID                    NUMBER(10)              NOT NULL,
  STRUCTURE_ID          VARCHAR2(50 BYTE),
  FIELD_ID              NUMBER(5),
  FIELD_NAME            VARCHAR2(50 BYTE),
  FIELD_CAPTION         VARCHAR2(50 BYTE),
  FIELD_READONLY        NUMBER(1)               DEFAULT 0,
  MASK                  VARCHAR2(10 BYTE),
  DISPLAY_WIDTH         NUMBER(5),
  FIELD_KIND            NUMBER(1)               DEFAULT 0,
  LOOKUP_SOURCE_QUERY   VARCHAR2(512 BYTE),
  LOOKUP_DISPLAY_FIELD  VARCHAR2(50 BYTE),
  LOOKUP_KEY_FIELD      VARCHAR2(50 BYTE),
  LOOKUP_TABLE          VARCHAR2(30 BYTE),
  FIELD_TYPE            VARCHAR2(1 BYTE),
  REL_OPER              VARCHAR2(4 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.MASTER_KLS_FIELD_STRUCTURE IS 'Описание полей запросов к БД';

COMMENT ON COLUMN MASTER.MASTER_KLS_FIELD_STRUCTURE.ID IS 'Уникальное ID';

COMMENT ON COLUMN MASTER.MASTER_KLS_FIELD_STRUCTURE.STRUCTURE_ID IS 'Запрос к БД';

COMMENT ON COLUMN MASTER.MASTER_KLS_FIELD_STRUCTURE.FIELD_ID IS '№ поля по порядку';

COMMENT ON COLUMN MASTER.MASTER_KLS_FIELD_STRUCTURE.FIELD_NAME IS 'Имя поля';

COMMENT ON COLUMN MASTER.MASTER_KLS_FIELD_STRUCTURE.FIELD_CAPTION IS 'Описание';

COMMENT ON COLUMN MASTER.MASTER_KLS_FIELD_STRUCTURE.FIELD_READONLY IS 'Только для чтения';

COMMENT ON COLUMN MASTER.MASTER_KLS_FIELD_STRUCTURE.MASK IS 'Маска';

COMMENT ON COLUMN MASTER.MASTER_KLS_FIELD_STRUCTURE.DISPLAY_WIDTH IS 'Ширина поля в GRID';

COMMENT ON COLUMN MASTER.MASTER_KLS_FIELD_STRUCTURE.FIELD_KIND IS 'Вид поля (0-Обычное, 1-Lookup, 2-CheckBox)';

COMMENT ON COLUMN MASTER.MASTER_KLS_FIELD_STRUCTURE.LOOKUP_SOURCE_QUERY IS 'Lookup-запрос';

COMMENT ON COLUMN MASTER.MASTER_KLS_FIELD_STRUCTURE.LOOKUP_DISPLAY_FIELD IS 'Отображаемое Lookup-поле';

COMMENT ON COLUMN MASTER.MASTER_KLS_FIELD_STRUCTURE.LOOKUP_KEY_FIELD IS 'Ключевое Lookup-поле';

COMMENT ON COLUMN MASTER.MASTER_KLS_FIELD_STRUCTURE.LOOKUP_TABLE IS 'Lookup-таблица';

COMMENT ON COLUMN MASTER.MASTER_KLS_FIELD_STRUCTURE.FIELD_TYPE IS 'Тип поля: N-число, C-символ, D-дата';

COMMENT ON COLUMN MASTER.MASTER_KLS_FIELD_STRUCTURE.REL_OPER IS 'оператор связи';



