--
-- MASTER_KLS_STRUCTURE  (Table) 
--
CREATE TABLE MASTER.MASTER_KLS_STRUCTURE
(
  ID                   VARCHAR2(50 BYTE)        NOT NULL,
  CAPTION              VARCHAR2(100 BYTE),
  SORTBY               NUMBER(3),
  TABLE_NAME           VARCHAR2(50 BYTE),
  UNIQUE_FIELD         VARCHAR2(30 BYTE)        DEFAULT 'ID',
  QUERY                VARCHAR2(1024 BYTE),
  START_ORDER          VARCHAR2(50 BYTE),
  SEQUENCES            VARCHAR2(30 BYTE),
  NAME_FIELD           VARCHAR2(30 BYTE),
  NAME_FIELD_2         VARCHAR2(30 BYTE),
  DATE_FIELD_BEGIN     VARCHAR2(15 BYTE),
  DATE_FIELD_END       VARCHAR2(15 BYTE),
  VIEW_TIME            NUMBER(1)                DEFAULT 0,
  FILTER_1             VARCHAR2(30 BYTE),
  FILTER_1_CAPTION     VARCHAR2(50 BYTE),
  FILTER_2             VARCHAR2(30 BYTE),
  FILTER_2_CAPTION     VARCHAR2(50 BYTE),
  FILTER_3             VARCHAR2(30 BYTE),
  FILTER_3_CAPTION     VARCHAR2(50 BYTE),
  ADD_FORM             VARCHAR2(30 BYTE),
  RIGHTS_ID            VARCHAR2(30 BYTE),
  FOX_UPDATE_QUERY     VARCHAR2(300 BYTE),
  FOX_INSERT_QUERY     VARCHAR2(300 BYTE),
  FOX_DELETE_QUERY     VARCHAR2(300 BYTE),
  UNIQID_SELECT_QUERY  VARCHAR2(300 BYTE),
  UNIQID_UPDATE_QUERY  VARCHAR2(300 BYTE),
  CHILD_FORM           VARCHAR2(30 BYTE),
  CHILD_NAME           VARCHAR2(30 BYTE),
  FROZEN_COLS          NUMBER(2),
  MASTER_FIELD         VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.MASTER_KLS_STRUCTURE IS 'Справочник запросов к БД';

COMMENT ON COLUMN MASTER.MASTER_KLS_STRUCTURE.VIEW_TIME IS 'Запрашивать время (в режиме "Запросы")';

COMMENT ON COLUMN MASTER.MASTER_KLS_STRUCTURE.CHILD_FORM IS 'Дочернее окно';

COMMENT ON COLUMN MASTER.MASTER_KLS_STRUCTURE.CHILD_NAME IS 'Наименование "дочернего" окна';

COMMENT ON COLUMN MASTER.MASTER_KLS_STRUCTURE.FROZEN_COLS IS '"Замороженных столбцов"';

COMMENT ON COLUMN MASTER.MASTER_KLS_STRUCTURE.MASTER_FIELD IS 'Ссылка на Мастер-таблицу';



