--
-- MASTER_REPORTS  (Table) 
--
CREATE TABLE MASTER.MASTER_REPORTS
(
  ID             NUMBER(10)                     NOT NULL,
  TERMINAL_NAME  VARCHAR2(30 BYTE),
  OSUSER_NAME    VARCHAR2(30 BYTE),
  APP_NAME       VARCHAR2(30 BYTE),
  REP_ID         NUMBER(10),
  REPORT_NAME    VARCHAR2(80 BYTE),
  REPORT_FILE    VARCHAR2(30 BYTE),
  REPORT_GROUP   VARCHAR2(15 BYTE),
  REPORT_TYPE    VARCHAR2(15 BYTE),
  REPORT_TITLE   VARCHAR2(250 BYTE),
  BEGIN_DATE     DATE,
  BEGIN_TIME     VARCHAR2(20 BYTE),
  END_DATE       DATE,
  END_TIME       VARCHAR2(20 BYTE),
  DATE_REE       VARCHAR2(30 BYTE),
  DATE_PLAN      VARCHAR2(30 BYTE),
  FROM_PARUS     NUMBER(3),
  VIEW_PROD      NUMBER(3),
  VIEW_DAYS      NUMBER(3),
  IS_AGENT       NUMBER(3),
  DIAGRAM_TYPE   VARCHAR2(15 BYTE),
  DIAGRAM_KIND   VARCHAR2(30 BYTE),
  AXES_X_NAME    VARCHAR2(30 BYTE),
  COUNT_COLS_X   NUMBER(3),
  AXES_Y_NAME    VARCHAR2(30 BYTE),
  COUNT_COLS_Y   NUMBER(3),
  REPORT_AGE     DATE                           DEFAULT TRUNC(SYSDATE+2),
  FILIAL_ID      NUMBER(10),
  GROUP_KIND_ID  NUMBER(10),
  AZC_ID         NUMBER(10),
  DOG_NUMBER     VARCHAR2(30 BYTE),
  PLAT_ID        NUMBER(10),
  GRP_ID_NPR     VARCHAR2(10 BYTE),
  PROD_ID_NPR    VARCHAR2(10 BYTE),
  IS_SNP         NUMBER(1),
  IS_UNP         NUMBER(1)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.MASTER_REPORTS.REPORT_AGE IS 'Срок жизни';

COMMENT ON COLUMN MASTER.MASTER_REPORTS.FILIAL_ID IS 'Филиал';

COMMENT ON COLUMN MASTER.MASTER_REPORTS.GROUP_KIND_ID IS 'Вид подразделения';

COMMENT ON COLUMN MASTER.MASTER_REPORTS.AZC_ID IS 'Подразделение';

COMMENT ON COLUMN MASTER.MASTER_REPORTS.DOG_NUMBER IS 'N договора';

COMMENT ON COLUMN MASTER.MASTER_REPORTS.PLAT_ID IS 'Плательщик';

COMMENT ON COLUMN MASTER.MASTER_REPORTS.GRP_ID_NPR IS 'Группа н/пр';

COMMENT ON COLUMN MASTER.MASTER_REPORTS.PROD_ID_NPR IS 'Нефтепродукт';

COMMENT ON COLUMN MASTER.MASTER_REPORTS.IS_SNP IS 'Пользователь из СНП';

COMMENT ON COLUMN MASTER.MASTER_REPORTS.IS_UNP IS 'Пользователь из УНП';



