--
-- MONTH  (Table) 
--
CREATE TABLE MASTER.MONTH
(
  NOM_ZD            VARCHAR2(16 BYTE)           NOT NULL,
  STANOTP_ID        NUMBER(10),
  NPR_SOBSTV_ID     NUMBER(6),
  STAN_ID           NUMBER(10),
  VETKA_ID          NUMBER(10),
  POLUCH_ID         NUMBER(6),
  TEX_PD_ID         NUMBER(10),
  NAZN_OTG_ID       NUMBER(2),
  LOAD_ABBR         VARCHAR2(3 BYTE),
  DOG_ID            NUMBER(5),
  USL_NUMBER        NUMBER(3),
  GOSPROG_ID        NUMBER(2),
  PROD_ID_NPR       VARCHAR2(5 BYTE),
  TONN_DECLARED     NUMBER(10,3),
  TONN_LOADED       NUMBER(10,3),
  CIST_DECLARED     NUMBER(4),
  CIST_LOADED       NUMBER(4),
  FLG_ALLOW_8_AXES  NUMBER(1),
  FLG_UPPER_SLIV    NUMBER(1),
  FLG_DOP_CIST      NUMBER(1),
  FLG_FORMA_2       NUMBER(10),
  FLG_OBOGR         NUMBER(1),
  DATE_PLAN         DATE,
  PRIM              VARCHAR2(100 BYTE),
  CENA              NUMBER(15,6),
  CENA_OTP          NUMBER(15,6),
  SUM_ZD            NUMBER(12,2),
  GR4               VARCHAR2(100 BYTE),
  K_TAR             VARCHAR2(10 BYTE),
  INPUT_DATE        DATE,
  UPDATE_DATE       DATE,
  TARIF1TONN        NUMBER(10,2)                DEFAULT 0,
  POTREB_ID         NUMBER(6),
  PLANSTRU_ID       NUMBER(20),
  NPODOG_ID         NUMBER(5),
  GROTP_ID          NUMBER(6)                   DEFAULT 0,
  DATE_CEN          DATE,
  GP_NAPR_ID        NUMBER(10),
  TONN_R            NUMBER(15,6)                DEFAULT 0,
  CIST_R            NUMBER(4)                   DEFAULT 0,
  TRANSPORT         VARCHAR2(20 BYTE),
  IS_EXP            NUMBER(1)                   DEFAULT 0,
  SUPPLIER_ID       NUMBER(6),
  APPL_TAG          VARCHAR2(6 BYTE),
  CENA_NPO          NUMBER(15,6)                DEFAULT 0,
  CENA_OTP_NPO      NUMBER(15,6)                DEFAULT 0,
  KOL_DN_NPO        NUMBER(3),
  TONN_RAZNAR       NUMBER(10,3),
  CIST_RAZNAR       NUMBER(10,3),
  ZAKAZ_ID          NUMBER(10),
  EXPED_ID          NUMBER(6),
  GU12_A_ID         NUMBER(10),
  ZAKAZ_HIST_ID     NUMBER(10),
  POKUP_DOG_ID      NUMBER(10),
  POKUP_USL_NUMBER  NUMBER(3),
  NAPR_POST_ID      NUMBER(10),
  CIST_FACT         NUMBER(5)                   DEFAULT 0,
  TONN_FACT         NUMBER(10,3)                DEFAULT 0,
  STAN_PER_ID       NUMBER(10),
  INCOTERM_ID       NUMBER(10),
  VZISK_ID          NUMBER(10),
  ZAKAZ_KOD_ISU     VARCHAR2(15 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.MONTH IS 'Заявки на отгрузку';

COMMENT ON COLUMN MASTER.MONTH.NOM_ZD IS 'Заявка';

COMMENT ON COLUMN MASTER.MONTH.STANOTP_ID IS 'Станция отправления';

COMMENT ON COLUMN MASTER.MONTH.NPR_SOBSTV_ID IS 'Собственник н/пр';

COMMENT ON COLUMN MASTER.MONTH.STAN_ID IS 'Станция назначения';

COMMENT ON COLUMN MASTER.MONTH.VETKA_ID IS 'Ветка получателя';

COMMENT ON COLUMN MASTER.MONTH.POLUCH_ID IS 'Получатель';

COMMENT ON COLUMN MASTER.MONTH.TEX_PD_ID IS 'ТЕХ ПД';

COMMENT ON COLUMN MASTER.MONTH.NAZN_OTG_ID IS 'Назначение отгрузки';

COMMENT ON COLUMN MASTER.MONTH.LOAD_ABBR IS 'Вид транспортировки';

COMMENT ON COLUMN MASTER.MONTH.DOG_ID IS 'Договор';

COMMENT ON COLUMN MASTER.MONTH.USL_NUMBER IS 'Условие';

COMMENT ON COLUMN MASTER.MONTH.GOSPROG_ID IS 'Госпрограмма';

COMMENT ON COLUMN MASTER.MONTH.PROD_ID_NPR IS 'Нефтепродукт';

COMMENT ON COLUMN MASTER.MONTH.TONN_DECLARED IS 'Заявленно т.';

COMMENT ON COLUMN MASTER.MONTH.TONN_LOADED IS 'Отгружено т.';

COMMENT ON COLUMN MASTER.MONTH.CIST_DECLARED IS 'Заявлено цист.';

COMMENT ON COLUMN MASTER.MONTH.CIST_LOADED IS 'Отгружено цист.';

COMMENT ON COLUMN MASTER.MONTH.FLG_ALLOW_8_AXES IS '8-осные ?';

COMMENT ON COLUMN MASTER.MONTH.FLG_UPPER_SLIV IS 'Верхний слив ?';

COMMENT ON COLUMN MASTER.MONTH.FLG_DOP_CIST IS 'Цист.сверх плана?';

COMMENT ON COLUMN MASTER.MONTH.FLG_FORMA_2 IS 'Вид расчета тарифа';

COMMENT ON COLUMN MASTER.MONTH.FLG_OBOGR IS 'Обогрев цист.?';

COMMENT ON COLUMN MASTER.MONTH.DATE_PLAN IS 'Дата плана';

COMMENT ON COLUMN MASTER.MONTH.PRIM IS 'Примечание';

COMMENT ON COLUMN MASTER.MONTH.CENA IS 'Цена ЛУКОЙЛ без налогов';

COMMENT ON COLUMN MASTER.MONTH.CENA_OTP IS 'Отпускная цена ЛУКОЙЛ';

COMMENT ON COLUMN MASTER.MONTH.SUM_ZD IS 'Сумма по заданию';

COMMENT ON COLUMN MASTER.MONTH.GR4 IS 'Графа 4';

COMMENT ON COLUMN MASTER.MONTH.K_TAR IS 'Код искл. тарифа';

COMMENT ON COLUMN MASTER.MONTH.INPUT_DATE IS 'Дата ввода';

COMMENT ON COLUMN MASTER.MONTH.UPDATE_DATE IS 'Дата последнего обновления';

COMMENT ON COLUMN MASTER.MONTH.TARIF1TONN IS 'Тариф за 1 тонну';

COMMENT ON COLUMN MASTER.MONTH.POTREB_ID IS 'Потребитель';

COMMENT ON COLUMN MASTER.MONTH.PLANSTRU_ID IS 'Позиция плана';

COMMENT ON COLUMN MASTER.MONTH.NPODOG_ID IS 'Договор НПО-Клиент';

COMMENT ON COLUMN MASTER.MONTH.GROTP_ID IS 'Грузоотправитель';

COMMENT ON COLUMN MASTER.MONTH.DATE_CEN IS 'Дата цены ЛУКОЙЛ';

COMMENT ON COLUMN MASTER.MONTH.GP_NAPR_ID IS 'Получатель по госпрограмме';

COMMENT ON COLUMN MASTER.MONTH.TONN_R IS 'Тонн разнаряжено';

COMMENT ON COLUMN MASTER.MONTH.CIST_R IS 'Цист.разнаряжено';

COMMENT ON COLUMN MASTER.MONTH.TRANSPORT IS 'N транспорта';

COMMENT ON COLUMN MASTER.MONTH.IS_EXP IS '1-Экспорт, 0-по России';

COMMENT ON COLUMN MASTER.MONTH.SUPPLIER_ID IS 'Поставщик';

COMMENT ON COLUMN MASTER.MONTH.APPL_TAG IS 'Тэг приложения';

COMMENT ON COLUMN MASTER.MONTH.CENA_NPO IS 'Цена без налогов СНП';

COMMENT ON COLUMN MASTER.MONTH.CENA_OTP_NPO IS 'Отпускная цена СНП';

COMMENT ON COLUMN MASTER.MONTH.KOL_DN_NPO IS 'Кол-во дней отсрочки при продаже';

COMMENT ON COLUMN MASTER.MONTH.TONN_RAZNAR IS 'Тонн передано на место отгрузки';

COMMENT ON COLUMN MASTER.MONTH.CIST_RAZNAR IS 'Цистерн передано на место отгрузки';

COMMENT ON COLUMN MASTER.MONTH.ZAKAZ_ID IS 'Ссылка на заказ потребителя';

COMMENT ON COLUMN MASTER.MONTH.EXPED_ID IS 'Экспедитор';

COMMENT ON COLUMN MASTER.MONTH.GU12_A_ID IS 'Заявка на перевозку';

COMMENT ON COLUMN MASTER.MONTH.ZAKAZ_HIST_ID IS 'Ссылка на позицию заказа';

COMMENT ON COLUMN MASTER.MONTH.NAPR_POST_ID IS 'Направление поставки';

COMMENT ON COLUMN MASTER.MONTH.CIST_FACT IS 'Кол-во вагонов отгружено (для контроля на местах отгрузки)';

COMMENT ON COLUMN MASTER.MONTH.TONN_FACT IS 'Тонн отгружено (для контроля на местах отгрузки)';

COMMENT ON COLUMN MASTER.MONTH.STAN_PER_ID IS 'Станция перехода';

COMMENT ON COLUMN MASTER.MONTH.INCOTERM_ID IS 'Условия поставки';



