--
-- MONTH_VISIR_LOC  (Table) 
--
CREATE TABLE MASTER.MONTH_VISIR_LOC
(
  ID            NUMBER(10)                      NOT NULL,
  DATE_REE      DATE,
  DOP_REE       NUMBER(1),
  NOM_ZD        VARCHAR2(12 BYTE),
  PRICHIN       VARCHAR2(200 BYTE),
  APP_USERS_ID  NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


