--
-- MONTH_REESTR_POS  (Table) 
--
CREATE TABLE MASTER.MONTH_REESTR_POS
(
  MONTH_REESTR_ID  NUMBER(10)                   NOT NULL,
  NOM_ZD           VARCHAR2(12 BYTE)            NOT NULL,
  TONN_REE         NUMBER(15,3)                 DEFAULT 0,
  PRIORITY         NUMBER(10),
  TONN_MOS         NUMBER(15,3)                 DEFAULT 0,
  R3_VBAK_ID       VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.MONTH_REESTR_POS IS 'Позиции суточного реестра заданий';

COMMENT ON COLUMN MASTER.MONTH_REESTR_POS.MONTH_REESTR_ID IS 'ID реестра';

COMMENT ON COLUMN MASTER.MONTH_REESTR_POS.NOM_ZD IS 'ID задания';

COMMENT ON COLUMN MASTER.MONTH_REESTR_POS.TONN_REE IS 'Объем по реестру';

COMMENT ON COLUMN MASTER.MONTH_REESTR_POS.PRIORITY IS 'Подтверждение/запрет';

COMMENT ON COLUMN MASTER.MONTH_REESTR_POS.TONN_MOS IS 'Согласованный объем';

COMMENT ON COLUMN MASTER.MONTH_REESTR_POS.R3_VBAK_ID IS 'разнарядка из SAP';



