--
-- MONTH_REESTR  (Table) 
--
CREATE TABLE MASTER.MONTH_REESTR
(
  ID                NUMBER(10)                  NOT NULL,
  NUM_REE           NUMBER(10),
  DATE_REE          DATE,
  DATE_TO           DATE,
  DATE_PLAN         DATE,
  USE_GRAFIK        NUMBER(1),
  GRAFIK_DATE_FROM  DATE,
  GRAFIK_DATE_TO    DATE,
  STATUS            NUMBER(10),
  DOP_REE           NUMBER(10),
  UHTA_XLS_NAME     VARCHAR2(50 BYTE),
  MOS_DBF_NAME      VARCHAR2(50 BYTE),
  MOS_XLS_NAME      VARCHAR2(50 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.MONTH_REESTR IS 'Суточные реестры заданий';

COMMENT ON COLUMN MASTER.MONTH_REESTR.ID IS 'ID реестра';

COMMENT ON COLUMN MASTER.MONTH_REESTR.NUM_REE IS 'Номер реестра';

COMMENT ON COLUMN MASTER.MONTH_REESTR.DATE_REE IS 'Дата реестра';

COMMENT ON COLUMN MASTER.MONTH_REESTR.DATE_TO IS 'Отгрузка по дату';

COMMENT ON COLUMN MASTER.MONTH_REESTR.DATE_PLAN IS 'Дата плана';

COMMENT ON COLUMN MASTER.MONTH_REESTR.USE_GRAFIK IS '1-использовать график';

COMMENT ON COLUMN MASTER.MONTH_REESTR.GRAFIK_DATE_FROM IS 'С даты';

COMMENT ON COLUMN MASTER.MONTH_REESTR.GRAFIK_DATE_TO IS 'По дату';

COMMENT ON COLUMN MASTER.MONTH_REESTR.STATUS IS 'Статус реестра';

COMMENT ON COLUMN MASTER.MONTH_REESTR.DOP_REE IS '№ доп.реестра';

COMMENT ON COLUMN MASTER.MONTH_REESTR.UHTA_XLS_NAME IS 'Ухтинский реестр (XLS)';

COMMENT ON COLUMN MASTER.MONTH_REESTR.MOS_DBF_NAME IS 'Московский реестр (DBF)';



