--
-- MONTH_OILSPACE  (Table) 
--
CREATE TABLE MASTER.MONTH_OILSPACE
(
  DOC_ID      VARCHAR2(25 BYTE),
  DOC_OUTNUM  VARCHAR2(10 BYTE),
  LUKOIL_ID   NUMBER(10)                        NOT NULL,
  FACTORY_ID  NUMBER(10),
  FACTORYNAM  VARCHAR2(20 BYTE),
  PRODUCT_ID  NUMBER(10),
  PROD_ID_R3  NUMBER(10),
  PROD_NAME   VARCHAR2(50 BYTE),
  PROD_KCCC   NUMBER(10),
  PROD_ETCNG  NUMBER(10),
  PROD_GNG    NUMBER(10),
  PROD_TYPE   VARCHAR2(50 BYTE),
  CONTRACT    VARCHAR2(10 BYTE),
  VOLUME      NUMBER,
  BASIS       VARCHAR2(3 BYTE),
  CLIENT      VARCHAR2(50 BYTE),
  POLU        VARCHAR2(50 BYTE),
  POLU_ID     NUMBER(10),
  POLU_KCCC   NUMBER(10),
  POLU_INN    VARCHAR2(13 BYTE),
  CUSTOMER    VARCHAR2(50 BYTE),
  CUST_ID     NUMBER(10),
  CUST_KCCC   NUMBER(10),
  CUST_INN    VARCHAR2(13 BYTE),
  EXPEDITOR   VARCHAR2(50 BYTE),
  TYP_VAG     VARCHAR2(30 BYTE),
  STATION_ID  VARCHAR2(10 BYTE),
  STATION     VARCHAR2(50 BYTE),
  TIT_RSK_ID  VARCHAR2(6 BYTE),
  TITLE_RISK  VARCHAR2(50 BYTE),
  NAPR        VARCHAR2(100 BYTE),
  COUNTRY     VARCHAR2(100 BYTE),
  CNTRY_KCCC  NUMBER(10),
  STATE       NUMBER(1),
  CATEGORY    NUMBER(1),
  NOTES       VARCHAR2(100 BYTE),
  RCAR_OWNR   VARCHAR2(20 BYTE),
  RCAR_TYPE   VARCHAR2(20 BYTE),
  RCAR_PHTYP  NUMBER(10),
  RCAR_OSTYP  NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.MONTH_OILSPACE IS 'Ёкспортные разнар€дки из OILSpace';



