--
-- NAKL  (Table) 
--
CREATE TABLE MASTER.NAKL
(
  ID            NUMBER(10)                      NOT NULL,
  MESTO_ID      NUMBER(10),
  LOAD_TYPE_ID  NUMBER(10),
  NAKL_NUM      NUMBER(10),
  NAKL_DATE     DATE,
  PROD_GU12_ID  VARCHAR2(10 BYTE),
  FORMNAKL_ID   NUMBER(10),
  SHABNAKL_ID   NUMBER(10),
  SHABEXP_ID    NUMBER(10),
  K_TAR         VARCHAR2(10 BYTE),
  VES_CIST      NUMBER(12,3)                    DEFAULT 0,
  VES           NUMBER(12,3)                    DEFAULT 0,
  UPAK_VES      NUMBER(12,3)                    DEFAULT 0,
  VES_ALL       NUMBER(12,3)                    DEFAULT 0,
  NOM_ZD        VARCHAR2(12 BYTE),
  PROD_ID_NPR   VARCHAR2(5 BYTE),
  SHABVOZ_ID    NUMBER(10),
  IS_EXP        NUMBER(1),
  OPERNALIV_ID  NUMBER(10),
  DOG_ID        NUMBER(10),
  STAN_ID       NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.NAKL IS 'Накладные';

COMMENT ON COLUMN MASTER.NAKL.ID IS 'ID накладной';

COMMENT ON COLUMN MASTER.NAKL.MESTO_ID IS 'Место отгрузки';

COMMENT ON COLUMN MASTER.NAKL.LOAD_TYPE_ID IS 'Тип транспортировки';

COMMENT ON COLUMN MASTER.NAKL.NAKL_NUM IS 'Номер накладной';

COMMENT ON COLUMN MASTER.NAKL.NAKL_DATE IS 'Дата накладной';

COMMENT ON COLUMN MASTER.NAKL.PROD_GU12_ID IS 'Ж/д код груза';

COMMENT ON COLUMN MASTER.NAKL.FORMNAKL_ID IS 'Форма накладной';

COMMENT ON COLUMN MASTER.NAKL.SHABNAKL_ID IS 'Шаблон накладной';

COMMENT ON COLUMN MASTER.NAKL.SHABEXP_ID IS 'Шаблон экспортной накладной';

COMMENT ON COLUMN MASTER.NAKL.K_TAR IS 'Код исключительного тарифа';

COMMENT ON COLUMN MASTER.NAKL.VES_CIST IS 'Вес вагона';

COMMENT ON COLUMN MASTER.NAKL.VES IS 'Вес груза';

COMMENT ON COLUMN MASTER.NAKL.UPAK_VES IS 'Вес упаковки';

COMMENT ON COLUMN MASTER.NAKL.VES_ALL IS 'Вес вагона груза и упаковки';

COMMENT ON COLUMN MASTER.NAKL.DOG_ID IS 'Оператор налива';



