--
-- OBOROT_KONS  (Table) 
--
CREATE TABLE MASTER.OBOROT_KONS
(
  ID_OPER             NUMBER(18)                NOT NULL,
  DATE_OPER           DATE,
  KOL                 NUMBER(15,3)              DEFAULT 0,
  KG                  NUMBER(15,3)              DEFAULT 0,
  LIT                 NUMBER(15,3)              DEFAULT 0,
  CENA_POKUP_BN       NUMBER(15,2)              DEFAULT 0,
  CENA_POKUP          NUMBER(15,2)              DEFAULT 0,
  SUMMA_POKUP_BN      NUMBER(15,2)              DEFAULT 0,
  SUMMA_POKUP_NDS     NUMBER(15,2)              DEFAULT 0,
  SUMMA_POKUP_AKCIZ   NUMBER(15,2)              DEFAULT 0,
  SUMMA_POKUP         NUMBER(15,2)              DEFAULT 0,
  CENA_REALIZ_BN      NUMBER(15,2)              DEFAULT 0,
  CENA_REALIZ         NUMBER(15,2)              DEFAULT 0,
  SUMMA_REALIZ_BN     NUMBER(15,2)              DEFAULT 0,
  SUMMA_REALIZ_NDS    NUMBER(15,2)              DEFAULT 0,
  SUMMA_REALIZ_AKCIZ  NUMBER(15,2)              DEFAULT 0,
  SUMMA_REALIZ        NUMBER(15,2)              DEFAULT 0,
  CENA_UCHET          NUMBER(15,2)              DEFAULT 0,
  SUMMA_UCHET         NUMBER(15,2)              DEFAULT 0,
  UPDATE_USER         VARCHAR2(20 BYTE),
  UPDATE_DATE         DATE,
  AKCIZ_SVED          NUMBER(1)                 DEFAULT 0,
  ORG_STRU_ID         NUMBER(10),
  PREDPR_KONS_ID      NUMBER(20),
  PROD_KONS_ID        VARCHAR2(21 BYTE),
  PREDPR_CLASS_ID     NUMBER(10),
  TIP_OP_ID           NUMBER(10),
  ST_PRIH_ID          NUMBER(10),
  ST_RASH_ID          NUMBER(10),
  TIP_REAL_ID         NUMBER(10),
  VID_REAL_ID         NUMBER(10),
  VID_POST_ID         NUMBER(10),
  OTGR_POST_ID        NUMBER(10),
  LOAD_TYPE_ID        NUMBER(2),
  REGION_ID           NUMBER(3),
  ORG_POLUCH_ID       NUMBER(10),
  FILIAL_ID           NUMBER(10)                NOT NULL
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.OBOROT_KONS IS 'Конс.отчетность: Обороты';

COMMENT ON COLUMN MASTER.OBOROT_KONS.ID_OPER IS 'Уникальный ID';

COMMENT ON COLUMN MASTER.OBOROT_KONS.DATE_OPER IS 'Дата';

COMMENT ON COLUMN MASTER.OBOROT_KONS.KOL IS 'Кол-во';

COMMENT ON COLUMN MASTER.OBOROT_KONS.KG IS 'Вес (кг)';

COMMENT ON COLUMN MASTER.OBOROT_KONS.LIT IS 'Объем (литр)';

COMMENT ON COLUMN MASTER.OBOROT_KONS.CENA_POKUP_BN IS 'Цена приобретения (без налогов)';

COMMENT ON COLUMN MASTER.OBOROT_KONS.CENA_POKUP IS 'Цена приобретения';

COMMENT ON COLUMN MASTER.OBOROT_KONS.SUMMA_POKUP_BN IS 'Сумма приобретения (без налогов)';

COMMENT ON COLUMN MASTER.OBOROT_KONS.SUMMA_POKUP_NDS IS 'НДС по приобретению';

COMMENT ON COLUMN MASTER.OBOROT_KONS.SUMMA_POKUP_AKCIZ IS 'АКЦИЗ по приобретению';

COMMENT ON COLUMN MASTER.OBOROT_KONS.SUMMA_POKUP IS 'Сумма приобретения';

COMMENT ON COLUMN MASTER.OBOROT_KONS.CENA_REALIZ_BN IS 'Цена реализации (без налогов)';

COMMENT ON COLUMN MASTER.OBOROT_KONS.CENA_REALIZ IS 'Цена реализации';

COMMENT ON COLUMN MASTER.OBOROT_KONS.SUMMA_REALIZ_BN IS 'Сумма реализации (без налогов)';

COMMENT ON COLUMN MASTER.OBOROT_KONS.SUMMA_REALIZ_NDS IS 'НДС по реализации';

COMMENT ON COLUMN MASTER.OBOROT_KONS.SUMMA_REALIZ_AKCIZ IS 'Акциз по реализации';

COMMENT ON COLUMN MASTER.OBOROT_KONS.SUMMA_REALIZ IS 'Сумма реализации';

COMMENT ON COLUMN MASTER.OBOROT_KONS.CENA_UCHET IS 'Учетная цена';

COMMENT ON COLUMN MASTER.OBOROT_KONS.SUMMA_UCHET IS 'Учетная сумма';

COMMENT ON COLUMN MASTER.OBOROT_KONS.UPDATE_USER IS 'Пользователь';

COMMENT ON COLUMN MASTER.OBOROT_KONS.UPDATE_DATE IS 'Дата-время обновления';

COMMENT ON COLUMN MASTER.OBOROT_KONS.AKCIZ_SVED IS 'Признак акцизного свидетельства';

COMMENT ON COLUMN MASTER.OBOROT_KONS.ORG_STRU_ID IS 'ID ОСЕ';

COMMENT ON COLUMN MASTER.OBOROT_KONS.PREDPR_KONS_ID IS 'Предприятие';

COMMENT ON COLUMN MASTER.OBOROT_KONS.PROD_KONS_ID IS 'Продукт (конс.отчетность)';

COMMENT ON COLUMN MASTER.OBOROT_KONS.PREDPR_CLASS_ID IS 'Классификатор предприятий';

COMMENT ON COLUMN MASTER.OBOROT_KONS.TIP_OP_ID IS 'Тип операции';

COMMENT ON COLUMN MASTER.OBOROT_KONS.ST_PRIH_ID IS 'Статья прихода';

COMMENT ON COLUMN MASTER.OBOROT_KONS.ST_RASH_ID IS 'Статья расхода';

COMMENT ON COLUMN MASTER.OBOROT_KONS.TIP_REAL_ID IS 'Тип реализации';

COMMENT ON COLUMN MASTER.OBOROT_KONS.VID_REAL_ID IS 'Вид реализации';

COMMENT ON COLUMN MASTER.OBOROT_KONS.VID_POST_ID IS 'Вид поставки';

COMMENT ON COLUMN MASTER.OBOROT_KONS.OTGR_POST_ID IS 'Отгрузка-поставка';

COMMENT ON COLUMN MASTER.OBOROT_KONS.ORG_POLUCH_ID IS 'ID ОСЕ';

COMMENT ON COLUMN MASTER.OBOROT_KONS.FILIAL_ID IS 'ID ОСЕ';



