--
-- OIL_TRACE  (Table) 
--
CREATE TABLE MASTER.OIL_TRACE
(
  KOD          NUMBER,
  KOD_PLAN     NUMBER,
  DATAPOR      DATE,
  NOMER        VARCHAR2(20 BYTE),
  SOBSTV       NUMBER,
  POSTAVSH     NUMBER,
  PRODUKT      NUMBER,
  MESTOR       NUMBER,
  PRIEM        NUMBER,
  SDACHA       NUMBER,
  PERERAB      NUMBER,
  VSEGO        NUMBER,
  POTERI       NUMBER,
  POTERIFAKT   NUMBER,
  OSTAT        NUMBER,
  FOR_SOBST    VARCHAR2(100 BYTE),
  IS_CLOSE     NUMBER,
  ID_PROD_NPR  VARCHAR2(5 BYTE),
  LICENSIAR    NUMBER
)
TABLESPACE USERS2
NOCOMPRESS ;


