--
-- OPL  (Table) 
--
CREATE TABLE MASTER.OPL
(
  KOD_PLD     NUMBER,
  RS_PLD      VARCHAR2(12 BYTE),
  PLAT_DOG    VARCHAR2(60 BYTE),
  SUMMA       NUMBER,
  NOM_POR     VARCHAR2(7 BYTE),
  DATA_POR    DATE,
  KOD_PLP     NUMBER,
  PLAT_POR    VARCHAR2(60 BYTE),
  NAZN_PLAT   VARCHAR2(255 BYTE),
  DATA_POST   DATE,
  TIP         NUMBER,
  DAV_ORG     NUMBER,
  N_SCHET     NUMBER,
  BANK_NOM    NUMBER,
  NOM_DOG     VARCHAR2(10 BYTE),
  KOL         NUMBER,
  BANK        NUMBER,
  N_BANK      VARCHAR2(30 BYTE),
  NAM_VEK     VARCHAR2(20 BYTE),
  PATH        VARCHAR2(20 BYTE),
  T_TIME      VARCHAR2(8 BYTE),
  T_DATE      DATE,
  K_SCHET     VARCHAR2(4 BYTE),
  NOM_DOK     NUMBER,
  STN_DOK     NUMBER,
  DISKONT     NUMBER,
  DATA_VIP    DATE,
  PR_DOG      NUMBER,
  DATECANCEL  DATE,
  EMITENT     NUMBER,
  INV         NUMBER,
  AVIZO       VARCHAR2(1 BYTE),
  DEN_SOP     VARCHAR2(1 BYTE),
  VZ          VARCHAR2(1 BYTE),
  PROGRAM     NUMBER(2)                         DEFAULT 0,
  DOG_ID      NUMBER(10),
  IS_SNP      NUMBER(1)
)
TABLESPACE USERS2
NOCOMPRESS ;


