--
-- ORG_STRUCTURE  (Table) 
--
CREATE TABLE MASTER.ORG_STRUCTURE
(
  ID                     NUMBER(10)             NOT NULL,
  ADRESS                 VARCHAR2(100 BYTE),
  NOTE                   VARCHAR2(100 BYTE),
  NAME                   VARCHAR2(100 BYTE),
  ORG_KIND_ID            NUMBER(10),
  PREDPR_ID              NUMBER(6),
  ORG_TYPE_ID            NUMBER(10)             DEFAULT NULL,
  IS_AUTO_LINK           NUMBER(1)              DEFAULT 1,
  FILIAL                 NUMBER(10),
  WORKSHOP               VARCHAR2(10 BYTE),
  INN                    VARCHAR2(15 BYTE),
  IS_AUTO_KONS           NUMBER(1)              DEFAULT 1,
  PLAN_REAL              NUMBER(2),
  CITY_PREFIX_FILE       VARCHAR2(20 BYTE),
  CITY_IN_XLS            VARCHAR2(30 BYTE),
  FULL_NAME              VARCHAR2(50 BYTE),
  PARUS_CRN_AUTO         NUMBER(17),
  PARUS_CRN_KNT          NUMBER(17),
  PARUS_DEPARTMENT       VARCHAR2(30 BYTE),
  PARUS_PLAN_AZC_DEP     VARCHAR2(15 BYTE),
  PARUS_PLAN_AUTO_DEP    VARCHAR2(15 BYTE),
  PARUS_PLAN_MB_DEP      VARCHAR2(15 BYTE),
  PARUS_PLAN_TRAN_DEP    VARCHAR2(15 BYTE),
  PARUS_PLAN_AZC_DEP_2   VARCHAR2(15 BYTE),
  PARUS_PLAN_AUTO_DEP_2  VARCHAR2(15 BYTE),
  PARUS_PLAN_TRAN_DEP_2  VARCHAR2(15 BYTE),
  ABBR                   VARCHAR2(15 BYTE),
  RAST                   NUMBER(10,2),
  TRANS_ORG              VARCHAR2(50 BYTE),
  NO_WORK                NUMBER(1)              DEFAULT 0,
  IS_AUTO                NUMBER(1)              DEFAULT 1,
  IS_AUTO_FOR_DISP_AZS   NUMBER(1)              DEFAULT 1,
  LOAD_NALIV_FROM_XLS    NUMBER(1)              DEFAULT 0,
  LOAD_NALIV_FROM_PARUS  NUMBER(1)              DEFAULT 1,
  LOAD_FAS_FROM_XLS      NUMBER(1)              DEFAULT 0,
  LOAD_FAS_FROM_PARUS    NUMBER(1)              DEFAULT 1,
  KSSS_ID                NUMBER
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.ID IS 'ID ОСЕ';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.ADRESS IS 'Адрес ОСЕ';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.NOTE IS 'Дополнение';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.NAME IS 'Наименование ОСЕ';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.IS_AUTO_LINK IS '0 - запрет обновления';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.FILIAL IS 'ID филиала (конс.отчетность)';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.WORKSHOP IS 'Цех (конс.отчетность)';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.INN IS 'ИНН';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.PLAN_REAL IS 'Видеть при вводе плана реализации';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.CITY_PREFIX_FILE IS 'Филиал в имени файла';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.CITY_IN_XLS IS 'Филиал внутри XLS-файла';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.FULL_NAME IS 'Полное имя';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.PARUS_CRN_AUTO IS 'Каталог лиц.счетов в Парусе (Заказы)';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.PARUS_CRN_KNT IS 'Каталог лиц.счетов Маслобазы (Заказы)';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.PARUS_DEPARTMENT IS 'Наименование штатного подразделения в Парусе';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.PARUS_PLAN_AZC_DEP IS 'Подразделение для планов - реализация с АЗС';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.PARUS_PLAN_AUTO_DEP IS 'Подразделение для планов - реализация с НБ';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.PARUS_PLAN_MB_DEP IS 'Подразделение для планов - реализация с Маслобазы';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.PARUS_PLAN_TRAN_DEP IS 'Подразделение для планов - транзит';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.PARUS_PLAN_AZC_DEP_2 IS 'Подразделение для планов - реализация с АЗС';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.PARUS_PLAN_AUTO_DEP_2 IS 'Подразделение для планов - реализация с НБ';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.PARUS_PLAN_TRAN_DEP_2 IS 'Подразделение для планов - транзит';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.ABBR IS 'Кратко';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.RAST IS 'Расстояние';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.TRANS_ORG IS 'Транспортная организация';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.NO_WORK IS '1-Не работает';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.IS_AUTO IS '1=Автоматизирована';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.IS_AUTO_FOR_DISP_AZS IS '1=Выбирать данные из Паруса (для Контроля АЗС)';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.LOAD_NALIV_FROM_XLS IS '1=Загружать наливные из XLS';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.LOAD_NALIV_FROM_PARUS IS '1=Загружать наливные из Паруса';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.LOAD_FAS_FROM_XLS IS '1=Загружать фасовку из XLS';

COMMENT ON COLUMN MASTER.ORG_STRUCTURE.LOAD_FAS_FROM_PARUS IS '1=Загружать фасовку из Паруса';



