--
-- ORG_RELATIONS  (Table) 
--
CREATE TABLE MASTER.ORG_RELATIONS
(
  ORG_STRU_1_ID  NUMBER(10)                     NOT NULL,
  ORG_STRU_2_ID  NUMBER(10)                     DEFAULT 0                     NOT NULL,
  KIND_RELA_ID   NUMBER(10),
  IS_ROOT        NUMBER(1)                      DEFAULT 0
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.ORG_RELATIONS.ORG_STRU_1_ID IS 'ID няе';

COMMENT ON COLUMN MASTER.ORG_RELATIONS.ORG_STRU_2_ID IS 'ID няе';



