--
-- OSTAT_KONS  (Table) 
--
CREATE TABLE MASTER.OSTAT_KONS
(
  ID_OST             NUMBER(18)                 NOT NULL,
  DATE_OST           DATE,
  KOL                VARCHAR2(240 BYTE)         DEFAULT '0',
  KG                 NUMBER(15,3)               DEFAULT 0,
  LIT                NUMBER(15,3)               DEFAULT 0,
  SUMMA_POKUP_BN     NUMBER(15,2)               DEFAULT 0,
  SUMMA_POKUP_NDS    NUMBER(15,2)               DEFAULT 0,
  SUMMA_POKUP_AKCIZ  NUMBER(15,2)               DEFAULT 0,
  SUMMA_POKUP        NUMBER(15,2)               DEFAULT 0,
  SUMMA_UCHET        NUMBER(15,2)               DEFAULT 0,
  ORG_STRU_ID        NUMBER(10),
  PREDPR_KONS_ID     NUMBER(20),
  PROD_KONS_ID       VARCHAR2(21 BYTE),
  FILIAL_ID          NUMBER(10)                 NOT NULL
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.OSTAT_KONS IS 'Конс.отчетность: остатки';

COMMENT ON COLUMN MASTER.OSTAT_KONS.ID_OST IS 'ID';

COMMENT ON COLUMN MASTER.OSTAT_KONS.DATE_OST IS 'Дата';

COMMENT ON COLUMN MASTER.OSTAT_KONS.KOL IS 'Кол-во';

COMMENT ON COLUMN MASTER.OSTAT_KONS.KG IS 'Вес (кг)';

COMMENT ON COLUMN MASTER.OSTAT_KONS.LIT IS 'Объем (литр)';

COMMENT ON COLUMN MASTER.OSTAT_KONS.SUMMA_POKUP_BN IS 'Сумма приобретения (без налогов)';

COMMENT ON COLUMN MASTER.OSTAT_KONS.SUMMA_POKUP_NDS IS 'НДС';

COMMENT ON COLUMN MASTER.OSTAT_KONS.SUMMA_POKUP_AKCIZ IS 'Акциз';

COMMENT ON COLUMN MASTER.OSTAT_KONS.SUMMA_POKUP IS 'Сумма приобретения';

COMMENT ON COLUMN MASTER.OSTAT_KONS.SUMMA_UCHET IS 'Учетная сумма';

COMMENT ON COLUMN MASTER.OSTAT_KONS.ORG_STRU_ID IS 'ID ОСЕ';

COMMENT ON COLUMN MASTER.OSTAT_KONS.PREDPR_KONS_ID IS 'Предприятие';

COMMENT ON COLUMN MASTER.OSTAT_KONS.PROD_KONS_ID IS 'Продукт (конс.отчетность)';

COMMENT ON COLUMN MASTER.OSTAT_KONS.FILIAL_ID IS 'ID ОСЕ';



