--
-- OSTAT_VYRAB  (Table) 
--
CREATE TABLE MASTER.OSTAT_VYRAB
(
  D_PLAN       DATE,
  QUANTITY     NUMBER,
  D_MAN        DATE,
  IS_HRAN      NUMBER,
  ID           NUMBER,
  ID_PROD_NPR  VARCHAR2(5 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


