--
-- PAYMENTS_ON_BILL_050208  (Table) 
--
CREATE TABLE MASTER.PAYMENTS_ON_BILL_050208
(
  ID           NUMBER(10),
  NOM_DOK      NUMBER(7),
  BILL_POS_ID  NUMBER(7),
  PAYMENTS_ID  NUMBER,
  SUMMA        NUMBER(15,2),
  DATE_REALIZ  DATE,
  SUMMA_NDS    NUMBER(20,6),
  SUMMA_AKCIZ  NUMBER(20,6)
)
TABLESPACE USERS2
NOCOMPRESS ;


