--
-- PAYMENTS_ON_BILLS  (Table) 
--
CREATE TABLE MASTER.PAYMENTS_ON_BILLS
(
  ID           NUMBER(10)                       NOT NULL,
  NOM_DOK      NUMBER(10),
  BILL_POS_ID  NUMBER(7),
  PAYMENTS_ID  NUMBER,
  SUMMA        NUMBER(15,2),
  DATE_REALIZ  DATE,
  SUMMA_NDS    NUMBER(20,6),
  SUMMA_AKCIZ  NUMBER(20,6),
  VES          NUMBER(15,6)
)
TABLESPACE USERS2
NOCOMPRESS ;


