--
-- PAYMENTS_TO_BILLS  (Table) 
--
CREATE TABLE MASTER.PAYMENTS_TO_BILLS
(
  PAYMENTS_ID  NUMBER                           NOT NULL,
  NOM_DOK      NUMBER(10)                       NOT NULL
)
TABLESPACE USERS2
NOCOMPRESS ;


