--
-- PLAN_REALIZ  (Table) 
--
CREATE TABLE MASTER.PLAN_REALIZ
(
  ID              NUMBER(10)                    NOT NULL,
  DATE_PLAN       DATE,
  VES             NUMBER(18,6)                  DEFAULT 0,
  SUPPLIER_ID     NUMBER(6),
  PROD_ID_NPR     VARCHAR2(5 BYTE),
  TIP_REAL_ID     NUMBER(10),
  VID_REAL_ID     NUMBER(10),
  ORG_KIND_ID     NUMBER(10),
  ORG_STRU_ID     NUMBER(10),
  PARUS_RN        NUMBER(17),
  PARUS_NOMEN     NUMBER(17),
  PARUS_NOMMODIF  NUMBER(17),
  SKLAD_ID        NUMBER(10),
  IS_KORR         NUMBER(1)                     DEFAULT 0,
  PLANSTRU_ID     NUMBER(10),
  SUMMA           NUMBER(15,2)                  DEFAULT 0,
  IS_SIGN1        NUMBER(1)                     DEFAULT 1,
  IS_SIGN2        NUMBER(1)                     DEFAULT 0,
  FIRST_PLAN      NUMBER(18,6)                  DEFAULT 0,
  SKLAD_ID_FROM   NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.PLAN_REALIZ IS 'План реализации';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.ID IS 'План реализации';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.DATE_PLAN IS 'Дата плана';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.VES IS 'План, тн';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.SUPPLIER_ID IS 'Поставщик';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.PROD_ID_NPR IS 'Продукт (MASTER)';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.TIP_REAL_ID IS 'Реализация_транзит';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.VID_REAL_ID IS 'Продажа Франчайзинг';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.ORG_KIND_ID IS 'АЗС Нефтебаза';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.ORG_STRU_ID IS 'Филиал';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.PARUS_RN IS 'Позиция графика (PARUS)';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.PARUS_NOMEN IS 'Продукт (PARUS)';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.PARUS_NOMMODIF IS 'Продукт (PARUS)';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.SKLAD_ID IS 'Склад';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.IS_KORR IS 'Признак корректировки';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.PLANSTRU_ID IS 'Позиция плана (для внутрикорп.транзита)';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.SUMMA IS 'План, руб';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.IS_SIGN1 IS 'Подпись 1 Внесено';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.IS_SIGN2 IS 'Подпись 2 Утверждено';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.FIRST_PLAN IS 'Первоначальный план';

COMMENT ON COLUMN MASTER.PLAN_REALIZ.SKLAD_ID_FROM IS 'Склад снабжения';



