--
-- PLAN_POST  (Table) 
--
CREATE TABLE MASTER.PLAN_POST
(
  ID           NUMBER(10)                       NOT NULL,
  PLAN_CENA    NUMBER(9,2)                      DEFAULT 0,
  PLAN_VES     NUMBER(15,6)                     DEFAULT 0,
  PLAN_SUM     NUMBER(15,2)                     DEFAULT 0,
  PLAN_ID      NUMBER(2),
  PLAN_PER_ID  NUMBER(10),
  PLANSTRU_ID  NUMBER(20),
  DOG_ID       NUMBER(5),
  PROD_ID_NPR  VARCHAR2(5 BYTE),
  PAYFORM_ID   NUMBER(2),
  DATE_CENA    DATE,
  CAT_CEN_ID   NUMBER(3),
  APPL_TAG     VARCHAR2(6 BYTE),
  REFINERY_ID  NUMBER(10)                       DEFAULT 8,
  ORGSTRU_ID   NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.PLAN_POST IS 'План поставок';

COMMENT ON COLUMN MASTER.PLAN_POST.PLAN_CENA IS 'Плановая цена';

COMMENT ON COLUMN MASTER.PLAN_POST.PLAN_VES IS 'Плановый объем';

COMMENT ON COLUMN MASTER.PLAN_POST.PLAN_SUM IS 'Плановая сумма';

COMMENT ON COLUMN MASTER.PLAN_POST.DATE_CENA IS 'Дата цены';

COMMENT ON COLUMN MASTER.PLAN_POST.REFINERY_ID IS 'Завод-производитель (ID из KLS_PREDPR)';

COMMENT ON COLUMN MASTER.PLAN_POST.ORGSTRU_ID IS 'Склад-получатель';



