--
-- PLAN_POST_SVOD  (Table) 
--
CREATE TABLE MASTER.PLAN_POST_SVOD
(
  ID           NUMBER(10)                       NOT NULL,
  DATE_PLAN    DATE,
  VES          NUMBER(18,6)                     DEFAULT 0,
  HRAN         NUMBER(18,6)                     DEFAULT 0,
  SUPPLIER_ID  NUMBER(6),
  PROD_ID_NPR  VARCHAR2(5 BYTE),
  PLANSTRU_ID  NUMBER(10),
  IS_KORR      NUMBER(1)                        DEFAULT 0
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.PLAN_POST_SVOD IS 'План закупок';

COMMENT ON COLUMN MASTER.PLAN_POST_SVOD.ID IS 'План закупок';

COMMENT ON COLUMN MASTER.PLAN_POST_SVOD.DATE_PLAN IS 'Дата плана';

COMMENT ON COLUMN MASTER.PLAN_POST_SVOD.VES IS 'План (ВСЕГО)';

COMMENT ON COLUMN MASTER.PLAN_POST_SVOD.HRAN IS 'В т.ч. хранение';

COMMENT ON COLUMN MASTER.PLAN_POST_SVOD.SUPPLIER_ID IS 'Поставщик';

COMMENT ON COLUMN MASTER.PLAN_POST_SVOD.PROD_ID_NPR IS 'Продукт';

COMMENT ON COLUMN MASTER.PLAN_POST_SVOD.PLANSTRU_ID IS 'Позиция плана поставки';

COMMENT ON COLUMN MASTER.PLAN_POST_SVOD.IS_KORR IS 'Корректировка';



