--
-- PLAN_FACT  (Table) 
--
CREATE TABLE MASTER.PLAN_FACT
(
  ID               NUMBER(10)                   NOT NULL,
  TERMINAL_NAME    VARCHAR2(30 BYTE),
  OSUSER_NAME      VARCHAR2(30 BYTE),
  TIP_ROW          VARCHAR2(10 BYTE),
  GROUP_ORDER      NUMBER(10),
  GROUP_NAME       VARCHAR2(30 BYTE),
  PROD_ORDER       NUMBER(10),
  PROD_ID_NPR      VARCHAR2(10 BYTE),
  PLANSTRU_ORDER   VARCHAR2(18 BYTE),
  PLANSTRU_ID      NUMBER(10),
  DATE_PLAN        DATE,
  PLAN_MON_C       NUMBER(18,6)                 DEFAULT 0,
  PLAN_MON_V       NUMBER(18,6)                 DEFAULT 0,
  PLAN_MON_SOBS_C  NUMBER(18,6)                 DEFAULT 0,
  PLAN_MON_SOBS_V  NUMBER(18,6)                 DEFAULT 0,
  PLAN_NAR_C       NUMBER(18,6)                 DEFAULT 0,
  PLAN_NAR_V       NUMBER(18,6)                 DEFAULT 0,
  PLAN_NAR_SOBS_C  NUMBER(18,6)                 DEFAULT 0,
  PLAN_NAR_SOBS_V  NUMBER(18,6)                 DEFAULT 0,
  DATE_ZAYV        DATE,
  ZAYV             NUMBER(18,6)                 DEFAULT 0,
  DATE_BEG_OST     DATE,
  TIME_BEG_OST     VARCHAR2(5 BYTE),
  BEG_OST          NUMBER(18,6)                 DEFAULT 0,
  DATE_FACT        DATE,
  TIME_FACT        VARCHAR2(5 BYTE),
  FACT_C           NUMBER(18,6)                 DEFAULT 0,
  FACT_V           NUMBER(18,6)                 DEFAULT 0,
  FACT_SOBS_C      NUMBER(18,6)                 DEFAULT 0,
  FACT_SOBS_V      NUMBER(18,6)                 DEFAULT 0,
  DATE_EMPTY_VOL   DATE,
  TIME_EMPTY_VOL   VARCHAR2(5 BYTE),
  MAX_VOL          NUMBER(18,6)                 DEFAULT 0,
  DEAD_VOL         NUMBER(18,6)                 DEFAULT 0,
  VOL              NUMBER(18,6)                 DEFAULT 0,
  EMPTY_VOL        NUMBER(18,6)                 DEFAULT 0,
  DATE_OST         DATE,
  TIME_OST         VARCHAR2(5 BYTE),
  OST              NUMBER(18,6)                 DEFAULT 0,
  NB_NAME          VARCHAR2(30 BYTE),
  NOMMODIF_NAME    VARCHAR2(100 BYTE),
  DICNOMNS_RN      NUMBER(17),
  NOMMODIF_RN      NUMBER(17),
  CONTRACTS_RN     NUMBER(17),
  STAGES_RN        NUMBER(17),
  FACEACC_RN       NUMBER(17),
  FACEACC_CODE     VARCHAR2(20 BYTE),
  ZAYV_RN          NUMBER(17),
  ZAYV_PREF        VARCHAR2(20 BYTE),
  TIP_OTGR_RN      NUMBER,
  TIP_OTGR_NAME    VARCHAR2(30 BYTE),
  PAYTYPE_RN       NUMBER(17),
  PAYTYPE_NAME     VARCHAR2(30 BYTE),
  POLUCH_RN        NUMBER(17),
  POLUCH_NAME      VARCHAR2(200 BYTE),
  CONTRACTS_NUMB   VARCHAR2(50 BYTE),
  AGENT_RN         NUMBER(17),
  AGENT_NAME       VARCHAR2(100 BYTE),
  OBR_MON_V        NUMBER(18,6),
  OBR_NAR_V        NUMBER(18,6),
  PLAN_NAR_RASP    NUMBER(18,6),
  OBR_NAR_RASP     NUMBER(18,6),
  KORR_MON_V       NUMBER(18,6),
  KORR_NAR_V       NUMBER(18,6),
  KORR_NAR_RASP    NUMBER(18,6),
  FACT_SUT_C       NUMBER(18,6)                 DEFAULT 0,
  FACT_SUT_V       NUMBER(18,6)                 DEFAULT 0,
  FACT_SOBS_SUT_C  NUMBER(18,6)                 DEFAULT 0,
  FACT_SOBS_SUT_V  NUMBER(18,6)                 DEFAULT 0,
  PLAN_NAR_RASP_7  NUMBER(18,6),
  OBR_NAR_RASP_7   NUMBER(18,6),
  FACT_NAR_7       NUMBER(18,6),
  FACT_DECADA_1    NUMBER(18,6)                 DEFAULT 0,
  FACT_DECADA_2    NUMBER(18,6)                 DEFAULT 0,
  FACT_DECADA_3    NUMBER(18,6)                 DEFAULT 0,
  PLAN_DECADA_1    NUMBER(18,6)                 DEFAULT 0,
  PLAN_DECADA_2    NUMBER(18,6)                 DEFAULT 0,
  PLAN_DECADA_3    NUMBER(18,6)                 DEFAULT 0,
  NUM_DECADA       NUMBER(1)                    DEFAULT 0
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.PLAN_FACT IS 'ПЛАН-ФАКТ';

COMMENT ON COLUMN MASTER.PLAN_FACT.ID IS 'План-факт';

COMMENT ON COLUMN MASTER.PLAN_FACT.TERMINAL_NAME IS 'Сетевое имя машины';

COMMENT ON COLUMN MASTER.PLAN_FACT.OSUSER_NAME IS 'Сетевое имя пользователя';

COMMENT ON COLUMN MASTER.PLAN_FACT.TIP_ROW IS 'Тип данных';

COMMENT ON COLUMN MASTER.PLAN_FACT.GROUP_ORDER IS 'Порядок групп';

COMMENT ON COLUMN MASTER.PLAN_FACT.GROUP_NAME IS 'Группа';

COMMENT ON COLUMN MASTER.PLAN_FACT.PROD_ORDER IS 'Порядок продуктов';

COMMENT ON COLUMN MASTER.PLAN_FACT.PROD_ID_NPR IS 'Продукт';

COMMENT ON COLUMN MASTER.PLAN_FACT.PLANSTRU_ORDER IS 'Порядок позиций';

COMMENT ON COLUMN MASTER.PLAN_FACT.PLANSTRU_ID IS 'Позиция плана';

COMMENT ON COLUMN MASTER.PLAN_FACT.DATE_PLAN IS 'Дата плана (по дату вкл.)';

COMMENT ON COLUMN MASTER.PLAN_FACT.PLAN_MON_C IS 'План за месяц в цист.';

COMMENT ON COLUMN MASTER.PLAN_FACT.PLAN_MON_V IS 'План за месяц в тн.';

COMMENT ON COLUMN MASTER.PLAN_FACT.PLAN_MON_SOBS_C IS 'План за месяц в цист. (собс.ваг.)';

COMMENT ON COLUMN MASTER.PLAN_FACT.PLAN_MON_SOBS_V IS 'План за месяц в тн. (собс.ваг.)';

COMMENT ON COLUMN MASTER.PLAN_FACT.PLAN_NAR_C IS 'План нарастающий в цист.';

COMMENT ON COLUMN MASTER.PLAN_FACT.PLAN_NAR_V IS 'План нарастающий в тн.';

COMMENT ON COLUMN MASTER.PLAN_FACT.PLAN_NAR_SOBS_C IS 'План нарастающий в цист. (собс.ваг.)';

COMMENT ON COLUMN MASTER.PLAN_FACT.PLAN_NAR_SOBS_V IS 'План нарастающий в тн. (собс.ваг.)';

COMMENT ON COLUMN MASTER.PLAN_FACT.DATE_ZAYV IS 'Дата заявленного объема (по дату вкл.)';

COMMENT ON COLUMN MASTER.PLAN_FACT.ZAYV IS 'Заявлено';

COMMENT ON COLUMN MASTER.PLAN_FACT.DATE_BEG_OST IS 'Дата начального остатка';

COMMENT ON COLUMN MASTER.PLAN_FACT.TIME_BEG_OST IS 'Время начального остатка';

COMMENT ON COLUMN MASTER.PLAN_FACT.BEG_OST IS 'Остаток в начале';

COMMENT ON COLUMN MASTER.PLAN_FACT.DATE_FACT IS 'Дата факта (по дату вкл.)';

COMMENT ON COLUMN MASTER.PLAN_FACT.TIME_FACT IS 'Время факта';

COMMENT ON COLUMN MASTER.PLAN_FACT.FACT_C IS 'Факт в цист.';

COMMENT ON COLUMN MASTER.PLAN_FACT.FACT_V IS 'Факт в тн.';

COMMENT ON COLUMN MASTER.PLAN_FACT.FACT_SOBS_C IS 'Факт в цист. (собс.ваг.)';

COMMENT ON COLUMN MASTER.PLAN_FACT.FACT_SOBS_V IS 'Факт в тн. (собс.ваг.)';

COMMENT ON COLUMN MASTER.PLAN_FACT.DATE_EMPTY_VOL IS 'Дата свободных емкостей';

COMMENT ON COLUMN MASTER.PLAN_FACT.TIME_EMPTY_VOL IS 'Время свободных емкостей';

COMMENT ON COLUMN MASTER.PLAN_FACT.EMPTY_VOL IS 'Свободная емкость';

COMMENT ON COLUMN MASTER.PLAN_FACT.DATE_OST IS 'Дата конечного остатка';

COMMENT ON COLUMN MASTER.PLAN_FACT.TIME_OST IS 'Время конечного остатка';

COMMENT ON COLUMN MASTER.PLAN_FACT.OST IS 'Конечный остаток';

COMMENT ON COLUMN MASTER.PLAN_FACT.NB_NAME IS 'Нефтебаза';

COMMENT ON COLUMN MASTER.PLAN_FACT.OBR_MON_V IS 'ОБР за месяц в тн.';

COMMENT ON COLUMN MASTER.PLAN_FACT.OBR_NAR_V IS 'ОБР нарастающий за месяц в тн.';

COMMENT ON COLUMN MASTER.PLAN_FACT.PLAN_NAR_RASP IS 'План нарастающий без нераспред.ресурса';

COMMENT ON COLUMN MASTER.PLAN_FACT.OBR_NAR_RASP IS 'ОБР без нераспред.ресурса';

COMMENT ON COLUMN MASTER.PLAN_FACT.KORR_MON_V IS 'Заявка на корректировку в тн';

COMMENT ON COLUMN MASTER.PLAN_FACT.KORR_NAR_V IS 'Заявка на корректировку нараст';

COMMENT ON COLUMN MASTER.PLAN_FACT.KORR_NAR_RASP IS 'Заявка на корректировку без нераспр. ресурса';

COMMENT ON COLUMN MASTER.PLAN_FACT.FACT_SUT_C IS 'Факт в цист. за отчетные сутки';

COMMENT ON COLUMN MASTER.PLAN_FACT.FACT_SUT_V IS 'Факт в тн. за отчетные сутки';

COMMENT ON COLUMN MASTER.PLAN_FACT.FACT_SOBS_SUT_C IS 'Факт в цист. за отчетные сутки (собс.ваг)';

COMMENT ON COLUMN MASTER.PLAN_FACT.FACT_SOBS_SUT_V IS 'Факт в тн. за отчетные сутки (собс.ваг)';

COMMENT ON COLUMN MASTER.PLAN_FACT.PLAN_NAR_RASP_7 IS 'План нарастающий 7 дней назад';

COMMENT ON COLUMN MASTER.PLAN_FACT.OBR_NAR_RASP_7 IS 'ОБР нарастающий 7 дней назад';

COMMENT ON COLUMN MASTER.PLAN_FACT.FACT_NAR_7 IS 'Факт нарастающий 7 дней назад';

COMMENT ON COLUMN MASTER.PLAN_FACT.FACT_DECADA_1 IS 'Факт за 1 декаду';

COMMENT ON COLUMN MASTER.PLAN_FACT.FACT_DECADA_2 IS 'Факт за 2 декаду';

COMMENT ON COLUMN MASTER.PLAN_FACT.FACT_DECADA_3 IS 'Факт за 3 декаду';

COMMENT ON COLUMN MASTER.PLAN_FACT.PLAN_DECADA_1 IS 'План за 1 декаду';

COMMENT ON COLUMN MASTER.PLAN_FACT.PLAN_DECADA_2 IS 'План за 2 декаду';

COMMENT ON COLUMN MASTER.PLAN_FACT.PLAN_DECADA_3 IS 'План за 3 декаду';

COMMENT ON COLUMN MASTER.PLAN_FACT.NUM_DECADA IS '№ декады';



