--
-- PLAN_FACT_REALIZ  (Table) 
--
CREATE TABLE MASTER.PLAN_FACT_REALIZ
(
  TERMINAL_NAME       VARCHAR2(30 BYTE),
  OSUSER_NAME         VARCHAR2(30 BYTE),
  TIP_ROW             VARCHAR2(40 BYTE),
  DATE_BEGIN          DATE,
  DATE_END            DATE,
  DATE_PLAN           DATE,
  FILIAL_ORDER        NUMBER(10),
  FILIAL_ID           NUMBER(10),
  FILIAL_NAME         VARCHAR2(100 BYTE),
  REGION_ORDER        NUMBER(10),
  REGION_NAME         VARCHAR2(30 BYTE),
  NAPR_ORDER          NUMBER(10),
  NAPR_NAME           VARCHAR2(30 BYTE),
  PROD_ID_NPR         VARCHAR2(6 BYTE),
  PROD_ORDER          NUMBER(10),
  PROD_NAME           VARCHAR2(100 BYTE),
  GROUP_ORDER         NUMBER(10),
  GROUP_NAME          VARCHAR2(100 BYTE),
  BEGIN_OST           NUMBER(15,6)              DEFAULT 0,
  PLAN_POST_VES       NUMBER(15,6)              DEFAULT 0,
  NORMA_POST_VES      NUMBER(15,6)              DEFAULT 0,
  FACT_POST_VES       NUMBER(15,6)              DEFAULT 0,
  RESURS              NUMBER(15,6)              DEFAULT 0,
  PLAN_REAL_VES       NUMBER(15,6)              DEFAULT 0,
  NORMA_REAL_VES      NUMBER(15,6)              DEFAULT 0,
  FACT_REAL_VES       NUMBER(15,6)              DEFAULT 0,
  END_OST             NUMBER(20,6)              DEFAULT 0,
  ORG_KIND_ORDER      NUMBER(10),
  ORG_KIND_ID         NUMBER(10),
  ORG_KIND_NAME       VARCHAR2(30 BYTE),
  ORG_STRU_ORDER      NUMBER(10),
  ORG_STRU_ID         NUMBER(10),
  ORG_STRU_NAME       VARCHAR2(50 BYTE),
  AVG_SUT_REAL_VES    NUMBER(15,6)              DEFAULT 0,
  GROUP_FULL_NAME     VARCHAR2(50 BYTE),
  FACT_REAL_SUMMA     NUMBER(15,2),
  AVG_SUT_REAL_SUMMA  NUMBER(15,2)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.PLAN_FACT_REALIZ IS 'ПЛАН-ФАКТ ПОСТАВКИ И РЕАЛИЗАЦИИ';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.TERMINAL_NAME IS 'Сетевое имя машины';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.OSUSER_NAME IS 'Сетевое имя пользователя';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.TIP_ROW IS 'Тип данных';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.DATE_BEGIN IS 'С даты';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.DATE_END IS 'По дату';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.DATE_PLAN IS 'Дата плана';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.FILIAL_ORDER IS 'Филиал';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.FILIAL_ID IS 'Филиал';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.FILIAL_NAME IS 'Филиал';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.REGION_ORDER IS 'Регион реализации';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.REGION_NAME IS 'Регион реализации';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.NAPR_ORDER IS 'Направление реализации';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.NAPR_NAME IS 'Направление реализации';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.PROD_ID_NPR IS 'Продукт';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.PROD_ORDER IS 'Продукт';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.PROD_NAME IS 'Продукт';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.GROUP_ORDER IS 'Порядок групп продуктов';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.GROUP_NAME IS 'Группа продуктов';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.BEGIN_OST IS 'Начальный остаток';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.PLAN_POST_VES IS 'План поставки';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.FACT_POST_VES IS 'Факт поставки';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.RESURS IS 'Ресурс';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.PLAN_REAL_VES IS 'План реализации';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.FACT_REAL_VES IS 'Факт реализации';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.END_OST IS 'Конечный остаток';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.ORG_KIND_ORDER IS 'Вид подразделения';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.ORG_KIND_ID IS 'Вид подразделения';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.ORG_KIND_NAME IS 'Вид подразделения';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.ORG_STRU_ORDER IS 'Подразделение';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.ORG_STRU_ID IS 'Подразделение';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.ORG_STRU_NAME IS 'Подразделение';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.AVG_SUT_REAL_VES IS 'Среднесуточная реализация';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.GROUP_FULL_NAME IS 'Полное наименование группы нефтепродуктов';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.FACT_REAL_SUMMA IS 'Факт реализации в рублях';

COMMENT ON COLUMN MASTER.PLAN_FACT_REALIZ.AVG_SUT_REAL_SUMMA IS 'Среднесуточная реализация в рублях';



