--
-- PLAN_POST_HIST  (Table) 
--
CREATE TABLE MASTER.PLAN_POST_HIST
(
  ID           NUMBER(10)                       NOT NULL,
  NUM_IZM      NUMBER(2)                        NOT NULL,
  PLAN_CENA    NUMBER(9,2)                      DEFAULT 0,
  PLAN_VES     NUMBER(15,6)                     DEFAULT 0,
  PLAN_SUM     NUMBER(15,2)                     DEFAULT 0,
  PLAN_ID      NUMBER(2),
  PLAN_PER_ID  NUMBER(10),
  PLANSTRU_ID  NUMBER(20),
  DOG_ID       NUMBER(5),
  PROD_ID_NPR  VARCHAR2(5 BYTE),
  PAYFORM_ID   NUMBER(2),
  DATE_CENA    DATE,
  CAT_CEN_ID   NUMBER(3),
  REFINERY_ID  NUMBER(10),
  ORGSTRU_ID   NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


