--
-- PLAN_RESU  (Table) 
--
CREATE TABLE MASTER.PLAN_RESU
(
  ID           NUMBER(10)                       NOT NULL,
  PLAN_UTMSK   NUMBER(15,6)                     DEFAULT 0,
  HRAN_UTMSK   NUMBER(15,6)                     DEFAULT 0,
  OSTAT_UTMSK  NUMBER(15,6)                     DEFAULT 0,
  PROD_ID_NPR  VARCHAR2(5 BYTE),
  PLAN_ID      NUMBER(2),
  PLAN_PER_ID  NUMBER(10),
  SOBSTV_ID    NUMBER(6),
  REFINER_ID   NUMBER(6)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.PLAN_RESU.PLAN_UTMSK IS 'План выработки';

COMMENT ON COLUMN MASTER.PLAN_RESU.HRAN_UTMSK IS 'На хранении';

COMMENT ON COLUMN MASTER.PLAN_RESU.OSTAT_UTMSK IS 'Остатки';



