--
-- PLAN_POST_PRICHIN  (Table) 
--
CREATE TABLE MASTER.PLAN_POST_PRICHIN
(
  ID           NUMBER,
  BEG_DATE     DATE,
  END_DATE     DATE,
  TO_MOS       NUMBER(1),
  ORDNUNG      NUMBER,
  PROD_ID_NPR  VARCHAR2(5 BYTE),
  PLANSTRU_ID  NUMBER,
  OWNER_ID     NUMBER,
  PLAN         NUMBER,
  IZM_PLAN     NUMBER,
  OBPR         NUMBER,
  NORMA        NUMBER,
  NORMA_OBPR   NUMBER,
  FACT         NUMBER,
  RAZN_TONN    NUMBER,
  RAZN_DAT     DATE,
  ZAYV_TONN    NUMBER,
  ZAYV_DAT     DATE,
  PRICHIN_ID   NUMBER,
  NOTE         VARCHAR2(250 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


