--
-- PODACHA_ROWS  (Table) 
--
CREATE TABLE MASTER.PODACHA_ROWS
(
  ID             NUMBER(10)                     NOT NULL,
  PODACHA_ID     NUMBER(10),
  NUM_POS        NUMBER(10),
  NUM_CIST       VARCHAR2(10 BYTE),
  KALIBR_ID      VARCHAR2(5 BYTE),
  VAGOWNER_ID    NUMBER(10),
  AXES           NUMBER(2),
  CAPACITY       VARCHAR2(10 BYTE),
  VAGONTYPE_ID   NUMBER(10),
  NCISTDOP       NUMBER(2),
  VAG_STATUS_ID  NUMBER(10),
  DEFI_MASS_ID   NUMBER(10),
  VETKA_POD_ID   NUMBER(10),
  VES            NUMBER(10,3),
  KOL_NET        NUMBER(10,3),
  VES_BRUTTO     NUMBER(10,3),
  VES_CIST       NUMBER(10,3),
  ZPU_TYPE1      NUMBER(10),
  ZPU_TYPE2      NUMBER(10),
  PLOMBA1        VARCHAR2(15 BYTE),
  PLOMBA2        VARCHAR2(15 BYTE),
  VZLIV          NUMBER(6),
  VOLUME         NUMBER(10),
  TEMPER         NUMBER(10,1),
  PL15           NUMBER(10,4),
  PL20           NUMBER(10,4),
  FACT_PL        NUMBER(10,4),
  PASP_ID        VARCHAR2(9 BYTE),
  PASP_NUM       VARCHAR2(20 BYTE),
  PASP_DATE      DATE,
  REZ_NUM        VARCHAR2(20 BYTE),
  PROD_ID_NPR    VARCHAR2(5 BYTE),
  WATER_P        NUMBER(6,4),
  SALT_P         NUMBER(6,4),
  SALT_MG        NUMBER(5,1),
  DIRT_P         NUMBER(6,4),
  SULFUR_P       NUMBER(6,4),
  NOM_ZD         VARCHAR2(12 BYTE),
  SVED_NUM       NUMBER(6),
  SVED_DATE      DATE
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.PODACHA_ROWS IS 'Позиции ведомости подачи';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.ID IS 'Позиции ведомости подачи';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.PODACHA_ID IS 'Ведомость подачи';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.NUM_POS IS 'Номер позиции по порядку';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.NUM_CIST IS 'Номер цистерны';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.KALIBR_ID IS 'Тип вагона';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.VAGOWNER_ID IS 'Собственник/владелец вагона';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.AXES IS 'Оси';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.CAPACITY IS 'Грузоподъемность';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.VAGONTYPE_ID IS 'Род вагона';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.NCISTDOP IS 'Признак дорог СНГ';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.VAG_STATUS_ID IS 'Состояние вагона';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.DEFI_MASS_ID IS 'Метод определения массы';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.VETKA_POD_ID IS 'Путь подачи';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.VES IS 'Вес';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.KOL_NET IS 'Вес НЕТТО для нефти';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.VES_BRUTTO IS 'Вес БРУТТО (жд)';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.VES_CIST IS 'Вес вагона';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.ZPU_TYPE1 IS 'Тип пломбы 1';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.ZPU_TYPE2 IS 'Тип пломбы 2';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.PLOMBA1 IS 'Пломба 1';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.PLOMBA2 IS 'Пломба 2';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.VZLIV IS 'Взлив';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.VOLUME IS 'Объем';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.TEMPER IS 'Температура';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.PL15 IS 'Плотность при 15';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.PL20 IS 'Плотность при 20';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.FACT_PL IS 'Фактическая плотность';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.PASP_ID IS 'ID паспорта';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.PASP_NUM IS 'N паспорта';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.PASP_DATE IS 'Дата паспорта';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.REZ_NUM IS 'N резервуара';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.PROD_ID_NPR IS 'Продукт';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.WATER_P IS 'Обводненность, %';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.SALT_P IS 'Хлористые соли, %';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.SALT_MG IS 'Хлористые соли, мг/л';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.DIRT_P IS 'Механические примеси, %';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.SULFUR_P IS 'Сера, %';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.NOM_ZD IS 'N задания';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.SVED_NUM IS 'N сведения';

COMMENT ON COLUMN MASTER.PODACHA_ROWS.SVED_DATE IS 'Дата сведения';



