--
-- PODACHA  (Table) 
--
CREATE TABLE MASTER.PODACHA
(
  ID              NUMBER(10)                    NOT NULL,
  POD_NUM         VARCHAR2(20 BYTE),
  POD_DATE        DATE,
  KOL             NUMBER(3)                     DEFAULT NULL,
  VES             NUMBER(12,3)                  DEFAULT NULL,
  GOTOV_DATE      DATE,
  NALIV_DATE      DATE,
  LUKOMA_NUM      NUMBER(7),
  MPS_NUM         NUMBER(7),
  SMN_NUM         NUMBER(7),
  GD_UVED_NUM     NUMBER(7),
  LOAD_TYPE_ID    NUMBER(2)                     DEFAULT 1,
  VETKA_OTP_ID    NUMBER(10)                    DEFAULT 10,
  MESTO_ID        NUMBER(2)                     DEFAULT 1,
  USER_ID         NUMBER(10),
  END_NALIV_DATE  DATE
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.PODACHA IS 'Ведомость подачи';

COMMENT ON COLUMN MASTER.PODACHA.ID IS 'ID ведомости подачи';

COMMENT ON COLUMN MASTER.PODACHA.POD_NUM IS 'Номер ведомости';

COMMENT ON COLUMN MASTER.PODACHA.POD_DATE IS 'Дата ведомости';

COMMENT ON COLUMN MASTER.PODACHA.KOL IS 'Кол-во вагонов';

COMMENT ON COLUMN MASTER.PODACHA.VES IS 'Вес продукта';

COMMENT ON COLUMN MASTER.PODACHA.GOTOV_DATE IS 'Дата готовности';

COMMENT ON COLUMN MASTER.PODACHA.NALIV_DATE IS 'Дата начала налива';

COMMENT ON COLUMN MASTER.PODACHA.LUKOMA_NUM IS 'Номер ЛУКОМ''а';

COMMENT ON COLUMN MASTER.PODACHA.MPS_NUM IS 'Номер МПС';

COMMENT ON COLUMN MASTER.PODACHA.SMN_NUM IS 'Номер СМН';

COMMENT ON COLUMN MASTER.PODACHA.GD_UVED_NUM IS 'Номер уведомления для ЖД';

COMMENT ON COLUMN MASTER.PODACHA.LOAD_TYPE_ID IS 'Тип транспортировки';

COMMENT ON COLUMN MASTER.PODACHA.VETKA_OTP_ID IS 'Ветка отправителя';

COMMENT ON COLUMN MASTER.PODACHA.MESTO_ID IS 'Место отгрузки';

COMMENT ON COLUMN MASTER.PODACHA.USER_ID IS 'Оператор';



