--
-- PREDPR_ROLE  (Table) 
--
CREATE TABLE MASTER.PREDPR_ROLE
(
  PREDPR_ID    NUMBER(6),
  KLS_ROLE_ID  NUMBER(2),
  FOX_KOD      NUMBER(7),
  KOD_MOSCOW   VARCHAR2(10 BYTE),
  KOD_ISU      VARCHAR2(15 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


