--
-- R3_AUART  (Table) 
--
CREATE TABLE MASTER.R3_AUART
(
  VBAK_AUART   VARCHAR2(10 BYTE)                NOT NULL,
  TVAKT_BEZEI  VARCHAR2(100 BYTE),
  NAZN_OTG_ID  NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_AUART.VBAK_AUART IS 'Вид разнарядки';

COMMENT ON COLUMN MASTER.R3_AUART.TVAKT_BEZEI IS 'Наименование';



