--
-- R3_BLOCKS  (Table) 
--
CREATE TABLE MASTER.R3_BLOCKS
(
  V_TJ30_TXT04  VARCHAR2(5 BYTE)                NOT NULL,
  NAME          VARCHAR2(100 BYTE),
  KERNEL_ID     NUMBER(18)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_BLOCKS.V_TJ30_TXT04 IS 'Признак блокировки';

COMMENT ON COLUMN MASTER.R3_BLOCKS.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.R3_BLOCKS.KERNEL_ID IS 'ID в KERNEL';



