--
-- R3_BILL_POS  (Table) 
--
CREATE TABLE MASTER.R3_BILL_POS
(
  VBELN           NUMBER(15)                    NOT NULL,
  R3_BILL_POS_ID  NUMBER(15)                    NOT NULL,
  CENA_BN         NUMBER(15,6)                  DEFAULT 0,
  CENA            NUMBER(15,6)                  DEFAULT 0,
  SUMMA_BN        NUMBER(20,6)                  DEFAULT 0,
  SUMMA_NDS       NUMBER(20,6)                  DEFAULT 0,
  SUMMA_AKCIZ     NUMBER(20,6)                  DEFAULT 0,
  SUMMA           NUMBER(20,6)                  DEFAULT 0,
  VBAP_MATNR      VARCHAR2(10 BYTE),
  VES             NUMBER(15,6)                  DEFAULT 0,
  DATE_REALIZ     DATE,
  PROD_ID_NPR     VARCHAR2(5 BYTE),
  IS_AGENT        NUMBER(1),
  NOM_DOK         NUMBER(7),
  OWNERSHIP_ID    NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_BILL_POS.VBELN IS 'Счет из R3';

COMMENT ON COLUMN MASTER.R3_BILL_POS.R3_BILL_POS_ID IS 'Позиция счета из R3';

COMMENT ON COLUMN MASTER.R3_BILL_POS.CENA_BN IS 'Цена без налогов';

COMMENT ON COLUMN MASTER.R3_BILL_POS.CENA IS 'Отпускная цена';

COMMENT ON COLUMN MASTER.R3_BILL_POS.SUMMA_BN IS 'Сумма без налогов';

COMMENT ON COLUMN MASTER.R3_BILL_POS.SUMMA_NDS IS 'НДС';

COMMENT ON COLUMN MASTER.R3_BILL_POS.SUMMA_AKCIZ IS 'Акциз';

COMMENT ON COLUMN MASTER.R3_BILL_POS.SUMMA IS 'Сумма';

COMMENT ON COLUMN MASTER.R3_BILL_POS.VBAP_MATNR IS 'Материал';



