--
-- R3_BILLS  (Table) 
--
CREATE TABLE MASTER.R3_BILLS
(
  VBELN            NUMBER(15)                   NOT NULL,
  NOM_R3           NUMBER(15),
  NOM_DOK          NUMBER(15),
  NOM_SF           NUMBER(15),
  DATE_VYP_SF      DATE,
  SUMMA_DOK        NUMBER(15,2)                 DEFAULT 0,
  SUMMA_PROD       NUMBER(15,2)                 DEFAULT 0,
  SUMMA_PROD_NDS   NUMBER(15,2)                 DEFAULT 0,
  SUMMA_AKCIZ      NUMBER(15,2)                 DEFAULT 0,
  SUMMA_TARIF      NUMBER(15,2)                 DEFAULT 0,
  SUMMA_TARIF_NDS  NUMBER(15,2)                 DEFAULT 0,
  SUMMA_VOZN       NUMBER(15,2)                 DEFAULT 0,
  SUMMA_VOZN_NDS   NUMBER(15,2)                 DEFAULT 0,
  SUMMA_STRAH      NUMBER(15,2)                 DEFAULT 0,
  VBAP_MATNR       VARCHAR2(10 BYTE),
  IS_AGENT         NUMBER(1),
  VES              NUMBER(15,6)                 DEFAULT 0
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_BILLS.VBELN IS 'Счет из R3';

COMMENT ON COLUMN MASTER.R3_BILLS.NOM_R3 IS 'N счета R3';

COMMENT ON COLUMN MASTER.R3_BILLS.NOM_DOK IS 'N счета НПО';

COMMENT ON COLUMN MASTER.R3_BILLS.NOM_SF IS 'N счета НПО';

COMMENT ON COLUMN MASTER.R3_BILLS.DATE_VYP_SF IS 'Дата счета';

COMMENT ON COLUMN MASTER.R3_BILLS.SUMMA_DOK IS 'Сумма счет-фактуры';

COMMENT ON COLUMN MASTER.R3_BILLS.SUMMA_PROD IS 'Сумма за продукт (вкл.НДС и акциз)';

COMMENT ON COLUMN MASTER.R3_BILLS.SUMMA_PROD_NDS IS 'НДС за продукт';

COMMENT ON COLUMN MASTER.R3_BILLS.SUMMA_AKCIZ IS 'Акциз';

COMMENT ON COLUMN MASTER.R3_BILLS.SUMMA_TARIF IS 'Тариф (вкл.НДС)';

COMMENT ON COLUMN MASTER.R3_BILLS.SUMMA_TARIF_NDS IS 'НДС за тариф';

COMMENT ON COLUMN MASTER.R3_BILLS.SUMMA_VOZN IS 'Вознаграждение (вкл.НДС)';

COMMENT ON COLUMN MASTER.R3_BILLS.SUMMA_VOZN_NDS IS 'НДС за вознаграждение';

COMMENT ON COLUMN MASTER.R3_BILLS.SUMMA_STRAH IS 'Страховка';

COMMENT ON COLUMN MASTER.R3_BILLS.VBAP_MATNR IS 'Материал';

COMMENT ON COLUMN MASTER.R3_BILLS.VES IS 'Вес';



