/* This object may not be sorted properly in the script due to cirular references. */
--
-- R3_CC  (Table) 
--
CREATE TABLE MASTER.R3_CC
(
  EKKO_ZZ021    VARCHAR2(30 BYTE)               NOT NULL,
  EKKO_KDATB    DATE,
  EKKO_KDATE    DATE,
  EKKO_LIFNR    VARCHAR2(10 BYTE),
  IS_AUTO_LINK  NUMBER(1)                       DEFAULT 1,
  DOG_ID        NUMBER(5),
  ZZZZ_STATUS   VARCHAR2(1 BYTE),
  ZZZZ_FILE     VARCHAR2(50 BYTE),
  ZZZZ_DATE     DATE,
  CUSTOMERS_ID  VARCHAR2(10 BYTE),
  EKKO_EBELN    VARCHAR2(20 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_CC.EKKO_ZZ021 IS 'Договор';

COMMENT ON COLUMN MASTER.R3_CC.EKKO_KDATB IS 'С даты';

COMMENT ON COLUMN MASTER.R3_CC.EKKO_KDATE IS 'По дату';

COMMENT ON COLUMN MASTER.R3_CC.EKKO_LIFNR IS 'Поставщик';

COMMENT ON COLUMN MASTER.R3_CC.IS_AUTO_LINK IS 'Автоматическая связь';

COMMENT ON COLUMN MASTER.R3_CC.ZZZZ_STATUS IS 'Статус прокачки';

COMMENT ON COLUMN MASTER.R3_CC.ZZZZ_FILE IS 'Файл';

COMMENT ON COLUMN MASTER.R3_CC.ZZZZ_DATE IS 'Дата прокачки';

COMMENT ON COLUMN MASTER.R3_CC.CUSTOMERS_ID IS 'Покупатель';



