/* This object may not be sorted properly in the script due to cirular references. */
--
-- R3_CUSTOMERS  (Table) 
--
CREATE TABLE MASTER.R3_CUSTOMERS
(
  ID                    VARCHAR2(10 BYTE)       NOT NULL,
  NAME                  VARCHAR2(110 BYTE),
  CITY                  VARCHAR2(50 BYTE),
  POST_CODE             VARCHAR2(10 BYTE),
  STREET                VARCHAR2(100 BYTE),
  HOUSE_NUM             VARCHAR2(20 BYTE),
  CITY_P                VARCHAR2(50 BYTE),
  POST_CODE_P           VARCHAR2(10 BYTE),
  ADREESS_P             VARCHAR2(100 BYTE),
  INN                   VARCHAR2(15 BYTE),
  KVERM                 VARCHAR2(30 BYTE),
  BIK                   VARCHAR2(10 BYTE),
  IS_AUTO_LINK          NUMBER(1)               DEFAULT 1,
  PREDPR_ID             NUMBER(6),
  VENDORS_ID            VARCHAR2(10 BYTE),
  ZZZZ_STATUS           VARCHAR2(1 BYTE),
  ZZZZ_FILE             VARCHAR2(50 BYTE),
  ZZZZ_DATE             DATE,
  BAHNS                 VARCHAR2(15 BYTE),
  EXIST_AKCIZ_SVED_NUM  VARCHAR2(2 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.ID IS 'Покупатель';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.CITY IS 'Город';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.POST_CODE IS 'Почтовый код';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.STREET IS 'Улица';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.HOUSE_NUM IS 'N дома';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.CITY_P IS 'Город (почтовый адрес)';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.POST_CODE_P IS 'Почтовый код (почтовый адрес)';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.ADREESS_P IS 'Почтовый адрес';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.INN IS 'ИНН';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.KVERM IS 'Договор';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.BIK IS 'БИК';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.IS_AUTO_LINK IS 'Автоматическая связь';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.VENDORS_ID IS 'Поставщик';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.ZZZZ_STATUS IS 'Статус прокачки в KERNEL';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.ZZZZ_FILE IS 'Файл';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.ZZZZ_DATE IS 'Дата прокачки';

COMMENT ON COLUMN MASTER.R3_CUSTOMERS.BAHNS IS 'ЖД код';



