/* This object may not be sorted properly in the script due to cirular references. */
--
-- R3_KVIT2SAP  (Table) 
--
CREATE TABLE MASTER.R3_KVIT2SAP
(
  ID_MS         NUMBER(10)                      NOT NULL,
  VSTEL         VARCHAR2(3 BYTE),
  ID_SAP        VARCHAR2(20 BYTE),
  ID_SAP_PSN    VARCHAR2(10 BYTE),
  BEDNR         NUMBER(10),
  VES           NUMBER(15,6)                    DEFAULT 0,
  KVIT_ID       NUMBER(10),
  VBAK_VBELN    VARCHAR2(30 BYTE),
  VBAP_POSNR    VARCHAR2(10 BYTE),
  NOM_ZD        VARCHAR2(12 BYTE),
  OPER          VARCHAR2(1 BYTE),
  LASTOPER      VARCHAR2(1 BYTE),
  SEND_OPER     NUMBER(1),
  DT_OPER       DATE,
  OF_FILE       VARCHAR2(30 BYTE),
  DT_DEL        DATE,
  SEND_DOC      NUMBER(1),
  DT_DOC        DATE,
  OF_FILE_D     VARCHAR2(30 BYTE),
  OS            VARCHAR2(1 BYTE),
  LASTOS        VARCHAR2(1 BYTE),
  SEND_OS       NUMBER(1),
  DT_OS         DATE,
  OS_FILE       VARCHAR2(30 BYTE),
  SU            VARCHAR2(1 BYTE),
  LASTSU        VARCHAR2(1 BYTE),
  SEND_SU       NUMBER(1),
  DT_SU         DATE,
  SU_FILE       VARCHAR2(30 BYTE),
  QQ            VARCHAR2(1 BYTE),
  LASTQQ        VARCHAR2(1 BYTE),
  SEND_QQ       VARCHAR2(240 BYTE),
  DT_QQ         DATE,
  QQ_FILE       VARCHAR2(30 BYTE),
  LOGFILE       VARCHAR2(30 BYTE),
  IS_EXP        NUMBER(1),
  NP            NUMBER(10),
  NUM_KVIT      NUMBER(10),
  NUM_CIST      VARCHAR2(10 BYTE),
  DATE_OTGR     DATE,
  LOAD_TYPE_ID  NUMBER(2),
  PROD_ID_NPR   VARCHAR2(5 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.ID_MS IS 'ID поставки в KERNEL';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.VSTEL IS 'ID пункта отгрузки';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.ID_SAP IS 'ID поставки в R3';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.ID_SAP_PSN IS 'ID позиции поставки в R3';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.BEDNR IS 'ID услуги в KERNEL';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.VES IS 'Вес "упавший" на позицию поставки';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.VBAK_VBELN IS 'Номер разнарядки';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.VBAP_POSNR IS 'Позиция';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.OPER IS 'Операция с поставкой (OF)';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.LASTOPER IS 'Предыдущая операция';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.SEND_OPER IS 'Признак отправки оперативной отгрузки';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.DT_OPER IS 'Дата отправки';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.OF_FILE IS 'Файл';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.DT_DEL IS 'Дата удаления';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.SEND_DOC IS 'Признак отправки документированной отгрузки';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.DT_DOC IS 'Дата отправки';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.OF_FILE_D IS 'Файл';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.OS IS 'Услуги (OS)';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.LASTOS IS 'Предыдущая операция';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.SEND_OS IS 'Признак отправки услуги';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.DT_OS IS 'Дата отправки';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.OS_FILE IS 'Файл';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.SU IS 'Провозная плата (SU)';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.LASTSU IS 'Предыдущая операция';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.SEND_SU IS 'Признак отправки провозной платы';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.DT_SU IS 'Дата отправки';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.SU_FILE IS 'Файл';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.QQ IS 'Сертификаты (QQ)';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.LASTQQ IS 'Предыдущая операция';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.SEND_QQ IS 'Признак отправки сертификата';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.DT_QQ IS 'Дата отправки';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.QQ_FILE IS 'Файл';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.LOGFILE IS 'Файл лога';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.IS_EXP IS '1 - ЭКСПОРТ';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.NP IS 'N сведения';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.NUM_KVIT IS 'N квитанции';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.NUM_CIST IS 'N тр.ср-ва';

COMMENT ON COLUMN MASTER.R3_KVIT2SAP.DATE_OTGR IS 'Дата отгрузки';



