--
-- R3_MATERIALS_GRP  (Table) 
--
CREATE TABLE MASTER.R3_MATERIALS_GRP
(
  GROUP_S  VARCHAR2(2 BYTE)                     NOT NULL,
  ATWTB    VARCHAR2(100 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_MATERIALS_GRP.GROUP_S IS 'Группа материалов';

COMMENT ON COLUMN MASTER.R3_MATERIALS_GRP.ATWTB IS 'Наименование';



