--
-- R3_MATERIALS  (Table) 
--
CREATE TABLE MASTER.R3_MATERIALS
(
  VBAP_MATNR    VARCHAR2(10 BYTE)               NOT NULL,
  MAKTX         VARCHAR2(100 BYTE),
  ATWRT_OKP     VARCHAR2(15 BYTE),
  ATWRT_TU      VARCHAR2(50 BYTE),
  ATWRT_GOST    VARCHAR2(50 BYTE),
  PROD_SIGN     VARCHAR2(2 BYTE),
  IS_AUTO_LINK  NUMBER(1)                       DEFAULT 1,
  PROD_ID_NPR   VARCHAR2(5 BYTE),
  GROUP_S       VARCHAR2(2 BYTE),
  ZZZZ_STATUS   VARCHAR2(1 BYTE),
  ZZZZ_FILE     VARCHAR2(50 BYTE),
  ZZZZ_DATE     DATE,
  BEGIN_DATE    DATE,
  END_DATE      DATE,
  ED_IZM        VARCHAR2(10 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_MATERIALS.VBAP_MATNR IS 'Материал';

COMMENT ON COLUMN MASTER.R3_MATERIALS.MAKTX IS 'Наименование';

COMMENT ON COLUMN MASTER.R3_MATERIALS.ATWRT_OKP IS 'Код ОКП';

COMMENT ON COLUMN MASTER.R3_MATERIALS.ATWRT_TU IS 'ТУ';

COMMENT ON COLUMN MASTER.R3_MATERIALS.ATWRT_GOST IS 'ГОСТ';

COMMENT ON COLUMN MASTER.R3_MATERIALS.PROD_SIGN IS 'Помоему признак  фасовки';

COMMENT ON COLUMN MASTER.R3_MATERIALS.IS_AUTO_LINK IS 'Автоматическая связь';

COMMENT ON COLUMN MASTER.R3_MATERIALS.GROUP_S IS 'Группа материалов';

COMMENT ON COLUMN MASTER.R3_MATERIALS.ZZZZ_STATUS IS 'Статус прокачки в KERNEL';

COMMENT ON COLUMN MASTER.R3_MATERIALS.ZZZZ_FILE IS 'Файл';

COMMENT ON COLUMN MASTER.R3_MATERIALS.ZZZZ_DATE IS 'Дата прокачки в KERNEL';

COMMENT ON COLUMN MASTER.R3_MATERIALS.ED_IZM IS 'Единица измерения';



