/* This object may not be sorted properly in the script due to cirular references. */
--
-- R3_OD  (Table) 
--
CREATE TABLE MASTER.R3_OD
(
  VBAK_VBELN    VARCHAR2(30 BYTE)               NOT NULL,
  VBAP_POSNR    VARCHAR2(10 BYTE)               NOT NULL,
  ZZZZ_ID       VARCHAR2(50 BYTE),
  VBAP_CHARG    VARCHAR2(20 BYTE),
  VBAP_KWMENG   NUMBER(15,6)                    DEFAULT 0,
  VBAP_VRKME    VARCHAR2(5 BYTE),
  VBAP_UEBTO    NUMBER(7,3)                     DEFAULT 0,
  VBAP_KBMENG   NUMBER(15,6)                    DEFAULT 0,
  VBAP_MATNR    VARCHAR2(10 BYTE),
  VBAP_LPRIO    NUMBER(2),
  ZZZZ_STATUS   VARCHAR2(1 BYTE),
  ZZZZ_FILE     VARCHAR2(50 BYTE),
  ZZZZ_DATE     DATE,
  V_TJ30_TXT04  VARCHAR2(5 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_OD.VBAK_VBELN IS 'Номер разнарядки';

COMMENT ON COLUMN MASTER.R3_OD.VBAP_POSNR IS 'Позиция';

COMMENT ON COLUMN MASTER.R3_OD.ZZZZ_ID IS 'Уникальный ID';

COMMENT ON COLUMN MASTER.R3_OD.VBAP_CHARG IS 'Партия';

COMMENT ON COLUMN MASTER.R3_OD.VBAP_KWMENG IS 'Заявленный объем';

COMMENT ON COLUMN MASTER.R3_OD.VBAP_VRKME IS 'Ед.изм.';

COMMENT ON COLUMN MASTER.R3_OD.VBAP_UEBTO IS '% перегруза';

COMMENT ON COLUMN MASTER.R3_OD.VBAP_KBMENG IS 'Разрешенный объем';

COMMENT ON COLUMN MASTER.R3_OD.VBAP_MATNR IS 'Материал';

COMMENT ON COLUMN MASTER.R3_OD.VBAP_LPRIO IS 'Приоритет';

COMMENT ON COLUMN MASTER.R3_OD.ZZZZ_STATUS IS 'Статус прокачки';

COMMENT ON COLUMN MASTER.R3_OD.ZZZZ_FILE IS 'Файл';

COMMENT ON COLUMN MASTER.R3_OD.ZZZZ_DATE IS 'Дата прокачки';

COMMENT ON COLUMN MASTER.R3_OD.V_TJ30_TXT04 IS 'Признак блокировки';



