/* This object may not be sorted properly in the script due to cirular references. */
--
-- R3_OA  (Table) 
--
CREATE TABLE MASTER.R3_OA
(
  ZZZZ_ID     VARCHAR2(50 BYTE)                 NOT NULL,
  VBAK_VBELN  VARCHAR2(30 BYTE),
  VBAP_POSNR  VARCHAR2(10 BYTE),
  KONV_KSCHL  VARCHAR2(10 BYTE),
  KONV_KBETR  VARCHAR2(30 BYTE),
  KONV_KRECH  VARCHAR2(1 BYTE),
  KONV_WAERS  VARCHAR2(10 BYTE),
  KONV_KPEIN  NUMBER(10),
  KONV_KMEIN  VARCHAR2(5 BYTE),
  ZZZZ_SATUS  VARCHAR2(1 BYTE),
  ZZZZ_FILE   VARCHAR2(50 BYTE),
  ZZZZ_DATE   DATE
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_OA.ZZZZ_ID IS 'Ценовое условие';

COMMENT ON COLUMN MASTER.R3_OA.VBAK_VBELN IS 'Номер разнарядки';

COMMENT ON COLUMN MASTER.R3_OA.VBAP_POSNR IS 'Позиция';

COMMENT ON COLUMN MASTER.R3_OA.KONV_KSCHL IS 'Условие разнарядки';

COMMENT ON COLUMN MASTER.R3_OA.KONV_KBETR IS 'Значение условия';

COMMENT ON COLUMN MASTER.R3_OA.KONV_KRECH IS 'Правило расчета (A-%, C-кол-во)';

COMMENT ON COLUMN MASTER.R3_OA.KONV_WAERS IS 'Валюта';

COMMENT ON COLUMN MASTER.R3_OA.KONV_KPEIN IS 'Ед-ца цены условия';

COMMENT ON COLUMN MASTER.R3_OA.KONV_KMEIN IS 'Ед.изм. условия';

COMMENT ON COLUMN MASTER.R3_OA.ZZZZ_SATUS IS 'Статус прокачки в KERNEL';

COMMENT ON COLUMN MASTER.R3_OA.ZZZZ_FILE IS 'Файл';

COMMENT ON COLUMN MASTER.R3_OA.ZZZZ_DATE IS 'Дата прокачки в KERNEL';



