--
-- R3_ROUTENODES  (Table) 
--
CREATE TABLE MASTER.R3_ROUTENODES
(
  KNOTE  VARCHAR2(10 BYTE)                      NOT NULL,
  BEZEI  VARCHAR2(100 BYTE),
  BAHNR  VARCHAR2(3 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_ROUTENODES.KNOTE IS 'Узел маршрута';

COMMENT ON COLUMN MASTER.R3_ROUTENODES.BEZEI IS 'Наименование';

COMMENT ON COLUMN MASTER.R3_ROUTENODES.BAHNR IS 'Железная дорога';



