--
-- R3_ROUTES  (Table) 
--
CREATE TABLE MASTER.R3_ROUTES
(
  ROUTE        VARCHAR2(10 BYTE)                NOT NULL,
  KNANF        VARCHAR2(10 BYTE),
  KNEND        VARCHAR2(10 BYTE),
  BEZEI        VARCHAR2(100 BYTE),
  ZZZZ_STATUS  VARCHAR2(1 BYTE),
  ZZZZ_FILE    VARCHAR2(50 BYTE),
  ZZZZ_DATE    DATE
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_ROUTES.ROUTE IS 'Маршрут';

COMMENT ON COLUMN MASTER.R3_ROUTES.KNANF IS 'Узел маршрута';

COMMENT ON COLUMN MASTER.R3_ROUTES.KNEND IS 'Узел маршрута';

COMMENT ON COLUMN MASTER.R3_ROUTES.BEZEI IS 'Наименование маршрута';

COMMENT ON COLUMN MASTER.R3_ROUTES.ZZZZ_STATUS IS 'Статус прокачки в KERNEL';

COMMENT ON COLUMN MASTER.R3_ROUTES.ZZZZ_FILE IS 'Файл';

COMMENT ON COLUMN MASTER.R3_ROUTES.ZZZZ_DATE IS 'Дата прокачки в KERNEL';



