/* This object may not be sorted properly in the script due to cirular references. */
--
-- R3_SC  (Table) 
--
CREATE TABLE MASTER.R3_SC
(
  ASNUM        VARCHAR2(10 BYTE)                NOT NULL,
  ASMDT_ASKTX  VARCHAR2(100 BYTE),
  ASMD_MEINS   VARCHAR2(10 BYTE),
  EKKO_ZZ021   VARCHAR2(30 BYTE),
  KERNEL_ID    NUMBER(18),
  KERNEL_TAG   VARCHAR2(30 BYTE),
  ZZZZ_STATUS  VARCHAR2(1 BYTE),
  ZZZZ_FILE    VARCHAR2(50 BYTE),
  ZZZZ_DATE    DATE
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_SC.ASNUM IS 'Услуга ММ_МО';

COMMENT ON COLUMN MASTER.R3_SC.ASMDT_ASKTX IS 'Наименование';

COMMENT ON COLUMN MASTER.R3_SC.ASMD_MEINS IS 'Ед.изм.';

COMMENT ON COLUMN MASTER.R3_SC.EKKO_ZZ021 IS 'Договор';

COMMENT ON COLUMN MASTER.R3_SC.KERNEL_ID IS 'ID в KERNEL';

COMMENT ON COLUMN MASTER.R3_SC.KERNEL_TAG IS 'TAG в KERNEL';

COMMENT ON COLUMN MASTER.R3_SC.ZZZZ_STATUS IS 'Статус прокачки в KERNEL';

COMMENT ON COLUMN MASTER.R3_SC.ZZZZ_FILE IS 'Файл';

COMMENT ON COLUMN MASTER.R3_SC.ZZZZ_DATE IS 'Дата прокачки в KERNEL';



