--
-- R3_TRATY  (Table) 
--
CREATE TABLE MASTER.R3_TRATY
(
  VBKD_TRATY    VARCHAR2(5 BYTE)                NOT NULL,
  NAME          VARCHAR2(100 BYTE),
  KERNEL_ID     NUMBER(18),
  FOX_ID        NUMBER(10),
  LOAD_TYPE_ID  NUMBER(10),
  LOAD_ABBR     VARCHAR2(3 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_TRATY.VBKD_TRATY IS 'Род вагона';

COMMENT ON COLUMN MASTER.R3_TRATY.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.R3_TRATY.KERNEL_ID IS 'ID в KERNEL';

COMMENT ON COLUMN MASTER.R3_TRATY.FOX_ID IS 'ID в MASTER';



