/* This object may not be sorted properly in the script due to cirular references. */
--
-- R3_VENDORS  (Table) 
--
CREATE TABLE MASTER.R3_VENDORS
(
  ID            VARCHAR2(10 BYTE)               NOT NULL,
  NAME          VARCHAR2(100 BYTE),
  CITY          VARCHAR2(50 BYTE),
  POST_CODE     VARCHAR2(10 BYTE),
  STREET        VARCHAR2(100 BYTE),
  HOUSE_NUM     VARCHAR2(20 BYTE),
  INN           VARCHAR2(20 BYTE),
  IS_AUTO_LINK  NUMBER(1)                       DEFAULT 1,
  PREDPR_ID     NUMBER(6),
  CUSTOMERS_ID  VARCHAR2(10 BYTE),
  ZZZZ_STATUS   VARCHAR2(1 BYTE),
  ZZZZ_FILE     VARCHAR2(50 BYTE),
  ZZZZ_DATE     DATE
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_VENDORS.ID IS 'Поставщик';

COMMENT ON COLUMN MASTER.R3_VENDORS.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.R3_VENDORS.CITY IS 'Город';

COMMENT ON COLUMN MASTER.R3_VENDORS.POST_CODE IS 'Почтовый код';

COMMENT ON COLUMN MASTER.R3_VENDORS.STREET IS 'Улица';

COMMENT ON COLUMN MASTER.R3_VENDORS.HOUSE_NUM IS 'N дома';

COMMENT ON COLUMN MASTER.R3_VENDORS.INN IS 'ИНН';

COMMENT ON COLUMN MASTER.R3_VENDORS.IS_AUTO_LINK IS 'Автоматическая связь';

COMMENT ON COLUMN MASTER.R3_VENDORS.CUSTOMERS_ID IS 'Покупатель';

COMMENT ON COLUMN MASTER.R3_VENDORS.ZZZZ_STATUS IS 'Статус прокачки в KERNEL';

COMMENT ON COLUMN MASTER.R3_VENDORS.ZZZZ_FILE IS 'Файл';

COMMENT ON COLUMN MASTER.R3_VENDORS.ZZZZ_DATE IS 'Дата прокачки в KERNEL';



