--
-- R3_VSTEL  (Table) 
--
CREATE TABLE MASTER.R3_VSTEL
(
  VBAP_VSTEL  VARCHAR2(3 BYTE)                  NOT NULL,
  VTEXT       VARCHAR2(100 BYTE),
  KERNEL_ID   NUMBER(18),
  FOX_ID      NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_VSTEL.VBAP_VSTEL IS 'ID пункта отгрузки';

COMMENT ON COLUMN MASTER.R3_VSTEL.VTEXT IS 'Наименование пункта отгрузки';

COMMENT ON COLUMN MASTER.R3_VSTEL.KERNEL_ID IS 'ID в KERNEL';

COMMENT ON COLUMN MASTER.R3_VSTEL.FOX_ID IS 'ID в MASTER';



