/* This object may not be sorted properly in the script due to cirular references. */
--
-- R3_VBAK  (Table) 
--
CREATE TABLE MASTER.R3_VBAK
(
  VBELN            VARCHAR2(30 BYTE)            NOT NULL,
  VBAK_VKORG       CHAR(3 BYTE),
  VBAK_VTWEG       VARCHAR2(3 BYTE),
  VBAP_VSTEL       VARCHAR2(3 BYTE),
  VBAK_ZZ021       VARCHAR2(30 BYTE),
  VBAK_AUART       VARCHAR2(10 BYTE),
  VBAK_VDATU       DATE,
  VBAK_VSBED       VARCHAR2(3 BYTE),
  VBAP_ROUTE       VARCHAR2(10 BYTE),
  VBAP_WERKS       VARCHAR2(3 BYTE),
  LGORT            VARCHAR2(5 BYTE),
  NP_OWNER         VARCHAR2(10 BYTE),
  NP_PRODR         VARCHAR2(10 BYTE),
  MVRG1            VARCHAR2(4 BYTE),
  TEXT3_Y003       VARCHAR2(100 BYTE),
  NPR_NAME         VARCHAR2(100 BYTE),
  TARIF_CODE       VARCHAR2(10 BYTE),
  TRANSP_NUM       VARCHAR2(20 BYTE),
  CONTRACTOR_ATTR  NUMBER(2),
  GAR_Y007         VARCHAR2(10 BYTE),
  MPS_Y006         VARCHAR2(10 BYTE),
  IS_AUTO_LINK     NUMBER(1)                    DEFAULT 1,
  VBKD_BSTKD       VARCHAR2(20 BYTE),
  OT_LIFNR         VARCHAR2(10 BYTE),
  SH_KUNNR         VARCHAR2(10 BYTE),
  VBPA_KUNNR       VARCHAR2(10 BYTE),
  PO_KNA1_NAME1    VARCHAR2(100 BYTE),
  VBPA_KUNNR_SP    VARCHAR2(10 BYTE),
  ZZZZ_STATUS      VARCHAR2(1 BYTE),
  ZZZZ_FILE        VARCHAR2(50 BYTE),
  ZZZZ_DATE        DATE,
  NOM_ZD           VARCHAR2(12 BYTE),
  VBKD_TRATY       VARCHAR2(5 BYTE),
  VBKD_VSART       VARCHAR2(3 BYTE),
  TEXT1_Y005       VARCHAR2(100 BYTE),
  V_TJ30_TXT04     VARCHAR2(5 BYTE),
  VBAP_MATNR       VARCHAR2(10 BYTE),
  VBAP_KBMENG      NUMBER(15,6)                 DEFAULT 0,
  VBAP_KWMENG      NUMBER(15,6)                 DEFAULT 0,
  VBAP_OICONTNR    VARCHAR2(10 BYTE),
  VEDA_VBEGDAT     DATE,
  VBKD_BSTDK       DATE,
  TVAKT_BEZEI      VARCHAR2(20 BYTE),
  VBAP_LPRIO       VARCHAR2(2 BYTE),
  VBAP_POSNR       VARCHAR2(6 BYTE),
  VBAP_VRKME       VARCHAR2(3 BYTE),
  INCO1            VARCHAR2(3 BYTE),
  INCO2            VARCHAR2(30 BYTE),
  ZLSCH            VARCHAR2(1 BYTE),
  STCEG_L          VARCHAR2(3 BYTE),
  ZTERM            VARCHAR2(4 BYTE),
  VBPA_LIFNR_SP    VARCHAR2(10 BYTE),
  VBAK_STCEG_L     VARCHAR2(3 BYTE),
  SPART            VARCHAR2(2 BYTE),
  MONTH_REESTR_ID  NUMBER(10),
  VBELN_POS        VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_VBAK.VBELN IS 'Номер разнарядки';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAK_VKORG IS 'Сбытовая организация (01-КЦ)';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAK_VTWEG IS 'Канал сбыта (01-экспорт, 02-внутренний рынок)';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAP_VSTEL IS 'ID пункта отгрузки';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAK_ZZ021 IS 'Договор';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAK_AUART IS 'Вид разнарядки';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAK_VDATU IS 'Дата разнарядки';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAK_VSBED IS 'Вид транспортировки';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAP_ROUTE IS 'Маршрут';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAP_WERKS IS 'Завод';

COMMENT ON COLUMN MASTER.R3_VBAK.LGORT IS 'Склад';

COMMENT ON COLUMN MASTER.R3_VBAK.NP_OWNER IS 'Поставщик';

COMMENT ON COLUMN MASTER.R3_VBAK.NP_PRODR IS 'Поставщик';

COMMENT ON COLUMN MASTER.R3_VBAK.MVRG1 IS 'Отгрузка 8-осными';

COMMENT ON COLUMN MASTER.R3_VBAK.TEXT3_Y003 IS 'Графа 4';

COMMENT ON COLUMN MASTER.R3_VBAK.NPR_NAME IS 'Ветка получателя';

COMMENT ON COLUMN MASTER.R3_VBAK.TARIF_CODE IS 'Код искл. тарифа';

COMMENT ON COLUMN MASTER.R3_VBAK.TRANSP_NUM IS 'N транспорта';

COMMENT ON COLUMN MASTER.R3_VBAK.CONTRACTOR_ATTR IS 'Признак договора';

COMMENT ON COLUMN MASTER.R3_VBAK.GAR_Y007 IS 'Оплата по ф.2';

COMMENT ON COLUMN MASTER.R3_VBAK.MPS_Y006 IS 'ЖД код получателя';

COMMENT ON COLUMN MASTER.R3_VBAK.IS_AUTO_LINK IS 'Автоматическая связь';

COMMENT ON COLUMN MASTER.R3_VBAK.VBKD_BSTKD IS 'N разнарядки НПО из R3';

COMMENT ON COLUMN MASTER.R3_VBAK.OT_LIFNR IS 'Поставщик';

COMMENT ON COLUMN MASTER.R3_VBAK.SH_KUNNR IS 'Покупатель';

COMMENT ON COLUMN MASTER.R3_VBAK.VBPA_KUNNR IS 'Покупатель';

COMMENT ON COLUMN MASTER.R3_VBAK.PO_KNA1_NAME1 IS 'Потребитель';

COMMENT ON COLUMN MASTER.R3_VBAK.VBPA_KUNNR_SP IS 'Покупатель';

COMMENT ON COLUMN MASTER.R3_VBAK.ZZZZ_STATUS IS 'Статус прокачки';

COMMENT ON COLUMN MASTER.R3_VBAK.ZZZZ_FILE IS 'Файл';

COMMENT ON COLUMN MASTER.R3_VBAK.ZZZZ_DATE IS 'Дата прокачки';

COMMENT ON COLUMN MASTER.R3_VBAK.VBKD_TRATY IS 'Род вагона';

COMMENT ON COLUMN MASTER.R3_VBAK.VBKD_VSART IS 'Собственник вагона';

COMMENT ON COLUMN MASTER.R3_VBAK.TEXT1_Y005 IS 'Примечание';

COMMENT ON COLUMN MASTER.R3_VBAK.V_TJ30_TXT04 IS 'Признак блокировки';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAP_MATNR IS 'Материал';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAP_KBMENG IS 'Разрешенный объем (без учета блокированных позиций)';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAP_KWMENG IS 'Заявленный объем (без учета блокированных позиций)';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAP_OICONTNR IS 'Код договорного документа';

COMMENT ON COLUMN MASTER.R3_VBAK.VEDA_VBEGDAT IS 'Дата начала действия договора';

COMMENT ON COLUMN MASTER.R3_VBAK.TVAKT_BEZEI IS 'Название вида разнарядки';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAP_LPRIO IS 'Приоритет поставки(00-Отгр. по указ-ю рук.,01-Отгр. в 1-ю очередь,02-Отгр. обязательно,03-Отгр. по возможности)';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAP_POSNR IS '№ позиции разнарядки';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAP_VRKME IS 'Единица измерения';

COMMENT ON COLUMN MASTER.R3_VBAK.INCO1 IS 'Инкотермс. Часть 1.';

COMMENT ON COLUMN MASTER.R3_VBAK.INCO2 IS 'Инкотермс. Часть 2.';

COMMENT ON COLUMN MASTER.R3_VBAK.ZLSCH IS 'Способ платежа.';

COMMENT ON COLUMN MASTER.R3_VBAK.STCEG_L IS 'Страна назначения.';

COMMENT ON COLUMN MASTER.R3_VBAK.ZTERM IS 'Условия платежа.';

COMMENT ON COLUMN MASTER.R3_VBAK.VBPA_LIFNR_SP IS 'Код экспедитора';

COMMENT ON COLUMN MASTER.R3_VBAK.VBAK_STCEG_L IS 'Страна назначения.';

COMMENT ON COLUMN MASTER.R3_VBAK.SPART IS 'Сектор сбыта(10 - нефть,20– нефтепродукты 30 – газ 40 – продукты г.п. 45- нефтехимия 50- прочие ТМЦ)';

COMMENT ON COLUMN MASTER.R3_VBAK.MONTH_REESTR_ID IS 'ID реестра';

COMMENT ON COLUMN MASTER.R3_VBAK.VBELN_POS IS 'Позиция разнарядки';



