--
-- R3_VSBED  (Table) 
--
CREATE TABLE MASTER.R3_VSBED
(
  VBAK_VSBED  VARCHAR2(3 BYTE)                  NOT NULL,
  NAME        VARCHAR2(100 BYTE),
  KERNEL_ID   NUMBER(18),
  FOX_ID      NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.R3_VSBED.VBAK_VSBED IS 'Вид транспортировки';

COMMENT ON COLUMN MASTER.R3_VSBED.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.R3_VSBED.KERNEL_ID IS 'ID в KERNEL';

COMMENT ON COLUMN MASTER.R3_VSBED.FOX_ID IS 'ID в MASTER';



