--
-- REESTR_IN  (Table) 
--
CREATE TABLE MASTER.REESTR_IN
(
  ID              NUMBER(10)                    NOT NULL,
  SVED_IN_ID      VARCHAR2(9 BYTE),
  MESTO_ID        NUMBER(2),
  TEX_PD_ID       NUMBER(10),
  GROTP_ID        NUMBER(10),
  STAN_OTP_ID     NUMBER(10),
  FORMNAKL_ID     NUMBER(2),
  NUM_KVIT        NUMBER(10),
  DATE_KVIT       DATE,
  PASP_NUM_KVIT   VARCHAR2(15 BYTE),
  REZ_NUM_KVIT    VARCHAR2(15 BYTE),
  PASP_DATE_KVIT  DATE,
  VZLIV_KVIT      NUMBER(6),
  TEMPER_KVIT     NUMBER(5,1),
  PL_KVIT         NUMBER(6,4),
  VES_KVIT        NUMBER(10,3),
  TARIF           NUMBER(12,2),
  TARIF_GUARD     NUMBER(12,2),
  DATE_IN_STAN    DATE,
  DATE_OTGR       DATE,
  NUM_CIST        VARCHAR2(10 BYTE),
  VAGONTYPE_ID    NUMBER(2),
  KALIBR_ID       VARCHAR2(5 BYTE),
  VES_CIST        NUMBER(10,3),
  VAGOWNER_ID     NUMBER(3),
  CAPACITY        VARCHAR2(10 BYTE),
  PLOMBA1         VARCHAR2(15 BYTE),
  PLOMBA2         VARCHAR2(15 BYTE),
  VZLIV           NUMBER(6),
  TEMPER          NUMBER(5,1),
  FAKT_PL         NUMBER(6,4),
  VES             NUMBER(14,7),
  VES_NETTO       NUMBER(14,7),
  DATE_VOZ        DATE,
  KVIT_VOZ        VARCHAR2(12 BYTE),
  SUM_VOZ         NUMBER(12,2),
  STAN_VOZ_ID     NUMBER(10),
  SVED_POS        NUMBER(5),
  EMPTY_VOZ       NUMBER(1)                     DEFAULT 1,
  VOLUME          NUMBER(10),
  VOLUME15        NUMBER(11,4),
  CTLV            NUMBER(6,4),
  GOST_ID         NUMBER(3)                     DEFAULT 0,
  ZPU_TYPE1       NUMBER(10),
  ZPU_TYPE2       NUMBER(10),
  BAD_NUM         NUMBER(1)                     DEFAULT 0,
  NAKL_ID         NUMBER(10),
  NAKL_POS        NUMBER(5),
  OSTAT           NUMBER(6),
  UVED_ID         NUMBER(7),
  UVED_POS        NUMBER(3),
  P_VOD_KVIT      NUMBER(7,4),
  P_DIRT_KVIT     NUMBER(7,4),
  P_SOL_KVIT      NUMBER(7,4),
  VES_NETTO_KVIT  NUMBER(14,3),
  NUM_KVIT_TXT    VARCHAR2(15 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REESTR_IN IS 'Разгруженные вагоны';

COMMENT ON COLUMN MASTER.REESTR_IN.ID IS 'Отгрузка';

COMMENT ON COLUMN MASTER.REESTR_IN.SVED_IN_ID IS 'Сведение';

COMMENT ON COLUMN MASTER.REESTR_IN.MESTO_ID IS 'Место отгрузки';

COMMENT ON COLUMN MASTER.REESTR_IN.TEX_PD_ID IS 'ТЕХ ПД';

COMMENT ON COLUMN MASTER.REESTR_IN.GROTP_ID IS 'Грузоотправитель';

COMMENT ON COLUMN MASTER.REESTR_IN.STAN_OTP_ID IS 'Станция отправления';

COMMENT ON COLUMN MASTER.REESTR_IN.FORMNAKL_ID IS 'Форма накладной';

COMMENT ON COLUMN MASTER.REESTR_IN.NUM_KVIT IS 'N квитанции или накладной';

COMMENT ON COLUMN MASTER.REESTR_IN.DATE_KVIT IS 'Дата квитанции или накладной';

COMMENT ON COLUMN MASTER.REESTR_IN.PASP_NUM_KVIT IS '№ паспорта с накладной';

COMMENT ON COLUMN MASTER.REESTR_IN.REZ_NUM_KVIT IS '№ резервуара с накладной';

COMMENT ON COLUMN MASTER.REESTR_IN.PASP_DATE_KVIT IS 'Дата паспорта с накладной';

COMMENT ON COLUMN MASTER.REESTR_IN.VZLIV_KVIT IS 'Взлив из накладной';

COMMENT ON COLUMN MASTER.REESTR_IN.TEMPER_KVIT IS 'Температура из накладной';

COMMENT ON COLUMN MASTER.REESTR_IN.PL_KVIT IS 'Плотность из паспорта при накладной';

COMMENT ON COLUMN MASTER.REESTR_IN.VES_KVIT IS 'Вес из накладной';

COMMENT ON COLUMN MASTER.REESTR_IN.TARIF IS 'Тариф';

COMMENT ON COLUMN MASTER.REESTR_IN.TARIF_GUARD IS 'Плата за охрану';

COMMENT ON COLUMN MASTER.REESTR_IN.DATE_IN_STAN IS 'Дата прихода на станцию';

COMMENT ON COLUMN MASTER.REESTR_IN.DATE_OTGR IS 'Дата сведения';

COMMENT ON COLUMN MASTER.REESTR_IN.NUM_CIST IS 'Номер транспортного ср-ва';

COMMENT ON COLUMN MASTER.REESTR_IN.VAGONTYPE_ID IS 'Род вагона (ЦС,КР и т.п.)';

COMMENT ON COLUMN MASTER.REESTR_IN.KALIBR_ID IS 'Тип вагона (номер)';

COMMENT ON COLUMN MASTER.REESTR_IN.VES_CIST IS 'Вес вагона';

COMMENT ON COLUMN MASTER.REESTR_IN.VAGOWNER_ID IS 'Собственник тр.ср-ва';

COMMENT ON COLUMN MASTER.REESTR_IN.CAPACITY IS 'Грузоподъемность';

COMMENT ON COLUMN MASTER.REESTR_IN.PLOMBA1 IS 'Пломба 1';

COMMENT ON COLUMN MASTER.REESTR_IN.PLOMBA2 IS 'Пломба 2';

COMMENT ON COLUMN MASTER.REESTR_IN.VZLIV IS 'Взлив или объем';

COMMENT ON COLUMN MASTER.REESTR_IN.TEMPER IS 'Температура';

COMMENT ON COLUMN MASTER.REESTR_IN.FAKT_PL IS 'Факт.плотность';

COMMENT ON COLUMN MASTER.REESTR_IN.VES IS 'Вес груза';

COMMENT ON COLUMN MASTER.REESTR_IN.VES_NETTO IS 'Вес НЕТТО (для нефти)';

COMMENT ON COLUMN MASTER.REESTR_IN.DATE_VOZ IS 'Дата возврата';

COMMENT ON COLUMN MASTER.REESTR_IN.KVIT_VOZ IS 'Квитанция на возврат';

COMMENT ON COLUMN MASTER.REESTR_IN.SUM_VOZ IS 'Сумма тарифа за возврат';

COMMENT ON COLUMN MASTER.REESTR_IN.STAN_VOZ_ID IS 'Станция возврата';

COMMENT ON COLUMN MASTER.REESTR_IN.SVED_POS IS '№ по порядку';

COMMENT ON COLUMN MASTER.REESTR_IN.EMPTY_VOZ IS 'Признак возврата порожним';

COMMENT ON COLUMN MASTER.REESTR_IN.VOLUME IS 'Объем';

COMMENT ON COLUMN MASTER.REESTR_IN.VOLUME15 IS 'Объем при 15''C';

COMMENT ON COLUMN MASTER.REESTR_IN.CTLV IS 'Коэф.корр.объема';

COMMENT ON COLUMN MASTER.REESTR_IN.GOST_ID IS 'ГОСТ';

COMMENT ON COLUMN MASTER.REESTR_IN.ZPU_TYPE1 IS 'Тип пломбы 1';

COMMENT ON COLUMN MASTER.REESTR_IN.ZPU_TYPE2 IS 'Тип пломбы 2';

COMMENT ON COLUMN MASTER.REESTR_IN.BAD_NUM IS '1-Неверный номер';

COMMENT ON COLUMN MASTER.REESTR_IN.OSTAT IS 'Остаток, см';

COMMENT ON COLUMN MASTER.REESTR_IN.UVED_ID IS 'Уведомление';

COMMENT ON COLUMN MASTER.REESTR_IN.UVED_POS IS 'Позиция в уведомлении';

COMMENT ON COLUMN MASTER.REESTR_IN.NUM_KVIT_TXT IS '№ ж/д накладной';



