--
-- REESTR_TEMP  (Table) 
--
CREATE TABLE MASTER.REESTR_TEMP
(
  SSTAN           VARCHAR2(6 BYTE),
  SNUM_PER        VARCHAR2(4 BYTE),
  DDAT_PER        DATE,
  SNUM_KVIT       VARCHAR2(8 BYTE),
  DDATE_KVIT      DATE,
  NSUMMA          NUMBER(12,2),
  NNDS            NUMBER(12,2),
  REESTR_TEMP_ID  NUMBER
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.REESTR_TEMP.SSTAN IS 'Код станции';

COMMENT ON COLUMN MASTER.REESTR_TEMP.SNUM_PER IS 'номер перечня';

COMMENT ON COLUMN MASTER.REESTR_TEMP.DDAT_PER IS 'дата перечня';

COMMENT ON COLUMN MASTER.REESTR_TEMP.SNUM_KVIT IS '№ квитанции';

COMMENT ON COLUMN MASTER.REESTR_TEMP.DDATE_KVIT IS 'дата квитанции';

COMMENT ON COLUMN MASTER.REESTR_TEMP.NSUMMA IS 'сумма';

COMMENT ON COLUMN MASTER.REESTR_TEMP.NNDS IS 'ндс';

COMMENT ON COLUMN MASTER.REESTR_TEMP.REESTR_TEMP_ID IS 'PK';



