--
-- REESTR_RAIL_RGD_SF  (Table) 
--
CREATE TABLE MASTER.REESTR_RAIL_RGD_SF
(
  NOM_SCH                VARCHAR2(10 BYTE),
  DATE_SCH               DATE,
  NOM_PERECH             VARCHAR2(10 BYTE),
  DAT_PERECH             DATE,
  R21                    NUMBER,
  KST                    NUMBER,
  REESTR_RAIL_RGD_SF_ID  NUMBER
)
TABLESPACE USERS2
NOCOMPRESS ;


