--
-- REESTR  (Table) 
--
CREATE TABLE MASTER.REESTR
(
  ID              NUMBER(10)                    NOT NULL,
  SVED_ID         VARCHAR2(9 BYTE),
  SVED_POS        NUMBER(5),
  VED_POD_ROW_ID  NUMBER(10),
  NUM_CIST        VARCHAR2(10 BYTE),
  NCISTDOP        NUMBER(2),
  AXES            NUMBER(2),
  CAPACITY        VARCHAR2(10 BYTE),
  WES1            VARCHAR2(5 BYTE),
  VES_CIST        NUMBER(10,3),
  VAGONTYPE_ID    NUMBER(10),
  KALIBR_ID       VARCHAR2(5 BYTE),
  TIP1            VARCHAR2(5 BYTE),
  VAGOWNER_ID     NUMBER(10),
  VETKA_POD_ID    NUMBER(10),
  VETKA_OTP_ID    NUMBER(10),
  VETKA_NAPR_ID   NUMBER(10),
  VAG_STATUS_ID   NUMBER(10)                    DEFAULT 0,
  VZLIV           NUMBER(10),
  TEMPER          NUMBER(6,1),
  FAKT_PL         NUMBER(6,4),
  VES             NUMBER(10,3)                  DEFAULT 0,
  KOL_NET         NUMBER(12,5)                  DEFAULT 0,
  VES_ALL         NUMBER(10,3)                  DEFAULT 0,
  VES_ED          NUMBER(10,3)                  DEFAULT 0,
  KOL_ED          NUMBER(6)                     DEFAULT 0,
  UPAK_ID         NUMBER(10),
  UPAK_VES        NUMBER(10,3)                  DEFAULT 0,
  UPAK_VES_ED     NUMBER(10,3)                  DEFAULT 0,
  PODDONS         NUMBER(3)                     DEFAULT 0,
  PODDON_VES      NUMBER(10,3)                  DEFAULT 0,
  SHIELDS         NUMBER(3)                     DEFAULT 0,
  SHIELD_VES      NUMBER(10,3)                  DEFAULT 0,
  ZPU_TYPE1       NUMBER(10),
  ZPU_TYPE2       NUMBER(10),
  PLOMBA1         VARCHAR2(15 BYTE),
  PLOMBA2         VARCHAR2(15 BYTE),
  ROSINSPL1       VARCHAR2(6 BYTE),
  ROSINSPL2       VARCHAR2(6 BYTE),
  NAR_LINE_ID     NUMBER(10),
  NUM_PROP        NUMBER(5),
  FIO_DRIVER      VARCHAR2(50 BYTE),
  NAKL_ID         NUMBER(10),
  FORMNAKL_ID     NUMBER(10),
  NUM_KVIT        VARCHAR2(10 BYTE),
  DATE_KVIT       DATE,
  TARIF           NUMBER(12,2)                  DEFAULT 0,
  TARIF_GUARD     NUMBER(12,2)                  DEFAULT 0,
  VOLUME          NUMBER(10)                    DEFAULT 0,
  BAD_NUM         NUMBER(1)                     DEFAULT 0,
  GOST_ID         NUMBER(2)                     DEFAULT 0,
  CTLV            NUMBER(6,4)                   DEFAULT 0,
  VOLUME15        NUMBER(8)                     DEFAULT 0,
  NAKL_POS        NUMBER(5),
  UVED_ID         NUMBER(10),
  UVED_POS        NUMBER(5),
  IS_AUTO         NUMBER(1)                     DEFAULT 1
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REESTR IS 'Отгрузки';

COMMENT ON COLUMN MASTER.REESTR.ID IS 'Отгрузка';

COMMENT ON COLUMN MASTER.REESTR.SVED_ID IS 'ID Сведения';

COMMENT ON COLUMN MASTER.REESTR.SVED_POS IS '№ п/п';

COMMENT ON COLUMN MASTER.REESTR.VED_POD_ROW_ID IS 'ID позиции ведомости подачи';

COMMENT ON COLUMN MASTER.REESTR.NUM_CIST IS 'Номер транспортного ср-ва';

COMMENT ON COLUMN MASTER.REESTR.NCISTDOP IS 'Признак отгрузки СНГ';

COMMENT ON COLUMN MASTER.REESTR.AXES IS 'Оси';

COMMENT ON COLUMN MASTER.REESTR.CAPACITY IS 'Грузоподъемность';

COMMENT ON COLUMN MASTER.REESTR.WES1 IS '?';

COMMENT ON COLUMN MASTER.REESTR.VES_CIST IS 'Вес вагона';

COMMENT ON COLUMN MASTER.REESTR.VAGONTYPE_ID IS 'Род вагона (ЦС,КР и т.п.)';

COMMENT ON COLUMN MASTER.REESTR.KALIBR_ID IS 'Тип вагона (номер)';

COMMENT ON COLUMN MASTER.REESTR.TIP1 IS '?';

COMMENT ON COLUMN MASTER.REESTR.VAGOWNER_ID IS 'Собственник тр.ср-ва';

COMMENT ON COLUMN MASTER.REESTR.VETKA_POD_ID IS 'Откуда подан';

COMMENT ON COLUMN MASTER.REESTR.VETKA_OTP_ID IS 'Путь погрузки';

COMMENT ON COLUMN MASTER.REESTR.VETKA_NAPR_ID IS 'Направление вывода';

COMMENT ON COLUMN MASTER.REESTR.VAG_STATUS_ID IS 'Статус вагона';

COMMENT ON COLUMN MASTER.REESTR.VZLIV IS 'Взлив';

COMMENT ON COLUMN MASTER.REESTR.TEMPER IS 'Температура';

COMMENT ON COLUMN MASTER.REESTR.FAKT_PL IS 'Факт.плотность';

COMMENT ON COLUMN MASTER.REESTR.VES IS 'Вес груза';

COMMENT ON COLUMN MASTER.REESTR.KOL_NET IS 'Вес НЕТТО (для нефти)';

COMMENT ON COLUMN MASTER.REESTR.VES_ALL IS 'Вес вагона, груза, упаковки';

COMMENT ON COLUMN MASTER.REESTR.VES_ED IS 'Вес ед.груза';

COMMENT ON COLUMN MASTER.REESTR.KOL_ED IS 'Кол-во ед-ц';

COMMENT ON COLUMN MASTER.REESTR.UPAK_ID IS 'Вид упаковки';

COMMENT ON COLUMN MASTER.REESTR.UPAK_VES IS 'Вес упаковки';

COMMENT ON COLUMN MASTER.REESTR.UPAK_VES_ED IS 'Вес (КГ) пустой упаковки 1 ед-цы товара';

COMMENT ON COLUMN MASTER.REESTR.PODDONS IS 'Кол-во поддонов';

COMMENT ON COLUMN MASTER.REESTR.PODDON_VES IS 'Вес (КГ) 1 поддона';

COMMENT ON COLUMN MASTER.REESTR.SHIELDS IS 'Кол-во щитов';

COMMENT ON COLUMN MASTER.REESTR.SHIELD_VES IS 'Вес (КГ) 1 щита';

COMMENT ON COLUMN MASTER.REESTR.ZPU_TYPE1 IS 'Тип пломбы 1';

COMMENT ON COLUMN MASTER.REESTR.ZPU_TYPE2 IS 'Тип пломбы 2';

COMMENT ON COLUMN MASTER.REESTR.PLOMBA1 IS 'Пломба 1';

COMMENT ON COLUMN MASTER.REESTR.PLOMBA2 IS 'Пломба 2';

COMMENT ON COLUMN MASTER.REESTR.ROSINSPL1 IS 'Пломба Росинспектората 1';

COMMENT ON COLUMN MASTER.REESTR.ROSINSPL2 IS 'Пломба Росинспектората 2';

COMMENT ON COLUMN MASTER.REESTR.NAR_LINE_ID IS 'ID позиции наряда/разрешения';

COMMENT ON COLUMN MASTER.REESTR.NUM_PROP IS '№ пропуска';

COMMENT ON COLUMN MASTER.REESTR.FIO_DRIVER IS 'ФИО водителя';

COMMENT ON COLUMN MASTER.REESTR.NAKL_ID IS 'ID накладной';

COMMENT ON COLUMN MASTER.REESTR.FORMNAKL_ID IS 'Форма накладной';

COMMENT ON COLUMN MASTER.REESTR.NUM_KVIT IS 'N квитанции';

COMMENT ON COLUMN MASTER.REESTR.DATE_KVIT IS 'Дата квитанции';

COMMENT ON COLUMN MASTER.REESTR.TARIF IS 'Тариф';

COMMENT ON COLUMN MASTER.REESTR.TARIF_GUARD IS 'Плата за охрану';

COMMENT ON COLUMN MASTER.REESTR.VOLUME IS 'Объем';

COMMENT ON COLUMN MASTER.REESTR.BAD_NUM IS '1-Неверный номер вагона';

COMMENT ON COLUMN MASTER.REESTR.GOST_ID IS 'ГОСТ расчета веса';

COMMENT ON COLUMN MASTER.REESTR.CTLV IS 'Коэффициент коррекции объема';

COMMENT ON COLUMN MASTER.REESTR.VOLUME15 IS 'Объем при 15''C';

COMMENT ON COLUMN MASTER.REESTR.NAKL_POS IS '№ п/п в накладной';

COMMENT ON COLUMN MASTER.REESTR.UVED_ID IS 'Уведомление об уборке';

COMMENT ON COLUMN MASTER.REESTR.UVED_POS IS '№ п/п в уведомлении об уборке';

COMMENT ON COLUMN MASTER.REESTR.IS_AUTO IS '1-Вес рассчитан автоматически';



