--
-- REPL_DSN_TYPES  (Table) 
--
CREATE TABLE MASTER.REPL_DSN_TYPES
(
  ID          VARCHAR2(15 BYTE)                 NOT NULL,
  NAME        VARCHAR2(30 BYTE),
  DESCRIPT    VARCHAR2(200 BYTE),
  CHECK_FILE  NUMBER(1)                         DEFAULT 0
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPL_DSN_TYPES IS 'Типы источников данных';

COMMENT ON COLUMN MASTER.REPL_DSN_TYPES.ID IS 'Тип источника';

COMMENT ON COLUMN MASTER.REPL_DSN_TYPES.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.REPL_DSN_TYPES.DESCRIPT IS 'Описание';

COMMENT ON COLUMN MASTER.REPL_DSN_TYPES.CHECK_FILE IS 'Проверять на изменение файла';



