--
-- REPL_FILE_KINDS  (Table) 
--
CREATE TABLE MASTER.REPL_FILE_KINDS
(
  ID    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(50 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPL_FILE_KINDS IS 'Виды транспортных файлов';

COMMENT ON COLUMN MASTER.REPL_FILE_KINDS.ID IS 'Вид транспортного файла';

COMMENT ON COLUMN MASTER.REPL_FILE_KINDS.NAME IS 'Наименование';



