--
-- REPL_CONFIG  (Table) 
--
CREATE TABLE MASTER.REPL_CONFIG
(
  REPL_SITE           NUMBER(10)                NOT NULL,
  REPL_AUTO_OSUSER    VARCHAR2(30 BYTE),
  REPL_AUTO_TERMINAL  VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPL_CONFIG IS 'Конфигурация текущего узла';

COMMENT ON COLUMN MASTER.REPL_CONFIG.REPL_SITE IS 'Текущий узел';

COMMENT ON COLUMN MASTER.REPL_CONFIG.REPL_AUTO_OSUSER IS ' Пользователь, под которым запускается репликация (автомат)';

COMMENT ON COLUMN MASTER.REPL_CONFIG.REPL_AUTO_TERMINAL IS 'Терминал, под которым запускается репликация (автомат)';



