--
-- REPL_SITE_TYPES  (Table) 
--
CREATE TABLE MASTER.REPL_SITE_TYPES
(
  ID    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(50 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPL_SITE_TYPES IS 'Типы узлов репликации';

COMMENT ON COLUMN MASTER.REPL_SITE_TYPES.ID IS 'Тип узла репликации';

COMMENT ON COLUMN MASTER.REPL_SITE_TYPES.NAME IS 'Наименование';



