--
-- REPL_INFO_TYPES  (Table) 
--
CREATE TABLE MASTER.REPL_INFO_TYPES
(
  ID    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(50 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPL_INFO_TYPES IS 'Типы источников';

COMMENT ON COLUMN MASTER.REPL_INFO_TYPES.ID IS 'Тип источника';

COMMENT ON COLUMN MASTER.REPL_INFO_TYPES.NAME IS 'Наименование';



