--
-- REPL_KINDS  (Table) 
--
CREATE TABLE MASTER.REPL_KINDS
(
  ID        NUMBER(10)                          NOT NULL,
  NAME      VARCHAR2(50 BYTE),
  DESCRIPT  VARCHAR2(250 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPL_KINDS IS 'Виды репликаций';

COMMENT ON COLUMN MASTER.REPL_KINDS.ID IS 'Вид репликации';

COMMENT ON COLUMN MASTER.REPL_KINDS.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.REPL_KINDS.DESCRIPT IS 'Описание';



