--
-- REPL_CALL_IN  (Table) 
--
CREATE TABLE MASTER.REPL_CALL_IN
(
  REPL_ID    NUMBER(17)                         NOT NULL,
  REPL_LIST  NUMBER(10),
  SRC_SITE   NUMBER(10),
  DST_SITE   NUMBER(10),
  REPL_DATE  DATE,
  REPL_SQL1  VARCHAR2(250 BYTE),
  REPL_SQL2  VARCHAR2(250 BYTE),
  REPL_SQL3  VARCHAR2(250 BYTE),
  OSUSER     VARCHAR2(30 BYTE),
  FILE_TYPE  NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPL_CALL_IN IS 'Таблица входящих запросов';

COMMENT ON COLUMN MASTER.REPL_CALL_IN.REPL_ID IS 'Запись в репликационной таблице';

COMMENT ON COLUMN MASTER.REPL_CALL_IN.REPL_LIST IS 'Репликация';

COMMENT ON COLUMN MASTER.REPL_CALL_IN.SRC_SITE IS 'Узел-источник';

COMMENT ON COLUMN MASTER.REPL_CALL_IN.DST_SITE IS 'Узел-назначение';

COMMENT ON COLUMN MASTER.REPL_CALL_IN.REPL_DATE IS 'Дата изменения';

COMMENT ON COLUMN MASTER.REPL_CALL_IN.REPL_SQL1 IS 'Запрос';

COMMENT ON COLUMN MASTER.REPL_CALL_IN.REPL_SQL2 IS 'Запрос';

COMMENT ON COLUMN MASTER.REPL_CALL_IN.REPL_SQL3 IS 'Запрос';

COMMENT ON COLUMN MASTER.REPL_CALL_IN.OSUSER IS 'Пользователь';

COMMENT ON COLUMN MASTER.REPL_CALL_IN.FILE_TYPE IS 'Тип транспортного файла';



