--
-- REPL_PROC_TYPES  (Table) 
--
CREATE TABLE MASTER.REPL_PROC_TYPES
(
  ID    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(50 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPL_PROC_TYPES IS 'Типы процедур обработки';

COMMENT ON COLUMN MASTER.REPL_PROC_TYPES.ID IS 'Тип процедуры обработки';

COMMENT ON COLUMN MASTER.REPL_PROC_TYPES.NAME IS 'Наименование';



