--
-- REPL_TABLE  (Table) 
--
CREATE TABLE MASTER.REPL_TABLE
(
  REPL_ID     NUMBER(17)                        NOT NULL,
  ID          NUMBER(10),
  REPL_OPER   VARCHAR2(1 BYTE),
  REPL_DATE   DATE,
  REPL_ANSW   DATE,
  REPLSTATUS  NUMBER(1)                         DEFAULT 1,
  REPL_ERROR  VARCHAR2(100 BYTE),
  REPL_LIST   NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPL_TABLE IS 'Репликационная таблица';

COMMENT ON COLUMN MASTER.REPL_TABLE.REPL_ID IS 'Запись в репликационной таблице';

COMMENT ON COLUMN MASTER.REPL_TABLE.ID IS 'Уникальный ID реплицируемой таблицы';

COMMENT ON COLUMN MASTER.REPL_TABLE.REPL_OPER IS 'Операция (I,U,D)';

COMMENT ON COLUMN MASTER.REPL_TABLE.REPL_DATE IS 'Дата операции';

COMMENT ON COLUMN MASTER.REPL_TABLE.REPL_ANSW IS 'Дата ответа';

COMMENT ON COLUMN MASTER.REPL_TABLE.REPLSTATUS IS 'Статус';

COMMENT ON COLUMN MASTER.REPL_TABLE.REPL_ERROR IS 'Ошибка';

COMMENT ON COLUMN MASTER.REPL_TABLE.REPL_LIST IS 'Репликация';



