--
-- REPL_SITE  (Table) 
--
CREATE TABLE MASTER.REPL_SITE
(
  ID         NUMBER(10)                         NOT NULL,
  NAME       VARCHAR2(50 BYTE),
  DESCRIPT   VARCHAR2(250 BYTE),
  DSN_TYPE   VARCHAR2(15 BYTE),
  CONN_STR   VARCHAR2(150 BYTE),
  DATABASE   VARCHAR2(100 BYTE),
  USERNAME   VARCHAR2(100 BYTE),
  PASSWORD   VARCHAR2(100 BYTE),
  SITE_TYPE  NUMBER(10)                         DEFAULT 2
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPL_SITE IS 'Узлы репликации';

COMMENT ON COLUMN MASTER.REPL_SITE.ID IS 'Узел репликации';

COMMENT ON COLUMN MASTER.REPL_SITE.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.REPL_SITE.DESCRIPT IS 'Описание';

COMMENT ON COLUMN MASTER.REPL_SITE.DSN_TYPE IS 'Тип источника';

COMMENT ON COLUMN MASTER.REPL_SITE.CONN_STR IS 'Строка подключения';

COMMENT ON COLUMN MASTER.REPL_SITE.DATABASE IS 'БД';

COMMENT ON COLUMN MASTER.REPL_SITE.USERNAME IS 'Пользователь';

COMMENT ON COLUMN MASTER.REPL_SITE.PASSWORD IS 'Пароль';

COMMENT ON COLUMN MASTER.REPL_SITE.SITE_TYPE IS 'Тип узла репликации';



