--
-- REPL_SESSION_LOG  (Table) 
--
CREATE TABLE MASTER.REPL_SESSION_LOG
(
  ID           NUMBER(10)                       NOT NULL,
  SESSION_ID   NUMBER(10),
  STATUS       NUMBER(10)                       DEFAULT 0,
  DESCRIPT     VARCHAR2(500 BYTE),
  LOG_TIME     DATE,
  MODULE_NAME  VARCHAR2(30 BYTE),
  SITE_RN      NUMBER(17)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPL_SESSION_LOG IS 'Журнал сессий';

COMMENT ON COLUMN MASTER.REPL_SESSION_LOG.ID IS 'ID этапа сессии';

COMMENT ON COLUMN MASTER.REPL_SESSION_LOG.SESSION_ID IS 'Сессия';

COMMENT ON COLUMN MASTER.REPL_SESSION_LOG.STATUS IS 'Статус';

COMMENT ON COLUMN MASTER.REPL_SESSION_LOG.DESCRIPT IS 'Описание';

COMMENT ON COLUMN MASTER.REPL_SESSION_LOG.LOG_TIME IS 'Дата записи в журнал';

COMMENT ON COLUMN MASTER.REPL_SESSION_LOG.MODULE_NAME IS 'Модуль приложения';

COMMENT ON COLUMN MASTER.REPL_SESSION_LOG.SITE_RN IS 'Узел, на котором произошло событие';



