--
-- REPL_FILE_TYPES  (Table) 
--
CREATE TABLE MASTER.REPL_FILE_TYPES
(
  ID         NUMBER(10)                         NOT NULL,
  TAG        VARCHAR2(15 BYTE),
  NAME       VARCHAR2(50 BYTE),
  FILE_KIND  NUMBER(10),
  FILE_MASK  VARCHAR2(20 BYTE),
  FILE_PATH  VARCHAR2(240 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPL_FILE_TYPES IS 'Типы транспортных файлов';

COMMENT ON COLUMN MASTER.REPL_FILE_TYPES.ID IS 'Тип транспортного файла';

COMMENT ON COLUMN MASTER.REPL_FILE_TYPES.TAG IS 'Префикс файла';

COMMENT ON COLUMN MASTER.REPL_FILE_TYPES.NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.REPL_FILE_TYPES.FILE_KIND IS 'Вид транспортного файла';

COMMENT ON COLUMN MASTER.REPL_FILE_TYPES.FILE_MASK IS 'Маска файла';

COMMENT ON COLUMN MASTER.REPL_FILE_TYPES.FILE_PATH IS 'Каталог';



