--
-- REPORTS_PARAM  (Table) 
--
CREATE TABLE MASTER.REPORTS_PARAM
(
  ID                      NUMBER(10)            NOT NULL,
  REPORTS_ID              NUMBER(10),
  PARAM_NAME              VARCHAR2(30 BYTE),
  PARAM_ORDER             NUMBER(10),
  PARAM_VISIBLE           NUMBER(1),
  PROC_PARAM_NAME         VARCHAR2(30 BYTE),
  PROC_PARAM_ORDER        NUMBER(10),
  MASTER_TAG              VARCHAR2(30 BYTE),
  PARUS_PROC_PARAM_NAME   VARCHAR2(30 BYTE),
  PARUS_PROC_PARAM_ORDER  NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPORTS_PARAM IS 'Параметры отчетов';

COMMENT ON COLUMN MASTER.REPORTS_PARAM.ID IS 'Параметры отчета';

COMMENT ON COLUMN MASTER.REPORTS_PARAM.REPORTS_ID IS 'Отчет';

COMMENT ON COLUMN MASTER.REPORTS_PARAM.PARAM_NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.REPORTS_PARAM.PARAM_ORDER IS 'Порядок параметров в отчете';

COMMENT ON COLUMN MASTER.REPORTS_PARAM.PARAM_VISIBLE IS 'Видимость параметра в интерфейсе';

COMMENT ON COLUMN MASTER.REPORTS_PARAM.PROC_PARAM_NAME IS 'Параметр процедуры';

COMMENT ON COLUMN MASTER.REPORTS_PARAM.PROC_PARAM_ORDER IS 'Порядок параметров в процедуре';

COMMENT ON COLUMN MASTER.REPORTS_PARAM.MASTER_TAG IS 'ТЕГ';

COMMENT ON COLUMN MASTER.REPORTS_PARAM.PARUS_PROC_PARAM_NAME IS 'Параметр процедуры из Паруса';

COMMENT ON COLUMN MASTER.REPORTS_PARAM.PARUS_PROC_PARAM_ORDER IS 'Порядок параметра процедуры из Паруса';



