--
-- REPORTS_REALIZ  (Table) 
--
CREATE TABLE MASTER.REPORTS_REALIZ
(
  ID          NUMBER(10)                        NOT NULL,
  BEGIN_DATE  DATE,
  END_DATE    DATE,
  IS_CRT      NUMBER(1)                         DEFAULT 0,
  NUM_REP     NUMBER(10),
  INN_SRC     NUMBER(12)                        DEFAULT 0,
  SRC         VARCHAR2(250 BYTE),
  REP_ROW     NUMBER(10),
  REP_CRT     NUMBER(10),
  KVIT_NUM    NUMBER(12),
  KV_DATA     DATE,
  CNTR        VARCHAR2(250 BYTE),
  INN_CNTR    NUMBER(12)                        DEFAULT 0,
  DOG_NUM     VARCHAR2(30 BYTE),
  DOG_ID      NUMBER(10),
  PLT_NUM     NUMBER(10),
  PLT_DATA    DATE,
  PROT_NUM    VARCHAR2(30 BYTE),
  TOVAR       VARCHAR2(250 BYTE),
  TOVAR_ID    NUMBER(10),
  PACK        VARCHAR2(50 BYTE),
  PACK_ID     NUMBER(10)                        DEFAULT 0,
  TOV_SRC     NUMBER(1)                         DEFAULT 0,
  TOV_CLS     NUMBER(1)                         DEFAULT 0,
  WEGHT       NUMBER(15,3)                      DEFAULT 0,
  CLR_PRC     NUMBER(15,2)                      DEFAULT 0,
  NDS         NUMBER(15,2)                      DEFAULT 0,
  AKCIZ       NUMBER(15,2)                      DEFAULT 0,
  FULL_PRC    NUMBER(15,2)                      DEFAULT 0,
  CLR_CST     NUMBER(15,2)                      DEFAULT 0,
  FULL_CST    NUMBER(15,2)                      DEFAULT 0,
  INN_RES     NUMBER(12)                        DEFAULT 0,
  RES         VARCHAR2(250 BYTE),
  STANTION    VARCHAR2(250 BYTE),
  REG_ID      NUMBER(10)                        DEFAULT 0,
  REG         VARCHAR2(250 BYTE),
  USER_SEND   VARCHAR2(30 BYTE),
  DATE_SEND   DATE,
  USERCREATE  VARCHAR2(30 BYTE),
  DATECREATE  DATE,
  BILL_ID     NUMBER(10),
  INCO1_ID    NUMBER(10),
  INCO1       VARCHAR2(50 BYTE),
  INCO2_ID    NUMBER(10),
  INCO2       VARCHAR2(30 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPORTS_REALIZ IS 'Отчет по реализации';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.ID IS 'ID';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.BEGIN_DATE IS 'С даты';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.END_DATE IS 'По дату';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.IS_CRT IS '0-отчет 1-корректировка';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.NUM_REP IS 'N отчета';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.INN_SRC IS 'ИНН предпр. представившего отчет';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.SRC IS 'Наименование предпр. представившего отчет';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.REP_ROW IS 'N строки';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.REP_CRT IS 'N отчета, к которому приводится корректировка';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.KVIT_NUM IS 'N квитанции';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.KV_DATA IS 'Дата квитанции';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.CNTR IS 'Покупатель';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.INN_CNTR IS 'ИНН покупателя';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.DOG_NUM IS 'Договор';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.DOG_ID IS 'ID договора';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.PLT_NUM IS 'N СФ';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.PLT_DATA IS 'Дата СФ';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.PROT_NUM IS 'Протокол цен';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.TOVAR IS 'Продукт';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.TOVAR_ID IS 'ID продукта';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.PACK IS 'Упаковка';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.PACK_ID IS 'ID упаковки';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.TOV_SRC IS '0-собс 1-приобр';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.TOV_CLS IS '0-н/п';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.WEGHT IS 'Вес';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.CLR_PRC IS 'цена без НДС';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.NDS IS 'НДС';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.AKCIZ IS 'ставка акциза';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.FULL_PRC IS 'цена с НДС';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.CLR_CST IS 'стоимость без НДС';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.FULL_CST IS 'стоимость с НДС';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.INN_RES IS 'ИНН получателя';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.RES IS 'Получатель';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.STANTION IS 'Станция';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.REG_ID IS 'ID регисона';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.REG IS 'Регион';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.USER_SEND IS 'Пользователь, отправивший отчет';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.DATE_SEND IS 'Дата отправки';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.USERCREATE IS 'Пользователь, сформировавший отчет';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.DATECREATE IS 'Дата формирования';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.BILL_ID IS 'ID СФ';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.INCO1_ID IS 'Пункт перехода';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.INCO1 IS 'Пункт перехода';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.INCO2_ID IS 'Условия поставки';

COMMENT ON COLUMN MASTER.REPORTS_REALIZ.INCO2 IS 'Условия поставки';



