--
-- REPORTS  (Table) 
--
CREATE TABLE MASTER.REPORTS
(
  ID               NUMBER                       NOT NULL,
  REPORT_NAME      VARCHAR2(80 BYTE),
  REPORT_FILE      VARCHAR2(30 BYTE),
  REPORT_GROUP     VARCHAR2(15 BYTE),
  SORTBY           NUMBER(5),
  PARAM1           VARCHAR2(15 BYTE),
  REPORT_TITLE     VARCHAR2(250 BYTE),
  IS_MSSQL         NUMBER(1)                    DEFAULT 0,
  IS_VIP           NUMBER(1)                    DEFAULT 0,
  COPY_FILE        VARCHAR2(100 BYTE),
  REPORT_TYPE      VARCHAR2(7 BYTE),
  DIAGRAM_TYPE     VARCHAR2(10 BYTE),
  DIAGRAM_KIND     VARCHAR2(30 BYTE),
  AXES_X_NAME      VARCHAR2(30 BYTE),
  COUNT_COLS_X     NUMBER(2)                    DEFAULT 1,
  AXES_Y_NAME      VARCHAR2(30 BYTE),
  COUNT_COLS_Y     NUMBER(2)                    DEFAULT 1,
  PROC_PACKET      VARCHAR2(30 BYTE),
  PROC_NAME        VARCHAR2(30 BYTE),
  DEF_BEG_VAL      VARCHAR2(30 BYTE),
  DEF_END_VAL      VARCHAR2(30 BYTE),
  DEF_BEG_TIME     VARCHAR2(8 BYTE),
  DEF_END_TIME     VARCHAR2(8 BYTE),
  VIEW_TIME        NUMBER(1)                    DEFAULT NULL,
  TIP_DATE         VARCHAR2(30 BYTE),
  PARUS_PROC       VARCHAR2(30 BYTE),
  REP_FORM         VARCHAR2(30 BYTE),
  LAST_NUM_REP     NUMBER(10),
  SQL_SOURCE       VARCHAR2(4000 BYTE),
  EMAIL_DBF        VARCHAR2(200 BYTE),
  ARCHIVE          VARCHAR2(100 BYTE),
  DBF_FOR_DBF      VARCHAR2(100 BYTE),
  FIELDS_NAME      VARCHAR2(1000 BYTE),
  FIELDS_SUM       VARCHAR2(100 BYTE),
  SEND_DBF         NUMBER(1)                    DEFAULT 0,
  SEND_XLS         NUMBER(1)                    DEFAULT 0,
  SEND_DBF_NAME    VARCHAR2(100 BYTE),
  DBF_FOR_XLS      VARCHAR2(100 BYTE),
  SEND_XLS_NAME    VARCHAR2(100 BYTE),
  EMAIL_XLS        VARCHAR2(200 BYTE),
  SQL_SOURCE_TYPE  VARCHAR2(3 BYTE),
  SQL_DATABASE     VARCHAR2(30 BYTE),
  SQL_USERNAME     VARCHAR2(30 BYTE),
  SQL_PASSWORD     VARCHAR2(30 BYTE),
  ZIP_DBF          NUMBER(1),
  PREPARE_XLS      NUMBER(1)                    DEFAULT 0,
  ASK_RUN_PROC     NUMBER(1)                    DEFAULT 0,
  ASK_RUN_TEXT     VARCHAR2(50 BYTE),
  SEND_CSV         NUMBER(1)                    DEFAULT 0,
  SEND_CSV_NAME    VARCHAR2(100 BYTE),
  EMAIL_CSV        VARCHAR2(200 BYTE),
  ZIP_CSV          NUMBER(1)                    DEFAULT 0,
  DOS_CODEPAGE     NUMBER(1)                    DEFAULT 1
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPORTS IS 'Отчеты';

COMMENT ON COLUMN MASTER.REPORTS.ID IS 'Отчет';

COMMENT ON COLUMN MASTER.REPORTS.REPORT_NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.REPORTS.REPORT_FILE IS 'Файл';

COMMENT ON COLUMN MASTER.REPORTS.REPORT_GROUP IS 'Группа';

COMMENT ON COLUMN MASTER.REPORTS.SORTBY IS 'Порядок';

COMMENT ON COLUMN MASTER.REPORTS.PARAM1 IS 'Параметр (будет передан в отчет)';

COMMENT ON COLUMN MASTER.REPORTS.REPORT_TITLE IS 'Заголовок';

COMMENT ON COLUMN MASTER.REPORTS.IS_MSSQL IS 'Использовать MS SQL Server';

COMMENT ON COLUMN MASTER.REPORTS.IS_VIP IS 'Для руководства';

COMMENT ON COLUMN MASTER.REPORTS.COPY_FILE IS 'Скопировать файл';

COMMENT ON COLUMN MASTER.REPORTS.REPORT_TYPE IS 'Тип отчета';

COMMENT ON COLUMN MASTER.REPORTS.DIAGRAM_TYPE IS 'Тип диаграммы';

COMMENT ON COLUMN MASTER.REPORTS.DIAGRAM_KIND IS 'Вид диаграммы';

COMMENT ON COLUMN MASTER.REPORTS.AXES_X_NAME IS 'Наименование оси X';

COMMENT ON COLUMN MASTER.REPORTS.COUNT_COLS_X IS 'Кол-во категорий по оси X';

COMMENT ON COLUMN MASTER.REPORTS.AXES_Y_NAME IS 'Наименование оси Y';

COMMENT ON COLUMN MASTER.REPORTS.COUNT_COLS_Y IS 'Кол-во категорий по оси Y';

COMMENT ON COLUMN MASTER.REPORTS.PROC_PACKET IS 'Пакет';

COMMENT ON COLUMN MASTER.REPORTS.PROC_NAME IS 'Процедура';

COMMENT ON COLUMN MASTER.REPORTS.DEF_BEG_VAL IS 'Значение по умолчанию';

COMMENT ON COLUMN MASTER.REPORTS.DEF_END_VAL IS 'Значение по умолчанию';

COMMENT ON COLUMN MASTER.REPORTS.DEF_BEG_TIME IS 'Время начала по умолчанию';

COMMENT ON COLUMN MASTER.REPORTS.DEF_END_TIME IS 'Время окончания по умолчанию';

COMMENT ON COLUMN MASTER.REPORTS.VIEW_TIME IS 'Показывать время';

COMMENT ON COLUMN MASTER.REPORTS.TIP_DATE IS 'Тип даты';

COMMENT ON COLUMN MASTER.REPORTS.PARUS_PROC IS 'Процедура из Паруса';

COMMENT ON COLUMN MASTER.REPORTS.REP_FORM IS 'Форма, которая открывается при выборе отчета';

COMMENT ON COLUMN MASTER.REPORTS.LAST_NUM_REP IS '№ последнего отправленного отчета';

COMMENT ON COLUMN MASTER.REPORTS.SQL_SOURCE IS 'Запрос на отбор данных для отчета';

COMMENT ON COLUMN MASTER.REPORTS.EMAIL_DBF IS 'Список адресов для отправки DBF-файла';

COMMENT ON COLUMN MASTER.REPORTS.ARCHIVE IS 'Каталог, в котором сохраняются отправленные файлы';

COMMENT ON COLUMN MASTER.REPORTS.DBF_FOR_DBF IS 'Шаблон файла DBF для формирования и отсылки DBF';

COMMENT ON COLUMN MASTER.REPORTS.FIELDS_NAME IS 'Наименования полей (через ;)';

COMMENT ON COLUMN MASTER.REPORTS.FIELDS_SUM IS 'Поля, по которым нужны итоги (через ;)';

COMMENT ON COLUMN MASTER.REPORTS.SEND_DBF IS 'Кнопка "Отправить DBF-файл"';

COMMENT ON COLUMN MASTER.REPORTS.SEND_XLS IS 'Кнопка "Отправить XLS-файл"';

COMMENT ON COLUMN MASTER.REPORTS.SEND_DBF_NAME IS 'Правила наименования файла для отправки DBF-файла';

COMMENT ON COLUMN MASTER.REPORTS.DBF_FOR_XLS IS 'Шаблон файла DBF для формирования и отсылки XLS';

COMMENT ON COLUMN MASTER.REPORTS.SEND_XLS_NAME IS 'Правила наименования файла для отправки XLS';

COMMENT ON COLUMN MASTER.REPORTS.EMAIL_XLS IS 'Список адресов для отправки XLS-файла';

COMMENT ON COLUMN MASTER.REPORTS.SQL_SOURCE_TYPE IS 'Тип запроса';

COMMENT ON COLUMN MASTER.REPORTS.SQL_DATABASE IS 'БД';

COMMENT ON COLUMN MASTER.REPORTS.SQL_USERNAME IS 'Пользователь';

COMMENT ON COLUMN MASTER.REPORTS.SQL_PASSWORD IS 'Пароль';

COMMENT ON COLUMN MASTER.REPORTS.ZIP_DBF IS 'Упаковывать DBF-файл';

COMMENT ON COLUMN MASTER.REPORTS.PREPARE_XLS IS 'Кнопка "Сформировать XLS-файл"';

COMMENT ON COLUMN MASTER.REPORTS.ASK_RUN_PROC IS 'Запрашивать запуск процедуры';

COMMENT ON COLUMN MASTER.REPORTS.ASK_RUN_TEXT IS 'Текст при запросе запуска процедуры';

COMMENT ON COLUMN MASTER.REPORTS.SEND_CSV IS 'Кнопка "Отправить CSV-файл"';

COMMENT ON COLUMN MASTER.REPORTS.SEND_CSV_NAME IS 'Правила наименования файла для отправки CSV-файла';

COMMENT ON COLUMN MASTER.REPORTS.EMAIL_CSV IS 'Список адресов для отправки CSV-файла';

COMMENT ON COLUMN MASTER.REPORTS.ZIP_CSV IS 'Упаковывать CSV-файл';

COMMENT ON COLUMN MASTER.REPORTS.DOS_CODEPAGE IS '1-Кодовая страница DOS';



