--
-- REPORT_GROUPS  (Table) 
--
CREATE TABLE MASTER.REPORT_GROUPS
(
  ID                 NUMBER                     NOT NULL,
  REPORT_GROUP       VARCHAR2(15 BYTE),
  REPORT_GROUP_NAME  VARCHAR2(80 BYTE),
  SORTBY             NUMBER(2),
  REP_KIND           VARCHAR2(30 BYTE),
  VIEW_TAB           VARCHAR2(15 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPORT_GROUPS IS 'Группы отчетов';

COMMENT ON COLUMN MASTER.REPORT_GROUPS.ID IS 'Группа отчетов';

COMMENT ON COLUMN MASTER.REPORT_GROUPS.REPORT_GROUP IS 'Мнемокод';

COMMENT ON COLUMN MASTER.REPORT_GROUPS.REPORT_GROUP_NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.REPORT_GROUPS.SORTBY IS 'Порядок сортировки (для записей с одинаковым REP_KIND)';

COMMENT ON COLUMN MASTER.REPORT_GROUPS.REP_KIND IS 'Принадлежность к подразделению';

COMMENT ON COLUMN MASTER.REPORT_GROUPS.VIEW_TAB IS 'Страница параметров';



