--
-- REPORTS_NUM_REP  (Table) 
--
CREATE TABLE MASTER.REPORTS_NUM_REP
(
  REP_ID      NUMBER(10),
  BEGIN_DATE  DATE,
  END_DATE    DATE,
  IS_CRT      NUMBER(1)                         DEFAULT 0,
  NUM_REP     NUMBER(10)                        DEFAULT 0
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.REPORTS_NUM_REP IS 'Нумерация отчетов';

COMMENT ON COLUMN MASTER.REPORTS_NUM_REP.REP_ID IS 'Отчет';

COMMENT ON COLUMN MASTER.REPORTS_NUM_REP.BEGIN_DATE IS 'С даты';

COMMENT ON COLUMN MASTER.REPORTS_NUM_REP.END_DATE IS 'По дату';

COMMENT ON COLUMN MASTER.REPORTS_NUM_REP.IS_CRT IS 'Признак корректировки';

COMMENT ON COLUMN MASTER.REPORTS_NUM_REP.NUM_REP IS 'Номер отчета';



