--
-- SAIO_CHECK  (Table) 
--
CREATE TABLE MASTER.SAIO_CHECK
(
  OUTPUTFILE   VARCHAR2(10 BYTE)                NOT NULL,
  SELECTQUERY  VARCHAR2(914 BYTE),
  CREATEQUERY  VARCHAR2(100 BYTE),
  IS_ACTIVE    NUMBER(1)                        DEFAULT 0
)
TABLESPACE USERS2
NOCOMPRESS ;


