--
-- SF_SIGNS  (Table) 
--
CREATE TABLE MASTER.SF_SIGNS
(
  BOSS           VARCHAR2(50 BYTE),
  BLAVBUH        VARCHAR2(50 BYTE),
  TERMINAL_NAME  VARCHAR2(30 BYTE),
  USER_NAME      VARCHAR2(30 BYTE),
  SF_DOVER_ID    NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.SF_SIGNS.TERMINAL_NAME IS 'Терминал';

COMMENT ON COLUMN MASTER.SF_SIGNS.USER_NAME IS 'Пользователь';



