--
-- SOOB_EXP  (Table) 
--
CREATE TABLE MASTER.SOOB_EXP
(
  ID            NUMBER                          NOT NULL,
  REP_DATE      DATE,
  POS_ID        NUMBER,
  SORTBY        NUMBER,
  DOG_ID        NUMBER,
  PROD_ID_NPR   VARCHAR2(5 BYTE),
  STAN_ID       NUMBER,
  EXPED_ID      NUMBER,
  LOAD_TYPE_ID  NUMBER,
  FACT_YEAR     NUMBER,
  PLAN_POST     NUMBER,
  PLAN_IZM      NUMBER,
  OBPR          NUMBER,
  PLAN_GD       NUMBER,
  NORMA_MON     NUMBER,
  FACT_MON      NUMBER,
  FACT_SUT      NUMBER,
  IS_BAD        NUMBER(1),
  PRICH         VARCHAR2(100 BYTE),
  ZAPR_MPS      VARCHAR2(250 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;


