--
-- STAN_PREDPR  (Table) 
--
CREATE TABLE MASTER.STAN_PREDPR
(
  PREDPR_ID     NUMBER(6),
  STAN_ID       NUMBER(10),
  VETKA_ID      NUMBER(4),
  PREDPR_GDKOD  VARCHAR2(12 BYTE),
  IS_MAIN       NUMBER(1)                       DEFAULT 0,
  ID            NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.STAN_PREDPR IS 'Терминалы';

COMMENT ON COLUMN MASTER.STAN_PREDPR.PREDPR_ID IS 'Предприятие';

COMMENT ON COLUMN MASTER.STAN_PREDPR.STAN_ID IS 'Станция';

COMMENT ON COLUMN MASTER.STAN_PREDPR.VETKA_ID IS 'Ветка';

COMMENT ON COLUMN MASTER.STAN_PREDPR.PREDPR_GDKOD IS 'ж/д код';

COMMENT ON COLUMN MASTER.STAN_PREDPR.IS_MAIN IS 'Основной терминал';

COMMENT ON COLUMN MASTER.STAN_PREDPR.ID IS 'Терминал';



