--
-- SVED  (Table) 
--
CREATE TABLE MASTER.SVED
(
  ID              VARCHAR2(9 BYTE)              NOT NULL,
  FLG_OPERDATA    NUMBER(1)                     DEFAULT 1                     NOT NULL,
  SVED_NUM        NUMBER(10),
  SVED_DATE       DATE,
  SVED_VES        NUMBER(15,6)                  DEFAULT 0,
  SVED_CNT        NUMBER(5)                     DEFAULT 0,
  GOTOV_TIME      DATE,
  BEG_NALIV_TIME  DATE,
  END_NALIV_TIME  DATE,
  DATE_OFORML     DATE,
  NARIAD_ID       NUMBER(10),
  PASP_ID         VARCHAR2(9 BYTE),
  PROD_ID_NPR     VARCHAR2(5 BYTE),
  MESTO_ID        NUMBER(10),
  DATE_EDIT       DATE,
  NOM_ZD          VARCHAR2(12 BYTE),
  LOAD_TYPE_ID    NUMBER(10),
  TECH_TIME       DATE,
  PASP_NUM        VARCHAR2(15 BYTE),
  REZ_NUM         VARCHAR2(15 BYTE),
  VES_CIST        NUMBER(12,3)                  DEFAULT 0,
  KOL_NET         NUMBER(14,5)                  DEFAULT 0,
  VES_ALL         NUMBER(12,3)                  DEFAULT 0,
  FROM_DBF        NUMBER(1)                     DEFAULT 0,
  DEFI_MASS_ID    NUMBER(10),
  CENA            NUMBER(10,2),
  CENA_OTP        NUMBER(10,2),
  DATE_CENA       DATE,
  PASP_DATE       DATE,
  POD_DATE        DATE
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.SVED IS 'Сведение об отгрузке/наливе';

COMMENT ON COLUMN MASTER.SVED.ID IS 'ID сведения';

COMMENT ON COLUMN MASTER.SVED.FLG_OPERDATA IS 'Признак оперативной отгрузки';

COMMENT ON COLUMN MASTER.SVED.SVED_NUM IS '№ сведения';

COMMENT ON COLUMN MASTER.SVED.SVED_DATE IS 'Дата сведения';

COMMENT ON COLUMN MASTER.SVED.SVED_VES IS 'Чистый вес';

COMMENT ON COLUMN MASTER.SVED.SVED_CNT IS 'Кол-во';

COMMENT ON COLUMN MASTER.SVED.GOTOV_TIME IS 'Комерческая годность';

COMMENT ON COLUMN MASTER.SVED.BEG_NALIV_TIME IS 'Начало погрузки';

COMMENT ON COLUMN MASTER.SVED.END_NALIV_TIME IS 'Окончание погрузки';

COMMENT ON COLUMN MASTER.SVED.DATE_OFORML IS 'Окончание оформления';

COMMENT ON COLUMN MASTER.SVED.NARIAD_ID IS 'Наряд/разрешение';

COMMENT ON COLUMN MASTER.SVED.PASP_ID IS 'Паспорт';

COMMENT ON COLUMN MASTER.SVED.PROD_ID_NPR IS 'Продукт';

COMMENT ON COLUMN MASTER.SVED.MESTO_ID IS 'Место отгрузки';

COMMENT ON COLUMN MASTER.SVED.DATE_EDIT IS 'Последняя дата редактирования';

COMMENT ON COLUMN MASTER.SVED.NOM_ZD IS 'Заявка';

COMMENT ON COLUMN MASTER.SVED.LOAD_TYPE_ID IS 'Тип транспортировки';

COMMENT ON COLUMN MASTER.SVED.TECH_TIME IS 'Техническая годность';

COMMENT ON COLUMN MASTER.SVED.PASP_NUM IS '№ паспорта';

COMMENT ON COLUMN MASTER.SVED.REZ_NUM IS '№ резервуара';

COMMENT ON COLUMN MASTER.SVED.VES_CIST IS 'Вес вагона';

COMMENT ON COLUMN MASTER.SVED.KOL_NET IS 'Вес НЕТТО (нефти)';

COMMENT ON COLUMN MASTER.SVED.VES_ALL IS 'Вес вагона и упаковки';

COMMENT ON COLUMN MASTER.SVED.FROM_DBF IS 'Признак загрузки из DBF';

COMMENT ON COLUMN MASTER.SVED.DEFI_MASS_ID IS 'Метод определения веса';

COMMENT ON COLUMN MASTER.SVED.CENA IS 'Цена без налогов';

COMMENT ON COLUMN MASTER.SVED.CENA_OTP IS 'Цена отпускная';

COMMENT ON COLUMN MASTER.SVED.DATE_CENA IS 'Дата начала действия цены';

COMMENT ON COLUMN MASTER.SVED.PASP_DATE IS 'Дата паспорта';

COMMENT ON COLUMN MASTER.SVED.POD_DATE IS 'Дата/время подачи';



