--
-- T_SNPORDEXP_UPLOADORD_KSE  (Table) 
--
CREATE TABLE MASTER.T_SNPORDEXP_UPLOADORD_KSE
(
  UPLOADID  NUMBER(17),
  ORDERID   NUMBER(10),
  LOAD_VES  NUMBER(16,6)
)
TABLESPACE USERS
NOCOMPRESS ;


