--
-- TEMP_PAYMENTS_PROD  (Table) 
--
CREATE TABLE MASTER.TEMP_PAYMENTS_PROD
(
  OSUSER_NAME    VARCHAR2(50 BYTE),
  TERMINAL_NAME  VARCHAR2(50 BYTE),
  PAYMENTS_ID    NUMBER                         NOT NULL,
  PROD_ID_NPR    VARCHAR2(5 BYTE)               NOT NULL
)
TABLESPACE USERS2
NOCOMPRESS ;


