--
-- TEMP_UVED  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE MASTER.TEMP_UVED
(
  UVED_POS        NUMBER(10),
  REESTR_ID       NUMBER(10),
  NOM_ZD          VARCHAR2(12 BYTE),
  STAN_NAME       VARCHAR2(50 BYTE),
  POLUCH_NAME     VARCHAR2(30 BYTE),
  NUM_CIST        VARCHAR2(10 BYTE),
  VAGOWNER_NAME   VARCHAR2(50 BYTE),
  VES             NUMBER(14,3),
  DATE_OFORML     DATE,
  PROD_NAME       VARCHAR2(30 BYTE),
  SVED_NUM        NUMBER(10),
  POD_NUM         NUMBER(10),
  VETKA_OTP_NAME  VARCHAR2(30 BYTE),
  SVED_POS        NUMBER(10),
  SVED_DATE       DATE,
  PASP_NUM        VARCHAR2(20 BYTE),
  VAG_STATUS      VARCHAR2(30 BYTE),
  NAKL_NUM        NUMBER(10),
  VES_ALL         NUMBER(14,3),
  VES_CIST        NUMBER(14,3),
  VES_UPAK        NUMBER(14,3)
)
ON COMMIT PRESERVE ROWS;

COMMENT ON TABLE MASTER.TEMP_UVED IS 'Временная таблица для формирования уведомления об уборке';



