--
-- TEMP_REESTR_PARAMS  (Table) 
--
CREATE TABLE MASTER.TEMP_REESTR_PARAMS
(
  TERMINAL_NAME    VARCHAR2(30 BYTE)            NOT NULL,
  OSUSER_NAME      VARCHAR2(30 BYTE)            NOT NULL,
  DATE_PLAN        DATE,
  DATETIME_REPORT  DATE
)
TABLESPACE USERS2
NOCOMPRESS ;


