--
-- TEMP_PAYMENTS_TO_BILLS  (Table) 
--
CREATE TABLE MASTER.TEMP_PAYMENTS_TO_BILLS
(
  OSUSER_NAME    VARCHAR2(50 BYTE),
  TERMINAL_NAME  VARCHAR2(50 BYTE),
  PAYMENTS_ID    NUMBER,
  NOM_DOK        NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


