--
-- TEST  (Table) 
--
CREATE TABLE MASTER.TEST
(
  ID    NUMBER(10)                              NOT NULL,
  NAME  VARCHAR2(100 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.TEST.ID IS 'ID';

COMMENT ON COLUMN MASTER.TEST.NAME IS 'Наименование';



