--
-- TOAD_PLAN_SQL  (Table) 
--
CREATE TABLE MASTER.TOAD_PLAN_SQL
(
  USERNAME      VARCHAR2(30 BYTE),
  STATEMENT_ID  VARCHAR2(32 BYTE),
  TIMESTAMP     DATE,
  STATEMENT     VARCHAR2(2000 BYTE)
)
TABLESPACE USERS
NOCOMPRESS ;


