--
-- USL_DOG  (Table) 
--
CREATE TABLE MASTER.USL_DOG
(
  DOG_ID            NUMBER(5)                   NOT NULL,
  USL_NUMBER        NUMBER(3)                   NOT NULL,
  USL_NAME          VARCHAR2(75 BYTE),
  USL_BEGIN_DATE    DATE,
  USL_END_DATE      DATE,
  VID_USL_ID        NUMBER(2),
  PAYDELAY_ID       NUMBER(2),
  PAYDELAY_DATE     DATE,
  KOL_DN            NUMBER(4),
  USL_AKT           NUMBER(1),
  USL_UTV           NUMBER(1),
  USL_BAZ           NUMBER(1),
  PROC_PRED         NUMBER(3),
  PROC_PENI         NUMBER(5,2),
  PROC_INSURE       NUMBER(5,2),
  NEUST             NUMBER(4,1),
  USL_SUM           NUMBER(6,2),
  PAYFORM_ID        NUMBER(2),
  CAT_CEN_ID        NUMBER(3),
  ID                NUMBER(10),
  NPOCAT_CEN_ID     NUMBER(3),
  R3_NUM_ISP        VARCHAR2(10 BYTE),
  USL_SUM_AREND     NUMBER(6,2),
  ISU_KOD_DOG_TEST  VARCHAR2(13 BYTE),
  ISU_KOD_DOG       VARCHAR2(13 BYTE)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.USL_DOG.DOG_ID IS 'Договор';

COMMENT ON COLUMN MASTER.USL_DOG.USL_NUMBER IS 'Условие';

COMMENT ON COLUMN MASTER.USL_DOG.USL_NAME IS 'Наименование';

COMMENT ON COLUMN MASTER.USL_DOG.USL_BEGIN_DATE IS 'С даты';

COMMENT ON COLUMN MASTER.USL_DOG.USL_END_DATE IS 'По дату';

COMMENT ON COLUMN MASTER.USL_DOG.VID_USL_ID IS 'Вид условия';

COMMENT ON COLUMN MASTER.USL_DOG.PAYDELAY_ID IS 'Вид отсрочки';

COMMENT ON COLUMN MASTER.USL_DOG.PAYDELAY_DATE IS 'отсрочка до определенной даты';

COMMENT ON COLUMN MASTER.USL_DOG.KOL_DN IS 'число дней отсрочки';

COMMENT ON COLUMN MASTER.USL_DOG.USL_AKT IS 'Актуально';

COMMENT ON COLUMN MASTER.USL_DOG.USL_UTV IS 'Утверждено';

COMMENT ON COLUMN MASTER.USL_DOG.USL_BAZ IS 'Базовое';

COMMENT ON COLUMN MASTER.USL_DOG.PROC_PRED IS 'процент предоплаты';

COMMENT ON COLUMN MASTER.USL_DOG.PROC_PENI IS 'процент пени';

COMMENT ON COLUMN MASTER.USL_DOG.PROC_INSURE IS 'процент страховки';

COMMENT ON COLUMN MASTER.USL_DOG.NEUST IS 'размер неустойки';

COMMENT ON COLUMN MASTER.USL_DOG.USL_SUM IS 'Руб. с тонны';

COMMENT ON COLUMN MASTER.USL_DOG.PAYFORM_ID IS 'Вид оплаты';

COMMENT ON COLUMN MASTER.USL_DOG.CAT_CEN_ID IS 'Категория цены';

COMMENT ON COLUMN MASTER.USL_DOG.ID IS 'ID';

COMMENT ON COLUMN MASTER.USL_DOG.NPOCAT_CEN_ID IS 'Категория цены при продаже';

COMMENT ON COLUMN MASTER.USL_DOG.R3_NUM_ISP IS 'Направление R3';

COMMENT ON COLUMN MASTER.USL_DOG.USL_SUM_AREND IS 'Руб. с тонны за аренд.вагоны';

COMMENT ON COLUMN MASTER.USL_DOG.ISU_KOD_DOG_TEST IS 'Код договора из ИСУ Переработка (тестовая база)';

COMMENT ON COLUMN MASTER.USL_DOG.ISU_KOD_DOG IS 'Код договора из ИСУ Переработка (продуктив)';



