--
-- VED_OSMOTR_ROW  (Table) 
--
CREATE TABLE MASTER.VED_OSMOTR_ROW
(
  ID             NUMBER(10)                     NOT NULL,
  VED_ID         NUMBER(10),
  POD_DATE       DATE,
  NUM_CIST       VARCHAR2(10 BYTE),
  KALIBR_ID      VARCHAR2(5 BYTE),
  RAZMET_PER     VARCHAR2(50 BYTE),
  F_OST          NUMBER(1)                      DEFAULT 0,
  PRIM           VARCHAR2(50 BYTE),
  POD_POS        NUMBER(10),
  PROD_ID_NPR    VARCHAR2(6 BYTE),
  VAGOWNER_ID    NUMBER(10),
  CAPACITY       VARCHAR2(10 BYTE),
  NCISTDOP       NUMBER(2),
  AXES           NUMBER(2),
  VES_CIST       NUMBER(10,3),
  VAGONTYPE_ID   NUMBER(10),
  BAD_NUM        NUMBER(1)                      DEFAULT 0,
  VAG_STATUS_ID  NUMBER(10)                     DEFAULT 0,
  GOST1510       NUMBER(1)                      DEFAULT 1
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.VED_OSMOTR_ROW IS 'Позиции ведомости предварительного осмотра';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.VED_ID IS 'Ведомость';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.POD_DATE IS 'Дата/время подхода';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.NUM_CIST IS '№ цистерны';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.KALIBR_ID IS 'Тип';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.RAZMET_PER IS 'Разметка по пересылке';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.F_OST IS 'Наличие остатка';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.PRIM IS 'Примечание';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.POD_POS IS '№ п/п';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.PROD_ID_NPR IS 'Под какой продукт годен';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.VAGOWNER_ID IS 'Владелец вагона';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.CAPACITY IS 'Грузоподъемность';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.NCISTDOP IS 'Признак дорог СНГ';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.AXES IS 'Осность';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.VES_CIST IS 'Вес вагона';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.VAGONTYPE_ID IS 'Род вагона';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.BAD_NUM IS '1-Неверный номер';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.VAG_STATUS_ID IS 'Статус вагона';

COMMENT ON COLUMN MASTER.VED_OSMOTR_ROW.GOST1510 IS 'Подготовка под налив по ГОСТ 1510';



