--
-- VED_OSMOTR_SMENA  (Table) 
--
CREATE TABLE MASTER.VED_OSMOTR_SMENA
(
  NAME  VARCHAR2(50 BYTE),
  ID    NUMBER(10)                              NOT NULL
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.VED_OSMOTR_SMENA IS 'Справочник операторов';



