--
-- VED_POD_ROW  (Table) 
--
CREATE TABLE MASTER.VED_POD_ROW
(
  ID                 NUMBER(10)                 NOT NULL,
  VED_POD_ID         NUMBER(10),
  POD_POS            NUMBER(10),
  RAZMET_FACT        VARCHAR2(30 BYTE),
  NUM_CIST           VARCHAR2(10 BYTE),
  NCISTDOP           NUMBER(2),
  AXES               NUMBER(2),
  CAPACITY           VARCHAR2(10 BYTE),
  VES_CIST           NUMBER(10,3)               DEFAULT 0,
  VAGONTYPE_ID       NUMBER(10),
  KALIBR_ID          VARCHAR2(5 BYTE),
  VAGOWNER_ID        NUMBER(10),
  VETKA_POD_ID       NUMBER(10),
  VETKA_NAPR_ID      NUMBER(10),
  VAG_STATUS_ID      NUMBER(10),
  PROD_ID_NPR        VARCHAR2(5 BYTE),
  VZLIV              NUMBER(10),
  TEMPER             NUMBER(6,1),
  VOLUME             NUMBER(10)                 DEFAULT 0,
  BAD_NUM            NUMBER(1)                  DEFAULT 0,
  ZPU_TYPE1          NUMBER(10),
  ZPU_TYPE2          NUMBER(10),
  PLOMBA1            VARCHAR2(15 BYTE),
  PLOMBA2            VARCHAR2(15 BYTE),
  ROSINSPL1          VARCHAR2(15 BYTE),
  ROSINSPL2          VARCHAR2(15 BYTE),
  VED_OSMOTR_ROW_ID  NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.VED_POD_ROW IS 'Позиции ведомости подачи';

COMMENT ON COLUMN MASTER.VED_POD_ROW.ID IS 'Позиции ведомости подачи';

COMMENT ON COLUMN MASTER.VED_POD_ROW.VED_POD_ID IS 'Ведомость подачи';

COMMENT ON COLUMN MASTER.VED_POD_ROW.POD_POS IS '№ п/п';

COMMENT ON COLUMN MASTER.VED_POD_ROW.RAZMET_FACT IS 'Разметка под груз';

COMMENT ON COLUMN MASTER.VED_POD_ROW.NUM_CIST IS 'Номер цистерны';

COMMENT ON COLUMN MASTER.VED_POD_ROW.NCISTDOP IS 'Признак дорог СНГ';

COMMENT ON COLUMN MASTER.VED_POD_ROW.AXES IS 'Оси';

COMMENT ON COLUMN MASTER.VED_POD_ROW.CAPACITY IS 'Грузоподъемность';

COMMENT ON COLUMN MASTER.VED_POD_ROW.VES_CIST IS 'Вес вагона';

COMMENT ON COLUMN MASTER.VED_POD_ROW.VAGONTYPE_ID IS 'Род вагона';

COMMENT ON COLUMN MASTER.VED_POD_ROW.KALIBR_ID IS 'Тип вагона';

COMMENT ON COLUMN MASTER.VED_POD_ROW.VAGOWNER_ID IS 'Собственник/владелец вагона';

COMMENT ON COLUMN MASTER.VED_POD_ROW.VETKA_POD_ID IS 'Путь подачи';

COMMENT ON COLUMN MASTER.VED_POD_ROW.VETKA_NAPR_ID IS 'Направление вывода';

COMMENT ON COLUMN MASTER.VED_POD_ROW.VAG_STATUS_ID IS 'Состояние вагона';

COMMENT ON COLUMN MASTER.VED_POD_ROW.PROD_ID_NPR IS 'Продукт';

COMMENT ON COLUMN MASTER.VED_POD_ROW.VZLIV IS 'Взлив';

COMMENT ON COLUMN MASTER.VED_POD_ROW.TEMPER IS 'Температура';

COMMENT ON COLUMN MASTER.VED_POD_ROW.VOLUME IS 'Объем';

COMMENT ON COLUMN MASTER.VED_POD_ROW.BAD_NUM IS '1-Неверный номер';

COMMENT ON COLUMN MASTER.VED_POD_ROW.ZPU_TYPE1 IS 'Тип пломбы 1';

COMMENT ON COLUMN MASTER.VED_POD_ROW.ZPU_TYPE2 IS 'Тип пломбы 2';

COMMENT ON COLUMN MASTER.VED_POD_ROW.PLOMBA1 IS 'Пломба 1';

COMMENT ON COLUMN MASTER.VED_POD_ROW.PLOMBA2 IS 'Пломба 2';

COMMENT ON COLUMN MASTER.VED_POD_ROW.ROSINSPL1 IS 'Пломба Росинспектората 1';

COMMENT ON COLUMN MASTER.VED_POD_ROW.ROSINSPL2 IS 'Пломба Росинспектората 2';

COMMENT ON COLUMN MASTER.VED_POD_ROW.VED_OSMOTR_ROW_ID IS 'ID позиции ведомости предварительного осмотра';



