--
-- VED_OSMOTR  (Table) 
--
CREATE TABLE MASTER.VED_OSMOTR
(
  ID            NUMBER(10)                      NOT NULL,
  VED_NUM       NUMBER(10),
  VED_DATE      DATE,
  FROM_DATE     DATE,
  TO_DATE       DATE,
  FIO1          VARCHAR2(50 BYTE),
  FIO2          VARCHAR2(50 BYTE),
  FIO3          VARCHAR2(50 BYTE),
  SIGN1         VARCHAR2(50 BYTE),
  MESTO_ID      NUMBER(10)                      DEFAULT 1,
  VED_PREFIX    VARCHAR2(10 BYTE),
  LOAD_TYPE_ID  NUMBER(10)                      DEFAULT 1,
  KOL           NUMBER(5)                       DEFAULT 0
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.VED_OSMOTR IS 'Ведомость предварительного осмотра';

COMMENT ON COLUMN MASTER.VED_OSMOTR.VED_NUM IS '№ ведомости';

COMMENT ON COLUMN MASTER.VED_OSMOTR.VED_DATE IS 'Дата ведомости';

COMMENT ON COLUMN MASTER.VED_OSMOTR.FROM_DATE IS 'С даты';

COMMENT ON COLUMN MASTER.VED_OSMOTR.TO_DATE IS 'По дату';

COMMENT ON COLUMN MASTER.VED_OSMOTR.FIO1 IS 'Смена: ФИО 1';

COMMENT ON COLUMN MASTER.VED_OSMOTR.FIO2 IS 'Смена: ФИО 2';

COMMENT ON COLUMN MASTER.VED_OSMOTR.FIO3 IS 'Смена: ФИО 3';

COMMENT ON COLUMN MASTER.VED_OSMOTR.SIGN1 IS 'Подпись 1';

COMMENT ON COLUMN MASTER.VED_OSMOTR.MESTO_ID IS 'Место отгрузки';

COMMENT ON COLUMN MASTER.VED_OSMOTR.VED_PREFIX IS 'Префикс номера';

COMMENT ON COLUMN MASTER.VED_OSMOTR.LOAD_TYPE_ID IS 'Тип транспортировки';

COMMENT ON COLUMN MASTER.VED_OSMOTR.KOL IS 'Кол-во вагонов';



