--
-- VED_OSMOTR_PODPIS  (Table) 
--
CREATE TABLE MASTER.VED_OSMOTR_PODPIS
(
  NAME  VARCHAR2(50 BYTE),
  ID    NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.VED_OSMOTR_PODPIS IS 'Справочник подписей';



