--
-- VOZVRAT  (Table) 
--
CREATE TABLE MASTER.VOZVRAT
(
  ID          NUMBER(10)                        NOT NULL,
  NUM_CIST    VARCHAR2(10 BYTE),
  NUM_KVIT    NUMBER(12),
  NUM_NAKL    VARCHAR2(12 BYTE),
  DATE_NAKL   DATE,
  DATE_VOZ    DATE,
  TIME_VOZ    VARCHAR2(6 BYTE),
  DATE_RASK   DATE,
  TARIF       NUMBER(14,3),
  SUMMA       NUMBER(14,2),
  NUM_AKT     VARCHAR2(10 BYTE),
  NUM_PERECH  VARCHAR2(10 BYTE),
  DAT_PERECH  DATE,
  VOZVRAT     NUMBER(1),
  FLG_KVIT    NUMBER(1),
  OLD_KVIT    NUMBER(12),
  SF_POROJN   VARCHAR2(10 BYTE),
  DAT_POROJN  DATE,
  SOBST       NUMBER(1),
  PRSTBETW1   DATE,
  PRSTBETT1   VARCHAR2(5 BYTE),
  PRSTBETW2   DATE,
  PRSTBETT2   VARCHAR2(5 BYTE),
  PRSTBETSF   VARCHAR2(10 BYTE),
  STAN_ID     NUMBER(10),
  PRST_N_AKT  VARCHAR2(15 BYTE),
  PRST_S_AKT  NUMBER(12,2),
  PRIM        VARCHAR2(50 BYTE),
  DATE_OTP    DATE,
  TIME_OTP    VARCHAR2(6 BYTE),
  OTSTOI      NUMBER(2),
  DATE_REP    DATE,
  DATE_EDIT   DATE,
  DATE_KVIT   DATE,
  KVIT_ID     NUMBER(10)
)
TABLESPACE USERS2
NOCOMPRESS ;


