--
-- VOZVRAT_TEMP  (Table) 
--
CREATE TABLE MASTER.VOZVRAT_TEMP
(
  NUM_AKT    VARCHAR2(10 BYTE),
  USER_NAME  VARCHAR2(30 BYTE),
  NUM_KVIT   VARCHAR2(10 BYTE),
  NUM_CIST   NUMBER,
  DATE_KVIT  DATE,
  PRIZNAK    NUMBER
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON COLUMN MASTER.VOZVRAT_TEMP.PRIZNAK IS '1 - для отчета, 2 - для новых или редактирования';



