--
-- XX101_MONTH  (Table) 
--
CREATE TABLE MASTER.XX101_MONTH
(
  NOM_ZD            VARCHAR2(12 BYTE),
  STANOTP_ID        NUMBER(10),
  NPR_SOBSTV_ID     NUMBER(6),
  STAN_ID           NUMBER(10),
  VETKA_ID          NUMBER(4),
  POLUCH_ID         NUMBER(6),
  TEX_PD_ID         NUMBER(7),
  NAZN_OTG_ID       NUMBER(2),
  LOAD_ABBR         VARCHAR2(3 BYTE),
  DOG_ID            NUMBER(5),
  USL_NUMBER        NUMBER(3),
  GOSPROG_ID        NUMBER(2),
  PROD_ID_NPR       VARCHAR2(5 BYTE),
  TONN_DECLARED     NUMBER(10,3),
  TONN_LOADED       NUMBER(10,3),
  CIST_DECLARED     NUMBER(4),
  CIST_LOADED       NUMBER(4),
  FLG_ALLOW_8_AXES  NUMBER(1),
  FLG_UPPER_SLIV    NUMBER(1),
  FLG_DOP_CIST      NUMBER(1),
  FLG_FORMA_2       NUMBER(10),
  FLG_OBOGR         NUMBER(1),
  DATE_PLAN         DATE,
  PRIM              VARCHAR2(100 BYTE),
  CENA              NUMBER(15,6),
  CENA_OTP          NUMBER(15,6),
  SUM_ZD            NUMBER(12,2),
  GR4               VARCHAR2(100 BYTE),
  K_TAR             VARCHAR2(10 BYTE),
  INPUT_DATE        DATE,
  UPDATE_DATE       DATE,
  TARIF1TONN        NUMBER(10,2)                DEFAULT 0,
  POTREB_ID         NUMBER(6),
  PLANSTRU_ID       NUMBER(20),
  NPODOG_ID         NUMBER(5),
  GROTP_ID          NUMBER(6)                   DEFAULT 0,
  DATE_CEN          DATE,
  GP_NAPR_ID        NUMBER(10),
  TONN_R            NUMBER(15,6)                DEFAULT 0,
  CIST_R            NUMBER(4)                   DEFAULT 0,
  TRANSPORT         VARCHAR2(20 BYTE),
  IS_EXP            NUMBER(1)                   DEFAULT 0,
  SUPPLIER_ID       NUMBER(6),
  APPL_TAG          VARCHAR2(6 BYTE),
  CENA_NPO          NUMBER(15,6)                DEFAULT 0,
  CENA_OTP_NPO      NUMBER(15,6)                DEFAULT 0,
  KOL_DN_NPO        NUMBER(3),
  TONN_RAZNAR       NUMBER(10,3),
  CIST_RAZNAR       NUMBER(10,3),
  ZAKAZ_ID          NUMBER(10),
  EXPED_ID          NUMBER(6),
  GU12_A_ID         NUMBER(10),
  ZAKAZ_HIST_ID     NUMBER(10),
  POKUP_DOG_ID      NUMBER(10),
  POKUP_USL_NUMBER  NUMBER(3),
  NAPR_POST_ID      NUMBER(10),
  CIST_FACT         NUMBER(5)                   DEFAULT 0,
  TONN_FACT         NUMBER(10,3)                DEFAULT 0,
  STAN_PER_ID       NUMBER(10),
  INCOTERM_ID       NUMBER(10),
  VZISK_ID          NUMBER(10)
)
TABLESPACE USERS
NOCOMPRESS ;


