--
-- XX101_ZPOSTAV  (Table) 
--
CREATE TABLE MASTER.XX101_ZPOSTAV
(
  WAYBILLID     VARCHAR2(16 BYTE),
  WAYBILLROWID  VARCHAR2(16 BYTE),
  NUM_CIST      VARCHAR2(10 BYTE),
  DATE_OTGR     DATE
)
TABLESPACE USERS
NOCOMPRESS ;


