--
-- XX101_ZRAZNAR  (Table) 
--
CREATE TABLE MASTER.XX101_ZRAZNAR
(
  ORDERNUM    VARCHAR2(16 BYTE)                 NOT NULL,
  BEGIN_DATE  DATE,
  END_DATE    DATE
)
TABLESPACE USERS
NOCOMPRESS ;


