--
-- ZAKAZ_GRAFIK  (Table) 
--
CREATE TABLE MASTER.ZAKAZ_GRAFIK
(
  ID             NUMBER(10)                     NOT NULL,
  ZAKAZ_HIST_ID  NUMBER(10),
  DATE_LOAD      DATE,
  TONN_LOAD      NUMBER(16,6)                   DEFAULT 0,
  CIST_LOAD      NUMBER(10)                     DEFAULT 0
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.ZAKAZ_GRAFIK IS 'График отгрузки';

COMMENT ON COLUMN MASTER.ZAKAZ_GRAFIK.ZAKAZ_HIST_ID IS 'Ссылка на позицию заказа "К отгрузке"';

COMMENT ON COLUMN MASTER.ZAKAZ_GRAFIK.DATE_LOAD IS 'Дата отгрузки';

COMMENT ON COLUMN MASTER.ZAKAZ_GRAFIK.TONN_LOAD IS 'Отгрузить тн';

COMMENT ON COLUMN MASTER.ZAKAZ_GRAFIK.CIST_LOAD IS 'Отгрузить вц';



