--
-- ZAKAZ_TEMP  (Table) 
--
CREATE TABLE MASTER.ZAKAZ_TEMP
(
  TERMINAL_NAME     VARCHAR2(30 BYTE),
  USER_NAME         VARCHAR2(30 BYTE),
  IS_AGENT          NUMBER(2),
  KIND_VALUE        NUMBER(2),
  FILIAL_ID         NUMBER(10),
  PROD_ID_NPR       VARCHAR2(5 BYTE),
  PARUS_NOMEN_TAG   VARCHAR2(20 BYTE),
  PLAT_ID           NUMBER(10),
  PARUS_AGENT_TAG   VARCHAR2(20 BYTE),
  DOG_ID            NUMBER(10),
  PARUS_DOGOVOR     VARCHAR2(30 BYTE),
  PROD_NAME         VARCHAR2(200 BYTE),
  PLAN_NB           NUMBER(15,3),
  PLAN_AZS          NUMBER(15,3),
  PLAN_TRAN         NUMBER(15,3),
  PLAN_VNCORPTR     NUMBER(15,3),
  PLAN_OTHER        NUMBER(15,3),
  PLAN_PROD         NUMBER(15,3),
  PLAN_DOG          NUMBER(15,3),
  ZAYV_ALL_PROD     NUMBER(15,3),
  ZAYV_ACCEPT_PROD  NUMBER(15,3),
  ZAYV_FACT_PROD    NUMBER(15,3),
  ZAYV_ALL_PLAT     NUMBER(15,3),
  ZAYV_ACCEPT_PLAT  NUMBER(15,3),
  ZAYV_FACT_PLAT    NUMBER(15,3),
  ZAYV_ALL_DOG      NUMBER(15,3),
  ZAYV_ACCEPT_DOG   NUMBER(15,3),
  ZAYV_FACT_DOG     NUMBER(15,3),
  SALDO             NUMBER(16,2)
)
TABLESPACE LOADER
NOCOMPRESS ;

COMMENT ON TABLE MASTER.ZAKAZ_TEMP IS '¬ременна€ таблица дл€ заказов потребителей';



