--
-- ZAKAZ_GRAFIK_TEMP  (Table) 
--
CREATE TABLE MASTER.ZAKAZ_GRAFIK_TEMP
(
  TERMINAL_NAME  VARCHAR2(30 BYTE),
  USER_NAME      VARCHAR2(30 BYTE),
  DATE_LOAD      DATE,
  TONN_LOAD      NUMBER(16,6)                   DEFAULT 0,
  CIST_LOAD      NUMBER(10)                     DEFAULT 0
)
TABLESPACE LOADER
NOCOMPRESS ;

COMMENT ON TABLE MASTER.ZAKAZ_GRAFIK_TEMP IS 'Временная таблица для графика отгрузки';



