--
-- ZAKAZ_PARUS  (Table) 
--
CREATE TABLE MASTER.ZAKAZ_PARUS
(
  PARUS_RN          NUMBER(17),
  DATE_PLAN         DATE,
  CLIENT_NUMBER     VARCHAR2(50 BYTE),
  CLIENT_DATE       DATE,
  INPUT_NUMBER      VARCHAR2(50 BYTE),
  INPUT_DATE        DATE,
  IS_ACCEPT         NUMBER(1)                   DEFAULT 0,
  FILIAL_ID         NUMBER(10),
  PARUS_AGENT_RN    NUMBER(17),
  PARUS_AGENT_TAG   VARCHAR2(20 BYTE),
  PARUS_AGENT_NAME  VARCHAR2(200 BYTE),
  PARUS_DOGOVOR     VARCHAR2(30 BYTE),
  PARUS_NOMEN_RN    NUMBER(17),
  PARUS_NOMEN_TAG   VARCHAR2(20 BYTE),
  PARUS_NOMEN_NAME  VARCHAR2(200 BYTE),
  PARUS_MODIF_RN    NUMBER(17),
  PARUS_MODIF_TAG   VARCHAR2(20 BYTE),
  PARUS_MODIF_NAME  VARCHAR2(200 BYTE),
  USL_OPL_ID        NUMBER(10),
  POLUCH_NAME       VARCHAR2(200 BYTE),
  POTREB_NAME       VARCHAR2(200 BYTE),
  NEFTEBASA         VARCHAR2(50 BYTE),
  PRICE_CLIENT      NUMBER(12,5)                DEFAULT NULL,
  PRICE             NUMBER(12,5)                DEFAULT NULL,
  VES               NUMBER(16,6)                DEFAULT 0,
  FACT_VES          NUMBER(16,6)                DEFAULT 0,
  PRIM              VARCHAR2(100 BYTE),
  IS_WORK           NUMBER(1)                   DEFAULT 1,
  LOAD_ABBR         VARCHAR2(10 BYTE),
  PARUS_PRN         NUMBER(17)
)
TABLESPACE USERS2
NOCOMPRESS ;

COMMENT ON TABLE MASTER.ZAKAZ_PARUS IS 'Заказы потребителей (ПАРУС)';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.PARUS_RN IS 'Ссылка на заявку из Паруса';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.DATE_PLAN IS 'Дата плана';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.CLIENT_NUMBER IS 'Исходящий номер клиента';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.CLIENT_DATE IS 'Исходящяя дата';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.INPUT_NUMBER IS 'Рег.номер';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.INPUT_DATE IS 'Дата регистрации';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.IS_ACCEPT IS 'Утвержден';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.FILIAL_ID IS 'Филиал';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.PARUS_AGENT_RN IS 'Плательщик по договору (Парус)';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.PARUS_AGENT_TAG IS 'Плательщик по договору (Парус)';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.PARUS_AGENT_NAME IS 'Плательщик по договору (Парус)';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.PARUS_DOGOVOR IS 'Договор (Парус)';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.PARUS_NOMEN_RN IS 'Продукт (Парус)';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.PARUS_NOMEN_TAG IS 'Продукт (Парус)';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.PARUS_NOMEN_NAME IS 'Продукт (Парус)';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.PARUS_MODIF_RN IS 'Модификация (Парус)';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.PARUS_MODIF_TAG IS 'Модицикация (Парус)';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.PARUS_MODIF_NAME IS 'Модификация (Парус)';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.USL_OPL_ID IS 'Условия оплаты';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.POLUCH_NAME IS 'Получатель';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.POTREB_NAME IS 'Потребитель';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.NEFTEBASA IS 'Склад (нефтебаза)';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.PRICE_CLIENT IS 'Цена клиента';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.PRICE IS 'Цена продажи';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.VES IS 'Заказанный объем';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.FACT_VES IS 'Фактически отгружено';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.PRIM IS 'Причина';

COMMENT ON COLUMN MASTER.ZAKAZ_PARUS.IS_WORK IS 'К отгрузке';



