--
-- GET_SEQ_LOCAL  (Function) 
--
CREATE OR REPLACE FUNCTION SNP_REPL.GET_SEQ_LOCAL
  RETURN VARCHAR2 IS
Res NUMBER;  
BEGIN
  SELECT SEQ_REPL_LOCAL.nextval INTO Res FROM DUAL;
  RETURN Res;
END;
/


