--
-- GET_SEQ_GLOBAL  (Function) 
--
CREATE OR REPLACE FUNCTION SNP_REPL.GET_SEQ_GLOBAL
  RETURN VARCHAR2 IS
Res NUMBER;  
BEGIN
  SELECT SEQ_REPL_GLOBAL.nextval INTO Res FROM DUAL;
  RETURN Res;
END;
/


