--
-- TRG_BIUDR_REPL_TABLE  (Trigger) 
--
CREATE OR REPLACE TRIGGER SNP_REPL.TRG_BIUDR_REPL_TABLE
 BEFORE DELETE OR INSERT OR UPDATE ON SNP_REPL.REPL_TABLE  FOR EACH ROW
BEGIN
  IF INSERTING() THEN
    IF :NEW.RN=0 OR :NEW.RN IS NULL THEN
      :NEW.RN:=Get_Seq_Global();
    END IF;
  END IF;
  IF INSERTING() OR UPDATING() THEN
	IF :NEW.USERNAME||' '=' ' THEN
	  :NEW.USERNAME:=NLS_UPPER(:NEW.REPL_USERNAME);
	END IF;
	IF :NEW.TABLENAME||' '=' ' THEN
	  :NEW.TABLENAME:=NLS_UPPER(:NEW.REPL_TABLENAME);
	END IF;
	IF :NEW.NOTE||' '=' ' OR
	   NLS_UPPER(:NEW.NOTE)||' '=NLS_UPPER(:OLD.USERNAME||'.'||:OLD.TABLENAME)||' ' THEN
	  :NEW.NOTE:=NLS_UPPER(:NEW.USERNAME||'.'||:NEW.TABLENAME);
	END IF;
  END IF;
END;
/


