--
-- TRG_BIUDR_REPL_SITE  (Trigger) 
--
CREATE OR REPLACE TRIGGER SNP_REPL.TRG_BIUDR_REPL_SITE
 BEFORE DELETE OR INSERT OR UPDATE ON SNP_REPL.REPL_SITE  FOR EACH ROW
BEGIN
  IF INSERTING() THEN
    IF :NEW.RN=0 OR :NEW.RN IS NULL THEN
      :NEW.RN:=Get_Seq_Global();
    END IF;
  END IF;
  IF INSERTING() OR UPDATING() THEN	
	-- Добавление строки в REPL_INIT
	UPDATE REPL_INIT SET SITE_RN=:NEW.RN WHERE SITE_RN=:NEW.RN;
	IF SQL%NOTFOUND THEN
	  INSERT INTO REPL_INIT (SITE_RN) VALUES(:NEW.RN);
	END IF;
  END IF;
  IF DELETING() THEN
    -- Удаление строки из REPL_INIT
	DELETE FROM REPL_INIT WHERE SITE_RN=:OLD.RN;
  END IF;
END;
/


