--
-- TRG_BIUDR_REPL_SCHEMA  (Trigger) 
--
CREATE OR REPLACE TRIGGER SNP_REPL.TRG_BIUDR_REPL_SCHEMA
 BEFORE DELETE OR INSERT OR UPDATE ON SNP_REPL.REPL_SCHEMA  FOR EACH ROW
BEGIN
  IF INSERTING() THEN
    IF :NEW.RN=0 OR :NEW.RN IS NULL THEN
      :NEW.RN:=Get_Seq_Global();
    END IF;
  END IF;
END;
/


