-- 
-- Non Foreign Key Constraints for Table CATALOG_LIST 
-- 
ALTER TABLE SNP_REPL.CATALOG_LIST ADD (
  CONSTRAINT CATALOG_LIST_PK
  PRIMARY KEY
  (DOC_TYPE, CRN)
  USING INDEX SNP_REPL.CATALOG_LIST_PK);

