-- 
-- Non Foreign Key Constraints for Table ENVIRONMENT_GRP 
-- 
ALTER TABLE SNP_REPL.ENVIRONMENT_GRP ADD (
  CONSTRAINT ENV_GRP_PK
  PRIMARY KEY
  (ID)
  USING INDEX SNP_REPL.ENV_GRP_PK);

ALTER TABLE SNP_REPL.ENVIRONMENT_GRP ADD (
  CONSTRAINT ENV_GRP_ENV_GRP_AK_UK
  UNIQUE (GRP_NAME)
  USING INDEX SNP_REPL.ENV_GRP_ENV_GRP_AK_UK);

