-- 
-- Non Foreign Key Constraints for Table REPL_SCHEMA 
-- 
ALTER TABLE SNP_REPL.REPL_SCHEMA ADD (
  CONSTRAINT REPL_SCHEMA_PK
  PRIMARY KEY
  (SITE_SOURCE_RN, SITE_DEST_RN, RN)
  USING INDEX SNP_REPL.REPL_SCHEMA_PK);

