-- 
-- Foreign Key Constraints for Table REPL_SCHEMA 
-- 
ALTER TABLE SNP_REPL.REPL_SCHEMA ADD (
  CONSTRAINT SCHEMA_REPL_SITE_DEST_FK 
  FOREIGN KEY (SITE_DEST_RN) 
  REFERENCES SNP_REPL.REPL_SITE (RN));

ALTER TABLE SNP_REPL.REPL_SCHEMA ADD (
  CONSTRAINT SCHEMA_REPL_SITE_SOURCE_FK 
  FOREIGN KEY (SITE_SOURCE_RN) 
  REFERENCES SNP_REPL.REPL_SITE (RN));

