-- 
-- Non Foreign Key Constraints for Table REPL_CALL_OUT_HIST 
-- 
ALTER TABLE SNP_REPL.REPL_CALL_OUT_HIST ADD (
  CHECK ("RN" IS NOT NULL));

ALTER TABLE SNP_REPL.REPL_CALL_OUT_HIST ADD (
  CHECK ("SITE_SOURCE_RN" IS NOT NULL));

ALTER TABLE SNP_REPL.REPL_CALL_OUT_HIST ADD (
  CHECK ("SITE_DEST_RN" IS NOT NULL));

ALTER TABLE SNP_REPL.REPL_CALL_OUT_HIST ADD (
  CHECK ("SCHEMA_RN" IS NOT NULL));

ALTER TABLE SNP_REPL.REPL_CALL_OUT_HIST ADD (
  CHECK ("SCHEMAROW_RN" IS NOT NULL));

ALTER TABLE SNP_REPL.REPL_CALL_OUT_HIST ADD (
  CHECK ("TABLERN" IS NOT NULL));

ALTER TABLE SNP_REPL.REPL_CALL_OUT_HIST ADD (
  CHECK ("REPL_RN" IS NOT NULL));

ALTER TABLE SNP_REPL.REPL_CALL_OUT_HIST ADD (
  CHECK ("OPERATION" IS NOT NULL));

ALTER TABLE SNP_REPL.REPL_CALL_OUT_HIST ADD (
  CHECK ("MODIFDATE" IS NOT NULL));

ALTER TABLE SNP_REPL.REPL_CALL_OUT_HIST ADD (
  CHECK ("COUNTER" IS NOT NULL));

ALTER TABLE SNP_REPL.REPL_CALL_OUT_HIST ADD (
  CHECK ("STATUS" IS NOT NULL));

ALTER TABLE SNP_REPL.REPL_CALL_OUT_HIST ADD (
  CHECK ("SQL1_TEXT" IS NOT NULL));

ALTER TABLE SNP_REPL.REPL_CALL_OUT_HIST ADD (
  CONSTRAINT REPL_CALL_OUT_HIST_PK
  PRIMARY KEY
  (SITE_SOURCE_RN, SITE_DEST_RN, RN)
  USING INDEX SNP_REPL.REPL_CALL_OUT_HIST_PK);

