-- 
-- Non Foreign Key Constraints for Table REPL_SCHEMA_ROW 
-- 
ALTER TABLE SNP_REPL.REPL_SCHEMA_ROW ADD (
  CONSTRAINT REPL_SCHEMA_ROW_PK
  PRIMARY KEY
  (RN)
  USING INDEX SNP_REPL.REPL_SCHEMA_ROW_PK);

ALTER TABLE SNP_REPL.REPL_SCHEMA_ROW ADD (
  CONSTRAINT REPL_SCHEMA_ROW_UK
  UNIQUE (SITE_SOURCE_RN, SITE_DEST_RN, SCHEMA_RN, TABLE_SOURCE_RN)
  USING INDEX SNP_REPL.REPL_SCHEMA_ROW_UK);

