-- 
-- Foreign Key Constraints for Table REPL_SCHEMA_ROW 
-- 
ALTER TABLE SNP_REPL.REPL_SCHEMA_ROW ADD (
  CONSTRAINT REPL_SCHEMAROW_TABLE_DEST_FK 
  FOREIGN KEY (TABLE_DEST_RN) 
  REFERENCES SNP_REPL.REPL_TABLE (RN));

ALTER TABLE SNP_REPL.REPL_SCHEMA_ROW ADD (
  CONSTRAINT REPL_SCHEMAROW_TABLE_SOURCE_FK 
  FOREIGN KEY (TABLE_SOURCE_RN) 
  REFERENCES SNP_REPL.REPL_TABLE (RN));

ALTER TABLE SNP_REPL.REPL_SCHEMA_ROW ADD (
  CONSTRAINT SCHEMA_ROW_REPL_SCHEMA_FK 
  FOREIGN KEY (SITE_SOURCE_RN, SITE_DEST_RN, SCHEMA_RN) 
  REFERENCES SNP_REPL.REPL_SCHEMA (SITE_SOURCE_RN,SITE_DEST_RN,RN));

