--
-- AZS_REPORTS_TMP_AK  (Index) 
--
CREATE UNIQUE INDEX MASTER.AZS_REPORTS_TMP_AK ON MASTER.AZS_REPORTS_TMP
(OSUSER_NAME, TERMINAL_NAME, ORG_STRU_ID, PROD_ID_NPR, TYPE_OPER_ID, 
DISCOUNT, OPER_DAY, PRICE)
TABLESPACE USERSINDX;


