--
-- EUL_HS_HS1_UK  (Index) 
--
CREATE UNIQUE INDEX MASTER.EUL_HS_HS1_UK ON MASTER.EUL_HI_SEGMENTS
(IHS_HN_ID_CHILD, IHS_HN_ID_PARENT, IHS_HI_ID, DHS_HI_ID, DHS_DHN_ID_CHILD, 
DHS_DHN_ID_PARENT)
TABLESPACE USERSINDX;


