--
-- MONTH_I_DOG_ID_PROD_ID_NPR_STA  (Index) 
--
CREATE INDEX MASTER.MONTH_I_DOG_ID_PROD_ID_NPR_STA ON MASTER.MONTH
(DOG_ID, PROD_ID_NPR, STAN_ID, PLANSTRU_ID, POLUCH_ID, 
NPODOG_ID, NOM_ZD, DATE_PLAN)
TABLESPACE USERSINDX;


