--
-- PK_V_TEMP_PAYMENTS_TO_BILLS  (Index) 
--
CREATE UNIQUE INDEX MASTER.PK_V_TEMP_PAYMENTS_TO_BILLS ON MASTER.TEMP_PAYMENTS_TO_BILLS
(OSUSER_NAME, TERMINAL_NAME, PAYMENTS_ID, NOM_DOK)
TABLESPACE USERSINDX;


