--
-- PLANSTRU_PLANSTRU_AK_UK  (Index) 
--
CREATE UNIQUE INDEX MASTER.PLANSTRU_PLANSTRU_AK_UK ON MASTER.KLS_PLANSTRU
(LEVEL_POS, KOD_SGR, KOD_SPG, KOD_RZD, KOD_PRZ, 
KOD_GRP, KOD_PGR)
TABLESPACE USERSINDX;


