--
-- REPORTS_REALIZ_UK  (Index) 
--
CREATE UNIQUE INDEX MASTER.REPORTS_REALIZ_UK ON MASTER.REPORTS_REALIZ
(BEGIN_DATE, END_DATE, IS_CRT, BILL_ID, KVIT_NUM, 
TOV_SRC, TOVAR_ID)
TABLESPACE USERSINDX;


