--
-- SVED_UK  (Index) 
--
CREATE UNIQUE INDEX MASTER.SVED_UK ON MASTER.SVED
(MESTO_ID, DECODE("FROM_DBF",1,"ID"||TO_CHAR("FLG_OPERDATA"),'0'), TRUNC("SVED_DATE",'fmyyyy'), SVED_NUM)
TABLESPACE USERSINDX;


