--
-- ZAKAZ_TEMP_MASTER_PROD_I  (Index) 
--
CREATE INDEX MASTER.ZAKAZ_TEMP_MASTER_PROD_I ON MASTER.ZAKAZ_TEMP
(TERMINAL_NAME, USER_NAME, IS_AGENT, KIND_VALUE, FILIAL_ID, 
PROD_ID_NPR, PLAT_ID, DOG_ID)
TABLESPACE LOADERINDX;


