--
-- UNP_SPRAV_OIL_PRODUCT  (Materialized View) 
--
CREATE MATERIALIZED VIEW MASTER.UNP_SPRAV_OIL_PRODUCT 
TABLESPACE USERS2
NOCOMPRESS
BUILD IMMEDIATE
USING INDEX
            TABLESPACE USERSINDX
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
SELECT "SPRAV_OIL_PRODUCT"."KOD_OIL_PRODUCT" "KOD_OIL_PRODUCT","SPRAV_OIL_PRODUCT"."NAME_OIL_PRODUCT" "NAME_OIL_PRODUCT","SPRAV_OIL_PRODUCT"."KOD_SERTIFICAT" "KOD_SERTIFICAT","SPRAV_OIL_PRODUCT"."GOST" "GOST","SPRAV_OIL_PRODUCT"."KOD_KATEGORY" "KOD_KATEGORY","SPRAV_OIL_PRODUCT"."PRIMECHANIE" "PRIMECHANIE","SPRAV_OIL_PRODUCT"."OKP" "OKP","SPRAV_OIL_PRODUCT"."OLD" "OLD","SPRAV_OIL_PRODUCT"."PRIMECHANIE1" "PRIMECHANIE1" FROM "PASP"."SPRAV_OIL_PRODUCT"@ORA.LUNP.RU "SPRAV_OIL_PRODUCT"
;


COMMENT ON MATERIALIZED VIEW MASTER.UNP_SPRAV_OIL_PRODUCT IS 'snapshot table for snapshot MASTER.UNP_SPRAV_OIL_PRODUCT';
