--
-- UNP_SPRAV_POKAZATEL  (Materialized View) 
--
CREATE MATERIALIZED VIEW MASTER.UNP_SPRAV_POKAZATEL 
TABLESPACE USERS2
NOCOMPRESS
BUILD IMMEDIATE
USING INDEX
            TABLESPACE USERSINDX
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
select a.*,1 as ttt from pasp.SPRAV_POKAZATEL@ora.lunp.ru a

;


COMMENT ON MATERIALIZED VIEW MASTER.UNP_SPRAV_POKAZATEL IS 'snapshot table for snapshot MASTER.UNP_SPRAV_POKAZATEL';
