--
-- UNP_FACT_PASP  (Materialized View) 
--
CREATE MATERIALIZED VIEW MASTER.UNP_FACT_PASP 
TABLESPACE USERS2
NOCOMPRESS
BUILD IMMEDIATE
USING INDEX
            TABLESPACE USERSINDX
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
SELECT "FACT_PASP"."ID_FACT_PASP" "ID_FACT_PASP","FACT_PASP"."ID_PASPORT" "ID_PASPORT","FACT_PASP"."KOD_POKAZATEL" "KOD_POKAZATEL","FACT_PASP"."FACT_PASP" "FACT_PASP","FACT_PASP"."TEXT_VAL" "TEXT_VAL","FACT_PASP"."GARANT" "GARANT","FACT_PASP"."PRIMECHANIE" "PRIMECHANIE" FROM "PASP"."FACT_PASP"@ORA.LUNP.RU "FACT_PASP"
;


COMMENT ON MATERIALIZED VIEW MASTER.UNP_FACT_PASP IS 'snapshot table for snapshot MASTER.UNP_FACT_PASP';
