--
-- SNP_REPL  (User) 
--
CREATE USER SNP_REPL
  IDENTIFIED BY VALUES '58B998B1C474276C'
  DEFAULT TABLESPACE PARUSREPL
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 4 Roles for SNP_REPL 
  GRANT CONNECT TO SNP_REPL;
  GRANT RESOURCE TO SNP_REPL;
  GRANT EXP_FULL_DATABASE TO SNP_REPL;
  GRANT IMP_FULL_DATABASE TO SNP_REPL;
  ALTER USER SNP_REPL DEFAULT ROLE ALL;
  -- 10 System Privileges for SNP_REPL 
  GRANT DELETE ANY TABLE TO SNP_REPL WITH ADMIN OPTION;
  GRANT INSERT ANY TABLE TO SNP_REPL WITH ADMIN OPTION;
  GRANT SELECT ANY TABLE TO SNP_REPL WITH ADMIN OPTION;
  GRANT UPDATE ANY TABLE TO SNP_REPL WITH ADMIN OPTION;
  GRANT DROP PUBLIC SYNONYM TO SNP_REPL;
  GRANT UNLIMITED TABLESPACE TO SNP_REPL;
  GRANT CREATE PUBLIC SYNONYM TO SNP_REPL;
  GRANT SELECT ANY DICTIONARY TO SNP_REPL WITH ADMIN OPTION;
  GRANT DROP PUBLIC DATABASE LINK TO SNP_REPL;
  GRANT CREATE PUBLIC DATABASE LINK TO SNP_REPL;
  -- 3 Tablespace Quotas for SNP_REPL 
  ALTER USER SNP_REPL QUOTA UNLIMITED ON PARUS00;
  ALTER USER SNP_REPL QUOTA UNLIMITED ON TEMP;
  ALTER USER SNP_REPL QUOTA UNLIMITED ON PARUSREPL;


