--
-- LOADER  (Tablespace) 
--
CREATE TABLESPACE LOADER DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\LOADER01.DBF' SIZE 1000M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
NOLOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


