--
-- LOADERINDX  (Tablespace) 
--
CREATE TABLESPACE LOADERINDX DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\LOADERINDX01.DBF' SIZE 1100M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


