--
-- TEMP  (Tablespace) 
--
CREATE TEMPORARY TABLESPACE TEMP TEMPFILE 
  'E:\ORACLE\MASTER\ORADATA\TEMP01.ORA' SIZE 16000M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


