--
-- USERS2  (Tablespace) 
--
CREATE TABLESPACE USERS2 DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\USERS02.DBF' SIZE 8300M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


