--
-- USERS  (Tablespace) 
--
CREATE TABLESPACE USERS DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\USERS01.DBF' SIZE 5350M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


