--
-- USERSINDX  (Tablespace) 
--
CREATE TABLESPACE USERSINDX DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\USERSINDX01.DBF' SIZE 5000M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


